### ISSUE TITLE
I can not choose drive by number

### ISSUE THREAD

**Issue by JanuszChmiel** [archlinux/archinstall#1000]
Dear specialists,
Archinstall Python installer would be ideal installer for ArchLinux users. Unfortunately, I Am currently helpless to choose drive name by using number. Only default option is usable but if I want to choose for example SDA drive by typing number 1 installer refuses to accept such number. I have tested this behaviour by using Notebook with UEFI and also on virtual machines in two BIOS or legacy modes.
I AM using latest archinstall Python installer available on The latest Arch Linux installation live .iso file.
Please how can I install ArchLinux to The wanted drive???

**Comment by JanuszChmiel** [comment]
Dear Mr taylor,
Thank you very much for so fast reaction on my reported issue.
I Am also very sad, why such interesting problem was happened. But really. Installer refuse to continue when I choose for example number 2. Sure, I really type number 2 and I press Enter. But installer report error message. Default choice choose RAm target which cause other error later but it is not bug of installer. It would be so excellent installer for visually impaired Arch Linux users. I have really used two other phxysical computers. Two are using UEFI system and I have also tried Vmware player on its default setting to BIOS. But I have used UEFFI mode on VMware player but without results.
I Am very sad, because I like Arch Linux so much. And asA paradox, I could try it as A distro by installing it to Android non rooted device. But when I want to install it on a regular PC there is always some issues
Installer inform Me about installed drives correctly. And I know number based installers from Debian NEt inst.

**Comment by Torxed** [comment]
@JanuszChmiel Would it be possible for you to film this with a mobile phone and upload a short video of the problem?
Or use a tool like [giph](https://github.com/phisch/giph) made by phisch here in this community.

It would help a lot to figure out what's going wrong :)

**Comment by JanuszChmiel** [comment]
I boot by using accessibility option for visually impaired users. But I hope, that loaded Speakup kernel module in to RAm and The fact, that espeakup communicate with this kernel module and send its output to The Espeak-ng which send data to Alsa sound server should not cause such problem. I will try to record a video.

**Comment by svartkanin** [comment]
@Torxed I think this was for the old menu, but shouldn't be an issue anymore since we migraged to the new one

**Comment by Torxed** [comment]
Agreed :) Good thing we got this new nice menu :D
