### ISSUE TITLE
Save current configuration

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#1002]
I'd like to add a new menu option to save the current configuration to file. 
I imaged it as a simple
```
Install (3 config(s) missing)                                                                                                                                
Save configuration
Abort             
```

and then specifying a filename when clicking on it

**Comment by Torxed** [comment]
Sounds good. its a bit more clear than `--dry-run` and since we now store it neatly in a next-gen (buzzzz) menu system, it makes perfect sense :)

**Comment by wllacer** [comment]
Great idea. You can use and extend the `output_configs` routine at *configurations.py*

**Comment by wllacer** [comment]
@svartkanin  How do you limit the number of options shown in the menu? 
Btw. we would need some kind of visual clue that more options are available.

**Comment by wllacer** [comment]
No. The last one is profiles.
I have to move with the cursor down to get at the end.
and i have a lot of free space in my terminal ...

**Comment by Torxed** [comment]
@svartkanin I think wllacer is referring to this:

![archinstall](https://user-images.githubusercontent.com/861439/156076634-9dd18d13-4d57-4d84-a1f8-a7c2085b4def.gif)

**Comment by svartkanin** [comment]
Ohh wow I did not see that behavior on mine :O
My first assumption is that the preview takes too much space, that's an easy fix

**Comment by OJFord** [comment]
Or/also have `--dry-run` create a file. A naive installer otherwise reaches the end and then gets only last part of the JSON document on screen, the rest disappeared with no scrollback.

Log/interactive messages also go to stdout (seems wrong itself), so you also can't `archinstall --dry-run > config.json`. If you `| tee config.json` then of course it's not a JSON file without first removing all the prompts and responses from the beginning, and it runs in a unpaged/non-interactive/curses-less way.

**Comment by Torxed** [comment]
> Or/also have `--dry-run` create a file. A naive installer otherwise reaches the end and then gets only last part of the JSON document on screen, the rest disappeared with no scrollback.
> 
> Log/interactive messages also go to stdout (seems wrong itself), so you also can't `archinstall --dry-run > config.json`. If you `| tee config.json` then of course it's not a JSON file without first removing all the prompts and responses from the beginning, and it runs in a unpaged/non-interactive/curses-less way.

`--dry-run` saves the configuration. if it doesnt its a bug :) No need to pipe anything, files are created under /var/log/archinstall

**Comment by OJFord** [comment]
@Torxed Oh, it probably did then, no bug. .. Except in docs? i.e How should I know that? Would be good to put it in `--help`:

> `--dry-run` Run the wizard without applying the selected configuration, which is instead saved to `/var/log/archinstall/config.json`

Anyway, that's tangential here :)

**Comment by Torxed** [comment]
agreed :)
