### ISSUE TITLE
Flake8 fails because of random mistake

### ISSUE THREAD

**Issue by Samisafool** [archlinux/archinstall#1011]
https://github.com/archlinux/archinstall/commit/537b9cab037aecfd18edef156dd3ea55072918e9#diff-6951dbb399883798a226c1fb496fdb4183b1ab48865e75eddecf6ceb6cf46442L9-R9

You can see here, that it failed because of a merge

**Comment by Torxed** [comment]
Ah thank you! : ) Pesky little miss hehe.

**Comment by Torxed** [comment]
Fixed in https://github.com/archlinux/archinstall/commit/04e3880d8f41a87889690609e20ab1220700c163

**Comment by Samisafool** [comment]
![image](https://user-images.githubusercontent.com/59611020/156015130-196fd92d-76fc-4070-be81-dec9a3e806e7.png)

Might wanna fix this too...

**Comment by Torxed** [comment]
> Might wanna fix this too...

It's the same key as I'm using usually. Just don't know why github insists on thinking it's unverified.
Will have to check that tomorrow.

**Comment by Torxed** [comment]
Bloody hell. Assumed this would be a tricky issue, but you're right :)
**Thank you**, had no idea git *had* to have the email match the key.
I'm using `signingkey` to sign I assumed, and the rest would be optional.

**Comment by Samisafool** [comment]
Github kinda pointed that out in the screenshot... Don't tell me you're one of those people who don't read error messages????

**Comment by Torxed** [comment]
> Github kinda pointed that out in the screenshot... Don't tell me you're one of those people who don't

I was literally merging while running ^^ Was already 45min late so didn't pay much attention no ^^
