### ISSUE TITLE
[master] Cannot select/enter super-users (TypeError: GlobalMenu._setup_selection_menu_options)

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1013]
![screenshot](https://user-images.githubusercontent.com/861439/156018652-83a31d43-07b4-4e3d-bd6d-09d59c0e99dd.jpg)

@wllacer / @svartkanin I think I bodged a PR. I think your help would solve this faster than I can.
If you're busy, that's fine - I'll try again tomorrow.

**Comment by bebetoalves** [comment]
Maybe it's because of #993 ?

**Comment by Torxed** [comment]
> Naw. It was just a parameter definition at a lambda, which went missing during the merges ... Apropos. the password weakness check (#983) almost drove me crazy the first time i saw it. Good feature but a PITA for tests ;-)

Speaking of which, we should make sure that doesn't trigger if `--advanced` or something is given. And especially `--silent`.
