### ISSUE TITLE
Multiple network configuration

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#1020]
As discussed in https://github.com/archlinux/archinstall/pull/1001 we decided to upgrade the current network config from a single to a multiple configuration option for the interfaces. With the work from @wllacer 's `ListWidget` that should be quite nice! 

I'll get it kicked off asap!

**Comment by wllacer** [comment]
Daniel. 
I have following changes to ListManager planned:
* Ability to define a header row or equivalent
* Ability to have multiple Default Actions (the ones below the list, to be executed for the list and not for one particular item
* Ability to define specific sort routines to the list 
None seems specially dificult, but they were low in my to-do list. If you think you could need them for the network management, i will be glad to implement them for you as soon as i am able
