### ISSUE TITLE
NTP configuration setting being ignored

### ISSUE THREAD

**Issue by asininemonkey** [archlinux/archinstall#1022]
I have `"ntp": false` defined in `user_configuration.json` in favour of `systemd-timesyncd` as a service. Unfortunately this is always ignored and the following prompted at install:

```
Would you like to use automatic time synchronization (NTP) with the default time servers? [Y/n]
```

Is this an overisght? This last worked for me on the Nov 2021 release of the Arch ISO.

**Comment by Torxed** [comment]
should work, so if this is true its a bug :) will check it out!

**Comment by ABotelho23** [comment]
It's definitely being ignored as well fr me.

I'm also wondering what value I should be setting for optional parameters to have it not prompt about them. I tried null, but it still asks me. Notably for "users" and "profile".

**Comment by svartkanin** [comment]
@Torxed this should work as well :)
