### ISSUE TITLE
Root and home partitions with wrong size in some partition sizes

### ISSUE THREAD

**Issue by hexarch** [archlinux/archinstall#1024]
Below is an example of the size of root and home partitions for 10, 20, 40, 60 and a 120GB hard disk.

For the 10GB, there is no home, but / has 9.5GB. That is ok.
For the 20GB, there is no home, but / has 19.5GB. That is ok.
For the 40GB, / has 36.8GB and /home is 2.7GB. This is wrong.
For the 60GB, / has 36.8GB and /home is 22.7GB. This is also wrong, makes no sense.
For the 120GB, / has 36.8GB and /home is 82.7GB. 

We see a pattern here and only the first two examples are ok. The script should ask what you want.

1. you want one partition, root and home in same volume?
2. you want your home on another location?

Script owner should decide what questions to make but at least make one option to put all into / and home included.

![archinstall-multiple-hd-configs](https://user-images.githubusercontent.com/96956419/156934669-e51af45b-27bf-4c1b-90a1-591a0f035be6.png)

**Comment by Torxed** [comment]
We've added a "Do you want a separate home?" question to avoid the above issues. Will be out in the next release.
However, there is a workaround and that is to do `--dry-run` and modify the disk layout defined in `/var/log/archinstall/user_disk_layout.json`.

It's pretty clear however that we'll need to re-work the guided manual partitioning as it's still very rudimentary.
Main focus has been on automatic layouts and manually specifying in the layout file.

**Comment by hexarch** [comment]
Thank you. Closing.
