### ISSUE TITLE
Silent install fails to create or mount partitions leading to pacstrap failure

### ISSUE THREAD

**Issue by brettski74** [archlinux/archinstall#1033]
Using version 2.3.2 with the 2022.03.01 live image, running the following command:

archinstall --silent --config user_configuration.json --creds user_credentials.json --disk-layouts user_disk_layout.json

fails. Logs are attached. JSON files were obtained from a prior guided installation. Similar failure also occurs without the disk-layouts file, which is supposed to be optional. No partitions were created. Tried with:

- no partition table
- blank GPT partition table
- GPT partition table with partitions similar to user_disk_layout.json manually created beforehand.

Same result. Nothing mounted and pacstrap fails.
[archinstall.failed.tar.gz](https://github.com/archlinux/archinstall/files/8240518/archinstall.failed.tar.gz)

**Comment by wllacer** [comment]
Might sound dumb, but ... looks like the disk_layout file is not read.
Use following command
```
archinstall --silent --config user_configuration.json --creds user_credentials.json --disk_layouts=user_disk_layout.json
```
Note the underscore in disk_layouts and the equal sign without spaces. A more coherent behaviour is already in master waiting for the new version

**Comment by brettski74** [comment]
Noticed the --disk-layouts rather than --disk_layouts, which gets me back to the other issue I was having:

root@archiso ~ # archinstall --silent --config user_configuration.json --creds user_credentials.json --disk_layouts user_disk_layout.json
Testing connectivity to the Arch Linux mirrors ...
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 33, in <module>
    sys.exit(load_entry_point('archinstall==2.3.2', 'console_scripts', 'archinstall')())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 113, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 180, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 395, in <module>
    load_config()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 55, in load_config
    if (dl_path := pathlib.Path(archinstall.arguments['disk_layouts'])).exists():
  File "/usr/lib/python3.10/pathlib.py", line 958, in __new__
    self = cls._from_parts(args)
  File "/usr/lib/python3.10/pathlib.py", line 592, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.10/pathlib.py", line 576, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not bool

--disk_layouts is supposed to optional, so it still seems like a problem that it doesn't create or mount anything, no? This seems like a separate issue, though. I can generate logs and raise that separately, or we can continue here.

**Comment by wllacer** [comment]
You still need the = sign without spaces. IIRC this was the exact error when it is  forgotten. So it's the same issue

**Comment by brettski74** [comment]
Consistency in the command line parameters would be nice. The documentation at https://archinstall.readthedocs.io/installing/guided.html#installing-directly-from-a-configuration-file doesn't mention anything about an equals sign and the example command line with --config doesn't use it. I ran into different errors on different iterations, so it was difficult to know which were user error (ie. me) or issues with the installer. It doesn't seem straightforward to follow the documentation, generate JSON files from a manual install as a starting point and have that work as a silent installation, though - at least not with 2.3.2. 

I've built and installed the 2.4.0-dev0 from master, built new JSON files using the new guided installer and I have gotten a successful silent installation to run, so whether this was all user error or a real problem somewhere, it seems fixed in master.

**Comment by Torxed** [comment]
I agree, and we already had it in `master` *(the consistency)*.
We've migrated the changes from `master` *(v2.4.0)*  into the latest stable release `v2.3.3` which was released today.

Hopefully it makes it into the April ISO.
Appreciate you reporting this and apologies for the unpolished command parsing, that one is on me :)
