### ISSUE TITLE
Could not strap in Packages: ==> ERROR: /mnt/archinstall is not a directory

### ISSUE THREAD

**Issue by maxderprofi** [archlinux/archinstall#1050]
I gave up installing arch becouse I had an error with efi vars, so i tried archinstall.
But it also gave an error.
I easly could crate the directory which is missing, but it should create one automaticly. 
And I cant write the command while it works.

**Comment by Torxed** [comment]
Most likely a network error, could you atttach your `/var/log/archinstall/install.log`?

**Comment by ABotelho23** [comment]
I ran into this issue, and noticed it was happening when I tried to specify custom disk partitioning.

**Comment by Torxed** [comment]
> I ran into this issue, and noticed it was happening when I tried to specify custom disk partitioning.

That should have error out, do you have any logs still under `/var/log/archinstall/`?
Be mindful of posting `install.log` as it may contain passwords in clear text until v2.4.0

**Comment by ABotelho23** [comment]
I can't even reproduce it anymore, but I'm getting something related to my disk_layouts.json file though. Pacman is claiming there isn't enough disk space to complete the installation:
```
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "2048MB",
                "start": "5MB"
            },
            {
                "btrfs": {
                    "subvolumes": {
                        "@.snapshots": "/.snapshots",
                        "@home": "/home",
                        "@log": "/var/log",
                        "@pkg": "/var/cache/pacman/pkg"
                    }
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs"
                },
                "format": true,
                "mountpoint": "/",
                "size": "100%",
                "start": "2053MB"
            }
        ],
        "wipe": true
    }
}

[install.log](https://github.com/archlinux/archinstall/files/8404905/install.log)

```

**Comment by Torxed** [comment]
Probably not related, but having `/boot` set to `ext4` might complicate things.
And I'm not sure we have a test case for the following, so not sure what would happen...
But this disk layout is pretty interesting:
```json
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": false,
                "encrypted": false,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "2048MB",
                "start": "5MB"
            },
            {
                "boot": true,
                "encrypted": true,
                "filesystem": {
                    "format": "vfat"
                },
                "format": true,
                "generate-encryption-key-file": true,
                "mountpoint": "/boot/efi",
                "size": "500MB",
                "start": "2053MB"
            },
            {
                "btrfs": {
                    "subvolumes": {
                        "@.snapshots": "/.snapshots",
                        "@home": "/home",
                        "@log": "/var/log",
                        "@pkg": "/var/cache/pacman/pkg"
                    }
                },
                "encrypted": true,
                "filesystem": {
                    "format": "btrfs"
                },
                "format": true,
                "mountpoint": "/",
                "size": "100%",
                "start": "2558MB"
            }
        ],
        "wipe": true
    }
}
```
I haven't tested encrypting `/boot/efi` either, so that's a bold interesting use case that I'll have to look in to! : )
I somehow suspect that maybe `/boot/efi` shouldn't be encrypted using a keyfile, but rather the other way around? `/` being encrypted using a keyfile taken from `/boot/efi` for this to work. Otherwise it would encrypt `/boot/efi` and wouldn't be able to load it without unlocking `/` first, which is a chicken-and-egg problem?

Anyway, to the problem at hand.
`/usr/bin/mount -t btrfs  /dev/mapper/ainstloop /mnt/archinstall/` appears to have been executed..
So the mount should definitely be there. Out of curiosity, how large is the disk?
And when it crashes, what does `mount` show?

**Comment by svartkanin** [comment]
@Torxed should we close this for inactivity?

**Comment by Torxed** [comment]
That and I think the main culprit was wrongful filesystem for boot, and `efi` vars not being written is what indicates that. As it **needs** fat32.
