### ISSUE TITLE
Awesome WM does not boot to GUI

### ISSUE THREAD

**Issue by cardosopab** [archlinux/archinstall#1058]
When Awesome is chosen, it will only boot into CLI after installation.

**Comment by Torxed** [comment]
That's as intended, there is no greeter for awesome.
Instead you'll have to run the command `startx` when you've logged in, or enable auto-start of it.

https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login

**Comment by cardosopab** [comment]
Just learned something new, thanks!
