### ISSUE TITLE
Support for specifying a specific partition to install onto

### ISSUE THREAD

**Issue by JD-The-65th** [archlinux/archinstall#1060]
Like the title says, this would be an immense help when dual booting.

**Comment by wllacer** [comment]
You have it already:
Per default Archinstall performs installation at the `/mnt/archinstall` directory. Simply when asked to select a disk, push the `esc` key, and don't select a disk. Installation will proceed there.
If you want a different directory execute archinstall as

`python -m archinstall --mount-point <directory_of_your_choice> `

Only nag is you have to define the disk structure** in advance**,  either by hand or using 

`python -m archinstall --script only_hd --mount-point <directory_of_your_choice> `, 
which is a script which only perform disk management

**Comment by JD-The-65th** [comment]
Alright, thank you. Closing the issue.

**Comment by wllacer** [comment]
Check the updated comment. Was missing my daily coffeine when I wrote it.
