### ISSUE TITLE
Partition.boot does not work anymore

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#1061]
Using the property `boot` from `Partition` always retuns  **False**

The code at master is 
https://github.com/archlinux/archinstall/blob/28c63b2354724601b0c88e5cc60473f801968d4d/archinstall/lib/disk/partition.py#L159-L177
The `sfdisk` in my installation never returns this attribute.
For the two images i have bootable partitions (a loop device and a real ssd disk)  i get (arch upgraded a couple of days ago)
```
      "partitions": [
         {
            "node": "/dev/loop0p1",
            "start": 2048,
            "size": 1046528,
            "type": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B",
            "uuid": "3D458F64-2FC8-49BD-BF3E-B1BCEB12DEF3",
            "name": "primary"
         },{

```
and 
```
    "partitions": [
         {
            "node": "/dev/sda1",
            "start": 8192,
            "size": 2088960,
            "type": "C12A7328-F81F-11D2-BA4B-00A0C93EC93B",
            "uuid": "B941AB7E-EC60-4CBC-8365-1A7558D20F1D",
            "name": "EFI"
         },
```
Still don't have an alternate way, but parsing the output of `parted`. I don't like the idea very much

The name/type EFI should be general, but we don't name it that way when we create them

**Comment by wllacer** [comment]
For GPT this is encoded at the entry "type" .
See [from systemd documentation](https://systemd.io/DISCOVERABLE_PARTITIONS/)

**Comment by Torxed** [comment]
Weird, since when did `sfdisk` not report `boot`?
I guess we can find this from `/sys/class` or `/dev` lookups, or if `blkid` reports it some how.

**Comment by wllacer** [comment]
New kernel version last week probably ... Btw. Do we still support MBR
disks?

**Comment by Torxed** [comment]
We do, MBR + GRUB is a large user base so we'll need to support it for a little longer ^^
I'm not sure how my MBR machine even boots because it's missing the boot flag, but either way `sfdisk` will only show bootable under MBR disks with the flag set. Under GPT it should return `True` if the partition is a `EFI`/`ESP` partition as those will be iterated and "bootable" by default.

So we'll need to extend the functionality of said function.
A good explanation of the different scenarios we have to support: https://superuser.com/a/1462453/155171

**Comment by wllacer** [comment]
The information is there for GPT. but hidden under the type UUID. If it is the one which begins with C12A is an EFI partition so it is the bootable one. 
I have to check what comes up with a MBR disk. Will report my finds

**Comment by wllacer** [comment]
On an MBR disk the routine works correctly. There is a `bootable` attribute.
The change is easy (adding a check for the correct GUID type)
Will have a PR probably tomorrow

**Comment by wllacer** [comment]
Faster than expected ;-) 
I will sweat to adapt to MBR disks my new disk management tool :-(
