### ISSUE TITLE
Partition.mountpoint gives incorrect result with Btrfs

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#1064]
In a btrfs partition with subvolumes, it returns the mountpoint of the first subvolume mounted. With a not discernible definition of  which is the first one (which doesn't guarantee repeatibility).
MapperDev.mountpoint has exactly the same problem

It either should return None, one according to a strict ordering criteria, or a list of all mounted subvolumes
For the first criteria a simple check if `filesystem[source]` is the exact partition path would suffice. The second would need a sorted() statement for the criteria we chose, and the third would break compatibility with current code
BTW. In my tests the recursive option for `findmnt` was not needed 

https://github.com/archlinux/archinstall/blob/57b16d5468493dbc4b134a43bb55cf52571acb0b/archinstall/lib/disk/partition.py#L95-L100

Whatever solution is chosen, it will not be without side effects.
I've located following usages of the property. I've marked in front of the line which calls are expected to give trouble, whatever change we chose
```
(Yes) archinstall/lib/disk/blockdevice.py:240:                        if self.partitions[partition].mountpoint == mountpoint:
(Yes) archinstall/lib/disk/filesystem.py:161:                 if partition.target_mountpoint == mountpoint or partition.mountpoint == mountpoint:
(Yes) archinstall/lib/disk/partition.py:68:           if self.mountpoint:
(not) archinstall/lib/disk/partition.py:69:                   mount_repr = f", mounted={self.mountpoint}"
(probably not) archinstall/lib/disk/partition.py:406:          if not self.mountpoint:
(following probably not)
archinstall/lib/luks.py:31:             self.mountpoint = mountpoint
archinstall/lib/luks.py:49:             return self.unlock(self.partition, self.mountpoint, self.key_file)
archinstall/lib/luks.py:198:                    crypttab.write(f"{self.mountpoint} UUID={convert_device_to_uuid(self.partition.path)} {key_path} {','.join(options)}\n")
(not) archinstall/lib/installer.py:622:                       if partition.filesystem == 'ntfs3' and partition.mountpoint == self.target:
(not) archinstall/lib/installer.py:918:                       if partition.mountpoint == os.path.join(self.target, 'boot'):
archinstall/lib/installer.py:920:                       elif partition.mountpoint == self.target:
examples/guided_old.py:257:                     if partition.mountpoint == installation.target + '/boot':
(not) examples/guided.py:134:                 if partition.mountpoint == installation.target + '/boot':
(not)examples/only_hd.py:100:                        if partition.mountpoint == installation.target + '/boot':
(not) examples/swiss.py:369:          if partition.mountpoint == installation.target + '/boot':
(yes) examples/diskmanager.py:231:                                    "actual_mountpoint" : result[res].mountpoint,  # <-- this is false
(yes) examples/diskmanager.py:266:                    print('\t\t',result[res].MapperDev.mountpoint)
(not) examples/diskmanager.py:267:                    print('\t',result[res].mountpoint)
```
I can't, at the moment, take care of a solution

**Comment by Torxed** [comment]
My logic was that the `Partition` object should only return one root mountpoint, and that [.subvolumes](https://github.com/archlinux/archinstall/blob/57b16d5468493dbc4b134a43bb55cf52571acb0b/archinstall/lib/disk/partition.py#L259-L262) should return a full detailed inventory of all subsequent mountpoints.

**Comment by wllacer** [comment]
Only problem with your approach (once you know the limitation) is that i
could find no sorting logic at the findmnt results. Nobody can guarantee
(although It is probable) that `/` will be the first element.

**Comment by wllacer** [comment]
Have a look at the function `has_mountpoint` i've included in PR #1069.  Can solve some of the sideeffects this situation (and all the solutions) have.

**Comment by Torxed** [comment]
I think we've solved this one?
At least by being able to use `partition.mountpoints` to iterate them all, instead of `.mountpoint` which returns the first in the list.
Example of use: https://github.com/archlinux/archinstall/blob/13703fbb04d7bc7975368b035342e104c26e3f35/archinstall/lib/installer.py#L1017-L1024

Is this enough or we want to tweak it further?

**Comment by svartkanin** [comment]
@Torxed I think this is resolved as well
