### ISSUE TITLE
error code 255, which doesn't seem to affect anything.

### ISSUE THREAD

**Issue by Onetopabove** [archlinux/archinstall#1073]
![image](https://user-images.githubusercontent.com/38457754/163577016-edd51e73-c4b3-4770-a033-86f5024beb8b.png)
When the installation was almost finished, the process got stuck here. I don't what the error means. But after I rebooted the virtual machine , no factual errors happened.
The entire install.log is https://0x0.st/oc9O.log

**Comment by svartkanin** [comment]
This is most likely resolved with the major rewrites since the issue was opened
