### ISSUE TITLE
error: libmfx: key is unknown

### ISSUE THREAD

**Issue by WilsontheWolf** [archlinux/archinstall#1077]
Hello there,

When trying to use archinstall, when installing packages it fails, stating error: libmfx: key "80247D99EABD3A4D1E3A1836E85B8683EB48BC95" is unknown

Log: https://haste.antti.codes/fawugijodu

**Comment by Torxed** [comment]
Are you by any chance using an older ISO?

**Comment by Torxed** [comment]
I'll close this one as I'm pretty sure it relates to an older ISO which had issues with signing keys.
