### ISSUE TITLE
Readability 

### ISSUE THREAD

**Issue by se7en-x230** [archlinux/archinstall#1080]
Love the installer. Nice and simple but it lacks a bit of readability design. Simple things like a empty line between sections would already do the trick.

**Comment by Torxed** [comment]
I'ts coming. version 2.4.0 will have a completely new TUI (which should also remain accessability friendly) :)

**Comment by se7en-x230** [comment]
NICE!!!
That is an improvement.
Might be a terminal problem but white on light blue is hard to read in st.
![image](https://user-images.githubusercontent.com/69777713/166148628-bcccc197-f4be-44f5-a381-827d6aecef10.png)

**Comment by Torxed** [comment]
> 

That doesn't look like the dark blue i'm used to in the official ISO.

**Comment by se7en-x230** [comment]
I did a dry-run on my arch 
Dwm and terminal is st
It might be a terminal problem or my terminal theme.

I'll check later
