### ISSUE TITLE
Menu system - btrfs subvolume issue

### ISSUE THREAD

**Issue by zepanv** [archlinux/archinstall#1091]
When trying to edit the subvolumes it deletes the item below the selected one.  In this case I was testing with 2 drives, I selected the boot drive, btrfs, suggested and then tried to remove the home subvolume, but instead the log was removed.  The idea being home would be mounted on the second drive.

![before](https://user-images.githubusercontent.com/2130492/165755110-b170d230-80a7-48bb-bbef-8dc7fce417b7.png)

![after](https://user-images.githubusercontent.com/2130492/165755109-43687566-2ea7-44aa-9650-d7299bbb95c1.png)

**Comment by Torxed** [comment]
Index offset probably, we'll get that sorted. For now manually editing the JSON result might be most reliable
