### ISSUE TITLE
LUKS + BTRFS = slow boot? strange `scanned by systemd-udevd`

### ISSUE THREAD

**Issue by Moelf** [archlinux/archinstall#1095]
```
> systemd-analyze
Startup finished in 4.738s (firmware) + 225ms (loader) + 13.090s (kernel) + 1.861s (userspace) = 19.916s 
graphical.target reached after 1.568s in userspace
```

**Comment by Moelf** [comment]
actually, looking more carefully, it's not decryption that is slow, it's the `filesystem` hook that comes after `encrypt`

**Comment by Torxed** [comment]
out of curiosity, did you install on a USB? or what's your HW specs?

**Comment by Moelf** [comment]
It's on a NVME Gen4 SSD (WD_BLACK™ SN850), CPU is 11th Gen Intel i5-1135 (it's a Framwork laptop

**Comment by xstondis** [comment]
@Moelf (How) did you fix this?

**Comment by Moelf** [comment]
didn't fix it, it's always this slow I think

**Comment by xstondis** [comment]
i fixed it with
`cryptsetup luksChangeKey /dev/nvme0n1p2 --iter-time 1000`
which was set to 10000ms by default

**Comment by Moelf** [comment]
right, I guess it depends on how secure you want it to be
