### ISSUE TITLE
f2fs not available under "Create New Partition"  &&  "timed out waiting for device" on boot

### ISSUE THREAD

**Issue by Schweber** [archlinux/archinstall#1101]
I tried installing the current archlinux-2022.04.05-x86_64.iso with the latest archinstall (executed pacman -Sy archinstall, archinstall did update, then executed archinstall). 

When selecting "Suggest disk layout" i could select f2fs among around 4 options. However, the proposed /root only had 20GB which i wanted to increase to 40GB. The version of archinstall shipped with archlinux-2022.04.05-x86_64.iso suggested 40GB for the /root partition, which is more sensible in my opinion.

When selecting "Create new partition" there were around 10 options but f2fs was **not** among them.

I then proceeded to install with the suggested disk layout and the installation succeeded without error. On rebooting, arch failed with "timed out waiting for device".

I don't know why this is the case and was hoping for archinstall to set up the system for me, as i am not experienced in setting up my os "the Arch way".

[install.log](https://github.com/archlinux/archinstall/files/8595250/install.log)
![IMG_20220430_013436](https://user-images.githubusercontent.com/64630479/166081018-9a854e95-d672-4baf-bc8e-175668cd471b.jpg)

**Comment by Torxed** [comment]
IIRC this was supposed to be a experimental filesystem hidden behind `--advanced`. And the path looks odd to me:

![B40A4471-1B9B-4FB8-A482-64B8A3E06B25](https://user-images.githubusercontent.com/861439/166095145-1cc1ac31-8ca5-490b-a1eb-345a6b9ca403.jpeg)

We will ofc try to fix this and also check the default filesize layout

**Comment by Schweber** [comment]
> IIRC this was supposed to be a experimental filesystem hidden behind `--advanced`. And the path looks odd to me:
> 
> ![B40A4471-1B9B-4FB8-A482-64B8A3E06B25](https://user-images.githubusercontent.com/861439/166095145-1cc1ac31-8ca5-490b-a1eb-345a6b9ca403.jpeg)
> 
> We will ofc try to fix this and also check the default filesize layout

Thank you!

**Comment by Torxed** [comment]
We'll still take care of this, but in favor of fixing some more critical issues I'm just pushing this back one version.

**Comment by svartkanin** [comment]
I can see f2fs being an option in the manual partitioning and I think the rest of the issues mentioned should be resolved as well
