### ISSUE TITLE
[glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig

### ISSUE THREAD

**Issue by SatouKuzuma1** [archlinux/archinstall#1104]
I'm unable to open kitty or alacritty in a fresh installation.
First of all I get this output when I run kitty from terminal.
```
kitty
libGL error: failed to create dri screen
libGL error: failed to load driver: swrast
[121 12:27:11.848966] [glfw error 65543]: GLX: Failed to create context: GLXBadFBConfig
[121 12:27:11.849101] Failed to create GLFW temp window! This usually happens because of old/broken OpenGL drivers. kitty requires working OpenGL 3.3 drivers.
```

So I run the next command:
`LIBGL_ALWAYS_SOFTWARE=true GALLIUM_DRIVER=llvmpipe kitty`
and then kitty finally opens. The problem is that when I close the window I need to rerun the same command to be able to open it again.
I have set the environmental variables in /etc/environment:

```
LIBGL_ALWAYS_SOFTWARE=true

GALLIUM_DRIVER=llvmpipe

```
But nothing changes. I don't know hot to stabilise those values so every time I boot I can launch kitty.
I also tried 
`export LIBGL_ALWAYS_SOFTWARE=true`
and it works but when I reboot I'm facing the same issue again.
 I don't know what else I can do. Maybe I'm setting wrong the environmental variables.

**Comment by Torxed** [comment]
Feels like a lack of GFX driver, what does `lspci | grep -i "vga"` say?

**Comment by SatouKuzuma1** [comment]
@Torxed I get this:
```
lspci | grep -i "vga"
00:02.0 VGA compatible controller: VMware SVGA II Adapter
```

**Comment by Torxed** [comment]
Did you select all the open source graphics drivers, specifically you'll need https://archlinux.org/packages/?name=xf86-video-vmware and `mesa` i believe. long time since i ran VMWare

**Comment by SatouKuzuma1** [comment]
@Torxed I'm running virtualBox

**Comment by Torxed** [comment]
I noticed, but the VMWare driver or open source driver tend to work well there too. but most importantly is the mesa package. on the phone atm so apoligies for short answers.

**Comment by Torxed** [comment]
Now do `pacman -Q mesa`, im almost certain you'll have that too tho

**Comment by SatouKuzuma1** [comment]
@Torxed 
```
pacman -Q mesa
mesa 22.0.2-1
```

**Comment by Torxed** [comment]
Then i'm not sure what is causing the issue. Appers as if kitty is having issues activating the GL context at least, i'll investigate and see what could cause this.

**Comment by SatouKuzuma1** [comment]
@Thank you. I've been trying to solve this for two days now and it's turning me crazy. Hope you find something.

**Comment by SatouKuzuma1** [comment]
I don't know what happened but when I booted up this morning everything worked fine. Weird. This kind of things makes me curious. I don't know if the problem would start again later but for the moment it seems solved.

**Comment by Torxed** [comment]
If it does, drop a post on the Arch forums or better yet the Kitty forums, as they probably know by heart what could cause this :) Glad it works tho!

**Comment by frenchbeard** [comment]
Sorry for ressucitating the "dead" issue, but I thought this would complement it nicely :

I ended up here having similar errors on an old computer (I think bought around 2010) I just reinstalled with Arch. I can't speak for the VMWare guest driver (don't have the required setup at hand), but the one I currently use seems to be limited to OpenGL 2.1. And to be able to run anything that requires a more recent OpenGL version than the one your graphics driver advertises will at least require the `LIBGL_ALWAYS_SOFTWARE=true` defined.

@SatouKuzuma1 if you ever run into such an issue again, to prevent having to export it at the beginning of each new session, you can place your `export  LIBGL_ALWAYS_SOFTWARE=true` either :

* in your user's `~/.profile` (for a single user);
* in a file of your choosing in `/etc/profile.d` (for a multi-user setup, shouldn' t be relevant for a VM).

Note that any such configuration should result in a way higher load on the CPU, rendering moot some of the key features.

Finally, regarding the problem itself, if `ixni -Ga` (or any other tool giving you details on your GL current running version) returns a value of OpenGL inferior to 3.3, such as what I have :
` ` `
Graphics:
  Device-1: Intel Core Processor Integrated Graphics driver: i915 v: kernel
  Display: server: X.org v: 1.21.1.6 driver: X: loaded: modesetting
    unloaded: fbdev dri: crocus gpu: i915 resolution: 1440x900~50Hz
  API: OpenGL v: 2.1 Mesa 22.3.2 renderer: Mesa Intel HD Graphics (ILK)
` ` `
 at least `kitty` won't be able to init properly (for anything else, it will depend on what API they actually require).
