### ISSUE TITLE
Generated user_*.json files do not appear to store all answers

### ISSUE THREAD

**Issue by jamincollins** [archlinux/archinstall#1112]
In attempting to use the `user_configuration.json` and `user_credentials.json` output from a previous installation/run for a subsequent installation/run.  I've found that they do not appear to store all answers.  Such as prompts that are to be left blank to skip.  Such as whether to set a root password or create additional users.  There may be other prompts that this applies to as well.

**Comment by Torxed** [comment]
they are stored in user_credentials and subsequent questions can be ignored with `--silent`

**Comment by jamincollins** [comment]
The questions where the prompt was left blank _are not_ recorded in **user_credentials**.  I've reviewed the file and when electing: not to set a root password, create only one user with sudo privileges, and no additional users.  The file contains only one entry and subsequent runs prompt for both the root password and additional users.  I guess passing `--silent` _could_ be seen as a workaround, but I would expect the previous answers (electing to leave blank is an answer) would have been recorded and as a result used to answer the same question on subsequent runs.
