### ISSUE TITLE
Enhancing readability with Spacing or clearing Screen between Questions

### ISSUE THREAD

**Issue by Akitarmo** [archlinux/archinstall#1115]
I encountered some Readability Issues while running the script because there is no Difference between the Output of the last Question and the new Question.

Therefore I would like to suggest to add some Spacing between the last Output and a new Question or even to clear the Screen befor a new Question appears.

**Comment by Torxed** [comment]
Do you remember which question in particular this refers to?

**Comment by Akitarmo** [comment]
Basicly every one, they where all mashed together.

I'm sorry if it's just an issue with my Setup...

I'm installing in VMware Workstation for Testing Purposes.

**Comment by Akitarmo** [comment]
Just as a Example:

![Archinstall1](https://user-images.githubusercontent.com/49686046/166167116-cc5c5d7e-9391-4485-8580-08f9382794bd.png)

**Comment by Torxed** [comment]
You're using an old version, fixed in v2.4

**Comment by Akitarmo** [comment]
Oh, sorry, downloaded the new Iso, thanks.
