### ISSUE TITLE
Pacstrap failing due to unknown PGP Key

### ISSUE THREAD

**Issue by Akitarmo** [archlinux/archinstall#1116]
Not sure whats wrong, I hope the Log helps.

![archinstall2](https://user-images.githubusercontent.com/49686046/166168975-029e6419-211a-4f04-914d-8ad31bd4c554.png)
[install.log](https://github.com/archlinux/archinstall/files/8599967/install.log)

**Comment by jamincollins** [comment]
You need to update the host system's `archlinux-keyring` before running the `archinstall`.  See #1110.

**Comment by jamincollins** [comment]
Might also be fixed by grabbing the current (released today) ISO.

**Comment by Akitarmo** [comment]
Oh, sorry, downloaded the new Iso, solved it, thanks.
