### ISSUE TITLE
BTRFS subvolumes creation issue

### ISSUE THREAD

**Issue by neuro-prog** [archlinux/archinstall#1118]
I'm testing archinstall in a VM (Virtualbox). I first created a disk, fired up the arch image iso and finally created three primary partitions with cfdisk (EFI, Swap and primary partition for the OS). The script works as expected until I try to manually create the subvolumes on the freshly created btrfs partition. Just after I select "@" as the name of the subvolume and "/" as the partition this is what I get:
 
![Screenshot_20220502_113811](https://user-images.githubusercontent.com/80591926/166215691-2d8d99d0-7c7e-4c47-ab3a-1aeb018720ac.png)
 
Am I missing something?

**Comment by Torxed** [comment]
Thank you for reporting this, we'll take a look at it.
For now, what you could do is run `archinstall --dry-run` and use the defaults for everything, and modify `/var/log/archinstall/user_disk_layout.json` according to your liking. And then run:
```
# archinstall --disk-layout /var/log/archinstall/user_disk_layout.json
```
It's a bit more convoluted, but you can also save the JSON for the next time you wish to re-install :)

**Comment by neuro-prog** [comment]
Thank you, I'll try that.

**Comment by svartkanin** [comment]
@neuro-prog this should be fixed now in master
