### ISSUE TITLE
KDE plasma not in French

### ISSUE THREAD

**Issue by laurentvv** [archlinux/archinstall#1123]
I had to add French language in panel configuration

and modify file .config/plasma-localerc
LANG=fr_FR.UTF-8 (default US)

**Comment by Torxed** [comment]
This is probably very specific to KDE. And could be considered a post-isntallation configuration.
I guess we *could* add a locale configuration in the KDE profile. It would be a very easy change to `profiles/kde.py` and I'd welcome a PR as I gotta focus on overall stability things for the next release. And documentation.. And tests..

**Comment by t-matze** [comment]
I can confirm that chosing the language and keyboard-layout during the install process (german in my case) didn't affect the localisation of the installed KDE DE, which was talking to me in english, having the american configuration for keyboard, numbers, currency etc. (I will have to test it with a different desktop environment to confirm your suggestion that it is specific to KDE.)

**Comment by Torxed** [comment]
This has been comsidered post-installation configuration. Archinstall traditionally performed tasks that were critical during install.

**Comment by svartkanin** [comment]
Closing this as this is a post-installation configuration that has to be done
