### ISSUE TITLE
`select_disk` throw an error because BlockDevice does not contain label

### ISSUE THREAD

**Issue by nonrg** [archlinux/archinstall#1127]
Running this line from a python script causes an error: 

`archinstall.select_disk(archinstall.all_blockdevices())`

```
Traceback (most recent call last):
  File "/root/test.py", line 3, in <module>
    hdd = archinstall.select_disk(archinstall.all_blockdevices())
  File "/usr/lib/python3.10/site-packages/archinstall/lib/user_interaction/disk_conf.py", line 68, in select_disk
    f"{index}: {drive} ({dict_o_disks[drive]['size'], dict_o_disks[drive].device, dict_o_disks[drive]['label']})"
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/blockdevice.py", line 45, in __getitem__
    raise KeyError(f'{self} does not contain information: "{key}"')
KeyError: 'BlockDevice(/dev/sr0, size=0.8GB, free_space=, bus_type=sata) does not contain information: "label"'
```

**Comment by svartkanin** [comment]
I was trying to reproduce this but actually got a different one myself 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "archinstall/archinstall/lib/user_interaction/disk_conf.py", line 68, in select_disk
    f"{index}: {drive} ({dict_o_disks[drive]['size'], dict_o_disks[drive].device, dict_o_disks[drive]['label']})"
TypeError: 'DMCryptDev' object is not subscriptable
```

I'll have a look, my feeling is that the Blockdevice class is a bit fragile and might need saver data structures

**Comment by Torxed** [comment]
Yea i want to make these more reliable and convert dicts to data structures overall. the mixing causes issues :) my bad!

**Comment by svartkanin** [comment]
I saw that some info is coming from `blkid` I wonder if they would return at known set of key-value pairs overall or if it will return exotic stuff for strange things. If it's a known set we can easily throw it into a dataclass

**Comment by Torxed** [comment]
Some are mandatory things that will always be there.
But most of the fields are totally optional, but we can handle that with `Optional[X]` I guess.

**Comment by svartkanin** [comment]
Sounds good :)

**Comment by svartkanin** [comment]
I started working on this, will add some dataclasses and rework the block device code a bit :)

**Comment by Torxed** [comment]
Sounds awesome, I've taken some inspiration from discord where each object should be responsible for it's own actions :)

**Comment by svartkanin** [comment]
I started to rework the block device but after changing 10 files I figured that I'll do more damage than good :D 
I think doing it piece by piece might be easier, so I'll "only" fix the issue in this ticket for now :)

**Comment by Torxed** [comment]
That sounds reasonable. Those big rewrites tend to take time and you end up in a rabbit hole hehe.
