### ISSUE TITLE
Make Ctrl-C clear the menu option - and Esc to only back out of menu's

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1130]
As pointed out in both [video format](https://www.youtube.com/watch?v=OtWWLN3wGNE) and in the [comments of the video](https://www.youtube.com/watch?v=OtWWLN3wGNE&lc=UgwWywhBjWoGfIvjard4AaABAg):

> ESC should just bring you back to previous screen. To reset, Ctrl+C

I think that makes sense so I'll post it here so we can track it.

**Comment by svartkanin** [comment]
Ohhh wow didn't know there's media coverage of the installer :D

**Comment by Torxed** [comment]
> Ohhh wow didn't know there's media coverage of the installer :D

Hehe. You'd be surprised.
 * https://www.reddit.com/r/archlinux/comments/ufvsif/comment/i6w54s6/?utm_source=reddit&utm_medium=web2x&context=3
 * https://www.reddit.com/r/archlinux/comments/uiv0xr/arch_guided_install_is_pretty_good_now/
 * https://youtu.be/BgesUogmHec (my favourite reviewer for sure)
 * https://youtu.be/MNJBh2vGRKI
 * ...

**Comment by svartkanin** [comment]
To the actual issue, yes I think that would be good way of handling it. We should keep it consistent throughout all menus then, I think most are doing an actual skip already.

Resetting might be a bit dangerous in certain cases, like what if I'm in the partitioning menu and I accidentally press ctrl+c, will my entire partitioning setup be erased?

**Comment by Torxed** [comment]
Good question. Would it be hard to add a "Are you sure you want to clear all work for this atep?"?

**Comment by svartkanin** [comment]
I raised a PR in upstream to introduce a new option
 https://github.com/IngoMeyer441/simple-term-menu/pull/50

**Comment by Torxed** [comment]
Oh that's pretty clean actually! Well done!
That means we can catch it and act on it.

**Comment by svartkanin** [comment]
@Torxed another review on the installer ;) https://youtu.be/leQbSsu-7F4

**Comment by Torxed** [comment]
> @Torxed another review on the installer ;) https://youtu.be/leQbSsu-7F4

It's interesting to see what people stumble/fumble on. Like the Grub entry that made him assume we don't have other boot loaders.. because ofc that is what people will think if they don't boot into UEFI mode which is where you get the option to choose other ones ^^

Nice calm walkthrouh, fun to see!
