### ISSUE TITLE
Archinstall encrypts already existing partitions

### ISSUE THREAD

**Issue by Schweber** [archlinux/archinstall#1134]
When using the latest Archinstall (2.4.2) it seems that it encrypts all existing partitions even when they are not edited in the disk layout configuration. 

One time i had a windows installation on the disk with its 3 partitions and created 2 additional partitions with archinstall. However, when installing archinstall immediately started to encrypt the windows partitions although i did not edit them in the disk layout.

The same thing happened again when trying to reinstall archlinux on its own / partition without editing the existing /home partition in disk layout. This even though the /home partition was already encrypted, so it seems that archinstall doesn't simply want to encrypt unencrypted partitions but simply all existing partitions.

Unfortunately i can't provide logs as i didn't go forward with both installations but this should be easy to replicate.

Due to the already mentioned bugs that don't let me select f2fs when creating a new partition and the small / partition when letting archinstall suggest a partition layout (19.5GB), the "safest" option right now is for me to let archinstall suggest a layout without /home and giving the disk entirely to archinstall.

**Comment by Torxed** [comment]
Could you supply `/var/log/archinstall/user_disk_layout.json` and possibly the `install.log`?

Just make sure they do not contain any passwords!

**Comment by Schweber** [comment]
I'm sorry i can't because i aborted the installations, made a few new attempts and then finally installed with the suggested layout without /home. Therefore i don't have the logs, sorry.

This should be easy to replicate though.

**Comment by Schweber** [comment]
I just had time to look into it again. The problem seems to be, that archinstall defaults to formatting all existing partitions and can't be told not to.

I took the attached screenshot after opening "disk layout -> select what to do" without further input. I am not able to unmark the partitions from being formatted.

I think this is a bug. The default should be not to format anything and i should be able to unmark partitions from being formatted.


![IMG_20220523_081941](https://user-images.githubusercontent.com/64630479/169758519-5c7a1ec8-9db7-4eeb-9396-b6fba3cea6a9.jpg)

**Comment by Torxed** [comment]
I think it's related to: https://github.com/archlinux/archinstall/issues/998

Could this be it?

**Comment by svartkanin** [comment]
Closing as resolved for now, if this re-appears we can have a dive into it
