### ISSUE TITLE
Cyrillic problems (?)

### ISSUE THREAD

**Issue by Alexmelman88** [archlinux/archinstall#1138]
I decided to test new translation and got this 
![Снимок экрана от 2022-05-06 17-47-09](https://user-images.githubusercontent.com/99257010/167248513-44b773ea-2f33-41b5-aa17-fc09a118358c.png)

**Comment by Torxed** [comment]
Humm, possibly a missing font on the official ISO.
Do you know which font you typically use in these regions?

**Comment by Fooftilly** [comment]
Just want to mention that you should choose font which has support for other languages which use Cyrillic outside Russia.

**Comment by Alexmelman88** [comment]
Open Sans, Noto Sans, Roboto, Ubuntu. That's the first thing that came to mind.

**Comment by Torxed** [comment]
I assume that some of these can handle Cyrillic as well. And most of them should handle other languages as well.
I was under the impression that only these would support Cyrillic: https://wiki.archlinux.org/title/fonts#Cyrillic

**Comment by Alexmelman88** [comment]
Noto Fonts are developed by Google and are designed for a large number of languages, including Cyrillic https://fonts.google.com/noto

**Comment by svartkanin** [comment]
I wonder if this is related to the rendering issue that is seen in french for certain characters

**Comment by svartkanin** [comment]
Maybe the encoding isn't right when the .mo files are generated

**Comment by Torxed** [comment]
> Maybe the encoding isn't right when the .mo files are generated

Might be, since some of these characters probably won't work in UTF-8?

**Comment by Alexmelman88** [comment]
> Maybe the encoding isn't right when the .mo files are generated
UTF-8 encoding.  The .mo file was made with locales_generator.sh and Poedit 3.0.1

**Comment by svartkanin** [comment]
@Alexmelman88 I gave this a try and it seemed to work for me on a real machine but fails with the ISO inside a VM, so it might actually be a font issue as @Torxed pointed out. 
Would you be able to confirm if you can type cyrillic characters outside archinstall, basically just in the console of the terminal?

**Comment by Alexmelman88** [comment]
On real machine after these commands everything worked
![20220508_133548](https://user-images.githubusercontent.com/99257010/167292937-39ffc85d-820d-44f7-9607-fcf18aaa6956.jpg)

The setfont parameter probably helped
![20220508_134417](https://user-images.githubusercontent.com/99257010/167293060-0f7876ab-113c-43ee-8a9d-2df4c4430c5b.jpg)

**Comment by Alexmelman88** [comment]
Not all translation strings are listed in base.pot. For example "Press "/" to search", "True", "None".

**Comment by svartkanin** [comment]
Interesting, we might be able to load the font dynamically in the installer.

Those strings were probably missed, they have to be marked with a special wrapper to show up in the translation file, something like `str(_('something'))`

**Comment by Alexmelman88** [comment]
By the way, the problem remains, maybe when selecting a language to load a font?

**Comment by Torxed** [comment]
I think the best thing we can do, is to load the font during language selection.
I still don't know what font/command to run to load the correct font tho

**Comment by Alexmelman88** [comment]
Maybe setfont UniCyrExt_8x16 ?

**Comment by Alexmelman88** [comment]
![Снимок экрана от 2022-05-27 18-32-31](https://user-images.githubusercontent.com/99257010/170731606-e45bc842-40ab-4bd8-9316-395a840b925c.png)
The second choice has more characters

**Comment by Torxed** [comment]
We'll get that one in there for the next version!

**Comment by Torxed** [comment]
@svartkanin can we some how set this: https://github.com/archlinux/archinstall/blob/4d57630c90ca6bf400df55f03eb8a4c6b9ed9ca7/archinstall/__init__.py#L249-L250

When a specific language is selected through the menu system?
I'm a bit unsure of where to put the call. And maybe move `def set_unicode_font()` to `general.py`.
And unset it if the language is anything but cyrillic?

**Comment by svartkanin** [comment]
We can set it when the language is selected, however, this does not only affect Russian I think (maybe it's the currently only supported language, but Ukranian, Bulgarian etc. would require it as well).

So the question would probably be, how do we identify languages that need this font? 

I did attempt to set it globally in #1153 but someone reported that that font wasn't present on their system? I was a bit confused about that, because I tested it on the iso and it seemed to be installed and available.

As a workaround we could do the #1153 implementation in a try-catch block so it doesn't blow up at least, any thoughts on that @Torxed ?

**Comment by Torxed** [comment]
We could create a global list in `storage` over `cyrillic_languages` for now also if we wanted to. And if Bulgarian for instance is added, that could be appended specially to that list.

But try catch would work too :D

> I did attempt to set it globally in https://github.com/archlinux/archinstall/pull/1153

Yea that one blew up, so I reverted it for now.
But moving that function to `if lang in storage['cyrillic_languages']` and then call that function would work nicely.
And `if lang not in ..` set the default.

**Comment by svartkanin** [comment]
@Torxed raised a PR to set the font only on cyrillic otherwise we'll set the default font :)
