### ISSUE TITLE
Changes made to disk layout can't be saved

### ISSUE THREAD

**Issue by asier-izquierdo** [archlinux/archinstall#1143]
When I set the disk layout, there's no option to save changes to go back to the menu, other than using "esc" or "q", which don't save anything.

**Comment by Torxed** [comment]
Archinstall never performs any operations, until you press `install`.
The configuration can be changed from the menu.

This is personally one of the stronger aspects of Archinstall, as it's safe to use until you hit `install`.
So assuming I understood your issue correctly, I will go ahead and close this ticket. Hope this explained the intended functionality :)

**Comment by asier-izquierdo** [comment]
Hello, I didn't mean saving the changes to the disk, per se.I mean that, when selecting the disk distribution in order to specify that the EFI partition should be mounted on /boot and the main partition on /, when exiting to the menu, if I go into the disk distribution again, those specifications don't show configured as I did.Hopefully this explains my problem better.Best regards. Sent from ProtonMail for iOS On Sun, May 8, 2022 at 20:38, Anton Hvornum ***@***.***> wrote:  
Archinstall never performs any operations, until you press install.
The configuration can be changed from the menu.
This is personally one of the stronger aspects of Archinstall, as it's safe to use until you hit install.
So assuming I understood your issue correctly, I will go ahead and close this ticket. Hope this explained the intended functionality :)
