### ISSUE TITLE
Disk distribution problem

### ISSUE THREAD

**Issue by asier-izquierdo** [archlinux/archinstall#1144]
Hello, and sorry for the trouble opening another issue.

I didn't mean saving the changes to the disk, per se.

I mean that, when selecting the disk distribution in order to specify that the EFI partition should be mounted on /boot and the main partition on /, when exiting to the menu, if I go into the disk distribution again, those specifications don't show configured as I did.

Hopefully this explains my problem better.

Best regards.

**Comment by Torxed** [comment]
Ah, I think I understand now. That would be a glitch yes. For future reference it is totally fine commenting on closed issues as we can re-open them when more details come in :)

I'll leave this one open and we'll get a patch sorted in a bit! :D

**Comment by svartkanin** [comment]
I think this is most likely resolved now when pyparted was introduced
