### ISSUE TITLE
Specify a custom post-installation script within archinstall config

### ISSUE THREAD

**Issue by i2** [archlinux/archinstall#1160]
Hi everyone,

Is it possible to specify a post-install script to run with archinstall? For me, this would be a very useful feature. Please note this is different from the option we already have "Write additional packages to install". As you know, in a typical Arch Linux installation, at the end, there is a [post-install step](https://wiki.archlinux.org/title/installation_guide#Post-installation). I want archinstall config to trigger an a post-installation shell script. For more clarification, in a manual Arch instalation, it'll translate to **[arch-chroot /mnt sh /home/my-script.sh](https://unix.stackexchange.com/questions/541819/automating-arch-installation)**

Thank you!

**Comment by i2** [comment]
Thank you! I just saw that after posting my question. My apologies!

**Comment by Torxed** [comment]
No worries at all :) Happy to help and fun to see that these more "advanced" features are being used :D
