### ISSUE TITLE
[master] Lag in menu after selecting a harddrive

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1162]
Running `viztracer` generates a 2.6G trace and crashes most machines trying to analyze it.
Here's the only evidence of the issue thus far:

https://user-images.githubusercontent.com/861439/167908067-694654d5-56a3-4baa-8bcb-9378472c8677.mov

https://user-images.githubusercontent.com/861439/167908074-be9c081f-2180-42ea-84bc-7fe0fed73e20.mov

I haven't been able to track it down.
Reported by `@rez` on discord.

Doesn't always happen, I tried a "speedrum" earlier today of `master` and it worked, with a slight hint of the lag: https://cdn.discordapp.com/attachments/726808924401172483/973994546126024714/archinstall_speedrun.gif

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/167910062-f92c2f29-51cb-481d-bc96-6abb7637a371.png)

Nothing really stands out.

**Comment by Torxed** [comment]
Ok so, it seams the printing of the block-device information is causing the delay. As we appear to refresh the information each time the arrows are pushed.

![screenshot](https://user-images.githubusercontent.com/861439/167910736-84d0ead6-abbc-4970-9e2b-57aef619f67d.png)

Here, highlighted is `__repr__` of `/home/anton/github/archinstall/archinstall/lib/disk/blockdevice.py:34`.
This is called from `menu_text` in `/home/anton/github/archinstall/archinstall/lib/menu/selection_menu.py:124`.

And `__repr__` has a horrific delay due to:
 * `self.size`
 * `self.free_space`
 * `self.bus_type`

But this is just a symptom because: https://github.com/archlinux/archinstall/blob/08452de09c8461178e27da27633778910a4e1b7a/archinstall/lib/general.py#L318-L341

It's a delay of `0.1 * 3` per time we print the information.

**Comment by i2** [comment]
[ Off-topic, but how do you create these graphics? I like them! ]

**Comment by Torxed** [comment]
> [ Off-topic, but how do you create these graphics? I like them! ]

```
$ pip install viztracer
$ viztracer python -m archinstall
```
Will generate `result.json` which you can upload and view on https://ui.perfetto.dev/

There's some other tools as well for local visualization that is a bit more oldschool.
```
$ python -m cProfile -o profile_data.pyprof guided.py
$ pyprof2calltree -i profile_data.pyprof -k
```
Available in `community/pyprof2calltree` and `extra/kcachegrind`.
