### ISSUE TITLE
After configuring additional repositories to enable in main menu, cursor is over blank option

### ISSUE THREAD

**Issue by mjdxp** [archlinux/archinstall#1167]
Once additional repos are configured, the cursor is brought down to the next line, which is blank. Attempting to select this blank option does nothing. This is occurring on the latest Arch Linux ISO release as of May 11th.

![VirtualBox_Arch Linux_11_05_2022_18_38_53](https://user-images.githubusercontent.com/71859271/167959240-52a13bea-b447-408e-baef-cb1c451eaa27.png)

**Comment by svartkanin** [comment]
@mjdxp this should already be fixed in master :)
