### ISSUE TITLE
Removing subvolumes through partitioning tool removes wrong entry

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1168]
When i tried to modify this by removing subvolumes I didn't want, it wouldn't remove the one I'm trying to delete but a different one. Ex. I would try to delete the @pkg subvolume and it would delete the @snapshots volume instead.

Source: https://www.reddit.com/r/archlinux/comments/unqkuu/archinstall_btrfs_bug/

**Comment by svartkanin** [comment]
@Torxed I read through the post and I think they are both fixed, definitely the first one which was fixed here https://github.com/archlinux/archinstall/pull/1103

They stated that they were using the ISO version not the latest master so if they update it, it should work :)

**Comment by Torxed** [comment]
Then I'll go ahead and close this! Thank you for checking!
