### ISSUE TITLE
Creating new btrfs subvolumes using the partitioning tool crash the installer

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1169]
Creating new subvolumes ended up in an error every way I tried it. I would get to the screen where you choose the subvolume options (compress or nocowdata). I've tried both the compress and nocowdata options as well as leaving both blank and hitting ESC. All three attempts would end with archinstall aborting with an error I don't quite understand.

Source: https://www.reddit.com/r/archlinux/comments/unqkuu/archinstall_btrfs_bug/

**Comment by svartkanin** [comment]
I read through the post and I think they are both fixed, definitely the first one which was fixed here https://github.com/archlinux/archinstall/pull/1103

**Comment by Torxed** [comment]
User reported that this is fixed as well :)
