### ISSUE TITLE
Empty list of services results in a systemctl error

### ISSUE THREAD

**Issue by i2** [archlinux/archinstall#1175]
I like to have my user config file written in a way that can act as a template and placeholder for future edits. For instance, even though I don't need to enable a service right now. I have:

```
    "services": [
        ""
    ],
```

But this results in archinstall throwing an error that:
`arch-chroot /mnt/archinstall systemctl enable exited with abnormal exit code [256]: Too few arguments.`

Which makes sense, as my list was empty. It would be nice if this can be avoided.

**Comment by svartkanin** [comment]
@Torxed we can close this as it should be resolved with the new profile manger
