### ISSUE TITLE
archinstall abnormal exit 

### ISSUE THREAD

**Issue by Yheffe** [archlinux/archinstall#1177]
Sorry if there is a lack of information. Trying to use archinstall on my desktop after having success with a few laptops. 

archinstall fails very quickly after issuing command.

log and command output included..

I’m sure I have simply missed something in the bios.

I can’t seem find anything on this issue.

![2D962D2A-8F9B-48A1-8D48-A709CD6543DA](https://user-images.githubusercontent.com/87397594/168283429-e2edb259-0da3-4a13-8e38-099e16ba219e.jpeg)

![8586AF10-568B-4F03-B320-7DB75679A5F4](https://user-images.githubusercontent.com/87397594/168283396-ce605325-d49b-40c0-be53-9fc5e3e82912.jpeg)

Note: this is not a VM installation.

**Comment by Torxed** [comment]
I'm wondering if you have a disk label/partition label that contains native language? like `backup hårddisk` and that it causes an issue?

**Comment by Yheffe** [comment]
I am unable to scroll for some reason. But here is what I have. I also ran lsblk -b
![98F8BDAA-99FC-4CA3-92DA-2418293C1085](https://user-images.githubusercontent.com/87397594/168327826-4c16f2de-5135-40c5-8679-605c5d356e16.jpeg)
![0AB4BFCB-7E20-4B4C-9FBC-771CAA2512E7](https://user-images.githubusercontent.com/87397594/168327843-0d17841b-7dc2-4385-9e4f-5009a9b59cfa.jpeg)

**Comment by Torxed** [comment]
Unfortunately I need the string that is hidden hehe.
You can enable scrolling with `lsblk -f -o+TYPE,SIZE -J | less -S`

It's specifically the `label` field that I'm worried is weird.
Myabe `lsblk -f -o+TYPE,SIZE` will be enough tho and thus no need to scroll :)

**Comment by Yheffe** [comment]
That worked! Here is the entire output!

![image](https://user-images.githubusercontent.com/87397594/168400156-63df7c25-539d-44ae-a082-6f63a0f5535f.jpeg)
![image](https://user-images.githubusercontent.com/87397594/168400177-412981c0-fbde-445c-99b1-63617857bdb2.jpeg)
![image](https://user-images.githubusercontent.com/87397594/168400190-9ced071e-3dfb-4977-b337-3e73280e849e.jpeg)

**Comment by Yheffe** [comment]
I booted up gparted and deleted all partitions on sda1 and then rebooted into arch and now archinstall is working! But I'm still curious what happened lol I did notice the odd label on the disk...

**Comment by Torxed** [comment]
Yea it's the label for sure.
I'll see if I can add some error handling, it's going to be hard without doing `str.replace()` on weird things, or clean it before hand. As I don't think there's a flag for it to `lbslk` or the python module `json`.

But we'll get that sorted :)

**Comment by svartkanin** [comment]
We can probably close this for now as it may be resolved with the move to pyparted
