### ISSUE TITLE
Guided ISO url from readme redirects to a 403 page

### ISSUE THREAD

**Issue by rursache** [archlinux/archinstall#1178]
Clicking `Guided ISO` (at the end of [#scripting-your-own-installation](https://github.com/archlinux/archinstall#scripting-your-own-installation)) will redirect user to https://hvornum.se/archiso/ which is dead

**Comment by Torxed** [comment]
Thank you for bringing this to our attention. I have removed the dead links.
Backstory: That instruction was mainly meant to exist before `archinstall` got included in mainline repo :)
