### ISSUE TITLE
Getting a Jason serializable while installing 

### ISSUE THREAD

**Issue by Datboss420** [archlinux/archinstall#1180]
![DC170481-5A41-4BE4-8E99-870CDB09253D](https://user-images.githubusercontent.com/95149539/168405527-69f808b0-b865-41ed-a6ab-3ce031084b80.jpeg)
Can anyone help me?

**Comment by dylanmtaylor** [comment]
Very likely someone can help, but we'll need more information that. What did you try to do and which options did you select?

**Comment by Datboss420** [comment]
> Very likely someone can help, but we'll need more information that. What did you try to do and which options did you select?

I tried doing a normal install I messed up a few times by not add a desktop so I made a new install but now I’m stuck in this loop. I reached out to someone on Facebook they said it was something to do with a spelling error like a invalid character

**Comment by dylanmtaylor** [comment]
> > Very likely someone can help, but we'll need more information that. What did you try to do and which options did you select?
> 
> I tried doing a normal install I messed up a few times by not add a desktop so I made a new install but now I’m stuck in this loop. I reached out to someone on Facebook they said it was something to do with a spelling error like a invalid character

Can you please provide us with the log files from /var/log/archinstall?

**Comment by Datboss420** [comment]
> 

I tried and nothing came up

**Comment by Torxed** [comment]
I think it's your `--config` that contains something mysterious.
Could you give us your `--config` without passwords?

**Comment by svartkanin** [comment]
@Torxed probably can be closed due to inactivity?
