### ISSUE TITLE
Creating user and promoting him does not show in the script

### ISSUE THREAD

**Issue by erikdubois** [archlinux/archinstall#1182]
When you create a user I did not get the first time I have to promote him to be superuser.
It does not say I should do that anywhere.

I would assume a user can update and install his system by default.

That happened in this video at that moment in time.

https://youtu.be/boWn4KnOc24?t=281

I tested it again lateron and I noticed that we do not see that the user has been created IF we promote him.
So we are uncertain if a user has been created for that matter or if he has root privileges. 

https://youtu.be/OZAyOXb_eC4?t=65

Everything works like a charm once you know you have to take an extra step in the user.
![ArcoLinux-2022-05-14_09-01](https://user-images.githubusercontent.com/10594806/168414901-cc92c4bb-a86d-4a4b-a84f-b5d6500adf71.png)

**Comment by Torxed** [comment]
I agree that this is a bit confusing.
The option is a bit hidden and a bit unclear.

We'll re-work this for the next minor release.
Cheers for reporting it!

**Comment by erikdubois** [comment]
I love the way you have changed since last time I looked at it.
the / to search is awesome

**Comment by Torxed** [comment]
Hehe thanks @erikdubois. All credit to the new menu system goes out to @svartkanin and @wllacer who has put in hours and hours making it look the way it is :) I just merged a few PR's hehe.

**Comment by svartkanin** [comment]
Yeah we should rework this user selection to make it clearer

**Comment by erikdubois** [comment]
complimenting you on a job well done
just installed 22.06.01 of ArchLinux
the user creation is solved in a very user friendly way
kudos - I will make a video shortly for anyone who needs it
