### ISSUE TITLE
Renaming config files result in 2 configs missing warning

### ISSUE THREAD

**Issue by i2** [archlinux/archinstall#1183]
To type less when I am testing archinstall in a VM, I have renamed my config files to:
- cf.json (user config)
- dl.json (disk layout)
- cr.json (user credentials)

When I run `python3 examples/guided.py --config cf.json --disk-layout dl.json --creds cr.json`, in the menu, I get the following:
![image](https://user-images.githubusercontent.com/3228126/168438932-22cc8a57-1c9d-4069-889b-071310c7737b.png)

Now, if I click on "Save configuration" and hit Esc (even without saving any config files), that warning disappears!

**Comment by Torxed** [comment]
I think it's due to a static setup step fo the dependency checks. They don't take into consideration of what's been given in the `--conf` fully. We'll look in to it :)

**Comment by svartkanin** [comment]
@i2 I have difficulties reproducing this, could you share which configurations where reported as missing? Or did you by any chance notice which ones did not get imported from the config files?

**Comment by i2** [comment]
@svartkanin Sorry I missed this! And thanks for the fix.
