### ISSUE TITLE
Installer breaks when selecting "Select harddrives"

### ISSUE THREAD

**Issue by Stagmattica** [archlinux/archinstall#1185]
![16525669501967892472179436691100](https://user-images.githubusercontent.com/62858866/168449942-48870105-b896-41ba-b3d3-fb30d8855352.jpg)
Hello,
When I start archinstall and press Return on Select harddrives, the installer closes and I get this error output.
As I'm not very skilled with coding, I quite frankly have no idea what is happening here; sorry about that.
This is running on a Dell Latitude E5520 with an SSD upgrade. I previously had a Manjaro install with LUKS disk encryption installed but tried to clear my disk using cfdisk before attempting archinstall.

**Comment by Torxed** [comment]
It looks like it's trying to access.. a dvd?

**Comment by saikatm** [comment]
installer breaks too for me. when selecting manual partition of drives.

**Comment by Torxed** [comment]
It should now be fixed in master.
These devices are untested, and there might be other places where it breaks.
Feel free to open a new ticket and I'll squash those. Unfortunately I don't have access to these kinds of devices for testing locally.

**Comment by NorthboundPaddler** [comment]
Hey @Torxed - sorry to bring this back up, but I'm experiencing the same issue on some different hardware. I have an x86 Chromebook, with an Arch iso built using Breath. The installer crashes with the same error as soon as I hit the "drive(s)" option.

I downloaded the latest archinstall package via pacman. The image below is the output of ```fdisk -l```. Any insights on how to get this fixed?

![PXL_20220718_013630506](https://user-images.githubusercontent.com/48971077/179434435-03f46519-927f-4deb-b019-8472af43e25b.jpg)

**Comment by NorthboundPaddler** [comment]
Hey @Torxed - sorry to bring this back up, but I'm experiencing the same issue on some different hardware. I have an x86 Chromebook, with an Arch iso built using Breath. The installer crashes with the same error as soon as I hit enter on the "drive(s)" option.

I downloaded the latest archinstall package via pacman. The image below is the output of ```fdisk -l```. Any insights on how to get this fixed?

![PXL_20220718_013630506](https://user-images.githubusercontent.com/48971077/179434435-03f46519-927f-4deb-b019-8472af43e25b.jpg)
