### ISSUE TITLE
How do you use archinstall to dual boot arch and windows?

### ISSUE THREAD

**Issue by AsuxAX** [archlinux/archinstall#1198]
I basically can set any other option other than the layout.
The default wipes the disk which I don't want since I am trying to dual boot windows and arch.
And the other option seems manual and I do not know what to do and don't want to mess up with my disk.
I have a free space that is 100gb that I made before I tried to install arch linux, how do I use that?
And if possible, can I create a new efi partition for arch linux?
I don't know if I should let it use the same efi partition as windows's.
Thanks.

(I am a linux noob btw, don't know anything about arch)

**Comment by Torxed** [comment]
I'll post a video in a bit showing how. Just be careful of #1197

**Comment by AsuxAX** [comment]
> I'll post a video in a bit showing how. Just be careful of #1197

Thanks, do you mean a youtube video?

**Comment by FourteenCoast** [comment]
> > > I'll post a video in a bit showing how. Just be careful of #1197
> > 
> > 
> > Thanks, do you mean a youtube video?
> 
> That or a gif, or a writeup. But usually a video that can be paused is useful.

Any ETA for the video?

**Comment by Torxed** [comment]
> > > > I'll post a video in a bit showing how. Just be careful of #1197
> > > 
> > > 
> > > Thanks, do you mean a youtube video?
> > 
> > 
> > That or a gif, or a writeup. But usually a video that can be paused is useful.
> 
> Any ETA for the video?

It's coming, but I'm sick and I got stuck trying to improve disk encryption :)

**Comment by svartkanin** [comment]
Maybe we could put this into a wiki section on the repo, I think github has something there

**Comment by Torxed** [comment]
Im halfway done with a guide, installed windows today. Who knew it takes 1/10 the time to install a full desktop of Arch, online vs windows offline ISO medium xD

**Comment by svartkanin** [comment]
I thought it's not even possible to install windows offline at all anymore? How would they get all your data otherwise :D

**Comment by Torxed** [comment]
They "hide" the ISO download since they want you to use the data-hoarding model mainly ^^

**Comment by system32uwu** [comment]
Pretty sure just adding os_prober as an additional package does the job. Just make sure you've partitioned your disk properly from windows diskmgmt.

**Comment by Torxed** [comment]
https://youtu.be/RoTe4uAqIHA

**Comment by svartkanin** [comment]
@Torxed probably can close this :)

**Comment by StrangeGirlMurph** [comment]
@Torxed Have you thought about making a GRUB version? :) 

Creating a dual-boot system isn't really archinstall related but rather bootloader related but since you already made that systemd-bootloader video maybe you want to make a GRUB version as well.

I am having some problems with GRUB not finding the Windows Bootloader on the EFI partition. os-prober installed and grub config edited but it somehow doesn't work.

**Comment by Torxed** [comment]
> @Torxed Have you thought about making a GRUB version? :)

Hehe, I haven't used GRUB in like ~10 years so I don't think I would do a very good job at it. So I'll probably let someone with more experience do that one ^^

**Comment by ethindp** [comment]
@Torxed Can you write a writeup of the video? This video is nice but it doesn't really help individuals like me who are blind and so can't see what your doing. The key moments helped but not all that much.

**Comment by StrangeGirlMurph** [comment]
@ethindp I could do that :) I ended up using systemd-boot.
I could create a written version of the video and publish it on medium. How urgent is it?

**Comment by Torxed** [comment]
Would a subarticle of `archinstall` on the wiki be a good place perhaps?

**Comment by ognirrrats** [comment]
this was helpful

**Comment by Glitchymew** [comment]
now i can call myself an arch user ;)
oh crap i remember how cringe the name of this account was damn

**Comment by BOSS-SOFTAWARE** [comment]
I fresh installed Windows 10 on primary SSD and setup all good. Then i booted ARCH ISO from DVD and ran ARCHINSTALL. 
Went through all that stuff, nothing fancy. Set to install on the Secondary SSD and seems to be all good. But when rebooting the system, no linux based bootloader or grub, its still windows and boots into windows 10 with no option to load ARCH. 

my option now is to try a 3rd party RescueCD (hirens/paragon/UBCD tool that fixes or find OS's and fixes bootloaders, ive seen it before) 
OR 
try booting from BIOS the secondary disk (f12 on startup). It seems the bootloader is not installed over the top of windows's one on the primary disk. So dualboot from ARCHINSTALL doesnt seem to work without much effort.
