### ISSUE TITLE
Swedish language causes menu system to break

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1203]
This happens when you click `Select disk layout (Välj hårddisk-layout)` -> `Wipe all (Töm alla)` -> `btrfs` -> `yes (Ja)` -> `yes (Ja)` 
![screenshot](https://user-images.githubusercontent.com/861439/168769523-55f759d6-98aa-4c44-b95a-c5c18e80904a.png)

99.9% of all Swedes know's English so this is not a show-stopper.

**Comment by Torxed** [comment]
I did run with pre-defined config:
```
$ cp examples/guided.py ./
$ sudo python guided.py --config /var/log/archinstall/user_configuration.json --creds /var/log/archinstall/user_credentials.json
```

**Comment by Torxed** [comment]
Oddly enough, on my branch `fix-861` it breaks on English as well o0
But not before, not sure what changed.. Am I missing something in a menu secion?

**Comment by Torxed** [comment]
Ah ok, so the issue is that something else is broken, and the `Menu` tries to quit without being fully rendered.
Meaning there is no previous height to set.

**Comment by svartkanin** [comment]
I feel like I'm doing something not quite right here...

https://user-images.githubusercontent.com/19396770/168786199-ca5d897d-dd9a-4739-b242-53bfa2923225.mp4

**Comment by svartkanin** [comment]
> Because I have a .po~? Nope..

Nah that's all fine, I think they're just temporary files generated when running the script or doing translations. They should be excluded within the gitignore

**Comment by Torxed** [comment]
Haha love your hostname!

Ok I shit you not, I just jumped into another archinstall directory.
That worked.. Jumped back into the broken folder, now that works too o0

What the spooky hell?
![archinstall](https://user-images.githubusercontent.com/861439/168787061-4dadda7b-0886-464a-9c26-0f92ee182aa1.gif)

**Comment by svartkanin** [comment]
okay I pulled your branch and I get the error now oO

**Comment by svartkanin** [comment]
I think this is the actual error 
```raise ValueError(f'Selection not found: {selection_name}')```

**Comment by Torxed** [comment]
Yepp that's what I'm getting to.

**Comment by svartkanin** [comment]
let me dig a bit, this looks really strange, the problem seems to be that the spacing isn't quite right when it compares the selected menu entry

**Comment by Torxed** [comment]
Thank you for checking it out. Kind of stuck with the Yunikey implementation hehe

**Comment by svartkanin** [comment]
Okay found it, this https://github.com/archlinux/archinstall/pull/1205 should fix it :) 
That was a naughty one

**Comment by Torxed** [comment]
Oh, so a hidden menu item was causing it? Not super obvious haha

**Comment by svartkanin** [comment]
Yeah the problem was that when calculating the padding for the correct alignment it was using all menu entries available, not only the ones that are actually enabled. Which means that WYS is not WYG :)

**Comment by Torxed** [comment]
Great work!

**Comment by Torxed** [comment]
Great work!
