### ISSUE TITLE
Fails to install when enabling fstrim.timer

### ISSUE THREAD

**Issue by Steve-0628** [archlinux/archinstall#1211]
I used archinstall to create a new installation of Arch Linux on UTM(QEMU), but it gave me errors, and did not install. I'm not familier with Arch Linux, or Linux instalation, so I don't know what went wrong, or what I can do to fix this. 
Thanks. 

keyboard: jp106
mirror:japan
harddrive: ext4
root: set password
user: create one user
profile: i3wm
audio: pipewire
kernel: linux-zen
additional package: firefox
timezone: Japan
additional repo: multilab, testing
Other install settings are not modified. 
![image](https://user-images.githubusercontent.com/49326405/169049549-9dc2ff28-6eb5-4d0e-a37e-aef3a444230f.png)

**Comment by Torxed** [comment]
Can you submit the log file https://archinstall.readthedocs.io/help/issues.html#log-files? Or the `/var/log/archinstall/user_configuration.json` *(just make sure they don't contain passwords first)*

**Comment by Steve-0628** [comment]
Yes, I can. Here is the log file and user configuration file: 
[install.log](https://0x0.st/oaq0.log)
[user_configuration.json](https://0x0.st/oabr.json)

**Comment by Steve-0628** [comment]
It seems it is the same as #1212. I will close this issue for now.
