### ISSUE TITLE
Support Unified Kernel Image

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1217]
Following the guidelines of: https://wiki.archlinux.org/title/Unified_kernel_image

**Comment by codefiles** [comment]
I'm working towards improving the code for boot loaders. This is something I plan to add if you want to assign it to me.

**Comment by magicgoose** [comment]
It looks like the guided installer has a choice for UKI, but it is not saved into the .json configuration, and is also not visible in the configuration preview when installing.
I wonder if this also means that this setting would not have any effect.
