### ISSUE TITLE
We should install network-manager-applet on XFCE/MATE profiles if it's NetworkManger is chosen for networking

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1222]
Putting this here as a TODO. Would be good to have some logic in the profile code to see if the JSON key is set to install NetworkManager and install the applet accordingly

**Comment by Torxed** [comment]
As long as the profiles themselves report `True` from `Profile().is_desktop_profile()`, this should be taken care of already: https://github.com/archlinux/archinstall/blob/8d4a62e504e98f89ad7b80850ac3b280af9a9b49/archinstall/lib/models/network_configuration.py#L80-L83
