### ISSUE TITLE
Network problems using the "Use NetworkManager" option.

### ISSUE THREAD

**Issue by jorglodita** [archlinux/archinstall#1224]
When you open "Configure network" there are two main options: "copy ISO network" and "Use NetworkManager". Have found a possible bug using the second option.

In a normal install (desktop/kde/nvidia propietary) using the "Use NetworkManager" option the install ends successfully and the default Ethernet connection just works. 
The problem is that Network Manager GUI allows to create VLAN and Bridges BUT they don't work, they appear on the list but show different errors when trying to connect to them (just created VLAN and Bridges but I bet other kind of connection will have the same problem). 

Inmediate fix: a systemctl restart NetworkManager.service immediately fix the issue and makes all connections available.  

Workaround: in the "Configure network" menu select the "copy ISO network" and finish install. When finished enable NetworkManager.service, all new created interfaces will work no problem.

**Comment by Torxed** [comment]
I am not sure i fully understand. Using "Copy ISO network" does not install NetworkManager. So you would not be able to enable `NetworkManager.seevice`?
Is it possible you have competing network managers?

**Comment by jorglodita** [comment]
My first idea was to use the "Copy ISO network" option so I could install Network Manager myself, as I was having problems with the "Use NetworkManager" option. 

It was a surprise but apparently that option came with Network Manager installed but not active (so I just had to enable it, not install).

As stated I did a normal setup, using "desktop", "kde" and "NVIDIA proprietary" options. 
I just did a clean reinstall, only adding "firefox" and "spectacle" (so I could take some screenshot and write to you again).

Here is the output of Konsole:

![proof](https://user-images.githubusercontent.com/104060911/169650854-022821dd-2350-4e9a-9928-c5b1b11a84f9.png)

**Comment by Torxed** [comment]
Could you post your `/var/log/archinstall/install.log` as well?

**Comment by hellerbarde** [comment]
Maybe the KDE profile comes with NetworkManager. Accidentally or on purpose.

**Comment by Torxed** [comment]
Correct, I conclude the same in issue #1268 where it's a dependency of KDE:
> I suspect [plastma-nm](https://archlinux.org/packages/extra/x86_64/plasma-nm/) pulls in [networkmanager-qt](https://archlinux.org/packages/extra/x86_64/networkmanager-qt/) which in turn pulls in [networkmanager](https://archlinux.org/packages/extra/x86_64/networkmanager/).

Closing this as it's just a KDE "oddity" and not all users want to use NM, or even use networking.
