### ISSUE TITLE
On current master commit, HSM seems broken.

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1225]
I set a password of test and hit the use HSM option. This caused a crash.
![image](https://user-images.githubusercontent.com/277927/169656782-a3787147-5f84-4f7f-af68-8564be9eca8a.png)

**Comment by dylanmtaylor** [comment]
Also seeing this one.

![image](https://user-images.githubusercontent.com/277927/169657022-ff931271-73df-4bac-ac76-e4a464511ed2.png)

**Comment by dylanmtaylor** [comment]
Using encryption AT ALL even without HSM seems broken now.

**Comment by Torxed** [comment]
Easy fix, think I know where it breaks :) Just need to assemble a new table for the PC heh

**Comment by Torxed** [comment]
> Using encryption AT ALL even without HSM seems broken now.

This is fixed in #1234. But I'm looking in to the other thing with the HSM.
it shouldn't try HSM either, unless it was selected through the menu. It does continue past it but I don't like the log output it gives "skipping" it : )

**Comment by Torxed** [comment]
Fixed in e19ef4463052201ae4635e9dc807fe1fc4d165a3
