### ISSUE TITLE
failing on copy of boot manager

### ISSUE THREAD

**Issue by red-smeg** [archlinux/archinstall#1226]
Available partitions: {'/mnt/archinstall': Partition(path=/dev/nvme0n1p6, size=888.9, PARTUUID=1a21560d-c9e9-4d5d-be40-01d66948963e, fs=ext4, mounted=/mnt/archinstall), '/mnt/archinstall/boot': Partition(path=/dev/nvme0n1p4, size=0.3, PARTUUID=50f513f3-7bfc-419e-968d-31953d79a1d3, fs=vfat, mounted=/mnt/archinstall/boot)}
Adding bootloader systemd-bootctl to Partition(path=/dev/nvme0n1p4, size=0.3, PARTUUID=50f513f3-7bfc-419e-968d-31953d79a1d3, fs=vfat, mounted=/mnt/archinstall/boot)
Installing packages: ('efibootmgr',)
['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--path=/boot', 'install'] exited with abnormal exit code [256]: b'Copied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/systemd/systemd-bootx64.efi".\r\nCopied "/usr/lib/systemd/boot/efi/systemd-bootx64.efi" to "/boot/EFI/BOOT/BOOTX64.EFI".\r\nRandom seed file /boot/loader/random-seed successfully written (512 bytes).\r\nFailed to write \'LoaderSystemToken\' EFI variable: Read-only file system\r\n'

**Comment by red-smeg** [comment]
This is a triple boot installation on a MBP using the archinstall-mbp profile to do guided install.  Looks like a lot of install is actually happening as the / drive and the boot/efi are quite well populated.

**Comment by Lunarequest** [comment]
For context for anyone who discovers this later. Certain UEFI implementations are incomplete or so fragile that the efi variables are mounted as read-only. `bootctl` by default writes to these UEFI variables and requires that `--no-variables` be passed so it knows not to write to the efi variables.
