### ISSUE TITLE
We should exclude the read-only Arch ISO media from the list of volumes that can be used for install

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1229]

**Comment by Torxed** [comment]
Yes! maybe we exclude any RO media in general?

**Comment by dylanmtaylor** [comment]
Is this really complete? I didn't see a change related to this

**Comment by Torxed** [comment]
Oh, thought this fixed it: https://github.com/archlinux/archinstall/pull/1275
