### ISSUE TITLE
Unknown device when using erofs 

### ISSUE THREAD

**Issue by demostanis** [archlinux/archinstall#1232]
archiso supports (and it's the default in the baseline profile) erofs fs type for the airrootfs (https://github.com/demostanis/demolinux/blob/e2800eed332fde1dbc4bccab4e9aa0668a9dd683/profiledef.sh#L14).
When using archinstall, this yields to the warning `Unknown device found by all_blockdevices(), ignoring: {'/dev/loop0': ...`
An additional check should be made at https://github.com/archlinux/archinstall/blob/33ce7dbd8baf5402a20e850f503390b9c229e698/archinstall/lib/disk/helpers.py#L247

**Comment by dylanmtaylor** [comment]
Good catch, want to make a PR for it so you get credit?
