### ISSUE TITLE
problems with/improvement proposals for the manual partitioner of archinstall

### ISSUE THREAD

**Issue by Quantenzitrone** [archlinux/archinstall#1233]
with manual partitioner i mean the "Select what to do with each individual drive (followed by partition usage)"-option

The Drive Overview has not enough information, am i supposed to know the UUID's of my partitions?

So better would be:
- type only for MBR as GPT has no need for extended partitions
- full path e.g. /dev/sda1 or partition number e.g. 1
- partlabel
- partition name (retrievable with `parted <disk> print`)
- start and size in human readable format (GiB and MiB depending on the size of the number)
- filesystem: "ext4" instead of "{'format': 'ext4'}"

Also I was not able to figure out how to save my partition layout and exit from the partition menu.

Someone pls help.

**Comment by Torxed** [comment]
I think most of these things are implemented in https://github.com/archlinux/archinstall/pull/1053
Would that PR satisfy most of these things? :)

**Comment by Quantenzitrone** [comment]
yeah thanks sorry i should have looked through the prs

**Comment by Quantenzitrone** [comment]
to anyone who reads this and has the same problem before the pr gets merged:
I solved it by hitting esc to exit the manual partitioner, which selected the current partition layout without any changes. Then I saved the configuration, exited from archinstall, edited the config in nano to suit my needs and then restarted archinstall with my saved layout

**Comment by Torxed** [comment]
No worries at all, I actually don't expect everyone to look through PR's hehe. Especially `WIP` ones.
I just secretly hoped that it would solve the requirements tho, but if you feel something is missing do add it there so we won't miss it :D
