### ISSUE TITLE
Default config applied

### ISSUE THREAD

**Issue by Shinyhero36** [archlinux/archinstall#1235]
I'm using archinstall 2.4.2 and none of the info I entered is applied during installation.

![Prompt Preview](https://user-images.githubusercontent.com/36128190/169708236-c4d5b521-eb0f-4462-a8f4-c28c1e39bf0b.png)

![Before install](https://user-images.githubusercontent.com/36128190/169708377-34379168-584c-4254-a665-d4fb4cf4a228.png)

**Comment by Torxed** [comment]
In what sense is it not entered?
What are you missing? Because I see the correct partition layout, and above that I see the configuration being used, like `timezone` etc.

**Comment by dylanmtaylor** [comment]
I can see it's set to English instead of French among other things. Would be useful to have them save off their config

**Comment by Torxed** [comment]
> I can see it's set to English instead of French

Are you referring to `sys-language`? Because that's a separate menu entry behind `--advanced`.
I only see keyboard layout being set, along side archinstall TUI language.

**Comment by Shinyhero36** [comment]
> > I can see it's set to English instead of French
> 
> Are you referring to `sys-language`? Because that's a separate menu entry behind `--advanced`. I only see keyboard layout being set, along side archinstall TUI language.
> 
> If that was what you were referring to, I agree that ideally setting `fr` keyboard layout and TUI language would set the `sys-language` as well, but not sure how we can map between the two.

That's what I was referring to. I misunderstood the `sys-language`
