### ISSUE TITLE
Selecting a shell (bash, zsh, fish, etc.)

### ISSUE THREAD

**Issue by ShiGhost** [archlinux/archinstall#1236]
It would be convenient when using archinstall to choose a shell (bash, zsh, fish, etc.)

**Comment by dylanmtaylor** [comment]
You can already add it as an additional package and it's a single chsh command on the user. You can even have archinstall do it for you with the custom-commands key in the JSON schema. Not sure this is important enough to be its own menu item.

**Comment by Torxed** [comment]
I'm starting to hear more and more requests for options in the menu.
Maybe we find a clever way of offering more menu options without tainting the guided installer?

As an example, currently the two of the top requested menu additions are:
 * Selecting an editor
 * Selecting a shell

Not sure how we could solve this tho. But yea this will be a low priority for now.

**Comment by dylanmtaylor** [comment]
> I'm starting to hear more and more requests for options in the menu. Maybe we find a clever way of offering more menu options without tainting the guided installer?
> 
> As an example, currently the two of the top requested menu additions are:
> 
> * Selecting an editor
> * Selecting a shell
> 
> Not sure how we could solve this tho. But yea this will be a low priority for now.

I am strongly opposed to this, both of these could be singular packages that are added to the additional packages line. Changing shell is literally one comand (a well understood one at that) and falls under system configuration and not installation. It's just bloat, IMHO, and would add more stuff for us to test with very little benefit. I can't think of a single other distro that has shell or editor selection as part of their installation.

**Comment by Torxed** [comment]
I kind of see the point in selecting a default shell before/during installation.
As part of my automated install collection of machines, it would be nice to not have to change default shell for every user.
But I get that it's bloaty. So I'll leave this open for a bit and see if anyone else chimes in. If there's no traction I'll close this issue around 2022-06-22.

**Comment by svartkanin** [comment]
Selecting a shell or editor sounds more like a system setup requirement rather than a system installation property though. 
I think not to go down a rabbit hole with no return, it might be good to distinguish between those 2 things. there's already means to accomplish the later by specifying additional packages, performing post installation tasks or running a post installation script

**Comment by svartkanin** [comment]
> If there's no traction I'll close this issue around 2022-06-22.

A useful feature from github to set a TTL on inactive issues and just reopen them when they come back ;)

**Comment by Torxed** [comment]
> > If there's no traction I'll close this issue around 2022-06-22.
> 
> A useful feature from github to set a TTL on inactive issues and just reopen them when they come back ;)

Been meaning to setup that, but I have some legic old stuff that is still active - just slow and on a backburner hehe.
Maybe it's time I really start organizing milestones more accurately so that isn't a problem >-<

**Comment by svartkanin** [comment]
I'm happy to offer some help on that front if you like :)

**Comment by dylanmtaylor** [comment]
> I kind of see the point in selecting a default shell before/during installation. As part of my automated install collection of machines, it would be nice to not have to change default shell for every user. But I get that it's bloaty. So I'll leave this open for a bit and see if anyone else chimes in. If there's no traction I'll close this issue around 2022-06-22.


This is really easy to do without a new menu option though.
Additional packages: zsh
Custom commands: chsh torxed /bin/zsh

**Comment by i2** [comment]
> Maybe we find a clever way of offering more menu options without tainting the guided installer?

I'm wondering if an extension/plugin like mechanism can be implemented even for menu items?! As in, we have a core basic menu entries that are fundamental. And the rest menu options can be extended by plugin/extensions!

**Comment by svartkanin** [comment]
That can currently already be done by creating a new class and inheriting from the main one. We have something like that in place for the "swiss.py" implementation :)

**Comment by svartkanin** [comment]
> If there's no traction I'll close this issue around 2022-06-22.

@Torxed your words :)

**Comment by Torxed** [comment]
People seem to be very passionate about not adding this in.
I could very well see this as a sub-menu entry to the user creation now that the user creation has gotten a whole sub-menu dedicated to it.

But in all fairness, yea it's one command and has nothing to do with installation.
So either a plugin that modifies the workflow of the user creation would be a cool concept.. But I'll close this for now :)
