### ISSUE TITLE
Add an option to install the new, open-source nvidia drivers

### ISSUE THREAD

**Issue by lexika979** [archlinux/archinstall#1242]
Title says it all, it would be great to have a option to install those instead of the normal third-party or proprietary drivers.

For those who dont know yet: Nvidia recently open-sourced their linux driver.

**Comment by svartkanin** [comment]
This is already done and available in master :)

**Comment by dylanmtaylor** [comment]
> This is already done and available in master :)

Yep, I wrote this feature the day they were announced. We're pretty quick around here ;)

**Comment by lexika979** [comment]
Awesome! Thank you two very much.

**Comment by Torxed** [comment]
Just a note, @dylanmtaylor: The packager has requested us to not present this to users just yet as it apprently is still causing a lot of issues. I'm thinking a middleground would be to use `--advanced` here too?

**Comment by svartkanin** [comment]
If it's actual problems with installations we might wanna hide it all together for now or just have a massive EXPERIMENTAL message ;)

**Comment by dylanmtaylor** [comment]
> Just a note, @dylanmtaylor: The packager has requested us to not present this to users just yet as it apprently is still causing a lot of issues. I'm thinking a middleground would be to use `--advanced` here too?

We can hide it under --advanced for now.

**Comment by dylanmtaylor** [comment]
> If it's actual problems with installations we might wanna hide it all together for now or just have a massive EXPERIMENTAL message ;)

--advanced is full of experimental stuff that's partially broken, this is a perfect candidate for that.
