### ISSUE TITLE
Update translation strings

### ISSUE THREAD

**Issue by castillofrancodamian** [archlinux/archinstall#1252]
I can't find in the documentation how to update a specific translation file, for example the Spanish one, with the new strings added (or removed) in the .pot file.
Using `./locales_generator.sh` updates all languages, but this is not desired.

**Comment by Torxed** [comment]
It will update all languages, because all languages are missing the strings.
And that is fine :) It just adds empty translations on the other languages.

If you really want to only update one language, simply do:
```
git add locales/<language>/*
```
And that will update one language :)

**Comment by castillofrancodamian** [comment]
Then I will update all languages. I had understood somewhere that only 1 language needs to be updated, not all.

**Comment by svartkanin** [comment]
@castillofrancodamian running the `locales_generator.sh` script will automatically regenerate all language files which is fine. It will simply put the english text into all of them and if there's no translation provided it will use that one when displaying something. 

If you absolutely want to generate only the desired language you can run the commands from the script manually (without the loop basically) and generate only that language file.

**Comment by castillofrancodamian** [comment]
I "fixed" it with Torxed's solution and it worked fine. Simply add the desired files.
