### ISSUE TITLE
GRUB fails to install on latest master, at the end of installation

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1261]
![image](https://user-images.githubusercontent.com/277927/170793244-8a0844b1-0c28-4c14-a2a5-664553373957.png)
![image](https://user-images.githubusercontent.com/277927/170793393-57fee1d0-64fd-45fc-9358-81db2d5e5524.png)

**Comment by dylanmtaylor** [comment]
This is caused by /boot being errantly encrypted.
![image](https://user-images.githubusercontent.com/277927/170793622-3b32c986-45fd-40e4-b811-fac7d0014ffe.png)

**Comment by dylanmtaylor** [comment]
user config
![image](https://user-images.githubusercontent.com/277927/170793688-c6ef7237-3fc3-4194-a365-e89f2cb43746.png)
![image](https://user-images.githubusercontent.com/277927/170793710-e8cbebb7-f82c-44f8-b643-3ea2ec2c7679.png)

**Comment by Torxed** [comment]
Using vanilla btrfs options, no encryption:
![screenshot](https://user-images.githubusercontent.com/861439/170816919-f918a1e5-481d-4392-9b80-3ec7121dd710.png)

First time using VDA devices so I gotta check this out.

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/170817946-aaa9e2f0-75ce-4473-805b-4148ad803155.png)

Obviously something wrong with my qemu parameters.

**Comment by Torxed** [comment]
```
qemu += f' -blockdev driver=qcow2,file.aio=threads,file.driver=file,cache.direct=off,cache.no-flush=on,file.filename={hdd},node-name=node{index}'
qemu += f' -device virtio-blk-pci,id=blk_data{index},drive=node{index},bus=pcie.0,bootindex={hdd_boot_priority+index},iothread=iothread0'
```
Instead of
```
qemu += f' -device virtio-blk-pci,drive=drive-virtio-disk{index},id=virtio-disk{index},bootindex={hdd_boot_priority+index}'
qemu += f'  -drive file={hdd},if=none,id=drive-virtio-disk{index},format=raw'
```

**Comment by Torxed** [comment]
I know it's a meme, but it works on my machine with the above configuration.
![archinstall](https://user-images.githubusercontent.com/861439/170823502-f5a00305-0f19-47ac-b0fa-48dfc1ad6f5c.gif)

**Comment by Torxed** [comment]
Works with GRUB + Encryption too.
I'm testing your qemu configuration next.
But here is the GRUB + Encryption:
![archinstall](https://user-images.githubusercontent.com/861439/170823827-0d1be010-8a40-4556-a87e-14c62fe6a2b9.gif)

**Comment by Torxed** [comment]
Works with the gnome-box disk configuration too.
So there has to be something else going on here.
