### ISSUE TITLE
No network after installing via the script

### ISSUE THREAD

**Issue by Betaminos** [archlinux/archinstall#1268]
Hi there,

I have just set up a device using archinstall, opting for the KDE desktop environment and was a bit surprised to find myself inside KDE without any network access.
A quick reboot and arch-chroot later, I realized that networkmanager was already installed, but seemingly inactive.

```
[beta@oxp ~]$ nmcli
Error: NetworkManager is not running.
[beta@oxp ~]$ systemctl enable NetworkManager
Created symlink /etc/systemd/system/multi-user.target.wants/NetworkManager.service → /usr/lib/systemd/system/NetworkManager.service.
Created symlink /etc/systemd/system/dbus-org.freedesktop.nm-dispatcher.service → /usr/lib/systemd/system/NetworkManager-dispatcher.service.
Created symlink /etc/systemd/system/network-online.target.wants/NetworkManager-wait-online.service → /usr/lib/systemd/system/NetworkManager-wait-online.service.
[beta@oxp ~]$ systemctl start NetworkManager
```

As new users are unlikely to know about this, they will face some trouble in narrowing down what has happened.
I would therefore like to propose making it the default to enable networkmanager.

**Comment by Torxed** [comment]
Could you supply us with the installation log? It would greatly help with debugging why this happen.
* https://archinstall.readthedocs.io/help/issues.html#log-files

**Comment by Betaminos** [comment]
> Could you supply us with the installation log? It would greatly help with debugging why this happen.
> 
>     * https://archinstall.readthedocs.io/help/issues.html#log-files

Of course, here you go:
[install.log](https://github.com/archlinux/archinstall/files/8791336/install.log)

**Comment by Torxed** [comment]
Ok so the reason why it wasn't activated, was because in the `--config` you never selected to configure networking:
```
"nic": {}
```
However, `NetworkManager` is most likely a dependency in KDE and got pulled in?
I suspect [plastma-nm](https://archlinux.org/packages/extra/x86_64/plasma-nm/) pulls in [networkmanager-qt](https://archlinux.org/packages/extra/x86_64/networkmanager-qt/) which in turn pulls in [networkmanager](https://archlinux.org/packages/extra/x86_64/networkmanager/).

So I'll go ahead and close this. If you feel this was wrongfully closed and is still a bug, do let me know :)

**Comment by Betaminos** [comment]
Sorry to reopen this, but I would like to make sure.
I went through the normal menus / process and did not realize that I had not configured networking.
At which stage should it have shown?

Looking at my recent run through the setup, I would like to propose enabling networkmanager by default.
It seems to be rather easy to miss and cuts off the single branch to get help that a newbie can use, which is why I would like to propose going with a more approachable default.
Alternatively, the networking section could be a specific page that the user has to go through and needs to actively disable networkmanager.

**Comment by Torxed** [comment]
It's in the main menu, one of the last steps right before install :) We won't be installing or enabling anything by default. Most users want the network to be quiet unless otherwise specified :)
