### ISSUE TITLE
[critical] master installation failure: 'MapperDev' object has no attribute parent

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1269]
installation video: https://www.youtube.com/watch?v=P-ZpZne7Pks

Installation: BIOS system on KVM, wiping whole drive, encryption on. Problem: /boot is errantly encrypted and is a mapper device. This causes bootloader installation to fail.

![image](https://user-images.githubusercontent.com/277927/170831869-aeda5d62-3e55-4d54-b9ee-2cdd4b496432.png)

**Comment by Torxed** [comment]
Just FYI, fixing this will cause other issues afterwards. Because the reason why we end up here is #1271 and allowing us to go past this might have more implications hehe.
