### ISSUE TITLE
Empty input on "Select one of the above disks" quits program

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archinstall#127]
Not providing an input when asked which disk to install on causes a `archinstall.lib.exceptions.DiskError` which isn't caught and causes the application to quit. :)

Tested with 2.1.3-1

**Comment by Torxed** [comment]
This should now be fixed in [v2.1.4](https://github.com/archlinux/archinstall/releases/tag/v2.1.4) that came out yesterday. Overall we've re-worked the selection and input process quite a bit in hopes to catch more issues like this. Thanks for reporting it! :)
