### ISSUE TITLE
[critical] master installation failure: /dev/block/252:0 is not located on a partitioned block device

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1270]
installation video (sorry for not being cropped, I only recorded half my screen). https://www.youtube.com/watch?v=m2Sk7XLH0cg

Setup: UEFI on KVM, using entire drive (wipe) with btrfs and all options selected. Encryption on.

![image](https://user-images.githubusercontent.com/277927/170831969-69935cb7-7a8b-421c-8e39-b3ab120a4d66.png)

This also seems to have an encrypted /boot and shouldn't.

![image](https://user-images.githubusercontent.com/277927/170831999-1d75e6a0-5798-48b7-b37f-bb60af977d9b.png)

**Comment by Torxed** [comment]
Is it due to encryption, because i got this too yesterday but couldnt trigger it again.
