### ISSUE TITLE
Re-write the subvolume menu 

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#1278]
The subvolume menu for Btrfs is broken in some places and needs to be updated and made more user friendly. 
@Torxed I'll keep this issue here as a collective for incoming issues related to the subvolume menu system

**Comment by svartkanin** [comment]
Related issues: 
- #1151
- #1131

**Comment by Torxed** [comment]
Good idea to gather them here.
I'll write a "known issues" on the release notes and link to this one.

**Comment by dylanmtaylor** [comment]
I feel like in the partition layout screen each subvolume should be wrapped onto its own line as well. Right now it's cut off

**Comment by svartkanin** [comment]
@dylanmtaylor are you referring to the displayed table output?

**Comment by dylanmtaylor** [comment]
> @dylanmtaylor are you referring to the displayed table output?

Yes, it currently doesn't wrap and some data could be hidden
