### ISSUE TITLE
Install fails at mkinitcpio

### ISSUE THREAD

**Issue by Bugbert** [archlinux/archinstall#1284]
Same error on version 2.4.2 as well as 2.5.0

Happens with and without encryption

[install.log](https://github.com/archlinux/archinstall/files/8793508/install.log)

**Comment by dylanmtaylor** [comment]
Can you share the output of lsblk?

**Comment by Torxed** [comment]
If possible, could you also run `arch-chroot /mnt/archinstall mkinitcpio -P` and report back the error message?
If it's the same, what does `pacstrap -i /mnt/archinstall base base-devel linux linux-firmware` report?

**Comment by Bugbert** [comment]
After restarting the instalation and wiping the disk, no errors occured when installing it. I'm unsure what the error was.

**Comment by dylanmtaylor** [comment]
I guess we can close this issue as unreproducible
