### ISSUE TITLE
Partition Creation Bug in 2.5.0

### ISSUE THREAD

**Issue by ghost** [archlinux/archinstall#1288]
Wanted to test this out because I was watching a Brodie Robertson video on YouTube and I wanted to see how the installer handles it. 

When the user creates partitions, it seems to always default to 512MB as the start sector once the boot partition is created. This causes the installer to crash if more than one partition is created. IE. If the user has the installer suggest a layout that creates a seperate root and home and then decides to resize them.

Is there anyway to code the installer to read where the apprpropriate start sector SHOULD be when creating new partitions?

**Comment by Torxed** [comment]
Yes is the short answer :) The long answer of why we haven't is a bit booring, but there are reason why we haven't yet. Mainly lack of time :) But we should improve that area and experience.

**Comment by svartkanin** [comment]
This should be handled with the updated tables and sector display
