### ISSUE TITLE
Pull request templates haven't been updated for a very long time.

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1299]
They date back to around 2.2.0

**Comment by Torxed** [comment]
Yea that disturbed me heh, I'll fix it :) I'm thinking of making an issue template as well where they can get a file-upload button to easier understand what we usually require.

**Comment by svartkanin** [comment]
@Torxed I think they have been updated now, right?

**Comment by Torxed** [comment]
Ah yea, I updated this quite recently.
There's still something iffy with the tag-to-solve issue line.
But the template has changed and contains less bloat.
