### ISSUE TITLE
Needed "ESC" functionality for selecting desktop environment menu and line space below "Use ESC to skip" statement

### ISSUE THREAD

**Issue by 0xShree** [archlinux/archinstall#1301]
I found it little bit difficulty to navigate in **_selecting desktop environment_** from the menu.
If the user chose the desktop profile and didn't want to choose the desktop environments from the list, there is no skip funct. to get back to previous menu. User needs click `ENTER` it will go to **_selecting driver menu_**, there can be skipped.
![1](https://user-images.githubusercontent.com/49250702/171786941-cc3aa2d3-221b-46ae-98ab-a7d413dd439e.png)
Also it requires a line space below **_Use ESC to skip_** statement, which is much visually distinguishable
![2](https://user-images.githubusercontent.com/49250702/171786758-e1c9a3ad-90c3-4702-8fca-f0fe264e5c3e.png)

**Comment by svartkanin** [comment]
@Torxed i think we can close this as it was confirmed that it's fixed in master :)
