### ISSUE TITLE
btrfs compression not configured.

### ISSUE THREAD

**Issue by JeremiahCheatham** [archlinux/archinstall#1303]
btrfs compression is not setup even when chosen. Its not compressed and not added to fstab.

**Comment by Torxed** [comment]
i'll investigate!

**Comment by ei-ke** [comment]
I can confirm the missing compression though explicitly enabled on my cureent install.

**Comment by guerra08** [comment]
Same thing happened on a fresh install.

**Comment by Vixeliz** [comment]
Same thing here, anyone who wants to enable it after the fact see here 'https://wiki.archlinux.org/title/btrfs#Compression' you can compress existing files and add compress=zstd to your fstab.

**Comment by kassindornelles** [comment]
i can confirm, even selecting to enable compression in btrfs running archinstall with --advanced and enabling it does nothing.

**Comment by Torxed** [comment]
I'll see if I can get that sorted before tagging the full release of `v2.5.1`.
Hopefully it's just a small issue and nothing that requires too much tinkering.

**Comment by legymhueck** [comment]
I can confirm that, too.
Previously, the compression was zstd:3, now it's gone in fstab.
If possible, give the user the freedom to choose the compression level. I found that on older systems, zsdt:1 appeared snappier than zstd:3.

**Comment by xerxeslins** [comment]
I would like to confirm the same error here.

Yesterday I selected the option to install (btrfs with compression), and at the end of the installation there was nothing in fstab related to compression.

I manually added:

compress-force=zstd:15

to fstab.

But I was wondering if it would still be necessary to run:

btrfs filesystem defragment -r -v -czstd /

Anyway, the installer didn't do this automatically.

Thanks.

**Comment by Torxed** [comment]
> But I was wondering if it would still be necessary to run:
> btrfs filesystem defragment -r -v -czstd /

This is a good workaround in case people noticed the fstab issue late into their usage.
But we'll make sure it gets in there.

**Comment by Torxed** [comment]
This should now be fixed in `master`.
I'll try to test this thurrowly within the couple of days and release a new version. Thank you all for bringing this to our attention : )

**Comment by phocks** [comment]
This may be an issue here again. Just tried a fresh archinstall with btrfs and compression setting enabled, but no compression set in the fstab on system boot.
