### ISSUE TITLE
Suggestion: babysitting password strength is not a necessary step?

### ISSUE THREAD

**Issue by DoTheEvo** [archlinux/archinstall#1304]
Arch itself does not do it, unlike some other distros that by default force requirements on you.

Just maybe the script should skip judging the password and not ask for additional input of yes/no, if you are aware your password is not very secure.

Arent even actually secure passwords ridiculously long? Like 15 chars? So its more of a show of security unless it stops yelling at you after really strong password only.

**Comment by Torxed** [comment]
Personally I wouldn't mind removing the `yes/no` question, and just have a color coded (or verbose) sign that it's weak.
But then again, the number one security issue still 2022 is weak passwords wherever I've been.. So there's that too.

**Comment by svartkanin** [comment]
I really like the color coding idea! 
I fully agree that weak passwords are a venerability, but to me the strength validation kind of feels a bit intrusive, especially when people are trying to install it on a vm :)

**Comment by DoTheEvo** [comment]
Yeah, just a notice without any extra input from user would be great.
Evaluation after each character typed instead of some extra Enter key press.

btw here is the table on how characters matter, of course assuming they cant go at it at full force without forced delay or kick after failed attempts.

![pic password strength](https://i.imgur.com/gVhlDQK.png)

**Comment by Torxed** [comment]
> I really like the color coding idea!

We could use `archinstall.stylize_output(f"******", fg="orange")` for instance :)
We already have:
```diff
- red
+ green
! orange
# gray/grey
```

**Comment by svartkanin** [comment]
Sounds great!

**Comment by svartkanin** [comment]
I raised a PR to make it less intrusive. I was aiming for the "after each character" display update but the `getpass` method does not allow for such fancy things. All other options I could find all required the installation of a package unfortunately so a post eval has to suffice atm :)
