### ISSUE TITLE
Long time no feedback before "A new package mirror-list has been created"

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archinstall#131]
It took quite a while until archinstall finished creating the mirror list, in that time the programm seemed to hang after "Mounting Partition(path=/dev/sda1[...]".

The program should output what it's about to do if it takes longer than a few seconds.

Tested with 2.1.3-1

**Comment by Torxed** [comment]
I'll increase verbosity, good catch!

**Comment by Torxed** [comment]
This was fixed in v2.3.0, apologies for not closing this sooner
