### ISSUE TITLE
No connection after an installation with manual configuration

### ISSUE THREAD

**Issue by castillofrancodamian** [archlinux/archinstall#1312]
In a new installation and manual network configuration, I have not been able to connect to the internet or ping to verify and I see that adding `Gateway=ip-dns` solves it.

**Comment by svartkanin** [comment]
@castillofrancodamian thanks for reporting would you mind sharing which network configuration you did exactly? Was it using auto dhcp or manual one?

**Comment by dylanmtaylor** [comment]
> @castillofrancodamian thanks for reporting would you mind sharing which network configuration you did exactly? Was it using auto dhcp or manual one?

The title says it was manual.

**Comment by Torxed** [comment]
> > @castillofrancodamian thanks for reporting would you mind sharing which network configuration you did exactly? Was it using auto dhcp or manual one?
> 
> The title says it was manual.

It could be manual interface configuration but with DHCP or static IP?

**Comment by Torxed** [comment]
It might be me miss-remembering the options from the top of my head.
IIRC the "manual configuration" used to be called that, meaning you can manually configure each individual NIC.
But Manual could also mean static IP manual configuration.. The irony/confusion doesn't get lost on me here and we should improve the language used I think.

With static IP, did you define a gateway at all during archinstall steps?
Easiest would be if you supplied the `/var/log/archinstall/install.log` and we can check what options you gave :)

**Comment by svartkanin** [comment]
That helps a lot thanks! I can have a look at this one

**Comment by Torxed** [comment]
`gateway: null` has me worried :) Might that be the issue?

**Comment by svartkanin** [comment]
Most likely, if the dhcp is not set to auto I think the gateway is an optional field (or also with dhcp!?)

So not sure atm if this is a bug or just something that has to be remembered to be set by the user :)

**Comment by castillofrancodamian** [comment]
I don't use DHCP, I use static IP. The installer asks me for an IP for the device, a gateway and a DNS server, but I see that the gateway is not saved.

**Comment by svartkanin** [comment]
okay cool, so you did specify the gateway but it didn't save it, I'll look into that

**Comment by castillofrancodamian** [comment]
That's how it is. I enter the data and the way it asks me.

**Comment by castillofrancodamian** [comment]
Thank you!
