### ISSUE TITLE
Encrypted home partition not properly mounted when creating a manual partitioning scheme

### ISSUE THREAD

**Issue by CaptainJack42** [archlinux/archinstall#1316]
When i tried to install my System using archinstall i created a manual partitioning scheme with encrypted `/` and `/home` partitions. The `/` partition is properly mounted, however the system won't boot saying something like *Failed to mount `/home`* (I don't remember the exact message sadly and don't really want to redo my system atm). Upon further inspections i noticed that the wrong UUID (or at least one i couldn't find with `blkid`) is tried to be decrypted and mounted.

I was able to work around this by manually unlocking and mounting `/home` and booting into my user with `systemctl default`. 

I have now worked around this by unlocking the `/home` partition with a keyfile and manually adding it to `/etc/crypttab` and mounting the partition (and commenting out the old mount procedure) in `/etc/fstab`.

Here's also some information about my System if thats relevant or of any help:
```
CPU: i5-12600K
Drive: WD Blue SN550 2TB NVME SSD
Kernel: 5.15.45-1-lts (had the same problem with linux (5.17-sth) as well)
Bootloader: grub
```

**Comment by BenVosper** [comment]
This also happened to me today. Using pretty much the default install settings. systemd-boot, ext4 filesystems, separate home partition. All seemed to install fine from the live system ISO, but then upon booting I got the same error as above. I could confirm that the home partition was created correctly by unlocking it manually, but I don't know enough about the cryptsetup system to be able to correct the problem.

I gave up in the end and just used a single partition for home. That booted fine and seems to be working so far. 

Let me know if I can provide any more info

**Comment by aL3xa** [comment]
Here's a good guide for [automounting LUKS encrypted partitions](https://kifarunix.com/automount-luks-encrypted-device-in-linux/). I can confirm that my older `archinstall`-based setup (`archlinux-2022.03.01-x86_64.iso`) created unlock key for `/home` partition correctly in `/etc/cryptsetup-keys.d/homeloop.key` and has set correct UUID in `/etc/fstab`.

**Comment by svartkanin** [comment]
This is most likely resolved now with the recent updates
