### ISSUE TITLE
Drive detect

### ISSUE THREAD

**Issue by negiot** [archlinux/archinstall#1318]
Hi, the script doesn't see my second drive.  I can't use it

**Comment by Torxed** [comment]
Can you run `lsblk -a -o+TYPE,MODEL,FSTYPE,PTTYPE,HOTPLUG,STATE,MODE,VENDOR,TRAN,PKNAME` and post the output?

Apologies for the many additional fields as i cannot be sure of which is relevant to the issue at this time.

**Comment by Torxed** [comment]
Nothing really stands out, except that the drive itself is used as a partition. I son't think I've ever seen a **disk** being formatted with ext4 and used as `/`.

**Comment by negiot** [comment]
Yes nvme1n1!

**Comment by negiot** [comment]
Hi, no I don't believe. In my opinion the discs have the same id and the script only sees one.

**Comment by svartkanin** [comment]
This is probably resolved with the switch to `pyparted` if not we can reopen it
