### ISSUE TITLE
Please remove packagekit from GNOME profile

### ISSUE THREAD

**Issue by heftig** [archlinux/archinstall#1321]
Speaking as the maintainer of GNOME on Arch, please remove packagekit from the `gnome` profile.

It's split out from the rest of gnome-software for a reason - packagekit is utterly unsupported. I've never seen it work reliably and it breaks our assumptions about user attention during upgrades.

**Comment by dylanmtaylor** [comment]
You would know better than anyone else if it's okay to ship this package. https://archlinux.org/packages/extra/x86_64/gnome-software-packagekit-plugin/ I see you maintain it. It's a shame that without this the GNOME Software app doesn't work at all though, and users get the impression that their system is broken.

**Comment by heftig** [comment]
I'd rather our users not break their systems by using packagekit.

**Comment by dylanmtaylor** [comment]
> I'd rather our users not break their systems by using packagekit.

I had no idea it was that bad on Arch Linux. I will make a pull request to remove it and do the same for KDE as well

**Comment by dylanmtaylor** [comment]
By the way, is there an upstream bug with the packagekit developers tracking issues with Arch systems breaking or something?

**Comment by Armadillidiid** [comment]
> Handling system packages via packagekit is just fundamentally incompatible with our high-maintenance rolling release distro, where any update might leave the system in an unbootable or otherwise unusable state if the user does not take care reading pacman's logs or merging pacnew files before rebooting.

@heftig Is this still true today? I'm working on a tool that involves PackageKit and I'm wondering whether to disable the ALPM backend.

**Comment by heftig** [comment]
Yes, nothing fundamentally changed. Though note this isn't about ALPM itself, just how Arch Linux uses it. It is possible to make a distro using ALPM that avoids the pitfalls that make unattended upgrades dangerous.
