### ISSUE TITLE
Multiple encrypted drives, system doesn't boot

### ISSUE THREAD

**Issue by knoppmyth** [archlinux/archinstall#1325]
I wanted to test the new installer in a VM before doing a clean install on my workstation. Installing with one drive worked without issue (BTW, great job with the installer! In my 20+ years of using Linux, this is one of the best installers out there!). Since I have 2 SSDs, I decided to add another virtual drive to the VM and encrypt it. The install proceeded without issue however upon rebooting, the system would not boot.

I've included a screenshot of the error I get as well as the user_disk_layout.json.

If I boot the ISO again, I can mount and chroot my root partition. I can edit fstab and comment /data so it isn't mounted on boot. The system then boots without issue. I can then manually mount the drive.

[user_disk_layout.json.txt](https://github.com/archlinux/archinstall/files/8874948/user_disk_layout.json.txt)
![Screenshot_20220609_175521](https://user-images.githubusercontent.com/107227128/172969207-c1368630-dab5-48f8-be0d-a2a3cb982a4e.jpg)

**Comment by ebarcikowski** [comment]
I just had this problem. I had to write my own `/etc/crypttab`, as described https://wiki.archlinux.org/title/Dm-crypt/System_configuration#crypttab.

Since this was from June, I'm sure you already figured this out.

**Comment by knoppmyth** [comment]
Did a new install today with the latest archinstall (2.5.4) which resolves this issue.
