### ISSUE TITLE
Multiple Issues with BTRFS Setup

### ISSUE THREAD

**Issue by johnvilsack** [archlinux/archinstall#1326]
Running into multiple issues any time I try to do any sort of custom configuration with archinstall & BTRFS.  Submitting logs and configuration using configuration hints from here: https://wiki.archlinux.org/title/User:I2Oc9/Btrfs_subvolumes I can confirm using sgdisk and mounting manually works, but archinstall breaks.

[install.log](https://github.com/archlinux/archinstall/files/8883270/install.log)
[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/8883271/user_configuration.json.txt)
[user_credentials.json.txt](https://github.com/archlinux/archinstall/files/8883272/user_credentials.json.txt)

**Comment by svartkanin** [comment]
@johnvilsack we had some recent updates for btrfs that are available in master. Did you run the latest version from the iso or the latest master?

**Comment by johnvilsack** [comment]
I'm pulling updates from pacman before install using cowspace, but it still looks like that only got me the latest release.

I've moved past the bug inflection point, so I'll close the ticket. If I try again before a new release is pushed, I'll try gitting from master and will report back if I still have an issue.

**Comment by svartkanin** [comment]
This may be resolved by now, if not we can reopen it
