### ISSUE TITLE
Use vim modelines

### ISSUE THREAD

**Issue by kpcyrd** [archlinux/archinstall#133]
> Archinstall uses tabs instead of spaces simply to make it easier for non-IDE developers to navigate the code

This makes it harder for non-IDE developers to contribute because I have vim configured to use 4 spaces for .py files, as it is standard for python. :) If you prefer tabs, you'd need to add this line to all files so my editor picks it up:

```
# vim: set ts=4 sw=0 noet :
```

Since vim uses tabs by default I've tried to come up with a modeline that enables 4 spaces in stock vim, but vim (as shipped by Arch Linux) already does that by default.

**Comment by nogweii** [comment]
An editor-independent method of configuring tabs vs spaces is [EditorConfig](https://editorconfig.org/); it doesn't work in Notepad.exe but many editors already have built-in support or a plugin. Github itself even supports it, if you wanted to edit any of the files using the web editor. 😄

**Comment by Torxed** [comment]
Thanks to #148 this has now been implemented. Thanks for pointing it out @nogweii and thanks for the PR @Didr!
