### ISSUE TITLE
Remove discover from kde install 

### ISSUE THREAD

**Issue by HowWof** [archlinux/archinstall#1330]
Hello
As in the title I think Discover should not be installed with kde because it does not work it is not recommended to use graphical managers and removing it even without plasma meta causes plasma components to be removed by the command pacman -R $(pacman -Qdtq)
It would be nice if you could choose xorg only for Nvidia or Wayland plus an additional option for both.

**Comment by Torxed** [comment]
Are these two separate suggestions or do they belong together? IIRC Discover is the search festure in KDE and the other is nvidia specific?

**Comment by HowWof** [comment]
Yes these are 2 separate ideas 
In Discover i mean shop 
https://apps.kde.org/discover/
