### ISSUE TITLE
[Feature Request] Option for 'opendoas' instead of 'sudo'

### ISSUE THREAD

**Issue by EyeCantCU** [archlinux/archinstall#1332]
Ideally, an option would exist allowing for the use of 'opendoas' instead of 'sudo'. 'opendoas' is much smaller than 'sudo', in both size and overall footprint, generally making it easier to breakdown and configure. There could also be an additional entry to allow the use of 'opendoas' as an alias to 'sudo' to prevent possible issues with applications expecting 'sudo'.

Thank you for your time and consideration.

**Comment by Torxed** [comment]
I will go ahead and close this as we've already had a back and fourth conversation about this here: https://github.com/archlinux/archinstall/issues/947

This is not directly saying we are against it and we appreciate the suggestion :) But for now we'll stick with sudo.

**Comment by EyeCantCU** [comment]
My bad. I didn't realize it had already been proposed. Thank you for the quick reply

**Comment by Torxed** [comment]
No worries at all. Those are easy to miss :)
