### ISSUE TITLE
Add the ability to see commands

### ISSUE THREAD

**Issue by nvidiaLinuxUser** [archlinux/archinstall#1337]
Hello! The Arch Linux installer is incredibly handy. But I would like a little more customization (packages, doas instead of sudo, etc). It would be nice to be able to see (export, call it what you want) all the commands that archinstall executes without going into the installer code to make your own installer based on them (yes, I know it's better to use Arch Wiki, but still). In other words, to see what archinstall is doing under the hood

**Comment by svartkanin** [comment]
Similar to this issue https://github.com/archlinux/archinstall/issues/1047
