### ISSUE TITLE
[Suggestion] Add a tag to distinguish between DE and WM during environment selection.

### ISSUE THREAD

**Issue by Big-Iron-Cheems** [archlinux/archinstall#1338]
![image](https://user-images.githubusercontent.com/52252627/174484646-5f9aa2e7-1d09-4a90-aa6e-6311d903fda6.png)

As the title says, it would be nice for newbies to be able to easily differentiate between WM and DE in this selection.

Maybe you could add a tag between parentheses, like [DE] and [WM] (either before or after each element).

This is just a QoL addition, so feel free to implement it whenever you like.
P.S: thanks for making this amazing tool 😄

**Comment by svartkanin** [comment]
That's an easy addition :)

**Comment by svartkanin** [comment]
This has been added and is available in the latest version
