### ISSUE TITLE
Installation fails in encryption step  with DiskError and NameError

### ISSUE THREAD

**Issue by pyfisch** [archlinux/archinstall#135]
I tried to test the installer but hit this error while encrypting a partition. I followed the instructions in the [README](https://github.com/Torxed/archinstall#testing).

```
{
    "!encryption-password": "******",
    "!root-password": "******",
    "filesystem": "ext4",
    "harddrive": {
        "model": null,
        "path": "/dev/loop2",
        "size": "5G"
    },
    "hostname": "laptop",
    "keyboard-language": "l1",
    "mirror-region": {
       ...
    },
    "nic": {
        "nic": "wlp4s0"
    },
    "packages": [
        "firefox",
        "thunderbird"
    ],
    "profile": {
        "path": "/usr/lib/python3.9/site-packages/archinstall/profiles/gnome.py"
    },
    "superusers": {
        "admin": {
            "!password": "******"
        }
    },
    "timezone": "Europe/Berlin",
    "users": {}
}
```

```
Encrypting Partition(path=/dev/loop2p2, real_device=/dev/loop2, fs=ext4, rel_mountpoint=/) (This might take a while)
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.9/site-packages/archinstall/__main__.py", line 34, in <module>
    run_as_a_module()
  File "/usr/lib/python3.9/site-packages/archinstall/__main__.py", line 31, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.9/site-packages/archinstall/lib/profiles.py", line 143, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 342, in <module>
    perform_installation_steps()
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 283, in perform_installation_steps
    perform_installation(device=fs.find_partition('/'),
  File "/usr/lib/python3.9/site-packages/archinstall/lib/disk.py", line 422, in __exit__
    raise args[1]
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 265, in perform_installation_steps
    partition.encrypt(password=passwd)
  File "/usr/lib/python3.9/site-packages/archinstall/lib/disk.py", line 263, in encrypt
    return handle.encrypt(self, *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/archinstall/lib/luks.py", line 98, in encrypt
    raise DiskError(f'Could not encrypt volume "{partition.path}": {o}')
NameError: name 'o' is not defined
```

Congratulations on the inclusion in an official arch installer image! :partying_face: (Even if this turns out to be an April fools joke ;-)

**Comment by Torxed** [comment]
> Congratulations on the inclusion in an official arch installer image! 🥳 (Even if this turns out to be an April fools joke ;-)

Haha, thank you!
Easy fix to the traceback, but the reason for the issue will remain unclear until I fix that issue, which #136 should fix.
I'll run a test in a day or two and merge it once I'm back on top.

**Comment by pyfisch** [comment]
I checked out #136 the issue was that I have my locale is `LANG=de_DE.UTF-8`. The command succeeded but didn't contain the `Command successful` string:

`archinstall.lib.exceptions.DiskError: Could not encrypt volume "/dev/loop0p2": b'Die bestehende Superblocksignatur \xc2\xbbext4\xc2\xab (Offset: 1080 Bytes) auf Ger\xc3\xa4t /dev/loop0p2 wird dadurch gel\xc3\xb6scht.\rSchl\xc3\xbcsselfach 0 erstellt.\rBefehl erfolgreich.\r'`

**Comment by Torxed** [comment]
> I checked out #136 the issue was that I have my locale is `LANG=de_DE.UTF-8`. The command succeeded but didn't contain the `Command successful` string:
> 
> `archinstall.lib.exceptions.DiskError: Could not encrypt volume "/dev/loop0p2": b'Die bestehende Superblocksignatur \xc2\xbbext4\xc2\xab (Offset: 1080 Bytes) auf Ger\xc3\xa4t /dev/loop0p2 wird dadurch gel\xc3\xb6scht.\rSchl\xc3\xbcsselfach 0 erstellt.\rBefehl erfolgreich.\r'`

Ah, of course! I really should have started using exit codes earlier *(I more or less exlusively rely on them these days because of this very reason)*. I'll go over the entire code base this weekend and transform the code to use exit codes throughout instead of relying on exit messages. Great catch!

**Comment by Torxed** [comment]
Apologies for the delay in closing this issue. We’ve made sure that `SysCommand` enforces an English locale by default so that prompts get identified properly. We’ve also fixed the missing variable eons ago :) as this is fixed in master, I’ll go ahead and close this.

again, thank you for helping us improve this little beast!
