### ISSUE TITLE
Add these packages to ensure Bluetooth and ntfs partition mounting work in gnome.

### ISSUE THREAD

**Issue by iitzrohan** [archlinux/archinstall#1350]
Add the "bluez-utils" and "ntfs-3g" package while installing archlinux.
Also, make the bashrc file to include home directiries.
New users will definitely benefit from it.
Currently i have to add these lines to the .bashrc file .

{
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH
}

**Comment by JeremiahCheatham** [comment]
This is good reading.
https://github.com/archlinux/archinstall/issues/1307

**Comment by iitzrohan** [comment]
> This is good reading. #1307

Ohh, I didn't see that.
Closing this as it has already mentioned before.
