### ISSUE TITLE
archinstall do not work 

### ISSUE THREAD

**Issue by elvenaz** [archlinux/archinstall#1357]
hello, im a archuser and this is the first time y get this problem

![errorarchinstall](https://user-images.githubusercontent.com/69324978/176896832-4811c688-5bb1-4f52-8672-8cd078402b00.jpeg)

**Comment by elvenaz** [comment]
> you don't have internet.
> 
> run the command "iwctl station wlan0 connect network"

I feel so stupid,,,, Thank you

**Comment by svartkanin** [comment]
@elvenaz would you mind closing the issue if it's resolved for you now :)

We may consider catching that error and pointing to a connection problem since this seems to confuse people recently

**Comment by ZeroIntensity** [comment]
> We may consider catching that error and pointing to a connection problem since this seems to confuse people recently 

yeah i had this problem the first time i tried archinstall, would have been nice if instructions were given or it at least just told you what the problem was

**Comment by svartkanin** [comment]
Should be an easy one to capture this, I'll look into it
