### ISSUE TITLE
Suggestion : add a parameter to choose if you want parallel downloads in /etc/pacman.conf

### ISSUE THREAD

**Issue by erikdubois** [archlinux/archinstall#1358]
Here is a video that shows you we can gai, some time IF we activate parallel downloads. 

one download : 7 min 7 sec
and with
5 parallel downloads = 4 min 14 seconds
https://youtu.be/cMWXdnauAa4?t=1097

Could you consider making another line asking us if we can activate parallel downloads?
Deleting the "#" in /etc/pacman.conf would be already a great help as you see above.

**Comment by svartkanin** [comment]
This is already an option by using `archinstall --advanced`
