### ISSUE TITLE
Btrfs without subvolumes on systemd-boot doesn't boot

### ISSUE THREAD

**Issue by 1nikolas** [archlinux/archinstall#1363]
Hello I found this minor issue. I tried to install arch with btrfs but without any subvolumes (when it asks if you want any subvolumes I said no). But after the install, when I rebooted, I got an error: `mount failed no such file or directory` and it wasn't booting.
I managed to find where the problem is. On the systemd-boot config (`/boot/loader/entries/something.cfg`) there was an option with a placeholder
`rootflags=subvol=<FS_TREE>`
Since there aren't any subvolumes I removed this option and it booted just fine

**Comment by Torxed** [comment]
I believe this should be fixed now.
The solution feels silly because it's too simple.. I'm not sure this might cause issues for other complex BTRFS layouts.

Hopefully we can catch those in testing after the version is tagged and released.
Thank you for reporting this! :)
