### ISSUE TITLE
Password with only space charactors error

### ISSUE THREAD

**Issue by drakiezt13** [archlinux/archinstall#1365]
A line in source code that strip the password and lead to that error.

**Comment by gadzbi123** [comment]
you would need to add " between the whitespaces to work, simple cmd logic

**Comment by svartkanin** [comment]
@drakiez92 thanks for reporting, did you get a stack trace by any chance?

**Comment by dylanmtaylor** [comment]
I can't imagine having a password with just space characters is too common, but I guess we should try to support that

**Comment by svartkanin** [comment]
There shouldn't be an error anymore when entering a password. 
If a password with leading, trailing or just spaces is entered they will be stripped.
