### ISSUE TITLE
No inputs after default KDE installation

### ISSUE THREAD

**Issue by huoi** [archlinux/archinstall#1366]
Help me. After installing Arch, I boot to SDDM and cannot use ANY inputs (mouse, keyboard, trackpad) after a few seconds or so. Even after logging into KDE Plasma quickly, the inputs still doesn't work. Looks like a Wayland/X11 error?

I have installed KDE using archinstall on other laptops, and it worked well. However on my new laptop, this issue occurs.

The laptop model is Dell Latitude 7490 if it matters.

**Comment by 0xShree** [comment]
Hi there @huoi 
You can post on [discord help channel](https://discord.gg/cqXU88y) for any help and attach `/var/log/archinstall/install.log` while doing so :)

**Comment by svartkanin** [comment]
@Torxed I reckon this can be closed as it's impossible to debug without a log file

**Comment by Torxed** [comment]
Yea, and I'm not sure this is a `archinstall` issue either.
As the installation appears to have gone smoothly : )
