### ISSUE TITLE
Request: iso of ArchLinux contains a certain version of archinstall - update the app

### ISSUE THREAD

**Issue by arcolinuxz** [archlinux/archinstall#1367]
Is there are already an option in the tool the get the last version of archinstall from github?

So basically can we update archinstall via an easy selection.
It will help development and betatesters for sure.

Hoping that there is already an easy way...

**Comment by dylanmtaylor** [comment]
> Is there are already an option in the tool the get the last version of archinstall from github?
> 
> So basically can we update archinstall via an easy selection. It will help development and betatesters for sure.
> 
> Hoping that there is already an easy way...

You could download the CI build isos from actions to get an ISO of any commit. It's also in the readme how to test a development branch of archinstall

**Comment by niluzz** [comment]
> Is there are already an option in the tool the get the last version of archinstall from github?
> 
> So basically can we update archinstall via an easy selection. It will help development and betatesters for sure.
> 
> Hoping that there is already an easy way...

It would really be a good one, it would make it a lot easier!

**Comment by dylanmtaylor** [comment]
Well, for development ISOs, we have https://github.com/archlinux/archinstall/actions/workflows/iso-build.yaml

And if you have an old ISO, you can use pacman -S archinstall to pull in the latest package.

I'm not sure we need a menu option to update archinstall.

**Comment by dylanmtaylor** [comment]
You can download the ISO file for any one individual commit.

![image](https://user-images.githubusercontent.com/277927/178039003-8b1129fe-10f9-4372-9cf0-b89e11fd55bf.png)

**Comment by svartkanin** [comment]
I would say updating the app inside the app is not a good idea. Handling references to installed versions may be quite difficult especially all different ways archinstall can be installed (pip, archinstall, github etc.)
