### ISSUE TITLE
/mnt/archinstall is not a directory

### ISSUE THREAD

**Issue by rado84-github** [archlinux/archinstall#1370]
I tried installing arch through the script in a VM and I got this error: "/mnt/archinstall is not a directory".

![Picture_created_10-07-2022_16-33-05](https://user-images.githubusercontent.com/41172201/178147498-309c1d4d-be6f-48de-90a8-fc59121f8020.png)

**Comment by wllacer** [comment]
@rado84-github 
it seems you didn't selected/defined any target mountpoint to install into.  The installation scripts mounts all the targets under the `/mnt/archinstall` but only creates it if there is something to do there. And from the log there isn't

**Comment by rado84-github** [comment]
I did. I created mount point / as it's always the default point in all distros and when it asked me where to save all changes (user, disks, etc.) I chose / again bc I didn't know what else to write there. But I'll check what you said about json.

**Comment by svartkanin** [comment]
This is most likely resolved with the latest changes
