### ISSUE TITLE
Crashes if `additional-repositories` is omitted from config

### ISSUE THREAD

**Issue by wpaivine2** [archlinux/archinstall#1386]
When running the archinstall script from the command line, if `additional-repositories` is omitted from the config, this causes a crash.

Config files:

<details>
<summary>
user_configuration.json
</summary>

```
{
    "audio": "pulseaudio",
    "config_version": "2.5.0",
    "debug": false,
    "gfx_driver": "VMware / VirtualBox (open-source)",
    "harddrives": [
        "/dev/sda"
    ],
    "mount_point": null,
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "iso"
    },
    "plugin": null,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/xorg.py"
    },
    "script": "guided",
    "silent": true,
    "version": "2.5.0"
}
```

</details>

<details>
<summary>
user_disk_layout.json
</summary>

```
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
```

</details>

<details>
<summary>
user_credentials.json
</summary>

```
{
    "!users": [
        {
            "!password": "examplefakepassword",
            "sudo": true,
            "username": "exampleusername"
        }
    ]
}
```

</details>

Installation command:

```
archinstall --silent --config user_configuration.json --creds user_credentials.json --disk_layouts user_disk_layout.json
```

Error:

```
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 281, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 307, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 137, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/installer.py", line 159, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 184, in perform_installation
    enable_testing = 'testing' in archinstall.arguments.get('additional-repositories', None)
TypeError: argument of type 'NoneType' is not iterable
```

It seems the error arises from the following lines expecting an iterable, so perhaps changing the default value from `None` would fix it.
https://github.com/archlinux/archinstall/blob/5c3c1312a49e1c110d4c5825fbb8242868544900/examples/guided.py#L184-L185

However, I'm a bit confused because the config [schema](https://github.com/archlinux/archinstall/blob/870da403e79ab50350803b45f200e0b272334989/schema.json#L7-L14) seems to suggest that this should be an `enum` value, not an iterable (so an equality check would suffice). But this is further complicated by the fact that the TUI seems to suggest you can select _both_ `testing` and `multilib` (although to make things more confusing, if you try to select both, only one will be inserted into the output string array value, e.g.
```
"additional-repositories": [
    "multilib"
],
```
is the result I get when I tried to check both boxes). 

It looks like the schema should be updated, or the code, or maybe both?

**Comment by vcup** [comment]
I'm also got this error, but i did't check additional-repo.
 if remove --silent flag, they can be install success , by manual operating, but I need this((

**Comment by codefiles** [comment]
The feature in the guided installer that allows one to save a `user_configuration.json` file does not populate defaults that are shown in the guided installer. When using the `--silent` argument to `archinstall` it also does not populate these same defaults if they are missing from the `user_configuration.json` file. Instead archinstall crashes when it arrives upon a missing argument.

One can capture these defaults in a `user_configuration.json` file by running the guided installer then selecting the install option. When prompted "Press Enter to continue." use Ctrl-C or other means of sending a SIGINT to archinstall to abort the install. This will create the file `/var/log/archinstall/user_configuration.json` which will be populated with the defaults shown in the guided installer. Using this configuration file with the `--silent` argument provided to `archinstall` will avoid any crashing caused by one of these missing arguments.

Here is a diff of the `user_configuration.json` file @wpaivine2 provided and one created using the steps given above.
```diff
 {
+    "HSM": null,
+    "__separator__": null,
+    "additional-repositories": [],
+    "archinstall-language": "English",
     "audio": "pulseaudio",
+    "bootloader": "systemd-bootctl",
     "config_version": "2.5.0",
     "debug": false,
     "gfx_driver": "VMware / VirtualBox (open-source)",
     "harddrives": [
         "/dev/vda"
     ],
+    "hostname": "archlinux",
+    "kernels": [
+        "linux"
+    ],
+    "keyboard-layout": "us",
+    "mirror-region": {},
     "mount_point": null,
     "nic": {
         "dhcp": true,
         "dns": null,
         "gateway": null,
         "iface": null,
         "ip": null,
         "type": "iso"
     },
+    "ntp": true,
+    "packages": [],
     "plugin": null,
     "profile": {
         "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/xorg.py"
     },
+    "save_config": null,
     "script": "guided",
-    "silent": true,
+    "silent": false,
+    "swap": true,
+    "sys-encoding": "UTF-8",
+    "sys-language": "en_US",
+    "timezone": "UTC",
     "version": "2.5.0"
}
```

**Comment by svartkanin** [comment]
I just confirmed that this should not longer happen
