### ISSUE TITLE
Key problem

### ISSUE THREAD

**Issue by Obema12** [archlinux/archinstall#1387]
I noticed that sometimes there is a problem with the keys:

![1](https://user-images.githubusercontent.com/109589272/179887190-24b63a0e-03c8-4f7f-9aa5-5b8645f1dd9e.png)

An attempt to update the package fails:

![2](https://user-images.githubusercontent.com/109589272/179887278-067b5073-4a1f-4355-b900-60bdca0217a1.png)

I can try to run the installer after a while and the problem goes away, which is weird because I'm using the same arch.iso...

Any thoughts on this?

**Comment by gamingmsi** [comment]
I just saw your post, I also have the same issue and it doesn't go away even after I try later.
Maybe **Christian Hesse** aka **eworm** messed something up with the signature. Interestingly I was able to install it just fine earlier this month.
