### ISSUE TITLE
Missing polkit package as dependence when install swaywm

### ISSUE THREAD

**Issue by Sharelter** [archlinux/archinstall#1388]
When I tried to install swaywm via archinstall I cound not start sway after reboot.

I found [this](https://wiki.archlinux.org/title/Sway#Starting) from archwiki.

I think that it will be better to install [polkit](https://archlinux.org/packages/?name=polkit) package when install sway via archinstall.

**Comment by Torxed** [comment]
We already have [systemd-logind](https://man.archlinux.org/man/systemd-logind.8) which appears to be recommended as well. That would avoid installing further packages.

Could that be an alternative?

**Comment by Sharelter** [comment]
Yeah It could. Sorry for my lack of logind knowledge.

**Comment by Torxed** [comment]
No worries, but perhaps we need to configure `systemd-logind` properly which I assume we don't currently.
