### ISSUE TITLE
Disk is not changing

### ISSUE THREAD

**Issue by DHCPCD9** [archlinux/archinstall#1402]
Hello everyone, I found a bug which is doesn't changing disk if you already choose one.

How to reproduce:
- Select disk
- Select another one
- And on install/pratition managing you will see first disk instead of second.

**Comment by svartkanin** [comment]
@DHCPCD9 sorry but I can't reproduce this, could you try to run this on the latest master and see if it still happens?

**Comment by svartkanin** [comment]
This should be fixed
