### ISSUE TITLE
TypeError: object of type `NoneType` has no len()

### ISSUE THREAD

**Issue by raiguard** [archlinux/archinstall#1405]
When setting up a user account with no password (leaving the password field blank), archinstall crashes. I am using the latest arch ISO (07.01). I'm going to set a password anyway and just use auto-login (I'm using full disk encryption and don't want to type two passwords), but this shouldn't crash.

**Steps:**
- `archinstall`
- Select `User account`
- Enter username
- Leave password blank and hit enter
- Select `no` for superuser
- See crash

I am unable to upload an image of the stacktrace from either my phone or my PC due to a certificate error. Luckily, it's easy to reproduce.

**Comment by svartkanin** [comment]
Thanks for reporting, I'll have a look at it :)

**Comment by svartkanin** [comment]
@raiguard apologies for the very late response, I can't seem to be able to reproduce this one.
I think this might have already been fixed and should work in master. If you could try it there just to confirm that would be great!

**Comment by svartkanin** [comment]
Okay I was able to confirm that the error exists on the latest ISO release but is fixed in master, so I think we can close this @Torxed
