### ISSUE TITLE
Adding "multilib" repository to optional repositories enables "multilib-testing" as well.

### ISSUE THREAD

**Issue by reedlove** [archlinux/archinstall#1407]
I somehow doubt that this is the desired behavior?
Certainly caused me some issues after I installed a 32-bit package with lots of dependencies. ;P
Luckily it wasn't hard to figure out what had happened. =D
I've also been able to duplicate the same behavior with the "archlinux-2022.08.05-x86_64.iso" installation image.

**Comment by gamingmsi** [comment]
Yeah I can confirm, this happened to me too. I've received conflicting info in terminal from multilib and multilib_testing, so during install I don't select any additional repositories but after installation I just enable multilib in pacman.

**Comment by Torxed** [comment]
We merged a fix 9 days ago: https://github.com/archlinux/archinstall/pull/1364
Does the latest [developer ISO](https://github.com/archlinux/archinstall/actions/runs/2827393795) also cause these issues?

**Comment by reedlove** [comment]
It looks like the problem was fixed. =
![VirtualBox_Arch Testing_12_08_2022_16_14_58](https://user-images.githubusercontent.com/11276590/184456027-c3fc8d49-79bd-4715-a11a-ebeab29dc609.png)
]

**Comment by Torxed** [comment]
Ah yes, thought the PR would close this one.
It's fixed in `master` but we haven't dropped a version yet so archiso will have this issue.

I'll try to release a new version in a couple of days.
