### ISSUE TITLE
Change Europe/Kiev timezone to Euroupe/Kyiv

### ISSUE THREAD

**Issue by smolovk** [archlinux/archinstall#1408]
In timezone selection there is Europe/Kiev timezone. Here is an [article](https://www.atlanticcouncil.org/blogs/ukrainealert/kyiv-not-kiev-why-spelling-matters-in-ukraines-quest-for-an-independent-identity/) about why is it important to change it.

**Comment by svartkanin** [comment]
@smolovk the timezones are taken from `timedatectl --no-pager list-timezones` so this is not something that should be raised with archinstall but rather `timedatectl`

**Comment by smolovk** [comment]
> @smolovk the timezones are taken from `timedatectl --no-pager list-timezones` so this is not something that should be raised with archinstall but rather `timedatectl`

oh, ok, sry, thanks for response
