### ISSUE TITLE
TypeError: Object of type Language is not JSON serializable

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1409]
![screenshot](https://user-images.githubusercontent.com/861439/183645924-e00bc416-72b7-432f-aba5-fdfcd0db51d4.png)

I'll push a fix for this in a bit, but saving here to track some issues I found while installing using latest `master`.

**Comment by svartkanin** [comment]
I see so the language is exported in the configuration files, it is most likely not deserialized though. So we could either remove it from the export or also apply it if it's set in the config

**Comment by Torxed** [comment]
I merged #1410 which adds serialization support to the class via `Language.json()`, it's a generic helper entry point that our JSON serializer looks for. It converts `Language` to `Language.lang` (not `.abbr`).

I think that's good enough? That way the UI can load the language between each installs and the user doesn't have to re-pick the language when re-using a conf? I haven't tried but I'd imagine that's how it works hehe
