### ISSUE TITLE
locale.conf is wrong if you choose en_US utf-8

### ISSUE THREAD

**Issue by xerxeslins** [archlinux/archinstall#1413]
During installation, I chose "en_US.UTF-8" for Locale Language.

And at the end of the installation (after reboot) the "locale.conf" file had:

en_US.UTF-8.UTF-8

should be: **en_US.UTF-8**

I believe that once "en_US.UTF-8" is chosen, the "locale encoding" should not be added again.

Thank you.

**Comment by Torxed** [comment]
Closing as duplicate of #1200
