### ISSUE TITLE
bspwm really disapoint

### ISSUE THREAD

**Issue by maxmx03** [archlinux/archinstall#1417]
It was just a black screen... nothing more to say, just black screen

**Comment by maxmx03** [comment]
my pc:
ryzen 2700
amd rx 590 8gb
16gb

**Comment by Torxed** [comment]
I get that it might be frustrating, and we'd love to see if we can fix it.
But we'll need more information than your screen was black.

Do you have the xorg log, `/var/log/archinstall/install.log` or any other debug information?
Perhaps `dmesg` can give some clarification?

:warning: Before posting `install.log`, make sure https://github.com/archlinux/archinstall/issues/1062 didn't hit you during installation!

**Comment by maxmx03** [comment]
i will use archcraft instead, i know is expect to open bspwm with a black screen but i tried to open a terminal with super + enter and didnt work, arch installation with bspwm doesnt have any default config?

**Comment by Torxed** [comment]
> arch installation with bspwm doesnt have any default config?

No there's no default configuration for bspwm. I don't use the WM myself but IIRC that's one of those WM's that is very user centric, every setup will be unique and I don't think we have a way of setting it up that won't go against most setups.
Again, this is just me guessing.
Perhaps we could use the example configuration from `/usr/share/doc/bspwm/examples/`, but I'm not sure that would do anything out of the box?

**Comment by maxmx03** [comment]
I saw a tutorial video on youtube, he install xorg bspum sxbkd on debian and then he copied the examples configuration

this is what he did.
```
mkdir .config/bspwm
mkdir .config/sxbkd

cp /usr/share/doc/bspwm/examples/bspwm ~/.config/bspwm
cp /usr/share/doc/bspwm/examples/bspwm ~/.config/sxbkd
```

i will try to again.
