### ISSUE TITLE
installer breaks when using manual partitions

### ISSUE THREAD

**Issue by saikatm** [archlinux/archinstall#1422]
- added manual partition using `cfdisk` 
- did not format
- selected manual partitions from the installer
- selected format, mount point, and file system type using the installer
- installer breaks while starting the install 
-
here is the log file: https://0x0.st/o2Ly.log

**Comment by Torxed** [comment]
Unfortunately I don't see exactly what broke.
The log ends without any traceback, maybe something we need to tweak.

But I've never tried the following:
```
{
                "ESP": false,
                "PARTUUID": "",
                "boot": false,
                "encrypted": false,
                "filesystem": {
                    "format": "linux-swap"
                },
                "mountpoint": "swap",
                "size": 2097152,
                "start": 4196352,
                "type": "primary",
                "wipe": true
},
```

Instead select swap from the main menu and it should.
If that doesn't fix it, would you mind screenshotting or extracting the traceback from the screen during installation?

**Comment by kazuhiroshigeru** [comment]
I can confirm this issue afer running the script on a vm. I made the partitions with gparted live iso and with archiso cfdisk and when trying to mount and format with the script, it breaks and fails to install. also there's no option afaik for swap partitions but only zram swap.

**Comment by Torxed** [comment]
> there's no option afaik for swap partitions but only zram swap.

That is correct!

> I made the partitions with gparted

Do you have the `user_disk_layout.json` and `user_configuration.json` by any chance?
That way I can try to reproduce it (it's fine if the start blocks etc differ, I can tweak that on my side).

**Comment by kazuhiroshigeru** [comment]
> > there's no option afaik for swap partitions but only zram swap.
> 
> That is correct!
> 
> > I made the partitions with gparted
> 
> Do you have the `user_disk_layout.json` and `user_configuration.json` by any chance? That way I can try to reproduce it (it's fine if the start blocks etc differ, I can tweak that on my side).

nvm. what I did was to disable swap when being asked and mounted the partitions that I already made on gparted then set the mounting points and it's working fine now.  wish that the option to make oldschool swap partitions was avaliable or use cfdisk to partition.

**Comment by Torxed** [comment]
You can export them with: https://archinstall.readthedocs.io/help/issues.html#log-files

Be mindful of https://github.com/archlinux/archinstall/issues/1062 if you're using the latest stable version. Fixed in `master` I believe.

**Comment by saikatm** [comment]
@Torxed just tried on my laptop instead of KVM. 
please take a look > https://0x0.st/o_Nr.log

**Comment by Torxed** [comment]
> @Torxed just tried on my laptop instead of KVM. please take a look > https://0x0.st/o_Nr.log

Thanks! So the culprit is 99% the swap setup (probably obvious).
We don't have any support for `swap` currently, meaning we don't have any code that can run `swapon` and/or partition it with the right partition type.

We should probably gracefully handle that tho and not allow it to be a part of the setup.

**Comment by saikatm** [comment]
@Torxed is it possible to add swap after the installation?

**Comment by Torxed** [comment]
> @Torxed is it possible to add swap after the installation?

Yes, as long as you don't force `archinstall` to perform any file operations (aka, don't mark the partition for `wipe: True` or `format: True`) and just pre-create it outside of archinstall so there's a slot for it on the drive.
Then you can run `swapon` after everything is installed.

A bit of an inconvenience, but that's the best we can offer now I'm afraid.

**Comment by kazuhiroshigeru** [comment]
> > @Torxed is it possible to add swap after the installation?
> 
> Yes, as long as you don't force `archinstall` to perform any file operations (aka, don't mark the partition for `wipe: True` or `format: True`) and just pre-create it outside of archinstall so there's a slot for it on the drive. Then you can run `swapon` after everything is installed.
> 
> A bit of an inconvenience, but that's the best we can offer now I'm afraid.

oh well, I will try to install arch without a swap partition then make it after installing arch. I hope you add support for swap partitions and other swap methods. 
will send the log and json if archinstall breaks again.

**Comment by Torxed** [comment]
Thank you, I will close this for now as it's a known issue that might get resolved later.
There's some things to really look out for tho when using traditional swap, mainly surrounding disk encryption and how it can impact security.
