### ISSUE TITLE
archinstall couldn't find file: file guided does not exist

### ISSUE THREAD

**Issue by UriZafrir** [archlinux/archinstall#1428]
Hi All
I am trying to install arch linux on mac m1 UTM.
I found an ISO online.
https://github.com/JackMyers001/archiso-aarch64/releases
I know it's not up to date this is why I try to update archinstall. I tried simply installing it but it gave me errors.
pacman -Syyu
![image](https://user-images.githubusercontent.com/35652384/185785587-2d3eb77d-7f0f-4459-9bcc-ef32264657f4.png)

So ignoring the previous idea I try to update archinstall alone.
When install boots up I do 
pacman -Syy
then pacman -S archinstall to have a latest version of it.
![image](https://user-images.githubusercontent.com/35652384/185785152-6c506142-81aa-4737-ba2a-82edbc406288.png)

after that I get this error:
![image](https://user-images.githubusercontent.com/35652384/185785164-777b4a50-9f03-459e-8ee6-b0c120222c34.png)

Then I try to install archinstall with 
pip3 install archinstall
 
![image](https://user-images.githubusercontent.com/35652384/185785368-97e7d7cd-1e87-4f31-8526-7395bf7350e8.png)

Then I get the following error:
![image](https://user-images.githubusercontent.com/35652384/185785379-baec1c5f-b5d2-4537-9e6f-2b103861409a.png)

which I don't know what to do with.
I assume having an updated ISO of arch64 would work too.
Please help.

**Comment by Torxed** [comment]
> ![img](https://user-images.githubusercontent.com/35652384/185785164-777b4a50-9f03-459e-8ee6-b0c120222c34.png)

Can you try running `python -m archinstall` here?
I'm not quite sure why the entrypoint helper in `/usr/bin` wouldn't find `archinstall` after installing, but circumventing the entrypoint helper and going straight for the python module might help.

Maybe the Mac ISO is running different python versions or something?

**Comment by UriZafrir** [comment]
thanks that works.
But I still get to the same errors I had without updating archinstall:

![image](https://user-images.githubusercontent.com/35652384/185872257-83aa41f1-d927-4374-b92e-fb8a3130497c.png)

after that I try doing what this link says:
https://unix.stackexchange.com/questions/179763/i-cant-create-fstab-while-installing-arch
mkdir /mnt/etc
genfstab /mnt >> /mnt/etc/fstab
mount -o remount,rw /


and I get 
![image](https://user-images.githubusercontent.com/35652384/185873104-d516e3cc-debd-43d9-9f36-1306ea804049.png)


This is the output from /var/log/archinstall/install.log
![image](https://user-images.githubusercontent.com/35652384/185879624-47dc5519-2d33-44fb-8494-964dab658093.png)


I know this isn't about connectivity because I can ping 8.8.8.8
![image](https://user-images.githubusercontent.com/35652384/185873387-c881df34-ea64-4f46-8661-7a18efc4d472.png)

after trying pacman -Sy I get:
![image](https://user-images.githubusercontent.com/35652384/185873195-4894989e-10f3-4e04-91d1-35ed8f6fa38c.png)

Tried searching the error on google but didn't manage to find a solution.
will setting dns to google help?


Some answers tell me to 
rm /var/lib/pacman/db.lck f
but I don't have that file. 

when trying pacman -Sy --debug:
![image](https://user-images.githubusercontent.com/35652384/185875158-9a939128-14f0-4fb3-a36a-bbdec11af298.png)

I guess the relevant line is the one where curl returns result 0.
but when I
curl www.google.com
I do get the webpage.

**Comment by Torxed** [comment]
> ![img](https://user-images.githubusercontent.com/35652384/185872257-83aa41f1-d927-4374-b92e-fb8a3130497c.png)

So this gives some indications that the setup has not gone right.
Archinstall when run "vanilla" mounts to `/mnt/archinstall` and will setup all mounts for you.

So I'm wondering if you are trying to mount things yourself and run it with "existing mounted volumes" (which we support)?

The package issues are a different issue in of itself, and that is something that will be very specific with archlinuxarm, something I have no idea how to solve sadly : /

**Comment by UriZafrir** [comment]
Thanks.
I'm not trying to mount anything by myself.
the only place in the install script that is maybe connected to what you wrote is this:
![image](https://user-images.githubusercontent.com/35652384/185903473-183318f1-2250-46f3-9058-fa94b3d83618.png)
When I encounter this I choose second option - /dev/vda.
Even when I try to leave it blank i encounter the same error...
Is there someone else who could help me?
thanks in advance.

**Comment by Torxed** [comment]
Oh, that's a really old version of archinstall.
I don't think you got the newest versions heh.

**Comment by UriZafrir** [comment]
I know.
I was looking for an ISO install but this is the only one I got.
When using archboot I got a different set of errors..
https://github.com/utmapp/UTM/issues/4326

**Comment by Torxed** [comment]
I think I'll close this ticket as most of these things are irrelevant to the archinstall project.
Archboot is written by Tobias over on gitlab: https://gitlab.archlinux.org/tpowa/archboot

And we'd need an up to date version of archinstall to debug these issues.
