### ISSUE TITLE
Enabling multilib repo also enables multilib-testing repo

### ISSUE THREAD

**Issue by gamerking64** [archlinux/archinstall#1430]
In the installer there is an option to select extra repos, after selecting multilib repo alone it always enables multilib-testing repo too after installing the system, ofc i saw the multilib-testing repo when running pacman -Sy... So plz if you can fix this very simple issue, maybe im gonna make a pull request if possible... Thanks in advance!

**Comment by Torxed** [comment]
Thsi is fixed in `master`, see https://github.com/archlinux/archinstall/pull/1424.
