### ISSUE TITLE
More options to pick than one in "Locale language" and "Locale encoding".

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1435]
If I want en language and other one with special letters there is no option to do that. I would suggest to add check boxes just like in "Mirror region".

**Comment by Torxed** [comment]
I believe this is what https://github.com/archlinux/archinstall/pull/1423 is aiming to do? Or at least to some extent.
There's no reason why we don't have multi-select, good call! :)

**Comment by eskiq** [comment]
Yes, that would probably solve the problem in half bcs "Locale encoding" also need that ability to make special characters working for specific language . Otherwise there would be post installation configuration for the same thing when somebody need those special letters for some languages.

**Comment by codefiles** [comment]
The plan is to have multi-select and #1423 sets up what is needed to implement this into the guided installer. This will be in a follow up pull request. @Torxed, you can assign this to me if you would like since this is what I'm working towards.

**Comment by codefiles** [comment]
Waiting for #1423 and #1458 to be merged before submitting a pull request for this.
![locales](https://user-images.githubusercontent.com/11915375/189510847-ada4f25a-2e39-43d1-abf6-f8f1a400d16a.gif)

**Comment by Torxed** [comment]
@eskiq any reason for closing this? As there's no PR for it ready yet AFAIK.

**Comment by eskiq** [comment]
@Torxed I was thinking that it would be not useful to keep that thread open. Forgive me.  : D

**Comment by codefiles** [comment]
@eskiq would you please reopen this issue since it has not been resolved yet?
