### ISSUE TITLE
Grub as a default option.

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1437]
Script suggest to use btrfs, so it would be better to use it with grub. It seems that snapshots are way more easy to manage when using with grub. The script itself is aiming at simplifying things so why systemd bootlader with btrfs?

**Comment by Torxed** [comment]
In what way is it easier with Grub? (I don't use grub very often so I don't know what the benefit is of grub in this case)

**Comment by eskiq** [comment]
I would also prefer to use systemd bootloader as this is what I get to use with ext4. Btrfs is completely new to me so forgive my stupidity. In this [video](https://youtu.be/8mEjwn_AjuQ?t=226) dude is suggesting to use grub. I looked into wiki [Booting into snapshots](https://wiki.archlinux.org/title/Btrfs#Booting_into_snapshots) and it looks like grub can easily auto generate snapshots with grub-btrfs package while systemd boot require manual fstab edit or additional script to do it automatically?

I also don't have noatime and compression in fstab just like the same dude in the same [video](https://youtu.be/8mEjwn_AjuQ?t=443).

**Comment by Torxed** [comment]
The fstab was brought to my attention yesterday and I'll investigate that: https://discord.com/channels/726808923662712894/726809631342592081/1013089654918107156

Regarding btrfs snapshots I haven't used it from the boot menu myself so I'll have to look in to that as well.

**Comment by eskiq** [comment]
I concluded that booting from snapshots is very interesting but not necessary for me, so instead I'll use systemd boot.
