### ISSUE TITLE
Red arrow instead of blue in main menu.

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1438]
Not everything need to be blue xD. The red arrow would have better contrast and would look more elegant. I'm just nitpicky. Maybe vote for color? Any color like red, green, yellow or orange would just stand out more instead of blending so much with blue background box of the option in the menu next to it. The light blue color most likely was used because it reminds arch logo more and stands out more than dark blue one.

**Comment by svartkanin** [comment]
I personally have issues identifying colors quite often, and red on black is imho more difficult to see :) 
![image](https://user-images.githubusercontent.com/19396770/188862663-7cf8380d-edab-41d9-8402-b8cedb2baa40.png)
![image](https://user-images.githubusercontent.com/19396770/188862739-c9b08efe-654c-4668-9d7f-419fe2be4390.png)

**Comment by eskiq** [comment]
What about green or yellow, orange? I would pick any instead of that bluish. : D
