### ISSUE TITLE
Migrate away from using "harddrives" in --conf and rely on --disk-layout souly

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1439]
This is a non-time-critical issue and can be done whenever really.

So the background to me creating this issue is mainly nit picking.
The current state works, but this would eliminate issues when people modify their `--disk-layout` to include a secondary drive but forget to adding it to `--conf`.

Assuming `--disk-layout`:
```json
{
    "/dev/sda": {
        "partitions": [
            ...
        ],
        "wipe": true
    },
    "/dev/sdb": {
        "partitions": [
            {
                ...
            }
        ],
        "wipe": true
    }
}
```

But `--conf` contains:
```json
{
    "harddrives": [
        "/dev/sda"
    ],
    ...
}
```

There will be an error where `device_instance` is never set for `/dev/sdb`, because it never got put through: https://github.com/archlinux/archinstall/blob/65212a46aa43fadb2b0ee88b46b573765d7be9f9/examples/guided.py#L128-L131

Moving to `--disk-layout` filtered list of harddrives makes more sense.

**Comment by svartkanin** [comment]
This would be awesome :)

**Comment by Torxed** [comment]
Hehe indeed, I spent around a week trying to figure out why my configurations didn't work when debugging all the other issues. Turns out I forgot to add `/dev/sdb`.. So I'm very much in favor of getting this done in time for the v2.5.2 or thereabout ^^

For now I'm pretty satisfied with the state to release v2.5.1 tbh. As it's a lot of small patches that really needs to get out there.

**Comment by svartkanin** [comment]
This should be resolved as we switched to a single config file
