### ISSUE TITLE
Option to change the kernel package used during installation

### ISSUE THREAD

**Issue by matteoturini** [archlinux/archinstall#145]
I would like to use linux-zen!

**Comment by Torxed** [comment]
I'll deliver on your request some how, this is something a lot of people seam to want.
But the guided installer might keep it simple - and adding custom (potentially unsupported kernels) will be optional.

So I'll have to separate the "official installer" which is guided and these some what exotic features :) But i'll come!

**Comment by matteoturini** [comment]
I think it would be nice to make that an option for the programmable install! I agree, the default should be kept simple.

**Comment by grazzolini** [comment]
@Torxed since the user has the liberty to install whichever kernel they want on the current method of installation, following the installation guide, I think adding a feature to list the official kernels (linux, linux-lts, linux-zen and linux-hardened) while keeping linux as the default option if the person simply press enter, would be a nice addition to have. I don't see the list of kernels growing anytime soon.

**Comment by dylanmtaylor** [comment]
This would be an awesome feature to have. One thought -- I think it may be desirable to have linux AND linux-lts on the same system (in case the newer kernel breaks), and have a bootloader menu for each. This is how I have my current installation now, as an example of this:

```
➜  ~ cat /boot/loader/entries/arch.conf 
title Arch Linux
linux /vmlinuz-linux
initrd /intel-ucode.img
initrd /initramfs-linux.img
options rd.luks.name=1ea54b52-e005-4438-afd9-e690e690bec4=cryptlvm root=/dev/vg0/root resume=/dev/vg0/swap rd.luks.options=discard i915.fastboot=1 quiet splash loglevel=3 rd.udev.log_priority=3 vt.global_cursor_default=0 rw
➜  ~ cat /boot/loader/entries/archlts.conf
title Arch Linux LTS
linux /vmlinuz-linux-lts
initrd /intel-ucode.img
initrd /initramfs-linux-lts.img
options rd.luks.name=1ea54b52-e005-4438-afd9-e690e690bec4=cryptlvm root=/dev/vg0/root resume=/dev/vg0/swap rd.luks.options=discard i915.fastboot=1 quiet rw
```

**Comment by dylanmtaylor** [comment]
Maybe have kernels be an array that is iterated over to install each one as a separate bootloader entry?

**Comment by dylanmtaylor** [comment]
Guided installation mockup:

```
0: linux
1: linux-lts
2: linux-zen
3: linux-hardened
Enter the Linux kernels you would like to install as a comma-separated list, or press return to default to 'linux': 0, 1, 2
```

**Comment by Torxed** [comment]
We could do something similar as to the user-menu, where it loops over the options and perhaps indicate which ones are selected.

**Comment by adnan449** [comment]
+1 for this, I need Linux-lts for my wireless driver

**Comment by dylanmtaylor** [comment]
> +1 for this, I need Linux-lts for my wireless driver

So I know it doesn't install it now, but you can fairly easily put linux-lts in additional packages and edit the boot line on your bootloader's configuration file. Which driver works on LTS but not mainline?

**Comment by adnan449** [comment]
> > +1 for this, I need Linux-lts for my wireless driver
> 
> So I know it doesn't install it now, but you can fairly easily put linux-lts in additional packages and edit the boot line on your bootloader's configuration file. Which driver works on LTS but not mainline?

I am using an rtl8812-au chipset which happens to work with https://github.com/aircrack-ng/rtl8812au. The driver is not guaranteed to work with the cutting edge kernels and might cause my WiFi to stop working. The AUR package updates from the upstream but the upstream might be a bit behind in testing.

**Comment by Torxed** [comment]
Forgot to link this issue in #315. But this is implemented and selecting kernels are now in `master` and up for the next release.
We maintain a list of the most common kernels: https://github.com/archlinux/archinstall/blob/e4c471b631632b7f419ba7ff4c982df406305a3c/examples/guided.py#L205

If there's any suggestions related to this, either drop the comments here or in a new issue :)
