### ISSUE TITLE
Create an option for archinstall with systemd-boot.

### ISSUE THREAD

**Issue by 4r6h** [archlinux/archinstall#1451]
Looking at the issue of grub. We should avoid using grub or not avoiding but adding an option to the arch installer for choosing other alternative boot options like systemd-boot, refind....etc. I prefer systemd-boot because majority of the people will going to be use systemd as their main init system. So why installing another extra program like grub or refind or other similar program that can just done by the already installed and good boot loader option like systemd-boot.

**Comment by Torxed** [comment]
We already have all those things, and have had since version 1 more or less :)
The default is also `systemd-boot` so I'm not sure if I'm missing anything here?

I'd be happy to re-open but I think this is "solved" :)
