### ISSUE TITLE
Multilib-testing is also enabled

### ISSUE THREAD

**Issue by castillofrancodamian** [archlinux/archinstall#1460]
The "testting" version of Multilib is enabled even if it is not selected in the installation.

**Comment by codefiles** [comment]
Fixed in `master` by https://github.com/archlinux/archinstall/pull/1364.

**Comment by castillofrancodamian** [comment]
It is not yet on the latest released ISO image.

**Comment by codefiles** [comment]
Right because the ISO contains the latest release which is [v2.5.0](https://github.com/archlinux/archinstall/releases/tag/v2.5.0). The next release of `archinstall` will have this fix, #1364 is under **Bug fixes** for [v2.5.1rc1](https://github.com/archlinux/archinstall/releases/tag/v2.5.1rc1)
