### ISSUE TITLE
Issue when install

### ISSUE THREAD

**Issue by Thinh-origami** [archlinux/archinstall#1464]
để![IMG20220909131511](https://user-images.githubusercontent.com/82449492/189285478-fa3929e5-9e31-4715-9c12-fa2fb1ffe2c6.jpg)
![IMG20220909131605](https://user-images.githubusercontent.com/82449492/189285505-bfa2b9cf-01a2-4ce4-902a-3573b92af2c1.jpg)
![IMG20220909132635](https://user-images.githubusercontent.com/82449492/189285542-25946d2e-21b4-4ae8-8d87-d52fe2bef0ae.jpg)
i don't know why this is happening, can someone help me Pls.

**Comment by Torxed** [comment]
The first picture shows the error "Partition(s) on <device> is being used".
You need to unmount or reboot :)
