### ISSUE TITLE
Keyboard/Locale chooser

### ISSUE THREAD

**Issue by pyfisch** [archlinux/archinstall#147]
The first step of the installer is choosing your keyboard layout:

```
0: by
1: cf
2: cz
3: dk
4: es
5: et
6: fi
7: il
8: it
9: k0
10: l1
11: l2
12: l3
13: l4
14: lt
15: lv
16: nl
17: no
18: ro
19: ru
20: uk
21: us
 -- You can enter ? or help to search for more languages --
Select one of the above keyboard languages (by number or full name):
```

I don't know how the 21 codes were selected and their meaning isn't obvious (I guess many are two letter country codes). I use a German keyboard layout and don't know what to choose in this step, many other major keyboards seem to be missing or hidden as well e.g. French and Chinese.

I would prefer either a simple textfield, where I can enter my keymap or a complex chooser that guides the user to the correct keymap.

**Comment by kpcyrd** [comment]
Since the installer asks for your country anyway we could make that the first question and then based on the country suggest a reasonable default.

**Comment by pyfisch** [comment]
@kpcyrd I'm fine with that.

If you want to be smart you can make timezone the next question and suggest sensible defaults based on the country. :wink:

**Comment by Didr** [comment]
I agree that the keyboard layout selection isn't very intuitive. I think the idea here is to follow the `-- You can enter ? or help to search for more languages --` message if your country(?) isn't in the list. 

> I would prefer either a simple textfield, where I can enter my keymap

While reading through the code trying to find a bug, I found that this is actually possible but the user isn't told that it can be done.
https://github.com/archlinux/archinstall/blob/master/archinstall/lib/user_interaction.py#L280

**Comment by Torxed** [comment]
> I would prefer either a simple textfield, where I can enter my keymap or a complex chooser that guides the user to the correct keymap.

This step obviously needs improvements.
One thing that's maybe not fully obvious is this step supports the user writing `sv-latin1` for Swedish, `be-latin1` for Belgian but also `de-latin1` for German.

The hint "full name" is obviously not enough and that's on me.
I'll improve this step in the next couple of days while evaluating a nice way of combining the mirror region and time zone setup.

**Comment by pyfisch** [comment]
Choosing a keyboard layout:

1. Call `localectl list-x11-keymap-layouts` to get a list of country codes for different keyboard layouts.
2. Map country [codes to country names](https://datahub.io/core/country-list) and display them.
3. User chooses a country code `$LAYOUT`.
4. Call `localectl list-x11-keymap-variants $LAYOUT`.
5. User optionally chooses a keyboard variant `$VARIANT`.
6. Call `localectl set-x11-keymap $LAYOUT "" $VARIANT`, to set both graphical and console keyboard layout.

For choosing a timezone have a look at the `tzselect` script and `/usr/share/zoneinfo/zone1970.tab`.

**Comment by rhwendt** [comment]
I have a similar project using ansible to install arch. For the time zone I call this in the initial setup script. 

```
result = subprocess.run(['tzselect'], stdout=subprocess.PIPE)
timezone = result.stdout.decode('utf-8')
```

**Comment by Torxed** [comment]
> I have a similar project using ansible to install arch. For the time zone I call this in the initial setup script.
> 
> ```
> result = subprocess.run(['tzselect'], stdout=subprocess.PIPE)
> timezone = result.stdout.decode('utf-8')
> ```

Maybe it's possible to spawn a separate process and get the return from it, but unfortunately I think that won't work. But I'll give it a try. The wiki mentions that the user should run the command `timedatectl list-timezones` to get a list of supported time zones.

But since we now have a [way of showing large lists and options](https://github.com/archlinux/archinstall/pull/117) it would have been nice to print the list. But it's `348` supported time zones, and that will probably not fit in the TTY of the ISO by default.

**Comment by dschemp** [comment]
> But since we now have a [way of showing large lists and options](https://github.com/archlinux/archinstall/pull/117) it would have been nice to print the list. But it's `348` supported time zones, and that will probably not fit in the TTY of the ISO by default.

Wouldn't it be possible to go through the timezone selection in two steps (like some installers do): first the continent and second the city.

This should be feasible even for the Americas region with about 130 entries.

**Comment by Torxed** [comment]
> > But since we now have a [way of showing large lists and options](https://github.com/archlinux/archinstall/pull/117) it would have been nice to print the list. But it's `348` supported time zones, and that will probably not fit in the TTY of the ISO by default.
> 
> Wouldn't it be possible to go through the timezone selection in two steps (like some installers do): first the continent and second the city. (edit: like @pyfisch mentioned `tzselect` was what I had in mind, but I am not sure how this would fit in the installer snuggly)
> 
> This should be feasible even for the Americas region with about 130 entries.

As discussed in #173, I propose the following solution for the time-zone issue:
```python
import archinstall
regions = set([x.split(b'/')[0] for x in archinstall.sys_command("timedatectl list-timezones --no-pager")])
```
Followed by another step where the user would choose city/region.
The down side is that it would add one additional menu-item, but perhaps we can suggest a keyboard layout (keyword here: suggest) as well as a locale based on the selected region. Not sure how you would map that tho, without manually creating a huge set of mapping variables in a dict or something.

**Comment by dylanmtaylor** [comment]
> > > But since we now have a [way of showing large lists and options](https://github.com/archlinux/archinstall/pull/117) it would have been nice to print the list. But it's `348` supported time zones, and that will probably not fit in the TTY of the ISO by default.
> > 
> > 
> > Wouldn't it be possible to go through the timezone selection in two steps (like some installers do): first the continent and second the city. (edit: like @pyfisch mentioned `tzselect` was what I had in mind, but I am not sure how this would fit in the installer snuggly)
> > This should be feasible even for the Americas region with about 130 entries.
> 
> As discussed in #173, I propose the following solution for the time-zone issue:
> 
> ```python
> import archinstall
> regions = set([x.split(b'/')[0] for x in archinstall.sys_command("timedatectl list-timezones --no-pager")])
> ```
> 
> Followed by another step where the user would choose city/region.
> The down side is that it would add one additional menu-item, but perhaps we can suggest a keyboard layout (keyword here: suggest) as well as a locale based on the selected region. Not sure how you would map that tho, without manually creating a huge set of mapping variables in a dict or something.

As long as it is a suggestion and not automatic determination it should be good. I know Canada has both French/English locales in one country for example, and we can't know for sure without a user prompt.

**Comment by C0MODIN** [comment]
Whe I choose the "es" option this cover spanish from latin american? or just only cover spanish from spain?

**Comment by Torxed** [comment]
> Whe I choose the "es" option this cover spanish from latin american? or just only cover spanish from spain?

Not sure, according to the [KEYMAP](https://wiki.parabola.nu/KEYMAP) definition, it's `Spanish`, `es-latin1` is for `Spanish Latinoamerican`.

**Comment by AntiBigTech** [comment]
I recently installed Archlinux with the archinstall. I've choosen the la-latin1 after being asked whith "?" that allow more options in the firs question.

The thing is after installing (without a Graficall Environment) and rebooting, my selected keymap (either my choosen locale America/Bogota) wasn't avaiable. 

I could already change the locale, but it was impossible to me to write the "ñ". 

For example, after the order:

$ sudo loadkeys la-latin1 

The console don't display any errors or confirmation, but It wasn´t possible to write ñ.

**Comment by Torxed** [comment]
> I recently installed Archlinux with the archinstall. I've choosen the la-latin1 after being asked whith "?" that allow more options in the first question.
> 
> The thing is after installing (without a Graficall Environment) and rebooting, my selected keymap (either my choosen locale America/Bogota) wasn't avaiable.
> 
> I could already change the locale, but it was impossible to me to write the "ñ".
> 
> For example, after the order:
> 
> $ sudo loadkeys la-latin1
> 
> The console don't display any errors or confirmation, but It wasn´t possible to write ñ.

I might be wrong, but you shouldn't use `sudo` for setting key-layout, as that changes for the `sudo` user and not your current logged in user. However, choosing `la-latin1` during installation *should* set your default layout to `la-latin1`.
If you don't mind, could you check your `/etc/locale.conf` and verify that it indeed is `la-latin1` in there?

**Comment by AntiBigTech** [comment]
I repeated the process (entire installation), and it worked correctly for the selected keymap; but not for mi choosen locale.

![IMG_20210412_144237](https://user-images.githubusercontent.com/82244838/114457635-dde9e580-9ba3-11eb-847c-301034e650fe.jpg)

*note that I could correctly use my ñ and other la-latin1 characters.

![IMG_20210412_144710](https://user-images.githubusercontent.com/82244838/114457657-e3dfc680-9ba3-11eb-8e20-69f75313b5a7.jpg)

![IMG_20210412_145215](https://user-images.githubusercontent.com/82244838/114457796-0f62b100-9ba4-11eb-85c0-775fa96261b6.jpg)

![IMG_20210412_145841](https://user-images.githubusercontent.com/82244838/114457801-125da180-9ba4-11eb-8099-ce331ca5a2f6.jpg)

![IMG_20210412_150503](https://user-images.githubusercontent.com/82244838/114457809-15589200-9ba4-11eb-91e3-2b424ad272c2.jpg)

After that, I run sway (one of my choosen packages) and after that IT FAILED. 

![IMG_20210412_151454](https://user-images.githubusercontent.com/82244838/114457864-230e1780-9ba4-11eb-9b47-5cfa1ffbf31a.jpg)

And the aviable teyboard list appears to be incomplete and it couldn't load correctly my needed keyboard map:

![IMG_20210412_151823](https://user-images.githubusercontent.com/82244838/114457999-4933b780-9ba4-11eb-91ff-d5aa9c78e7af.jpg)

And this is the output that 'Torxed' asked meto check:

for:

#nano /etc/locale.conf

LANG=en_US.UTF-8

And that's it.

---------------------------------------------------------------------------------------------------

What do you think, is this an issue that I need to repor to the sway git?

Thankyou for your time.

**Comment by dylanmtaylor** [comment]
From the looks of this, there's likely a bug in how locale selection is handled. Either that or the installer is not clear enough on how to change locale. I wouldn't say this is an issue with Sway unless the locale file specified la-latin1 or whatever the correct value is and sway ignored it. It doesn't look like the correct value is written into that file.

**Comment by AntiBigTech** [comment]
I've been studying a lot about sway also, and the Archlinux wiki explains that the default settings of it; don't load the system keyboard, it comes by default with the US QUERTY keymap:

https://wiki.archlinux.org/index.php/Sway#Keymap

I think that for persons from other regions is VERY difficult to deal whith those defaults. It would be intresting to find more user friendly wikis.

**Comment by AntiBigTech** [comment]
I just got the ultimate config solution for my keymap (under sway):

After editing the "~/.config/sway/config." archive whith nano, and only writing this tree lines:
    
       input "type:keyboard" {
              xkb_layout latam
              xkb_variant deadtilde
       }

I have reached the goal to write properly in SPANISH, with my la-latin1 keyboard distribution. 

I wish this info help much more people with the same problem I had.

THANKS A LOT for the ARCHINSTALL script aid; it is very useful and it saved me a lot of time, compared to a manual installation of Archlinux.

**Comment by Torxed** [comment]
Note that we don't transfer terminal locale/keyboard layout to X.
X handles language layout differently from the TTY and the language codes are some times very different *(For instance, swedish is `sv-latin1` in tty land but `se` in x-org land)*. This is something we have to figure out how to map without maintaining a language map between the two worlds. After that, we should be able to tweak that desktop environment configurations to match the selected locale in tty.

**Comment by Torxed** [comment]
Update to my previous comment, in accordance with #147 this is something `localectl` can set, and perhaps it can be a unified way of setting both the console and x11 configuration.

**Comment by Torxed** [comment]
`localectl` is now being used and locale's are set both for vconsole and X11.
We're trusting that `localectl` can handle the mapping between the two and we'll have to see how we deal with wayland in the future.

Any locale/layout that `localectl` supports, we now support.
We're not mapping locale language files for the listing any longer, and we're not using `loadkeys` or manual configuration of `/etc/vconsole.conf`, which means more robustness and any issues mentioned in this thread is considered resolved in the latest master branch. (next release will contain these changes).

Thank you to everyone reporting on on these issues!
