### ISSUE TITLE
Small mistake in Nationalization.

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1470]
It should be [polski](https://github.com/archlinux/archinstall/search?q=polskie)  instead of polskie.

polski - polish            
polskie tłumaczenie - polish translation

**Comment by Torxed** [comment]
Any reason for closing? Or is it supposed to be `Polskie`?
As it's a reference to the language and not "polish translation"?

**Comment by eskiq** [comment]
I think I misunderstood something. You are not listing all available languages but translations, so it's all good. I was quite busy so I closed the issue. Sorry for confusion.

**Comment by Torxed** [comment]
No worries :D Thank you for taking the time to explain it to me!
