### ISSUE TITLE
Observed issue with partition being mounted twice causing a collision

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1477]
![screenshot](https://user-images.githubusercontent.com/861439/191481448-542ab854-2f5b-409e-ba08-4353668e6666.png)

**Comment by Torxed** [comment]
I can't reproduce now, weird.

**Comment by archite** [comment]
I’ve had this happen about 10 times out of 11. Not sure how I got it work once though.

**Comment by svartkanin** [comment]
@Torxed that's awesome 😊😊

**Comment by Betablockr** [comment]
I have the exact same issue, I'm using an Acer Nitro 5 and trying to use the archinstall method on my 128GB NVMe drive, I set the drive to automatically partition too with and without a swap and I get the same error everytime. I have tried manually making 3 seperate partions, 1 512MB fat32 as EFI boot, 1 4GB set as linux-swap and the rest ext4 but I just get a different error. Very strange!
