### ISSUE TITLE
Make menu checks detect and not require disk selection if `/mnt/archinstall` contains a mounted device

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1484]
So the current setup is to enter the disk selection, and press `Ctrl-C` (reset) at which point the user will be prompted with the option to skip disk selection and `self._disk_check` is set and the following logic is skipped: https://github.com/archlinux/archinstall/blob/53a2797af6ac0832bf7dd00dfe96b8ea1867db2e/archinstall/lib/menu/global_menu.py#L316-L321

I'd argue that we can set this variable directly if we use `findmnt("/mnt/archinstall", traverse=False)` and get a result for this mountpoint.
Because users mounting stuff wouldn't expect to enter the disk selection menu entry at all, since they knew they mount something before running `archinstall`.

This would also require less information to be given and remove a step in the disk selection process hopefully reducing complexity.
It's a good fix for now since we added back in the option to use existing mountpoints.

Current workflow:
![archinstall](https://user-images.githubusercontent.com/861439/192139721-18d1c25c-0d70-4fe2-8d4f-334c8c881d72.gif)

**Comment by svartkanin** [comment]
With the latest menu there's now an option to specify a mountpoint in the config alongside default and manual.
If that's not enough we can re-open this one :)
