### ISSUE TITLE
ISO Build failures

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#1485]
Dug into this a bit. The reason the ISO build is failing is due to a bug in the archiso package caused by the [removal of ipw2100-fw and ipw2200-fw](https://lists.archlinux.org/archives/list/arch-dev-public@lists.archlinux.org/thread/UKXPJEJZPU5PFKAPSATNL2DSWFGNEUCK/). We can patch this out ourselves so the build still works, or wait for a fix to archiso upstream.

**Comment by dylanmtaylor** [comment]
https://gitlab.archlinux.org/archlinux/archiso/-/commit/8afa2b65d54b51518c14b7d587c6c624b7ed6352

This was already fixed in archiso master.

**Comment by Torxed** [comment]
Yea I talked to David and C/O about it, there's really no way for them to know the outcome of dropping a package from `core` unless they know about all the projects. In this case `archiso` got affected, but a new release is being pushed.. well while writing this :P so I think we should be fine :)

**Comment by svartkanin** [comment]
I reckon this is good now
