### ISSUE TITLE
Problem selecting bootloader

### ISSUE THREAD

**Issue by Ryyoukka** [archlinux/archinstall#1489]
by default it comes with grub and if I try to change it it doesn't leave, nor enters the selection menu

**Comment by Torxed** [comment]
By default it comes with `systemd-boot`, and if you select yes in the menu entry you get `grun`.

Is it a phrasing issue?

**Comment by Torxed** [comment]
I'll verify in a bit and release a hotfix ASAP so that it gets fixed in time for the ISO :) Thank you for pointing it out!

**Comment by Torxed** [comment]
I'm having issues reproducing this bug:

![archinstall](https://user-images.githubusercontent.com/861439/192502999-315cc518-0c45-426b-9268-1d30796b3bfb.gif)

**Comment by Torxed** [comment]
Strange, I'll have to deep diver tonight! "It works on my machine" heh, so I'll have to try another one and also step through the code. So it's a bit more involved time wise.

**Comment by Ryyoukka** [comment]
sorry for the delay to reply.
It's exactly what @GlinstoneCrusader showed in its gif. It starts with grub and if you try to select another it ignores it.
If that helps, I'm testing it in a virtual-box, the iso is the latest too

**Comment by Torxed** [comment]
Ah yea, if you're not running UEFI we for very obvious reasons won't show any EFI options (systemd-boot requires EFI).

**Comment by Torxed** [comment]
Odd, I believe it used to be mentioned in the wiki article: https://wiki.archlinux.org/index.php?title=Archinstall&diff=738368&oldid=737213

I'll close this as we only support GRUB for BIOS.
I should have picked this up quicker but I assumed the machine was booted in EFI mode ^^
