### ISSUE TITLE
Searching for non-existent keyboard layout crashes archinstall

### ISSUE THREAD

**Issue by Didr** [archlinux/archinstall#149]
Searching for non-existent keyboard layout crashes archinstall.
Steps to reproduce:
1. Start `archinstall`
2. Type `?` or `help` when asked to select a keyboard language.
3. In response to "Search for layout containing", type `potato`

Archinstall crashes with the following output:
![image](https://user-images.githubusercontent.com/9605751/113466862-55e73b80-943f-11eb-949e-dd85ca3824f9.png)

I'm assuming that `select_language` doesn't like it when `search_keyboard_layout` returns an empty list.
Link to select_language: https://github.com/archlinux/archinstall/blob/master/archinstall/lib/user_interaction.py#L249
Link to search_keyboard_layout: https://github.com/archlinux/archinstall/blob/master/archinstall/lib/locale_helpers.py#L23

_A thank you to @erikdubois for finding this bug and recording it._

**Comment by erikdubois** [comment]
glad I was able to help
