### ISSUE TITLE
Enabling Zram support should disable Zswap

### ISSUE THREAD

**Issue by Dungeonseeker** [archlinux/archinstall#1493]
According to the Arch Wiki, when using Zram you have to disable Zswap since it is enabled by default in the Linux Kernel.

See - [https://wiki.archlinux.org/title/Improving_performance#zram_or_zswap](url)

> Since it is enabled by default, [disable zswap](https://wiki.archlinux.org/title/Zswap#Toggling_zswap) if you decide to use zram to avoid zswap acting as a swap cache in front of it. Having both enabled also results in incorrect [zramctl(8)](https://man.archlinux.org/man/zramctl.8) statistics as zram remains mostly unused; this is because zswap intercepts and compresses memory pages being swapped out before they can reach zram.

Thought I'd bring it up since archinstall uses Zram for swap by default.

**Comment by spaceoden** [comment]
Check the .conf file(s) in `/boot/loader/entries/`. Is `zswap.enabled=0` among the kernel parameters? If so, archinstall is successfully disabling zswap.

**Comment by Dungeonseeker** [comment]
> Check the .conf file(s) in `/boot/loader/entries/`. Is `zswap.enabled=0` among the kernel parameters? If so, archinstall is successfully disabling zswap.

I'm using grub but the answer is no, I had to add it manually.

**Comment by codefiles** [comment]
I'll add this to #1517 .

**Comment by svartkanin** [comment]
This should be fixed now
