### ISSUE TITLE
Could not detect root or boot

### ISSUE THREAD

**Issue by DefinitelyQuartz** [archlinux/archinstall#1497]
![IMG20221001015348](https://user-images.githubusercontent.com/66527700/193376838-e578a0b6-750e-48ea-9b27-164802ca0ade.jpg)

**Comment by AussieAnon** [comment]
Experiencing the same issue here also. Have tried different installation sources (ie Ventoy HDD, Bootable USB stick etc) and multiple file systems ext4, XFS and BTRFS with no luck.

**Comment by Torxed** [comment]
What do you both have if you run `findmnt /mnt/archinstall`? also the install log would be useful :)

**Comment by goodaniu** [comment]
我也遇到这个问题了，因为之前分区的时候没有给boot单独分区，后来单独分了个boot区，就顺利安装了，不妨试试看。

**Comment by lucazade** [comment]
same issue here.. I get this error on september iso (with november iso instead I get another issue #1557)
attached log
[install.log](https://github.com/archlinux/archinstall/files/10015144/install.log)

**Comment by Torxed** [comment]
Than you, I will investigate shortly!

**Comment by svartkanin** [comment]
This is most likely resolved with the recent changes, if not we can re-open it
