### ISSUE TITLE
Could not get UUID/PARTUUID of Partition using blkid

### ISSUE THREAD

**Issue by Roshan-24** [archlinux/archinstall#1515]
I'm trying to dual boot arch alongside windows11 on the same nvme drive using the guided installer, but I got this error (install.log attached below). However, I am able to get the uuid from blkid when run manually

lsblk output:
(I had created and formatted nvme0n1p5 as swap, p6 as ext4 for root) (nvme0n1p1-p4 was present already for windows) (p1 is the ESP)
![lsblk](https://user-images.githubusercontent.com/63301253/194692424-a4e4445d-c91c-43c2-b652-1ebace2a505c.jpg)

Install log:
![installlog](https://user-images.githubusercontent.com/63301253/194692406-66e8d013-72b8-4f43-8714-27caf50828fc.jpg)

Disk layout:
![disklayout](https://user-images.githubusercontent.com/63301253/194692678-42129402-d5aa-4478-8908-473e1f3f5bd3.jpg)

User config:
![userconfig](https://user-images.githubusercontent.com/63301253/194692683-e139c665-a950-45c7-ad18-045d27f60948.jpg)

**Comment by Torxed** [comment]
It seems related to #1495 in a way. nvme disk operations are too quick.

**Comment by Torxed** [comment]
Merged into `master` and I'm pushing a new release now, which should fix this.
