### ISSUE TITLE
Installation fails because archinstall is mounted on the drive

### ISSUE THREAD

**Issue by HarmoGlace** [archlinux/archinstall#1516]
Hello, when I try to install arch with archinstall, I get the following error message :![IMG_20221008_183546_524.jpg](https://user-images.githubusercontent.com/23212967/194717996-5e057198-6265-4643-a8ef-d54570ba9afa.jpg)

Here is my configuration : ![IMG_20221008_184028_781.jpg](https://user-images.githubusercontent.com/23212967/194718154-6bbe4d5c-d912-42c5-979a-f8e26e4c036b.jpg)

I have tried to manually unmount it but archinstall automatically mounts it.

**Comment by syedaniq** [comment]
It worked for me by using an older version of Arch (e.g. https://archive.archlinux.org/iso/2022.07.01/)

**Comment by acfuns** [comment]
this is duplicate https://github.com/archlinux/archinstall/issues/1495

**Comment by acfuns** [comment]
I try `sudo pacman -S archinstall`, then reinstall and success.

**Comment by Torxed** [comment]
Either just retry the installation, on some hardware that works.
On others you might get lucky with wiping the disk so it doesn't contain any partitions, reboot, and try again.

It's a duplicate as acfuns said of #1495 and a workaround can be found here: https://github.com/archlinux/archinstall/issues/1495#issuecomment-1274131130
