### ISSUE TITLE
Two bugs in the Disk Layout UI's compressible partition selection screen: Incorrect Text Bug and fat32 compression flag

### ISSUE THREAD

**Issue by J1Man** [archlinux/archinstall#1524]
Hi Torxed,

There are two minor bugs in the Disk Layout UI's compressible partition selection screen. I am using the official archiso that was released on October 2022.

The first one is an incorrect text bug.  When I select "Mark/Unmark a partition as compressed (btrfs only)" option, the UI displays "Select which partition to mark as **bootable**".  It is supposed to say "Select which partition to mark as **compressible**". Regardless of the text, it sets the compression flag on the selected partition.  I think the text error is in line 275 of partitioning_conf.py

The second bug is also in the same part (compressible partition selection screen) of the UI.  If the fat32 boot partition is accidentally selected by the user, the UI sets the compress=zstd flag on it.  It seems like the code is not checking the file system type before setting the compression flag.

In order to replicate these bugs, first select a hdd and then click the following: "Disk Layout",  "select what to do with each individual drive", "suggest partition layout", "say yes to removing existing partitions", "btrfs", "no sub volumes", "no BTRFS compression", "Mark/Unmark a partition as compressed (btrfs only)", "note the incorrect select bootable partition message on screen, and click fat32 or btrfs partitions"

**Comment by svartkanin** [comment]
This should be resolved in the latest version
