### ISSUE TITLE
reuse/keep existing /home-partition with archinstall

### ISSUE THREAD

**Issue by AWHubGit** [archlinux/archinstall#1525]
In recent light of all the trouble the `/home` partition has created, I think it makes sense to merge this in so that users can more safely choose whether or not they want a separate `/home` partition and judge it for themselves. Manually editing the JSON every time they want to remove/add it is a bit cumbersome and this saves some time.

_Originally posted by @Torxed in https://github.com/archlinux/archinstall/issues/801#issuecomment-1004028239_

Does "safely choose to want a separate `/home` partition" allow to reuse/keep an existing /home partition?
Does it format the existing /home-partition?

Is there a way to reinstall Arch with archinstall keeping an existing /home-partition?

May be above choice for users should be extended they can reuse/keep existing /home-partition. My proposal.

I have a running Arch with some damages I want to refresh/reinstall/repair with archinstall. How to do this?

**Comment by Torxed** [comment]
We do have a question, "Do you want a separate /home partition?" and it's a yes or no question.
Is that not easier than editing the JSON files?

**Comment by eskiq** [comment]
@Torxed There is option to create separate home partition, but is there option to reinstall system when home is not separated?

**Comment by AWHubGit** [comment]
> We do have a question, "Do you want a separate /home partition?" and it's a yes or no question. Is that not easier than editing the JSON files?
> 
> > Is there a way to reinstall Arch with archinstall keeping an existing /home-partition?
> 
> Yes, "re-use partitions" can be selected in the disk partitioner and simply select the `/home` partition and mount it as `/home` and make sure `wipe = false`.
> 
> Same goes for "refreshing" your installation. Make a disk descision, and wipe or don't wipe existing partitions and you can let archinstall wipe just the root device for instance.
> 
> I usually leave `/boot` alone and `/home`. But bare in mind that it will install `systemd-boot` or grub to the partition, so it might mess with other boot loaders.

Thanks.

I defined the root-partition to use by inputting the sectors 34867200 to 137267199 as per "gdisk -l /dev/nvme1n1, but parted failed with error: "parted ended with bad exit code: 256 - location 34867200 is outside of device /dev/nvme1n1". I doublechecked that root-partition is within sectors 34867200 to 137267199. Finally I did the usual/normal steps as per Archwiki install guide without formatting root-part. This worked without problems. No need to install bootloader. I use refind from usb stick.
Also see [parted error archinstall](https://photos.app.goo.gl/Dzzdgm7zHuHjqBdc8)

**Comment by svartkanin** [comment]
This should be possible by using the manual installation option
