### ISSUE TITLE
missing module python-setuptools

### ISSUE THREAD

**Issue by eskiq** [archlinux/archinstall#1526]
https://github.com/archlinux/archinstall#using-a-live-iso-image
When I tried to install new bleeding edge release, there was an error about missing python-setuptools module. Just missing info about it on the front page.

**Comment by Torxed** [comment]
Good catch, workaround for now:
```
python -m build -n; pip install dist/archinstall*.whl"
```

**Comment by svartkanin** [comment]
The README should be fixed and reflect the working steps
