### ISSUE TITLE
Could not get block device information using blkid() using command blkid -p -o export /dev/sr0

### ISSUE THREAD

**Issue by SG-starr** [archlinux/archinstall#1529]
Hi there,

Just tried installing the system via archistall and got the following error messages during the whole process:

Could not get block device information using blkid() using command blkid -p -o export /dev/sr0
Could not get free space on /dev/sr0: ['/usr/bin/parted', '-s', '--machine', '/dev/sr0', 'print', 'free'] exited with abnormal exit code [256]: b'Error: Error opening /dev/sr0: No medium found\r\n'

Here is the log:
[install.log](https://github.com/archlinux/archinstall/files/9827397/install.log)

**Comment by svartkanin** [comment]
THis should be resolved with the recent changes and using pyparted
