### ISSUE TITLE
Fix disk layout settings in config file (Was: Why 3 different config files?)

### ISSUE THREAD

**Issue by cfinnberg** [archlinux/archinstall#1531]
### Discussed in https://github.com/archlinux/archinstall/discussions/1528

<div type='discussions-op-text'>

<sup>Originally posted by **cfinnberg** October 20, 2022</sup>
Hi!

Is there any reasoning to why the settings for automated install are shared into three different config files instead of using one common file? It makes more "difficult" to run the installer:
```
# Why this:
archinstall --config http://myserver.local/config.json --creds http://myserver.local/creds.json --disk_layouts http://myserver.local/disk_layouts.json --silent

# Instead of this:
archinstall --config http://myserver.local/config.json --silent
```</div>

**Comment by cfinnberg** [comment]
Issue opened just to track the progress on this:

The dictionary key for disk layouts should change name so it does not conflict with the command line parameter of the same name (probably better to change the key than the command line name)

**Comment by svartkanin** [comment]
We have moved to 2 config files `user_configuration.json` and `user_credentials.json`. We will most likely not merge those 2 for the simple reason that when people report issues they can safely share their configuration without compromising any specified credentials.
