### ISSUE TITLE
README "Live ISO Image" instructions fail to setup 

### ISSUE THREAD

**Issue by deobald** [archlinux/archinstall#1532]
The ISO does not have `python-setuptools' installed by default, so `python setup.py install` in step 5 fails.

**Comment by eskiq** [comment]
#1526

**Comment by martinstark** [comment]
Ran into the same issue when I wanted to try the 2.5.2 release with the NVME fixes

**Comment by svartkanin** [comment]
`setup.py` has been removed and we're only using `pyproject.yaml` now. The README instructions are also up to date and should work as described
