### ISSUE TITLE
Add Polkit to desktop install with Sway

### ISSUE THREAD

**Issue by ca-cl2** [archlinux/archinstall#1535]
I installed Sway with a desktop profile, but when I logged in to the new install and tried to launch Sway, it said it needed privilege escalation, either by installing Polkit or by setting up seatd (enable systemd service, add user to seat group).
Sway launched once Polkit was installed.

**Comment by eskiq** [comment]
I was also quite lazy to type in the search bar "sway polkit". Created my own thread about sway and polkit just like you. :D
https://github.com/archlinux/archinstall/issues?q=sway+polkit

**Comment by ca-cl2** [comment]
Whoops :)
