### ISSUE TITLE
All AMD system installs Intel and AMDVLK Vulkan drivers

### ISSUE THREAD

**Issue by lennie420** [archlinux/archinstall#1536]
On an all AMD system (laptop, not sure about desktop) archinstall will install AMDVLK and Intel Vulkan drivers.

**Comment by lennie420** [comment]
Seems I may have selected all open source instead of amd drivers but then if I install Steam as an extra package it will also select the AMDVLK drivers instead of mesa Vulkan drivers.

**Comment by svartkanin** [comment]
This should be fixed
