### ISSUE TITLE
Partitions not set correct size

### ISSUE THREAD

**Issue by kulact** [archlinux/archinstall#1549]
I was installed Arch Linux using archinstall on my old laptop and i have a few tested before installed

Maybe it's not a bug, i don't know. I wanted to partition manually the disk and followed the instructions. First, i set /boot 512MB and / 100GB but partitions set less after install. Second, i set /boot 512MB and / 102400MB and same happend again

After install, my lsbk

```
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda      8:0    0 298.1G  0 disk
├─sda1   8:1    0   487M  0 part /boot
└─sda2   8:2    0  94.9G  0 part /home
                                 /
zram0  254:0    0   1.9G  0 disk [SWAP]
```

I used one subvolume as well in two install

After, i used cfdisk for partition. I created my partitions, open archinstall, i selected partitions and finish install. This time it wasn't wrong partitions sizes

**Comment by Advantaged** [comment]
Which partitioning tool do you use?
Use please a tool of `gptfdisk` group like `gdisk` for visual interface in terminal or `sgdisk` for CLI &| script, this only if you have problems with the size.

**Note:** The most used tools use KB, MB, GB & TB and not KiB, MiB, GiB & TiB as they should.

If underneath are other "problems", read please [4Kn-Formatting.](https://github.com/Advantaged/4Kn-Formatting)

**Comment by kulact** [comment]
I used `cfdisk` before archinstall. `lsblk` gave, `512MB` and `100GB`
When partitioning in archinstall, i used MB and GB. lsblk gave `487MB` and `94.9GB`

Archinstall uses which partition tool, i don't know

**Comment by eskiq** [comment]
512 MB = 488.28125 MiB
102400 MB = 95.367431641 GiB

> I used `cfdisk` before archinstall. `lsblk` gave, `512MB` and `100GB`

lsblk is displaying in MiB and GiB. Look on the size of your HDD. It's 320GB, but lsblk is displaying it in GiB so you can see 298.1G.

https://www.gbmb.org/mb-to-mib
https://www.gbmb.org/gib-to-gb

**Comment by Advantaged** [comment]
As well I can remember, `parted` (gparted) use "iB' until Mega, afterwards... if you want give 1 GiB you have to type '1024' MiB.

[parted](https://www.gnu.org/software/parted/manual/html_chapter/parted_2.html) and [gparted](https://gparted.org/display-doc.php%3Fname%3Dhelp-manual) can do a lot of nice thing other app are not able to do (btrfs, zfs (with a trick)), also to rescue other OS, but, until today have problem with 4096 B Sector size (LBS Logical Block Size) as already explained.

By the way, `gparted` is not `parted`, using one e.g. 'gparted' and recheck alignment with 'parted' can cause "unexpected" results, for-all bye mentioned "4k".

"New" partition-type and file-systems (btrfs, zfs) are not really well supported under Linux and it's time to become `ext5` that at least don't need twice force-parameter to format a 4k partition (see my link "4Kn-Partitioning" above).

To evolve correctly, at least `gparted` should give the possibility to "switch" nvme (over `nvme-cli`) from "512" or "512e", but, also HDD's over `hdparm`, SATA-SSD, etc..

It's also time to show the capacity correctly in "iB" for all measure and not only for MiB, here my incomplete bash-script:
```
#!/bin/bash

### VARIABLES-LIST
# DISK = choose Disk
# e.g.: DISK=/dev/sde
# TCB = total capacity in Bytes
# TCK = total Capacity in KiB
# TCM = total Capacity in MiB
# TCG = total capacity in GiB
# TCT = total Capacity in TiB
# KIB=1024
# MIB=1048576
# GIB=1073714824
# TIB=1099511627776

KIB=1024
export KIB
MIB=1048576
export MIB
GIB=1073714824
export GIB
TIB=1099511627776
export TIB

# Choose DISK
DISK=$(lsblk


# Read Capacity

TCB=$(fdisk -l /dev/sde | awk 'NR==1 {print $5}') && \
echo "Total Capcity of: $DISK in Byte is: $TCB" && \
TCK=$(($TCB / $KIB)) && \
echo "Total Capcity of: $DISK in KiB: $TCK" && \
TCM=$(($TCB / $MIB)) && \
echo "Total Capcity of: $DISK in MiB is: $TCM" && \
TCG=$(($TCB / $GIB)) && \
echo "Total Capcity of: $DISK in GiB: $TCG" && \
TCT=$(($TCB / $TIB)) && \
echo "Total Capcity of: $DISK in TiB: $TCT"

# Unset Variables

unset TCT TCG TCM TCK TCB TIB GIB MIB KIB DISK

# Check if Variable are unset

env | grep TCT
env | grep TCG
env | grep TCM
env | grep TCK
env | grep TCB
env | grep TIB
env | grep GIB
env | grep MIB
env | grep KIB
env | grep DISK

```
I'm not a coder, this bash is only the begin and not ready to use and developers are late, almost to late.
The times of computers with MiB capacity is over, the future appertain to "btrfs & zfs" (see "True NAS Scale" based on Debian).

**Comment by kulact** [comment]
@Advantaged and @eskiq thanks for information. I'm sorry I thought it was a bug. Completly my ignorance

**Comment by Advantaged** [comment]
> @Advantaged and @eskiq thanks for information. I'm sorry I thought it was a bug. Completly my ignorance

Our OS makes continuously "disk capacity checks" by starting (the EFI-Partition) and upgrading grub, by each `pacman -Syyu` and even swap. Well, if the user don't partition boundary to cluster-size (512 o. 4096) or whole KiB, MiB, GiB, etc. you have disk-size-fragmentation or better saying you partition is no more filled with whole clusters but with decimal parts of it.

e.g. 500 MB are neither 500*1000  KiB nor an half GiB but simply 464.xyz... MiB, this mean, the system have to calculate all figure/numbers after the decimal point but the data on the carrier are stored on whole clusters.

This mean, the system must spend time to calculate all those decimal-point, right?

If the user make the partitioning with proper tools e.g. `cgdisk` o. `sgdisk` o.  even `gdisk` of `gptdisk`-package ([see wiki](https://wiki.archlinux.org/title/GPT_fdisk)) always present on the Arch-iso... you have no more cluster-segmentation.

I read one time my disk with e.g. `fdisk -l /dev/sda` and divide the capacity trough 1024^3 , this give you 298....... GiB, subtracting 512 MiB for EFI or take just 1 GiB you still have 297 GiB available.

My nvme is "declared" as 2 TB but there are 200000000.... Bit, this mean my nvme is 1863 GiB and by partitioning I use only the unity GiB, 1GiB for EFI and 1860 GiB for `/`, if I use 'swap' I let additional 3 Gib empty space at end of "disk" and there are good reasons for making so.

The time you spend to calculate the real capacity in iB is saved several time after the installation.
