### ISSUE TITLE
Add progress bar for package install

### ISSUE THREAD

**Issue by m1ten** [archlinux/archinstall#155]
Currently when installing packages (base, desktop environment, etc) there is no progress bar. This may seem like the installation is stuck or unresponsive; It would be nice to see the progress.

**Comment by kpcyrd** [comment]
Maybe we could simply forward the output from pacstrap to stdout?

**Comment by Torxed** [comment]
> Maybe we could simply forward the output from pacstrap to stdout?

That's one way. Or we replace and update the last output of archinstall with the output from pacstrap, just to minimize output and keep it clean. Which would show what's currently being executed/installed.

**Comment by Torxed** [comment]
This was implemented in a earlier commit, but activated in #443
