### ISSUE TITLE
Selection of options looks small

### ISSUE THREAD

**Issue by castillofrancodamian** [archlinux/archinstall#1551]
Current Release: 2022.11.01

![Screenshot_20221106_023737](https://user-images.githubusercontent.com/47670442/200155999-92718dab-f0b5-40dc-b4e9-48b52808b37b.png)
![Screenshot_20221106_023757](https://user-images.githubusercontent.com/47670442/200156000-8ef639e1-230c-4205-935c-4f97cf12e7ea.png)
![Screenshot_20221106_023833](https://user-images.githubusercontent.com/47670442/200156002-3a46c760-a8ae-41c5-99aa-3426d53edb01.png)

**Comment by svartkanin** [comment]
What exactly looks too small? The screenshots look as expected

**Comment by svartkanin** [comment]
We're currently setting a custom font in the installer which may explain the small text. 

I'll raise a PR to only set it if a different language is selected

**Comment by castillofrancodamian** [comment]
These screenshots are from the `archlinux-2022.09.03-x86_64.iso` image and the options take up the entire screen.
![Screenshot_20221106_153717](https://user-images.githubusercontent.com/47670442/200189000-e3c81f7c-cad8-4154-a4c5-76949f49f327.png)
![Screenshot_20221106_153741](https://user-images.githubusercontent.com/47670442/200189002-163e5052-091a-4616-af0b-7e3a311ae435.png)
![Screenshot_20221106_153754](https://user-images.githubusercontent.com/47670442/200189003-d98b6c11-69fc-4613-913e-c1509a96d8b5.png)

**Comment by svartkanin** [comment]
I see, thanks for reporting. 
I'll have a look and see what changed

**Comment by svartkanin** [comment]
This is resolved with the above PR
