### ISSUE TITLE
rtl8192ee error of this agent is reported first - 2022.11.01

### ISSUE THREAD

**Issue by tjulioh** [archlinux/archinstall#1554]
Hi, trying a new installation, but the error is occurring with wifi pcie (with rj45 work fine):

```
pcieport 0000:00:1d.2: AER: Error of this agent is reported first
rtl8192ee 0000:05:00.0: AER: Error of this agent is reported first
```

**Comment by dravenk** [comment]
I had the same problem when I tried to add additional disks using pcie to Nvme, but I using Ubuntu not Arch.

**Comment by dravenk** [comment]
This is the answer to my problem. 
https://askubuntu.com/questions/1213973/how-to-repair-kernel-error-pcieport-aer-p-pcieport-device-8086a110-error-st

>`sudo -H gedit /etc/default/grub # edit this file`
Locate the string "quiet splash" and change it to `"quiet splash pci=noaer"`.
`sudo update-grub # update GRUB`
`reboot` # reboot the computer

**Comment by bjorn-helgaas** [comment]
Can you please report this to linux-pci@vger.kernel.org? Then we can try to fix the underlying problem so the parameter is not needed for future kernels.

It's helpful if you can include a complete dmesg log from the most recent kernel you have (ideally an upstream kernel) and the output of "sudo lspci -vv". The linux-pci@vger.kernel.org mailing list only accepts plain-text email and limits the message size, so it may be easiest to open a report at https://bugzilla.kernel.org and include the URL in your email.

**Comment by svartkanin** [comment]
This is not a archinstall issue
