### ISSUE TITLE
Disk Encryption - AttributeError: Nonetype object has no attribute `hsm_device`

### ISSUE THREAD

**Issue by Syzygianinfern0** [archlinux/archinstall#1562]
I don't have a proper error log, just a picture. Sorry about that. This is on the master branch (following [this ](https://github.com/archlinux/archinstall#using-a-live-iso-image)method). 

![PXL_20221113_071123280](https://user-images.githubusercontent.com/31875325/201542053-0c873032-33e1-486a-9299-25550818d853.jpg)

**Comment by svartkanin** [comment]
Thanks for reporting this, it's a bug in a newly merged code. I'll fix that asap

**Comment by Torxed** [comment]
Merged the fix, it should be in `master` and the upcoming version :)
