### ISSUE TITLE
Installation guide change: Use `pacstrap -K`

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1569]
Add `-K` option to `pacstrap` call.

### ArchWiki edit summary

> [→‎Install essential packages](https://wiki.archlinux.org/title/Installation_guide#Install_essential_packages): use pacstrap -K to generate a new pacman master key instead of copying it from the host, this avoids issues if the host's keyring was created when the time/timezone was incorrect and should generally be considered "safer"; see [Talk:Installation guide#Use pacstrap -K](https://wiki.archlinux.org/title/Talk:Installation_guide#Use_pacstrap_-K)

### ArchWiki diff

https://wiki.archlinux.org/index.php?title=Installation_guide&diff=750948&oldid=741457

### Relevant code

https://github.com/archlinux/archinstall/blob/126f56169d6faacd492b0b0f10c18762cf42a2ba/archinstall/lib/installer.py#L399

**Comment by KenEkanem** [comment]
This has been implemented.

**Comment by Torxed** [comment]
> This has been implemented.

it has? oÔ

**Comment by codefiles** [comment]
No it has not.

https://github.com/archlinux/archinstall/blob/79eb6bba627c4c70f24a265ac0b2ef9cbfbbd211/archinstall/lib/installer.py#L421

@Torxed, should this change be made?

**Comment by KenEkanem** [comment]
> No it has not.
> 
> https://github.com/archlinux/archinstall/blob/79eb6bba627c4c70f24a265ac0b2ef9cbfbbd211/archinstall/lib/installer.py#L421
> 
> @Torxed, should this change be made?

Oh yeah! You're right. It hasn't been implemented.

**Comment by Torxed** [comment]
> No it has not.
> 
> https://github.com/archlinux/archinstall/blob/79eb6bba627c4c70f24a265ac0b2ef9cbfbbd211/archinstall/lib/installer.py#L421
> 
> @Torxed, should this change be made?

It looks like it's the recommended way, so let's do it and see how it behaves :)
