### ISSUE TITLE
Can't reselect drive

### ISSUE THREAD

**Issue by xxyzz** [archlinux/archinstall#1574]
Reselect the "Drive(s)" option will get `ValueError` from here: https://github.com/archlinux/archinstall/blob/126f56169d6faacd492b0b0f10c18762cf42a2ba/archinstall/lib/menu/simple_menu.py#L660

because the `item` variable is a `BlockDevice` object.

**Comment by svartkanin** [comment]
This is resolved with the latest rewrites
