### ISSUE TITLE
Will you add unity desktop into archinstall?

### ISSUE THREAD

**Issue by mumin16** [archlinux/archinstall#1577]
Will you add unity desktop into archinstall?

https://9to5linux.com/you-can-now-install-ubuntus-unity-desktop-on-arch-linux-heres-how

**Comment by Torxed** [comment]
If there's public interest for it, and someone wants to maintain the profile. Then I don't see why not :)

**Comment by dylanmtaylor** [comment]
> If there's public interest for it, and someone wants to maintain the profile. Then I don't see why not :)

I'm against it because as documented in the post above, it needs a custom repo added to pacman.conf.

**Comment by Torxed** [comment]
Dang, assumed it was in the repo's.
Thanks @dylanmtaylor! I'll close this issue since it's blocked by AUR/External repo.
