### ISSUE TITLE
archinstall "list index out of range"

### ISSUE THREAD

**Issue by cabiste69** [archlinux/archinstall#1586]
I'm trying to install arch on my machine and every time i try to use `archinstall` i get an out of range error when mounting partitions
![16702439378522063780540266753858](https://user-images.githubusercontent.com/55938130/205639337-29fe07fd-b590-4842-9cba-c9dac66edef9.jpg)

I'm only choosing 1 drive which is my SSD and no matter if i partition it myself or choose the auto partition i always get this error

**Comment by ShaunTheSalvo** [comment]
I can confirm this; receiving the same error.

**Comment by cabiste69** [comment]
it always worked for me when i use a virtual machine but never worked when i tried to install arch on my machine

**Comment by JCallicoat** [comment]
Can you show the output of `lsblk` and `blkid` after you get that error and can you please attach /var/log/archinstall/install.log here?

**Comment by cabiste69** [comment]
i already installed arch manually, if i try the archinstall again would it delete my stuf?

**Comment by Oyinbra** [comment]
> i already installed arch manually, if i try the archinstall again would it delete my stuf?

That depends on how you installed Arch manually and how you want to re-install with the archinstall script. A new install will always clear out the root partition but if you have a separate partition for home, you can exclude the home partition from your new installation.

**Comment by cabiste69** [comment]
i don't have a separate home partition...

**Comment by Oyinbra** [comment]
> i don't have a separate home partition...

Then a new installation on that same Partition will format the partition unless you want to dual boot in which you'll have to shrink your old Partition and create a new one for your new installation.

**Comment by marcelorsoares** [comment]
This worked for me:
https://github.com/archlinux/archinstall/issues/1557#issuecomment-1336453021

**Comment by Torxed** [comment]
Solved in [v2.5.3](https://github.com/archlinux/archinstall/releases/tag/v2.5.3rc1)*(rc1)*.
