### ISSUE TITLE
Only a few lines are visible when creating a user

### ISSUE THREAD

**Issue by arcolinuxz** [archlinux/archinstall#1588]
I do not know if you can do anything about this issue.

On virtualbox I create videos to promote the use of your script but ran a few times into an issue not being able to move out of the create user bit until I discovered there is text hidden. Arrow down will show you more text.

Is it possible for you to show all lines available. Did not test this on real metal how it looks.

My tutorial videos of archinstall are mostly on VB.

https://youtu.be/GzQoI4UFOB8

![image](https://user-images.githubusercontent.com/36679406/205852808-33027fdf-f575-4704-b155-4efdc39b5369.png)

archinstall 2.5.2-1 on archlinux iso of 22.12.01

**Comment by arcolinuxz** [comment]
Ps. did you hear from others that the option to use grub leaves you in a failed grub installation when you reboot?
Or is it just me?
If so I can make a different issue.

**Comment by arcolinuxz** [comment]
My gut feeling told me that the grub issue I have on VB or real metal see https://github.com/archlinux/archinstall/issues/1588#issuecomment-1338923720 might have to something to do with sdb usb reported on 
https://github.com/archlinux/archinstall/issues/1557

IF I unplug the arch linux usb - grub installs just fine.
so both issues are related in that matter

**Comment by svartkanin** [comment]
I think this should be resolved
