### ISSUE TITLE
archinstall  硬盘分区挂载的bug,超过2个分区，会导致整个install流程失败

### ISSUE THREAD

**Issue by six7ths** [archlinux/archinstall#1589]
用archinstall最新版，我只能挂载/boot和/分区，其他分区无法挂载上。 

即便用archinstall本身来分区和挂载，只要分区数超过2个，比如3、4、5个以上，最后执行安装流程时，会导致整个安装流程异常跳出

只有挂载两个分区时，且为/boot和/时，其他分区都不挂载，这时才能执行安装流程成功。 

请帮助修改这个安装bug, 非常痛苦痛苦。

**Comment by Torxed** [comment]
Unfortunately I do not have the fonts or enough understanding of the language to help.
If possible, please provide a English description and a `install.log` for further assistance.

I'll close this ticket for now, and once the above is provided I can re-open it :)
