### ISSUE TITLE
Partition /mnt/archinstall/boot too full

### ISSUE THREAD

**Issue by Confuze** [archlinux/archinstall#1597]
I'm trying to multiboot arch linux with manjaro and windows but archinstall keeps failing when it tries to install some packages.

Here's whole error:
https://imgur.com/a/B004woX

I'm using v2.5.0 because the latest version (v2.5.2) has some other issues with my nvme drive. (Described it in #1593)

Here's my drive setup: (photo from v2.5.2 but I have the exact same setup in v2.5.0)
https://imgur.com/a/s0mP7Cz

And here's my whole config: (again, different version but config is the same)
https://imgur.com/a/UD1hd1p

I tried unchecking multilib and additional packages but it still tries to install a lot of stuff in the boot partition (whcich I explicitly set to be mounted to /boot and have another one mounted to /)

I'd love to provide the whole log file but I have no idea how to save it. Any tips?

**Comment by lucasvs** [comment]
I also got this error today, i typed yes each time the error popped up and somehow the last time it worked.

**Comment by Confuze** [comment]
> I also got this error today, i typed yes each time the error popped up and somehow the last time it worked.

Lol that's one way to fix problems for sure. Gonna try screaming yes at it then. Thanks.

**Comment by Torxed** [comment]
I'll post a new release and then i'll start working on https://github.com/archlinux/archinstall/issues/1650 which should resolve this.

**Comment by Confuze** [comment]
Awesome, thanks!
