### ISSUE TITLE
Problem with partitioning

### ISSUE THREAD

**Issue by mesteryui** [archlinux/archinstall#1599]
![IMG_20221217_202938](https://user-images.githubusercontent.com/108957859/208263474-6b7ca7a0-d541-4fd0-87d3-f0520f907961.jpg)

**Comment by critkitten** [comment]
duplicate of https://github.com/archlinux/archinstall/issues/1557

**Comment by Confuze** [comment]
> duplicate of https://github.com/archlinux/archinstall/issues/1557

Yup, should fix itself with retries. If not, try installing a different version of the installer. (Guide in readme) If none of that works, try using the solution in #1557 which involved changing the code with a command.

**Comment by svartkanin** [comment]
This is resolved with the latest rewrites
