### ISSUE TITLE
nvidia open source driver and zen kernel

### ISSUE THREAD

**Issue by aucub** [archlinux/archinstall#1600]
I selected the zen kernel and nvidia open source drivers, but installed nvidia-open instead of nvidia-open-dkms.

**Comment by lavafroth** [comment]
Can confirm. You have to manually add nvidia-open-dkms to the additional packages list. Perhaps we can check if a selected kernel is custom and add necessary dkms packages implicitly?

**Comment by Torxed** [comment]
> Perhaps we can check if a selected kernel is custom

I think this sounds like a good approach!

**Comment by lavafroth** [comment]
I have a couple ideas on implementing this when selecting nvidia drivers.
* Have a list of custom kernels (like zen, hardened, etc.) and checking if any of them are selected.
* Have a class Kernel and an Enum attribute (with enum types like Mainline, Custom) and check that attribute while selecting a nvidia drivers.

Although I prefer the latter way, it might be an overkill for something this simple. Suggestions?

**Comment by Torxed** [comment]
> * Have a list of custom kernels (like zen, hardened, etc.) and checking if any of them are selected.

This one we have already I believe. It's a list within `Installer`.
