### ISSUE TITLE
archinstall fails after adding partitions to a block device.

### ISSUE THREAD

**Issue by aaron-gh** [archlinux/archinstall#1602]
### issue
When running archinstall, the script exits with a traceback after adding partitions to the selected block device(s)
#### configuration
This was tested with a qemu virtual machine, not real hardware. Real hardware test can be performed if requested.
#### Configuration
The configuration selected in the guided installer is the following:
`{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "config_version": "2.5.2",
    "debug": false,
    "desktop-environment": "i3",
    "gfx_driver": "All open-source (default)",
    "harddrives": [
        "/dev/vda"
    ],
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {},
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "iso"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "orca",
        "git",
        "espeakup",
        "alsa-utils",
        "git"
    ],
    "parallel downloads": 0,
    "profile": {
        "path": "/root/archinstall/archinstall/profiles/desktop.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "UTC",
    "version": "2.5.2"
}
{
    "/dev/vda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}`
#### error
The error returned is below:
`File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/archinstall/archinstall/__main__.py", line 15, in <module>
    archinstall.run_as_a_module()
  File "/root/archinstall/./archinstall/__init__.py", line 307, in run_as_a_module
    script.execute()
  File "/root/archinstall/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/archinstall/archinstall/examples/guided.py", line 311, in <module>
    perform_filesystem_operations()
  File "/root/archinstall/archinstall/examples/guided.py", line 126, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/root/archinstall/archinstall/lib/disk/filesystem.py", line 46, in __exit__
    raise args[1]
  File "/root/archinstall/archinstall/examples/guided.py", line 127, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/root/archinstall/archinstall/lib/disk/filesystem.py", line 116, in load_layout
    if partition in disk_encryption.partitions:
AttributeError: 'NoneType' object has no attribute 'partitions'`

**Comment by svartkanin** [comment]
This issue is resolved
