### ISSUE TITLE
exited with abnormal exit code [256]: b`File system "/dev/dm-0" is not located on the partitioned block device. \r\n'

### ISSUE THREAD

**Issue by float3** [archlinux/archinstall#1605]
[install.log](https://github.com/archlinux/archinstall/files/10289600/install.txt)

Please let me know what other info you need.

**Comment by ynnckvdv** [comment]
@float3 were you able to fix this? I keep running into it now.

**Comment by float3** [comment]
no

**Comment by float3** [comment]
from the archinstall discord:
Workaround if you have a NVMe device and keep getting issues:

1) Manually partition your drive(s)
2) Manually mount both /mnt/archinstall (root)  and /mnt/archinstall/boot (boot)
3) Run archinstall as usual
4) Go to disk selection and press Ctrl+C (This aborts disk operations)

Then continue with your installation as per normal.
Apologies, the issue is being tracked here independent of symptoms: https://github.com/archlinux/archinstall/issues/1495

**Comment by adrfantini** [comment]
> from the archinstall discord: Workaround if you have a NVMe device and keep getting issues:
> 
> 1. Manually partition your drive(s)
> 2. Manually mount both /mnt/archinstall (root)  and /mnt/archinstall/boot (boot)
> 3. Run archinstall as usual
> 4. Go to disk selection and press Ctrl+C (This aborts disk operations)
> 
> Then continue with your installation as per normal. Apologies, the issue is being tracked here independent of symptoms: #1495

How did you continue the install? If I do as you say, `archinstall` complains of "Missing configurations: Disk layout" and refuses to install.

**Comment by float3** [comment]
as I said I just continued as usual, I think that error message means that you didn't do step 4 correctly

**Comment by adrfantini** [comment]
¯\_(ツ)_/¯
didn't work for me!
In the end I just chose not to encrypt the boot partition, and it worked.

**Comment by svartkanin** [comment]
This is resolved with the recent changes
