### ISSUE TITLE
Problem on my pull request (changing of the files .po and .mo)

### ISSUE THREAD

**Issue by roxfr** [archlinux/archinstall#1609]
Hello,
My pull request to modify the translation doesn't work.
Could you help me, please.
Thank you.
Regards,
Roxfr

https://github.com/archlinux/archinstall/pull/1608

![image](https://user-images.githubusercontent.com/52124613/209987462-a914bba3-21ab-475a-bebf-ad4ec02d366f.png)

**Comment by svartkanin** [comment]
PR was merged
