### ISSUE TITLE
Grub install issue due to specific motherboard

### ISSUE THREAD

**Issue by ChocolatCheeseCakeAfterComputers** [archlinux/archinstall#1611]
first time github user. Please be gentle.

grub-install fails with the following message:
"Could not prepare Boot variable: Read-only file system"

after many attempts it seams that efivars has to be mount as read-write.
(see https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Bootloader#Install )

remounting `/sys/firmware/efi/efivars` with read-write enabled solves the problem.
I now have a functioning system.
But systemd-boot still does not work for some reason. 

1. I remounted `efivars` with the command `mount -o remount,rw /sys/firmware/efi/efivars`
2. I ran `archinstall` and chose grub as my bootloader
3. Everything works

I only have this problem on my laptop. My desktop is fine. I guess it has to do something with the manufacturer Acer. 

Looking at the source code I noticed that in `archinstall/lib/user_interaction/installer.py:929` the same grub install command is used. Maybe adding the remount command helps. 

Here may be some helpful wiki entries:
https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface#Mount_efivarfs
https://wiki.archlinux.org/title/GRUB#Common_installation_errors

I would like to have done it myself but I am new to git and github and don't know how to use it. I also don't want to test anymore since I worked with grub enough. It already took me too long to figure out why it won't install.

**Comment by svartkanin** [comment]
I'm not sure this is a archinstall issue
