### ISSUE TITLE
Unknown filesystem type [8192]

### ISSUE THREAD

**Issue by Wraaath** [archlinux/archinstall#1612]
Tried dualbooting Arch on my laptop and I keep getting errors like in attached log.
[install.log](https://github.com/archlinux/archinstall/files/10340211/install.log)

**Comment by TuxMC-sys** [comment]
It looks like this is a recurring issue within the project. For the time being maybe try writing a new partition table to the disk before install, and when the archISO is booted up unplug the flash drive (it's all in ram). Also it seems like it only happens some installs so just give another go at the problem.

**Comment by Wraaath** [comment]
> 

So I should partition my drive in Windows first? I did write the partition changes when installing if I'm not mistaken.

**Comment by TuxMC-sys** [comment]
I would recommend doing it from the ArchISO

**Comment by Wraaath** [comment]
> I would recommend doing it from the ArchISO

Thats what I did ¯\_(ツ)_/¯.

**Comment by svartkanin** [comment]
There have been a lot of updates since this issue was raised. If it still happens we can re-open it
