### ISSUE TITLE
Install failing "Could not find the new PARTUUID after adding the partition."

### ISSUE THREAD

**Issue by zlehnherr1** [archlinux/archinstall#1615]
Tried several times to install after putting in the install options. Happened 3 times before giving up as the error was the same. Tried removing drive with ISO and got the same result. Saw in second to last line it was trying to use fat32, but I selected ext4 as the filesystem type.

![ArchInstallFail](https://user-images.githubusercontent.com/122128543/211108996-70106bd4-a736-4b20-9203-7026644652de.jpg)

**Comment by Confuze** [comment]
I recently encountered a similar issue. Have you tried using an older version? Downgrading to 2.5.0 fixed the problem for me. If you're confused, the readme has a guide on how to install a different version from source.

Also, if you wanna help the developer out, I think some more information about the issue and your setup (log file would be best) could make their job much easier.

**Comment by zlehnherr1** [comment]
Can no longer recreate the issue above, as I am now running into an issue earlier on, but here is the log from the new issue (will also create new issue ticket)
[install.log](https://github.com/archlinux/archinstall/files/10365195/install.log)

**Comment by svartkanin** [comment]
There have been a lot of updates since the issue was raised. If it still happens we can re-open it
