### ISSUE TITLE
Possibility to run a pre-, chroot- and postscript

### ISSUE THREAD

**Issue by rosaLux161** [archlinux/archinstall#1622]
There should be a possibility of running a pre, chroot and postscript.

# Motivation

Functions that have not yet been implemented in the installation script, but are desired can thus be completed by adding a custom script.

Even though the first priority should be to implement functions natively in the installation script, it is possible to make the script easy more powerful.

Examples for this are:

> * Specific manual partitioning, which cannot (yet) be executed in the script.
> * Activation of services
> * Copying of install logs or similar into the finished installed system (maybe this already happens, but is also only an example)

# How could this work?

Conceivable would be CLI parameters, e.g. --pre-scripts, --chroot-scripts, --post-scripts, which take an array of scripts that are executed in the respective context.

# Example

`archinstall --pre-scripts my_manual_partitioning.sh my_manual_mounting_to_mnt_whatiwant.sh --chroot-scripts my_service_enabling.sh --post-scripts my_copy_dump_stuff.sh --mount-point /mnt/whatiwant`

**Comment by TuxMC-sys** [comment]
And what would these scripts do/be? It might be better to open a PR for this.

**Comment by svartkanin** [comment]
Most of these things are available in the installer. 
If a more complex partitioning is needed then that can be accomplished manually upfront and then the partitions can be selected in the installer. 
If none of these work, there is also the option to script the whole installation yourself using building blocks that are available in the code
