### ISSUE TITLE
20 GB root partition?

### ISSUE THREAD

**Issue by se7en-x230** [archlinux/archinstall#1623]
Default partitioning.
My / is with 20 GB mostly around 80% full that makes me kind of nervous.
Wouldn't be 25 or 30 GB be a better choice?

**Comment by TuxMC-sys** [comment]
Do you have a /home as well?

**Comment by se7en-x230** [comment]
Yes I do

**Comment by esemeniuc** [comment]
Would be great to have this configurable, or there should be an option to resize the partition :)

**Comment by svartkanin** [comment]
There's a lot of opinions around this. The easiest to solve this is to go to the manual partitioning and choose the default layout. Then modify the auto populated partitions and edit the size accordingly
