### ISSUE TITLE
Archinstall doesn't install xdg-desktop-portal. 

### ISSUE THREAD

**Issue by Lokito23** [archlinux/archinstall#1629]
Used latest version of Archinstall, KDE preset.

Pipewire wasn't finding xdg-desktop-portal, but it was because it wasn't installed.

Not sure if this is an Archinstall problem or a plasma-meta problem, but it seems I am the first one to report it.

**Comment by Anonymo** [comment]
I think the package for KDE would be **xdg-desktop-portal-kde**

**Comment by Lokito23** [comment]
xdg-desktop-portal-kde does come installed, but is not enabled, and even after enabling it, pipewire still broke.

I had to install xdg-desktop-portal itself to fix it.

**Comment by svartkanin** [comment]
This should be resolved
