### ISSUE TITLE
Should KDE and KDE-wayland be combined?

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#163]
For simplicity's sake, couldn't both of these profiles be combined into one, installing the packages for each to conceivably run, and allowing either session to be selected from SDDM? The benefit of doing it this way is that it would allow a user to switch effortlessly from X.org to Wayland in the future - KDE Wayland support is improving and it does seem to be the future. It's nice to test it out every once in a while and see if it works well enough to use full-time, and this would provide a consistent experience with the GNOME install that currently lets you select X or Wayland via GDM.

**Comment by m1ten** [comment]
Add sub-categories?

- KDE
	- KDE Xorg
	- KDE Wayland
	- KDE Minimal

- GNOME
	- GNOME Minimal

**Comment by dylanmtaylor** [comment]
I think they should all be minimal installs with users adding packages later, but as far as Wayland/Xorg goes, I don't see why we can't have both as options from the greeter like GNOME does.

**Comment by Torxed** [comment]
Technically I don't see why this can't be done, it would require us to choose a default for the first launch maybe to guide users to something that's stable, which means a little bit more maintenance.

The down side to this, is that it will pull in more packages than say most people need, which is perhaps not ideal.
And in regards to going minimal by default would benefit the mirrors and probably most arch native users. But the down side would be a bit confusing for new users, and since this tool mainly aims towards welcoming new users into the echo-sphere, I think going minimal by default might be confusing for the target audience.

So personally I'm torn, but I also don't know how much extra packages would be required since I don't use wayland or kde myself. Do we have statistics on the package sizes and what the default would be on first launch (and how to modify it)?

**Comment by dylanmtaylor** [comment]
> Technically I don't see why this can't be done, it would require us to choose a default for the first launch maybe to guide users to something that's stable, which means a little bit more maintenance.
> 
> The down side to this, is that it will pull in more packages than say most people need, which is perhaps not ideal.
> And in regards to going minimal by default would benefit the mirrors and probably most arch native users. But the down side would be a bit confusing for new users, and since this tool mainly aims towards welcoming new users into the echo-sphere, I think going minimal by default might be confusing for the target audience.
> 
> So personally I'm torn, but I also don't know how much extra packages would be required since I don't use wayland or kde myself. Do we have statistics on the package sizes and what the default would be on first launch (and how to modify it)?

Regarding this, I have a few, admittedly very opinionated thoughts about this:

* Philosophically, Arch Linux is very similar to Fedora as in it has a principle of being first; early adoption of new technologies as soon as they come out
* Fedora has deemed the KDE Wayland session to be good enough to ship as default in Fedora 34 for general consumption, and for both GNOME and KDE it is reasonably stable already.
* As time goes on, Wayland is becoming more mature and there are few things it doesn't do as well as Xorg these days. Ubuntu and Fedora are pretty much pushing it as the default
* Xorg is basically unmaintained except for security patches; new development is happening in the Wayland space
* Given the last few points, I feel that eventually, it is inevitable that distros will all likely ship this as default. I feel that Arch choosing Wayland for GNOME/KDE/Sway as a default solution with an option for users to select Xorg as a fallback is sane.

As far as extra packages go for these, it is quite minimal, and may not even amount to many at all, as your average Wayland install will also have Xwayland by default anyways, so if you look at it that way, it's not like we're talking hundreds of MB additional. To switch to Xorg or back, it'd be a simple dropdown in the greeter of choice to boot another session. The benefit to only having one KDE option far outweighs the cons as it simplifies install and promotes future flexibility -- users can no easily switch sessions as they'll already have the packages they need installed without having to either install them themselves or do a reinstallation with another option selected.

**Comment by Torxed** [comment]
@dylanmtaylor I think you make some very strong points to your argument. I especially agree with the fact that xorg is unmaintained *(I read an interview I believe where the main developer used those words himself, but can't find it as of writing this)*.

This would probably make it less confusing for new users as well, if there's only one profile to choose from.
So from my end of things, I'm for this change! Unless there's any objections, this will be introduced either in the next patch release (v2.1.4) or the new minor release (v2.2.0), essentially whenever someone manages to build and test it in time.

**Comment by m1ten** [comment]
Currently, KDE Wayland requires Xorg. That will probably change in the future.

**Comment by dylanmtaylor** [comment]
> Currently, KDE Wayland requires Xorg. That will probably change in the future.

Yes, but this doesn't change the fact that the solution can be implemented as I have described with the packages for both sessions being installed in a 'kde' option. Even if it does change, I'm all for having it install both, as the overhead is minimal and it gives users choice as far as what they want to run.

**Comment by dylanmtaylor** [comment]
> @dylanmtaylor I think you make some very strong points to your argument. I especially agree with the fact that xorg is unmaintained _(I read an interview I believe where the main developer used those words himself, ~but can't find it as of writing this~ https://ajaxnwnk.blogspot.com/2020/10/on-abandoning-x-server.html)_.
> 
> This would probably make it less confusing for new users as well, if there's only one profile to choose from.
> So from my end of things, **I'm for this change! Unless there's any objections**, this will be introduced either in the next patch release (v2.1.4) or the new minor release (v2.2.0), essentially whenever someone manages to build and test it in time.
> 
> --
> 
> In regards to minimal profiles by default, I'm still a bit torn, mainly because I don't know which applications are expected in these environments. I like the idea of building something up, and not forcing say the KDE browser on people when the majority is going to run chrome/chromium/firefox/vivalid etc anyway.

I made an attempt at changing this in PR #189 - if that looks good to you, feel free to pull it. I'm not sure how to make the Wayland session the default in SDDM, but I'm sure there's a good way to do that.

**Comment by advaithm** [comment]
Fedora kind jumped, the gun with wayland being default. with plasma in xorg its very stable with little to no issues, on wayland while AMD/Intel support is almost indistinguishable from  xorg. Nvidia wayland is unusable. I've tried using it several times. your lucky if you are able to load up plasma. most of the time it crashes sddm. when it does load up into plasma you'll find its filled with rendering issues that make it unusable. I feel we should hold off on this until plasma wayland matures more.
base on [this article](https://www.phoronix.com/scan.php?page=news_item&px=NVIDIA-GBM-Mesa-Backend-Alt) by phoronix its very likely that nvidia will support GBM meaning a lot plasma wayland probably will change. I feel forcing plasma wayland in a not ready state on to users is a bad move

**Comment by dylanmtaylor** [comment]
> Fedora kind jumped, the gun with wayland being default

I disagree, but I was using Intel hardware (ThinkPad X1 Carbon Gen 3 if you are curious) to test their beta - not Nvidia, so it worked relatively well. Regardless, it's good to have the option. It's getting better over time, and releases are pretty stable for the most part. If Nvidia adds GBM support for it will be better :)

> I feel forcing plasma wayland in a not ready state on to users is a bad move

Forcing anything on users is a bad move - this is Arch Linux, it's all about choice and flexibility here. My proposal is not "If you use KDE you must use Wayland", it's to have one single install option for KDE that installs both sessions for Wayland and Xorg, which the user selects via SDDM. This works for everyone and lets users easily switch from Xorg to Wayland when ready (or vide versa) without manually installing packages.

**Comment by advaithm** [comment]
not everyone wants to install wayland. if you force install wayland people will get angry, I would suggest maybe instead we have one file and based on a argument maybe `wayland=True` we install the wayland session

**Comment by dylanmtaylor** [comment]
> not everyone wants to install wayland. if you force install wayland people will get angry, I would suggest maybe instead we have one file and based on a argument maybe `wayland=True` we install the wayland session

That seems like it isn't very sensible, Wayland doesn't add too much since it's a protocol that more or less has KWin interacting with the drivers/kernel directly instead of going through Xorg, it's not a big install size difference. I feel this is a good default for most people and if someone is really adamant they don't want Wayland on their system after the installation, they can always do 'pacman -R plasma-wayland-session`.

**Comment by dylanmtaylor** [comment]
So looking at the size differences - the session itself is 6KB and it pulls in some wayland specific deps:

qt5-wayland: 6.1MB
kwayland-integration: 130 KB
xorg-xwayland: 2.2MB
plasma-wayland-protocols: 138 KB

Unless I missed something, the difference is <10 MB, or completely insignificant in 2021.

**Comment by advaithm** [comment]
Imo plasma wayland isn't ready and won't be for a while. there are still issues with things like latte dock.  we should hold of for the next release before we ship it by default.

**Comment by dylanmtaylor** [comment]
I think we will have to agree to disagree. Whether to ship it by default should boil down to a few things - 

* Having one option instead of two simplifies maintenance (and is consistent with GNOME which has both sessions under one label)
* Does including it in the default installation add substantial space utilization? No, it seems to be very minimal.
* Does this 'force' anyone to use a Wayland session if they prefer Xorg? No, it gives them the choice between both.
* Does this add substantial burden to the user to get their preferred session type? No, it's a one-time change on the greeter (SDDM) before session login. It greatly eases the transition from one to another though if they want to change later.

I feel like it's perfectly usable *now* for most people (maybe not on Nvidia hardware, haven't tested that personally, but it's not like this breaks Xorg), and the pros in my opinion outweigh the cons. For users not familiar with how to install a new session and switch to it after the install, it makes it easier for them to do so when it's pre-installed. From what I see, Wayland on KDE is improving, very quickly, and as you said the Nvidia GDM changes will make it even more functional. I expect full parity very soon (would not surprise me if it's very close this year). Having a choice is a good thing, and think of the target audience here: Arch Linux users. We're infamously more technologically savvy early adopters. For advanced users who want to try things out, this is a great change, and honestly the flow of log out -> select session -> log in is very nice to have. Previously, you got one or the other. This is so much simpler and makes maintainability better.

**Comment by advaithm** [comment]
I created a _post_install hook for i3/i3-gaps. i think it would be better to use it and ask the user if the want wayland and explain on the proprietary nvidia drivers the session is currently not in a usable state. The kde plasma teams does want to go wayland first but currently do not have it as default due to the broken state of parts of plasma.

**Comment by advaithm** [comment]
I created a pr that uses the _post_install hook

**Comment by Torxed** [comment]
So I do like the option to have both present, as it doesn't add a lot of overhead.
But I do wish that xorg is the default on the first boot *(at least if nvidia is detected, for now)*.

Would that be possible to achieve? That would settle the fact that nvidia is shaky and only "people that know the risk" will and should go up and change the default on greeter.

**Comment by advaithm** [comment]
My pr uses the postinstall hook to ask the user if they want to use plasma wayland as officially the kde devs don't thinks it's ready to be default. Although they are working on making it production ready

**Comment by dylanmtaylor** [comment]
> So I do like the option to have both present, as it doesn't add a lot of overhead.
> But I do wish that xorg is the default on the first boot _(at least if nvidia is detected, for now)_.
> 
> Would that be possible to achieve? That would settle the fact that nvidia is shaky and only "people that know the risk" will and should go up and change the default on greeter.

I think this is fine, so in that case, can we install the packages for both in every instance, and set xorg as the default if the Nvidia driver is selected (this is already handled by the conditional. I think the approach in #192 is close to what we want, but I'd change the post-hook from determining and installing additional packages to outputting the string "Plasma has known compatibility issues with the proprietary Nvidia driver. Using the Xorg session with this driver is recommended." Does that sound like a good approach to you both @Torxed @advaithm ?

**Comment by advaithm** [comment]
I think it would be better to ask the user if they want to install plasma-wayland it gives the user more choice/control over their installation

**Comment by advaithm** [comment]
yeah I'm for that

**Comment by dylanmtaylor** [comment]
> yeah I'm for that, although I still feel the user should be given choice if they want to install/use wayland

Do you think there will be any issues with the packages for it to be functional being installed on the user's disk? It's very small. I think most distros shipping these days, including Fedora/Ubuntu/OpenSUSE ship both sessions out of the box. As far as being given the choice, I agree with you, and that's why I think the selection at the greeter is nice. Since the plasma devs want Wayland to eventually replace Xorg and it is the future, this is also a way to have installs be more 'future-proof' without user intervention.

**Comment by advaithm** [comment]
We can change the code when the time comes. forcing users to switch to something which a lot of devs with in kde feel isn't ready to be the default session might annoy a lot of users. a lot of users felt like they were being forced to be guinea pigs when fedora switched

**Comment by dylanmtaylor** [comment]
> We can change the code when the time comes. forcing users to switch to something which a lot of devs with in kde feel isn't ready to be the default session might annoy a lot of users. a lot of users felt like they were being forced to be guinea pigs when fedora switched

It doesn't need to be default, just as a pre-installed option. Xorg can be the default with a choice for "Would you like to enable the Plasma Wayland session type be default (this has known compatibility issues with the proprietary Nvidia driver)?", and I would be happy with that.

**Comment by advaithm** [comment]
okay. I'm fine with that. I'll also add a section on would you like to uninstall it if they are on nvidia since its basically unusable

**Comment by dylanmtaylor** [comment]
> okay. I'm fine with that. I'll also add a section on would you like to uninstall it if they are on nvidia since its basically unusable

I'm glad we've reached a compromise, but I'm not sure how I feel about the uninstall choice. Upsteam devs seem to think it's usable, and more bug fixes are coming to it over time, especially with the Nvidia 470 series drivers. https://community.kde.org/Plasma/Wayland/Nvidia 

Even if it isn't ideal now (and it wouldn't need to be default), let's think about how users will interpret this message in the future if it is not changed. It basically tells them it doesn't work when that might not be the case when they do their installation. Realistically if it's not default, users will likely not care that it is installed, and it'll probably start working as more driver patches come in.

**Comment by advaithm** [comment]
the uninstall section is only for Nvidia users

**Comment by Torxed** [comment]
> > So I do like the option to have both present, as it doesn't add a lot of overhead.
> > But I do wish that xorg is the default on the first boot _(at least if nvidia is detected, for now)_.
> > Would that be possible to achieve? That would settle the fact that nvidia is shaky and only "people that know the risk" will and should go up and change the default on greeter.
> 
> I think this is fine, so in that case, can we install the packages for both in every instance, and set xorg as the default if the Nvidia driver is selected (this is already handled by the conditional. I think the approach in #192 is close to what we want, but I'd change the post-hook from determining and installing additional packages to outputting the string "Plasma has known compatibility issues with the proprietary Nvidia driver. Using the Xorg session with this driver is recommended." Does that sound like a good approach to you both @Torxed @advaithm ?

I think this is a good way forward. I get that it's a minor inconvenience to have a few extra packages installed, but the desktop profiles will never ever possibly cater to everyone - they are meant to ease the use for most people.

And considering it's a matter of when, not if - wayland will be the default (since xorg is abandonware more or less), I think it's nice to have there so people can try it out once in a while. It would also boost bug testing and give wayland a wider test-audience.. again, as long as it's not default and don't cause like 8GB extra downloads - I think this is the way forward.

I didn't expect this topic to be so loaded - and I think it's impossible to not step on someones toes here.
As long as this doesn't actively break things for everyone I think we've made progress.

**Comment by dylanmtaylor** [comment]
> > > So I do like the option to have both present, as it doesn't add a lot of overhead.
> > > But I do wish that xorg is the default on the first boot _(at least if nvidia is detected, for now)_.
> > > Would that be possible to achieve? That would settle the fact that nvidia is shaky and only "people that know the risk" will and should go up and change the default on greeter.
> > 
> > 
> > I think this is fine, so in that case, can we install the packages for both in every instance, and set xorg as the default if the Nvidia driver is selected (this is already handled by the conditional. I think the approach in #192 is close to what we want, but I'd change the post-hook from determining and installing additional packages to outputting the string "Plasma has known compatibility issues with the proprietary Nvidia driver. Using the Xorg session with this driver is recommended." Does that sound like a good approach to you both @Torxed @advaithm ?
> 
> I think this is a good way forward. I get that it's a minor inconvenience to have a few extra packages installed, but the desktop profiles will never ever possibly cater to everyone - they are meant to ease the use for most people.
> 
> And considering it's a matter of when, not if - wayland will be the default (since xorg is abandonware more or less), I think it's nice to have there so people can try it out once in a while. It would also boost bug testing and give wayland a wider test-audience.. again, as long as it's not default and don't cause like 8GB extra downloads - I think this is the way forward.
> 
> I didn't expect this topic to be so loaded - and I think it's impossible to not step on someones toes here.
> As long as this doesn't actively break things for everyone I think we've made progress.
> 
> So lets start with this, and we can fine tune it as we go along. It's a good starting point.

Excellent, this sounds good to me. From my initial look at it, the difference is ~10 MB. It's honestly very small.

**Comment by advaithm** [comment]
okay I've actually gone through the fedora package spec, I have a really rough idea of how to set the default session

**Comment by dylanmtaylor** [comment]
> okay I've actually gone through the fedora package spec, I have a really rough idea of how to set the default session

I made a PR with my suggested wording here https://github.com/advaithm/archinstall/pull/1

**Comment by dagdrommer** [comment]
> > Technically I don't see why this can't be done, it would require us to choose a default for the first launch maybe to guide users to something that's stable, which means a little bit more maintenance.
> > The down side to this, is that it will pull in more packages than say most people need, which is perhaps not ideal.
> > And in regards to going minimal by default would benefit the mirrors and probably most arch native users. But the down side would be a bit confusing for new users, and since this tool mainly aims towards welcoming new users into the echo-sphere, I think going minimal by default might be confusing for the target audience.
> > So personally I'm torn, but I also don't know how much extra packages would be required since I don't use wayland or kde myself. Do we have statistics on the package sizes and what the default would be on first launch (and how to modify it)?
> 
> Regarding this, I have a few, admittedly very opinionated thoughts about this:
> 
>     * Philosophically, Arch Linux is very similar to Fedora as in it has a principle of being first; early adoption of new technologies as soon as they come out
> 
>     * Fedora has deemed the KDE Wayland session to be good enough to ship as default in Fedora 34 for general consumption, and for both GNOME and KDE it is reasonably stable already.
> 
>     * As time goes on, Wayland is becoming more mature and there are few things it doesn't do as well as Xorg these days. Ubuntu and Fedora are pretty much pushing it as the default
> 
>     * Xorg is basically unmaintained except for security patches; new development is happening in the Wayland space
> 
>     * Given the last few points, I feel that eventually, it is inevitable that distros will all likely ship this as default. I feel that Arch choosing Wayland for GNOME/KDE/Sway as a default solution with an option for users to select Xorg as a fallback is sane.
> 
> 
> As far as extra packages go for these, it is quite minimal, and may not even amount to many at all, as your average Wayland install will also have Xwayland by default anyways, so if you look at it that way, it's not like we're talking hundreds of MB additional. To switch to Xorg or back, it'd be a simple dropdown in the greeter of choice to boot another session. The benefit to only having one KDE option far outweighs the cons as it simplifies install and promotes future flexibility -- users can no easily switch sessions as they'll already have the packages they need installed without having to either install them themselves or do a reinstallation with another option selected.

I agree with @dylanmtaylor. Having xorg and wayland in one KDE option is ideal...especially in times where wayland might not work for some NVIDIA users (which they might not know when installing). Tough to keep the install minimal as possible I rather would consider dropping the `kde-applications-meta`, as this adds at least 600+ MB of mostly unnecessary apps and games to the installation.

**Comment by advaithm** [comment]
iirc there are plans for a minimal install of kde plasma, but no one has gotten around to it

**Comment by dagdrommer** [comment]
I will make an enhancement request for that, with a proposal of some basic kde apps, which are good for the start in a minimal environment.

**Comment by advaithm** [comment]
I think this issue can be closed now
