### ISSUE TITLE
Error partitioning disk --> Could not detect root ({root_partition}) or boot ({boot_partition}) in {self.target} based on: {self.partitions}")

### ISSUE THREAD

**Issue by Alexsussa** [archlinux/archinstall#1630]
After some installations I noticed two things:

1 - I can't partionate disks manually (cfdisk for example). I can just partionate for archinstall script.

2 - Obligatorily I have to create a separated partition for /boot.

Both things bring me same error in line 1024 from installer.py.

**Comment by svartkanin** [comment]
There were a lot of new updates to the codebase and this should be resolved
