### ISSUE TITLE
Wired headphone audio doesn't work on my hardware unless sof-firmware and alsa-firmware packages installed

### ISSUE THREAD

**Issue by chris03-dev** [archlinux/archinstall#1631]
Greetings!

I just discovered a problem (and a solution) with wired headphones audio. To elaborate, my computer houses a Celeron J4125 (Gemini Lake) processor and an Intel HD Sound Card. My last use with this installer is to setup MATE Desktop and Pipewire. I should also note that the issue occurs in my computer with both Pulseaudio and Pipewire installations. I have not tested my solution with Pulseaudio yet, and unfortunately I don't plan to do so anytime soon.

Right now I mainly just want to develop on Linux as a hobby, and I don't want to risk potentially throwing a wrench to my already functional system. My computer's network card is not very performant, and backing up my files as well as downloading all those packages again with my installation media in case something unexpectedly breaks is just not ideal for me. Besides, I already wasted enough hours in trial-and-error just trying to find a solution to this audio problem.

Anyway, I had to install two packages: `sof-firmware` and `alsa-firmware`.

`sof-firmware` is what my computer needed to detect its sound card. Unfortunately (and hopefully not due to lack of prior knowledge) I had to reboot my computer so that such sound card would show up in my audio settings.

`alsa-firmware` is what made the headphone jack port on my computer's chassis work properly. Without this package, I could only hear a brief snapping sound whenever I try to play any media with audio every few seconds.

The above packages also fixed the buggy audio in my VMware images with MATE and Pipewire installed.

This may not be substantial on its own, but I hope this feedback may help those with similar issues, and if possible, make its way into the developers of this project. I believe that these post-installation steps should not have to be painstakingly discovered by these users in the first place, and I hope some progress could be made towards determining whether these packages should be installed by default in the following months.

Thank you for your attention.

---

P. S. Not completely relevant, but way before I discovered the above solution, I had to use Bluetooth as a temporary workaround, and so I installed `blueman`. Surprisingly, I haven't found any issues so far with any Bluetooth audio devices I have used (despite the hearsay about Bluetooth supposedly not working properly or reliably in Linux).

Think it would be nice to provide an option to provide Bluetooth support in the Audio section of `archinstall`, since, at least in my use case, `blueman` was the only thing needed to make Bluetooth work. It may not even need to work with all sorts of hardware, as someone could just put "(experimental)" after it.

**Comment by svartkanin** [comment]
I think this should be resolved in the latest release

**Comment by sahaskamble** [comment]
Sorry for this late but I have a new HP 15s and there is the same problem my audio jack is not working even after installing correct firmware and all, even after installing pipewire-jack I was missing it but it not working at all only speakers are working

**Comment by svartkanin** [comment]
Please raise a new issue and provide the installation log
