### ISSUE TITLE
installation error with grup

### ISSUE THREAD

**Issue by MindCollaps** [archlinux/archinstall#1637]
I've been crying all day, trying to install arch linux, but even the archinstall doesn't work for me and I don't understand why

`Hardware model detected: Dell Inc. Latitude E5270; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Memory statistics: 15040540 available out of 16273492 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '710.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '238.5G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '600E-BE44', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1G'}, {'name': 'sda2', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': 'cb3193d8-be73-443b-9496-e36ab2c1389f', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '237.5G'}]}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202302', 'uuid': '2023-02-01-09-09-31-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.3G', 'children': [{'name': 'sdb1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202302', 'uuid': '2023-02-01-09-09-31-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '809M'}, {'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'CA18-653E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '15M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Could not decode JSON: lsblk: /dev/sdb1: not a block device
{
   "blockdevices": [

   ]
}

Hardware model detected: Dell Inc. Latitude E5270; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Memory statistics: 15047216 available out of 16273492 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '710.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '238.5G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '600E-BE44', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1G'}, {'name': 'sda2', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': 'cb3193d8-be73-443b-9496-e36ab2c1389f', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '237.5G'}]}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202302', 'uuid': '2023-02-01-09-09-31-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.3G', 'children': [{'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'CA18-653E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '15M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Password strength: weak
Password strength: strong
 * Passwords did not match * 
Password strength: strong
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "grub-install",
    "config_version": "2.5.1",
    "debug": false,
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "AName",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "de-latin1",
    "mirror-region": {},
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "nano"
    ],
    "parallel downloads": 0,
    "profile": null,
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "Europe/Berlin",
    "version": "2.5.1"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": true,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=238.5GB, free_space=1031kB+335kB, bus_type=sata), 1MiB->512MiB
Adding partition using the following parted command: /dev/sda mkpart primary fat32 1MiB 512MiB
Retrieving partition PARTUUID=a4047323-9477-4ee6-807c-7268d23b9daa or UUID=None
Matched PARTUUID=a4047323-9477-4ee6-807c-7268d23b9daa against a4047323-9477-4ee6-807c-7268d23b9daa
Formatting /dev/sda1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/sda1
Marking partition Partition(path=/dev/sda1, size=0.5, PARTUUID=a4047323-9477-4ee6-807c-7268d23b9daa, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sda, size=238.5GB, free_space=1031kB+335kB, bus_type=sata), 513MiB->100%
Adding partition using the following parted command: /dev/sda mkpart primary ext4 513MiB 100%
Retrieving partition PARTUUID=52766966-7510-48ac-81bc-35a7162043d4 or UUID=None
Matched PARTUUID=52766966-7510-48ac-81bc-35a7162043d4 against 52766966-7510-48ac-81bc-35a7162043d4
Encrypting Partition(path=/dev/sda2, size=238.0, PARTUUID=52766966-7510-48ac-81bc-35a7162043d4, fs=None) (This might take a while)
Hardware model detected: Dell Inc. Latitude E5270; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Memory statistics: 15052008 available out of 16273492 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '710.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '238.5G'}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202302', 'uuid': '2023-02-01-09-09-31-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.3G', 'children': [{'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'CA18-653E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '15M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Could not get block device information using blkid() using command blkid -p -o export /dev/sda
Could not get free space on /dev/sda: ['/usr/bin/parted', '-s', '--machine', '/dev/sda', 'print', 'free'] exited with abnormal exit code [256]: b'Error: /dev/sda: unrecognised disk label\r\nBYT;\r\n/dev/sda:256GB:scsi:512:512:unknown:ATA INTEL SSDSCKKF25:;\r\n'
Password strength: strong
Password strength: weak
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "grub-install",
    "config_version": "2.5.1",
    "debug": false,
    "desktop-environment": "kde",
    "gfx_driver": "All open-source (default)",
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "AName",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "de-latin1",
    "mirror-region": {},
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "nano"
    ],
    "parallel downloads": 0,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/desktop.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "Europe/Berlin",
    "version": "2.5.1"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": true,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=238.5GB, free_space=?, bus_type=sata), 1MiB->512MiB
Adding partition using the following parted command: /dev/sda mkpart primary fat32 1MiB 512MiB
Retrieving partition PARTUUID=ae1c6983-48b0-4da9-bd42-fad7309fe648 or UUID=None
Matched PARTUUID=ae1c6983-48b0-4da9-bd42-fad7309fe648 against ae1c6983-48b0-4da9-bd42-fad7309fe648
Formatting /dev/sda1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/sda1
Marking partition Partition(path=/dev/sda1, size=0.5, PARTUUID=ae1c6983-48b0-4da9-bd42-fad7309fe648, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sda, size=238.5GB, free_space=?, bus_type=sata), 513MiB->100%
Adding partition using the following parted command: /dev/sda mkpart primary ext4 513MiB 100%
Retrieving partition PARTUUID=1607365f-716f-4f54-8a57-d35a30ee01ab or UUID=None
Matched PARTUUID=1607365f-716f-4f54-8a57-d35a30ee01ab against 1607365f-716f-4f54-8a57-d35a30ee01ab
Encrypting Partition(path=/dev/sda2, size=238.0, PARTUUID=1607365f-716f-4f54-8a57-d35a30ee01ab, fs=None) (This might take a while)
Hardware model detected: Dell Inc. Latitude E5270; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Memory statistics: 15047296 available out of 16273492 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '710.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '238.5G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '0284-4AFC', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '511M'}, {'name': 'sda2', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '238G'}]}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202302', 'uuid': '2023-02-01-09-09-31-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.3G', 'children': [{'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'CA18-653E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '15M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Hardware model detected: Dell Inc. Latitude E5270; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
Memory statistics: 15053892 available out of 16273492 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [256]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '710.1M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '238.5G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '0284-4AFC', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '511M'}, {'name': 'sda2', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '238G'}]}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202302', 'uuid': '2023-02-01-09-09-31-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.3G', 'children': [{'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': 'CA18-653E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '15M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Setting font: LatGrkCyr-8x16
Password strength: weak
 -- Chosen configuration --
{
    "HSM": null,
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio": "pulseaudio",
    "bootloader": "grub-install",
    "config_version": "2.5.1",
    "debug": false,
    "desktop-environment": "kde",
    "gfx_driver": "All open-source (default)",
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "AName",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "de-latin1",
    "mirror-region": {},
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "nano"
    ],
    "parallel downloads": 0,
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/desktop.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": false,
    "sys-encoding": "UTF-8",
    "sys-language": "en_US",
    "timezone": "Europe/Berlin",
    "version": "2.5.1"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4",
                    "mount_options": []
                },
                "mountpoint": "/",
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=238.5GB, free_space=1031kB+1049kB+335kB, bus_type=sata), 1MiB->512MiB
Adding partition using the following parted command: /dev/sda mkpart primary fat32 1MiB 512MiB
Retrieving partition PARTUUID=0b6ae161-3b32-4b09-bb41-50b6dc086c85 or UUID=None
Matched PARTUUID=0b6ae161-3b32-4b09-bb41-50b6dc086c85 against 0b6ae161-3b32-4b09-bb41-50b6dc086c85
Formatting /dev/sda1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/sda1
Marking partition Partition(path=/dev/sda1, size=0.5, PARTUUID=0b6ae161-3b32-4b09-bb41-50b6dc086c85, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sda, size=238.5GB, free_space=1031kB+1049kB+335kB, bus_type=sata), 513MiB->100%
Adding partition using the following parted command: /dev/sda mkpart primary ext4 513MiB 100%
Retrieving partition PARTUUID=595aafe1-8d29-420d-9fb3-63b25cb3754d or UUID=None
Matched PARTUUID=595aafe1-8d29-420d-9fb3-63b25cb3754d against 595aafe1-8d29-420d-9fb3-63b25cb3754d
Formatting /dev/sda2 -> ext4
Mounting / to /mnt/archinstall/ using Partition(path=/dev/sda2, size=238.0, PARTUUID=595aafe1-8d29-420d-9fb3-63b25cb3754d, fs=ext4)
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/sda1, size=0.5, PARTUUID=0b6ae161-3b32-4b09-bb41-50b6dc086c85, fs=vfat)
Using mount order: [('/', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fb7b12d09d0>), ('/boot', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fb7b12d0a60>)]
Mounting Partition(path=/dev/sda2, size=238.0, PARTUUID=595aafe1-8d29-420d-9fb3-63b25cb3754d, fs=ext4) to /mnt/archinstall/
Getting mount information for device path /mnt/archinstall
Mounting Partition(path=/dev/sda1, size=0.5, PARTUUID=0b6ae161-3b32-4b09-bb41-50b6dc086c85, fs=vfat) to /mnt/archinstall/boot
Getting mount information for device path /mnt/archinstall/boot
Could not decode JSON: lsblk: /dev/sdb1: not a block device
{
   "blockdevices": [

   ]
}

Failed to read disk "/dev/sdb1" with lsblk
`

**Comment by bambirombi** [comment]
I also cannot install it. When rebooting nothing happens.

**Comment by jaybent** [comment]
Known issue: https://github.com/archlinux/archinstall/issues/1557

Work around(s): 
- Retry multiple times
- Manually format your drives
- Bunch of other different ways mentioned in the issue

**Comment by Torxed** [comment]
Closing as duplicate (Fix is a WIP)
