### ISSUE TITLE
Add support for Sway desktop environment

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#164]
This is a feature request to see the sway desktop environment added as an option.

**Comment by Torxed** [comment]
> This is a feature request to see the sway desktop environment added as an option.

Heard rumors that it's coming tomorrow to the feature branch `v2.2.0` :D

**Comment by dylanmtaylor** [comment]
> > This is a feature request to see the sway desktop environment added as an option.
> 
> Heard rumors that it's coming tomorrow to the feature branch `v2.2.0` :D

Is this code already in the branch? I don't see a profile for it, and wanted to test it out to see how it worked.

**Comment by Torxed** [comment]
> > > This is a feature request to see the sway desktop environment added as an option.
> > 
> > 
> > Heard rumors that it's coming tomorrow to the feature branch `v2.2.0` :D
> 
> Is this code already in the branch? I don't see a profile for it, and wanted to test it out to see how it worked.

I believe @advaithm was/is creating a PR but #190 and #192 needed to be implemented first for some post-installation hooks on profiles.

**Comment by advaithm** [comment]
Yeah I'm working on this. I'll also be splitting the gpu drivers from xorg

**Comment by advaithm** [comment]
@Torxed could you assign this issue to me

**Comment by Torxed** [comment]
> @Torxed could you assign this issue to me

It would be my pleasure!
