### ISSUE TITLE
Archinstall script kernel parameter messing with CPU frequency scaling

### ISSUE THREAD

**Issue by brenoferreiralima** [archlinux/archinstall#1640]
The script is setting the intel_pstate=no_hwp option generically for all installations including systems with amd processors or intel processors that support HWP.

This makes some features such as the "performance" mode of CPU frequency scaling unavailable for intel processors that support this feature, as well as not setting the amd_pstate driver for amd processors that support this feature.

All this causes performance and resource limitations on both platforms (intel/amd) on their latest processors.

**Comment by rffontenelle** [comment]
Already fixed in #1541, but would be nice to release it to avoid further impact.

**Comment by Torxed** [comment]
Closing as it's in for the next release. Waiting for #1557 before release tho.
