### ISSUE TITLE
Set /efi partition as default ESP mountpoint (separate /boot and /efi)

### ISSUE THREAD

**Issue by kojq** [archlinux/archinstall#1650]
Referencing https://wiki.archlinux.org/title/EFI_system_partition#Typical_mount_points:

> /efi is a replacement[[5]](https://github.com/systemd/systemd/pull/3757#issuecomment-234290236) for the historical and now discouraged ESP mountpoint /boot/efi.

Thus, could we consider `/efi` as the default `ESP` mountpoint? I know this was mentioned a few times, such as in /pull/1583. However, here is an issue dedicated to discussing separate partitions for `/boot` and `/efi`.

**Comment by Torxed** [comment]
100% agree with this, as mentioned in:
 * https://github.com/archlinux/archinstall/issues/645
 * https://github.com/archlinux/archinstall/issues/1072
 * https://github.com/archlinux/archinstall/issues/1189

I'll keep this issue open to track the other 3 as the title is a better description than the other ones.

**Comment by uhthomas** [comment]
@Torxed I'm confused, was this issue resolved? I don't believe `/efi` is the default mount point.
