### ISSUE TITLE
"Save configuration" Improve UX

### ISSUE THREAD

**Issue by bd-g** [archlinux/archinstall#1652]
*Feature Request*

I have some time in the next week, I may try and implement this depending on how many roadblocks I hit. Currently, to save a configuration, you are prompted to enter a directory. If it isn't valid, you have to scratch your head wondering what the exact paths are, because you can't discover any directory without exiting `archinstall`. 

It would be great if there was a sort of tab completion, or even filesystem traversal similar to `ncdu` to find a directory to save the configuration in.

**Comment by jaybent** [comment]
I'm not familiar with the TUI code and can't say if this would be complicated or not to implement. It would of course be a nice convenience, maybe it would make sense to create a default path. 

As a work-around you can switch to another TTY by pressing ALT+F2 and log in there to create / find a suitable path.
