### ISSUE TITLE
Add sound server selection (pipewire or pulseaudio)

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#166]
With pipewire being a viable alternative to pulseaudio, it would be useful to have a prompt to install pipewire instead, and pull in packages for compatibility like pipewire-media-session, pipewire-pulse, pipewire-alsa, pipewire-jack and gst-plugin-pipewire.

**Comment by Torxed** [comment]
I think this can be achieved with a application profile under [profiles/application/pipewire.py](https://github.com/archlinux/archinstall/tree/master/profiles/applications). And by matching on packages pull that app profile in automatically if `pipewire` is added as an additional package.

At least this is one concept I've been tinkering with to get multi-profile-installation-support without having to ask the user for which profile**s** they want installed. Would mean they could do:

```
Enter any additional packages to install: pipewire
```

And it would source the profile `profiles/applications/pipewire.py` and do the correct setup steps that's required outside of installing the package itself. Would this be desirable?

**Comment by dylanmtaylor** [comment]
> I think this can be achieved with a application profile under [profiles/application/pipewire.py](https://github.com/archlinux/archinstall/tree/master/profiles/applications). And by matching on packages pull that app profile in automatically if `pipewire` is added as an additional package.
> 
> At least this is one concept I've been tinkering with to get multi-profile-installation-support without having to ask the user for which profile**s** they want installed. Would mean they could do:
> 
> ```
> Enter any additional packages to install: pipewire
> ```
> 
> And it would source the profile `profiles/applications/pipewire.py` and do the correct setup steps that's required outside of installing the package itself. Would this be desirable?

Hmm, treating the sound server like an application seems like an odd choice. Perhaps better:

```
Select the desired sound server:
1. pipewire
2. pulseaudio
3. jack
4. alsa
```

**Comment by Torxed** [comment]
> > I think this can be achieved with a application profile under [profiles/application/pipewire.py](https://github.com/archlinux/archinstall/tree/master/profiles/applications). And by matching on packages pull that app profile in automatically if `pipewire` is added as an additional package.
> > At least this is one concept I've been tinkering with to get multi-profile-installation-support without having to ask the user for which profile**s** they want installed. Would mean they could do:
> > ```
> > Enter any additional packages to install: pipewire
> > ```
> > 
> > 
> > And it would source the profile `profiles/applications/pipewire.py` and do the correct setup steps that's required outside of installing the package itself. Would this be desirable?
> 
> Hmm, treating the sound server like an application seems like an odd choice. Perhaps better:
> 
> ```
> Select the desired sound server:
> 1. pipewire
> 2. pulseaudio
> 3. jack
> 4. alsa
> ```

The reason behind treating it as an application, is that in a sense it is an application (which we just happen to call a server), with specific configuration needs. But it would be more clear to the user that they're selecting a sound server by having a menu option for it.

This is just a guess, and I'm asking because I honestly have no clue, but is the sound server synonymous with a desktop/graphical environment? Or do "every day people" use it outside of a desktop environment?
I know I myself use it on Raspberry Pi's in a terminal capacity as a Sonos:TM: alternative, but I also know this isn't really the typical use case. If it is mainly used by desktop environments, maybe add it in wayland/xorg dependencies as a sub-menu?

I'm just throwing ideas out to see if we can minimize the user interaction in the main menu system, but I also hear that this might be illogical, in which case I'm open for suggestions. Maybe add support for multiple profiles, and add "audio" as a profile? :)

**Comment by dylanmtaylor** [comment]
> The reason behind treating it as an application, is that in a sense it is an application (which we just happen to call a server), with specific configuration needs. But it would be more clear to the user that they're selecting a sound server by having a menu option for it.
> 
> This is just a guess, and I'm asking because I honestly have no clue, but is the sound server synonymous with a desktop/graphical environment? Or do "every day people" use it outside of a desktop environment?
> I know I myself use it on Raspberry Pi's in a terminal capacity as a Sonos:TM: alternative, but I also know this isn't really the typical use case. If it is mainly used by desktop environments, maybe add it in wayland/xorg dependencies as a sub-menu?
> 
> I'm just throwing ideas out to see if we can minimize the user interaction in the main menu system, but I also hear that this might be illogical, in which case I'm open for suggestions. Maybe add support for multiple profiles, and add "audio" as a profile? :)

This is a large generalization, so forgive me if it's not entirely technically accurate, others may chime in and provide clarity, but I'm going to attempt to give this a go. From the user's point of view, the sound server is closer to a graphics driver than an application. It's a component on the system that is essentially *part* of the desktop environment, in that without one there will be no sound output/capture/routing unless applications call ALSA directly (extremely uncommon). There are 3 main sound servers that people use on Arch: pipewire -- including the pipewire-* packages (the newest and arguably most advanced one, but it's early in development - this has the pros of both pulseaudio and jack), pulseaudio (used very widely, basically default for all desktops except for Fedora which just switched to pipewire), and JACK (which is pretty much only used for professional audio use-cases, like audio production). I'm not super familiar with JACK, so I'll talk about pipewire and pulse a bit. These are not applications as much as system components and you can only have one installed at a time (pipewire-pulse needs to remove pulseaudio. There is a non-trivial amount of configuation from a new install to switch sound servers, like enabling and starting system services and sockets for instance. Pipewire provides the pipewire-x packages as a compatibility layer so that with pipewire you still can use applications coded to use existing sound servers. Pipewire has several advantages like being able to handle both video at once, so there is no latency between the video and audio content as it plays, and it is designed in a way to handle both pro and consumer use-cases. https://www.collabora.com/news-and-blog/blog/2020/03/05/pipewire-the-media-service-transforming-the-linux-multimedia-landscape

**Comment by Torxed** [comment]
> As far as using a sound server outside of a desktop environment, it's possible but uncommon. My suggestion would be to handle it in the same way as graphics drivers are currently selected, for all desktops.

Easily implemented, I'd say we'll go for this one for the time being.
As everyone can probably tell, I'm not the right guy for setting this up optimally :P I mainly do:
```
Any additional packages: pylseaudio
```
And then I'm satisfied ^^ But I can start on it if that helps :)

**Comment by dylanmtaylor** [comment]
> > As far as using a sound server outside of a desktop environment, it's possible but uncommon. My suggestion would be to handle it in the same way as graphics drivers are currently selected, for all desktops.
> 
> Easily implemented, I'd say we'll go for this one for the time being.
> As everyone can probably tell, I'm not the right guy for setting this up optimally :P I mainly do:
> 
> ```
> Any additional packages: pylseaudio
> ```
> 
> And then I'm satisfied ^^ But I can start on it if that helps :)

Awesome. So, for pipewire, this isn't just a package install, it's several:

* pipewire
* pipewire-alsa
* pipewire-pulse
* pipewire-jack
* pipewire-media-session
* gst-plugin-pipewire

This should have pulseaudio removed first, of course. Then, services need to be enabled for the user's session. I don't think this is default.

I belive the commands we will need are along the lines of

systemctl --user enable --now pipewire-pulse pipewire pipewire-media-session
systemctl --user enable --now pipewire.socket

There may be a better way to do this, maybe someone can chime in?

**Comment by dylanmtaylor** [comment]
To test the pipewire-pulse service after reboot, run 

pactl info | grep '^Server Name'

You should see this:

```
Server Name: PulseAudio (on PipeWire 0.3.24)
```

**Comment by dylanmtaylor** [comment]
Started working on this in #208

**Comment by grazzolini** [comment]
The purpose of the Arch installation is to get a minimal system going so the user can reboot into something that they can customize later. I think that, if the installer allowed the user to drop into the chroot to do whatever they wanted, it's a good compromise between the installer not having too many steps and keeping it user friendly and close to the installation guide. A sound server installation is part of the post installation steps on Arch.
