### ISSUE TITLE
Crash during partitioning

### ISSUE THREAD

**Issue by sambonbonne** [archlinux/archinstall#1664]
Hello,

Using `archiso 2023.03.01` with included archinstall (version `2.5.3`), it seems I have the same issue than #742: the disk can't be partitioned. I run the installation on Qemu with Packer.

Here is the file given to `--disk_layouts`:

```json
{
  "/dev/vda": {
    "partitions": [{
      "boot": true,
      "encrypted": false,
      "filesystem": {
        "format": "fat32"
      },
      "format": true,
      "mountpoint": "/boot",
      "size": "513MB",
      "start": "5MB",
      "type": "primary"
    }, {
      "encrypted": false,
        "filesystem": {
          "format": "ext4"
        },
        "format": true,
        "mountpoint": "/",
        "size": "4000MB",
        "start": "518MB",
        "type": "primary"
    }, {
      "encrypted": false,
        "filesystem": {
          "format": "ext4"
        },
        "format": true,
        "mountpoint": "/var",
        "size": "100%",
        "start": "4518MB",
        "type": "primary"
    }]
  }
}
```

And here is the logs:

```log
Testing connectivity to the Arch Linux mirrors ...
 ! Formatting [BlockDevice(/dev/vda, size=9.8GB, free_space=5242kB+5243kB+518MB, bus_type=None)] in 5....4....3....2....1....
Adding partition to BlockDevice(/dev/vda, size=9.8GB, free_space=5242kB+5243kB+518MB, bus_type=None), 5MB->513MB
Parted ended with a bad exit code: 256 (['/usr/bin/parted', '-s', '/dev/vda', 'mkpart', 'primary', 'fat32', '5MB', '513MB'] exited with abnormal exit code [256]: b'Error: You requested a partition from 5000kB to 513MB (sectors 9765..1001953).\r\nThe closest location we can manage is 5242kB to 5242kB (sectors 10239..10239).\r\n')
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
  File "/usr/lib/python3.10/site-packages/archinstall/__init__.py", line 307, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.10/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 319, in <module>
    perform_filesystem_operations()
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 126, in perform_filesystem_operations
    with archinstall.Filesystem(drive, mode) as fs:
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 46, in __exit__
    raise args[1]
  File "/usr/lib/python3.10/site-packages/archinstall/examples/guided.py", line 127, in perform_filesystem_operations
    fs.load_layout(archinstall.arguments['disk_layouts'][drive.path])
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 91, in load_layout
    partition['device_instance'] = self.add_partition(partition.get('type', 'primary'),
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 248, in add_partition
    if self.parted(parted_string):
  File "/usr/lib/python3.10/site-packages/archinstall/lib/disk/filesystem.py", line 201, in parted
    raise DiskError(f"Parted failed to add a partition: {parted_handle}")
archinstall.lib.exceptions.DiskError: Parted failed to add a partition: ['/usr/bin/parted', '-s', '/dev/vda', 'mkpart', 'primary', 'fat32', '5MB', '513MB'] exited with abnormal exit code [256]: b'Error: You requested a partition from 5000kB to 513MB (sectors 9765..1001953).\r\nThe closest location we can manage is 5242kB to 5242kB (sectors 10239..10239).\r\n'
```

If I can help with anything, feel free to ask!

**Comment by madper** [comment]
Does changing MB to MiB make it work?

**Comment by sambonbonne** [comment]
Just to be precise, I really just changed all `MB` to `MiB`, nothing else.

**Comment by Torxed** [comment]
It looks like a tricky disk to partition, as there's no one-clear-space to put partitions.
In your `--conf` options, do you have `{"disks": ["/dev/vda"]}` and you'll need to add `"wipe": true` to the `--disk-layout` in order to let archinstall wipe the disk (if this is what you want).
Because there's no free space to allocate any new partitions.

**Comment by sambonbonne** [comment]
It's on Qemu so maybe I should have some options?

Anyway, I already have `"harddrives": ["/dev/vda"]` and I tried adding `"disks": ["/dev/vda"]` with no success. Same with `"wipe": true"` on each partition in the disk layout file.

Could it be the disk inited by Packer in Qemu that can be "bad"?

**Comment by PadTrick** [comment]
Exact same behavior for me on Real Laptop. (1TB NVMe). Installer from February worked nice, installer from March was really slow in detecting/partitioning disks. April installer crashes instant after hitting Install(where he creates the partitions).

**Comment by Torxed** [comment]
Could you attach the installation log file as well? Because it looks like a disk-not-wiped issue, meaning the disk contained partitions and archinstall didn't clear it before or there's some virtualization issue I don't know about.

**Comment by PadTrick** [comment]
for me the installer crashs at summary, where i can read all the change the installer will do, if i press enter and the countdown starts.

**Comment by PadTrick** [comment]
no sorry, cant provide a log. already installed with februar iso. but i was thinking the same and cleaned the disk before i started the installer with a livecd.

**Comment by Torxed** [comment]
No worries, I'll keep an eye open for anyone with a log here but I suspect #1604 will solve this and will close this once that's introduced.

**Comment by sambonbonne** [comment]
@Torxed I'll wait for the potential fix from #1604 to test again with the release of Archiso which includes the rewrite (I'm not in a rush). I subscribed to the pull request in order to follow when it's merged (and I guess it'll be in the ISO released just after the merge).

**Comment by NodeAf176** [comment]
delete all disk partition and try again

**Comment by sambonbonne** [comment]
@NodeAf176 in my case, the disk is always already empty as I use Packer which creates a new virtual machine and a new disk each time I launch it

**Comment by svartkanin** [comment]
There were a lot of changes recently and this should be resolved in the most recent release
