### ISSUE TITLE
Partition Layout Table - Size & End confusion

### ISSUE THREAD

**Issue by StrangeGirlMurph** [archlinux/archinstall#1669]
# Overview

I think the partition layout table needs some attention. IMO there are some problems with the start and size columns that lead to confusion and there is an opportunity to improve the table with an end column that should be addressed. 

Lets consider the following case: I have a 500GB SSD with some Linux distro installed at the end of it and now want to use archinstall to install Arch on the first half of the drive to have a dual boot system.

**fdisk -l /dev/nvme0n1**
```txt
Device             Start       End   Sectors   Size Type
/dev/nvme0n1p1        64    202814    202751    99M EFI System
/dev/nvme0n1p2 390625280 976773119 586147840 279,5G Linux filesystem
```

**The partition layout table in archinstall**
```txt
   type  |               PARTUUID               |  wipe |  boot |  ESP  | mountpoint | encrypted |   start   |    size   | format
-----------------------------------------------------------------------------------------------------------------------------------
 primary | 8e1adfee-373e-443a-a0b8-35c92ef771b3 | False |  True |  True |    None    |   False   |     64    |   202751  |  vfat
 primary | b3d90b80-9542-4d8b-919a-11b96733d365 | False | False | False |    None    |   False   | 390625280 | 586147840 |  ext4
```

# Problems
## 1. end column
The easiest and most precise way of creating a new partition is to use the start and end sectors of the partition by using the end and start sectors of the surrounding partitions. To create the root partition in archinstall with the fdisk output I would just enter `202815s` for the start sector prompt and `390625279s` for the end sector prompt to fill all the available space. (Note: the sector unit is currently being added in [this](https://github.com/archlinux/archinstall/pull/1668) pr) With the current partition layout table in archinstall I would have to calculate the starting sector for the partition from the start of the previous partition and its size myself which is a bit tedious and will probably require a calculator (`64 + 202751 => 2020815s` and `390625279s`). A column for the end sector of each partition would make this easier. It would also allow the size column to have a different and more human friendly unit like GB and MB which would help identifying partitions more easily. Lastly it would also fix my [third point](#3.%20end%20sector%20in%20size%20column).

## 2. Unit specifiers
I think the start and size column could benefit from an unit specifiers.

## 3. end sector in the size column
When creating a new partition with archinstall the end sector in whatever unit the user entered it will be shown in the size column which is very confusing. 

```txt
   type  |               PARTUUID               |  wipe |  boot |  ESP  | mountpoint | encrypted |   start   |    size    | format
------------------------------------------------------------------------------------------------------------------------------------
 primary | 8e1adfee-373e-443a-a0b8-35c92ef771b3 | False |  True |  True |    None    |   False   |     64    |   202751   |  vfat
 primary | b3d90b80-9542-4d8b-919a-11b96733d365 | False | False | False |    None    |   False   | 390625280 |  586147840 |  ext4
 primary |                                      |  True |       |       |    None    |           |  202815s  | 390625279s |  ext4
```

This example clarifies a lot that it makes no sense:

```txt
   type  |               PARTUUID               |  wipe |  boot |  ESP  | mountpoint | encrypted |   start   |    size    | format
------------------------------------------------------------------------------------------------------------------------------------
 primary | 8e1adfee-373e-443a-a0b8-35c92ef771b3 | False |  True |  True |    None    |   False   |     64    |   202751   |  vfat
 primary | b3d90b80-9542-4d8b-919a-11b96733d365 | False | False | False |    None    |   False   | 390625280 |  586147840 |  ext4
 primary |                                      |  True |       |       |    None    |           |  202815s  |    100%    |  ext4
```

# Proposal
```txt
   type  |               PARTUUID               |  wipe |  boot |  ESP  | mountpoint | encrypted | start sector | end sector |  size  | format
------------------------------------------------------------------------------------------------------------------------------------------------
 primary | 8e1adfee-373e-443a-a0b8-35c92ef771b3 | False |  True |  True |    None    |   False   |      64      |   202814   |   99M  |  vfat
 primary | b3d90b80-9542-4d8b-919a-11b96733d365 | False | False | False |    None    |   False   |   390625280  |  976773119 | 279,5G |  ext4
 primary |                                      |  True |       |       |    None    |           |    202815    |  390625279 | 186,2G |  ext4
```

I would love the partition layout table to be like this. There is a separate end sector column and the partition size has human readable units just like fdisk outputs them. Plus behind the scenes the user input for the start and end of a new partition will be converted to sectors and its size will be calculated.

# Future
I would actually consider fixing this myself if @Torxed supports the proposal.

**Comment by svartkanin** [comment]
There's a big change in the whole partitioning display and management coming soon (TM) and this will be fixed there

**Comment by StrangeGirlMurph** [comment]
Oh that's great! Although from what it looks like sadly there won't be an end column and the start unit will be MiB. Are you making sure that creating a new partition from 20481 to 33000 for example will directly follow the previous one with a starting sector one above the previous end sector or are gaps possible?

![](https://user-images.githubusercontent.com/19396770/208875550-43447af2-1922-4109-aa67-87a24af5f0ae.png)

**Comment by svartkanin** [comment]
It's not fully finalised yet, but the new code introduces a Unit object that allows to convert easily between Sizes
 https://github.com/archlinux/archinstall/pull/1604/files?file-filters%5B%5D=.cfg&file-filters%5B%5D=.json&file-filters%5B%5D=.md&file-filters%5B%5D=.py&file-filters%5B%5D=.toml&file-filters%5B%5D=.yaml&file-filters%5B%5D=No+extension&file-filters%5B%5D=dotfile&show-deleted-files=true&show-viewed-files=true#diff-49d9b36869efacf15eb51c938c50c302010c7c50b4b0032051479a69ce4d8c3eR62


The idea is that, when specifying a manual partition layout the user will be able to choose the unit and then enter the size respectively. This will probably not be included in this major PR as I really wanna get it over the finish line:) but definitely in a follow up.

Regarding the display, yes it's very simple to add the end as well, only concern is that the table will get fairly wide and cut off in small ttys especially on the iso in a virtual machine...

**Comment by StrangeGirlMurph** [comment]
Okay, thanks. The Unit object sounds wonderful!
With the Part UUID column gone it might fit :>

**Comment by svartkanin** [comment]
I have raised a PR that will use the proposed table schema

**Comment by StrangeGirlMurph** [comment]
Thank you so much @svartkanin! C:
