### ISSUE TITLE
deal with booster

### ISSUE THREAD

**Issue by madper** [archlinux/archinstall#1671]
Howdy,

With testing repo enabled, the installation will failed due to mkinitcpio is not installed by default.
```
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'xfsprogs', 'xfsprogs', 'amd-ucode']
Enabling periodic TRIM
Enabling service fstrim.timer
['/usr/bin/arch-chroot', '/mnt/archinstall', 'mkinitcpio', '-P'] exited with abnormal exit code [32512]: b"chroot: failed to run command 'mkinitcpio': No such file or directory\r\n"

```
It seems the default initramfs generator changed to booster right now:
```
==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall
:: Synchronizing package databases...
 testing                50.2 KiB   207 KiB/s 00:00 [######################] 100%
 core                  156.1 KiB  2.67 MiB/s 00:00 [######################] 100%
 extra                1745.6 KiB  3.12 MiB/s 00:01 [######################] 100%
 community               7.3 MiB  2.93 MiB/s 00:02 [######################] 100%
resolving dependencies...
:: There are 4 providers available for initramfs:
:: Repository testing
   1) booster
:: Repository core
   2) mkinitcpio
:: Repository extra
   3) booster  4) dracut

Enter a number (default=1):
looking for conflicting packages...
```
Thus mkinitcpio will not installed by default.

An workaround is force install mkinitcpio.  (Or, disable testing repo. However it will move to stable I guess.)

**Comment by Torxed** [comment]
This feels strange, as it's a dependency of `linux` which does get installed: https://archlinux.org/packages/core/any/mkinitcpio/

And there's no testing version that I can see.

**Comment by madper** [comment]
It seems when booster existed in testing repo it takes the first of enumeration order. 
Not sure if it worth a fix as most people won't enable testing repo during installation.
