### ISSUE TITLE
Cannot update archlinux-keyring

### ISSUE THREAD

**Issue by mbledkowski** [archlinux/archinstall#1688]
Hi,
When I try to install ArchLinux in VM using archinstall command, I get the following error:
![image](https://user-images.githubusercontent.com/23295125/227047198-e33ed6cc-a3e4-49e3-8ff9-505f306a5b2b.png)
I tried to repair it using the commands found online, but nothing seems to work.
Arch Linux iso: archlinux-2023.03.01-x86_64.iso

**Comment by Torxed** [comment]
ouff this bloody keyring.. I wonder if it's safe to completely remove the update procedure of the `archlinux-keyring` package and just rely on the keyring update service and nothing else. If so we can just patch those troublesome lines out: https://github.com/archlinux/archinstall/blob/79eb6bba627c4c70f24a265ac0b2ef9cbfbbd211/examples/guided.py#L290-L302

Can you try running `archinstall --skip-keyring-update`?

**Comment by mbledkowski** [comment]
> ouff this bloody keyring.. I wonder if it's safe to completely remove the update procedure of the `archlinux-keyring` package and just rely on the keyring update service and nothing else. If so we can just patch those troublesome lines out:
> 
> https://github.com/archlinux/archinstall/blob/79eb6bba627c4c70f24a265ac0b2ef9cbfbbd211/examples/guided.py#L290-L302
> 
> Can you try running `archinstall --skip-keyring-update`?

Today I recreated the VM using the same image, and did not get this error. No idea how, but it fixed itself overnight

**Comment by Torxed** [comment]
> Not working from here. Same issue.

Did my "fix" solve it?

**Comment by Pro-Prietary** [comment]
> Can you try running `archinstall --skip-keyring-update`?
I have the same issue on a Dell Inspiron 15, the flag fixed this issue for me. It looks like it was trying to update the keyring, but I apparently didn't have enough space.

**Comment by Torxed** [comment]
> > Can you try running `archinstall --skip-keyring-update`?
> 
> I have the same issue on a Dell Inspiron 15, the flag fixed this issue for me. It looks like it was trying to update the keyring, but I apparently didn't have enough space.

Good, thank you for testing. That was my suspicion as well. I'll patch those lines and push a release later tonight/tomorrow.

**Comment by Torxed** [comment]
Should be fixed in `master` :) Thanks for the report!
