### ISSUE TITLE
Support `--version=X.Y.Z` flag for grabing a specific version

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#169]
After some discussion back and fourth with @phisch, having the support to tell archinstall which version to run on would eliminate some issues with breaking changes and the release cycle of archiso. And it would make archinstall more dynamic on its own.

Something like:
```
# python -m archinstall --version=2.2.0
```
Would be nice, that way users can choose to use the latest, or maintainers could choose to stick to an older version while waiting for the breaking changes to be tested properly.

This would require some meta functions to be re-introduced in to the library section, not the guided installer.
Where it would rely on (in preferred order):
 * pacman - If older verions can be found
 * Git - to clone from upstream repository and sync contents directly
 * pip - If present, could be used to fetch from upstream python repository
 * Python's `requests` module to grab the tarball of the desired release from upstream

This would be out of ordinary operations, and I just want to be clear that it will be outside of guided (which is the shipped installer with Arch Iso). It would cause potential issues with `pacman`'s installed version, but if done in a ISO users should be one reboot away from normal operation again.

**Comment by kpcyrd** [comment]
I'm not sure if this can be implemented in a reasonable way. I assume the need for "the installer needs to update more than once a month" is more of an indicator that the project is very new, this is going to be less of a problem eventually.

Instead I'd suggest you try to use github actions to build daily isos with the latest version of archinstall for testing.

**Comment by Torxed** [comment]
That can work. This is more of a need for the library part - and not so much for the guided installer that ships with Arch Linux ISO. But fair points!

**Comment by grazzolini** [comment]
I'm also not a fan of loading code at run time. I mean, we try to avoid broken stuff on the ISO, but occasionally they do happen. This is one of the reasons we keep the 3 latest ISO's on the mirrors.

**Comment by Torxed** [comment]
I'll park this idea for now :) There's also test instructions on how to test the latest code in the README/Github wiki for those that want to do this. Which lowers the amount of code I have to write.
