### ISSUE TITLE
libkeybinder3 isn't installed by default

### ISSUE THREAD

**Issue by knoppmyth** [archlinux/archinstall#1701]
Installed with version 2.5.4 and choose kde as my desktop. Installation worked without issue. However when I tried to use <shift><del> to delete some files, it didn't work. After I manually installed libkeybinder3, logged out and back in, the shortcut works.

**Comment by knoppmyth** [comment]
In thinking about this further, I believe the issue is with the plasma-desktop package. libkeybinder3 should be a dependency. I've reported this against the plasma-desktop package.

**Comment by Torxed** [comment]
Great job and thank you for reporting it upstream!
