### ISSUE TITLE
cryptdevice and root have same PARTUUID -> unable to boot

### ISSUE THREAD

**Issue by legymhueck** [archlinux/archinstall#1716]
Version: archinstall 2.5.4 (official 2023-04 ISO) and 2.5.5 (cloned)

Issue: encrypted root partition (btrfs) does not boot due to /boot/loader/entries .conf having the same UUID for cryptdevice and root

Fix: changing the root uuid to the encrypted partition (or just using /dev/mapper/luksdev) fixed the issue

**Comment by Torxed** [comment]
Can you post before and after changes?
Because I don't think I've ever seen this happen when I'm installing.

**Comment by mewejo** [comment]
This happened to me yesterday - dropped me into `initramfs` with `rootfs #` prompt.

Ended up being two `options` lines in the boot entry, one for an encrypted partition and one for not. Removed the 2nd (for non-encrypted) and it worked. This was BTRFS and on the `2023.04.01` ISO.

**Comment by codefiles** [comment]
This is caused by a portion of code that was duplicated in 5669f3b. I submitted a pull request that fixes the issue.

**Comment by Torxed** [comment]
> Yep, as @mewejo pointed out, there are 2 `options` lines. In the first, the root is correctly set, the second overwrtites the values and causes booting into `emergency shell`.
> 
> ```
> options cryptdevice=PARTUUID=a34c8618-c601-4c3a-bfdf-d6d983a17723:luksdev root=/dev/mapper/luksdev zswap.enabled=0 rw rootfstype=btrfs 
> options root=PARTUUID=a34c8618-c601-4c3a-bfdf-d6d983a17723 zswap.enabled=0 rw rootfstype=btrfs
> ```
> 
> A question in general: Why doesn't the installer use labels (as in nixos) to be able to clone a system easily without the hassle of changing UUIDs?

Thank you for the details, and a huge thanks to @codefiles for submitting a fix.
I'll most likely submit a new patch release if #1604 testing takes longer than 20:th of this month.
