### ISSUE TITLE
error: failed to commit transaction

### ISSUE THREAD

**Issue by DiamondBond** [archlinux/archinstall#172]
error: https://0x0.st/-cAb.jpg

profile: https://0x0.st/-cAc.jpg

**Comment by Torxed** [comment]
This feels like you ran out of disk space, but run a `df -h` to confirm when the error occurs.
*(this makes sure that the disk is correctly mounted before running `df -h`, but you can run it after manually mounting too)*

**Comment by DiamondBond** [comment]
yep, looks like you're right, blk_update_request: i/o error, multiple SQUASHFS errors followed by zsh: input/output error: df.
strange though, the drive i was installing to had 120g free and the pendrive i was installing from was 64g.

**Comment by Torxed** [comment]
Closing this as it's most likely related to a hardware issue.
But the new release [v2.1.4](https://github.com/archlinux/archinstall/releases/tag/v2.1.4) *(released yesterday)* should also have some improvements in detecting and erroring out if this happens.

Hopefully this patch release addresses this issue, if it still doesn't work - don't hesitate to poke me and I'll re-open this!
