### ISSUE TITLE
Broken Cyrillic fonts in Archlinux 2023.4 

### ISSUE THREAD

**Issue by K1LL3RPUNCH** [archlinux/archinstall#1724]
![IMG_20230404_002638](https://user-images.githubusercontent.com/82245216/229731534-726266e3-6703-4a66-acc4-b48c5d2484d9.jpg)

**Comment by Torxed** [comment]
It's not broken, but you'll need a font that supports it first.
Those fonts are not included in the vanilla arch ISO IIRC.
