### ISSUE TITLE
Replace the disk management counterpart with fdisk

### ISSUE THREAD

**Issue by ognirrrats** [archlinux/archinstall#1725]
While the full disk wipe leading to arch install works fine, the dualboot option is unnecerary hard, since the programme's initial look is bloody awful. Fdisk is a much better tool and i feel like it should replace the current one. I hope I've used the correct terminology, as I don't tend to remember the names of tools used in the instalation.

**Comment by Torxed** [comment]
Closing this as I don't find it too relevant.
We've got a big change upcoming in #1604, and you are always welcome to partition the disk in whatever tool you think look pretty and does the job - and tell `archinstall` to use that setup. That way archinstall won't do any disk operations :)

**Comment by ognirrrats** [comment]
Sorry I am not very familiar with archinstall so there's that

**Comment by Torxed** [comment]
> Sorry I am not very familiar with archinstall so there's that

That's ok. If you partition your disk with any tool (like fdisk or cfdisk) and mount your setup to `/mnt/archinstall` then in the menu step "Select disks" you press `Ctrl+C` - `archinstall` will use your mounted layout and setup as-is without touching anything disk related :)
