### ISSUE TITLE
Adding option for hyprland wm in installer

### ISSUE THREAD

**Issue by Pyntux** [archlinux/archinstall#1727]
This is just a suggestion.

It would be nice to add option for hyprland wm in to installer, because hyprland just  got in to community repo.

Thank you for your efforts so far! :)

https://archlinux.org/packages/?name=hyprland

**Comment by Torxed** [comment]
I don't see why not, PR is welcome

**Comment by Torxed** [comment]
Implemented!

**Comment by Pyntux** [comment]
Great! Thank you!
