### ISSUE TITLE
Unable to mount encrypted root partition after installation

### ISSUE THREAD

**Issue by lukaswrz** [archlinux/archinstall#1731]
I'm trying to install Arch with an encrypted Btrfs root partition. Here's a screenshot of what happens after rebooting:

![Error](https://share.2gbcss.net/-aJGCgzxS8s/error.png)

In the emergency shell, i can mount `/dev/mapper/luksdev` just fine. I'm not sure why it's trying to mount the encrypted partition directly though (the PARTUUID in the screenshot refers to the encrypted partition).

I tried the ISOs from the 1st of March and the 1st of April, so both of them have this issue.

Here's the log file: [install.log](https://share.2gbcss.net/-b9kmkGQtQQ/install.log).

**Comment by kuanhulio** [comment]
Question: are you using `systemd-bootctl`?

In my loader entry, I noticed these two lines:

```
# Created by: archinstall
# Created on: 2023-04-07_15-30-21
title Arch Linux (linux-hardened)
linux /vmlinuz-linux-hardened
initrd /initramfs-linux-hardened.img
options cryptdevice=PARTUUID=a4a7c7b6-e8f9-4620-9cd7-3dec5bb3edb9:luksdev root=/dev/mapper/luksdev zswap.enabled=0 rw rootfstype=ext4
options root=PARTUUID=a4a7c7b6-e8f9-4620-9cd7-3dec5bb3edb9 zswap.enabled=0 rw rootfstype=ext4
```

**Comment by Torxed** [comment]
Probably fixed in https://github.com/archlinux/archinstall/pull/1721

**Comment by kuanhulio** [comment]
> Probably fixed in #1721

When trying to build `archinstall` from the Testing > ISO Image instructions, `setup.py` doesn't exist.

```bash
root@archiso ~/archinstall (git)-[master] # python setup.py install
python: can't open file '/root/archinstall/setup.py': [Errno 2] No such file or directory
```

**Comment by Torxed** [comment]
> > Probably fixed in #1721
> 
> When trying to build `archinstall` from the Testing > ISO Image instructions, `setup.py` doesn't exist.
> 
> ```shell
> root@archiso ~/archinstall (git)-[master] # python setup.py install
> python: can't open file '/root/archinstall/setup.py': [Errno 2] No such file or directory
> ```

Just a few commits ago we changed to `pyproject.toml` instead of the legacy `setup.py`.
Try `python -m build && python -m installer dist/*.whl`

**Comment by kuanhulio** [comment]
> > > Probably fixed in #1721
> > 
> > 
> > When trying to build `archinstall` from the Testing > ISO Image instructions, `setup.py` doesn't exist.
> > ```shell
> > root@archiso ~/archinstall (git)-[master] # python setup.py install
> > python: can't open file '/root/archinstall/setup.py': [Errno 2] No such file or directory
> > ```
> 
> Just a few commits ago we changed to `pyproject.toml` instead of the legacy `setup.py`. Try `python -m build && python -m installer dist/*.whl`
> 
> Or use the pre-built ISO with every commit: https://github.com/archlinux/archinstall/actions/runs/4605279177

Cool beans, thank you!

**Comment by kuanhulio** [comment]
Can confirm: the patch works and is bootable. There is only one entry in the bootloader.

**Comment by lukaswrz** [comment]
Thanks, the ISO linked above works, so I'll close this.

**Comment by Torxed** [comment]
Thank you for testing!
