### ISSUE TITLE
Error when installing i3

### ISSUE THREAD

**Issue by ffranciscofferraz** [archlinux/archinstall#1732]
I get an error and based on the logged, it is trying to install i3 packages but one part of the script is like this 'i3wmi3locks' while the other commands like 'i3status' and 'base-devel' are each one in it's own ' '.
The version I'm using is 2.5.5.

**Comment by beate-user** [comment]
moin!
as a hacky quick fix, you can edit /usr/lib/python/site-pack/archinst/prof/i3.py
in the first few lines of this script you can see
`
'i3-wm'
'i3lock',
...
`

there is a comma after "i3wm" missing.
add the missing comma and have fun!  ;-)
