### ISSUE TITLE
April 2023 iso archinstall script requires encryption else wont install

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#1733]
as the title says. if no encryption password added, script will fail. Basically forcing users to add encryption. What if users dont want encryption?

**Comment by p-otato2** [comment]
I think the solve to this is update the arch installer by 

pacman -Sy archinstall

**Comment by SimonASK8317** [comment]
Hi,

yes, this is a dublication of Issue #1704 which was fixed with pull requests #1705, it is part of version [2.5.5](https://github.com/archlinux/archinstall/releases/tag/v2.5.5).
