### ISSUE TITLE
Encryption partition not loaded from config (>= 2.5.4)

### ISSUE THREAD

**Issue by SimonASK8317** [archlinux/archinstall#1734]
Hi everybody,

when I tried to re-install Arch with saved configs from 2.5.1, I noticed that my configured disk encryption was not applied (everything else was fine).

Digging a little deeper I noticed that apparently, since 2.5.4, the disk encryptions settings are not loaded from the configuration files.

How to reproduced:

1. Boot the April 2023 install ISO (e.g. with VirtualBox)
2. Start `archinstall`
3. Select /dev/sda as the installation drive
4. In the disk layout, select the default BTRFS settings
5. In the disk encryption, set the entryption password and select the previously configured BTRFS partition
6. Set a root password
7. Save all configs (e.g. to /tmp) and copy them to a save place.
8. Install, then reboot. You will be asked for the decryption password, so far so good.
9. Boot the installation ISO again
10. Copy the configuration files you previously saved back to /tmp.
11. Start archinstall `archinstall --config /tmp/user_configuration.json --disk_layout /tmp/user_disk_layout.json --creds /tmp/user_credentials.json`
12. You will notice now, that in the section for Disk encryption, the "Partitions: 1 selected" part is missing
14. If you hit install without further changes OR if you start archinstall with the config files in non-interactive mode (`archinstall --config /tmp/user_configuration.json --disk_layout /tmp/user_disk_layout.json --creds /tmp/user_credentials.json --silent`), if you reboot after the installation finishes, you will not be asked for a decryption password since the disk was not encrypted. During the installation you can also see that there is no "encrypting disk" part.

Disk encryption screen after partition is manually selected:

![encryption_selected_partition](https://user-images.githubusercontent.com/68168003/230744378-914cb047-5f3c-452a-b5f2-0fe55b8b682f.png)

Disk encryption screen when archinstall is started with previously saved configuration files where the partition was selected:

![encryption_missing_partition](https://user-images.githubusercontent.com/68168003/230744379-98a73cb4-2de7-4c9d-a6ed-8f1b194d7f63.png)

I was able to reproduce this behavior in version 2.5.4 which is shipped with the April 2023 installation ISO as well as the version 2.5.5 after updating it via pacman `pacman -Sy archinstall`.

I also noticed that when starting the installation in the error case, archinstall displays the disk_encryption.partitions dict as an empty object. Could be related to the changed made regarding the disk encryption declarations in 2.5.4 (#1672 ), am not that good in Python though to confirm this.

Another interesting thing is that after starting point 14, in the output displayed on the screen before the installation starts, the key "encryption_password" is part of the JSON with the encryption password in clear text as it's value, this is usually written to the user_credentials.json and not user_configuration.json. The output after point 8 did not contain this key.

The workaround for this is to manually select the partition to encrypt after loading the configs, this does not work for non-interactive mode though meaning that automated installations of encrypted disks is currently not possible.

I attach all my config files, don't worry, all passwords are just dummy values from my test VM I created to re-produce this issue, no real-world data was used.

[configs.zip](https://github.com/archlinux/archinstall/files/11184340/configs.zip)

Thank you for your help and the good work 🙂.

**Comment by mtompkins** [comment]
Confirming this issue persists in v2.5.6

**Comment by svartkanin** [comment]
This should be fixed already in master.
You can run `pacman -Sy archinstall`

**Comment by mtompkins** [comment]
> This should be fixed already in master. You can run `pacman -Sy archinstall`

Thank you - I'm not running *-git as we are bootstrapping from TFTP/PXE.
Presume this means it will work its way through Extra/testing in short order.

**Comment by rbroggi** [comment]
I don't think this is actually corrected. Regardless of my selection of partitions to be encrypted the disk layout configuration always display `"encrypted": false` any ideas?

**Comment by Torxed** [comment]
> I don't think this is actually corrected. Regardless of my selection of partitions to be encrypted the disk layout configuration always display `"encrypted": false` any ideas?

If the issue still exist we'll fix it before the release of 2.6.0 which is the next in the release order

**Comment by rbroggi** [comment]
any easy workarounds? I would love avoiding going through the manual installation.

**Comment by Torxed** [comment]
> any easy workarounds? I would love avoiding going through the manual installation.

Just to confirm, were you using the git codebase or the official app on the ISO?

**Comment by rbroggi** [comment]
I tried using the `master` tip but `pip` install failed

**Comment by svartkanin** [comment]
Master has a lot of changes that the latest release doesn't have including encryption. Therefore I would suggest to try test it on master or wait for the new release. 

What was the issue with `pip install .`?

**Comment by Torxed** [comment]
I suspect the `--break-operating-system` was required.

As it is a new thing

**Comment by svartkanin** [comment]
Yeah that'd make sense

**Comment by rbroggi** [comment]
interesting, maybe worth enhancing the readme?

**Comment by Torxed** [comment]
> interesting, maybe worth enhancing the readme?
> 
> #1897

Absolutely! Thank you for the contribution.

**Comment by jarkkojs** [comment]
So I downloaded the latest ISO and experienced the exact same problem. Is this expected?

**Comment by svartkanin** [comment]
This should be fixed
