### ISSUE TITLE
Nothing works..seriously a fine proof...

### ISSUE THREAD

**Issue by 6422amri** [archlinux/archinstall#1737]
I have..what..more than 40 years of computing experience and 20 years of Linux..let's try arch...and archintsall..

NOTHING works...

Unresponsive keyboard when I try to enter password for root and the first userid....Was working for the for the first userid AFTER  I set up encrypted disk..I was NEVER prompted after to enter a password for the disk...mystery....
After many attempt I finally got a wonderful system..some sort of... without network..without network manager..only lo interface..very practical...

I am going to stick with Zorin and Windows 11....a lot of noise....

**Comment by Torxed** [comment]
I'm sorry but this bug report is nothing but noise and a personal rant.
I appreciate the need to get frustration out, but maybe not on a public issue tracker next time?

**Comment by 6422amri** [comment]
It is NOT...plain and simple. It doesn't work. For me Linux is a tool and nothing else.

**Comment by Torxed** [comment]
Sure, but after 40 years of computer experience I'd expect more from a bug report.
Installation log? Traceback? Hardware specs? Versions used? Keyboard layout?

None of that is present so I'll keep this closed until it's posted. That is if you actually want help making the tool — a tool.
