### ISSUE TITLE
I3 in archinstall error

### ISSUE THREAD

**Issue by CarleAlexandre** [archlinux/archinstall#1739]
between i3-wm and i3-lock a space is missing causing it to be read as a single package in the installation script

**Comment by CarleAlexandre** [comment]
corrected last week but not in the actual arch iso

**Comment by Torxed** [comment]
I'm waiting for v2.5.6 to be packaged, but it's been released. After that a `pacman -Sy archinstall` should work despite the hotfix being quite easy to make yourself (it's a missing comma) :)
