### ISSUE TITLE
A possible miswording in README

### ISSUE THREAD

**Issue by blochl** [archlinux/archinstall#174]
Regarding the following line:

https://github.com/archlinux/archinstall/blob/2c73989da4fc19de86e273f9fdda9840b312dff5/README.md#L65

Shouldn't it be: `s/network-profile/window manager/`?

**Comment by Torxed** [comment]
> Regarding the following line:
> 
> https://github.com/archlinux/archinstall/blob/2c73989da4fc19de86e273f9fdda9840b312dff5/README.md#L65
> 
> Shouldn't it be: `s/network-profile/window manager/`?

Correct, the original wording is a bit technical.
In the background, it does source the profile from the network and installs it - hence "network profile". But more accurately it is a window manager, so that should be changed! :)

**Comment by blochl** [comment]
Thanks!
