### ISSUE TITLE
Install not working because no encryption password

### ISSUE THREAD

**Issue by michaeleldar** [archlinux/archinstall#1740]
When I try to install arch linux 2023.04.01, and I leave the encryption password blank I get this error when I select install after completing all the settings:
<img width="938" alt="image" src="https://user-images.githubusercontent.com/66514999/231195838-65d072a5-7008-4031-b45a-1402c85a2cb7.png">
I've tried going into the encryption password setting and leaving it blank, as well as just skipping over it. I haven't tried installing with an encryption password.

**Comment by Torxed** [comment]
You're using an outdated arch version (even tho you use the latest Arch ISO (long story)).
Do `pacman -Sy archinstall` and you should be good to go.
