### ISSUE TITLE
Can't install without encrypting with a password - 'NoneType' object has no attribute 'encryption_password'

### ISSUE THREAD

**Issue by Araraura** [archlinux/archinstall#1741]
Hey, I'm trying to use archinstall in a VM on the April 2023 ISO, but after filling everything up and choosing 'Install' I get this error:

![image](https://user-images.githubusercontent.com/25017422/232079942-e4e17b66-bd38-473d-ad0d-a632052f0879.png)

I did not encrypt my drive by using a password, but when I ran the script again and I did choose to encrypt with a password, it did install.

**Comment by epicbattle1** [comment]
the version used in the iso is outdated, type pacman -Sy and then pacman -S archinstall to update it

**Comment by Torxed** [comment]
Solution above is correct, unfortunately the ISO's only update once a month so you have to do a manual upgrade of archinstall in the ISO: `pacman -Sy archinstall` should work too :)
