### ISSUE TITLE
Bug with `cryptsetup` retries

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1743]
There is a logic error in the `luks2.encrypt()` function where the `DISK_RETRY_ATTEMPTS` do not occur if the first `SysCommand()` call for `cryptsetup` fails. A non-zero exit code will raise a `SysCallError`, which will be caught by the exception, leaving the retry loop.

https://github.com/archlinux/archinstall/blob/5689d4f59f4f08465d2ef72412f5819e9df87430/archinstall/lib/luks.py#L105-L117

I have an open pull request (#1707) that includes a fix for the logic error as I saw it related to issue #1702 (should still be open). @Torxed, would you prefer it as a separate pull request?

**Comment by Torxed** [comment]
I'm ok with bulking up the change in one PR, so if you want to modify that PR before I merge it that is fine! :)
