### ISSUE TITLE
Error when no encryption

### ISSUE THREAD

**Issue by CarleAlexandre** [archlinux/archinstall#1746]
AttributeError: 'NoneType' oject has no attribute 'encryption_password' when using ext4, no disk encryption password was entered has i don't want to, also using linux hardened kernel and server profil
![Capture](https://user-images.githubusercontent.com/122493613/232299384-d040f17f-055d-45ea-91a2-16e33dcb3d4a.PNG)

**Comment by nyuware** [comment]
The issue has been fixed in the newest release, run pacman -Sy archinstall to update

**Comment by CocoXiaoLong** [comment]
When you can't update (to little storage for example), set a password and select that no partition should be encrypted.
He then has a password, using it for nothing.

**Comment by CarleAlexandre** [comment]
Ok thanks
