### ISSUE TITLE
The parallel downloads page is shown half in English, half in another language if a language other than English is selected

### ISSUE THREAD

**Issue by acuteenvy** [archlinux/archinstall#1749]
I checked every language that has this page translated and it happens on every single one.
### Example:
![French-example](https://user-images.githubusercontent.com/126529524/232617481-5f4f06ac-7359-4f61-96f2-6e7cdbeda770.png)

### Another one:
![Russian-example](https://user-images.githubusercontent.com/126529524/232617561-9463fc23-3223-4814-af8c-586dc1638ab3.png)

**Comment by svartkanin** [comment]
Did you change the archinstall language at all?

**Comment by acuteenvy** [comment]
I did. As I said, no matter which language I choose, parts of the page are still displayed in English.

**Comment by svartkanin** [comment]
@acuteenvy sorry for the late reply, yes it is to expect that some text may still be in English. As you can see when selecting the language there is a percentage next to each language which indicates how much of the language has been translated. 
If not all the text has been translated yet then English will be shown for which there's not translation to be found. 
We rely on community support for the translations so any contributions are most welcome

**Comment by acuteenvy** [comment]
I know that, that's why I checked the languages that had this page translated.
[Here](https://github.com/archlinux/archinstall/blob/master/archinstall/locales/fr/LC_MESSAGES/base.po#L801) is the French translation of "Enter the number of parallel downloads to be enabled", yet this sentence is still being shown in English as in the screenshot.

**Comment by svartkanin** [comment]
In that particular case the translation isn't applied because the text that should be translated is not written correctly as it uses the template in the wrong way. 
Instead of having 
```
print(_(f"Enter the number of parallel downloads to be enabled.\n (Enter a value between 1 to {max_downloads})\nNote:"))
```

It should be 

```
print(str(_("Enter the number of parallel downloads to be enabled.\n (Enter a value between 1 to {})\nNote:")).format(max_downloads))
```
