### ISSUE TITLE
enabling swap on ZRAM 

### ISSUE THREAD

**Issue by jatin-cbs** [archlinux/archinstall#175]
There is no SWAP by default in the guided installer, However I recommend Swap on ZRAM by default as it will automatically allocate swap on boot.    So SWAP will automatically be equal to RAM size ! This is how its in Fedora and is the default behavior since fedora 33.

**Comment by Torxed** [comment]
Does this pose any security concerns if we have a encrypted root partition?

**Comment by jatin-cbs** [comment]
No it does not 
It can easily be setup using - 

https://aur.archlinux.org/packages/zram-generator/
https://aur.archlinux.org/packages/zram-generator-defaults/

zram-generator-defaults  package is just the same configuration as on Fedora, if it sees zram-generator it will enable it on boot.

**Comment by jatin-cbs** [comment]
Also as you were concerned I looked at bodhi and redhat bugzilla there is no security concern or regression.

**Comment by Torxed** [comment]
I personally don't mind adding AUR, but since AUR is not officially supported I can not add it either to something that's supposed to be officially supported. Perhaps under the AUR plugin for archinstall which will be available for other distro maintainers to use, but pushing for AUR to be implemented here is going to be a big no no sadly.

If zram-generator is available in any supported capacity, then we can add it here too.
If we're just talking about setting up a traditional swap, that can be done. Or if we can rely on [systemd-zswap](https://archlinux.org/packages/community/any/systemd-swap/), I don't use swap personally so I can't make heads or tails of what setup would be the best.

But something in the back of my mind tells me that swap, which is an extension of RAM, stored on disk, usually ends up unencrypted unless used with for instance [dmcrypt](https://wiki.archlinux.org/index.php/Dm-crypt/Swap_encryption).

**Comment by jatin-cbs** [comment]
I don't recommend zswap because of this https://fedoraproject.org/wiki/Changes/SwapOnZRAM#Why_not_zswap.3F
But you are correct that its in the AUR.

**Comment by omeringen** [comment]
> I personally don't mind adding AUR, 

Agree. I use [systemd-swap](https://archlinux.org/packages/community/any/systemd-swap/)  for zram.

**Comment by Torxed** [comment]
> > but since AUR is not officially supported
> 
> Agree. I use [systemd-swap](https://archlinux.org/packages/community/any/systemd-swap/) for zram.
> 
> * Edit /etc/systemd/swap.conf
> * uncomment
>   _zram_enabled=1_
>   And edit zram size to full of RAM
>   _zram_size=$(( RAM_SIZE / 1 ))_
> * enable service
>   _systemctl enable systemd-swap.service_

Seams clean enough and easy to implement with existing wrapping functions in the library.
I would just have to double-check the security implications on a partition-encrypted setup and laptops that hibernate and stuff.

**Comment by jatin-cbs** [comment]
I have encrypted setup and I asked on redhat bugzilla as well as reports on bodhi, there is no security implications or regressions, Its default in all fedora versions including workstation, server, IoT.

**Comment by Torxed** [comment]
> I have encrypted setup and I asked on redhat bugzilla as well as reports on bodhi, there is no security implications or regressions, Its default in all fedora versions including workstation, server, IoT and spins.

I also poked around and as long as it's zram it should be good.
It's the old and trusted traditional swap that spooked my brain a bit.

We'll add swap support for `v2.2.0`!

**Comment by grazzolini** [comment]
I'm not sure it's a good idea to enforce this on all the installations, regardless of what other distros do or don't. However, since swap is something that some people might want to have on a partition, it's something that should probably be a step, or, you know, #124. Allowing the user to run commands on the chroot post install also is helpful here.

**Comment by Torxed** [comment]
> Allowing the user to run commands on the chroot post install also is helpful here.

I see a pattern hehe. I'll hold off on this until #124 and we'll see if this is so frequently used that it should make it into an actual feature.

**Comment by grazzolini** [comment]
Yes, this allows any user customization they want at the ISO level, but actually happening post installation. By post installation here, I mean after the installer has installed a minimal system (or one of the profiles). However, one must keep in mind that, building packages from the AUR is not something easily done from withing the chroot. So, zram-generator is not achievable here.

**Comment by jatin-cbs** [comment]
> > but since AUR is not officially supported
> 
> Agree. I use [systemd-swap](https://archlinux.org/packages/community/any/systemd-swap/) for zram.
> 
>     * Edit /etc/systemd/swap.conf
> 
>     * uncomment
>       _zram_enabled=1_
>       And edit zram size to full of RAM
>       _zram_size=$(( RAM_SIZE / 1 ))_
> 
>     * enable service
>       _systemctl enable systemd-swap.service_

@grazzolini we can achieve this not using the AUR. by simply enabling it in swap config.

**Comment by Torxed** [comment]
This might be wild because I don't fully understand any existing issues, but would dropping into a `systemd-nspawn` be benefitial?
Personally I've loved this because it enables things like "setting up databases" because services and sockets are actually spun up.

It's a little bit heavy than just dropping in to a chroot, but it offers more.
Any down sides/risks?

**Comment by grazzolini** [comment]
> 
> @grazzolini we can achieve this not using the AUR. by simply enabling it in swap config.

Sure, there are several ways to use zram. While I agree that we should add swap in some manner and, depending on the type of swap (partition), it should be done at install time, we should address this and perhaps add zram as an option for the user to choose from. However, we should avoid being too opinionated on what the user should or shouldn't have by default. Some people don't want swap **at all**.

**Comment by jatin-cbs** [comment]
I think asking a user to "Do you want to enable swap on ZRAM ?" would be great before it sets up the partitions.

**Comment by grazzolini** [comment]
The thing is, without more information the user can't know if they want zram. Or if they want zswap, or if they want swap file, or partition. They might want to hibernate. They might not want swap at all. Without giving them more information, they will mostly say no on this, or simply hit enter to whatever default. Swap is the most problematic of things on an installation. Some users might realize too late they need/want a swap partition (or LVM), for hibernation, only to realize they'd have to mess with resizing partitions/filesystems. It's a mess.

**Comment by jatin-cbs** [comment]
thats why zram solves this.  Create a swap-on-zram during start-up. And no longer use swap partitions by default. it creates swap on system startup = the RAM size (according to its configuration) ,rather than having a swap partition. Also it can be easily removed or disabled. However your point is right that some people may not want swap that is why I was in favour on asking this during installation. Its fine if this won't be implemented as it can be configured any time and does not want any partitions. This can even be in the post install.

**Comment by Torxed** [comment]
> thats why zram solves this. Create a swap-on-zram during start-up. And no longer use swap partitions by default. it creates swap on system startup = the RAM size (depends on the configuration) ,rather than having a swap partition. Also it can be easily removed or disabled. However your point is right that some people may not want swap that is why I was in favour on asking this during installation. Its fine if this won't be implemented as it can be configured any time and does not want any partition changes This can even be in the post install.

I'll implement #124 first, and then I'm coming back here to see how to implement this nicely.
The partitioner will get a real overhaul after the patch release, after which a swap option might be very easilly included in the more advanced stages of the formatting! I'll leave it open and connect it to #124.

**Comment by Torxed** [comment]
This is being worked on and is partially done.
But the change is too big to be reasonably pushed for v2.2.0 in time - Which is why it will be introduced next month in v2.3.0.

**Comment by omeringen** [comment]
> 
> 
> > but since AUR is not officially supported
> 
> Agree. I use [systemd-swap](https://archlinux.org/packages/community/any/systemd-swap/) for zram.
> 
>     * Edit /etc/systemd/swap.conf
> 
>     * uncomment
>       _zram_enabled=1_
>       And edit zram size to full of RAM
>       _zram_size=$(( RAM_SIZE / 1 ))_
> 
>     * enable service
>       _systemctl enable systemd-swap.service_
Note that:
[Deprecating systemd-swap](https://lists.archlinux.org/pipermail/arch-dev-public/2021-May/030429.html). Moving to [zram-generator](https://archlinux.org/packages/community/x86_64/zram-generator/) which has been added to [community]

**Comment by Torxed** [comment]
I've now added a small step in the guided installer that asks if you the user wish to enable swap on zram. After which, `zram-generator` is installed and the example configuration is copied and used.

No enforcement is done, and it uses defaults.
