### ISSUE TITLE
Logic errors in `_fetch_lsblk_info()`

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1753]
The for loop here will cause the `lsblk` command to be called as many times as specified by the retry parameter. It does not break out of the loop if there is a success. In addition, if all tries fail the last try does not need a sleep.

https://github.com/archlinux/archinstall/blob/00b0ae7ba439a5a420095175b3bedd52c569db51/archinstall/lib/disk/device_model.py#L979-L989

The `get_lsblk_info()` function calls `_fetch_lsblk_info()` without the retry argument.

https://github.com/archlinux/archinstall/blob/00b0ae7ba439a5a420095175b3bedd52c569db51/archinstall/lib/disk/device_model.py#L1004-L1008

The retry parameter will then default to 3.

https://github.com/archlinux/archinstall/blob/00b0ae7ba439a5a420095175b3bedd52c569db51/archinstall/lib/disk/device_model.py#L967

This means that when `get_lsblk_info()` is called, if the `lsblk` command is working fine (exit code of 0) then the command will be called unnecessarily 2 additional times.

**Comment by codefiles** [comment]
This could be the source of the issue described by @hkrutzer in https://github.com/archlinux/archinstall/pull/1604#issuecomment-1514704715. Maybe the NVMe drive is being overwhelmed by 3 consecutive `lsblk` calls but they are all producing an exit status of zero, with the output of the last call missing data such as the partuuid.

https://github.com/archlinux/archinstall/blob/00b0ae7ba439a5a420095175b3bedd52c569db51/archinstall/lib/disk/device_handler.py#L344-L347

I tried to reproduce the issue using QEMU NVMe emulation because I do not have an NVMe drive to do testing with. [1] I can not reproduce the issue using that method.

[1] https://www.qemu.org/docs/master/system/devices/nvme.html

**Comment by svartkanin** [comment]
Great catch!

**Comment by Torxed** [comment]
PR has been merged!
