### ISSUE TITLE
Configuration File Error - Can't read profile

### ISSUE THREAD

**Issue by bd-g** [archlinux/archinstall#1762]
## Description

When using a configuration file saved from archinstall, it can't parse the profile section.

## Log Message

```
Unable to parse file {path}/archinstall/archinstall/default_profiles/custom.py: attempted relative import with no known parent package
```

## Examples of various config files that cause this error when loaded

```
...
"profile_config": {
    "gfx_driver": "All open-source (default)",
    "greeter": "lightdm",
    "profile": {
        "details": [
            "Awesome"
        ],
        "main": "Desktop"
    }
},
...
```

```
...

"profile_config": {
    "gfx_driver": "null",
    "greeter": null,
    "profile": {
        "details": [ ],
        "main": "Minimal"
    }
},
...
```

And several others, it happens with any profile.

**Comment by svartkanin** [comment]
@Torxed this didn't auto close after the merge

**Comment by bd-g** [comment]
I can close it - thought you were going to work on custom profile more first, so kept the issue open, but I can close if you're just deprecating it for now.

**Comment by svartkanin** [comment]
Custom profile is still bigger WIP if even useful at all, so I that's why I simply commented out the whole thing
