### ISSUE TITLE
Sway Profile Changes Not Persisted to Configuration File 

### ISSUE THREAD

**Issue by bd-g** [archlinux/archinstall#1763]
## Description

When selecting `sway` profile, it properly asks for control preference between `seatd` and `polkit`, however, this selection isn't written to a configuration file.

## Reproduce

1. Launch archinstall on commit 00b0ae7ba439a5a420095175b3bedd52c569db51
2. Go to profile, select profile, select desktop, select sway, and select either polkit or seatd for your seat access.
3. Select back, then save your configuration to a file.
4. Abort and check the contents of the file. The seat access option is not persisted.

## Example Config File from steps above

Note that the polkit/seatd selection is not included, and therefore not recoverable.

```
...
"profile_config": {
    "gfx_driver": "All open-source (default)",
    "greeter": "gdm",
    "profile": {
        "details": [
            "Sway"
        ],
        "main": "Desktop"
    }
},
...
```

**Comment by svartkanin** [comment]
The problem with it is that it's a custom question in the sway profile :thinking: 
I will try to get something implemented that makes it possible to export/import such generic profile specific settings

**Comment by Torxed** [comment]
It would be nice if the profile could inject configuration options to the configuration.
Which is why it modified that magic global variable before hehe.

I know that looked and felt non-standard and a bit ugly, so a more "pythonic way" would be awesome
