### ISSUE TITLE
encryption error

### ISSUE THREAD

**Issue by TimurSennikov** [archlinux/archinstall#1767]
there is an encryption error is py script, i cant install arch because of it

**Comment by Ziimmie** [comment]
Try ```

pacman -Sy archinstall

``` and that should fix it.

**Comment by RochaLAJ** [comment]
This error happened on line 75 of configuration.py file.

```
self._user_credentials['encryption_password'] = self._config[key].encryption_password
AttributeError: 'NoneType' object has no attribute 'encryption _password'
```

If you are in a rush and doens't care about encryption, you can remove those lines with vim and try again.

**Comment by TimurSennikov** [comment]
thanks guys

**Comment by svartkanin** [comment]
There were a lot of changes recently and this should be resolved in the most recent release
