### ISSUE TITLE
Error after setup everything

### ISSUE THREAD

**Issue by ryannewcomer** [archlinux/archinstall#1769]
Hi, i just download the iso file from arch Linux.org and make a new vm on virtualBox. Then i type archinstall. After set up everythink:
![38215029-59C9-49A2-A173-3ABE0CF2A601](https://user-images.githubusercontent.com/88273136/234383062-127d96a1-8fc9-4197-9e69-429e1692d7c7.jpeg)

I press install. But then:
![D3E6AD12-8562-40C7-B4BC-62A7FCFE8B80](https://user-images.githubusercontent.com/88273136/234383161-9f5e2c64-d1d0-4d55-b5e0-6e7fc93e2833.jpeg)

What’s wrong?

I am new. Please help me

**Comment by ryannewcomer** [comment]
Hi. I just ran the command and it Woking ! Thanks

**Comment by ryannewcomer** [comment]
Hi. Sadly, when everything is done and i go to chroot. But i don't know what to do. Then i just exit and reboot. But it don't work. It just go back to the home page and i have to it all again

**Comment by Elandig** [comment]
> Hi. Sadly, when everything is done and i go to chroot. But i don't know what to do. Then i just exit and reboot. But it don't work. It just go back to the home page and i have to it all again

Make sure you're booting from the drive you installed your distro on.

**Comment by jaybent** [comment]
> > Hi. Sadly, when everything is done and i go to chroot. But i don't know what to do. Then i just exit and reboot. But it don't work. It just go back to the home page and i have to it all again
> 
> Make sure you're booting from the drive you installed your distro on.

I agree, this sounds like you have forgot to remove the ISO and your system prioritizes ISOs for booting. Either change your settings or remove the ISO.

If it still doesn't work, then we need to have more information about what happens to be able to help you. If you join our discord you will get help with debugging quicker: https://discord.gg/R8HWv365Fp

**Comment by svartkanin** [comment]
This should be resolved
