### ISSUE TITLE
archinstall i3 fails

### ISSUE THREAD

**Issue by gtowen** [archlinux/archinstall#1776]
Attempted to install arch with i3 in virtualbox using archinstall. Install fails in package installation because i3wm and i3lock is written as one word in script and not separated by a comma.
`Installing packages: ('i3-wmi3lock', 'i3status', 'i3blocks', 'xterm', 'lightdm-gtk-greeter', 'lightdm', 'dmenu')`

[install.log](https://github.com/archlinux/archinstall/files/11374786/install.log)

**Comment by svartkanin** [comment]
This has already been fixed and is in master

**Comment by svartkanin** [comment]
You can run a `pacman -Sy archinstall` that should have the fix

**Comment by gtowen** [comment]
Hi, I did run a pacman Sy archinstall which installed archinstall-2.5.5-1 which gave the previous result.

I noticed a newer version in testing so I enabled the testing repo in pacman.conf and did pacman Sy archinstall again.
This installed archinstall-2.5.6-1 which failed to start with the following:

`Traceback (most recent call)
File "/usr/bin/archinstall", line 5, in <module>
from archinstall import_run_as_a_module
ModuleNotFoundError: no module named "archinstall"`

**Comment by svartkanin** [comment]
Right, that is fixed as well in master nut there hasn't been a new release yet

**Comment by gtowen** [comment]
Thank you for the info. My normal setup is archlinux with openbox which I manually install. 
I'm doing some de/wm testing so just wanted to speed things up using archinstall but wanted to let the team know of problems encountered.
Thanks for the help, will close this now and wait for the updated package release.
