### ISSUE TITLE
Error after updating archinstall

### ISSUE THREAD

**Issue by mimimalloc** [archlinux/archinstall#1781]
Experienced the error in archinstall as in #1769 and attempted the update workaround with

`pacman -Sy archinstall`

If I do this and then enter the 'archinstall' command, I then get this error:

```
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
ModuleNotFoundError: No module named 'archinstall'
```

**Comment by Torxed** [comment]
That is strange, what `python --version` is it on the ISO? They haven't dropped Python 3.11 yet right?
IIRC it's still in staging and I have a few more weeks to work out the kinds.

**Comment by calr0x** [comment]
Same.

**Comment by christian-heusel** [comment]
> ```
> pacman -Sy archinstall
> ```
> If I do this and then enter the 'archinstall' command, I then get this error:

Please try to do a full upgrade (`pacman -Syu`) and then see if the error persists.
By doing a `pacman -Sy` you are performing a so called partial upgrade which are unsupported in archlinux (see https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported for reference).

In theory the error should be resolved [by the rebuild](https://github.com/archlinux/svntogit-packages/commit/0d3752df41b9b54e512ede7be0d00acd68986cc1) that happened in the context of the python3.11 upgrade that just landed in the repos. This of course does not guarantee that there are no errors afterwards but I would atleast expect a different one!

**Comment by mimimalloc** [comment]
Update: If you're in the same position make sure you're using the latest Arch install image, I missed that a new one was released just today and was using last month's version downloaded a few days ago. archinstall works fine out-the-box for me on May's image release

**Comment by browser-bug** [comment]
I'm experiencing the same error on latest ISO (archlinux-2023.05.03-x86-64.iso). Upgrading with `pacman -Sy archinstall` corrupts the installation for some reason. And a full upgrade is not possible since partition is too full.

**Comment by christian-heusel** [comment]
> Upgrading with pacman -Sy archinstall

See my [post above](https://github.com/archlinux/archinstall/issues/1781#issuecomment-1533752228) about partial updates, you are updating archinstall (which then expects python3.11 and deps in python3.11) without updating the rest of the system which causes exactly this problem.

**Comment by KenjiTakahashi** [comment]
It's still happening. Updating the whole system is not possible (anymore), because the install media doesn't have enough space allocated for `/`.
Fixed for now with `pacman -Sy python archinstall`.

**Comment by calr0x** [comment]
Just get the newest install ISO and it fixes that. I had the same
problem...

**Comment by Torxed** [comment]
Out of curiosity, on the boot cmd line does adding `copytoram=y` allow for a full `pacman -Syu`?

**Comment by KenjiTakahashi** [comment]
I'm already using the latest ISO.
The `copytoram=y` doesn't change anything. From what I'm seeing, the ISO root is an `airootfs` of `256M` either way. [It is possible that the size is RAM dependent, the machine I'm testing on has "only" 2G of RAM.]

**Comment by Torxed** [comment]
> I'm already using the latest ISO. The `copytoram=y` doesn't change anything. From what I'm seeing, the ISO root is an `airootfs` of `256M` either way. [It is possible that the size is RAM dependent, the machine I'm testing on has "only" 2G of RAM.]

Yea the amount of RAM will be highly relevant here.
Either way, https://github.com/archlinux/archinstall/issues/1781#issuecomment-1538952304 will be the best workaround for sure.

**Comment by me-atilla** [comment]
> It's still happening. Updating the whole system is not possible (anymore), because the install media doesn't have enough space allocated for `/`. Fixed for now with `pacman -Sy python archinstall`.

I found a post that fixed the free space problem by adding `cow_spacesize=4G` to the boot parameters and running `mount -o remount,size=4G /run/archiso/cowspace` in live-arch. `pacman -Syu` still breaks archinstall, but thanks to you `pacman -Sy python archinstall` worked fine for me!
