### ISSUE TITLE
RFE: Consider installing/enabling dbus-broker instead of standard dbus-daemon by default

### ISSUE THREAD

**Issue by Edu4rdSHL** [archlinux/archinstall#1783]
Hello, thank you for all the work you have been doing on this project, it's really wonderful. Now, on why `archinstall` should switch by default to installing and enabling [dbus-broker](https://github.com/bus1/dbus-broker) by default, I will expose the reasons below.

## Background
DBus-broker is a modern implementation of the D-Bus message bus system, designed to be faster, more secure, and more efficient than the standard dbus-daemon implementation. As a result, many Linux distributions already switched to it, Fedora, for example, and others (Ubuntu) are considering switching to dbus-broker as well. 

## Request
I recommend that ArchLinux consider using dbus-broker instead of the standard dbus-daemon implementation for the following reasons:

- **Security**: dbus-broker is designed with security in mind and provides better isolation between applications, making it more difficult for one application to interfere with another.
- **Performance**: dbus-broker is optimized for performance, with a streamlined design that minimizes overhead and latency.
- **Simplicity**: dbus-broker has a simpler codebase than the standard dbus-daemon implementation, making it easier to maintain and debug.
- **Compatibility**: dbus-broker is fully compatible with the D-Bus specification and works seamlessly with existing D-Bus clients and services.
- **Modern design**: dbus-broker has been designed from the ground up to take advantage of modern hardware and software architectures, including support for asynchronous I/O and multithreading.

In addition to the above, here are some other reasons why a Linux distribution might want to use dbus-broker:

- **It is actively maintained and developed**: The dbus-broker project is actively maintained and developed by a team of experienced developers. This means that it is more likely to be bug-free and up-to-date with the latest security patches.
- **It is well-documented**: The dbus-broker project has extensive documentation that is available online. This makes it easy to learn how to use and configure dbus-broker.
- **It is supported by a large community**: The dbus-broker project has a large and active community of users and developers. This means that there are many resources available to help with troubleshooting and support.

## Impact
Dbus-broker is 100% compatible with the standard dbus-daemon implementation; therefore the change would not impact ArchLinux users in any way. Basically, it would be a transparent change for end users.

## Changes
So far, the changes would be:

- Install the `dbus-broker` package, which is in the official repos.
- Enable the system unit so that it replaces the old dbus-daemon: `systemctl enable dbus-broker.service`
- Enable the user unit so that it replaces the old dbus-daemon: `systemctl enable --user --global  dbus-broker.service`

## Conclusion
Overall, I believe that switching to dbus-broker would be beneficial for ArchLinux in all cases, and therefore I recommend that it be considered as an alternative to the standard dbus-daemon implementation.

Regards,
Ed

**Comment by dylanmtaylor** [comment]
As far as I know, dbus isn't explicitly installed - it is pulled in as a dependency. In other words, this would have to be a change made in Arch's packages/groups. It doesn't make sense for the installer to deviate from Arch default configuration.

**Comment by Edu4rdSHL** [comment]
systemd requires dbus, so, it's installed on every Arch system.

**Comment by dylanmtaylor** [comment]
This isn't really an installer bug - I think you'd have better luck filing a bug against https://archlinux.org/packages/core/x86_64/systemd/

**Comment by Edu4rdSHL** [comment]
I never said it's a bug, the title says "RFE", aka, Request For Enhancement.

Also, I discussed this with Torxed before opening the issue and he said it was ok.

**Comment by jaybent** [comment]
First off, I'm not against the idea of progress, and having better tools is great! Never heard of it and will look it up a bit more. Thanks!

That said, my gut reaction is that the Arch Install "guided" profile should not deviate from the default Arch Linux settings. 

My main arguments:
- It's the profile most beginners use. Changing fundamentals will create hurdles for them, especially in regards to getting help / finding the cause of issues

- First point will probably increase support load for us and frustration for users

- The guided profile is an example of how to use the python library to create your own implementation of a system profile or automated installer. It's not necessarily the "most optimal" way of doing things

- People can create their own profiles, one of the main reason this project exist!

- If Arch Linux decides to pivot to the new Dbus system, so will we automatically


Conclusion:
- Reject this suggestion based on my arguments

- OP creates a profile that implements the requested feature for inclusion in the project such that advanced users of Arch Install can use it


Thanks for your issue and support for the project!
//Jaybent

**Comment by Torxed** [comment]
> my gut reaction is that the Arch Install "guided" profile should not deviate from the default Arch Linux settings

This incorrectly assumes we *have* to change default values during installation.
We could easily create a sub-menu called `Optimizations` where it's optional to turn on this as an enhancement *(with or without a disclaimer that this voids support rights etc etc)*.

See https://github.com/archlinux/archinstall/issues/1796#issuecomment-1537344879

I appreciate the involvement and I just want to point out that we read and value all the points mentioned in this thread. Nothing is final or decided :)

**Comment by Edu4rdSHL** [comment]
Hey @jaybent, thank you for your input, indeed the most optimal way to implement it would be directly by Arch's defaults. However, there are some points in response to your points:

- The current `dbus-daemon` implementation in more likely to cause issues regarding D-Bus, than `dbus-broker`. Several well-known issues on `dbus-daemon` are addressed and fixed by `dbus-broker`, see [this article](https://dvdhrm.github.io/rethinking-the-dbus-message-bus/) if you want more context.
- `dbus-broker` is 100% compatible with the `dbus-daemon` capabilities.
- `dbus-broker` is a sufficiently mature software, which has been there since 2017 and demonstrated true benefits at the point where distros such as Fedora have used this implementation [for various years](https://fedoraproject.org/wiki/Changes/DbusBrokerAsTheDefaultDbusImplementation) instead of the default `dbus-daemon`, and looks like that Ubuntu [will switch](https://bugs.launchpad.net/ubuntu/+source/dbus-broker/+bug/2015538) to it as well from Ubuntu 23 onwards.
- As personal experience, I have used `dbus-broker` for some years now, and I can tell you that it's an install-and-forget improvement.

That said, I agree with @Torxed with it being under a sub-menu called `Optimizations`  that allows users to “tweak” its installation, that sub-menu idea will open the door to more ideas from the community as well.

Thank you again for your comments.

Regards,
Ed

**Comment by jaybent** [comment]
Sounds great! If the other big players are moving over I'm sure Arch will consider it as well and we all would benefit.

As to @Torxed point, it would be really good to create a standardized way of implementing things like this and I'm sure he has a few ideas of how to do that! There seems to be a few other issues and ideas that would benefit from it as well.

Good suggestions!

**Comment by jelly** [comment]
No, please don't do this in Arch Install ever... Arch itself should switch to `dbus-broker` by default. This is not a tweak this is something the distro should do.

**Comment by Edu4rdSHL** [comment]
+1 to Jelly's proposal, I really would love to see it change directly on AL. If there's something in what I could help (like, proposing it on some mailing list), please let me know.

**Comment by Edu4rdSHL** [comment]
With https://archlinux.org/news/making-dbus-broker-our-default-d-bus-daemon/ I'm closing this issue as I consider it done.
