### ISSUE TITLE
Error on first launch after archinstall

### ISSUE THREAD

**Issue by omnitrogen** [archlinux/archinstall#1820]
Hello all!

Thanks for that great script!

I've been using archinstall for the first time tonight to try to install Arch on my new desktop (AMD Ryzen 5 5600 / Nvidia RTX 4070) and the installation process was pretty straightforward (1 big ext4 encrypted partition).

After shutting down and unplugging the key, I powered on my computerand a prompt (very likely the `encrypt` mkinicpio hook) asked for the encryption password.

After typing my password, I got some mount errors:

```
[ 18.288026] /dev/nvme0n1p2: Can't open blockdev

mount: /new_root: /dev/nvme0n1p2 already mounted or mount point busy.
```

I'm then unable to access a shell and I'm dropped to a `>: rootfs`.

I'm unsure how to move forward..

Did something wrong happened during the install process?

**Comment by Torxed** [comment]
Is this issue similar to https://github.com/archlinux/archinstall/issues/1817?

**Comment by omnitrogen** [comment]
Thanks @Torxed for your answer!

It seems to be related, I'll have a look!

Sorry for the duplicate, I'm gonna close this issue.

**Comment by Torxed** [comment]
no worries! :)
