### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by ww866** [archlinux/archinstall#1829]
![image](https://github.com/archlinux/archinstall/assets/58193167/41ce3590-3ea6-41f1-838b-8c64a3ee8224)

**Comment by svartkanin** [comment]
Fair enough, would you mind sharing at least what exactly doesn't work?

**Comment by svartkanin** [comment]
Could you share the log file please, it should be under /var/log/archinstall/install.log

**Comment by DmitrySkibitsky** [comment]
![Uploading PXL_20230730_224911826.jpg…]()
I just had something similar.

**Comment by Torxed** [comment]
> I just had something similar.
> 
> ![PXL_20230730_224911826](https://user-images.githubusercontent.com/20288556/257079973-113df9af-f4bc-4d0c-bd10-b732c0034d84.jpg)

that looks like an older version of archinstall.

**Comment by svartkanin** [comment]
This should be resolved with the newest release otherwise we can revive this
