### ISSUE TITLE
gnome-extra provides WAY too much bloatware

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#183]
I can't imagine most people wanting all the packages this installs on a new installation. Most of these applications are things like games and advanced tools like dconf-editor that your average user should not be touching. Some of them are nice to have but can be installed later manually instead of during initial installation.

**Comment by dylanmtaylor** [comment]
After looking at the packages installed by gnome-extra, many are not needed or even desired for most people. I picked a few good ones to keep and removed gnome-extra. This removes almost 30 apps that were cluttering new installs.

**Comment by Torxed** [comment]
I'm all for it, as long as the basic expectations hold up, such as:
 * Terminal has to work out of the bat
 * At least one browser present or a way to get one
 * Configuring the basic things like wallpaper *(and possibly themes)*
 * A text editor would be nice

If all those things work, I don't see an issue with this and I don't mind merging.

**Comment by dylanmtaylor** [comment]
> I'm all for it, as long as the basic expectations hold up, such as:
> 
> * Terminal has to work out of the bat
> * At least one browser present or a way to get one
> * Configuring the basic things like wallpaper _(and possibly themes)_
> * A text editor would be nice
> 
> If all those things work, I don't see an issue with this and I don't mind merging.

Terminal is still installed with this change.
GNOME Web is also installed, with firefox/chrome a command away.
gedit is in the base GNOME, not extra.
Wallpaper can be configured without anything but base GNOME shell, and themes are enabled by gnome-tweaks which I explicitly typed in.

**Comment by dylanmtaylor** [comment]
Honestly, this could probably be even further reduced, but I think it's decent for an out of the box experience. It has all the expected applications and far less bloat than before.

**Comment by Torxed** [comment]
> > I'm all for it, as long as the basic expectations hold up, such as:
> > 
> > * Terminal has to work out of the bat
> > * At least one browser present or a way to get one
> > * Configuring the basic things like wallpaper _(and possibly themes)_
> > * A text editor would be nice
> > 
> > If all those things work, I don't see an issue with this and I don't mind merging.
> 
> Terminal is still installed with this change.
> GNOME Web is also installed, with firefox/chrome a command away.
> gedit, a text editor is in the base GNOME, not extra.
> Wallpaper can be configured without anything but base GNOME shell, and themes are enabled by gnome-tweaks which I explicitly typed in.

Then consider it merged! Well done and thanks for digging in to all of this.
You've done a lot of work already and it's nice to get some fresh eyes on all of these profiles..
