### ISSUE TITLE
Install Archlinux on a single ext4 partition

### ISSUE THREAD

**Issue by medmedin2014** [archlinux/archinstall#1832]
I don't use any secure boot so I'm used to installing Ubuntu Mate and Manjaro KED on a single partition ext4 (the others 3  partitions are only NTFS and contain Windows 10 and personal data), I simply set "/" to that partition then start the installation process, but with `archinstall` in manual partitioning I set mountpoint to `/` and boot to `True` and wipe to `True` and format to `ext4`, but after clicking on install it gives kind of error `! Formatting...Could not find... in disk after 5 retries...` then it gets stack at `Setting boot on on (parted) partition index 1`. I'm using archlinux-2023.05.03-x86_64.iso which I put on a USB using Ventoy.

**Comment by jothi-prasath** [comment]
I am also experiencing the same error

**Comment by svartkanin** [comment]
There have been some major upgrades which are not released yet. If you have a chance you could try to run the latest master
