### ISSUE TITLE
i3-wm install error

### ISSUE THREAD

**Issue by grzesgaj3** [archlinux/archinstall#1835]
During the installation  with desktop/i3wm option selected an error occurs ,  i3-lock needs to be separated with comma, that I belive will solve the issue

**Comment by svartkanin** [comment]
This is already fixed and xan be applied with
pacman -S archinstall

**Comment by vcrn** [comment]
You will need to update python also. Only updating archinstall will make archinstall unrunnable, at least at the moment.
```
pacman -S python archinstall
```
