### ISSUE TITLE
No need to enable periodic TRIM for btrfs

### ISSUE THREAD

**Issue by kojq** [archlinux/archinstall#1837]
Btrfs async discard has been enabled since the 6.2 kernel. Consequently, I suggest not enabling the fstrim.timer (periodic TRIM) for btrfs.

**Comment by lavafroth** [comment]
Thanks! This appears to be enabled by default. For everyone's reference, [here](https://elixir.bootlin.com/linux/latest/source/fs/btrfs/disk-io.c#L3688) is the source. Maybe someone can write a PR to change this behavior.

**Comment by Torxed** [comment]
> Thanks! This appears to be enabled by default. For everyone's reference, [here](https://elixir.bootlin.com/linux/v6.4.11/source/fs/btrfs/disk-io.c#L3688) is the source. Maybe someone can write a PR to change this behavior.

We need to change it, only for BTRFS it seems.
