### ISSUE TITLE
i am encountering fstrim error

### ISSUE THREAD

**Issue by smittyn** [archlinux/archinstall#1841]
from everything i can read the testing repo causes this issue or a dirty drive and with a completely clean drive and not selecting testing i still hit this error

**Comment by svartkanin** [comment]
Would you mind sharing the log please under /var/log/archinstall

**Comment by smittyn** [comment]
i ended up just installing manually

**Comment by lavafroth** [comment]
@svartkanin, we might as well remove the function that enables fstrim. It has been enabled in the kernel since 6.4.11 IIRC. Refer to #1837.
