### ISSUE TITLE
How to install to an existing partition?

### ISSUE THREAD

**Issue by fausone** [archlinux/archinstall#1843]
It doesn't seem possible. How can I know that I am using /dev/sdb4/ as root to install to.
In the manual disk setup I can't see the correct info for my partitions. No UUID or anything that matches the cfdisk readout or anything else.

**Comment by fausone** [comment]
After 3 attempts doing the exact same thing, magically archinstall's manual disk setup reported the correct UUID numbers so I could install. So something to look into anyway.

**Comment by svartkanin** [comment]
There were a lot of changes recently and this should be resolved in the most recent release
