### ISSUE TITLE
[master] User password not saved in user_credentials.json

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1860]

**Comment by Torxed** [comment]
My bad, was using an old version (thought I was using latest master ISO but mixed up the local files)

**Comment by Torxed** [comment]
Nope I was using the latest hehe.

![screenshot](https://github.com/archlinux/archinstall/assets/861439/0133bfb0-3282-4a81-8162-270462bd33bd)

**Comment by svartkanin** [comment]
@Torxed I should have more time again this week and can have a look.
Are you working on a new release

**Comment by Torxed** [comment]
That would be awesome! That one I can probably figure out and patch if you want to look at other stuff.

I'm planning it, but waiting for on-boarding of my packaging key. After that I'll package `simple_term_menu` and that's practically the last thing blocking a release.

A bonus would be if I could get #1859 done in time for that.

So at least 2-3 weeks away from a release :)

**Comment by svartkanin** [comment]
Thay sounds awesome, looking forward to the new release!

**Comment by lavafroth** [comment]
This probably happens because the `User` class is not already converted to a dictionary using the `json` method before passing it to [`_unsafe_encode`](https://github.com/archlinux/archinstall/blob/92b0d0f8332f5006f9e242d33809cd2c7c2248ea/archinstall/lib/general.py#L104-L120), which in turn defaults to safe encoding (ignoring the bang `!`) [here](https://github.com/archlinux/archinstall/blob/92b0d0f8332f5006f9e242d33809cd2c7c2248ea/archinstall/lib/general.py#L120).

**Comment by lavafroth** [comment]
I believe this issue has been resolved.

**Comment by f73** [comment]
So I used archistall (from archlinux-2023.07.01) for the first time today, using `--config `  , `--creds` and -`-disk_layouts` and my `user_credentials.json` is missing password, which I did not noticed until I found out that I could not login. I fixed it chrooting, not a big issue. Also, not sure what is the correct way to provide password, manually, based on `user_credentials.json` below? Thank you in advance... This is my `user_credentials.json`:

```
{
    "!users": [
        {
            "sudo": true,
            "username": "user"
        }
    ]
}
```

Thank you so much for making archinstall it is awesome!

**Comment by svartkanin** [comment]
This has been fixed in master and @Torxed will release a new version soon

**Comment by f73** [comment]
Also, not sure what is the correct way to provide password, manually, based on user_credentials.json? Any example? I have read [Options for --creds](https://archinstall.readthedocs.io/installing/guided.html#options-for-creds), but values part for !user are not clear to me...Thanks!
