### ISSUE TITLE
Mounting Parition KeyError

### ISSUE THREAD

**Issue by DomiRusz24** [archlinux/archinstall#1869]
```
 ! Formatting [BlockDevice(/dev/sdh, size=3.7GB, free_space=4010MB, bus_type=usb)] in 5....4....3....2....1....
Creating a new partition label on /dev/sdh
Adding partition to BlockDevice(/dev/sdh, size=3.7GB, free_space=4010MB, bus_type=usb), 3MiB->203MiB
Formatting /dev/sdh1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/sdh1
Marking partition Partition(path=/dev/sdh1, size=0.2, PARTUUID=e6a5ca46-01, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sdh, size=3.7GB, free_space=4010MB, bus_type=usb), 206MiB->100%
Formatting /dev/sdh2 -> ext4
Mounting / to /mnt/archinstall/ using Partition(path=/dev/sdh2, size=3.5, PARTUUID=e6a5ca46-02, fs=ext4)
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/sdh1, size=0.2, PARTUUID=e6a5ca46-01, fs=vfat)
Mounting Partition(path=/dev/sdh2, size=3.5, PARTUUID=e6a5ca46-02, fs=ext4) to /mnt/archinstall/
Mounting Partition(path=/dev/sdh1, size=0.2, PARTUUID=e6a5ca46-01, fs=vfat) to /mnt/archinstall/boot
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
'/dev/sdb'
[!] A log file has been created here: /var/log/archinstall/install.log
    Please submit this issue (and file) to https://github.com/archlinux/archinstall/issues
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 312, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/profiles.py", line 195, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 306, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', '/mnt'))
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 137, in perform_installation
    with archinstall.Installer(mountpoint, kernels=archinstall.arguments.get('kernels', ['linux'])) as installation:
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 163, in __exit__
    raise args[1]
  File "/usr/lib/python3.11/site-packages/archinstall/examples/guided.py", line 144, in perform_installation
    for partition in installation.partitions:
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 183, in partitions
    return get_partitions_in_use(self.target).values()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/helpers.py", line 434, in get_partitions_in_use
    block_devices_available = all_blockdevices(mappers=True, partitions=True, error=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/helpers.py", line 292, in all_blockdevices
    instances[path] = Partition(path, block_device=BlockDevice(get_parent_of_partition(pathlib.Path(path))))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/blockdevice.py", line 44, in __init__
    self.info = all_blockdevices(partitions=False)[path].info
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: '/dev/sdb'
```
Logs:

[install.log](https://github.com/archlinux/archinstall/files/11726322/install.log)

**Comment by sklorpion** [comment]
I think i have simillar problem:

Hardware model detected: Micro-Star International Co., Ltd. MS-7B79; UEFI mode: True
Processor model detected: AMD Ryzen 5 5600 6-Core Processor
Memory statistics: 14851040 available out of 16297608 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: b'none\r\n'
System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: b'none\r\n'
Virtualization detected: None; is VM: None
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Navi 23 [Radeon RX 6600/6600 XT/6600M] (rev c1)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '672M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '238.5G', 'children': [{'name': 'sda1', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '63003b8b-8f15-49ef-a9e6-e37039e5c5e9', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '238.5G'}]}, {'name': 'sdb', 'fstype': 'nvidia_raid_member', 'fsver': '100', 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sdb1', 'fstype': 'ntfs', 'fsver': None, 'label': 'Duzy', 'uuid': '01CE8FC75E123B00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '931.4G'}]}, {'name': 'sdc', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '2.7T', 'children': [{'name': 'sdc1', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '743db923-ba1c-4dd5-9d64-2d9695ae5d91', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '2.7T'}]}, {'name': 'sdd', 'fstype': 'promise_fasttrack_raid_member', 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sdd1', 'fstype': 'ntfs', 'fsver': None, 'label': 'Duzy', 'uuid': '01CE8FC75E123B00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '931.4G'}]}, {'name': 'sde', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '55.9G', 'children': [{'name': 'sde1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'NO_LABEL', 'uuid': '3CD6-DC6E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '300M'}, {'name': 'sde2', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': '9b04da5d-84c9-41eb-8907-aed97e044259', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '55.6G'}]}, {'name': 'sdf', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202306', 'uuid': '2023-06-01-15-26-15-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '7.5G', 'children': [{'name': 'sdf1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202306', 'uuid': '2023-06-01-15-26-15-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '775M'}, {'name': 'sdf2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '8BDF-0F5A', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '15M'}]}, {'name': 'sdg', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '0B'}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '1.9T', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '8CB4-CEA7', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '511M'}, {'name': 'nvme0n1p2', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': '5637a0a4-2fa6-4f49-a72d-a9c503fc3c18', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.9T'}]}, {'name': 'nvme1n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '465.8G', 'children': [{'name': 'nvme1n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '3583-6E8D', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '512M'}, {'name': 'nvme1n1p2', 'fstype': 'ext4', 'fsver': '1.0', 'label': 'Arch', 'uuid': '8be203e4-b29f-48a4-a27f-c4852b8cc938', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '457.3G'}, {'name': 'nvme1n1p3', 'fstype': 'swap', 'fsver': '1', 'label': None, 'uuid': 'b8f17bc7-a2d8-4342-bca8-31de290761e5', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '8G'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Unknown device found by '/sys/class/block/*', ignoring: /dev/sdg
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Password strength: moderate
Password strength: very weak
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [
        "multilib"
    ],
    "archinstall-language": "English",
    "audio": "pipewire",
    "bootloader": "grub-install",
    "config_version": "2.5.6",
    "debug": false,
    "desktop-environment": "kde",
    "disk_encryption": null,
    "gfx_driver": "AMD / ATI (open-source)",
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "lantan",
    "kernels": [
        "linux-lts"
    ],
    "keyboard-layout": "pl",
    "mirror-region": {
        "Poland": {
            "http://arch.midov.pl/arch/$repo/os/$arch": true,
            "http://arch.sakamoto.pl/$repo/os/$arch": true,
            "http://ftp.icm.edu.pl/pub/Linux/dist/archlinux/$repo/os/$arch": true,
            "http://ftp.psnc.pl/linux/archlinux/$repo/os/$arch": true,
            "http://mirror.juniorjpdj.pl/archlinux/$repo/os/$arch": true,
            "http://mirror.onet.pl/pub/mirrors/archlinux/$repo/os/$arch": true,
            "http://repo.skni.umcs.pl/archlinux/$repo/os/$arch": true,
            "https://arch.midov.pl/arch/$repo/os/$arch": true,
            "https://arch.sakamoto.pl/$repo/os/$arch": true,
            "https://ftp.icm.edu.pl/pub/Linux/dist/archlinux/$repo/os/$arch": true,
            "https://ftp.psnc.pl/linux/archlinux/$repo/os/$arch": true,
            "https://mirror.juniorjpdj.pl/archlinux/$repo/os/$arch": true,
            "https://repo.skni.umcs.pl/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "dhcp": true,
        "dns": null,
        "gateway": null,
        "iface": null,
        "ip": null,
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [],
    "parallel downloads": 0,
    "profile": {
        "path": "/usr/lib/python3.11/site-packages/archinstall/profiles/desktop.py"
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "pl_PL.UTF-8",
    "timezone": "Europe/Warsaw",
    "version": "2.5.6"
}
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "mountpoint": "/boot",
                "size": "512MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "btrfs": {
                    "subvolumes": [
                        {
                            "compress": false,
                            "mountpoint": "/",
                            "name": "@",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/home",
                            "name": "@home",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/log",
                            "name": "@log",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/var/cache/pacman/pkg",
                            "name": "@pkg",
                            "nodatacow": false
                        },
                        {
                            "compress": false,
                            "mountpoint": "/.snapshots",
                            "name": "@.snapshots",
                            "nodatacow": false
                        }
                    ]
                },
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs",
                    "mount_options": [
                        "compress=zstd"
                    ]
                },
                "mountpoint": null,
                "size": "100%",
                "start": "513MiB",
                "type": "primary",
                "wipe": true
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/nvme0n1
Adding partition to BlockDevice(/dev/nvme0n1, size=1907.7GB, free_space=1031kB+1049kB+335kB, bus_type=nvme), 1MiB->512MiB
Adding partition using the following parted command: /dev/nvme0n1 mkpart primary fat32 1MiB 512MiB
Retrieving partition PARTUUID=c815b0a6-f8ae-4318-81ad-a168a22006f2 or UUID=None
Matched PARTUUID=c815b0a6-f8ae-4318-81ad-a168a22006f2 against c815b0a6-f8ae-4318-81ad-a168a22006f2
Formatting /dev/nvme0n1p1 -> vfat
/usr/bin/mkfs.vfat -F32 /dev/nvme0n1p1
Marking partition Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=c815b0a6-f8ae-4318-81ad-a168a22006f2, fs=vfat) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/nvme0n1, size=1907.7GB, free_space=1031kB+1049kB+335kB, bus_type=nvme), 513MiB->100%
Adding partition using the following parted command: /dev/nvme0n1 mkpart primary btrfs 513MiB 100%
Retrieving partition PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f or UUID=None
Matched PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f against 54f7e9a2-a9ae-4264-b162-d569d505ef4f
Formatting /dev/nvme0n1p2 -> btrfs
Mounting BTRFSPartition(path=/dev/nvme0n1p2, size=1907.2, PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f, fs=btrfs) to /mnt/archinstall/
Setting up subvolumes: [Subvolume(name='@', mountpoint='/', compress=False, nodatacow=False), Subvolume(name='@home', mountpoint='/home', compress=False, nodatacow=False), Subvolume(name='@log', mountpoint='/var/log', compress=False, nodatacow=False), Subvolume(name='@pkg', mountpoint='/var/cache/pacman/pkg', compress=False, nodatacow=False), Subvolume(name='@.snapshots', mountpoint='/.snapshots', compress=False, nodatacow=False)]
Attempting to create subvolume at /mnt/archinstall/@
Attempting to create subvolume at /mnt/archinstall/@home
Attempting to create subvolume at /mnt/archinstall/@log
Attempting to create subvolume at /mnt/archinstall/@pkg
Attempting to create subvolume at /mnt/archinstall/@.snapshots
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=c815b0a6-f8ae-4318-81ad-a168a22006f2, fs=vfat)
Using mount order: [('/', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fa34de3bba0>), ('/.snapshots', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fa34de3bd80>), ('/boot', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fa34de3bf60>), ('/home', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fa34de3bc40>), ('/var/cache/pacman/pkg', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fa34de3be20>), ('/var/log', <function Installer.mount_ordered_layout.<locals>.<lambda> at 0x7fa34de3bec0>)]
Mounting subvolume @ on BTRFSPartition(path=/dev/nvme0n1p2, size=1907.2, PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f, fs=btrfs) to /mnt/archinstall
Getting mount information for device path /mnt/archinstall
Mounting subvolume @.snapshots on BTRFSPartition(path=/dev/nvme0n1p2, size=1907.2, PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f, fs=btrfs) to /mnt/archinstall/.snapshots
Getting mount information for device path /mnt/archinstall/.snapshots
Mounting Partition(path=/dev/nvme0n1p1, size=0.5, PARTUUID=c815b0a6-f8ae-4318-81ad-a168a22006f2, fs=vfat) to /mnt/archinstall/boot
Getting mount information for device path /mnt/archinstall/boot
Mounting subvolume @home on BTRFSPartition(path=/dev/nvme0n1p2, size=1907.2, PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f, fs=btrfs) to /mnt/archinstall/home
Getting mount information for device path /mnt/archinstall/home
Mounting subvolume @pkg on BTRFSPartition(path=/dev/nvme0n1p2, size=1907.2, PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f, fs=btrfs) to /mnt/archinstall/var/cache/pacman/pkg
Getting mount information for device path /mnt/archinstall/var/cache/pacman/pkg
Mounting subvolume @log on BTRFSPartition(path=/dev/nvme0n1p2, size=1907.2, PARTUUID=54f7e9a2-a9ae-4264-b162-d569d505ef4f, fs=btrfs) to /mnt/archinstall/var/log
Getting mount information for device path /mnt/archinstall/var/log
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdd': {'path': '/dev/sdd', 'PATH': '/dev/sdd', 'TYPE': 'promise_fasttrack_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '48', 'DEVNAME': 'sdd', 'DEVTYPE': 'disk', 'DISKSEQ': '4'}}
Unknown device found by all_blockdevices(), ignoring: {'/dev/sdb': {'path': '/dev/sdb', 'PATH': '/dev/sdb', 'VERSION': '100', 'TYPE': 'nvidia_raid_member', 'USAGE': 'raid', 'MAJOR': '8', 'MINOR': '16', 'DEVNAME': 'sdb', 'DEVTYPE': 'disk', 'DISKSEQ': '2'}}
Could not get block device information using blkid() using command blkid -p -o export /dev/sdg
Could not get free space on /dev/sdg: ['/usr/bin/parted', '-s', '--machine', '/dev/sdg', 'print', 'free'] exited with abnormal exit code [1]: b'Error: Error opening /dev/sdg: No medium found\r\n'
'/dev/sdd'

**Comment by Torxed** [comment]
I got this earlier today as well but can't for the love of me remember why it happened.
Regarding the second post, the device appears to be a RAID device which is something we haven't added support for yet.

**Comment by svartkanin** [comment]
Could you try the latest master version instead as there have been a major overhaul of the code regarding partitioning

**Comment by svartkanin** [comment]
There were a lot of changes recently and this should be resolved in the most recent release
