### ISSUE TITLE
Desktop Environment Selection Bug

### ISSUE THREAD

**Issue by DGarcia200** [archlinux/archinstall#1876]
Installer remembers previously selected profile rather than the updated selection. 
E.g. I chose Gnome desktop but then decided I preferred KDE. Selection appeared to have updated but the installer proceeded to install Gnome instead.

**Comment by svartkanin** [comment]
Which release are you on?

**Comment by DGarcia200** [comment]
> Which release are you on?

I’m currently running the latest ISO release. I made sure to update the database and use the latest archinstall script

**Comment by svartkanin** [comment]
I'll have a look at that

**Comment by svartkanin** [comment]
@DGarcia200 I just tried to reproduce this on the latest master but it seems to work as expected. 
```
$ archinstall
Profile -> Desktop -> Gnome
<Back to Global Menu>
Profile -> Desktop -> Uncheck Gnome and Check KDE
<Back to Global Menu>
```

KDE was installed. 
The Deskop selection is a multi selection, which means if you re-enter and navigate to a different entry and press ENTER it will *ADD* that selection to the existing ones. 

If you have it available would you mind sharing the `/var/log/archinstall/install.log` file?

**Comment by svartkanin** [comment]
After selection of the profile configuration, back in the main menu if you hover on the profile the box on the bottom should show you exactly which profiles will be installed.

In case of the profile selection, space or enter will have similar effects as it's a multi selection, which means you can install multiple profiles at the same time.

**Comment by DGarcia200** [comment]
Is the branch you’re referring to the one under the steps for installing in a live environment? I’ll give it a shot when I get home from work.

**Comment by svartkanin** [comment]
Yes it should be that one

**Comment by XEmpty** [comment]
Umm, where is hyperland on list ?  On 2.5.6, I don't see it.
