### ISSUE TITLE
Could not detect root

### ISSUE THREAD

**Issue by AnmolKamat** [archlinux/archinstall#1879]
Arch Linux is new to me.
I want to dual-boot Windows 11 and Arch Linux.
I want to allocate 30GB for Root and 300MB for the boot and remaining for windows on my 256GB SSD.
Also i don't want to wipe everything.

Install log : [Install.log](http://0x0.st/HTAc.log)
configuration : [user_configuration.json](http://0x0.st/HTAT.json)
Disk layout : [disk_layout.json](http://0x0.st/HTAA.json)

**Comment by svartkanin** [comment]
For dual boot setup there's a guide available here https://www.youtube.com/watch?v=RoTe4uAqIHA&feature=youtu.be
