### ISSUE TITLE
Cant find any drive

### ISSUE THREAD

**Issue by mariorodvenUS** [archlinux/archinstall#1881]
When doing the archinstall, i can do pretty much any step, excepting selecting a drive, it shows a black screen that can only be quitted with ctrl + C. I can list the disks with lslbk

Here is the /var/log/archinstall/install.log:

Hardware model detected: innotek GmbH VirtualBox; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Memory statistics: 17686428 available out of 18134944 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '672M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '40.5G'}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202306', 'uuid': '2023-06-01-15-26-15-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '790.3M'}]}
Testing connectivity to the Arch Linux mirrors ...

['/usr/bin/pacman', '-Sy'] exited with abnormal exit code [None]: b'\x1b[?25l:: Synchronizing package databases...\r\n core\r\n'
Arch Linux mirrors are not reachable. Please check your internet connection and the log file '/var/log/archinstall/install.log'.
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Memory statistics: 17663880 available out of 18134944 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '672M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '40.5G'}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202306', 'uuid': '2023-06-01-15-26-15-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '790.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Memory statistics: 17659044 available out of 18134944 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '672M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '40.5G'}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202306', 'uuid': '2023-06-01-15-26-15-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '790.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz
Memory statistics: 17628376 available out of 18134944 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '672M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '40.5G'}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202306', 'uuid': '2023-06-01-15-26-15-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '790.3M'}]}
Testing connectivity to the Arch Linux mirrors ...

**Comment by Eyndjl** [comment]
Just 5 minutes ago I encountered this problem. The only thing that helped me was formatting the disk on which to install the system.

**Comment by mariorodvenUS** [comment]
> Just 5 minutes ago I encountered this problem. The only thing that helped me was formatting the disk on which to install the system.

I did that, changed the disk, but none of that worked for me ;-;

**Comment by svartkanin** [comment]
There were a lot of changes recently and this should be resolved in the most recent release
