### ISSUE TITLE
you still need to configure the username 

### ISSUE THREAD

**Issue by peteblank** [archlinux/archinstall#1892]
So this is not really a problem for me but I can't 100% recommend arch install to new comers because the username still needs some configuration post install. The username is not added to the sudoers file and it's not added to the sudoers group and it logs in as a root by default when it boots. Other than that its pretty good, but really I think that should be given some priority over other less pressing concerns really. Also i think NetworkManager wasn't installed I'm not sure but I ended up having to do wpa-cli before installing NetworkManager if I recall correctly and the internet kept going on and off while I was doing it and I think I've had to deal with those issues last time I used it which was years ago I think.

**Comment by Torxed** [comment]
> The username is not added to the sudoers file

It should be added to `/etc/sudoers.d/username` and not the ordinary sudoers file.

> not added to the sudoers group

I'm not sure there even is a sudoers group by default in Arch, but we've never added users to it as we add user by user.

> Also i think NetworkManager wasn't installed

Aside from your uncertanty I'm pretty sure it does get installed, but only if you chose that setting in the network settings. As we have three options, one being NM. And we now days install the applet if you choose a desktop environment with NM :)

**Comment by peteblank** [comment]
not sudoers group well you know what I mean user usermod -aG wheel... either way the point is the user that is created does not have sudo privileges and it logs in as a root at first. I can't recall the exact steps i took but it was something like that.

**Comment by Torxed** [comment]
I mean I can *try* to reproduce this but without the exaxt steps it'll be hard to try anything beyond the obvious things.

Whe moved away from adding wheel to avoid accidents. But i'll make sure sudo users are sudo before closing this.

**Comment by peteblank** [comment]
Okay thank you
