### ISSUE TITLE
Maybe build wheel dependencies and package them into the ISO

### ISSUE THREAD

**Issue by lavafroth** [archlinux/archinstall#1896]
The ISO file that is generated using `build_iso.sh` does not contain necessary build tools like `pkg-config` and `gcc`. Some libraries like `simple-term-menu` require compilation of libraries using `gcc`. However, if we include these packages, the ISO gets bloated to ~1.2GiB. The tradeoff of packaging pre-built wheel dependencies into the ISO is that we won't be able to
```sh
git pull
pip install . --break-system-packages
```
in the live environment.

Maybe someone can suggest a better alternative?

**Comment by Torxed** [comment]
You should be able to remove makedepends after the package is installed tho? So the ISO should only take up as much space as is needed by the package itself.

On a phone so can't verify :)

**Comment by lavafroth** [comment]
Yes, we might build the dependencies with `gcc` ahead of time since most developers won't be modifying them directly. I'll try modifying `build_iso.sh` to incorporate this.
