### ISSUE TITLE
device_model.py - 'NoneType' object has no attribute 'value'

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#1899]
Reported from discord: https://discord.com/channels/726808923662712894/726809631342592081/1123276450288652298

![rn_image_picker_lib_temp_ffb4d1f7-5aad-4472-9e1e-0f4e9ac6e927 (1)](https://github.com/archlinux/archinstall/assets/861439/214083a7-11dc-49fd-bb22-72b89e3a54a0)

**Comment by svartkanin** [comment]
@Torxed this one should fix it https://github.com/archlinux/archinstall/pull/1880
