### ISSUE TITLE
Sway Nvidia missing kernel parameter

### ISSUE THREAD

**Issue by JustFrederik** [archlinux/archinstall#1903]
I tried installing sway with archinstall, but no GPUs where detected when I tried to boot into sway. This is because this kernel parameter was missing: nvidia-drm.modeset=1

**Comment by Torxed** [comment]
This feels more like a bug with nVidia:
![screenshot](https://github.com/archlinux/archinstall/assets/861439/7fa6cf13-2bc3-41f6-bb67-9a3fb5d6f7a7)

We could work around it and add "fixes" as mentioned in the above note taking from [sway wiki entry](https://wiki.archlinux.org/title/Sway), but that would add complexity here and is specific to a set of users running that specific setup.

I wouldn't mind adding it, but we should treat it as a workaround if we do.

**Comment by JustFrederik** [comment]
@Torxed it does not officially support nvidia and it wont work with modern nvidia gpus. When [Direct Rendering Manager](https://en.wikipedia.org/wiki/Direct_Rendering_Manager) is enabled it works. Its not like it is only a small group of users that are affected, since there is only nvidia, radeon and intel. I thought it would make sense since it fixes that issue for everyone who has an nvida gpu
