### ISSUE TITLE
Add extra option  to download packages faster - #ParallelDownloads = 5

### ISSUE THREAD

**Issue by erikdubois** [archlinux/archinstall#1914]
Could you provide the choice to use ParallelDownloads in /etc/pacman.conf in the live environment and later on real metal?

**Comment by svartkanin** [comment]
I think that's already a possibility, you need to run archinstall with the "--advanced" flag

**Comment by erikdubois** [comment]
Well if it works - please make it a default

**Comment by erikdubois** [comment]
`archinstall --advanced `

![image](https://github.com/archlinux/archinstall/assets/10594806/efc482b7-2980-43b3-b4b1-b89d3f1553ba)
