### ISSUE TITLE
Crash on Drive Selection - No Option Available

### ISSUE THREAD

**Issue by DC4JG** [archlinux/archinstall#1915]
Downloaded `archlinux-2023.07.01-x86_64.iso` and launched `archinstall`. Drive selection crashed the installer (reproducibly), apparently because it expects at least one option to choose from and got none due to some issue.

The drive had an ext4 partition and maybe parts of grub on it from a previous botched installation. After deleting the drive/partition via `fdisk` the installer's drive selection works as intended.

Sorry for bad image quality and thanks for improving the Arch installation process ❤️ 
![2023-07-03-152309_002](https://github.com/archlinux/archinstall/assets/1653033/42ce84f5-06e8-4f12-ac39-87bf46874a67)

Transcript for searchability:
Unknown device found by all_blockdevices()
Menu didn't find any options to choose from *
invalid parameter at Menhu() call was at <select_harddrives>
archinstall.lib.exceptions.RequirementError: Menu.__init__() requires at least one option to proceed.

**Comment by realJustinLee** [comment]
same here, `archinstall` is broken again

**Comment by svartkanin** [comment]
There hasn't been any new release. Please use master if you can

**Comment by realJustinLee** [comment]
@svartkanin okay, please just close this issue thanks.

**Comment by svartkanin** [comment]
Closing as resolved
