### ISSUE TITLE
Log messages interfere with menus

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1916]
If a call to a log function is made while a menu is being displayed the log message will be written on top of the menu.

This came to my attention with 748f03c where an instance of the bug became possible inside the menu created by `GlobalMenu._disk_encryption()`. 

Below are two screenshots; the first shows this menu displayed as expected and the second shows this menu when the libfido2 package is not installed.

![image](https://github.com/archlinux/archinstall/assets/11915375/d82d83d9-aa15-4eb8-bc7b-bc05ca7afffd)

![image](https://github.com/archlinux/archinstall/assets/11915375/5a1ce93b-c568-4f48-ad36-01bb1515f3fc)

The following `systemd-cryptenroll --fido2-device=list` command results in an exception being raised when the libfido2 package is not installed and so both of the error log messages get triggered.

https://github.com/archlinux/archinstall/blob/64fc585fa7624060d406b9fcb877baf968ff0f24/archinstall/lib/disk/fido.py#L39-L46

In this case the log messages are written to `stdout` since the log level is `logging.ERROR`.

https://github.com/archlinux/archinstall/blob/64fc585fa7624060d406b9fcb877baf968ff0f24/archinstall/lib/output.py#L324-L326

**Comment by svartkanin** [comment]
These should probably be converted into debug instead, but the user will never get informed about it. 

A better solution would be to handle the problem very explicitly and not allow the user to perform any encryption actions while displaying the problem in an info box

**Comment by svartkanin** [comment]
It's not a big issue atm I think as this shouldn't happen on the ISO as the libis present

**Comment by codefiles** [comment]
Please note that this issue is intended to be broad and cover the concept of logging while a menu is being displayed. The  particular instance given where this occurs in the encryption menus is being used as an example. Unless it is determined that logging while a menu is being displayed is not valid, a solution should be targeted at the broad concept and not the given particular instance. There may be other instance where this occurs, I have not checked.

> These should probably be converted into debug instead, but the user will never get informed about it.

It may be more appropriate for them to be debug but this would not be a solution for more than just failing to inform the user. The bug can also occur with debug when verbose is used, take a look at the conditional for writing the log to `stdout`.

> A better solution would be to handle the problem very explicitly and not allow the user to perform any encryption actions while displaying the problem in an info box

To not allow the user to perform any encryption actions would be a mistake because encryption works fine without the libfido2 package. The package is needed for HSM to unlock encrypted drives, which is not required to use encryption.

> It's not a big issue atm I think as this shouldn't happen on the ISO as the libis present

Correct, this one particular instance of the bug will not occur on the official installation image. Please see the comment left by @ArtikusHG here https://github.com/archlinux/archinstall/pull/1893#issuecomment-1603291003 and the following ArchWiki topic for a better understanding.

https://wiki.archlinux.org/title/Install_Arch_Linux_from_existing_Linux#From_a_host_running_Arch_Linux

**Comment by svartkanin** [comment]
That's all correct. To add to that, it's not necessarily only log messages that may interfere but all kind of output done (essentially any `print`) while a menu is active. 

I'm not entirely sure if it is possible to detect an active menu and suppress stdout but only log to the file instead

**Comment by codefiles** [comment]
Could menus be expanded to have a footer section that is visible when there is logging information to display? Maybe that could be paired with the addition of a parameter to the log functions that can be used in a conditional for writing to that area instead of stdout?

**Comment by codefiles** [comment]
> To add to that, it's not necessarily only log messages that may interfere but all kind of output done (essentially any `print`) while a menu is active.

Very good point.

**Comment by svartkanin** [comment]
Menus do have a footer in the form of the preview where we show information in. 
Not sure if that would be a good way to display it though, as there may already be info displayed there.

For this particular problem with the HSM we could display a message in that box to indicate that the selection ain't working as the library is missing.

For others we could try to redirect the output to the log file. For any additional case we probably have to decide on a xase to case basis what the best option is 🤷‍♂️

**Comment by codefiles** [comment]
> Menus do have a footer in the form of the preview where we show information in.
> Not sure if that would be a good way to display it though, as there may already be info displayed there.

Right but that would not really be expanding it to add a new section to the bottom for this particular use.

> For this particular problem with the HSM we could display a message in that box to indicate that the selection ain't working as the library is missing.

I like this. Good enough for now.
