### ISSUE TITLE
Redundant profile menu

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1933]
Selecting the Profile option in the menu leads to a menu with the option Profile. Below is a screenshot of the menu described.

![image](https://github.com/archlinux/archinstall/assets/11915375/e2fac7f7-2ee9-4e49-a7e2-a9d4fe09fafc)

**Comment by svartkanin** [comment]
Yep indeed that's a bit of a waste

**Comment by svartkanin** [comment]
@codefiles I just had a look at this and it's actually not a redundant selection. 
If you go into the `Profile -> Profile` and lets say select `Desktop -> KDE` then this selection will enable more options such as GFX driver and greeter

![image](https://github.com/archlinux/archinstall/assets/19396770/bd4d3003-c641-4557-a21e-ad7fd526a497)


Maybe renaming the second `Profile` would help here? I'm open for suggestions

**Comment by Torxed** [comment]
Yea this one confused me too a bit heh.
If it's a selection menu, maybe `Profile` -> `Select Profile`?

**Comment by svartkanin** [comment]
What about `Profile -> Type`?

**Comment by Torxed** [comment]
Yepp that works!
