### ISSUE TITLE
Audio option regression

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1934]
The Audio option is inaccessible without selecting a profile first.

**Comment by svartkanin** [comment]
I think the best would be to not show the Audio unless there's a profile selected. Unless there's a good reason someone would want to install Audio without a Profile :thinking:

**Comment by Torxed** [comment]
A common scenario is a sonos-like setup with pulseaudio/pipewire where people have a "server" connected to remote speaker and want no desktop etc but want a sound server in order to play audio only.

**Comment by svartkanin** [comment]
Olay then let's completely decouple the audio setting from the profile

**Comment by svartkanin** [comment]
@Torxed @codefiles raised a PR that addresses the regression
