### ISSUE TITLE
Boot partition regression

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1941]
The change to the `DeviceModification.get_boot_partition()` function in afaf42e means that it will return `None` when an ESP is used and an XBOOTLDR is not present. Before this change in that given scenario the function would return the ESP. Anywhere the boot partition is accessed when there is only an ESP is going to cause an issue.

The code below will prevent proceeding with the installation by selecting _Install_.

https://github.com/archlinux/archinstall/blob/69c37e7c79b8756e300438fd2d25f6d40db5e04b/archinstall/lib/global_menu.py#L350-L351

The screenshot below demonstrates that this occurs with the _Disk configuration_ option _Use a best-effort default partition layout_.

![image](https://github.com/archlinux/archinstall/assets/11915375/0efd293f-cfd7-4824-979a-09951d11408c)

The code below will cause a crash and prevent the boot loader from being installed if providing a configuration with the described setup and then using `--silent`.

https://github.com/archlinux/archinstall/blob/69c37e7c79b8756e300438fd2d25f6d40db5e04b/archinstall/lib/installer.py#L1101-L1102

```
ValueError: Could not detect boot at mountpoint /mnt/archinstall
```

**Comment by 25d-228** [comment]
That's it, same here.

**Comment by Torxed** [comment]
@25d-228 the fix from codefiles should be merged and should solve the issue :)
