### ISSUE TITLE
Boot loader disk encryption conditional always fails

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#1949]
The screenshot below shows the warning that is displayed on boot of an installed system using systemd-boot and root encryption.

![image](https://github.com/archlinux/archinstall/assets/11915375/abc0ec94-ed5c-40e8-9579-08caf6e0c77a)

The options line of the systemd-boot entry is:

```
options root=PARTUUID=7e2b6859-82f1-41c5-828c-4f05fef09596 rw rootfstype=ext4
```

What is intended by the code and would also resolve the warning is:

```
options cryptdevice=PARTUUID=7e2b6859-82f1-41c5-828c-4f05fef09596:luksdev root=/dev/mapper/luksdev rw rootfstype=ext4
```

The intended options line is not produced because the following conditional always returns false.

https://github.com/archlinux/archinstall/blob/1af21c3e9582f3bf88f03ae2d45761b8b4ba3b64/archinstall/lib/installer.py#L800

This conditional does not work because a `PartitionModification.fs_type` is not considered valid if it is `FilesystemType.Crypto_luks` and encrypted partitions are tracked by the `Installer._disk_encryption.partitions` list rather than the `PartitionModification.fs_type` anyway.

https://github.com/archlinux/archinstall/blob/1af21c3e9582f3bf88f03ae2d45761b8b4ba3b64/archinstall/lib/disk/device_handler.py#L244-L257

**Comment by Torxed** [comment]
Solid testing! And glad you found it before I tagged the release!

**Comment by codefiles** [comment]
Thank you for putting in the time to review and merge all these last minute fixes before the release.
