### ISSUE TITLE
KDE minimal installation

### ISSUE THREAD

**Issue by dagdrommer** [archlinux/archinstall#195]
First I would like to thank everyone contributing to this great package, I think it will help our great Arch community to grow.

When installing the KDE option it comes with the `kde-applications-meta` package with adds more than 600MB of mostly unnecessary apps and games to the arch installation. In my humble opinion this is against the mindset the Arch-Distro: To keep things simple and minimal. On the other hand, when removing this metapackage some important apps are missing that might harm a smooth start of a newbie. Therefore I purpose to add the following packages for a minimal arch installation instead of the meta package:
- `konsole` (native kde console)
- `dolphin` (kde file manager)
- `kate` (kde text editor)

Furthermore the following packages can be considered:
`dolphin-plugins, kcalc, yakuake, kio, kio-extras, kfind, okular, ksystemlog, ksysguard, khotkeys, kdegraphics-thumbnailers, gwenview, kimageformats, qt5-imageformats`

Please let me know what you think.
Cheers!

**Comment by Torxed** [comment]
I think this is what #183 and mainly d5da80d is trying to solve.
But if I read between the lines, you suggest further slimming? @dylanmtaylor, any input here? :)

**Comment by dagdrommer** [comment]
> I think this is what #183 and mainly [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37) is trying to solve.
> But if I read between the lines, you suggest further slimming? @dylanmtaylor, any input here? :)

I do not suggest further smlimming when it comes to [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37) -- which is the GNOME option. I suggest slimming for the KDE option (which is at the moment even more bloated than gnome ever was). :smile:

**Comment by dylanmtaylor** [comment]
> > I think this is what #183 and mainly [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37) is trying to solve.
> > But if I read between the lines, you suggest further slimming? @dylanmtaylor, any input here? :)
> 
> I do not suggest further smlimming when it comes to [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37) -- which is the GNOME option. I suggest slimming for the KDE option (which is at the moment even more bloated than gnome ever was). 
> 
> Edit: Tough, when looking at the edits of the gnome option [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37), I don't think the e-mail-client `evolution` or an e-mail-client in general is necessary from minute one of an installation.

Right, this is KDE, not GNOME, so it'd be different. Probably a packaging issue as we're pulling in only a few packages explicitly for KDE: `plasma-meta kde-applications-meta sddm`. These metapackages might have too much in there so could be an upstream packaging issue. Regarding evolution specifically, I left it in since it was in before my change and figured it might be desirable out of the box, but I don't care one way or another - easy enough for users who want it to install it, so if we remove it, I don't have any complaints.

**Comment by Torxed** [comment]
> > I think this is what #183 and mainly [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37) is trying to solve.
> > But if I read between the lines, you suggest further slimming? @dylanmtaylor, any input here? :)
> 
> I do not suggest further smlimming when it comes to [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37) -- which is the GNOME option. I suggest slimming for the KDE option (which is at the moment even more bloated than gnome ever was). 😄
> 
> Edit: Tough, when looking at the edits of the gnome option [d5da80d](https://github.com/archlinux/archinstall/commit/d5da80d770bd0867510791fccd955873c64cea37), I don't think the e-mail-client `evolution` or an e-mail-client in general is necessary from minute one of an installation.

I've been working my way up the notifications today and sure enough linked the wrong profile ^^
I agree that the profiles take way to long to install and doesn't really follow the Arch principles at the moment, they're a bit to bloated.

I honestly welcome any PR's for slimming these down to keep things simple, as long as:
 * The default terminal works
 * The user have a browser *(or way of installing one)*
 * The expected WM features are there *(such as changing wallpaper, volume control etc)*

Anything else should be optional *(to some extent even audio and network should be too)*

**Comment by dagdrommer** [comment]
> These metapackages might have too much in there so could be an upstream packaging issue. Listing out packages individually instead of the metapackage is tricky to get right, though.

The main problem of the metapackage is that it contains multiple other meta-packages such as games, partitionmanager, TEX-Editor etc... I do not see a problem with listing two or three packages instead of a bloated meta package.

> I honestly welcome any PR's for slimming these down to keep things simple, as long as:
> 
>     * The default terminal works
> 
>     * The user have a browser _(or way of installing one)_
> 
>     * The expected WM features are there _(such as changing wallpaper, volume control etc)_
> 
> 
> Anything else should be optional _(to some extent even audio and network should be too)_

When taking the approach by @Torxed, then I just the kde terminal `konsole` is sufficient instead of the meta package.

**Comment by Torxed** [comment]
> > These metapackages might have too much in there so could be an upstream packaging issue. Listing out packages individually instead of the metapackage is tricky to get right, though.
> 
> The main problem of the metapackage is that it contains multiple other meta-packages such as games, partitionmanager, TEX-Editor etc... I do not see a problem with listing two or three packages instead of a bloated meta package.

I agree, and I can put up a reoccuring action to check in on the meta package every now and then to see if they gotten saner defaults.

> > I honestly welcome any PR's for slimming these down to keep things simple, as long as:
> > ```
> > * The default terminal works
> > 
> > * The user have a browser _(or way of installing one)_
> > 
> > * The expected WM features are there _(such as changing wallpaper, volume control etc)_
> > ```
> > 
> > 
> > Anything else should be optional _(to some extent even audio and network should be too)_
> 
> When taking the approach by @Torxed, then I just the kde terminal `konsole` is sufficient instead of the meta package.

I mean my approach is not that of a messiah or spaghetti monster, I think your list above looks more useable. My "demands" are only those of the absolute bare minimum heh.

**Comment by dagdrommer** [comment]
>  mean my approach is not that of a messiah or spaghetti monster, I think your list above looks more useable. My "demands" are only those of the absolute bare minimum heh.

> Btw, I really do enjoy these healthy discussions. Buts a lot of perspective on it and I'm happy that you all chime in! It's fun :D

If I was a arch beginner choosing KDE, I would be happy about a terminal, a filemanager and a texteditor (the three listed packages above). Everything else I can pick for myself later. 

Yes, I also enjoy the discussion. :)

**Comment by dylanmtaylor** [comment]
> > mean my approach is not that of a messiah or spaghetti monster, I think your list above looks more useable. My "demands" are only those of the absolute bare minimum heh.
> 
> > Btw, I really do enjoy these healthy discussions. Buts a lot of perspective on it and I'm happy that you all chime in! It's fun :D
> 
> If I was a arch beginner choosing KDE, I would be happy about a terminal, a filemanager and a texteditor (the three listed packages above). Everything else I can pick for myself later.
> 
> Yes, I also enjoy the discussion. :)

Let's merge in @advaithm's PR and then make this change, so it's not too messy to follow the history.

Can we replace kde-applications-meta with the following useful packages: 

konsole kate dolphin ksystemlog khelpcenter 

and optionally, konqueror

**Comment by Torxed** [comment]
On it, running a test now (but takes time because of the additional packages, ironically) ^^

**Comment by dagdrommer** [comment]
...work is getting done here. Love it!

**Comment by Torxed** [comment]
Added a return value in b968bec which seams to pass all tests.
The PR still asks the user if wayland should be default, I still think detecting and auto-configuring a sane default is more future proof and less intrusive, must not forget to circle back to this.

**Comment by dylanmtaylor** [comment]
> Added a return value in [b968bec](https://github.com/archlinux/archinstall/commit/b968bec77182b215c8786ac22b794c8440f46df9) which seams to pass all tests.
> The PR still asks the user if wayland should be default, I still think detecting and auto-configuring a sane default is more future proof and less intrusive, must not forget to circle back to this.

Honestly, it was a compromise since it was controversial to have wayland as a default. I liked the idea of using Wayland as default on all but proprietary Nvidia with a choice to enable it on proprietary Nvidia if they wanted, but I think it's good enough and should meet everyone's needs.

**Comment by dylanmtaylor** [comment]
I just made https://github.com/archlinux/archinstall/pull/197 which should implement the solution. If you want konqueror/firefox in there or something, let me know and I can add it.

**Comment by advaithm** [comment]
I think we should add a browser since it's pretty important for a new install

**Comment by dylanmtaylor** [comment]
Which one? Firefox?

**Comment by advaithm** [comment]
I'd prefer Firefox since it supports more modern features and isn't on the edge of being abandonware

**Comment by dylanmtaylor** [comment]
I mean honestly the space savings is huge. On my arch system I tried running pacman on that metapackage and it wants to pull almost 1GB of data and a ton of apps:

Total Download Size:    728.75 MiB
Total Installed Size:  2185.07 MiB

I'll add firefox.

**Comment by dylanmtaylor** [comment]
https://github.com/archlinux/archinstall/pull/198/files 

And when that is merged, I imagine this issue can be closed :)

**Comment by dylanmtaylor** [comment]
Also, when is the 2.2.0 branch going to be merged to master, @Torxed ?

**Comment by Torxed** [comment]
I saw @advaithm has a [PR on their fork](https://github.com/advaithm/archinstall/pull/1) which also addresses some of this.
Is this something we should bring in?

Oh, humm.. \*grinding gears*.
Do we really wanna pick Firefox for the users? Or should we stick with whatever the KDE people descide so we redirect the browser war on to them? 🗳️

**Comment by Torxed** [comment]
> Also, when is the 2.2.0 branch going to be merged to master, @Torxed ?

Right after v2.1.4 and after the next ISO release, so minimum a month away I'd say.
Focus is still on patch release to fix some of the issues that has been reported over the last couple of days.

**Comment by dylanmtaylor** [comment]
I mean honestly I don't care what browser ships with the OS by default. I do know that chromium is controversial to people that hate Google ;) The PR you linked to is basically already included in the one that just got merged for the combining wayland and xorg.

**Comment by dylanmtaylor** [comment]
> > Also, when is the 2.2.0 branch going to be merged to master, @Torxed ?
> 
> Right after v2.1.4 and after the next ISO release, so minimum a month away I'd say.
> Focus is still on patch release to fix some of the issues that has been reported over the last couple of days.

That's kind of disappointingly slow. Many of these changes are huge quality of life improvements, and not merging them in makes trunk-based development harder since PRs tend to be against master.

**Comment by advaithm** [comment]
Konquer and Falkon the 2 browsers in the kde ecosystem are really not great. They are pretty much on the edge of being unmaintained. I think we could just print something telling the user they should chose a browser and add it too additional packages.

**Comment by Torxed** [comment]
> > > Also, when is the 2.2.0 branch going to be merged to master, @Torxed ?
> > 
> > 
> > Right after v2.1.4 and after the next ISO release, so minimum a month away I'd say.
> > Focus is still on patch release to fix some of the issues that has been reported over the last couple of days.
> 
> That's kind of disappointingly slow. Many of these changes are huge quality of life improvements, and not merging them in makes trunk-based development harder since PRs tend to be against master.

I'm aware. This is most likely a one time off in terms of slow pace.
This is the first ever test in the wild for this little project, and a lot of peoples mind are set on this failing.
So for the sake of the long game, the next version will mainly focus on stability.. Just so we don't feed the fire that is the internet.

**Comment by dylanmtaylor** [comment]
> Konquer and Falkon the 2 browsers in the kde ecosystem are really not great. They are pretty much on the edge of being unmaintained. I think we could just print something telling the user they should chose a browser and add it too additional packages.

I mean we could do that and install a browser of the user's choice for each DE... or just leave the install without one and let them handle that. I personally don't mind typing pacman -S firefox on a new install.

**Comment by Torxed** [comment]
> > Konquer and Falkon the 2 browsers in the kde ecosystem are really not great. They are pretty much on the edge of being unmaintained. I think we could just print something telling the user they should chose a browser and add it too additional packages.
> 
> I mean we could do that and install a browser of the user's choice for each DE... or just leave the install without one and let them handle that. I personally don't mind typing pacman -S firefox on a new install.

Could work, I believe that's more in line with the principle of "keep it simple, don't force things, let people decide" philosophy :)

**Comment by advaithm** [comment]
Yeah i think we can output a line about installing a browser after the installation process since it's a very controversial topic

**Comment by dylanmtaylor** [comment]
"If you would like a web browser, you can install one after installation using pacman -S [browser]"?

**Comment by dylanmtaylor** [comment]
For consistency we should remove chromium from the awesome DE then.

**Comment by advaithm** [comment]
I don't think we have to tell the user how to install the browser.

**Comment by Torxed** [comment]
> "If you would like a web browser, you can install one after installation using pacman -S [browser]"?

If we add it before additional packages, they can have the option to add it there for a more complete experience.

**Comment by Torxed** [comment]
> For consistency we should remove chromium from the awesome DE then.

Why did I have to open my bloody mouth haha.
Oh well, I have to agree and finally realize I'm not the only one using this anymore ^^

**Comment by dylanmtaylor** [comment]
Oh, good point. Maybe mention that they can just type the web browser name in during the next prompt.

**Comment by Torxed** [comment]
> Oh, good point. Maybe mention that they can just type the web browser name in during the next prompt.

```
Write additional packages to install, such as a browser or text editors (space separated, leave blank to skip): 
```

**Comment by advaithm** [comment]
> Oh, good point. Maybe mention that they can just type the web browser name in during the next prompt.

I think it would be simpler to say we do not install a browser by default. If you wish to have one add it in additional packages

**Comment by dylanmtaylor** [comment]
> > For consistency we should remove chromium from the awesome DE then.
> 
> Why did I have to open my bloody mouth haha.
> Oh well, I have to agree and finally realize I'm not the only one using this anymore ^^

https://github.com/archlinux/archinstall/pull/199 is ready for your review.

**Comment by dagdrommer** [comment]
> I mean honestly the space savings is huge. On my arch system I tried running pacman on that metapackage and it wants to pull almost 1GB of data and a ton of apps:
> 
> Total Download Size: 728.75 MiB
> Total Installed Size: 2185.07 MiB
> 
> I'll add firefox.

I would also go with firefox, if we want to add a browser.

**Comment by Torxed** [comment]
Not to kill the mood, but did #197 close this? :)

**Comment by Anonymo** [comment]
> Not to kill the mood, but did #197 close this? :)
> Or do we want anything additional from `dolphin-plugins, kcalc, yakuake, kio, kio-extras, kfind, okular, ksystemlog, ksysguard, khotkeys, kdegraphics-thumbnailers, gwenview, kimageformats, qt5-imageformats`?

that looks like a good selection.

**Comment by dagdrommer** [comment]
> Not to kill the mood, but did #197 close this? :)
> Or do we want anything additional from `dolphin-plugins, kcalc, yakuake, kio, kio-extras, kfind, okular, ksystemlog, ksysguard, khotkeys, kdegraphics-thumbnailers, gwenview, kimageformats, qt5-imageformats`?

Yes, for me it is closed with #197. I don't think the other packages are necessary, they would just add to a more complete kde experience.
To the browser discussion once more. Imo people don't need a browser from min 1, as the personal preferences can be very different here. But I also think that the khelpcenter isn't  necessary, as it just reads the journalctl.

Sorry for discussing every little package in detail :D

**Comment by Torxed** [comment]
> > Not to kill the mood, but did #197 close this? :)
> > Or do we want anything additional from `dolphin-plugins, kcalc, yakuake, kio, kio-extras, kfind, okular, ksystemlog, ksysguard, khotkeys, kdegraphics-thumbnailers, gwenview, kimageformats, qt5-imageformats`?
> 
> Yes, for me it is closed with #197. I don't think the other packages are necessary, they would just add to a more complete kde experience.
> To the browser discussion once more. Imo people don't need a browser from min 1, as the personal preferences can be very different here. But I also think that the khelpcenter isn't necessary, as it just reads the journalctl.
> 
> Sorry for discussing every little package in detail :D

It's a healthy discussion and it ensures that one person (me) don't add the wrong kind of stuff.
Ultimately the verdict will be general population, but the more healthy stuff we discuss here - the less hate will rain down on me..

I agree, unless specified in "additional packages", there's no need for a browser from the first get go.

If any additional packages are needed from the list, feel free to submit a PR and we can continue discussions there I think.
As for making KDE more minimal, I think we achieved it :)

**Comment by dylanmtaylor** [comment]
I mean honestly, this just removed over 1GB from the install, so that's a huge win. Users can install those things if they want it. We can have holy wars about browsers/what apps go in all day, or just go with the bare minimum and let users do what they want :)

**Comment by dagdrommer** [comment]
> I mean honestly, this just removed over 1GB from the install, so that's a huge win. Users can install those things if they want it. We can have holy wars about browsers/what apps go in all day, or just go with the bare minimum and let users do what they want :)

I think so too...I see the installer as a good helper for people being confident with Linux and trying out Arch, or Arch users, who want to quickly install a new, minimal and configurable system. Everyone using this installer knows some basics about a terminal and know how to install additional applications.
