### ISSUE TITLE
btrfs manual partitioning 'could not set compress attribute at @home'

### ISSUE THREAD

**Issue by VRof** [archlinux/archinstall#1974]
archinstall 2.6.0 from the newest arch iso

[my config file](https://0x0.st/H2Wn.json)

![Screenshot_1](https://github.com/archlinux/archinstall/assets/101021359/29deae7f-0b9d-4d1b-ad3d-bbff4126ffd3)

**Comment by lavafroth** [comment]
This appears related to the `nodatacow` attribute set to true for `@home`. The [BTRFS docs](https://btrfs.readthedocs.io/en/latest/btrfs-man5.html#btrfs-specific-mount-options) states,
> Nodatacow implies nodatasum, and disables compression

In the configuration file you have shared, the `nodatacow` attribute conflicts with the `compress=zstd` mount option. I think the installer should check the `nodatacow` flag and only enable compression when it is false.

**Comment by lavafroth** [comment]
I have been able to reproduce this issue, I think the script is supposed to have `compress` and `nodatacow` for a `btrfs` subvolume as mutually exclusive. For the time being, you would have to choose either of the flags but not both during manual partitioning.

**Comment by svartkanin** [comment]
The fix was merged
