### ISSUE TITLE
Boot loader installation fails: "Can not find block device: /dev/nvme0n1p1"

### ISSUE THREAD

**Issue by Bydo-Spore** [archlinux/archinstall#1985]
I've attempted installation several times with both automatic and manual partitioning. This failure happens every time, irrespective of which boot loader is chosen or any other options.

There's nothing wrong with the computer; I had Manjaro installed on it 3 years ago, and the computer hasn't been changed since.

`install.log` is attached.
[install.log](https://github.com/archlinux/archinstall/files/12267541/install.log)

**Comment by Torxed** [comment]
Could you take a screenshot of the stack trace as well?
Maybe this is a Python thing.

**Comment by Bydo-Spore** [comment]
The USB drive was being booted in 'Legacy boot' mode. I changed it to boot in 'UEFI boot' mode and it installed properly

I tested it by installing it again but it wouldn't install again. There's another problem that I will post separately.

**Comment by linuts** [comment]
I did also have this happen with both a vda1 and sda1 mount points. I was using BIOS boot, not UEFI.
