### ISSUE TITLE
Archinstall stuck in "waiting for time sync"

### ISSUE THREAD

**Issue by lxbx44** [archlinux/archinstall#1987]
I've tried multiple times to install arch but the installation just gets stuck showing this:

![IMG_20230805_192407.jpg](https://github.com/archlinux/archinstall/assets/90387298/c23235c9-0c64-42ea-8ac5-358a374c293f)

**Comment by horror-proton** [comment]
try switching to another tty and run `systemctl start systemd-timesyncd.service`

**Comment by Torxed** [comment]
Most likely the timesync timed out waiting for a network connection, and while the above might work you might have to do `systemctl restart systemd-timesyncd.service` since it should already be started.

**Comment by MyMeepSQL** [comment]
For me, I opened the `/etc/systemd/timesyncd.conf` file and add a NTP server right to the `ntp` settings under `[Time]`. Restart the service (`systemctl restart systemd-timesyncd.service`) and then the the install with archinstall

**Comment by sugeodj** [comment]
I've got the same issue here, anyone found a fix yet?

**Comment by lxbx44** [comment]
> I've got the same issue here, anyone found a fix yet?

< Noup, I've moved to Fedora, its way more stable (i miss saying 'I use arch btw' :3)

**Comment by darkyzhou** [comment]
Same here, why does archinstall have to do time synchronization? Seeing it hanging for a couple of minutes really makes me feeling stupid. It this what 'I use arch btw' means in 2023?

**Comment by sugeodj** [comment]
Have a look at my archmininstall repo on my page, I wrote the script a few months back to automate a minimal install that you could attain using the official archinstall script that is currently broken. I haven't utilised it in the recent months however I have faith that it will still work.

**Comment by Torxed** [comment]
> the official archinstall script that is currently broken

This is quite a statement, in what way is it broken?

> why does archinstall have to do time synchronization?

It's actually a dependency to get everything post-boot work.
Any kind of package retrieval **requires** your time to be no more than a few seconds off due to HTTPS calls.

This would answer the *why* in your question :)

> And why does it just stuck there when the action takes too much time to complete?

The reason being time sync is attempted quickly during boot, and it doesn't necessarily wait for network to be available. When that fails, the restart on the time sync service appears to be wonky - or we're not using optimal checks.

We've been bouncing ideas internally about what the best approach forward would be, as there's other ways of checking of time is synced without relying on the service.

**Comment by sugeodj** [comment]
As i wrote a script which practically does the same as the minimal install, i am aware of each command needed to manually setup an archinstall yourself, this is a clear issue with this repos archinstall script, the time sync is broken for numeous users however when using my own scirpt, it does not hang at a time synchonisation and sets the time value manually itself after logging into the mounted drive.

**Comment by mcMineyC** [comment]
I got it to work by editing /etc/systemd/time syncs.conf and uncommenting FallbackNTP.

**Comment by mcMineyC** [comment]
I got it to work by editing /etc/systemd/time syncs.conf and uncommenting FallbackNTP.  Why is it commented out in the first place?

**Comment by MaanAlaulaqi** [comment]
if anyone runs into the same issue, one way would be to just (temporarily) disable the checker that checks if NTP is synced in installer.py, but it goes without needing to say you’ll take responsibility for your actions and ensure your stuff is synced 

(commenting it out worked for me)
