### ISSUE TITLE
Installation fails: "error: unresolvable package conflicts detected"

### ISSUE THREAD

**Issue by Bydo-Spore** [archlinux/archinstall#1989]
Not caused by additional packages I'm installing. I only requested `kwin`, `conky` and `xcursor-vanilla-dmz`.

Bottom of `install.log` (attached) shows:
```

resolving dependencies...
looking for conflicting packages...
:: wireplumber and pipewire-media-session are in conflict. Remove pipewire-media-session? [y/N] 
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: wireplumber and pipewire-media-session are in conflict
[?25h==> ERROR: Failed to install packages to new root
```

[install.log](https://github.com/archlinux/archinstall/files/12267924/install.log)

**Comment by FigmentEntity** [comment]
You can temporarily work around this issue by selecting no audio drivers during installation. no pulse audio no pipewire, do it after installation

**Comment by fabianmuehlberger** [comment]
Duplicate of #1973
