### ISSUE TITLE
archinstall formats the existing partition though i didn't marked it for formatting

### ISSUE THREAD

**Issue by darkblaze69** [archlinux/archinstall#1992]
latest 20230801.

archinstall formats the existing partition though I didn't marked it for formatting.

It should indicate in the table what it's going to format.

In my case it was sdb4, see on screenshots:

![PXL_20230806_173402843](https://github.com/archlinux/archinstall/assets/6976920/5bad9d3e-3398-4f8b-a0d2-3b601c541110)

![PXL_20230806_173536445_](https://github.com/archlinux/archinstall/assets/6976920/f668b45b-a223-4e47-bc25-007276a3d97f)

**Comment by svartkanin** [comment]
Could you share the log file as well under /var/log/archinstall/install.log

Even if you didn't mark it as formatting did you do any other modifications to it? E.g. extend/shrink the size?

**Comment by darkblaze69** [comment]
Well, I tried again with logs.

1. I had some partitions and a last partiton not to be touched.
2. Chosen manual formatting.
3. Removed all first partitions except the last one.
4. Created partitions for /boot and / with subvolumes.
5. Didn't touch the last partition vda4.

And it wiped vda4 again. Here's logs.

[arch-install.log.zip](https://github.com/archlinux/archinstall/files/12311113/arch-install.log.zip)

**Comment by fabianmuehlberger** [comment]
The problem seems to be here, it fails to unmount and format vda3.

``` Unmounting: /dev/vda3
Error calling lsblk: lsblk: /dev/vda3: not a block device
{
   "blockdevices": [
   ]
}
```

``` Unmounting: /dev/vda4
Formatting filesystem: /usr/bin/mkfs.fat -F32 /dev/vda1
Formatting filesystem: /usr/bin/mkfs.ext4 -F /dev/vda2
Formatting filesystem: /usr/bin/mkfs.ext4 -F /dev/vda3
Could not format /dev/vda3 with ext4: ['/usr/bin/mkfs.ext4', '-F', '/dev/vda3'] exited with abnormal exit code [1]: mke2fs 1.47.0 (5-Feb-2023)
The file /dev/vda3 does not exist and no size was specified.

Virtualization detected: kvm; is VM: True ```
