### ISSUE TITLE
ERROR: Failed to install package for new root

### ISSUE THREAD

**Issue by Zhan-Here** [archlinux/archinstall#1995]
If you can speak Chinese, please!
These are my config. The last one is ERROR message.
https://img1.imgtp.com/2023/08/07/SbplRAX6.png
https://img1.imgtp.com/2023/08/07/Rml10gEG.png
https://img1.imgtp.com/2023/08/07/TZlRFw8n.png
https://img1.imgtp.com/2023/08/07/fQPHmhbF.png
https://img1.imgtp.com/2023/08/07/6T0YuJY1.png
https://img1.imgtp.com/2023/08/07/IzyRWdem.png
I don't know how to upload image on github.

**Comment by svartkanin** [comment]
This has been resolved and a fix was merged
