### ISSUE TITLE
Archinstall error "pipewire-jack and jack2 are in conflict" (with log)

### ISSUE THREAD

**Issue by Timortifus** [archlinux/archinstall#1996]
I have basically the same error as #1973 and #1995, but I wanted to add the install log because I thought that it might be useful.

[install.log](https://github.com/archlinux/archinstall/files/12285039/install.log)

**Comment by xavier-valter** [comment]
Estou com o mesmo prlema ,não consigo instalt pelo script.

**Comment by kacperwyczawski** [comment]
I have the same problem

**Comment by Timortifus** [comment]
You can just install the system without configuring the audio and then install it afterwards.

**Comment by xavier-valter** [comment]
Fiz conforme fui orientado , não instalei o audio , deu tudo certo inclusive o particionamento. obrigado.

**Comment by C0rn3j** [comment]
> I have basically the same error as X a but I wanted to add the install log

Please close this issue and add your log to the existing original issue then.

**Comment by svartkanin** [comment]
@C0rn3j agreed, opening new issues for the same problem doesn't speed things up but just distributes the information
