### ISSUE TITLE
EFI system partition can't be mounted at /efi

### ISSUE THREAD

**Issue by aki-k** [archlinux/archinstall#2001]
If I create a partition setup as follows:

partition 1: esp fat32 mounted at /efi
partition 2: btrfs with three subvs:
arch_boot mounted at /boot
arch_root mounted at /
arch_home mounted at /home

Then select grub as boot loader; the installation starts, but fails spectacularly when it's installing grub. If I change the esp mount point to /boot, the installation succeeds.

https://wiki.archlinux.org/title/EFI_system_partition

4.1 Typical mount points

- mount the ESP to /boot

- mount the ESP to /efi

**Comment by Weissnix4711** [comment]
[This line in installer.py](https://github.com/archlinux/archinstall/blob/master/archinstall/lib/installer.py#L908) is the culprit.

On efi systems with a different ESP mountpoint (other than `/boot`), it will attempt to use the `boot_partition` mountpoint (`/efi`) as the prefix directory.

**Comment by roboboredom** [comment]
Same issue. Commenting for bump.
