### ISSUE TITLE
archinstall sets wrong uuid in /etc/default/grub (current arch iso, latest stable archinstall) 2023-08-01

### ISSUE THREAD

**Issue by khang33k** [archlinux/archinstall#2006]
Encrypted install with automatic btrfs partitioning layout. 
Archinstall sets wrong uuid in the "GRUB_CMDLINE_LINUX" in /etc/default/grub
Have to manually set the correct uuid for the system to boot after installation.

**Comment by MyMeepSQL** [comment]
A shell open up after choising Arch Linux in Grub and say that i'm now in a emergency shell. Because the device was not found.

Can you help me too? How did you change de UUID with the correct one?

**Comment by dedroot** [comment]
I was able to boot just by puting the real name of the disk (/dev/<you_luks_disk>) and not with the UUID

**Comment by reklis** [comment]
Specifically it's the wrong `cryptdevice` value. I had to change the cryptdevice UUID value to the value from `blkid` in my grub.cfg then grub prompts for a password and mounts the encrypted volume

**Comment by Torxed** [comment]
I believe we've recently reworked the grub installer dealing with this thing: https://github.com/archlinux/archinstall/blob/b1e00687953de168bbc31ea435b2c5bdc7c61e39/archinstall/lib/installer.py#L870-L874

But it's looked the same way for quite a whilte: https://github.com/archlinux/archinstall/blob/57ebc42ffd64babb121c940caa3c5ff415062162/archinstall/lib/installer.py#L907

@svartkanin Perhaps we changed the behavior of `root_partition.uuid`?

**Comment by svartkanin** [comment]
This is the last major change to this part of the code https://github.com/archlinux/archinstall/pull/1962/files
Can't say though if it introduced the bug or not

**Comment by Torxed** [comment]
Nah, it still uses the `root_partition.uuid` variable. Doubt it's the logic there.

**Comment by Torxed** [comment]
Is it a case of https://github.com/archlinux/archinstall/blob/b1e00687953de168bbc31ea435b2c5bdc7c61e39/archinstall/lib/disk/device_model.py#L631 not being updated? Once we format a new filesystem on it, the UUID will most likely change.

**Comment by svartkanin** [comment]
But it did remove the `rootfstype={root_partition.safe_fs_type.value}` part, not sure if that will have an impact

**Comment by Torxed** [comment]
Ah yea, but it gets added a bit later: https://github.com/codefiles/archinstall/blob/6f3ceea9eea2ce2baaeca1a5ec91d73272e890e5/archinstall/lib/installer.py#L830

The rework was to separate the logic of appending options a bit.

**Comment by svartkanin** [comment]
Ahh right, missed that. 
For the UUID, we run a `partprobe` just after the creation https://github.com/svartkanin/archinstall/blob/47cde37edc1caf601225ae1ffdc6ac326039c9dd/archinstall/lib/disk/device_handler.py#L358-L358 which "should" update it?

**Comment by codefiles** [comment]
I got this figured out and am working on a fix. About to update this comment with more information.

**Comment by Torxed** [comment]
Well spotted @codefiles! I'm rounding up for a release in the next couple of days and this is probably one of the last few that really needs to go in :D

**Comment by Torxed** [comment]
This should now be corrected thanks to #2077
