### ISSUE TITLE
Spelling Issue in the profiles section for hyprland

### ISSUE THREAD

**Issue by wiillou** [archlinux/archinstall#2007]
https://github.com/archlinux/archinstall/blob/master/archinstall/default_profiles/desktops/hyperland.py

the compositor should be referred to as 'hyprland' (without the 'e') as the package name and actual project are always referred to as 'hyprland'.

https://hyprland.org/

**Comment by wiillou** [comment]
![RDT_20230811_2015416852549950976214041.jpg](https://github.com/archlinux/archinstall/assets/127661559/80396a63-c7dd-40ee-9535-93fcc44ae45c)

**Comment by hyper-dot** [comment]
They got a bit hyper 😂

**Comment by TheChuckster** [comment]
Added a PR

**Comment by ShalokShalom** [comment]
I thought Hyperland is a pure WM?

**Comment by wiillou** [comment]
> I thought Hyperland is a pure WM?

Yup, it's a compositing window manager

**Comment by Xag8031** [comment]
> I thought Hyperland is a pure WM?

Yes, but this installs hyprland. A wm running on Wayland

**Comment by ShalokShalom** [comment]
The screenshot says Desktop Environment.

**Comment by TheChuckster** [comment]
Several of the others listed are also pure WMs, and arguing about those separate semantics is out of scope for this issue.

**Comment by Torxed** [comment]
#1824 will correct this, as well as a seat issue. Apologies for the delay in renaming this.
