### ISSUE TITLE
Maybe there is a bug of grub-install in archinstall

### ISSUE THREAD

**Issue by FTS427** [archlinux/archinstall#2008]
![image](https://github.com/archlinux/archinstall/assets/122330825/2decfff6-fbdb-4aa7-8a54-50ab43df2b91)
What happened?
This bug appaers on my computer and my friend computer.
I think this is an important thing
I think grub-install should be
"grub-install /dev/sda"
not
"grub-install /dev/sdaX"

(I'm sorry that my English is not good. I'm a chinese)

**Comment by RosGtHub** [comment]
are you trying to install it on a vm?

**Comment by FTS427** [comment]
> are you trying to install it on a vm?

Yes, we're

**Comment by FTS427** [comment]
So this problem is because I downloaded a wrong image?

**Comment by NextStep-IM** [comment]
Same problem here. I am trying to install it on VM. Just in case this is relevant, when I  tried installing Arch on my PC pipewire-jack and jack2 were in conflict and this messed up my installation.

**Comment by RosGtHub** [comment]
For the first issue, try enabling EFI. For the second one, navigate to /etc/pacman.conf and change #IgnorePKG = to IgnorePKG = jack2
