### ISSUE TITLE
Allow assign mount point without wiping partition

### ISSUE THREAD

**Issue by f73** [archlinux/archinstall#2009]
Hello, 
This was an option in previous version of archinstall - to mount a partition without the need to format it - for example, separate `/home` partition that has data from previous install. In this version this is not available, or maybe I am missing something?! There is an option "mark/unmark" partition for formating, but its one way only, you can't toggle it. Only after you "mark" partition for formating, there is new menu with "assign mount point"...

**Comment by ccolorado** [comment]
This would be awesome, I dont think formatting my ssd 10 times is good for it. (Realizing a misconfiguration or the script failing)

**Comment by svartkanin** [comment]
I think this is a regression, I'll have a look at it
