### ISSUE TITLE
Unable to find block device /dev/sda1 !

### ISSUE THREAD

**Issue by mnu9** [archlinux/archinstall#2013]
What the hell, the fifth time the system was reinstalled

![image](https://github.com/archlinux/archinstall/assets/91161592/1dfa4761-b118-4bc7-bbfe-5bdb153672bb)

**Comment by n1ckisthereu** [comment]
I'm facing the same problem, still no solution here...

**Comment by fabianmuehlberger** [comment]
What options did you choose in the installer? 
Can you make a gist of the log?

**Comment by fabianmuehlberger** [comment]
Looks like the same issue as #1971 and should be merged if it is.

**Comment by paulkre** [comment]
Same issue here :(

**Comment by paulkre** [comment]
I could solve this problem by booting in EFI mode.

**Comment by frozen905** [comment]
Same issue here, cannot install arch using archinstall.  Latest version of Arch.

**Comment by deyuva** [comment]
I have the same issue with version 2023.08.01-x86_64.

Version 2023.07.01-x86_64 archinstall works fine.

**Comment by svartkanin** [comment]
This seems to be something related to Grub bootloader, I'll have a look

**Comment by Stealth1993** [comment]
I am getting the same error archlinux-2023.09.01-x86_64

<img width="438" alt="ArchLinux_error" src="https://github.com/archlinux/archinstall/assets/76648814/039c9f22-5f14-4f2b-9fa7-c8958660fe99">
