### ISSUE TITLE
Archinstall fails with pre-mounted partitions

### ISSUE THREAD

**Issue by TheoSmith0308** [archlinux/archinstall#2014]
Previously when I installed with the script on pre-mounted partitions using btrfs it worked great.

With the August 2023 release it does not work anymore. It bugs out when it reaches the grub or systemd boot install stage. Does not matter which bootloader you choose.

Ps! I am doing everything right as per Torxed's previous instructions. It worked great until August release.

mkdir /mnt/archinstall
mount /dev/vda2 /mnt/archinstall
cd /mnt/archinstall
btrfs su cr @
btrfs su cr @home
btrfs su cr @log
btrfs su cr @pkg
cd
umount /mnt/archinstall
mount -o noatime,space_cache=v2,compress=zstd,ssd,discard=async,subvol=@ /dev/vda2 /mnt/archinstall
mkdir -p /mnt/archinstall/{boot/efi,home,var/log,var/cache/pacman/pkg}
mount -o noatime,space_cache=v2,compress=zstd,ssd,discard=async,subvol=@home /dev/vda2 /mnt/archinstall/home
mount -o noatime,space_cache=v2,compress=zstd,ssd,discard=async,subvol=@log /dev/vda2 /mnt/archinstall/var/log
mount -o noatime,space_cache=v2,compress=zstd,ssd,discard=async,subvol=@pkg /dev/vda2 /mnt/archinstall/var/log/pacman/pkg
mount /dev/vda1 /mnt/archinstall/boot/efi
I then run archinstall and under disk setup I choose pre-mounted and enter /mnt/archinstall
In the above case I choose grub as bootloader.

What am I doing wrong my here. I currently reinstalled the old way.

**Comment by fabianmuehlberger** [comment]
Can you share a log of the installation? what do you mean by "pre-mounted partitions" ? do you mean you already have a partition table and disk layout ?

**Comment by svartkanin** [comment]
@TheoSmith0308 we recently merged a fix for a bug in the bootloader https://github.com/archlinux/archinstall/pull/2032, this could be related but it's difficult to say without any error message or log file. 
If you could provide the `/var/log/archinstall/install.log` that'd be very helpful

**Comment by codefiles** [comment]
Fixed in #2143
