### ISSUE TITLE
Throws error when using manual partitioning 

### ISSUE THREAD

**Issue by inmymum** [archlinux/archinstall#2016]
I dual boot windows and arch, having to need windows for genshin impact. Anyways today I booted up my xfce install and the panel was broken. So I booted up the arch iso and ran 
```shell
archinstall
``` 
Here is my config:
```shell
 Archinstall lang     English
 Mirrors              Defined 
 Locales              Defined
 Disk configuration   Manual Partitioning 
 Disk encryption
 Bootloader           Systemd-boot
 Swap                 True
 Hostname             archlinux
 Root password
 User account         1 User(s)
 Profiles             Desktop
 Sound server         Pulseaudio
 Kernels              linux-zen
 Additional packages
 Network config       use NetworkManager
 Timezone             UTC
 Optional repositories
``` 

Under manual partitioning I formatted the boot, root and home partitions. I then assigned the mountpoints as follows:
 sda1: /boot 
 sda2: /
 sda3: /home

I attempted to install it and I get this error almost right away:
ValueError: Filesystem must be set for modification

The problem is I did that already in manual partitioning.
Version 2.6.0 of archinstall

**Comment by fabianmuehlberger** [comment]
What does the `lsblk` command say? 
Have you tried using a default partitioning, best effort scheme?

**Comment by inmymum** [comment]
I do not have access to the computer currently, but I will update in a few days. The default partitioning works, but like I said I have windows with a large game installed and that will delete the windows partitions.

**Comment by fabianmuehlberger** [comment]
Looks like the same issue as #1971 and should be merged if it is.

**Comment by inmymum** [comment]
This fix did not work. I ended up backing up genshin to a hard drive and wiped windows. Still quite annoying as this wasted about an hour of time

**Comment by fabianmuehlberger** [comment]
Do you get the same error when you use a suggested layout? 
you can also store the install config file. I would suggest storing it and inspect it. Maybe you can find a problem with your disk layout

**Comment by inmymum** [comment]
No, I don't get the error when using suggested layout. Also I did not see that there was a similar issue report. I've never really used GitHub issues, can you explain how to merge it

**Comment by iver0** [comment]
Same issue here, I'm tryin to dual-boot with Windows and it throws that error. Before this I've tried installing Arch on a VM - I didn't get this error when using a suggested layout and wiping the virtual disk, so that's definitely a problem specifically with manual partitioning.

**Comment by fabianmuehlberger** [comment]
In that case, the config file would be very helpful to investigate

**Comment by Baturax** [comment]
İ am having the same issue. While using suggested partition there is no problem. But using manuel i get error. İ am trying dual boot.

**Comment by inmymum** [comment]
I also forgot to mention that this was not an issue in previous versions of archinstall. Because the day before I attempted to reinstall, I had installed arch using archinstall with no issues. Clearly an update messed it up.

**Comment by Baturax** [comment]
> I also forgot to mention that this was not an issue in previous versions of archinstall. Because the day before I attempted to reinstall, I had installed arch using archinstall with no issues. Clearly an update messed it up. 

Did you do it dual boot? İ still cannot install dual boot.

**Comment by inmymum** [comment]
Yes I did.

**Comment by svartkanin** [comment]
@inmymum sorry for the late reply, but if you still have the log file that would help immensely with the debugging. After you get the error could you share the file `/var/log/archinstall/install.log`

**Comment by WoltEye** [comment]
> @inmymum sorry for the late reply, but if you still have the log file that would help immensely with the debugging. After you get the error could you share the file `/var/log/archinstall/install.log`

Im having the exact same problem this my log file
[install.log](https://github.com/archlinux/archinstall/files/12467400/install.log)

**Comment by iver0** [comment]
Yeah, still present in September .iso, gotta use the July one for manual partitioning and dual booting for now.

**Comment by svartkanin** [comment]
As you can see above I've raised a fixPR which hasn't been merged yet. You can give that a go
