### ISSUE TITLE
archinstall failed /dev/sda1 log attached

### ISSUE THREAD

**Issue by frozen905** [archlinux/archinstall#2019]
Hi there, thanks for help 

https://[0x0.st/HLEM.txt](https://0x0.st/HLEM.txt)

ArchInstall failed and I used the guide to upload the log file.

Log output tells me to create a post here!!!

**Comment by fabianmuehlberger** [comment]
Have you checket the other issues for duplicate first? There are already about 5 issues created with the same problem.

please add your issue to:  #1971 

Additionally: It seems you are using a VM? I  think that others also have a problem related to VMs or not using UEFI

**Comment by fabianmuehlberger** [comment]
Duplicate of #1971
