### ISSUE TITLE
Image generation FAILED 'bsdtar (step 1) reported an error'

### ISSUE THREAD

**Issue by Wemmons831** [archlinux/archinstall#2020]
Am I unsure the best way to get the full log file off of my boot usb but I noted down some of the warning that seemed important to the issue.
Possibly missing firmware for module: "xhcl_pct","qed", "wd713x", "qla1280", "qla2xxx", "bfa", "alc94xx"
Also got a write error "cannot write block : Now space left on device". There is definitely free space on the drive.
here is how the drive is partitioned (via the suggested partition layout): 1.95 GB EFI boot partition, 1 MB healthy partition, 18.5 GB healthy partition (/), 911GB healthy partition (/home)

**Comment by svartkanin** [comment]
@Wemmons831 one way of getting the log file extracted is
```
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

**Comment by Torxed** [comment]
I don't think we'll be able to solve this one without the log file.
So I'm going to close it as it feels disk-space related, but we can't say for sure without the log.

I'll re-open if the requested log is submitted. Apologies for the inconvenience!
