### ISSUE TITLE
`custom-commands` fails with no such file or directory

### ISSUE THREAD

**Issue by stephenhouser** [archlinux/archinstall#2025]
When using `-config` and specifying `custom-commands` a `no such file or directory` error is generated as the path to the script is built incorrectly in `lib/general.py`. It appears 2 months ago a refactor was done when this was introduced. The previous code looks fine. The errors introduced include:

- `chroot_path = installation.target / script_path` << not sure how to interpret this line
- `chroot_path.write_text(command)` << there is no such method on strings

**Comment by svartkanin** [comment]
Closing as the fix was merged
