### ISSUE TITLE
Loading saved configs doesn't fully install DEs like GNOME or KDE

### ISSUE THREAD

**Issue by darkblaze69** [archlinux/archinstall#2035]
* archinstall 2.6.0.

Steps:
* selected all the necessary, Profile > Desktop > KDE or GNOME
* save config to files.
* abort install
* run again with options --config user_configuration.json --creds user_credentials.json

If you run like this you will get only minimal DE install without any GNOME/KDE apps like gnome-control-center, console, tweaks etc. Probably you get only dependecies for greeter.

**Comment by svartkanin** [comment]
Thanks for reporting I was able to reproduce this
