### ISSUE TITLE
useradd: group 'wheel' does not exist

### ISSUE THREAD

**Issue by VelogicMusic** [archlinux/archinstall#2040]
I have looked at previous issues, but could not really find some fix here.

The installation fails with
could not create user inside installation: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'useradd', '-m', '-G', 'wheel', 'einsimon']

This is the install log: https://0x0.st/Hfad.log

**Comment by SlumberDemon** [comment]
Getting the same error

**Comment by kyyrsr** [comment]
> Getting the same error

Here also, manual installing is the way currently

**Comment by utsusemioxo** [comment]
getting same error
[install.log](https://github.com/archlinux/archinstall/files/12563649/install.log)

**Comment by shodanwashere** [comment]
came by the same error...

**Comment by mrizla** [comment]
Getting the same error

**Comment by hnsylzg** [comment]
Getting the same error

**Comment by mrizla** [comment]
I figured out a workaround. If you set up **JUST** root and not a user, you can add the user manually after install :) (for lazy people like me that don't want to manually archinstall)

**Comment by alfaroale** [comment]
Is a bug in systemd (254.2-1), check this: https://bugs.archlinux.org/task/79619

**Comment by VelogicMusic** [comment]
I guess this closes this issue as it is not related to the archinstall script itself.

The workaround I used and was already mentioned by @mrizla: Use the archinstall script, but do not setup additional users using the script. Add them afterwards manually (just find some guide online or look at the docs :wink:)

**Comment by utsusemioxo** [comment]
> I guess this closes this issue as it is not related to the archinstall script itself.
> 
> The workaround I used and was already mentioned by @mrizla: Use the archinstall script, but do not setup additional users using the script. Add them afterwards manually (just find some guide online or look at the docs 😉)

You are right, when I try to install manually, I meet this problem again, and I use useradd command to solve.

**Comment by coderxmeta** [comment]
> I guess this closes this issue as it is not related to the archinstall script itself.
> 
> The workaround I used and was already mentioned by @mrizla: Use the archinstall script, but do not setup additional users using the script. Add them afterwards manually (just find some guide online or look at the docs 😉)

Could you share your install config? Im having the same issue in the middle of the installation with root user

**Comment by VelogicMusic** [comment]
What is the error you are getting?
You can find the config in the log provided in the original comment (just search for  `-- Chosen configuration --`)

**Comment by coderxmeta** [comment]
[ 407.940937] bootctl[1]: Failed to get device path for: 8:1: No such device
[ 407.982472] bootctl[1]: Failed to get device path for: 8:1: No such device

[ '/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', ínstall'] exited with abnormal exit code [1]

But now Im reading that is a bug in the systemd Iso so I guess I've to wait for fix

**Comment by VelogicMusic** [comment]
Yes, this should be a systemd related bug I also encountered.
A workaround would be to select grub as boot manager instead of the default systemd one (worked for me :wink:)

**Comment by coderxmeta** [comment]
> Yes, this should be a systemd related bug I also encountered.
> 
> A workaround would be to select grub as boot manager instead of the default systemd one (worked for me :wink:)


Yep i tried grub instead, but after installation it doesnt boot. Im trying to install it on a laptop
