### ISSUE TITLE
smth failed

### ISSUE THREAD

**Issue by oldwizard1010** [archlinux/archinstall#2046]
logs files:
[archiso.log](https://github.com/archlinux/archinstall/files/12565954/archiso.log)
[archiso2.log](https://github.com/archlinux/archinstall/files/12565989/archiso.log)

**Comment by 1995parham** [comment]
I am getting this issue since this morning on every system I tried. I think there is a package upgrade or something else happened.

**Comment by 1995parham** [comment]
@oldwizard1010 I didn't see the second issue (about user creation) can you express how did you see that? I mean, it happened after the bootloader issue, or you did another setting for installation?

**Comment by oldwizard1010** [comment]
@1995parham 
second issue was added a little bit later after second attempt to install, using grub instead of systemd-boot

**Comment by 1995parham** [comment]
You can see #2040 for this I think.

**Comment by VelogicMusic** [comment]
I've had this problem yesterday aswell. Seems like there is something broken in systemd.
See #2040 (I used grub and did not create an useraccount via the script, but only the root account. You then have to add your useraccount later aswell)
Apart from that you can fall back to a manual arch installation.

**Comment by 1995parham** [comment]
@VelogicMusic thanks, I think we need to wait for new systemd release :cry:

**Comment by oldwizard1010** [comment]
yep, this helped
https://github.com/archlinux/archinstall/issues/2040

**Comment by alfaroale** [comment]
The problem seems to be actually with arch-chroot. Check comment section in: https://bugs.archlinux.org/task/79619
Using systemd-nspawn instead of arch-chroot solved it. https://wiki.archlinux.org/title/systemd-nspawn
Maybe archinstall should use systemd-nspawn instead of arch-chroot.

**Comment by 1995parham** [comment]
Yeah, but I think the fix will be available sooner that archinstall migration to systemd-nspawn. For now, I am waiting for 254.3 version of systemd to have my systems back :clock1:

**Comment by ret2src** [comment]
I can confirm that systemd 254.3 does indeed fix the recently reported issues. If you're in a hurry and can't wait a few days to install Arch, you can turn on the `testing` repos. Since this is a very dirty hack, you should definitely turn them off after the installation has succeeded, otherwise you're more likely to get broken updates in the future.

To turn on the `testing` repos, edit your `/etc/pacman.conf` (see <https://joshtronic.com/2019/08/19/how-to-install-packages-from-testing-on-arch-linux/>)

**Comment by Zer0Qx** [comment]
while installing archlinux freshly, enabling testing repo, did not resolve the issue. still getting it

**Comment by 1995parham** [comment]
I enable testing repository on ISO and also in the installation environment, everything works as expected.

**Comment by tanjilbs23** [comment]
Everything works as expected.means you successfully installed arch linux on your machine?

**Comment by ret2src** [comment]
> Everything works as expected.means you successfully installed arch linux on your machine?

Yes, fresh install on a wiped disk.

**Comment by 1995parham** [comment]
Yeah, for me, wipes out everything and fresh installation works.

**Comment by tanjilbs23** [comment]
So i tried and it did not work for me. What i did: 

1. Enable wifi
2. Pacman -Syy
3. Enable testing repo for core and extra.
4. Pacman -Syy
5. Archinstall

And boom failed..

Can you please tell me what exact steps you followed? Thanks in advance.![IMG20230910044453.jpg](https://github.com/archlinux/archinstall/assets/99186413/27fa58cc-beaf-42d8-b6a7-5e31a555bb58)

**Comment by tanjilbs23** [comment]
Forgot to mention, also deleted partition using fdisk prior to installation.

**Comment by ret2src** [comment]
@tanjilbs23 

- Boot into Arch ISO from Ventoy USB (GPT, UEFI, Secure Boot)
- Wipe disk with `cfdisk`
- Enable `testing` repos in `/etc/pacman.conf`
- `$ archinstall`
- Single ext4 Partition with recommended layout, LUKS encryption, KDE Desktop, pipewire, German mirrors, Berlin timezone

**Comment by tanjilbs23** [comment]
Tried again. Almost similar to the process you mentioned. I did not disable swap. Used btrfs. Let me try your way

**Comment by tanjilbs23** [comment]
> @tanjilbs23 
> 
> - Boot into Arch ISO from Ventoy USB (GPT, UEFI, Secure Boot)
> - Connect to WiFi using `iwctl`
> - Wipe disk with `cfdisk`
> - Enable `testing` repos in `/etc/pacman.conf`
> - `$ archinstall`
> - Single ext4 Partition with recommended layout, no swap, LUKS encryption, single `sudo` user, KDE Desktop, pipewire, German mirrors, Berlin timezone

Still installing , but i am sure it worked. But i dont know why. The main difference i see.
1. I did not ran pacman -Syy
2. I disabled zram. 
3..i used ext4.
4. I used cfdisk instead fdisk.

The last time systemd version was 254.2 now it showed and installed 254.3. Why?? And how??

**Comment by tanjilbs23** [comment]
Figured out. My mistake was to run : pacman -Syy command.

Other than that all we have to do is enable testing repo in iso ( before install)  and additional repository ( while installing).

The most important part i think is to clear the old partition i guess. 

But for now this is working.

**Comment by insidesources** [comment]
I just installed successfully with all of my normal options, btrfs, encryption, adding an user, using systemd boot

I did what was said in this thread above, enabled core testing in /etc/pacman.conf and selected testing repo during the script installation. Thanks all.

**Comment by insidesources** [comment]
tested without enabling testing repos and installs successfully

**Comment by Fuhrerbaumanki** [comment]
> tested without enabling testing repos and installs successfully

It turns out you just turned it on /etc/pacman.conf repository core testing and was this enough for a successful installation?

**Comment by Fuhrerbaumanki** [comment]
> tested without enabling testing repos and installs successfully

It turns out you just turned it on /etc/pacman.conf repository core testing and was this enough for a successful installation?

**Comment by ret2src** [comment]
> > tested without enabling testing repos and installs successfully
> 
> It turns out you just turned it on /etc/pacman.conf repository core testing and was this enough for a successful installation?

You probably no longer need `testing` as the new systemd version is in the normal repos since yesterday: https://archlinux.org/packages/core/x86_64/systemd/
