### ISSUE TITLE
could not strap in packages error 

### ISSUE THREAD

**Issue by RayenMnif** [archlinux/archinstall#2048]
```
Could not strap in packages: ['/usr/bin/pacstrap', C, etc/pacman.conf", -, mnt/archinstall'. xorg-server', 'xorg-xinit' nesa, libua-intel-driver Intel-media-driver. lkan-intel',noconfirm'3 exited with abnormal exit code [1]: b'--> Creating install root at /mnt/archinstall) Installing pac ages to st/architall1b7251:: Synchronizing package databases...APA corerx1b1F core is up to datex1bKxibl1E extraalblIF extra is up to datmalal commith(IF community is up to datesxib(kx1b11Euarning: mesa-22.2.3-1.0 is up to date- reinstalling\r\nerror: target not found: In

tel-media-drunni725 ERROR: Failed to install packages to neu rootin'
```

by the way i tried those commands before running the archinstall that did solve some errors but not all of them

1. `Ping archlinux.org` just to make sure
2. `timedatectl set-ntp true`
3. i waited for 60s
4. `pacman -Sy archlinux-keyring`
6. `rm -rf /etc/pacman.d/gpg/`
7. `rm -rf .gnupg`
8. `dirmngr</dev/null`
9. `pacman-key --init`
10. `pacman-key --populate`

**Comment by Torxed** [comment]
It looks like the stack trace was cut short or is incomplete.

**Comment by svartkanin** [comment]
as there is no reply and we can't really debug this I'll close it for now
