### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'index'

### ISSUE THREAD

**Issue by qcasey** [archlinux/archinstall#205]
I got this error when typing "gnome" when asked for what profile to install. It is thrown on this line:

https://github.com/archlinux/archinstall/blob/1a09ad7bff5d799180b926df4a3611c8f7a6ea29/archinstall/lib/user_interaction.py#L254

Would a `selected_profile = options[list(options).index(selected_profile)]` solve this one?

~can't copy text from this VM~ just remembered screenshots exist

![Screenshot from 2021-04-06 12-19-58](https://user-images.githubusercontent.com/1429672/113766663-88f52d80-96d2-11eb-9cd7-154f98a487f8.png)

**Comment by dylanmtaylor** [comment]
Instead of typing gnome you should have hit '2'. That said, looking up the index by value on an error might work to recover from a situation where a user inputs the value instead of number.

**Comment by Torxed** [comment]
> Instead of typing gnome you should have hit '2'. That said, looking up the index by value on an error might work to recover from a situation where a user inputs the value instead of number.

Agreed, this option was *meant* to be a number-input, but it should also support by name, so this is a mistake on my end :)

**Comment by qcasey** [comment]
It looks like the line that threw the error already tries to account for this, in the way you said. I think the `list` conversion in my OP might fix :smiley: 

I was using numbers up until that point, but what threw me off was the installer asking for "Enter a pre-programmed profile **name**". Anyway, it's a cool installer, thanks for writing it!

**Comment by Torxed** [comment]
We, and by we I mean me, should really start using [generic_select()](https://github.com/archlinux/archinstall/blob/a8da159f176b6867ccf147780c63ee7c7ba3045b/archinstall/lib/user_interaction.py#L164) which supports both numbers and text-input.

**Comment by dylanmtaylor** [comment]
FYI, this seems to be resolved in master and can probably be closed:

![VirtualBox_arch_11_04_2021_20_41_29](https://user-images.githubusercontent.com/277927/114327264-59955500-9b06-11eb-85b2-690a92c6d988.png)

**Comment by dylanmtaylor** [comment]
Note that this issue persists for the graphics driver selection, and I would rework it in master, but there are substantial changes to this GPU driver selection logic being made in 2.2.0, so it'll probably get fixed in that version :)

**Comment by dylanmtaylor** [comment]
This should be fixed in the latest RC, and 2.2.0 with it's reworked graphics driver selections. Please test the ISO on https://github.com/archlinux/archinstall/releases/tag/v2.1.4-RC2

**Comment by Torxed** [comment]
This was fixed in [v2.1.4](https://github.com/archlinux/archinstall/releases/tag/v2.1.4) *(released yesterday)*. Generally we did a lot of improvements to the selection process and this specific error shouldn't happen anymore. If it does, feel free to poke me and I'll re-open! :)
