### ISSUE TITLE
pipewire-jack and jack2 conflict. Archinstall failed to install and script exit

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#2052]
As title says.

Using archinstall v2.6.0-1 and September iso.

Only way to get around is not to choose pipewire as sound server and then just install pipewire lib32-pipewire wireplumber pipewire-audio etc etc etc in the additional packages

**Comment by yrncollo** [comment]
I am also having the same issue

**Comment by Torxed** [comment]
It's being fixed in PR https://github.com/archlinux/archinstall/pull/2030
