### ISSUE TITLE
Hyprland desktop profile with nvidia. No nvidia packages installed

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#2053]
Ive chose hyprland desktop profile with nvidia proprietary drivers.

Upon booting, no nvidia packages installed.

**Comment by Torxed** [comment]
Closing as I think it's a duplicate of #2002

**Comment by ThijsGaming** [comment]
doesn't it also need hyprland-nvidia instead of hyprland
or are you on a laptop?

**Comment by JaKooLit** [comment]
> doesn't it also need hyprland-nvidia instead of hyprland
> or are you on a laptop?

are you asking me? 

first off, archinstall dont or cannot install anything outside official repo. And certainly cant compile from source.... atleast thats what I know.

**Comment by ThijsGaming** [comment]
> > doesn't it also need hyprland-nvidia instead of hyprland
> > or are you on a laptop?
> 
> are you asking me?
> 
> first off, archinstall dont or cannot install anything outside official repo. And certainly cant compile from source.... atleast thats what I know.

what about using the choatic aur package maybe?
