### ISSUE TITLE
Pre-mounted disk configuration causing systemd and grub bootloaders errors and issues

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#2054]
partitions where mounted as following:

root - /mnt/archinstall
boot - /mnt/archinstall/boot

when ask root directory /mnt/archinstall

if choosing grub as bootloader, script will fail.. throwing some errors about boot

if systemd is chosen - script will install Arch linux. However, during boot, will have ERROR: device 'PARTUUID=None' not found. Solution is to edit the /boot/loader/entries/xxx.conf and add the UUID to make it permanent.

No issues when choosing use-a-best-effort default partition layout.

I have not tried the Manual Partitioning though

Id like to add that there are other partition on that testing... thats why I pre-mounted the partitions first

**Comment by Torxed** [comment]
We have to verify that pre-mounted option still work, by the sound of it it doesn't.
The mount points looks right! :)

**Comment by ccolorado** [comment]
I was mounting / directly on /mnt/ like the arch iso works. I am curious where is the  `/mnt/archinstall/` mentioned. Most likely I didn't read carefully.

**Comment by JaKooLit** [comment]
try and you'll be surprised :)

**Comment by svartkanin** [comment]
These errors sound like something we have just fixed, but difficult to day with such a vague error description.

Could you share the stacktrace of the log file under /var/log/archinstall/install.log

**Comment by JaKooLit** [comment]
> These errors sound like something we have just fixed, but difficult to day with such a vague error description.
[install-efi_stub.log](https://github.com/archlinux/archinstall/files/12647337/install-efi_stub.log)
[install-grub.log](https://github.com/archlinux/archinstall/files/12647339/install-grub.log)
[install-systemd.log](https://github.com/archlinux/archinstall/files/12647340/install-systemd.log)

> 
> Could you share the stacktrace of the log file under /var/log/archinstall/install.log

**Comment by svartkanin** [comment]
Right (note to myself to update the Readme),  you don't need the last step, after cloning master, just cd into the folder and run `python -m archinstall`

**Comment by BachoSeven** [comment]
@svartkanin My installation from `master` with pre-mounted disk configurations in `/mnt/archinstall` and `/mnt/archinstall/boot` just failed as well, with errors from Grub:

[install.log](https://0x0.st/HO0e.log)

Relevant ending:

```
Installing packages: ['grub']
Adding bootloader Grub to /dev/nvme0n1p5
Installing packages: ['grub']
kernel parameters: zswap.enabled=0 rootfstype=ext4
GRUB boot partition: /dev/nvme0n1p5
Installing packages: ['efibootmgr']
Could not install GRUB to /mnt/archinstall/mnt/archinstall/boot: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'grub-install', '--debug', '--target=x86_64-efi', '--efi-directory=/mnt/archinstall/boot', '--bootloader-id=GRUB', '--removable'] exited with abnormal exit code [1]: Installing for x86_64-efi platform.
grub-install: info: cannot open `/boot/grub/device.map': No such file or directory.
grub-install: error: failed to get canonical path of `/mnt/archinstall/boot'.
```

Any tips?

**Comment by Torxed** [comment]
@BachoSeven and your `master` is up to date with 6d908e8?

**Comment by BachoSeven** [comment]
I had just cloned it from github

**Comment by Torxed** [comment]
Understood, if it's a fresh ISO and a fresh glone, it should be up to date. I knew you tried before so was worried you had an old clone of the repo :) We'll have a look.

**Comment by BachoSeven** [comment]
`btw`, doing `arch-chroot /mnt/archinstall` and executing `grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB` installs GRUB correctly.

**Comment by Torxed** [comment]
Aaaah wait, damn. The `--boot-path` is not relative to within the installation.. bah..

**Comment by Torxed** [comment]
@codefiles / @svartkanin: if any of you two have time, could you check why `--boot-path` turns out to be `--efi-directory=/mnt/archinstall/boot` It should be `/boot` not `/mnt/archinstall/boot` :S 

If we can push a fix for this today or tomorrow, I can bump to `v2.6.2` with a hotfix, I'm booked for at least 24h.

**Comment by svartkanin** [comment]
I can have a look at it in my evening, which is in 11h hope that's not too late

**Comment by codefiles** [comment]
Hold on! Haha! I already have a fix about to drop.

**Comment by svartkanin** [comment]
fantastic thanks

**Comment by Enzo-Nunes** [comment]
Hey guys! I've had the same issue when installing dual boot on my desktop with windows. Is there an ETA on the release of this fix? Should I wait for it or use @JaKooLit 's workaround?
