### ISSUE TITLE
Can't find block device /dev/sda1

### ISSUE THREAD

**Issue by amonetlol** [archlinux/archinstall#2056]
I've always installed Archlinux through archinstall on VMware, but this month's iso is giving an error when installing grub, I don't know if it's a bug with grub or archinstall

![archinstall-error](https://github.com/archlinux/archinstall/assets/65382640/6a4a9351-ebcd-4fef-b944-80fd52c6d430)

Grub: 2:2.12rc1-1
Archinstall: 2.6.00-1

**Bios mode**:
https://transfer.sh/SyyrrCD2dv/archinstallbug.log

**Grub mode**:
works without problem

**Comment by svartkanin** [comment]
There's a lot of issues raised for this error can you please check first before creating another one.
Also the problem has been fixed and merged but not released yet
