### ISSUE TITLE
(Newest arch iso, and archinstall script) both audio drivers have package conflicts

### ISSUE THREAD

**Issue by XDuskAshes** [archlinux/archinstall#2062]
![IMG_20230917_102141801_HDR.jpg](https://github.com/archlinux/archinstall/assets/101196233/9d8fdda2-130e-4080-bac0-108dbc810431)

The above has occurred when trying to install either audio driver.

**Comment by Torxed** [comment]
This is solved in master I believe.
So next release (next ISO) will not have this issue.
