### ISSUE TITLE
In _add_efistub_bootloader()  cmd error

### ISSUE THREAD

**Issue by Leebais** [archlinux/archinstall#2065]

**Comment by Leebais** [comment]
--disk should use numeric parameter. [EFISTUB-Archlinux](https://wiki.archlinux.org/title/EFISTUB#efibootmgr)
Example from wiki：
`efibootmgr --create --disk /dev/sdX --part Y --label "Arch Linux" --loader /vmlinuz-linux --unicode 'root=block_device_identifier rw initrd=\initramfs-linux.img'`

**Comment by Torxed** [comment]
I assume you're refering to this: https://github.com/archlinux/archinstall/blob/ca09e1e63d611a0141a68789503cfa472e85e9f9/archinstall/lib/installer.py#L1091C15-L1091C30

Which now will resolve to `/dev/sda` instead of `/dev/sda1`? Or is this the concern?

**Comment by svartkanin** [comment]
I think this was resolved
