### ISSUE TITLE
migrated to kubuntu and causes missig files but size is showing okay in partition.

### ISSUE THREAD

**Issue by urparvezali** [archlinux/archinstall#2068]
I was in arch linux and there were my /home directory mounted at a nvme0n1p3 partition. I never formate this partition because all the important files are in that partition. I had installed arch linux 2-3 month before with the configuration by archinstall where I had selected no subvolumes + no compression.
Today I installed ubuntu based xubuntu and mounted my important partition in /home directory like what i did in the arch linux by archinstall. But after booting my xubuntu I saw all the files are missing but the partition used size is showing like my files are in that but I cant find them.
How can i get my files back? plz response.

**Comment by Torxed** [comment]
Not sure how Ubuntu formats the disk, this might be a question for them or a general support forum.

Unless there's something specific about archinstall here, I'm going to close this as it doesn't have anything to do with archinstall specifically (again, this is my interpretation)
