### ISSUE TITLE
using archinstall get faile.

### ISSUE THREAD

**Issue by HaSaKiYasuooo** [archlinux/archinstall#2074]
I don't know how to resolve this.
![image](https://github.com/archlinux/archinstall/assets/87591236/daf9c136-72ef-488e-a1e5-abe78231be74)

**Comment by Torxed** [comment]
That feels like a very very old ISO, considering it's running Python 3.10.
Could you try with a newer ISO and newer version of archinstall?

If the issue persists, please submit the log files: https://archinstall.readthedocs.io/help/issues.html#log-files

**Comment by Torxed** [comment]
I'll close this for now but if the information above is supplied I'll re-open this ticket :)
