### ISSUE TITLE
Sway does not appear to be a profile

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#2075]
> Cannot import <module 'sway' from '/root/archinstall/archinstall/default_profiles/desktops/sway.py'>, it does not appear to be a Profile class

Noted in #2072 *(log: https://pastebin.com/ddnFkxzR line 3310)*

Not sure if it's relevant as I haven't investigated, just noting down here for later.

**Comment by codefiles** [comment]
This enum is triggering that message.

https://github.com/archlinux/archinstall/blob/3e2999bc2752c76e666d916bdb80608ad74528bf/archinstall/default_profiles/desktops/sway.py#L13-L15

When `_load_profile_class()` is called on the Sway profile `module.__dict__.items()` will contain the enum. Then the line `cls_ = v()` will raise an exception with the enum.

https://github.com/archlinux/archinstall/blob/3e2999bc2752c76e666d916bdb80608ad74528bf/archinstall/lib/profile/profiles_handler.py#L272-L286

Maybe adding the code below to the function following the line with the `module.__dict__.items()` for loop (including the EnumType import)?

```python
if isinstance(v, EnumType):
	continue
```

That works. Thoughts?

**Comment by Torxed** [comment]
Thanks for deep diving on this one.
I think the fix is good enough! It's hard to avoid it in any other way to be honest.

**Comment by svartkanin** [comment]
Adding the specific exclusion for `EnumType` will solve this particular case but if in the future other constructs will get added to profile modules it will break again

Maybe something like this 

```
					import inspect
					bases = inspect.getmro(v)

					if Profile in bases:
						cls_ = v()
						if isinstance(cls_, Profile):
							profiles.append(cls_)
```

**Comment by codefiles** [comment]
Yea, it was just good enough for the case. I like yours approach more.
