### ISSUE TITLE
I3wm at the bottom of the list in the desktops

### ISSUE THREAD

**Issue by erikdubois** [archlinux/archinstall#2078]
list is no longer alphabetical

![image](https://github.com/archlinux/archinstall/assets/10594806/136235a6-ef61-40e4-b349-530b6a12a569)

Could you put i3 after hyprland?

**Comment by svartkanin** [comment]
To be fair it is alphabetical, it's just that the "i" in "i3" is lowercase that's why it comes after all the other uppercase ones

**Comment by erikdubois** [comment]
well consider changing it
please

**Comment by Torxed** [comment]
It has been considered and subsequently implemented :)
