### ISSUE TITLE
How do i use the older version of archinstall which still has the disk layout option?

### ISSUE THREAD

**Issue by john-basilio** [archlinux/archinstall#2085]
There's not much documentation or tutorials about the disk configuration that replaced the disk layout option. The new one makes me really confused a lot, especially when I am just trying to go back on using arch after a long time. I just wanted the older version. Is it still possible?

**Comment by Torxed** [comment]
What specifically is confusing?
We renamed the main menu entry, and cleaned up the options a bit - so we'd love to hear your feedback.

Using old version works if you git clone the master repo and checkout an earlier version (check the release page for tag names) :)

**Comment by john-basilio** [comment]
> What specifically is confusing? We renamed the main menu entry, and cleaned up the options a bit - so we'd love to hear your feedback.


Well to be exact it is the ''Disk configuration" part that is confusing me. I'm also having a hard time finding proper docs about its usage or even tutorials about it.

Also, forgot to mention about this, I tried doing 
`pacman -U https://archive.archlinux.org/packages/a/archinstall/(https://archive.archlinux.org/packages/a/archinstall/archinstall-2.5.3-1-any.pkg.tar.zst`

It successfully downloaded because I double checked. But when I used `archinstall` I was met with error `Module not found`

![379630217_840551557596651_3113782520260513145_n](https://github.com/archlinux/archinstall/assets/105198549/a6d3d94f-d7d3-419a-ade1-d8854197c1e8)


> Using old version works if you git clone the master repo and checkout an earlier version (check the release page for tag names) :)

Also, I'm not much knowledgeable when it comes to the filesystem regarding the installation since I'm just returning to arch after a very long time and I'm still trying to refresh in this field. Could you please elaborate more about the steps on how exactly do I proceed with cloning the master repo for the earlier version? Just being careful to avoid the error `Module not found` again.

**Comment by Torxed** [comment]
> Also, forgot to mention about this, I tried doing
pacman -U https://archive.archlinux.org/packages/a/archinstall/(https://archive.archlinux.org/packages/a/archinstall/archinstall-2.5.3-1-any.pkg.tar.zst
> 
> It successfully downloaded because I double checked. But when I used archinstall I was met with error Module not found

This won't work because the ISO contains python 3.11 but the arch package is built with python 3.10, so it looks in the wrong location.

We have instructions on the README that goes into details how to test with git and the current dev code from `master` here on GitHub: https://github.com/archlinux/archinstall#using-a-live-iso-image

If anything is unclear there please do not hesitate to ask :)

> Well to be exact it is the ''Disk configuration" part that is confusing me. I'm also having a hard time finding proper docs about its usage or even tutorials about it.

Could you elaborate what is confusing? As I can make a whole walkthrough but there's a lot of different filesystems to walk through :) is it what the first three options do? How to define sizes?

**Comment by john-basilio** [comment]
>Could you elaborate what is confusing? As I can make a whole walkthrough but there's a lot of different filesystems to walk through :) is it what the first three options do? How to define sizes?

(Note that I'm trying to dual boot arch and win10)

Sure, let me change the question because it seems like it will be one heck of a trouble.

To elaborate my situation, I followed the same video I used to install arch before, and in that video, we are instructed to first create partitions such as the `EFI` , `Linux Swap` , and `Linux filesystem`. Then only after that should we proceed to use archinstall and mount those partitions to their respected mountpoints using the "Disk layout" option in the guided script.

The problem is I'm not very tech savvy in this field now. Sure I tried to explore all those options but they are all very confusing to me, like "I've already created the partitions, how do I mount them to their mountpoints?" and the other options is kind of a big risk as I don't exactly know how they will work and that if I recklessly do stuff it might instead format the whole drive.

For now, I have deleted the said partitions and left them as unallocated space.
![image](https://github.com/archlinux/archinstall/assets/105198549/590a649a-e3f1-4ed3-baee-835c82e0cecd)

So yeah, instead of asking how to use the older version of archinstall, maybe you could guide me on how do I proceed with dual booting arch on the same drive as windows. To be honest, its really the partitioning part that gives me the headache every time.

So far, I've left the desired space for arch installation as unallocated just like in the picture

**Comment by john-basilio** [comment]
i seem to have made a mistake on the part where i keep mentioning the disk layout part but it's parent name is actually "Drive(s)" 


also, thanks for mentioning the python version. after contemplating with all the life choices i've made throughout my life, i found out that i can temporarily downgrade python too to a fitting version to solve it

(i just looked on the archlinux archive then picked both archinstall and python that were both released in february then pacman -U :)))


Might as well spread this information until the pros make a video about the disk config option;) 

thanks for the time too
