### ISSUE TITLE
Publish docs with github pages on archinstall.archlinux.page

### ISSUE THREAD

**Issue by klausenbusk** [archlinux/archinstall#2098]
As discussed with @Torxed on IRC, Arch Linux has a official domain for project documentation and similar (archlinux.page). E.g. https://repod.archlinux.page/, https://rfc.archlinux.page/ and https://monthly-reports.archlinux.page/.

It could make sense to publish the archinstall documentation to said domain instead of readthedocs.io. For this to work, the documentation must be published with GitHub Pages with e.g. [this action](https://github.com/actions/deploy-pages) and then devops can add `archinstall.archlinux.page` as a custom domain.

**Comment by klausenbusk** [comment]
This is now implemented.

Relevant PRs: #2234, #2237, #2239 and #2240.

**Comment by klausenbusk** [comment]
infrastructure commit: https://gitlab.archlinux.org/archlinux/infrastructure/-/commit/1576ee70270514429b1ea487f463749e411a3d77.

**Comment by Torxed** [comment]
Thank you for the help on this one! New home for the docs feel great and look great :)
