### ISSUE TITLE
Needs a 'minimal' profile

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#210]
Minimal profile should not install a DE, Xorg, or any packages other than enough to boot to a console.

**Comment by dylanmtaylor** [comment]
Another good name for this would be 'server' - maybe just install openssh server or something.

**Comment by Torxed** [comment]
I agree, lets re-work that one. It's main purpose has served as a programming example.
But I also do want to use it for things like getting a bare minimum without absolutely anything. I also want it to take `--haddisk=/dev/x` as an argument from `archinstall.arguments` as It's to risky to have it default to `/dev/sda`.

**Comment by dylanmtaylor** [comment]
Implemented in #219

**Comment by Torxed** [comment]
I was a bit unclear and missunderstood "minimal" I think. As I mentioned in our conversation *(Putting it here for public information)*:
> Archinstall supports this already:
> ```
> python -m archinstall minimal
> ```
> It sources the examples/minimal.py and I was thinking of updating that to be a very minimal installation.

So we should re-work `examples/minimal.py` :) Merged the PR tho!
