### ISSUE TITLE
Arch won't install if you don't have a UEFI device

### ISSUE THREAD

**Issue by mostwise** [archlinux/archinstall#2106]
On my BIOS laptop, I can't install arch because it cant find a valid boot media / manager, and instead it runs archiso instead. I am now running Pop!_OS, but I can't seem to get arch working

**Comment by Torxed** [comment]
Please try the new version from yesterday, and if you did please share the logs :)

**Comment by Torxed** [comment]
Thank you for testing! We have limited hardware to test on ourselves so any feedback is welcome tbh :)
