### ISSUE TITLE
v2.6.1 fails in VMs because of an error in mounting a partition

### ISSUE THREAD

**Issue by a-p-jo** [archlinux/archinstall#2110]
I'm not entirely sure how to accurately describe the issue. I initially experienced #2107, so I appended `cow_spacesize=2G` to kernel params at boot and updated the ISO's archinstall to v2.6.1. But now it fails because of some sort of failure to mount a partition? 

[install.log](https://pastebin.com/CstYTrt4), [dmesg output](https://pastebin.com/2eQBqe9X).

**Comment by a-p-jo** [comment]
The same thing seems to be happening in VMWare Fusion too: [install.log](https://pastebin.com/9prKdMqw), [dmesg output](https://pastebin.com/u0qg214R).

**Comment by Torxed** [comment]
Can you on that machine, run the following:
```
lsblk -f /dev/sda2
lsmod | grep ext4
zgrep EXT4 /proc/config.gz
```

**Comment by Torxed** [comment]
Ah, if you took my advice before and did `pacman -Su archinstall` that might have upgraded the whole system. What I meant to write and should have written is that you should do `pacman -Sy archinstall`.

Most likely the kernel modules updated, and you need a reboot (which is pointless on a live ISO). So running `-Sy` should **not** upgrade the kernel, but upgrade only archinstall.

**Comment by a-p-jo** [comment]
@Torxed Yes, it did upgrade the whole system including the kernel and whatnot. I tried `pacman -Sy archinstall` but there seem to be keyring issues? There seems to be no right answer to importing your keys, it fails with both answers (see attached image).

![image](https://github.com/archlinux/archinstall/assets/66941562/ab351d59-9cf6-4546-9f8a-374010cdb991)

**Comment by Torxed** [comment]
That's another quirk of Arch Linux *(and the bane of my existence)*.
When the Arch ISO boots, it does two things:

1. Automatic Time Sync *(to avoid TLS issues)*
2. Updates the keyring *(to avoid missing keys)*

If you use the latest ISO *(from September)*, usually the key issue won't happen.
But if it does, wait for this service to execute once:

```
# journalctl -f -u archlinux-keyring-wkd-sync.timer
```

And you have to wait until you see something like:
```
Sep 23 14:55:32 laptop systemd[1]: Started Refresh existing PGP keys of archlinux-keyring regularly.
```

Or, option two, manually install a new keyring first:

```
# pacman -Sy archlinux-keyring
<and after that>
# pacman -Sy archinstall
```

That *should* solve that issue ^^

**Comment by a-p-jo** [comment]
This worked. Maybe the ISO should be updated to use the latest version of archinstall...

**Comment by Torxed** [comment]
@a-p-jo that is another issue, similar to here: https://github.com/archlinux/archinstall/issues/2054#issuecomment-1729968841

No idea what causes that yet, it's also very strange.
As running the exact same command manually works (that's the strange part).
