### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9: invalid start byte

### ISSUE THREAD

**Issue by Jastock** [archlinux/archinstall#2111]
I just downloaded the fresh archiso from archlinux.org. Directly after booting into the iso and executing archinstall, I get the following stacktrace:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module

  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 8, in <module>
    from .lib import disk

  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts

  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 615, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 39, in __init__
    self.load_devices()

  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 61, in load_devices
    device_info = _DeviceInfo.from_disk(disk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 381, in from_disk
    model=device.model.strip(),
          ^^^^^^^^^^^^

  File "/usr/lib/python3.11/site-packages/parted/device.py", line 69, in model
    return self.__device.model
           ^^^^^^^^^^^^^^^^^^^

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9: invalid start byte

This is the content of /var/log/archinstall/install.log: 

Could not determine the filesystem: None
Could not determine the filesystem: None
Could not determine the filesystem: None
Could not determine the filesystem: None

**Comment by Torxed** [comment]
```
File "/usr/lib/python3.11/site-packages/parted/device.py", line 69, in model
return self.__device.model
^^^^^^^^^^^^^^^^^^^

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9: invalid start byte
```

This indicates that there's an issue with parted not archinstall.
Nevertheless we're invested in it working.

Could you run:
```
# lsblk -o+MODEL,VENDOR
```

**Comment by Jastock** [comment]
I started a manual install for now and partitioned the disk, but the error is still the same. Here is the output:

``````
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS           MODEL      VENDOR
loop0          7:0    0 682.6M  1 loop /run/archiso/airootfs            
sda            8:0    1  14.6G  0 disk                       Cruzer Fit SanDisk 
├─sda1         8:1    1  14.6G  0 part                                  
│ └─ventoy   254:0    0 804.3M  1 dm   /run/archiso/bootmnt             
└─sda2         8:2    1    32M  0 part                                  
mmcblk0      179:0    0   7.3G  0 disk                                  
├─mmcblk0p1  179:1    0   512M  0 part /mnt/boot                        
└─mmcblk0p2  179:2    0   6.8G  0 part /mnt/home                        
                                       /mnt                             
mmcblk0boot0 179:8    0     4M  1 disk                                  
mmcblk0boot1 179:16   0     4M  1 disk   

The storage I am trying to install on is 8GB of flash. Thanks for the help :)

**Comment by Torxed** [comment]
I think we'd need more debug info to solve this.
A full stack trace might help because it feels like it's cut short.
Not sure why `/usr/lib/python3.11/site-packages/parted/device.py` line 69 would cause decode error as it's not trying to decode :/

**Comment by svartkanin** [comment]
Without the proper log file this will be difficult to debug

**Comment by Torxed** [comment]
I'll close it, as you mentioned you did a manual install.
If you ever bump into it again, we'll need to modify `/usr/lib/python3.11/site-packages/parted/device.py` at line 69 to add a print or something to get the raw value what `pyparted` found as a device model. Because character `\x92` is at best a `ISO-8859-1` encoding, but `lsblk -o+VENDOR,MODEL` showed nothing strance.. but it might strip it.. so gotta check what pyparted found :)

**Comment by okh-mzny** [comment]
> The storage I am trying to install on is 8GB of flash

Could it be that you are trying to install on a Dell Wyse 3040 thin client? I have this excact device in front of me right now, it has 8GB of internal soldered eMMC and it's giving me the excact error you mentioned.

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9: invalid start byte`

Some more info about this device for reference: https://www.parkytowers.me.uk/thin/wyse/3040/

I have tried to add the print statements @Torxed suggested, and also attempted to halt execution and examine the situation with pdb, but always got the same encoding error, even attempting to print the object using inspect.

As i have the device standing around I don't mind investigating further with some assistance :)

**Comment by Torxed** [comment]
> As i have the device standing around I don't mind investigating further with some assistance :)

I'd love to get the full device name that's causing the issue.
`sudo nano /usr/lib/python3.11/site-packages/parted/device.py` and modify like 69 with:

```diff
+ print([self.__device, self.__device.model])
  return self.__device.model
```

**Comment by okh-mzny** [comment]
I tried to print the object like I said, and even tried to examine it while stopped with pdb, but no luck.

I just get the same Exception, this time in the print statemtent.
The first line is the flash drive I boot off.

```
[<_ped.Device object at 0x7f84c336cd40>, 'Kingston DataTraveler 3.0']
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 11, in <module>
    from .lib import disk
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 664, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 39, in __init__
    self.load_devices()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 71, in load_devices
    device_info = _DeviceInfo.from_disk(disk)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 446, in from_disk
    model=device.model.strip(),
          ^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/parted/device.py", line 69, in model
    print([self.__device, self.__device.model])
                          ^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 9: invalid start byte
```

**Comment by okh-mzny** [comment]
I poked around the system some more and did find where the broken disk model string is coming from.

The name comes from the emmc subsystem.

```
root@archiso ~ # cat /sys/class/block/mmcblk0/device/name
H8G4a▒
root@archiso ~ # cat /sys/class/block/mmcblk0/device/name | hexdump -C
00000000  48 38 47 34 61 92 0a                              |H8G4a..|
```

The emmc subsystem gets its name from the so-called "CID" or Card IDentification registers as defined in the SD/MMC standard.

It is defined as a 5 Byte ASCII string so my name is supposed to be `H8G4a` but it is longer..

But for some reason the emmc subsystem under linux returns more data and includes these 0x92 and 0x0a bytes that causes the issue. I can find 0x92 in my CID but not sure where 0x0a is coming from.

Since to me this issue seems out of scope of the archinstall script I'm thinking where to take this.

Ask the pyparted people to strip invalid values returned by libparted?
Ask if something is wrong with the kernels mmc subsystem?

I look forward to more input :)

**Comment by Jastock** [comment]
> > The storage I am trying to install on is 8GB of flash
> 
> Could it be that you are trying to install on a Dell Wyse 3040 thin client? I have this excact device in front of me right now, it has 8GB of internal soldered eMMC and it's giving me the excact error you mentioned.

Yes, I also have the 3040.

**Comment by okh-mzny** [comment]
I created a new issue in the pyparted repo but haven't checked whether the issue already exists 🤦  whoops 

https://github.com/dcantrell/pyparted/issues/76

There are instructions to modify certain pieces of code to get it all to work but it sadly doesnt look like a real fix got much traction.. I'll still leave this here for anyone looking for any kind of solution 

Perhaps archinstall could catch a UnicodeDecodeError as suggested in the pyparted issue?

**Comment by Torxed** [comment]
That we can do, without promising anything I/we can also apply a patch when shipping pyparted as an official arch package and put some pressure on the linked fix!

So thank you for bringing this to my attention ❤️
