### ISSUE TITLE
Couple of suggestions

### ISSUE THREAD

**Issue by mativiters** [archlinux/archinstall#2128]
I have a couple of suggestions that would at least personally make my post-install job easier, though I'm not sure which ones are possible/in line with the philosophy of the project:
1. Archinstall offering to install an AUR helper such as yay or paru.
2. Being able to choose the default shell (zsh, fish, etc)
3. Additional minimal display managers such as slim, lxdm for some of the more minimal desktops. If user chooses lightdm, several nice greeters can be offered to choose from.
4. It's good to suggest some of the very important pieces of software to be installed (can be toggled on using tab). For video player [mpv, vlc], for office suite [libreoffice-fresh], for browser [firefox, firefox-developer-edition, chromium, vivaldi], graphical bluetooth manager [blueman for desktops besides gnome and plasma], archiving tools [xarchiver for gtk desktops and lxqt-archiver for qt based desktops, unzip, zip, unrar], calculator (galculator for gtk, speedcrunch for qt), document reader (zathura, atril, etc), webcam utility (guvcview-qt, guvcview-gtk), coding tools for those who want it [code, neovim, git, php, mariadb, apache] and also several handy utilities like audacity, gimp, shotcut, thunderbird, telegram-desktop, obs-studio, yt-dlp, neofetch,  a firewall (ufw with gufw, firewalld)
the way this can be achieved is that in the menu that currently only accepts a list of packages to be installed, two options are offered: to manually enter package names or alternatively to select from a list of recommended software.
5. Enabling the bluetooth service.
6. If grub is chosen for bootloader, plymouth can be offered, and if chosen, its theme can also be chosen (plymouth offers several themes by default)

**Comment by svartkanin** [comment]
These all seem very subjective things and most are possible already by installing additional packages.
We don't want to present specific software options because the will be an infinite battle of opinions

**Comment by dylanmtaylor** [comment]
1 is out of the question - we've decided to not ship anything from the AUR in the installer or set up the AUR for users. 
2 is trivial and doesn't really need to be done at install time so it'd be largely bloat. chsh isn't too hard, is it?
No opposition to number 3.
4 is already possible in additional packages, it'd be hardly worth it to suggest software, and users can always install more after the install. The point of this project is to bootsrap a system to an installed state, not install and configure everything the users needs.
5 is also post-install configuration. I think this is a single click in GNOME
For 6, Plymouth can break depending on graphics config and theming is likely too opinionated. I'd see adding Plymouth theme selection to the installer as bloat.

**Comment by Torxed** [comment]
I agree that some of these suggestions might improve some users experiences, but I too believe all of the suggestions can be added post-installation with very little effort.
It's a fine balance between what's easy during installation and what's not needed, so we constantly have to balance things. And in this case I think most of the things in the list are things that *some* users would want, and not something that is needed for a successful installation.

I'll go ahead and close this as I think we've gotten enough opinions on these particular suggestions. If you have more suggestions, we're always up for discussing them :)
