### ISSUE TITLE
BTRFS with 2 different drives fails with Unable to add partition, most likely due to overlapping sectors: Can't have a partition outside the disk!

### ISSUE THREAD

**Issue by Rattle189** [archlinux/archinstall#2132]
I have the latest version of the Arch ISO as of writing, and the archinstall script is manually updated to archinstall-2.6.2-1 via pacman in the live USB,

I'm trying to install Arch via the archinstall script on my machine (not through a VM), I have two SSDs (both DRAM-less) plugged in and I wish to use BTRFS for both of them with this configuration:
- The 120GB SSD will be used for the operating system alone
- The 480GB SSD will be used for the home folders

The script crashes when its formatting a partition on the 480GB SSD with the error: Unable to add partition, most likely due to overlapping sectors: Can't have a partition outside the disk!

Here is my user_configuration.json:
[user_configuration.json.txt](https://github.com/archlinux/archinstall/files/12762472/user_configuration.json.txt)

Here is my cmd_history.txt:
[cmd_history.txt](https://github.com/archlinux/archinstall/files/12762476/cmd_history.txt)

And here is my install.log:
[install.log](https://github.com/archlinux/archinstall/files/12762477/install.log)

**Comment by datsfilipe** [comment]
I'm having the same issue.

**Comment by yasas-mintpay** [comment]
I have the same issue as well

**Comment by MeReda** [comment]
did someone find the solution to that issue?
