### ISSUE TITLE
Premounted partitions systemd-boot issue

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#2138]
so this is in connection to my previous issue
https://github.com/archlinux/archinstall/issues/2054

Anyway, the v2.6.3 have fix the grub issue. However the systemd-boot remains.

![Screenshot_2023-10-02-00-59-47_18238](https://github.com/archlinux/archinstall/assets/85185940/71513ed1-a3bd-4832-80fc-e6303f81171a)

It seems that the UUID was not filled up.

Like I said above, I have tested grub and it was fixed. I have not tried other other bootloaders

here is the install log

[install-systemd.log](https://github.com/archlinux/archinstall/files/12777578/install-systemd.log)

It install just fine but it just does not boot since no UUID in the loader

**Comment by codefiles** [comment]
I tested my last fix with GRUB and it worked so I submitted a pull request for it. After, I figured I had not done enough testing and tried with BTRFS subvolumes and systemd-boot and that did not work as I stated at the end here https://github.com/archlinux/archinstall/pull/2113#discussion_r1336510577. I then switched the pr to a draft and was going to come back to it. I saw the next day it had been marked as ready, approved, and merged. I thought maybe I did something wrong in my test and it worked.

I now see that the `PartitionModification` returned by `PartitionModification.from_existing_partition()` does not contain the partuuid. There also is a problem where the mount point for BTRFS subvolumes is not updated in `DeviceHandler.detect_pre_mounted_mods()` like it was for partitions with the last fix.

I will submit a fix shortly. Please test and report back. Thanks.

**Comment by JaKooLit** [comment]
yeah sure I'll be happy to test it.

**Comment by JaKooLit** [comment]
Perfect. tested the current master with systemd-boot and ext4. and its working. Thanks for the efforts. 

Will try as well btrfs, grub systemd and so on
