### ISSUE TITLE
fstab created with incorrect new line chars (CR/LF instead of LF)

### ISSUE THREAD

**Issue by insanemal** [archlinux/archinstall#214]
generated FS tab attached.
Lines generated by script have erroneous ^M at eol.

```
# Static information about the filesystems.
# See fstab(5) for details.

# <file system> <dir> <type> <options> <dump> <pass>

tmpfs /tmp tmpfs defaults,noatime,mode=1777 0 0
# /dev/sda2^M
UUID=fbca8a3c-c6d7-409d-aa4b-6b41cbcc98cb       /               xfs             rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota        0 1^M
^M
# /dev/sda1^M
UUID=FA42-9155          /boot           vfat            rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,utf8,errors=remount-ro   0 2^M
^M
```

Looking at hexdump output it looks like its emiting CR/LF pairs instead of just LF's
```
00000130  75 6f 74 61 09 30 20 31  0d 0a 0d 0a 23 20 2f 64  |uota.0 1....# /d|
```
Should be simple to fix.

**Comment by Torxed** [comment]
Nicely spotted!

**Comment by wc7086** [comment]
This issue should be re-open

**Comment by Torxed** [comment]
@wc7086 let me run a test just to verify, if that's the case I'll re-open and submit a quick PR.

**Comment by Torxed** [comment]
Thank you @wc7086 for poking me.
There's some weird issue with the forked process returning `\r\n`. And adding `newline="\n"` doesn't solve the issue.

I'll get a PR going tomorrow.
![screenshot](https://user-images.githubusercontent.com/861439/168495262-c069e134-a0ef-4f58-b618-86c5d97a1416.png)

**Comment by svartkanin** [comment]
This is most likely resolved
