### ISSUE TITLE
selected Grub bootloader after grub rescue problem.

### ISSUE THREAD

**Issue by DrVektor** [archlinux/archinstall#2140]
i was selected manual partitioning. I was been test in vmware with windows dual boot install archinstall latest version 2.6.3 without desktop environment but i was stucked at grub rescue. i selected disk management  mount efi partition /boot .  Sorry for cant put log file becoz i couldnt pull log file from usb installer in realhardware. i have been tested at my pc too.

**Comment by Torxed** [comment]
There is an easy way if you can: https://archinstall.readthedocs.io/help/issues.html#log-files

```
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st
```

**Comment by svartkanin** [comment]
Without the installation log this is not possible to debug
