### ISSUE TITLE
Error when using "pre-mounted partition" option with a Btrfs filesystem

### ISSUE THREAD

**Issue by ricmau** [archlinux/archinstall#2146]
Description:

Environment:

Archinstall version: 2.6.3
Filesystem: [Btrfs]

Steps to reproduce:

Mount a Btrfs partition to /mnt/archinstall.
Run archinstall and select the "pre-mounted partition" option.

Actual behavior:
The following error is displayed:

Installing packages: ['grub']
Could not detect root at mountpoint /mnt/archinstall

[install.log](https://github.com/archlinux/archinstall/files/12815924/install.log)

**Comment by Torxed** [comment]
Thank you for reporting this, we'll have a look!

**Comment by codefiles** [comment]
Fixed in #2143

**Comment by ricmau** [comment]
I wanted to take a moment to thank you for addressing my issue and for implementing a fix so promptly. It's truly commendable to see how responsive and attentive you are to the community.
I'm grateful for your dedication and expertise.
Thank you again for all that you do and for making this project even better!

Best regards,
Ricmau
