### ISSUE TITLE
Disk Configuration fails to recognize boot partition

### ISSUE THREAD

**Issue by RamonaRoseThomas** [archlinux/archinstall#2147]
I've created a Boot EFI partition at /dev/nvme0n1p6; a swap at /dev/nvme0n1p7; and a root system at /dev/nvme0n1p8;

I mounted the root partition to /mnt/archinstall and the boot partition /mnt/archinstall/boot;

After running through the install and setting the disk configuration to pre-mounted configuration, I inputed /mnt/archinstall;

(this is where the error occurs)

I recieved an error before clicking install stating [Invalid Configuration: Boot partition not found]

I know users were having trouble with nvme drives but is there a solution i'm not finding?

**Comment by svartkanin** [comment]
Can you please submit the log file

**Comment by RamonaRoseThomas** [comment]
Apologies for my 2am brain, heres the log file: https://pastebin.com/vavCbVX4

I ran through the process again before saving the log file recreating the exact steps i took, mounting, running the install.

Hope this helps <3 thank your for your time.

**Comment by RamonaRoseThomas** [comment]
I think my last post got deleted I came back to check and its not here, so heres the log file again:
https://pastebin.com/vavCbVX4

**Comment by svartkanin** [comment]
Sorry I meant the archinstall log https://github.com/archlinux/archinstall#help-or-issues

**Comment by RamonaRoseThomas** [comment]
apologies, im gonna get sleep after this im making rookie mistakes left and right, heres the proper log file:
https://pastebin.com/gAVZhufZ

thank you again!

**Comment by codefiles** [comment]
This looks like a user error in partitioning.

The intended EFI system partition incorrectly has the [partition type GUID](https://en.wikipedia.org/wiki/GUID_Partition_Table#Partition_type_GUIDs) for _Linux filesystem data_.

                "name": "nvme0n1p6",
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",

The partition type GUID should be `C12A7328-F81F-11D2-BA4B-00A0C93EC93B`. See the ArchWiki for partitioning instructions:
https://wiki.archlinux.org/title/EFI_system_partition#GPT_partitioned_disks

**Comment by RamonaRoseThomas** [comment]
just went and checked the log this morning myself and i see the section your pointed out, thank you both so much, i knew i did something wrong thanks for the help 💜
