### ISSUE TITLE
Auto updating the script when the ISO boots

### ISSUE THREAD

**Issue by RyzenDew** [archlinux/archinstall#2148]
Many people in the few discords that I’m a part of that are about linux we’re having issues with arch install and I think it would be a good idea that when you start Archinstall script it auto updates itself to avoid issues and always be on the newest release vs what the iso comes with .. so please consider how much this could help.

**Comment by svartkanin** [comment]
Auto updating software isn't a good approach especially as it's a arch package or can be installed in other ways as well.

An option could be to display an initial message to inform the user that a newer version is available

**Comment by ArchLinuxLover** [comment]
> Auto updating software isn't a good approach especially as it's a arch package or can be installed in other ways as well.
> 
> An option could be to display an initial message to inform the user that a newer version is available

If I have used the ISO before and it has been working for me  I dont want to use this as a "new" one without testing it.

**Comment by Torxed** [comment]
> An option could be to display an initial message to inform the user that a newer version is available

This is something I've wanted to do, and try to get libalpm to be used. As it would be very beneficial to get C bindings to work. That way we could bypass a few more system calls. :)
