### ISSUE TITLE
AttributeError: module '_ped' has no attribute 'PARTITION_BLS_BOOT'. Did you mean: 'PARTITION_BOOT'?

### ISSUE THREAD

**Issue by markus-seidl** [archlinux/archinstall#2149]
I was trying to install a new Arch Linux (first time) from a Debian rescue image (Hetzner, only Debian available for rescue mode) and got to this point:

```
(venv) root@rescue ~ # pip install archinstall
Collecting archinstall
  Using cached archinstall-2.6.3-py3-none-any.whl (732 kB)
Collecting pyparted==3.12.0
  Using cached pyparted-3.12.0.tar.gz (100 kB)
  Preparing metadata (setup.py) ... done
Collecting simple-term-menu==1.6.1
  Downloading simple_term_menu-1.6.1-py3-none-any.whl (27 kB)
Installing collected packages: pyparted, simple-term-menu, archinstall
  DEPRECATION: pyparted is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyparted ... done
Successfully installed archinstall-2.6.3 pyparted-3.12.0 simple-term-menu-1.6.1
(venv) root@rescue ~ # archinstall
Traceback (most recent call last):
  File "/root/venv/bin/archinstall", line 5, in <module>
    from archinstall import run_as_a_module
  File "/root/venv/lib/python3.11/site-packages/archinstall/__init__.py", line 8, in <module>
    from .lib import disk
  File "/root/venv/lib/python3.11/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/root/venv/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 16, in <module>
    from .device_model import (
  File "/root/venv/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 565, in <module>
    class PartitionFlag(Enum):
  File "/root/venv/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 572, in PartitionFlag
    XBOOTLDR = _ped.PARTITION_BLS_BOOT # Note: parted calls this bls_boot
               ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module '_ped' has no attribute 'PARTITION_BLS_BOOT'. Did you mean: 'PARTITION_BOOT'?
```

In my humble opinion I think this is a bug, but please let me know if I have installed wrong dependencies.

**Comment by svartkanin** [comment]
This is quite strange actually, I tried to reproduce this but can't. Looking at the above versions installed, I'm getting the same when running `pip install archinstall` on my local machine. 
 
I'm not sure why this would cause the error., we're using `pyparted` as the wrapper python lib around `parted`. I don't know how `pyparted` generates the code (it seems somewhat auto generated) and may not have all constants defined based on compilation medium, but this is wild speculation.

**Comment by markus-seidl** [comment]
There is no pacman available and I installed it with PIP directly. I had a look into the pyparted and there are `#if` around specific enums (PARTITION_BLS_BOOT and others). I lack the pyparted / parted knowledge to debug this.

**Comment by Torxed** [comment]
I would say this would not work.
`libparted` which `pyparted` relies heavily on is most likely incompatible. Further, even after getting `archinstall` to run - as @svartkanin pointed out - you'll need `pacman`, `pacastrap`, a bunch of services that are arch specific (like `archlinux-keyring-sync-wkd.service` etc.

So I would say abandon all hope - and see if you can't chain-load the arch ISO or kernel instead, to get a good foundation to install from.

**Comment by svartkanin** [comment]
I think we can close this as there's nothing we can do
