### ISSUE TITLE
"ValueError: File system type must be set for modification" when attempting dual boot with Windows 10 or 11

### ISSUE THREAD

**Issue by emes81** [archlinux/archinstall#2156]
Here's the log from an attempt at dual booting with Win11. The same install media has worked successfully on a single boot Arch system. I noted the default btrfs subfolder structure from that install, then created two partitions on the free space left after the Windows install:
300MB, mount point /boot, format ext4
remainder of the space (ca. 225GB), compressed, with the following subfolder structure:
@, /
@home, /home
@log, /var/log
@pkg, /var/cache/pacman/pkg
@.snapshots, /@.snapshots
[install.log](https://github.com/archlinux/archinstall/files/12873597/install.log)

**Comment by svartkanin** [comment]
Your using an older version of `archinstall` 2.6.0, please update to the latest version

**Comment by emes81** [comment]
Oops yes - I tried it with various Arch isos. Tried it with the latest and ran pacman -Sy archinstall before executing archinstall, did not get the ValueError this time and made slightly more progress but still failed. Will open a new issue
