### ISSUE TITLE
mkinitcpio.conf: keymap hook after encryption hook

### ISSUE THREAD

**Issue by MazeChaZer** [archlinux/archinstall#216]
The mkinitcpio.conf file generated by archinstall has the `keymap` hook after the `encryption` hook which means that the vconsole keymap is not applied for the encryption password promt. It should be the other way round.

Reference: https://wiki.archlinux.org/index.php/Mkinitcpio#Common_hooks

**Comment by Torxed** [comment]
Nicely spotted, I patched this two days ago in 1da9e52 and will come in the next release :)
