### ISSUE TITLE
GNOME install: xkb-options set which interferes with ctrl-backspace to delete a word in gtk apps

### ISSUE THREAD

**Issue by darkblaze69** [archlinux/archinstall#2166]
Using Wayland session.
After installing with selected GNOME profile somehow 
"Key sequence to kill X server" is set `org.gnome.desktop.input-sources xkb-options ['terminate:ctrl_alt_bksp']`

It is known to interfere ctrl-backspace to delete a word in gtk apps like gedit, text-editor, evolution etc. Because of this setting ctrl-bksp only deletes a single character. It's annoying and unexpected behavior. Moreover I couldn't find a way to fix this permanently, as unsetting this parameter it returns back after re-login.

I tried clean Arch installation with only `gnome gnome-extra gdm` and there's no such problem, ctrl-bksp works as expected, and this parameter (xkb-options) is default (unset).

I wonder which package sets this parameter and probably it should be excluded from the GNOME profile.

**Comment by darkblaze69** [comment]
I've learnt that removing `XKBOPTIONS=terminate:ctrl_alt_bksp` from /etc/vconsole.conf solves the issue permanently.

After installing GNOME by archinstall /etc/vconsole.conf gets populated with this:
```
# Written by systemd-localed(8) or systemd-firstboot(1), read by systemd-localed
# and systemd-vconsole-setup(8). Use localectl(1) to update this file.
KEYMAP=us
XKBLAYOUT=us
XKBMODEL=pc105+inet
XKBOPTIONS=terminate:ctrl_alt_bksp
```

So `XKBOPTIONS=terminate:ctrl_alt_bksp` gets into action.

But if installed manually `/etc/vconsole.conf` is empty, default:
```
# This is the fallback vconsole configuration provided by systemd.

#KEYMAP=us
```

So I'd like to know by which part of script or package `/etc/vconsole.conf` gets populated, particularly `terminate:ctrl_alt_bksp` option?

**Comment by Torxed** [comment]
It's either `systemd-firstboot` as it's "built-in" to the `systemd` package.
Or it's as mentioned above, a `systemd-localed` call.

I don't think we explicitly do either of those?
So more likely it's one of the gnome packages adding this.

**Comment by darkblaze69** [comment]
This is populated during archinstall script, while chrooted I can see vconsole.conf already contains this. Apparently during this phase firstboot not happened yet.

**Comment by codefiles** [comment]
> So I'd like to know by which part of script or package `/etc/vconsole.conf` gets populated, particularly `terminate:ctrl_alt_bksp` option?

https://github.com/archlinux/archinstall/blob/f107104103b74ac065a56bd94a0878f0d263e177/archinstall/lib/installer.py#L1369

The `/etc/vconsole.conf` you provided can be reproduced with the following command.

```
localectl set-keymap us
```

**Comment by darkblaze69** [comment]
Indeed, there's an issue in on systemd side:
https://github.com/systemd/systemd/issues/25312

Then I close this because of an upstream issue.
