### ISSUE TITLE
ERROR: /mnt/archinstall is not a directory

### ISSUE THREAD

**Issue by TotoShampoin** [archlinux/archinstall#2167]
Hey!
So, I tried running archinstall after mounting my hard drives as /mnt /mnt/boot and /mnt/home
But it throws `/mnt/archinstall is not a directory`
Am I missing something, or is something wrong?

The logs and configs
[install.log](https://github.com/archlinux/archinstall/files/12908145/install.log)
[user_configuration.json](https://github.com/archlinux/archinstall/files/12908146/user_configuration.json)

**Comment by codefiles** [comment]
You are not missing something, the code is. The mount point to be installed to given at the prompt is not used to update the stored mount point so the default `/mnt/archinstall` is used. I submitted a fix but until a release with it is made mount the device to `/mnt/archinstall`.

**Comment by TotoShampoin** [comment]
So, I have done as you said, mounted / /boot and /home in /mnt/archlinux
But now I cannot press "install", for it says "boot partition not found"... Despite it clearly showing up when I hover "Disk configuration", as you can see here

![IMG_20231015_100643012_HDR](https://github.com/archlinux/archinstall/assets/41761945/dad13cfc-0f6e-4969-a77d-c67edc450987)

**Comment by TotoShampoin** [comment]
Nevermind, I see why now
I didn't actually set /boot as EFI partition
