### ISSUE TITLE
Exceptions that inherit from `BaseException` are not logged when raised

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#2172]
None of the exceptions in [`archinstall/lib/exceptions.py`](https://github.com/archlinux/archinstall/blob/c4c5cc42248645142828d09ec0322cdefa49209a/archinstall/lib/exceptions.py) are caught and logged in the following since they are all `BaseException` rather than `Exception`.

https://github.com/archlinux/archinstall/blob/c4c5cc42248645142828d09ec0322cdefa49209a/archinstall/__init__.py#L310-L324

**Comment by Torxed** [comment]
Good catch, best practice would be to change all the exceptions to `Exception` as per hierarchy: https://docs.python.org/3/library/exceptions.html#exception-hierarchy

We'd just need to handle `KeyboardInterrupt` separately for instance

**Comment by svartkanin** [comment]
Ahh right i missed this, I'll raise an update shortly
