### ISSUE TITLE
ValueError: binary mode doesn't take a newline argument

### ISSUE THREAD

**Issue by runbmp** [archlinux/archinstall#218]
https://github.com/archlinux/archinstall/blob/04bc9ce05f6c86e0c3e3e97ed4734165b9482472/archinstall/lib/installer.py#L156

On the torxed-v2.2.0 branch, in a virtualbox virtual machine with btrfs + no desktop, US install, this line is returning an error:
```
File "root/archinstall/archinstall/lib/installer.py", line 156, in genfstab
  with open(f"{self.mountpoint}/etc/fstab", 'ab',newline='\n') as fstab_fh:
ValueError: binary mode doesn't take a newline argument
```

**Comment by Torxed** [comment]
This is correct and an oversight on my end before merging.
> newline controls how universal newlines mode works (it only applies to text mode). It can be None, '', '\n', '\r', and '\r\n'. It works as follows:
But it raises another good find:
I'm iterating the output from `genfstab` by splitting on `\n` and have done so for a long time:
 * https://github.com/archlinux/archinstall/blob/master/archinstall/lib/general.py#L131-L133

This means that when  `.write(fstab)` writes the buffer by iterating the response, `\n` is "replaced" as I assumed this would be added manually during programming. But instead only `\r` will get written.

As this is a little bit bigger, either we iterate `fstab` manually or I'll have to re-work the `__iter__` logic, the later being risky.

**Comment by insanemal** [comment]
So hang on genfstab is emitting the '\r\n' terminated strings? Or is python adding them them in somewhere? Andyeah, that's my bad. I forgot that write with binary mode doesn't add newlines.

**Comment by Torxed** [comment]
> So hang on genfstab is emitting the '\r\n' terminated strings? Or is python adding them them in somewhere? Andyeah, that's my bad. I forgot that write with binary mode doesn't add newlines.

It's `genfstab` that generates it. But I mistakenly removed the `\n` which we'll add back.
As IMO `\r` isn't a real new-line character ^^

**Comment by insanemal** [comment]
So it's going to emit files with \r\n?

Or just \n?

**Comment by Torxed** [comment]
> So it's going to emit files with \r\n?
> 
> Or just \n?

I'm assuming both works/are supported by the kernel.
So IMO I'll output the data from `genfstab` directly without touching the `\n`. Essentially just being transparent with the output and not break it up so much. But I believe it will be `\r\n` since that's what `genfstab` spits out so I'll honor that.

**Comment by insanemal** [comment]
genfstab is bash. It only issues /n line endings. Something else is happening. 

https://github.com/glacion/genfstab/blob/master/genfstab

**Comment by Torxed** [comment]
> genfstab is bash. It only issues /n line endings. Something else is happening.
> 
> https://github.com/glacion/genfstab/blob/master/genfstab

I'm looking in to it, if this is an issue it's most likely coming up else where as well.

**Comment by insanemal** [comment]
Part of the reason I had used the forced newline was because I was reading something in the python documentation about the internal representation being transparently converted to and from different newline representations. 

I have to admit, I've not encountered this issue before when reading in output of other processes.

**Comment by insanemal** [comment]
I've looked at the code being used for calling external applications. 
I can't see any good reason for it happening. Unless its somehow happening in an encode/decode call?
I have to admit the code for calling external commands does, to me, look far more complicated than I think is required. You've already imported subprocess why not just use that with readline? It would avoid this whole issue and allow you to have pre-split output.

**Comment by Torxed** [comment]
> I've looked at the code being used for calling external applications.
> I can't see any good reason for it happening. Unless its somehow happening in an encode/decode call?
> I have to admit the code for calling external commands does, to me, look far more complicated than I think is required. You've already imported subprocess why not just use that with readline? It would avoid this whole issue and allow you to have pre-split output.

Because up until recently there was no easy way of catching password prompts and making things interactive.
The complexity had it's reasons, but I will be re-designing it to be less "weird".. because it is a bit weird at the moment.
I just have to finish up #124 first to fix the biggest issue at the moment which is the partitioning acting up.

**Comment by insanemal** [comment]
I've got some solid code based around subprocess. I'll have a crack at seeing how it deals with password fields. 

If it works I'm happy to have a crack at merging it. I'm happy for you to knock it back when it's done

**Comment by Torxed** [comment]
I don't mind!

Bare in mind that for convenience the `sys_call` has a `__iter__` function as well as:
 * Exit code (kind of a no brainer)
 * A trace log (for logging purposes)
 * Ability to change working directory

These are probably trivial but I'll note them down for clarity's sake :)
And I'm happy to merge in any of this into a better function at any time.
