### ISSUE TITLE
Give a warning if "best guess" partitioning is going to wipe data

### ISSUE THREAD

**Issue by iKadmium** [archlinux/archinstall#2183]
I recently attempted an Arch install opting to let the installer try to work out a course of action for partitioning. I have four hard drives installed, with an ext4 partition on drive 4 (as well as a data partition) and an EFI boot partition on drive 2 (as well as a data partition).

Optimistic Expectation: Installation of Grub on the Boot partition and automatic replacement of the ext4 partition.
Pessimistic Expectation: An explanation of the suggested course of action, with an option to accept or edit. Or at least, options to accept or cancel.
Actual: Drives 2 and 4 were wiped completely with no option to cancel. There was a countdown but frantically tapping Ctrl-C did nothing.

**Comment by Torxed** [comment]
We do have a preview when going to disk options after selecting best effort.
And Ctrl-C has worked on the many tests over the years.

I think showing the preview and having the warning about wiping is enough, we'll verify that Ctrl-C works tho.
