### ISSUE TITLE
Password visible on Profiles list

### ISSUE THREAD

**Issue by natedawg20** [archlinux/archinstall#2186]
After creating a new user, the "Password" is visible in plain text under the list of available profiles, unless this is the intended behavior?

![image](https://github.com/archlinux/archinstall/assets/99000334/ab51d3e7-4b62-452e-9da4-86deb872be87)

![image](https://github.com/archlinux/archinstall/assets/99000334/67d447e0-a01a-4ed6-a008-817716e21dc2)

**Comment by Torxed** [comment]
I believe this has been hidden in the past, we'll get on to fixing it!

**Comment by natedawg20** [comment]
Oh perfect!

**Comment by codefiles** [comment]
This stopped functioning correctly with 360a1b4f. The fix I submitted reverts the change to `archinstall/lib/output.py` from that commit.

**Comment by Torxed** [comment]
Fix has been merged, will make it to the next release due in a couple of days :)

**Comment by natedawg20** [comment]
Awesome sauce!! Great job!!!
