### ISSUE TITLE
Limine bootloader error, unable to create directories 

### ISSUE THREAD

**Issue by spsf64** [archlinux/archinstall#2197]
I think title says it all, will attach image with the error....
I was able to install if I create the /EFI/BOOT directory in the /boot partiton before starting archinstall.

![limine](https://github.com/archlinux/archinstall/assets/1877391/5f8f9d90-83e2-4a00-91e4-8bb8778b7a11)

**Comment by amebtw** [comment]
Tested today with arch iso 2023.11.01; still a problem.
I was not able to install by creating /EFI/BOOT.
[cmd_history.txt](https://github.com/archlinux/archinstall/files/13250609/cmd_history.txt)
[install.log](https://github.com/archlinux/archinstall/files/13250610/install.log)
[user_configuration.json](https://github.com/archlinux/archinstall/files/13250612/user_configuration.json)

**Comment by amebtw** [comment]
This issue can be closed as #2216 fixed the issue.

**Comment by spsf64** [comment]
Just tested and its working as expected.
Thanks!
