### ISSUE TITLE
Premounted partitions systemd-boot issue - Nov 2023 iso

### ISSUE THREAD

**Issue by JaKooLit** [archlinux/archinstall#2200]
so going back to this

https://github.com/archlinux/archinstall/issues/2138

Had a quick test today on Nov 2023 iso

Grub is working fine..

however, the systemd-boot issue came back again? No UUID and need to manually add the UUID...

**Comment by JaKooLit** [comment]
I just want to add that this only happens on pre mounted partitions.

 ie /mnt/archinstall for root 
 /mnt/archinstall/boot for boot partion

**Comment by codefiles** [comment]
This was fixed by 8257e9f. A release has not been made since then.
