### ISSUE TITLE
Can't use seprated home partition on seprated nvme.

### ISSUE THREAD

**Issue by Edgars-Cirulis** [archlinux/archinstall#2205]
![20231109_010854](https://github.com/archlinux/archinstall/assets/58264013/70c4182c-b7be-4303-8a65-f33926330f49)
![20231109_010529](https://github.com/archlinux/archinstall/assets/58264013/ddd4e8d9-c806-4c99-889e-91f7abaaff5b)

**Comment by svartkanin** [comment]
Can you please submit the logfile /var/log/archinstall/install.log

**Comment by Edgars-Cirulis** [comment]
https://0x0.st/HtEY.log

**Comment by svartkanin** [comment]
Thanks we'll have a look at it

**Comment by Torxed** [comment]
The topic of this issue is pinpointing the issue, but I'll close this one in favor of duplicate https://github.com/archlinux/archinstall/issues/2192 as it's more searchable.
