### ISSUE TITLE
Desktop/Gnome does not install only `gnome` and `gnome-tweaks`

### ISSUE THREAD

**Issue by osalbahr** [archlinux/archinstall#2215]
Hello,

After selecting Desktop -> Gnome (and nothing else) I was a bit surprised that I had `vim` already installed. In the window down below, I thought that "Installed packages" listing `gnome` and `gnome-tweaks` means that these are the only packages/metapackages being installed (`gnome` is all that's needed, `gnome-tweaks` is neat to have). It's also cool that it installs `vim`, I was planning to install it anyways. But I was not expecting it (granted, I haven't read the docs).

Would it be possible/desirable to make it more clear in the script which packages are being installed as part of all Desktop profiles?

I think these are the packages:

- https://github.com/archlinux/archinstall/blob/f6106324eb71905df9b832eb973a08a1f45fa5af/archinstall/default_profiles/desktop.py#L23-L36

![image](https://github.com/archlinux/archinstall/assets/54853250/cbfe1b24-e66f-49b4-8030-9b6e5ac794d4)

**Comment by svartkanin** [comment]
The displayed packages are per profile. We can possibly add the main desktop ones as well there in the list to avoid confusion. Or add them outside on the main selection

**Comment by svartkanin** [comment]
A improvement PR is up, it will display all packages for the main profiles as well as subprofiles and GFX drivers
