### ISSUE TITLE
archinstall.lib.exceptions.DiskError: Could not format ... mkfs.fat: Too few blocks for viable filesystem

### ISSUE THREAD

**Issue by qwelias** [archlinux/archinstall#2224]
Follow up on https://github.com/archlinux/archinstall/issues/2222

I've been following [this](https://wiki.archlinux.org/title/Install_Arch_Linux_from_existing_Linux#Method_B:_Using_the_LiveCD_image) for installation from host system.
Pulled fresh master, HEAD e6344f93f7e476d05bbcd642f2ed91fdde545870
`rm -rf /var/log/archinstall/install.log`
`python archinstall/archinstall/__main__.py`
Got new error with same "Use a best-effort default partition layout"
```
archinstall.lib.exceptions.DiskError: Could not format /dev/sda1 with fat32: ['/usr/bin/mkfs.fat', '-F32', '/dev/sda1'] exited with abnormal exit code [1]: mkfs.fat 4.2 (2021-01-31)
mkfs.fat: Too few blocks for viable filesystem
```
[install.log](https://gist.github.com/qwelias/a4250b8e9b6d8522b2d4ab2469dfbe5f)

**Comment by qwelias** [comment]
Running `python archinstall/archinstall/__main__.py` again results in:
```
Traceback (most recent call last):
  File "//archinstall/archinstall/__main__.py", line 16, in <module>
    import archinstall
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 10, in <module>
    from .lib import disk
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/__init__.py", line 1, in <module>
    from .device_handler import device_handler, disk_layouts
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 650, in <module>
    device_handler = DeviceHandler()
                     ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 39, in __init__
    self.load_devices()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_handler.py", line 75, in load_devices
    lsblk_info = get_lsblk_info(partition.path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 1161, in get_lsblk_info
    if infos := _fetch_lsblk_info(dev_path):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 1145, in _fetch_lsblk_info
    raise err
  File "/usr/lib/python3.11/site-packages/archinstall/lib/disk/device_model.py", line 1134, in _fetch_lsblk_info
    result = SysCommand(f'lsblk --json -b -o+{lsblk_fields} {dev_path}').decode()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/lsblk', '--json', '-b', '-o+name,path,pkname,size,log-sec,pttype,ptuuid,rota,tran,partn,partuuid,parttype,uuid,fstype,fsver,fsavail,fsuse%,type,mountpoint,mountpoints,fsroots', '/dev/sda1'] exited with abnormal exit code [32]: lsblk: /dev/sda1: not a block device
{
   "blockdevices": [

   ]
}
```

Also added `lsblk -J -O` output into [install.log](https://gist.github.com/qwelias/a4250b8e9b6d8522b2d4ab2469dfbe5f) gist

**Comment by Torxed** [comment]
Not quite sure about these particular errors:

> Error calling lsblk: lsblk: /dev/sda1: not a block device

> Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code: 

it feels like `/dev/sda1` is not behaving at all what `libparted` want.

I'm assuming you did the step:
```
# chroot squashfs-root bash
```
If not that would explain the second issue.
And probably the first one too.

If not, this might have weird consequences: `mount -o bind /dev squashfs-root/dev` as `chroot` will behave a bit strange I suppose?

**Comment by qwelias** [comment]
> I'm assuming you did the step:
> `# chroot squashfs-root bash`

Yes, running it as root

`mount -o bind /dev squashfs-root/dev` under `chroot`:
```
mount: squashfs-root/dev: mount point does not exist.
       dmesg(1) may have more information after failed mount system call.
```

**Comment by qwelias** [comment]
> lsblk: /dev/sda1: not a block device

Goes away after deleting all partitions from the drive.

Tried to unmount everything according to guide and mount back in:
```
# umount squashfs-root/dev/pts
# umount squashfs-root/dev
# umount squashfs-root/sys
# umount squashfs-root/proc
# umount squashfs-root
# mount --bind squashfs-root squashfs-root
# mount -t proc none squashfs-root/proc
# mount -t sysfs none squashfs-root/sys
# mount -o bind /dev squashfs-root/dev
# mount -o bind /dev/pts squashfs-root/dev/pts
# cp -L /etc/resolv.conf squashfs-root/etc
# chroot squashfs-root bash
```
Got same `mkfs.fat: Too few blocks for viable filesystem` after `python archinstall/archinstall/__main__.py` and fresh config

**Comment by qwelias** [comment]
I guess I'll try all that again from an actual LiveUSB without host system to avoid any potential for bad mounts or whatever

**Comment by qwelias** [comment]
seems like running from actual live sub went just fine, must be related to running from host system

**Comment by svartkanin** [comment]
This isn't necessarily a archinstall issue, `lsblk` seemed to have bad issues detecting things `Error calling lsblk: lsblk: /dev/sda1: not a block device` which is quite strange. 
Is the /dev/sda drive a special drive in any way?

**Comment by qwelias** [comment]
It's Kingston XS2000, nothing special aside from being external from what I know

**Comment by qwelias** [comment]
I general I agree that it's probably not an issue in archinstall itself.
I suspect there's either a problem with mount instructions [here](https://wiki.archlinux.org/title/Install_Arch_Linux_from_existing_Linux#Method_B:_Using_the_LiveCD_image), or the mount itself is misbehaving, or lsblk has some issues with those mounts in particular, but I lack the expertise to narrow it down

**Comment by Torxed** [comment]
I'll be running these tests within a few days. But I'll close this for now as it will still be indexable and people can come here by the title and read up.

And if new info comes along I can re-open it :)
