### ISSUE TITLE
After install, prompt the user if they want to chroot into the installation

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#225]
I think it would be a good idea to add a prompt to ask the user if they want to chroot into the newly created installation after the installation steps are executed.

For instance in pseudo-code, 

```
choice = input("Would you like to chroot into the newly created installation? [Y/n]")
if choice.lower() == 'y':
     execute('arch-chroot /mnt');
```

**Comment by Torxed** [comment]
I think this is a nice touch, it explains what's about to happen and it gives an easy way to jump into the new installation.
Also add the "finished" output after it:
```python
choice = input("Would you like to chroot into the newly created installation and perform post installation configurations? [Y/n]")
if choice.lower() in ("y", ""):
    installation.log("For post installations tips, see https://wiki.archlinux.org/index.php/Installation_guide#Post-installation", fg="yellow")
    try:
        subprocess.check_call("arch-chroot /mnt", shell=True)
    except:
        pass
finally:
    installation.log("Installation completed without any errors. You may now reboot."
```

**Comment by dylanmtaylor** [comment]
> I think this is a nice touch, it explains what's about to happen and it gives an easy way to jump into the new installation.
> Also add the "finished" output after it:
> 
> ```python
> choice = input("Would you like to chroot into the newly created installation and perform post installation configurations? [Y/n]")
> if choice.lower() in ("y", ""):
>     installation.log("For post installations tips, see https://wiki.archlinux.org/index.php/Installation_guide#Post-installation", fg="yellow")
>     try:
>         subprocess.check_call("arch-chroot /mnt", shell=True)
>     except:
>         pass
> finally:
>     installation.log("Installation completed without any errors. You may now reboot."
> ```

I like this a lot. I think it'd be great to add this in.

**Comment by dylanmtaylor** [comment]
By the way, is there a shortened link to that? from the installer, it's not like you can copy/paste https://wiki.archlinux.org/index.php/Installation_guide#Post-installation.

**Comment by Torxed** [comment]
> By the way, is there a shortened link to that? from the installer, it's not like you can copy/paste https://wiki.archlinux.org/index.php/Installation_guide#Post-installation.

Not that I know of. So printing it in full is probably the only option, I hope people would search it in their favorite search engine and find it instead of writing off the whole thing.

**Comment by advaithm** [comment]
Maybe we can use a link shortener for this. Also if we do add this. I think it should be fine to change the post install hooks in i3 and sway to just print out a message stating we don't ship a default config

**Comment by dylanmtaylor** [comment]
> Maybe we can use a link shortener for this. Also if we do add this. I think it should be fine to change the post install hooks in i3 and sway to just print out a message stating we don't ship a default config

I just made https://tinyurl.com/archpostinstallwiki but I'm hesitant to have a link to any domain not part of the arch project.

**Comment by Torxed** [comment]
> > Maybe we can use a link shortener for this. Also if we do add this. I think it should be fine to change the post install hooks in i3 and sway to just print out a message stating we don't ship a default config
> 
> I just made https://tinyurl.com/archpostinstallwiki but I'm hesitant to have a link to any domain not part of the arch project.

I second this hesitation ^^ It's almost as long anyway so go with the original link.
