### ISSUE TITLE
[2.7.0] Luks : disk not encrypted but system works like without Luks.

### ISSUE THREAD

**Issue by Xdavius** [archlinux/archinstall#2258]
More info and logs tomorrow. It was working on the previous release. I need to test more.

**Comment by Torxed** [comment]
I can almost bet that in the encryption menu, you didn't select which positions to encrypt — because it's very easy to miss

**Comment by Xdavius** [comment]
> I can almost bet that in the encryption menu, you didn't select which positions to encrypt — because it's very easy to miss

I think that was the problem of my friend, tested ok today.

![Screenshot_20231124_152610](https://github.com/archlinux/archinstall/assets/66792063/331307dd-108e-4f89-9371-07aa4d64e0b5)
