### ISSUE TITLE
[2.7.0 - git] Nvidia still not installed

### ISSUE THREAD

**Issue by Xdavius** [archlinux/archinstall#2260]
Sorry, but the fix doesn't work :(

method to test : 

- pacman -Sy git python-pip
- pip install --upgrade archinstall --break-system-packages (to have dependancies, if not, iku error)
- git clone archinstall.git
- cd archinstall/archinstall/scripts
- python guided.py
- selecting KDE, luks, nvidia, linux
- selecting chroot for post installation
- pacman -Qs nvidia

Result : 

- no packages installed

![Screenshot_20231124_151934](https://github.com/archlinux/archinstall/assets/66792063/3e84b3b3-cafe-4b97-ae69-dac8f47f7b00)

**Comment by Xdavius** [comment]
Tested with XFCE too : 
![Screenshot_20231124_155728](https://github.com/archlinux/archinstall/assets/66792063/60ec8894-8b5a-4438-8b95-1fd7eb3bf9d1)

**Comment by Torxed** [comment]
#2259 solved this, new release in a few minutes.

**Comment by Xdavius** [comment]
> #2259 solved this, new release in a few minutes.

Ok, tomorrow, New tests again...

**Comment by svartkanin** [comment]
It seems that @Xdavius actually run the latest master though, is that correct?
If that's not working could you please submit the logs as otherwise we can't debug it properly

**Comment by Xdavius** [comment]
Yes. But I wasn't sure about the test method. Now I've got the good one and will test again tomorrow and send logs if needed.
