### ISSUE TITLE
[2.7.0 - Master GIT] - Nvidia DKMS : Hooks for pacman missing / drm_modset=1 in /etc/modprobe.d missing

### ISSUE THREAD

**Issue by Xdavius** [archlinux/archinstall#2263]
Hi

Using nvidia-dkms, you need to add the hooks. If not, first kernel or nvidia update = Boom

Adding drm_modset=1 for early loading could be considerated (seems in some laptop can be a problem (1 case for more than 50 installations on our group). But in almost others solve more problems than without)

![Screenshot_20231125_122237](https://github.com/archlinux/archinstall/assets/66792063/101cb7ec-407e-4cbe-9cc0-419b4b693154)

**Comment by svartkanin** [comment]
The hook should not be necessary, according to the wiki https://wiki.archlinux.org/title/NVIDIA
> Note: A custom pacman hook is only needed for packages that ship built kernel modules. *-dkms packages do not need it as their upgrades will automatically trigger a mkinitcpio run.

**Comment by Xdavius** [comment]
> The hook should not be necessary, according to the wiki https://wiki.archlinux.org/title/NVIDIA

> > Note: A custom pacman hook is only needed for packages that ship built kernel modules. *-dkms packages do not need it as their upgrades will automatically trigger a mkinitcpio run.


Ok.

If not needed, no problems. 

What do you think about adding "drm-modset 1" ?

Thank you.

**Comment by svartkanin** [comment]
We could consider it, but this seems more like a "feature" to me than a necessity which is always a bit tricky as some people may not want it. 
@Torxed any thoughts on this?

**Comment by svartkanin** [comment]
I just found this issue here which is the same https://github.com/archlinux/archinstall/issues/2214
So i'll close this one in favor of the other one and we can merge any discussions
