### ISSUE TITLE
No option to change the system language

### ISSUE THREAD

**Issue by DenysMb** [archlinux/archinstall#227]
In the moment there is no option in the script for user to select the language of the system (**it will always be en_US.UTF-8**).

Is any plan to implement a language selection in the future?

**Comment by dylanmtaylor** [comment]
Locale selection in general, including timezone definitely could use some improvement. I wouldn't rule this out, and it's definitely a valid pain point for non-US or non-English users.

**Comment by Torxed** [comment]
The function [.set_locale()](https://github.com/archlinux/archinstall/blob/master/archinstall/lib/installer.py#L163-L171) exists.
We simply have to add a clean way of asking for a language to it.

This will for sure get some love and attention going forward.

**Comment by Col433** [comment]
So I take it in v2.2.0 we will get the option to chose our locale?

**Comment by Torxed** [comment]
> So I take it in v2.2.0 we will get the option to choose our locale?

That's the goal :)
