### ISSUE TITLE
Archinstall refuses to encrypt

### ISSUE THREAD

**Issue by mindtheegab** [archlinux/archinstall#2301]
hi, i feel im missing something i tried twice to run archinstall choosing best effort partitioning both ext4 and btrfs with disk encryption, i set the password for encryption but even if the script is successful when i boot it doesnt ask me for a password before booting into arch , i remember using this in the past did something change to enable encryption? 

thanks

**Comment by svartkanin** [comment]
Can you please provide the installation log

**Comment by svartkanin** [comment]
We are unable to debug this without a log, so I'll close it for now. If this reappears we can reopen the issue
