### ISSUE TITLE
Keyboard layout option is not there

### ISSUE THREAD

**Issue by Bydo-Spore** [archlinux/archinstall#2319]
Under 'Keyboard layout' there's no option to set it to British English. There's only 'us' and 'en'. British English is required in order to map " and @ to the correct keys for example.

'uk' is Ukranian. I must be missing something. Please help.

**Comment by svartkanin** [comment]
The keymaps are retrieved from `localectl list-keymaps`. According to https://wiki.archlinux.org/title/Linux_console/Keyboard_configuration#Listing_keymaps `uk` does indeed map to British English so you should be able to pick that one
