### ISSUE TITLE
Crash: Cannot use existing partitionning

### ISSUE THREAD

**Issue by Chevek** [archlinux/archinstall#2324]
Hi,

I want to use an SSD with an already existing partitioning scheme.

I asked for 3 partitions to bu used:

Partition | mount point | format | filesystem
/dev/nvme2n1p1 | /boot/efi | NO | FAT32
/dev/nvme2n1p8 | /boot | YES | EXT4
/dev/nvme2n1p20 | / | YES | EXT4

There is many much more partitions on this drive which should remain untouched. And I setup GRUB.

Fort some reason, archinstall seems to be confused with BTRFS an another partition, then says "Mountpoint is not specified". I'm quite sure all 3 partitions I asked for to be used have all their mount points assigned (I repeated 3 time the operation).
/dev/nvme2n1p1 -> /boot/efi
/dev/nvme2n1p8 -> /boot
/dev/nvme2n1p20 -> /

In particular I never asked to use /dev/nvme2n1p19 (which is formated using btrfs).

log is attached.
[H6xo.log](https://github.com/archlinux/archinstall/files/13841512/H6xo.log)

Regards

**Comment by jotenakis2** [comment]
I have the same use case, same issue. It seems having boot and boot/efi segregated is not supported by archinstall which is a pity.

**Comment by svartkanin** [comment]
Thanks for the logs, this seems to be a bug as you correctly mentioned, the Btrfs is existing and also marked as such in the logs and therefore should not be touched at all

**Comment by svartkanin** [comment]
This is the same bug as #2337 and a PR is up to fix the issue
