### ISSUE TITLE
NVIDIA Proprietary drivers should include nvidia_drm modeset=1 by default.

### ISSUE THREAD

**Issue by reedlove** [archlinux/archinstall#2326]
I know that there are several issue reports that "sort've" touch upon this, but it looks like nothing is being done about it.
So, in this example, the profile selected is Desktop/KDE with the NVIDIA Proprietary graphics package.

1.) The default login manager is SDDM
2.) The default Plasma instance under SDDM is WAYLAND
3.) Your installer does not create the modprobe.d or boot entry to set nvidia_drm modeset=1
4.) This breaks KDE Plasma on NVIDIA Proprietary drivers.

Why is modeset=1 not being enabled by default for NVIDIA Proprietary? In most cases it seems safe to enable it by default.
I get that ARCH is an advanced distribution and that people like me who are experienced with Linux can figure this stuff out in a few seconds/minutes, but I thought that the purpose of archinstall was to limit the amount of manual intervention for a fresh install?

Wayland on NVIDIA has been horrible, for sure, but NVIDIA has done a bunch of work for wayland in the 545 series which should hopefully improve the experience, but even if it's not perfect why would you break the entire Plasma Wayland instance by default by not enabling modesetting?

For everyone else, open a terminal and do the following:
1.) Type: "sudo nano /etc/modprobe.d/nvidia_drm.conf" and press enter.
2.) Enter your password.
3.) Type in "options nvidia_drm modeset=1"
4.) Press Ctrl+x
5.) Press y
6.) Press enter
7.) Reboot your machine

Thanks.
-Reed

**Comment by JTEpic** [comment]
Agreed, I had to enable nvidia_drm.modeset=1 in the systemd config file though (https://wiki.archlinux.org/title/Kernel_parameters) (your method worked but wayland had about 1 frame per 5 seconds) which is something archinstall could do

**Comment by svartkanin** [comment]
This seems to be a duplicate of https://github.com/archlinux/archinstall/issues/1239

**Comment by AttackButton** [comment]
Any news on this? I had to fix it to get Cosmic + Wayland + the NVIDIA driver working.

**Comment by h8d13** [comment]
@AttackButton this is done by default by nvidia-utils for a while now https://archlinux.org/packages/extra/x86_64/nvidia-utils/

**Comment by reedlove** [comment]
> Any news on this? I had to fix it to get Cosmic + Wayland + the NVIDIA driver working.

Cosmic appears to be slightly broken at the moment. I can also tell you from personal experience that I've had other issues with it even before the latest breakage. I can see the potential in it, but it feels like it needs to bake in the oven a little bit more before becoming a daily driver. =(

https://github.com/pop-os/cosmic-epoch/issues/3330
