### ISSUE TITLE
PGP signature issues with downloads on installation 

### ISSUE THREAD

**Issue by RobertTVarga** [archlinux/archinstall#2327]
Invalid or corrupted packages, PGP signature issues
[H67r.log.txt](https://github.com/archlinux/archinstall/files/13853368/H67r.log.txt)

**Comment by rileyparadox** [comment]
I have the same issue!

**Comment by elppans** [comment]
Reinstall archlinux-keyring

**Comment by svartkanin** [comment]
As suggested, updating the keyring should fix the problem https://archinstall.archlinux.page/help/known_issues.html#keyring-is-out-of-date-2213
