### ISSUE TITLE
About "Waiting for automatic mirror selection (reflector) to complete."

### ISSUE THREAD

**Issue by WLongSAMA** [archlinux/archinstall#2328]
In some regions of China, it may not be possible to access the archLinux website, which may result in the inability to obtain the correct mirrors and prevent the installation process from continuing.

When I try to use a custom mirror, it still doesn't solve the problem.

![QQ截图20240107220733](https://github.com/archlinux/archinstall/assets/12743204/1f030f81-353c-4496-89f3-a391e010bdbe)

**Comment by Dlinuigh** [comment]
把设置保存到文件，然后编辑user_configuration.json文件里的url，把速度快的留下。再执行的时候用上--config选项。
在最开始也要自己修改一次mirrorlist否则也会进行一次reflector耗时。其实reflector如果能加上国家地区这个参数就不会有那么多错。reflector -c china -f 5 > mirrorlist就能做到了。

**Comment by Dlinuigh** [comment]
触发这个的条件是使用了ntp但是地区选了utc吗

**Comment by Dlinuigh** [comment]
> 触发这个的条件是使用了ntp但是地区选了utc吗

我尝试了好像是这个原因

**Comment by WLongSAMA** [comment]
@Dlinuigh  虚拟机不方便导出配置文件抱歉，安装源用的是自定义源，区域语言选的是zh_CN，ntp是默认值true，时区utc和shanghai都测试过。
因为网络问题当我想选择Mirror region的话，会黑屏等待，一直不显示国家列表，所以只能暂时用自定义源，也怀疑是自定义源的格式输入的有问题，输入的是https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
![QQ截图20240109213021](https://github.com/archlinux/archinstall/assets/12743204/6183491d-93cf-44b2-b8a3-38471ba6dcb7)

另外，在我这里reflector似乎始终都是用不了的。
![QQ截图20240109211625](https://github.com/archlinux/archinstall/assets/12743204/2905c0a5-a365-4bc6-a470-213a01c28628)

**Comment by WLongSAMA** [comment]
补区域语言的截图
![QQ截图20240109213823](https://github.com/archlinux/archinstall/assets/12743204/f92ef566-1b42-4469-9def-e8db4e46557f)

**Comment by WLongSAMA** [comment]
> @Dlinuigh 虚拟机不方便导出配置文件抱歉，安装源用的是自定义源，区域语言选的是zh_CN，ntp是默认值true，时区utc和shanghai都测试过。 因为网络问题当我想选择Mirror region的话，会黑屏等待，一直不显示国家列表，所以只能暂时用自定义源，也怀疑是自定义源的格式输入的有问题，输入的是https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch ![QQ截图20240109213021](https://private-user-images.githubusercontent.com/12743204/295220707-6183491d-93cf-44b2-b8a3-38471ba6dcb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDg0NjAsIm5iZiI6MTcwNDgwODE2MCwicGF0aCI6Ii8xMjc0MzIwNC8yOTUyMjA3MDctNjE4MzQ5MWQtOTNjZi00NGIyLWI4YTMtMzg0NzFiYTZkY2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzNDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4MjJlYzFlMDBhYzY5YjA0NDA4ZmEwOWQxZGMyOWExMDc1ZmFmZWJjN2MwNGY0ZmZjNTc1NDU4ZDI4NzkwMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TdaIzTazyW1VKRHcDMUUigv_lwmzI9sUIho1m8NNL1A)
> 
> 另外，在我这里reflector似乎始终都是用不了的。 ![QQ截图20240109211625](https://private-user-images.githubusercontent.com/12743204/295221412-2905c0a5-a365-4bc6-a470-213a01c28628.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MDg0NjAsIm5iZiI6MTcwNDgwODE2MCwicGF0aCI6Ii8xMjc0MzIwNC8yOTUyMjE0MTItMjkwNWMwYTUtYTM2NS00YmM2LWE0NzAtMjEzYTAxYzI4NjI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDEzNDkyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMDViMGRlMDFiYjBlMDE3Mjc0NjlmY2RjOWJhNTFkOTBmNTQ5MjIxNDdlZmJmYjg2YzcxYTZhOGU5OWYxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PgMjVlhxzllqFU0YA6okoo_v34CLlIadGaOcHpuYhww)

其实我的意思是，既然已经手动设置了自定义源，就没必要再启动reflector拉取源列表了吧。

**Comment by dewaltz** [comment]
Is this related to now to all mirrors.
Having the same issues in this post.

https://github.com/archlinux/archinstall/issues/2338

**Comment by WLongSAMA** [comment]
https://github.com/archlinux/archinstall/issues/2338#issuecomment-1899355047

禁用reflector服务之后可以正常安装
systemctl mask reflector.service

**Comment by svartkanin** [comment]
Can we please stick to using English when commenting

**Comment by WLongSAMA** [comment]
> Can we please stick to using English when commenting


Sorry, I'm not very good at English and can only rely on machine translation.
