### ISSUE TITLE
partition 3 on xxx have been written, but we have

### ISSUE THREAD

**Issue by Dlinuigh** [archlinux/archinstall#2329]
trying to install arch but found this…
https://0x0.st/HIcL.log
I will reboot to make any difference.
![Uploading IMG_1303.jpeg…]()

**Comment by svartkanin** [comment]
I have seen this error usually if there was a kernel update performed on the system you're running `archinstall` from without rebooting. 
If that was the case, a reboot and then retrying `archinstall` should fix the problem
