### ISSUE TITLE
Empty `/etc/hosts` file after installation

### ISSUE THREAD

**Issue by Gobidev** [archlinux/archinstall#2331]
After the installation the `/etc/hosts` file is empty, which causes some issues, like [Firefox taking very long to start](https://wiki.archlinux.org/title/Firefox#Firefox_startup_takes_very_long).

**Comment by codefiles** [comment]
This is covered in the _troubleshooting_ section of the _network configuration_ ArchWiki article, it is not required configuration. 

https://wiki.archlinux.org/title/Network_configuration#localhost_is_resolved_over_the_network

See the comments in [FS#56684](https://bugs.archlinux.org/task/56684).
