### ISSUE TITLE
Suggestion: OpenVMTools for automatic resizing

### ISSUE THREAD

**Issue by elppans** [archlinux/archinstall#2333]
When testing Archlinux on VMWare, the automatic resolution does not work, even when choosing to install the packages for "Virtual Box/VMWare" for X, in Archinstall.

The solution to this is to install OpenVMTools:

```
sudo pacman -S open-vm-tools
sudo systemctl enable --now vmtoolsd
```

This package should be automatically installed and activated along with the drivers for X when choosing this option

**Comment by svartkanin** [comment]
This seems very subjective and it may not be wanted be some people. 
We aim to install only necessary packages so that a working system is available

**Comment by elppans** [comment]
> This seems very subjective and it may not be wanted be some people. We aim to install only necessary packages so that a working system is available

If the installation is on a VM and whoever is installing chooses the option "... Graphics driver: VMWare/VirtualBox (open-source)", it is expected that at least the video resizing will work automatically.
If you don't have a single package that helps you do this, then this option is nothing more than an embellishment.
Since if it doesn't work, you can leave the option at the default (... Graphics driver: All open-source) which is the same.
