### ISSUE TITLE
Font installation instruction translation

### ISSUE THREAD

**Issue by yarons** [archlinux/archinstall#2344]
I'm looking at the following string for translation:
[`To be able to use this translation, please install a font manually that supports the language.`](https://github.com/archlinux/archinstall/blob/f107104103b74ac065a56bd94a0878f0d263e177/archinstall/locales/base.pot#L839)

When I think about it, this message is confusing because if it is translated and there's no font, the user won't be able to see it; it should be either English only or English + localized version.

**Comment by svartkanin** [comment]
This message is exactly due to those reasons not translated and only always shows in English

**Comment by svartkanin** [comment]
What do you mean with "they will change it"?

**Comment by yarons** [comment]
Never mind, I just realized this string is ignored regardless of the PO string state. Thanks :)
