### ISSUE TITLE
Context missing for a string

### ISSUE THREAD

**Issue by yarons** [archlinux/archinstall#2345]
https://github.com/archlinux/archinstall/blob/f107104103b74ac065a56bd94a0878f0d263e177/archinstall/locales/base.pot#L602

I couldn't find it in the code and am unsure what it means. Can I get some help with it?

**Comment by svartkanin** [comment]
If you can't find it in the code, it was removed, so no translation should be necessary. 
It referred to a value that was selected

**Comment by yarons** [comment]
Is there a way to remove it completely if it's unnecessary?

**Comment by svartkanin** [comment]
Unfortunately, generating these files doesn't remove existing unused ones. 
Also I'd rather keep them around because if they have been translated and we introduce them again then the translations are already available

**Comment by yarons** [comment]
I've been translating GNOME for several years now. All my old strings are being promoted to "fuzzy," once they are removed from the POT file and msgmerged again, they end up at the end of the file as comments; here are some examples:
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/po/he.po?ref_type=heads#L3109
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/main/po/he.po?ref_type=heads#L3109

They are still used for TM, reference, and fed to [OPUS](https://opus.nlpl.eu/GNOME.php) for years to come :)

Since this is a relatively vast and old project, there are many of these in the various apps.
