### ISSUE TITLE
Wrong instruction in README

### ISSUE THREAD

**Issue by yarons** [archlinux/archinstall#2346]
https://github.com/archlinux/archinstall/blob/f107104103b74ac065a56bd94a0878f0d263e177/README.md?plain=1#L31

This line says I should `cp` some python file, but I'm unsure where to and why; what am I missing?

**Comment by svartkanin** [comment]
Yeah that step is somewhat outdated. 
You can either run 
* `archinstall` on the ISO which is pre-installed and will use the `guided` version by default. 
* `archinstall --script guided` with which you can specify which script to run
* Same goes for the git version except you will run it with `python -m archinstall --script ...`

**Comment by yarons** [comment]
It's a very easy method if I don't want to recreate the ISO (assuming I've cloned the code from git) to test my translation changes.
Can you help me rewrite it?

**Comment by svartkanin** [comment]
You want to rewrite what?
If you want to run your code, clone tour fork, switch to the branch and run the sbove command `python -m archinstall`

**Comment by yarons** [comment]
LOL, that's way easier :)
I'll send a PR to modify the README and allow editing if you'd like to change something.

**Comment by svartkanin** [comment]
Thanks for that

**Comment by svartkanin** [comment]
this is fixed in the REAME
