### ISSUE TITLE
Pulsewire

### ISSUE THREAD

**Issue by Pictohenk1** [archlinux/archinstall#2368]
I installed pulsewire and i try to start the app but it's keeps giving me the error: pulseaudio.service not found. What should i do?

**Comment by svartkanin** [comment]
Can you share the installation log

**Comment by Pictohenk1** [comment]
![image](https://github.com/archlinux/archinstall/assets/126801250/17eecbb7-a65c-40a7-a570-fd4a0fab1cc6)

Here is the photo of the error but i can't get the install log back because i did this 2 days ago.

**Comment by svartkanin** [comment]
Without the install log this is very difficult to reproduce and debug.

**Comment by svartkanin** [comment]
This is the installation process for pipewire https://github.com/svartkanin/archinstall/blob/c0a7d45a83a8a6a8a7497362364d899a7ae8843d/archinstall/default_profiles/applications/pipewire.py#L13 we haven't noticed any issues with this recently and unless the install logs are provided this is difficult to debug so I'll be closing this issue for now
