### ISSUE TITLE
Add "printer setup" (just like "Audio" & "Network configuration") as option in main installation menu.

### ISSUE THREAD

**Issue by chalybesmith** [archlinux/archinstall#2374]
I would like to suggest adding as one of the main configuration options "printer setup" (installing CUPS, printer drivers, enabling cups.socket, default configs, adding user to appropriate groups etc.) since it seems like a reasonable component to expect from a fully setup desktop installation.

**Comment by svartkanin** [comment]
That would be a setup way beyond a basic installation and AFAIK there's no installer out there that would actually provide that functionality either as the variety of printers and drivers is massive.

**Comment by chalybesmith** [comment]
Any other distro installation manages to set up printing and the basic setup is literally three commands though:
`sudo pacman -S cups cups-pdf hplip gutenprint foomatic-db-engine foomatic-db foomatic-db-nonfree gsfonts && sudo systemctl enable cups && making user part of wheel group which is most likely done in other steps already`

Of course this will not cover any printer out there under the sun, but there is a reasonable default setup which one can expect from a basic desktop installation, likes of which are provided by distros like fedora, ubuntu, debian, opensuse, etc.

**Comment by svartkanin** [comment]
Archinatall aims to set up a minimal installation for a running system, printers are most definitely not required for a functioning basic system. 
This isn't necessarily a no to printers but to anything where there's not a good argument for it to be installed out of the box. If printers get added, then what about adding XYZ as well? It's a dangerous box that would be opened and difficult to close again or draw a line.
