### ISSUE TITLE
Plasma Install not working

### ISSUE THREAD

**Issue by hyperwriter1** [archlinux/archinstall#2380]
I used archinstall to attempt to install Arch, and I chose KDE Plasma as my DE. When it tried to install Plasma, it failed to do so, and I had to use archinstall again. This time, I chose MATE, and it worked fine.

I believe the issue to be related to Plasma 6 being released, and the script not being updated, but I'm not too sure.

**Comment by burnsco** [comment]
I believe this would be fixed by changing "plasma-wayland-session" in the kde.py script to "plasma-workspace".

**Comment by Schweeeeeeeeeeeeeeee** [comment]
Same problem

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> I believe this would be fixed by changing "plasma-wayland-session" in the kde.py script to "plasma-workspace".

Could you explain where that code is located so i can change it?

**Comment by SalvatoreNoschese** [comment]
Same here. plasma-wayland-session error
![PXL_20240306_174945866 MP](https://github.com/archlinux/archinstall/assets/16841896/b462a2be-9913-4f58-ae24-0d7e0c501482)

**Comment by hyperwriter1** [comment]
I will try that, and report back if it works.

**Comment by SalvatoreNoschese** [comment]
How I can edit archinstall? 😅

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> I will try that, and report back if it works.

Does work

**Comment by Schweeeeeeeeeeeeeeee** [comment]
> How I can edit archinstall? 😅

With vim cd /lib/idk... Until you find the file kde.py
Then google how to use vim

**Comment by SalvatoreNoschese** [comment]
![Uploading PXL_20240306_182316423.MP.jpg…]()


ATM I think Ed to do this 😅

**Comment by SalvatoreNoschese** [comment]
![PXL_20240306_182316423 MP](https://github.com/archlinux/archinstall/assets/16841896/167fd037-23f6-499a-8d8a-ae07714635b4)

ATM I thinked to do this 😅

**Comment by hyperwriter1** [comment]
Thank you all for the assistance.

**Comment by lustigo** [comment]
> > How I can edit archinstall? 😅
> 
> With vim cd /lib/idk... Until you find the file kde.py Then google how to use vim

The kde.py is found in /usr/lib/python3.11/site-packages/archinstall/default_profiles/kde.py

**Comment by SalvatoreNoschese** [comment]
![PXL_20240306_194726113 MP](https://github.com/archlinux/archinstall/assets/16841896/771720ad-8192-46fc-82ef-42e9fd75732a)
![PXL_20240306_194611818 MP](https://github.com/archlinux/archinstall/assets/16841896/e54f1fee-d0ae-4a7f-96e3-855e663548aa)

Indeed, found just some minutes ago thanks to 
pacman -Ql archinstall

**Comment by pumpkintheproot** [comment]
for users needing a fix:
`vim /usr/lib/python3.11/site-packages/archinstall/default_profiles/desktops/kde.py`
press `i`
go to `plasma-wayland-session` and edit it to `plasma-workstation`
press `esc` and type `:w`
this hopefully should be a temporary fix for the current problem

**Comment by intentionally-left-nil** [comment]
Funnily enough, that fails with `plasma-workstation` cannot be installed

**Comment by dylanmtaylor** [comment]
https://github.com/archlinux/archinstall/pull/2386 should fix it.
