### ISSUE TITLE
Kde cannot be installed

### ISSUE THREAD

**Issue by remussatala** [archlinux/archinstall#2383]
Kde cannot be installed. The package "plasma-wayland-session" no longer exists.

**Comment by pumpkintheproot** [comment]
known issue, see #2380

**Comment by dylanmtaylor** [comment]
I made a PR to change it to plasma-workspace here: https://github.com/archlinux/archinstall/pull/2386

**Comment by inmymum** [comment]
I was just going to create a report about this, pretty annoying but gnome is pretty great on this lower end laptop as well

**Comment by svartkanin** [comment]
Fixed with https://github.com/archlinux/archinstall/pull/2386, as there is no new release yet please clone the latest master and run it from there to workaround it for now
