### ISSUE TITLE
not found plasma-wayland- session

### ISSUE THREAD

**Issue by leessmin** [archlinux/archinstall#2388]
not found plasma-wayland- session

**Comment by leessmin** [comment]
error：target not found：plasma-wayland-session

emergency calling，

I like kde very much, how to do what, can not install my plasma, my heart is very painful

**Comment by leessmin** [comment]
Please help me.

**Comment by leessmin** [comment]
Help

**Comment by leessmin** [comment]
Help

**Comment by leessmin** [comment]
Help

**Comment by MFlossmann** [comment]
Fixed in #2386

**Comment by MFlossmann** [comment]
Has been fixed in #2381 . Execute `pacman -S archinstall` and try again. Please don't spam like this in the future.

**Comment by leessmin** [comment]
> Has been fixed in #2381 . Execute `pacman -S archinstall` and try again. Please don't spam like this in the future.

think you，but I tried it and it's still the same

**Comment by leessmin** [comment]
> Has been fixed in #2381 . Execute `pacman -S archinstall` and try again. Please don't spam like this in the future.

archinstall is updated, it seems that there is a problem with the source I selected，thank you for your help
