### ISSUE TITLE
PermissionError

### ISSUE THREAD

**Issue by DevLenn** [archlinux/archinstall#2396]
Hi,

i don't understand why i'm getting the following error by executing archinstall with root permission in order to install arch.
It's not my first time installing arch and i would consider my self as a somewhat-experienced arch user, it's just i've never experieced the following error:

![image](https://github.com/archlinux/archinstall/assets/138329707/91de581e-2415-48f9-93d2-18c01f2f3783)

Btw: it's running in a vmware VM

**Comment by Tacit-git** [comment]
vbox, error too

**Comment by Torxed** [comment]
Could it be that it's in use? Mounted or otherwise?

**Comment by DevLenn** [comment]
@Torxed nope, created two different virtual drives, and tried Installing on both of them. Same Error. 
Tried updating pacman keys and packages as well...

**Comment by Torxed** [comment]
Could you try:
`# python -c "with open('/dev/yourDevice', 'wb') as p:;  
  p.write(bytearray(1024))"`

And if that fails, which it should, try:
`# dd if=/dev/zero of=/dev/yourDevice bs=1 count=1024`

And if that fails, which it should not, try:
`# parted /dev/yourDevice mklabel gpt`

And lastly, can you post your virtual disk setup? If you have custom SCSI controllers etc I'll need those too, and root hubs if you have custom PCI hubs/ports. And the disk conf itself, such as `virtio` driver etc.

**Comment by DevLenn** [comment]
first command didn't fail, it just returned nothing. 
My disk is a .vmdk created automatically by vmware (File --> create new virtual machine --> typical (recommendet) --> i will install the operating system later -->  Linux 5x kernel 64 bit --> etc ), --> SCSI 128gb
I dont know which file the disk conf is in vmware workstation
Dont have any custom stuff

**Comment by Torxed** [comment]
Weird, the first command is just a copy paste from our source code oÔ.
I can give it a try with vmware workstation or something.

**Comment by DevLenn** [comment]
yeah idk, very weird, never had a probem with archinstall... 
does it work for you in vmware?

**Comment by HarbingerOfFire** [comment]
@DevLenn I'm having the same problem on vmware 17.5.2 Pro workstation. I have it configured under "Other Linux 6.x kernel 64-bit" with 32 gb of space.

**Comment by upbqdn** [comment]
I'm getting the same error on Framework 13 AMD.

**Comment by upbqdn** [comment]
> Could you try: `# python -c "with open('/dev/yourDevice', 'wb') as p:; p.write(bytearray(1024))"`
> 
> And if that fails, which it should, try: `# dd if=/dev/zero of=/dev/yourDevice bs=1 count=1024`
> 
> And if that fails, which it should not, try: `# parted /dev/yourDevice mklabel gpt`
> 
> And lastly, can you post your virtual disk setup? If you have custom SCSI controllers etc I'll need those too, and root hubs if you have custom PCI hubs/ports. And the disk conf itself, such as `virtio` driver etc.

All commands fail with access denied.

**Comment by bacon-cheeseburger** [comment]
I just downloaded the current arch iso (archlinux-2024.10.01-x86_64.iso) and ran into this problem trying to install it in VirtualBox. I deselected the loopback device per @HarbingerOfFire and the installer seems to be working now.  Not a great start for a first-time arch user using the installer defaults.

**Comment by codefiles** [comment]
> I found the best solution was to change the disk configuration from using the loopback (/dev/loop0) to using the vmware solution (/dev/sda)

> I deselected the loopback device per @HarbingerOfFire and the installer seems to be working now.

To be clear, no disk is ever selected by default, any disk selection will be from action taken by the user. With that said, the archiso loop device should not be an option per #563 and #1229.
