### ISSUE TITLE
NTFS ? Really ? Why ?

### ISSUE THREAD

**Issue by DarkXero-dev** [archlinux/archinstall#2407]
Hey 

I noticed you added NTFS as selectable FS type [Here](https://github.com/archlinux/archinstall/blob/c210cdcb8f0883ac13a6ee22aebb8f01f3043e09/archinstall/lib/disk/device_handler.py#L227) .. Why ? Selecting will result is unbootable system `unknown flesystem type`.. Tested it last night.. Maybe more needs to be done ? I am lost as to why one would select such a crappy FS for Linux xS

Feel free to correct me if am wrong..

**Comment by codefiles** [comment]
> I am lost as to why one would select such a crappy FS for Linux xS

You selected it though? Thanks for the laugh.

**Comment by DarkXero-dev** [comment]
Just for the lols yeah in a VM of course.. Are we April 1st already ? Did I miss time ?

**Comment by Torxed** [comment]
It's intended for the [root file system](https://github.com/archlinux/archinstall/pull/748), shared partition - or as a preparation for future dual-boot. :)

We did hide it behind the a [--advanced](https://github.com/archlinux/archinstall/pull/753) flag historically to avoid easy mistake from beginners as you mention.

**Comment by DarkXero-dev** [comment]
> It's intended for the [root file system](https://github.com/archlinux/archinstall/pull/748), shared partition - or as a preparation for future dual-boot. :)
> 
> We did hide it behind the a [--advanced](https://github.com/archlinux/archinstall/pull/753) flag historically to avoid easy mistake from beginners as you mention.

Ahh yess I know that but then why hide parallel downloads behind advanced then ? Unhide it so users don't have to use advanced n make any mistakes lol..
