### ISSUE TITLE
"No space left on device" error while configuring grub

### ISSUE THREAD

**Issue by Redcarred2** [archlinux/archinstall#2419]
Trying to install arch on-top of a windows install, EFI boot partition is 2gb, thanks in advance

https://0x0.st/HFeB.log

**Comment by Redcarred2** [comment]
ID10T error on my part, closing issue

**Comment by b3ldin** [comment]
Hi, I have this issue too and i still can't understand what happens, can you please tell how did you solve it?

**Comment by Mintsuki** [comment]
@Redcarred2 @b3ldin alternatively, it can be due to the efivars filesystem being mounted read only because the firmware does not allow writing to NVRAM for whatever reason, in which case you can try installing using the "removable" option in the bootloader submenu.
