### ISSUE TITLE
Unable to open /dev/sda1: Device or resource busy

### ISSUE THREAD

**Issue by Nydonidd** [archlinux/archinstall#2424]
Heyaaa, I'm trying to install arch on my chromebook but I keep coming across this one error that prevents me from finalising the installation. Does anyone know what I could do to fix it? I'm sorry, this is my first time using Linux, thank you!

Log: https://0x0.st/HCDx.log

**Comment by svartkanin** [comment]
How are you trying to install this on a Chromebook? It seems that one of the partitions is still active...
According to this https://wiki.archlinux.org/title/Chrome_OS_devices/Chromebook installing Arch will need way more things and Archinstall is not catering for that nor do I think that it ever will as this is a very difficult thing to keep maintained and and provided for all different chromebooks
