### ISSUE TITLE
Encryption does not work with GRUB

### ISSUE THREAD

**Issue by HanM23** [archlinux/archinstall#2429]
Done an installation today with /boot/efi fat32 partition, / btrfs with 2 sub and luks encrypted.
Installation is OK
But when i boot up, i got the following issue :

![image](https://github.com/archlinux/archinstall/assets/38059479/565808bb-3976-44c7-adbd-548235178193)

the uuid in the picture exists, this is the uuid of the decrypted root partition e.g. /dev/mapper/xxxxxx

When i edit the grub menu i have the following :+1: 

![image](https://github.com/archlinux/archinstall/assets/38059479/d16b64f9-f88f-4e96-aae1-6fffa7e2229e)

Is it a bug or do i have an issue with my system ?
Thanks

**Comment by svartkanin** [comment]
Can you provide the installation log file otherwise this is not possible to debug

**Comment by svartkanin** [comment]
without installation log this cannot be debugged
