### ISSUE TITLE
Error when archinstall tries to get its own version after updating it

### ISSUE THREAD

**Issue by Rust1667** [archlinux/archinstall#2436]
This happened to me after updating archinstall to the latest version before using it, with 
```
pacman -Sy
pacman -S archinstall
pacman -Qu archinstall
```
After updating, `pacman -Qu archinstall` doesnt work
So when archinstall tries to get its own version, the script breaks
`Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
`

For example this happens when in manual partioning I create a new partition, in the menu (even before the final step where you accept all the configs and start the install process)

Here is my full log https://0x0.st/Xsc3.log

**Comment by Rust1667** [comment]
I guess I could instead download the repo and run the script from there.
But Im worried about potential bugs since the vesion would still be getting checked from pacman, not from the github repo

**Comment by Rust1667** [comment]
alright I just realized this might just be a temporary pacman bug and I need to try to use the updated version from github in the meantime

**Comment by Rust1667** [comment]
OK I tried the git method.
I tried to do manual partitioning. Btrfs, but ext4 for the /home folder.
I got more errors, and when I try to run archinstall again, the main device "vda" where I was supposed to install, doesnt appear anymore in the Disk Configuration menu.
https://0x0.st/Xsc3.log

**Comment by svartkanin** [comment]
Please don't post multiple things under a single issue that makes it difficult to follow and to determine what is resolved and what isn't. 
The posted log doesn't have anything to do with the version check failure so I'll close this issue as the title is referring to a version check problem
