### ISSUE TITLE
Suggestions partition 20GB for root is absolutely bad idea

### ISSUE THREAD

**Issue by matinabbasi788** [archlinux/archinstall#2438]
If it asks for it or there's a way to change it.
Im Installed with that size of root and i hope that i can change it later but for some reason im not

So that's just an offer

Thank you all

**Comment by Jazztache** [comment]
This should be rectified, there needs to be an option to change how large the root and home partitions are when picking best-fit.

On a 64gb SSD, 20gb is very sensible like the one in the Steam Deck.
On a much larger machine running a 512GB SSD, it's way too small.

You should be able to easily pick 100GB without touching the manual partitioning screen. This should be a feature after picking what kind of filesystem you want.

**Comment by svartkanin** [comment]
If you go into manual partitioning you can suggest the same default partitioning layout and then modify the root partition

**Comment by svartkanin** [comment]
Also this should fix things https://github.com/archlinux/archinstall/pull/2415

**Comment by Jazztache** [comment]
> Also this should fix things #2415

Once the issues are worked out this looks like a good PR to merge. maybe 75GB for much bigger disks could be the max but 50GB is good.
