### ISSUE TITLE
Attempting to dual boot with existing windows: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal exit code [1]

### ISSUE THREAD

**Issue by drewboardman** [archlinux/archinstall#2441]
# Summary of disk management

 * [Here are photos of the installation configuration](https://imgur.com/a/kelZEsZ).
 * I have an existing windows installation on `dev/sda`. There is an existing boot partition from a previous dual boot I had set up.
 * I'm marking this partition for re-formatting, and mounting `/boot` here. Labeling as a `Boot, ESP`.
 * I have a `dev/sdc` hard drive that is 256gb.
 * For this drive, I am creating 1 partition. No splitting of `/root` and `/home`. No second boot partition.

# Results #1

Arch install accepts this configuration and goes through the installation process. It downloads and updates many packages. At the end, after about 25 minutes, I get a large error.

[`grub-install: /boot does not look like an EFI partition`](https://imgur.com/a/2DHGm7t)

## Attempted fix #1

reran arch install, this time changing the windows `/boot` partition to also change filesystem type to `ext4`

# Results #2

Goes through whole install again, fails at the end with `could not detect efi partition`.

[Screenshot of error](https://imgur.com/a/pbSt9m5)

## Attempted fix #2

I reran arch install with the windows disk boot partition mounted at `/boot/efi`.

# Results #3

Same error with grub unable to detect the efi partition

## Attempted fix #3

I'm just going to abandon grub and try `systemd-boot`. This time going back to `/boot` as the mount and not `/boot/efi`.

# Results #4

Goes through entire install and fails with cryptic error.

`SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal status code [1]`

[photo of full error](https://imgur.com/a/qvpB6aY)

## Attempted fix #4

I found [this thread](https://github.com/archlinux/archinstall/issues/2157) about the same error. Attempting this also fails with `['/usr/bin/arch-chroot', '/mnt/archinstall', 'bootctl', '--no-variables', 'install'] exited with abnormal exit code [1]`

## Help
I could use any help that you can give. I'm also concerned that messing with this windows boot partition was a mistake. I'm no longer able to boot into either windows or arch, and only the install medium for the arch iso.

**Comment by drewboardman** [comment]
If i do `lsblk` I see the mountpoint for that boot partition is `/mnt/archinstall/boot`. Why is archinstall attempting to run the command on `/mnt/archinstall`?

So I attempted to manually run:

`/usr/bin/arch-chroot /mnt/archinstall/boot bootctl install`

This fails with `mount point does not exists`. This is confusing.

So I ran the command from the errors and got:

`/usr/bin/arch-chroot /mnt/archinstall bootctl install`

This fails with `Couldn't find EFI system partition`

So I ran `mkdir /mnt/archinstall/boot/efi`. Then I ran:

`/usr/bin/arch-chroot /mnt/archinstall/boot/efi bootctl install`

This fails with `mount point does not exists`.

**Comment by svartkanin** [comment]
Did you follow https://github.com/archlinux/archinstall?tab=readme-ov-file#how-to-dual-boot-with-windows

**Comment by AmionSky** [comment]
I seem to have the same issue. Trying to install arch alongside existing windows 11. 
[install.log](https://github.com/archlinux/archinstall/files/15186575/install.log)

**Comment by AmionSky** [comment]
I just checked the failed install and it seems like it installed files into /boot on the target root partition (for me nvme1n1p1) but this directory should have been mounted to the efi partition?
Maybe it's a mount ordering issue?

**Comment by yrahul3910** [comment]
@drewboardman Thank you!! Yours was actually super helpful because I got the same errors! Okay so I set the mount point for my main disk as `/`, and set the mount point for the Boot/ESP partition as `/boot`. Then, and this is key: make sure that `/boot` partition is formatted as FAT32--this was what finally got it to work. And this is all with `systemd-boot` and not `grub`.

**Comment by codefiles** [comment]
> Maybe it's a mount ordering issue?

@AmionSky, that is what it is. From the log you provided:

```
Starting installation
Mounting partitions in order
Mounting /dev/nvme0n1p1: mount /dev/nvme0n1p1 /mnt/archinstall/boot
Mounting /dev/nvme1n1p1: mount /dev/nvme1n1p1 /mnt/archinstall
```

From the log provided by @malta-rf in #2566:

```
Starting installation...
Mounting ordered layout
Unlocking luks2 device: /dev/sdb1
cryptsetup open output: 
Mounting partition layout
Mounting /dev/sda1: mount /dev/sda1 /mnt/archinstall/boot
Mounting /dev/mapper/ainstsdb1: mount /dev/mapper/ainstsdb1 /mnt/archinstall
```
