### ISSUE TITLE
Can use archinstall reinstall and keep the content in btrfs subvolume @home

### ISSUE THREAD

**Issue by heheda123123** [archlinux/archinstall#2442]
I want reinstall my archlinux but keep the content in home directory.
below is my test in vmware.
reboot to enter archiso. 
run `archinstall`
I choose manually partition
in the partition list, I can only set partion unmark to be formatted.
Can add the function to unmark to be formatted in subvolume.
![image](https://github.com/archlinux/archinstall/assets/97490782/831d0fdd-38a3-44c5-82bb-3eb114eecef2)

**Comment by svartkanin** [comment]
Duplicate https://github.com/archlinux/archinstall/issues/2290
