### ISSUE TITLE
ISO wont build [workflow failing]

### ISSUE THREAD

**Issue by vojkovic** [archlinux/archinstall#2443]
The https://github.com/archlinux/archinstall/blob/master/build_iso.sh script is failing with the following error:

```
grub-mkstandalone: /usr/lib/libdevmapper.so.1.02: version `DM_1_02_197' not found (required by grub-mkstandalone)
```

Full logs from the failing workflow:
https://github.com/archlinux/archinstall/actions/runs/8411954875/job/23032180341

**Comment by stevleibelt** [comment]
Same issue on my [workflows](https://github.com/stevleibelt/arch-linux-live-cd-iso-with-zfs/actions) for building an archiso with archzfs included.
So more or less, just a comment to subscribe to this issue and link them.

**Comment by vojkovic** [comment]
@stevleibelt Great find. That's fixed it for my workflows. I've sent in a PR.

**Comment by Torxed** [comment]
Thanks for submitting a PR for this, well evaluate how this image behaves as these issues are transient usually, but hopefully this is more stable.
