### ISSUE TITLE
`pacman -S keyring` not preventing `error: libarchive: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust error: failed to commit transaction (invalid or corrupted package) Errors occurred, no packages were upgraded.`

### ISSUE THREAD

**Issue by sklbz** [archlinux/archinstall#2446]
Recently, I had this problem when trying to run `pacman -Syu` : 
```bash
error: libarchive: signature from "Levente Polyak (anthraxx) <levente@leventepolyak.net>" is unknown trust
:: File /var/cache/pacman/pkg/libarchive-3.7.2-2-x86_64.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] n
error: failed to commit transaction (invalid or corrupted package)
Errors occurred, no packages were upgraded.
```

So I runned `pacman -S keyring` to solve it. However I didn't fixes anything.

How can I update my system ?

**Comment by svartkanin** [comment]
This doesn't seem to have anything to do with archinstall

**Comment by sklbz** [comment]
> This doesn't seem to have anything to do with archinstall

I searched for solutions on my browser and this was the first github repo it gave me. And after actually looking its true.

Sorry for disturbing.

**Comment by earthquakeonmars** [comment]
https://bbs.archlinux.org/viewtopic.php?pid=1680594#p1680594
