### ISSUE TITLE
Installer python issue

### ISSUE THREAD

**Issue by raninduwathsal** [archlinux/archinstall#2454]
can't install after browsing documentation tried pacman -Sy archinstall, pacman -S dosfstools still doesnot work. using the archlinux-2024.04.01-x86_64.iso 

log file,
Hardware model detected: innotek GmbH VirtualBox; UEFI mode: False
Processor model detected: 11th Gen Intel(R) Core(TM) i3-1115G4 @ 3.00GHz
Memory statistics: 3603172 available out of 4014080 total installed
Virtualization detected: oracle; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": true,
        "size": "788 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0xb",
                "partuuid": "cd5f33a4-01",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "cd5f33a4",
                "rota": true,
                "size": "203 MiB",
                "tran": null,
                "type": "part",
                "uuid": "B190-C3F9"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0x83",
                "partuuid": "cd5f33a4-02",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "dos",
                "ptuuid": "cd5f33a4",
                "rota": true,
                "size": "65280 MiB",
                "tran": null,
                "type": "part",
                "uuid": "e26e3f7a-e9fc-489f-a9b9-5f5d814a5538"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "cd5f33a4",
        "rota": true,
        "size": "65536 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "iso9660",
        "fsuse_percentage": "100%",
        "fsver": "Joliet Extension",
        "log_sec": 2048,
        "mountpoint": "/run/archiso/bootmnt",
        "mountpoints": [
            "/run/archiso/bootmnt"
        ],
        "name": "sr0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sr0",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "e3fe56f2",
        "rota": true,
        "size": "955 MiB",
        "tran": "ata",
        "type": "rom",
        "uuid": "2024-04-01-17-57-21-00"
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: very weak
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Grub",
    "config_version": "2.7.2",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/sda",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "997d6e99-bdc4-43d2-aad3-d2415ae59b22",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 203
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 3
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "ext4",
                        "mount_options": [],
                        "mountpoint": "/",
                        "obj_id": "5f1ec327-1b96-4349-85dd-b575bf5ed949",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 68503470080
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 216006656
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "archlinux",
    "kernels": [
        "linux"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Singapore": [
                "https://sg.mirrors.cicku.me/archlinux/$repo/os/$arch",
                "https://mirror.sg.gs/archlinux/$repo/os/$arch",
                "https://mirror.jingk.ai/archlinux/$repo/os/$arch",
                "https://mirror.guillaumea.fr/archlinux/$repo/os/$arch",
                "https://mirror.aktkn.sg/archlinux/$repo/os/$arch",
                "https://mirror.0x.sg/archlinux/$repo/os/$arch",
                "https://download.nus.edu.sg/mirror/archlinux/$repo/os/$arch",
                "http://sg.mirrors.cicku.me/archlinux/$repo/os/$arch",
                "http://mirror.sg.gs/archlinux/$repo/os/$arch",
                "http://mirror.jingk.ai/archlinux/$repo/os/$arch",
                "http://mirror.guillaumea.fr/archlinux/$repo/os/$arch",
                "http://mirror.aktkn.sg/archlinux/$repo/os/$arch",
                "http://mirror.0x.sg/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "git"
    ],
    "parallel downloads": 0,
    "profile_config": null,
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Asia/Jayapura",
    "uki": false,
    "version": "2.7.2"
}
Unmounting all existing partitions: /dev/sda
Unmounting: /dev/sda1
Unmounting: /dev/sda2
Wiping partitions and metadata: /dev/sda
Creating partitions: /dev/sda
	Type: primary
	Filesystem: fat32
	Geometry: 6144 start sector, 415744 length
	Type: primary
	Filesystem: ext4
	Geometry: 421888 start sector, 133795840 length
Unmounting all existing partitions: /dev/sda
Unmounting: /dev/sda1
Unmounting: /dev/sda2
Formatting filesystem: /usr/bin/mkfs.fat -F32 /dev/sda1
partition information found: {'name': 'sda1', 'path': '/dev/sda1', 'pkname': 'sda', 'size': '203 MiB', 'log_sec': 512, 'pttype': 'dos', 'ptuuid': 'c6e99fc9', 'rota': True, 'tran': None, 'partn': 1, 'partuuid': 'c6e99fc9-01', 'parttype': '0xb', 'uuid': 'CF5E-C8C4', 'fstype': 'vfat', 'fsver': 'FAT32', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Formatting filesystem: /usr/bin/mkfs.ext4 -F /dev/sda2
partition information found: {'name': 'sda2', 'path': '/dev/sda2', 'pkname': 'sda', 'size': '65280 MiB', 'log_sec': 512, 'pttype': 'dos', 'ptuuid': 'c6e99fc9', 'rota': True, 'tran': None, 'partn': 2, 'partuuid': 'c6e99fc9-02', 'parttype': '0x83', 'uuid': 'a5c454db-93c2-401a-8e11-ea7198d57ee7', 'fstype': 'ext4', 'fsver': '1.0', 'fsavail': None, 'fsuse_percentage': None, 'type': 'part', 'mountpoint': None, 'mountpoints': [], 'fsroots': [], 'children': []}
Starting installation
Mounting partitions in order
Mounting /dev/sda2: mount /dev/sda2 /mnt/archinstall
Mounting /dev/sda1: mount /dev/sda1 /mnt/archinstall/boot
Waiting for time sync (timedatectl show) to complete.
Waiting for automatic mirror selection (reflector) to complete.
Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Archinstall will not install any ucode.
The multilib flag is not set. This system will be installed without multilib repositories enabled.
The testing flag is not set. This system will be installed without testing repositories enabled.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'grub']
Enabling periodic TRIM
Enabling service fstrim.timer
A new package mirror-list has been created: /mnt/archinstall/etc/pacman.d/mirrorlist
Setting up swap on zram
Installing packages: ['zram-generator']
Enabling service systemd-zram-setup@zram0.service
Adding bootloader Grub to /dev/sda1
Installing packages: ['grub']
kernel parameters: zswap.enabled=0 rootfstype=ext4
GRUB boot partition: /dev/sda1
GRUB boot partition: /dev/sda1
Creating user rani
Setting password for rani
Enabling sudo permissions for rani
Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'rani', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: su: Module is unknown

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 332, in run_as_a_module
    main()
  File "/usr/lib/python3.11/site-packages/archinstall/__init__.py", line 327, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 256, in <module>
    perform_installation(archinstall.storage.get('MOUNT_POINT', Path('/mnt')))
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 118, in perform_installation
    with Installer(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 109, in __exit__
    raise exc_val
  File "/usr/lib/python3.11/site-packages/archinstall/scripts/guided.py", line 179, in perform_installation
    audio_config.install_audio_config(installation)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/models/audio_configuration.py", line 46, in install_audio_config
    PipewireProfile().install(installation)
  File "/usr/lib/python3.11/site-packages/archinstall/default_profiles/applications/pipewire.py", line 40, in install
    self._enable_pipewire_for_all(install_session)
  File "/usr/lib/python3.11/site-packages/archinstall/default_profiles/applications/pipewire.py", line 35, in _enable_pipewire_for_all
    install_session.arch_chroot('systemctl enable --user pipewire-pulse.service', run_as=user.username)
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 497, in arch_chroot
    return self.run_command(cmd)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/installer.py", line 491, in run_command
    return SysCommand(f'/usr/bin/arch-chroot {self.target} {cmd}')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.11/site-packages/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'rani', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: su: Module is unknown

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st

**Comment by svartkanin** [comment]
This is fixed in the latest release
