### ISSUE TITLE
Nvidia-dkms installs wrong

### ISSUE THREAD

**Issue by dieBakterie** [archlinux/archinstall#2456]
When i use Desktop w/nvidia-proprietary it doen't do the nvidia-dkms stuff correctly nor at all. I'm using archinstall 2.7.2 and zen-kernel only. It does it in the process but when i boot in it i need to do it manually, `nvidia.conf` `MODULE=(nvidia ....)`...

**Comment by svartkanin** [comment]
Without an install log this can't be debugged

**Comment by dieBakterie** [comment]
what was the log format/the needed logs again? It's through installing w/archinstall 2.7.2 w/profile Desktop and Hyprland and nvidia-proprietary and there are no errors it just installs dkms and when i boot in chroot and check the modules arent added the nvidia.conf is missing and so on.

**Comment by svartkanin** [comment]
/var/log/archinstall/install.log

**Comment by dieBakterie** [comment]
[install.log](https://github.com/archlinux/archinstall/files/14964093/install.log)
Here is the log.

**Comment by svartkanin** [comment]
According to the log 
```
 "profile_config": {
        "gfx_driver": null,
        "greeter": null,
        "profile": {
            "custom_settings": {},
            "details": [],
            "main": "Minimal"
        }
    },
```

you did not install any driver nor profile so there will not be any nvidia packages isntalled

**Comment by dieBakterie** [comment]
Sry have only this one forgot that i did minimal to Cut down what i've to downoad, sorry.
