### ISSUE TITLE
mountpoint not found

### ISSUE THREAD

**Issue by coreymwamba** [archlinux/archinstall#2475]
Fresh install onto SSD (btrfs format). Any ideas on what went wrong? 

[XHK6.log](https://github.com/archlinux/archinstall/files/15095471/XHK6.log)

**Comment by svartkanin** [comment]
```
    "disk_config": {
        "config_type": "pre_mounted_config",
        "mountpoint": "/mnt"
    },
```

Pre-mounted option does not work for Btrfs

**Comment by codefiles** [comment]
> Pre-mounted option does not work for Btrfs

That is false. As always, give it a try, especially before commenting with confidence.

**Comment by svartkanin** [comment]
You're correct. I run through a pre-mounted installation with Btrfs and it does work as expected. 
From the logs provided it seems that `sda3` was mounted and `sda2` was mounted when archinstall was run
```
...
   "mountpoints": [
       "/mnt"
   ],
    "name": "sda3",
...
   "mountpoints": [
       "/mnt/boot"
   ],
   "name": "sda2",
...
```

but I fail to see the actual btrfs volumes being mounted. I would expect something like 
```
  "mountpoints": [
      "/mnt/archinstall/.snapshots", 
      "/mnt/archinstall/var/cache/pacman/pkg", 
      "/mnt/archinstall/var/log", 
      "/mnt/archinstall/home", 
      "/mnt/archinstall"
  ],
```

Could it be that the subvolumes themselves where not mounted which could explain the error

**Comment by coreymwamba** [comment]
I managed to work around my issue by doing an old-fashioned install; but it isn't actually solved since I'm not sure what went wrong. Was there a step I missed?

**Comment by svartkanin** [comment]
If you had setup btrfs outside archinstall you need to mount all volumes to the respective mount points first before running the installer

**Comment by coreymwamba** [comment]
Thanks. I hadn't mounted /home.
