### ISSUE TITLE
exited with abnormal exit code [1]

### ISSUE THREAD

**Issue by JeromeSchmied** [archlinux/archinstall#2477]
0x0.st/XHZN.log

**Comment by svartkanin** [comment]
You're using an older version 2.7.1, please use the latest release and try again.

**Comment by svartkanin** [comment]
It may be a duplicate of https://github.com/archlinux/archinstall/issues/2452 as well

**Comment by JeromeSchmied** [comment]
after marking both `/` and `/boot` for formatting, everything worked as expected

**Comment by svartkanin** [comment]
Could you possibly run the command that failed manually and share if there's any output from it? 

/usr/bin/arch-chroot /mnt/archinstall bootctl --no-variables install

Basically run this when you get the error

**Comment by JeromeSchmied** [comment]
no, I've already managed to install Archlinux, and there's `No such file or directory` as `/usr/bin/arch-chroot` or `/mnt/archinstall`
