### ISSUE TITLE
Manual Partitioning failed on b8052c5

### ISSUE THREAD

**Issue by utuhiro78** [archlinux/archinstall#2479]
Manual Partitioning failed on b8052c5.
[install.log](https://github.com/archlinux/archinstall/files/15139144/install.log)

There is no problem on v2.8.0.

**Comment by svartkanin** [comment]
How did you run archinstall?
Are you saying that the latest 2.8.0 is working fine?

**Comment by utuhiro78** [comment]
> How did you run archinstall? Are you saying that the latest 2.8.0 is working fine?

I tested them first on my local Arch Linux. archinstall-git crashed, archinstall-2.8.0 works fine.
I thought "Maybe archinstall-git can't manage the mounted system partition", so I tested them on USB stick.

Boot EndeavourOS from USB stick.
(I always run archinstall on XFCE or KDE Plasma. Linux Console can't show Japanese characters properly.)
Run Konsole.

## archinstall-git

```
yay -Syy
yay -S --needed python-build python-packaging python-sphinx_rtd_theme 
yay -S archinstall-git
sudo archinstall
```

[archinstall-git.webm](https://github.com/archlinux/archinstall/assets/34818411/2c768e3d-2057-4cdb-84ae-3c7e7a482593)

## archinstall-2.8.0

```
yay -S archinstall
sudo archinstall
```

[archinstall-2.8.0.webm](https://github.com/archlinux/archinstall/assets/34818411/f8f13082-c774-42d3-907f-77b980fbac36)

**Comment by svartkanin** [comment]
Thanks for reporting this I managed to reproduce it and a fix is up

**Comment by utuhiro78** [comment]
Thank you so much, svartkanin!
It works fine.

[archinstall-git-fixed.webm](https://github.com/archlinux/archinstall/assets/34818411/796e549a-7202-409f-baab-54a46c201dc8)
