### ISSUE TITLE
AttributeError: module 'pathlib' has no attribute 'Paht'

### ISSUE THREAD

**Issue by D4v1dH03** [archlinux/archinstall#248]
This is a serious typo in the code of luks.py

I tried to create an encrypted luks partitiom but end up with this error in the title

Please fix as soon as possible

**Comment by D4v1dH03** [comment]
![IMG_20210408_194641_078.jpg](https://user-images.githubusercontent.com/81270448/114121555-68c89880-98a3-11eb-9e2d-a194f104678d.jpg)

**Comment by Torxed** [comment]
I would recommend to use the `archinstall` package and not git for production use.
As we're working on salying a few bugs that existed in the `archinstall` package the source may change every hour or so.
But it's good that you catched this and reported it! `master` and `torxed-2.2.0` are constantly moving however :)
