### ISSUE TITLE
No module named 'archinstall'

### ISSUE THREAD

**Issue by LunasShade** [archlinux/archinstall#2486]
I tried to start archinstall after pacman -Syy and it says "File "usr/bin/archinstall", line 5, in <module> from archinstall import run_as_a_module
ModuleNotFoundError: No module named 'archinstall'"

**Comment by svartkanin** [comment]
Seems to be the same as https://github.com/archlinux/archinstall/issues/1810

**Comment by LunasShade** [comment]
It seems the same, but mine goes further. When I do 'pacman -Sy python archinstall' how it is said in #1810 I get another error:

![image](https://github.com/archlinux/archinstall/assets/55425467/a96c587f-bb43-4c04-82e2-7f0d7bfd8fbd)
