### ISSUE TITLE
0x0.st/XXBx.log

### ISSUE THREAD

**Issue by TRESAS777** [archlinux/archinstall#2487]
https://0x0.st/XXBx.log

**Comment by TRESAS777** [comment]
after trying to install with archinstall the laptop stopped working, it turns on and stays in the logo, it does not even enter the bio, do you know what it can be?

**Comment by svartkanin** [comment]
I run an installation with the same configuration and I went through fine. My suggestion would be to try another installation and see if that works

**Comment by svartkanin** [comment]
First logo being your laptop vendors logo? What laptop is it?
Have you tried unplugging everything including the live USB and powering it on?

**Comment by TRESAS777** [comment]
> https://0x0.st/XXBx.log 
Hewlett-Packard HP Pavilion dv4 Notebook PC
after the installation failed, i restarted the computer and it got stuck in the hp logo, the first one that appears to enter the bios, and all the shortcuts that can be done when turning on, i try to enter the bios or boot device but it keeps loading and does not pass from there, even without the usb. so i am destroyed, since you can not access the most basic thing that is the bios or boot devices to try to fix it with a bootable usb.

**Comment by svartkanin** [comment]
Archinstall would not cause a laptop to completely meltdown, according to the error you posted the partitioning was successful but retrieving the newly created partition failed for some reason. This does not impact the actual functionality of the laptop. 
Without any more information we can't help you debugging

**Comment by TRESAS777** [comment]
I will give as much information as possible, it is an old computer, before I had windows, I decided to install linux and I was trying different distributions but for some reason some drivers failed, so I installed another different distro, before arch I had installed 3 different ones, and when installing with archinstall the first time I got an error so I decided to update the packages and I did it again but it did not work, everything was fine until I deleted the disk to create the partitions and there was that failure, I do not know if there on the disk was the boot to enter the bios and keyboard shortcuts to turn on the computer, and only the hp logo appears and shows as if it were loading the shortcut as bios or quel enter and then does not pass. I'm going to try connecting another hard drive which by the way is ata type, and I think that's all. thank you very much.
![WhatsApp Image 2024-05-04 at 3 28 33 AM](https://github.com/archlinux/archinstall/assets/103174712/b1eb50a4-0e2c-473b-a8f5-7dd2d22bbb11)

**Comment by svartkanin** [comment]
It says press F10 for BIOS setup options, are you able to perform that?

**Comment by TRESAS777** [comment]
That's exactly what I did and it doesn't go beyond that screen, it doesn't load anything else. That's what happens if I press F9 to boot from USB, that's why I say it was destroyed if I can't even access the bios, the truth is I don't know what happened.
