### ISSUE TITLE
ModuleNotFoundError: No module named 'parted' (#1810 but with further problems)

### ISSUE THREAD

**Issue by LunasShade** [archlinux/archinstall#2490]
It seems the same, but mine goes further. When I do 'pacman -Sy python archinstall' how it is said in #1810 I get another error:

![image](https://github.com/archlinux/archinstall/assets/55425467/a96c587f-bb43-4c04-82e2-7f0d7bfd8fbd)

_Ursprünglich gepostet von @LunasShade in https://github.com/archlinux/archinstall/issues/2486#issuecomment-2090568438_

**Comment by svartkanin** [comment]
Try `pacman -S python-simple-term-menu python-pyarted archinstall`

**Comment by svartkanin** [comment]
This may also be helpful https://github.com/archlinux/archinstall/issues/1781

**Comment by LunasShade** [comment]
error: target not found: python-pyarted

**Comment by LunasShade** [comment]
Did you mean python-pyparted?

... yeah it's python-pyparted 🫠

**Comment by svartkanin** [comment]
Yeah that one :)

**Comment by LunasShade** [comment]
Yes, it works now

**Comment by RomitSingh1999** [comment]
after following these steps I got:
`import error : /user/lib/libcrypto.so.3: version 'OPENSSL_3.3.0' not found`

**Comment by Tryingtoinstallarchlinux** [comment]
> Try `pacman -S python-simple-term-menu python-pyarted python archinstall`

No usable package repositories configured

**Comment by Tryingtoinstallarchlinux** [comment]
Svartkanin's command just comes back with another error

**Comment by SpyrMark** [comment]
tried everithing in the thread so far and i got `ModuleNotFoundError: No module named 'pydantyc'`

**Comment by Jaquan1314** [comment]
> Tried everithing in the thread so far and i got `ModuleNotFoundError: No module named 'pydantic'`

same here

**Comment by SpyrMark** [comment]
Also i downloaded every new packege requirment and everytime it asks for a new one , wth happend to archinstall ??

**Comment by Salman7236** [comment]
> Good news !!!! `pacman -S python-annotated-types` is the last requirment

I had to do three more packages after this one. "python-pydantic-core python-typing_extensions python-pydantic"

**Comment by volmak-extrudex-junks** [comment]
> > Good news !!!! `pacman -S python-annotated-types` is the last requirment
> 
> I had to do three more packages after this one. "python-pydantic-core python-typing_extensions python-pydantic"
> 
> Here's the full command: `pacman -Sy archinstall archlinux-keyring python python-pyparted python-simple-term-menu pyhton-annotated-types python-pydantic python-pydantic-core python-typing_extensions`

Yes, this did work !!!

**Comment by Badboy-7** [comment]
yeah i did everything here mostly. i did run the full command and typed archinstall but nothing happened. it still asked for modules. ive figured out how to manually install the modules. however now it keeps asking me for "typing_extentions" and ive tried running the command "pacman -S python-typing_extensions" but it says target not found. can anyone please help me with this

**Comment by Jaquan1314** [comment]
> yeah i did everything here mostly. i did run the full command and typed archinstall but nothing happened. it still asked for modules. ive figured out how to manually install the modules. however now it keeps asking me for "typing_extentions" and ive tried running the command "pacman -S python-typing_extensions" but it says target not found. can anyone please help me with this

even though it says `"typing_extensions"` I believe the right command to install this was `pacman -S python-typing-extensions`. So no underscore just a dash.

**Comment by Badboy-7** [comment]
> > yeah i did everything here mostly. i did run the full command and typed archinstall but nothing happened. it still asked for modules. ive figured out how to manually install the modules. however now it keeps asking me for "typing_extentions" and ive tried running the command "pacman -S python-typing_extensions" but it says target not found. can anyone please help me with this
> 
> even though it says `"typing_extensions"` I believe the right command to install this was `pacman -S python-typing-extensions`. So try with no underscore just a dash.

yeah i tried it now but now it just says "error: target not found : python-typing-extentions"

**Comment by Salman7236** [comment]
> yeah i tried it now but now it just says "error: target not found : python-typing-extentions"

It's [python-typing_extensions](https://archlinux.org/packages/extra/any/python-typing_extensions/)

**Comment by Badboy-7** [comment]
> > yeah i tried it now but now it just says "error: target not found : python-typing-extentions"
> 
> It's [python-typing_extensions](https://archlinux.org/packages/extra/any/python-typing_extensions/) (hyphen then underscore)

i still get the same problem

**Comment by Salman7236** [comment]
> > > yeah i tried it now but now it just says "error: target not found : python-typing-extentions"
> > 
> > 
> > It's [python-typing_extensions](https://archlinux.org/packages/extra/any/python-typing_extensions/) (hyphen then underscore)
> 
> i still get the same problem

(Ok I literally don't know if this will work or not, I'm just guessing)

Try fixing your mirrors with reflector and then running ```pacman -Syy```

Then try installing the package again. 

(Also, I don't think it's that important to update archinstall, unless you are experiencing a problem that might be fixed by updating. So yesterday, when doing another reinstall, instead of installing all these packages again, I just rebooted the system, updated the keyring (not archinstall), ran archinstall and it installed everything without any problem.

**Comment by Badboy-7** [comment]
> > > > yeah i tried it now but now it just says "error: target not found : python-typing-extentions"
> > > 
> > > 
> > > It's [python-typing_extensions](https://archlinux.org/packages/extra/any/python-typing_extensions/) (hyphen then underscore)
> > 
> > 
> > i still get the same problem
> 
> (Ok I literally don't know if this will work or not, I'm just guessing)
> 
> Try fixing your mirrors with reflector and then running `pacman -Syy`
> 
> Then try installing the package again.
> 
> (Also, I don't think it's that important to update archinstall, unless you are experiencing a problem that might be fixed by updating. So yesterday, when doing another reinstall, instead of installing all these packages again, I just rebooted the system, updated the keyring (not archinstall), ran archinstall and it installed everything without any problem.

Alright so I just ran the pacman -Syy command and most of the things I saw was "Error:failed to retrieve file" and "Warning: fatal error from mirror". I am not sure what to do at this point since the youtube tutorial I was watching helped me to get at this point. However I want to know will it be possible to get another Type of easier Linux to install on this computer and will I be able to put the other version on this USB stick and the try to install that?

**Comment by abhimangs** [comment]
I had the same issue, and this worked for me:

**`pacman -Sy archinstall archlinux-keyring python python-pyparted python-simple-term-menu python-annotated-types python-pydantic python-pydantic-core python-typing_extensions`**

Give it a try and see if it resolves your issue!  
If any other missing module is mentioned, let me know the details of that error. These are the missing packages that resolved the issue for me.

**Comment by abhimangs** [comment]
> Also i downloaded every new packege requirment and everytime it asks for a new one , wth happend to archinstall ??

Dude use **`pacman -Sy archinstall archlinux-keyring python python-pyparted python-simple-term-menu python-annotated-types python-pydantic python-pydantic-core python-typing_extensions`**

**Comment by sttern** [comment]
I'm still having " error:  target not found: python-typing_extentions and if I type in archinstall or python archinstall in the console anyway, I get ModulenotFoundError: No module named 'pydantic'

Help😭

**Comment by sttern** [comment]
> Good news !!!! `pacman -S python-annotated-types` is the last requirment 

I'm still having the pydantic error

**Comment by abhimangs** [comment]
> > Good news !!!! `pacman -S python-annotated-types` is the last requirment
> 
> I'm still having the pydantic error

Use **`pacman -Sy archinstall archlinux-keyring python python-pyparted python-simple-term-menu python-annotated-types python-pydantic python-pydantic-core python-typing_extensions`**

The above code installs all the necessary python modules to run the `archinstall` or you should avoid running the `sudo pacman -S archinstall` at the start and skip the steps. Most youtube videos do not skip but skipping solves the problem or just use install all modules mentioned above.

**Comment by Salman7236** [comment]
> > Good news !!!! `pacman -S python-annotated-types` is the last requirment
> 
> I'm still having the pydantic error

New arch ISO just got released, try that.
