### ISSUE TITLE
Root partition should be "Linux root"

### ISSUE THREAD

**Issue by crwn1337** [archlinux/archinstall#2503]
Small nitpick, but the root partition should be "Linux root" instead of "Linux filesystem" for systems without /etc/fstab.

https://wiki.gentoo.org/wiki/Handbook:AMD64/Installation/Disks#Creating_the_root_partition
https://www.freedesktop.org/software/systemd/man/latest/systemd-gpt-auto-generator.html
https://wiki.archlinux.org/title/partitioning#/

**Comment by codefiles** [comment]
I do not think this is a nitpick and I have been meaning to submit something for it. Thank you for bring attention to this and great job reporting.

Related: https://wiki.archlinux.org/title/Systemd#GPT_partition_automounting
