### ISSUE TITLE
Change default boot size from 512Mi

### ISSUE THREAD

**Issue by uhthomas** [archlinux/archinstall#2504]
512Mi is tiny, and fills up quickly with modern Linux + fallback, especially so if using another kernel too (like linux-zen). Disks are huge these days and a more sensible default of 4Gi would be great, as to avoid difficult resizing in future. Users can still make this default value smaller if they are genuinely using a small disk, but for the majority of users it's better to not have this headache.

**Comment by uhthomas** [comment]
Related #2314

**Comment by codefiles** [comment]
It was increased to 1GiB to conform with the suggested size of the installation guide; see 1064f74.

**Comment by uhthomas** [comment]
> It was increased to 1 GiB to conform with the suggested size given by the installation guide; see 1064f74.

This is great, thank you! Is 1Gi enough? Would 2Gi or 4Gi be more suitable? What do you think? As mentioned before, 512Mi is tight even with just one kernel + fallback and so 1Gi is going to be the same with two kernels.

**Comment by codefiles** [comment]
I think it is best left to the ArchWiki and for achinstall to conform.
