### ISSUE TITLE
extra packages installed without selecting

### ISSUE THREAD

**Issue by RashadGasimli** [archlinux/archinstall#2523]
Hi, when I select other kernels expect vanilla arch linux kernel and select nvidia (open gpu kernel modules or proprieatry) on archinstall, nvidia (non-dkms) and vanilla linux kernel will be installed. Here is log.

[install.log](https://github.com/archlinux/archinstall/files/15493897/install.log)

**Comment by svartkanin** [comment]
Which packages exactly are you not expecting to be installed?

**Comment by RashadGasimli** [comment]
> Which packages exactly are you not expecting to be installed?
vanilla linux kernel (linux).

**Comment by RashadGasimli** [comment]
> Which packages exactly are you not expecting to be installed?

"linux"

**Comment by svartkanin** [comment]
From the log file you provided I see 
```
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-zen', 'btrfs-progs', 'intel-ucode']
Installing packages: ['linux-zen-headers']
```
which corresponds to the kernel you selected 

```
    "kernels": [
        "linux-zen"
    ],
```

**Comment by RashadGasimli** [comment]
> From the log file you provided I see
> 
> ```
> Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-zen', 'btrfs-progs', 'intel-ucode']
> Installing packages: ['linux-zen-headers']
> ```
> 
> which corresponds to the kernel you selected
> 
> ```
>     "kernels": [
>         "linux-zen"
>     ],
> ```

yes but "linux" package is installed automaticly

**Comment by cbrbygones** [comment]
> > From the log file you provided I see
> > ```
> > Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux-zen', 'btrfs-progs', 'intel-ucode']
> > Installing packages: ['linux-zen-headers']
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which corresponds to the kernel you selected
> > ```
> >     "kernels": [
> >         "linux-zen"
> >     ],
> > ```
> 
> yes but "linux" package is installed automaticly

Did you ensure you unchecked the `linux` kernel when you went into `Select Kernels`? 
Maybe it was left checked while you checked `linux-zen`. [See this screenshot.](https://i0.wp.com/www.lorenzobettini.it/wp-content/uploads/2022/07/archinstall-9.png?ssl=1)

**Comment by svartkanin** [comment]
I did an installation with the exact same configuration as you provided and I cannot see the package `linux` being installed

**Comment by svartkanin** [comment]
As this isn't reproducible and without more information this can't be debugged further so I'll close this for now

**Comment by rashadgasimli** [comment]
> As this isn't reproducible and without more information this can't be debugged further so I'll close this for now

Yes, it wad fixed. Anyway thank you
