### ISSUE TITLE
Error with archinstall on MacBook9,1

### ISSUE THREAD

**Issue by benfindlay** [archlinux/archinstall#2524]
I get an error when running the archinstall script. Screenshots attached of the error and (since the error seems to pertain to the NVMe in some way) the output of the lsblk command.

I have used multiple different versions of the Arch ISO, and have tried performing an update via pacman prio to install. They always seem to produce the same error.

Please can someone advise?
![archinstall_error](https://github.com/archlinux/archinstall/assets/3143803/9bc99190-70c9-4d95-9568-b696d03c2077)
![lsblk](https://github.com/archlinux/archinstall/assets/3143803/98fd6dc0-5d18-46c5-a1d5-2b5ce4894f9f)

**Comment by C0rn3j** [comment]
A quick dirty fix might be ignoring devices smaller than 1GiB, but it's odd that the block device is there in the first place if it's some kind of unpopulated slot.

Can you upload the full output from `dmesg`, or at least the part with `nvme0n2` initialization?

**Comment by C0rn3j** [comment]
https://github.com/archlinux/archinstall/blob/b2d29eeba3b110e458bee752f0fc67f670c7aa36/archinstall/lib/disk/device_handler.py#L60-L62

A condition would have to go here, similar to the existing one that checks device type.  
That was more of a suggestion to whoever is going to try and fixing this.  
There's probably a more proper way to fix this.
