### ISSUE TITLE
Don't format partition if it's not selected to format

### ISSUE THREAD

**Issue by samuelvw01** [archlinux/archinstall#2525]
During manual setup I had selected Linux partition to format and I just assigned /boot to my EFI partition (did not selected it to format). Yet archlinux decided to format it. Thanks god I managed it to cancel just 1 second before end of countdown.

**Comment by svartkanin** [comment]
Can you provide the log file please

**Comment by samuelvw01** [comment]
Sorry installing Arch when I'm tired wasn't the best idea 😅. I have a NVME and I saw formating nvme0n1**p1** but it was nvme0n1. Everything works now.
