### ISSUE TITLE
failed install

### ISSUE THREAD

**Issue by garybig** [archlinux/archinstall#2534]
install fail
![failed arch](https://github.com/archlinux/archinstall/assets/75581054/1aca6868-d84f-44d8-91d1-7eb7510c0649)

**Comment by svartkanin** [comment]
Can you please upload the log file

**Comment by garybig** [comment]
The directions "curl -F'file=@var/log/archinstall/install.log' https://0x0/st
came back with "server not found"

**Comment by HarbingerOfFire** [comment]
Are you using vmware?

**Comment by garybig** [comment]
No. Install would have been to an internal SSD drive.

**Comment by fiver22** [comment]
> The directions "curl -F'file=@var/log/archinstall/install.log' https://0x0/st came back with "server not found"

should be https://0x0.st not /st

**Comment by svartkanin** [comment]
Unless there's a full log file provided this can't be debugged properly. 

I'll be closing this for now unless it can be confirmed it's still broken on master
