### ISSUE TITLE
seems to fail on existing linux partitions? log in description

### ISSUE THREAD

**Issue by fiver22** [archlinux/archinstall#2538]
I had the install fail multiple times with what seems to be a fairly standard set of selections http://0x0.st/Xckf.log

I then tried running fdisk and manually deleting partitions/setting gpt, then reran archinstall selecting best effort  suggest partition layout, fs selection, no to separate home (i expect this has nothing to do with it), confirm and exit.

this seems to allow install as expected. 

related? #2534

**Comment by megamind1230** [comment]
ok I guess related also https://0x0.st/XTa2.log

**Comment by svartkanin** [comment]
This should be resolved in master

**Comment by svartkanin** [comment]
I'll be closing this for now unless it can be confirmed it's still broken on master
