### ISSUE TITLE
Errors out when installing via Manual Partitioning

### ISSUE THREAD

**Issue by AKM7622** [archlinux/archinstall#2540]
Error calling lsblk: lsblk: /dev/nvme0n1p1: not a block device
{
   "blockdevices": [

   ]
}

Error calling lsblk: lsblk: /dev/sdb1: not a block device
{
   "blockdevices": [

   ]
}

Hardware model detected: Dell Inc. Latitude 3510; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
Memory statistics: 6564188 available out of 7889952 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "792 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "1788a2f5-dfd9-407a-96a9-26c26da92df4",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "046228f4-ec9b-0b4f-a3bc-47f3cc54343f",
                "rota": true,
                "size": "953869 MiB",
                "tran": null,
                "type": "part",
                "uuid": "BEFEB0EAFEB09C59"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "046228f4-ec9b-0b4f-a3bc-47f3cc54343f",
        "rota": true,
        "size": "953869 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "273a7db7-ee20-4089-aa78-a1fda5f7c792",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "c8c8905a-32af-4b7a-a298-6abaaa371807",
                "rota": true,
                "size": "7632 MiB",
                "tran": null,
                "type": "part",
                "uuid": "1455-78B3"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "c8c8905a-32af-4b7a-a298-6abaaa371807",
        "rota": true,
        "size": "7633 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "5e3117cc-c669-4135-8021-c7dba6934aeb",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "100 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "9A1B-E4EE"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae",
                "partuuid": "b955d4aa-d19b-4cbf-9ff4-3fb79bf866e2",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "16 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p3",
                "partn": 3,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "7e0a9308-6eec-4f48-9c8e-9009177962db",
                "path": "/dev/nvme0n1p3",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "177520 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "BADE236BDE231EDF"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p4",
                "partn": 4,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "be3e06d0-cdc0-463e-aff1-3a6924a4e23f",
                "path": "/dev/nvme0n1p4",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "1024 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p5",
                "partn": 5,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "3ee7ee3b-2ad8-4b28-83b5-d45e2dbc804b",
                "path": "/dev/nvme0n1p5",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "65536 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
        "rota": false,
        "size": "244198 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Error calling lsblk: lsblk: /dev/nvme0n1p1: not a block device
{
   "blockdevices": [

   ]
}

Hardware model detected: Dell Inc. Latitude 3510; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i3-10110U CPU @ 2.10GHz
Memory statistics: 6554752 available out of 7889952 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation CometLake-U GT2 [UHD Graphics] (rev 02)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "792 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "1788a2f5-dfd9-407a-96a9-26c26da92df4",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "046228f4-ec9b-0b4f-a3bc-47f3cc54343f",
                "rota": true,
                "size": "953869 MiB",
                "tran": null,
                "type": "part",
                "uuid": "BEFEB0EAFEB09C59"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "046228f4-ec9b-0b4f-a3bc-47f3cc54343f",
        "rota": true,
        "size": "953869 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "273a7db7-ee20-4089-aa78-a1fda5f7c792",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "c8c8905a-32af-4b7a-a298-6abaaa371807",
                "rota": true,
                "size": "7632 MiB",
                "tran": null,
                "type": "part",
                "uuid": "1455-78B3"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "c8c8905a-32af-4b7a-a298-6abaaa371807",
        "rota": true,
        "size": "7633 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "5e3117cc-c669-4135-8021-c7dba6934aeb",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "100 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "9A1B-E4EE"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae",
                "partuuid": "b955d4aa-d19b-4cbf-9ff4-3fb79bf866e2",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "16 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p3",
                "partn": 3,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "7e0a9308-6eec-4f48-9c8e-9009177962db",
                "path": "/dev/nvme0n1p3",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "177520 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "BADE236BDE231EDF"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p4",
                "partn": 4,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "be3e06d0-cdc0-463e-aff1-3a6924a4e23f",
                "path": "/dev/nvme0n1p4",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "1024 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p5",
                "partn": 5,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "3ee7ee3b-2ad8-4b28-83b5-d45e2dbc804b",
                "path": "/dev/nvme0n1p5",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
                "rota": false,
                "size": "65536 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "38dc4c84-4315-4a64-a0d8-f26eb4c8226e",
        "rota": false,
        "size": "244198 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: very weak
Password strength: very weak
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/kde.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [
        "multilib"
    ],
    "archinstall-language": "English",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Systemd-boot",
    "config_version": "2.8.0",
    "debug": false,
    "disk_config": {
        "config_type": "manual_partitioning",
        "device_modifications": [
            {
                "device": "/dev/nvme0n1",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": "/dev/nvme0n1p1",
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": null,
                        "obj_id": "0bfa092d-9f89-429c-a686-9b2b8a2da259",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 104857600
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "sectors",
                            "value": 2048
                        },
                        "status": "existing",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": "/dev/nvme0n1p2",
                        "flags": [],
                        "fs_type": "",
                        "mount_options": [],
                        "mountpoint": null,
                        "obj_id": "8055dd22-77c8-4712-8ed4-4880e5c0c384",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 16777216
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "sectors",
                            "value": 206848
                        },
                        "status": "existing",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": "/dev/nvme0n1p3",
                        "flags": [],
                        "fs_type": "ntfs",
                        "mount_options": [],
                        "mountpoint": null,
                        "obj_id": "8f1f77d1-2175-4065-bb91-9fb21734ea5c",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 186143254016
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "sectors",
                            "value": 239616
                        },
                        "status": "existing",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": "/dev/nvme0n1p4",
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "35d0cb38-7129-4d82-9da8-7f5093d39142",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1073741824
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "sectors",
                            "value": 363802624
                        },
                        "status": "modify",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": "/dev/nvme0n1p5",
                        "flags": [],
                        "fs_type": "",
                        "mount_options": [],
                        "mountpoint": "/",
                        "obj_id": "b5bca520-e47a-4184-9691-1132bad4070d",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 68719476736
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "sectors",
                            "value": 365899776
                        },
                        "status": "modify",
                        "type": "primary"
                    }
                ],
                "wipe": false
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "potato",
    "kernels": [
        "linux-zen"
    ],
    "locale_config": {
        "kb_layout": "us",
        "sys_enc": "UTF-8",
        "sys_lang": "en_US"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "China": [
                "https://mirrors.xjtu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.wsyu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.sjtug.sjtu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.shanghaitech.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.qvq.net.cn/archlinux/$repo/os/$arch",
                "https://mirrors.qlu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.nju.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.jxust.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.jlu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.jcut.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.hust.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch",
                "https://mirrors.aliyun.com/archlinux/$repo/os/$arch",
                "https://mirror.nyist.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.zju.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.wsyu.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.shanghaitech.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.qvq.net.cn/archlinux/$repo/os/$arch",
                "http://mirrors.nju.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.neusoft.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.jxust.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.jlu.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.jcut.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.hust.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.cqu.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.bfsu.edu.cn/archlinux/$repo/os/$arch",
                "http://mirrors.aliyun.com/archlinux/$repo/os/$arch",
                "http://mirrors.163.com/archlinux/$repo/os/$arch",
                "http://mirror.nyist.edu.cn/archlinux/$repo/os/$arch",
                "http://mirror.lzu.edu.cn/archlinux/$repo/os/$arch"
            ],
            "India": [
                "https://mirrors.nxtgen.com/archlinux-mirror/$repo/os/$arch",
                "https://mirror.sahil.world/archlinux/$repo/os/$arch",
                "https://mirror.nag.albony.in/archlinux/$repo/os/$arch",
                "https://mirror.maa.albony.in/archlinux/$repo/os/$arch",
                "https://mirror.albony.in/archlinux/$repo/os/$arch",
                "https://mirror.4v1.in/archlinux/$repo/os/$arch",
                "https://in.mirrors.cicku.me/archlinux/$repo/os/$arch",
                "https://in-mirror.garudalinux.org/archlinux/$repo/os/$arch",
                "http://mirrors.nxtgen.com/archlinux-mirror/$repo/os/$arch",
                "http://mirror.sahil.world/archlinux/$repo/os/$arch",
                "http://mirror.4v1.in/archlinux/$repo/os/$arch",
                "http://in.mirrors.cicku.me/archlinux/$repo/os/$arch",
                "http://in-mirror.garudalinux.org/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {
        "type": "nm"
    },
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "neofetch",
        "nano",
        "git"
    ],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "All open-source",
        "greeter": "ly",
        "profile": {
            "custom_settings": {
                "Hyprland": {
                    "seat_access": "polkit"
                }
            },
            "details": [
                "Hyprland"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": true,
    "timezone": "Asia/Kolkata",
    "uki": false,
    "version": "2.8.0"
}
Unmounting all existing partitions: /dev/nvme0n1
Unmounting: /dev/nvme0n1p1
Unmounting: /dev/nvme0n1p2
Unmounting: /dev/nvme0n1p3
Unmounting: /dev/nvme0n1p4
Unmounting: /dev/nvme0n1p5
Use existing device: /dev/nvme0n1
Creating partitions: /dev/nvme0n1
Delete existing partition: /dev/nvme0n1p4
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 332, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 327, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 245, in <module>
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 54, in perform_filesystem_operations
    device_handler.partition(mod, partition_table=partition_table)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 521, in partition
    self._setup_partition(part_mod, modification.device, disk, requires_delete=requires_delete)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 364, in _setup_partition
    filesystem = FileSystem(type=part_mod.safe_fs_type.value, geometry=geometry)
                                 ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 699, in safe_fs_type
    raise ValueError('File system type is not set')
ValueError: File system type is not set

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st

**Comment by svartkanin** [comment]
This should be fixed in master
