### ISSUE TITLE
Grub doesnt recognize Windows after installing Arch through Archinstall

### ISSUE THREAD

**Issue by st-am** [archlinux/archinstall#2542]
After using archinstall to install Arch, when I start my computer I only get options to boot into Arch Linux or UEFI Firmware Settings, I used the command os-prober and it recognizes Windows Boot Manager, but it doesnt get added to Grub.

**Comment by svartkanin** [comment]
For a dual boot setup, did you follow the instructions https://github.com/archlinux/archinstall?tab=readme-ov-file#how-to-dual-boot-with-windows ?

**Comment by st-am** [comment]
> For a dual boot setup, did you follow the instructions https://github.com/archlinux/archinstall?tab=readme-ov-file#how-to-dual-boot-with-windows ?

I forgot to mention that I have windows on a seperate drive

**Comment by svartkanin** [comment]
You may have to boot from the usb, mount all relevant partitions.
Install os-prober and try something like `sudo grub-mkconfig -o /boot/grub/grub.cfg`

**Comment by st-am** [comment]
I realised that i had GRUB_DISABLE_OS_PROBER commented, after I uncommented it and ran the command you gave me it worked.
