### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by JCDentonCore** [archlinux/archinstall#2546]
Hardware model detected: ASRock B650E Steel Legend WiFi; UEFI mode: True
Processor model detected: AMD Ryzen 7 7800X3D 8-Core Processor
Memory statistics: 30538520 available out of 32468848 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/7900M] (rev cc)'])
Disk states before installing: [
    {
        "children": [],
        "fsavail": 0,
        "fsroots": [
            "."
        ],
        "fstype": "squashfs",
        "fsuse_percentage": "100%",
        "fsver": "4.0",
        "log_sec": 512,
        "mountpoint": "/run/archiso/airootfs",
        "mountpoints": [
            "/run/archiso/airootfs"
        ],
        "name": "loop0",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/loop0",
        "pkname": null,
        "pttype": null,
        "ptuuid": null,
        "rota": false,
        "size": "792 MiB",
        "tran": null,
        "type": "loop",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda1",
                "partn": 1,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "c9c2357e-e295-4d5b-bb96-7b28f628bb3c",
                "path": "/dev/sda1",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "737dfce0-8976-4bc4-b6d3-58618b4affd8",
                "rota": true,
                "size": "890000 MiB",
                "tran": null,
                "type": "part",
                "uuid": "aee0de63-af3d-444e-acec-bb5a6b77950f"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sda2",
                "partn": 2,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "5ede402b-3ae3-460a-8ff3-2aa873270338",
                "path": "/dev/sda2",
                "pkname": "sda",
                "pttype": "gpt",
                "ptuuid": "737dfce0-8976-4bc4-b6d3-58618b4affd8",
                "rota": true,
                "size": "63866 MiB",
                "tran": null,
                "type": "part",
                "uuid": "d9161d54-da43-419e-97f6-7451f7cefcbc"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sda",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sda",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "737dfce0-8976-4bc4-b6d3-58618b4affd8",
        "rota": true,
        "size": "953869 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdb1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "38c6bec9-a012-4d17-9572-9b1de2f14505",
                "path": "/dev/sdb1",
                "pkname": "sdb",
                "pttype": "gpt",
                "ptuuid": "b005911f-33d9-403f-a42a-3cae27478cfc",
                "rota": true,
                "size": "476939 MiB",
                "tran": null,
                "type": "part",
                "uuid": "269E42AC24E008EB"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdb",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdb",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "b005911f-33d9-403f-a42a-3cae27478cfc",
        "rota": true,
        "size": "476940 MiB",
        "tran": "sata",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [
                    {
                        "children": [],
                        "fsavail": null,
                        "fsroots": [],
                        "fstype": "iso9660",
                        "fsuse_percentage": null,
                        "fsver": "Joliet Extension",
                        "log_sec": 512,
                        "mountpoint": null,
                        "mountpoints": [],
                        "name": "ventoy",
                        "partn": null,
                        "parttype": null,
                        "partuuid": null,
                        "path": "/dev/mapper/ventoy",
                        "pkname": "sdc1",
                        "pttype": "dos",
                        "ptuuid": "6aae9122",
                        "rota": true,
                        "size": "1114 MiB",
                        "tran": null,
                        "type": "dm",
                        "uuid": "2024-06-01-09-07-18-00"
                    }
                ],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdc1",
                "partn": 1,
                "parttype": "0x7",
                "partuuid": "3806a954-01",
                "path": "/dev/sdc1",
                "pkname": "sdc",
                "pttype": "dos",
                "ptuuid": "3806a954",
                "rota": true,
                "size": "117965 MiB",
                "tran": null,
                "type": "part",
                "uuid": "BA48E59048E54BA7"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT16",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "sdc2",
                "partn": 2,
                "parttype": "0xef",
                "partuuid": "3806a954-02",
                "path": "/dev/sdc2",
                "pkname": "sdc",
                "pttype": "dos",
                "ptuuid": "3806a954",
                "rota": true,
                "size": "32 MiB",
                "tran": null,
                "type": "part",
                "uuid": "223C-F3F8"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "sdc",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/sdc",
        "pkname": null,
        "pttype": "dos",
        "ptuuid": "3806a954",
        "rota": true,
        "size": "117998 MiB",
        "tran": "usb",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 4096,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme1n1p1",
                "partn": 1,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "eb3eef72-8d44-a767-acc2-c0f3ff6064d2",
                "path": "/dev/nvme1n1p1",
                "pkname": "nvme1n1",
                "pttype": "gpt",
                "ptuuid": "5c497ba2-1d24-4bb4-8a84-e0626a4fb3fe",
                "rota": false,
                "size": "1907472 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "01DA983B66231AC0"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 4096,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme1n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme1n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "5c497ba2-1d24-4bb4-8a84-e0626a4fb3fe",
        "rota": false,
        "size": "1907729 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    },
    {
        "children": [
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "vfat",
                "fsuse_percentage": null,
                "fsver": "FAT32",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p1",
                "partn": 1,
                "parttype": "c12a7328-f81f-11d2-ba4b-00a0c93ec93b",
                "partuuid": "0d01b505-60ba-4452-9038-bb5d4ed002fb",
                "path": "/dev/nvme0n1p1",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "878cd1a6-d40c-40ac-b211-cf3c20c138a6",
                "rota": false,
                "size": "1024 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "88A7-1643"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ext4",
                "fsuse_percentage": null,
                "fsver": "1.0",
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p2",
                "partn": 2,
                "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                "partuuid": "b2af1a17-e2ed-4bcf-b581-d66f9fbdaf78",
                "path": "/dev/nvme0n1p2",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "878cd1a6-d40c-40ac-b211-cf3c20c138a6",
                "rota": false,
                "size": "1399521 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "44f3555c-0a49-40ff-a92f-9d24a52a06fb"
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": null,
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p3",
                "partn": 3,
                "parttype": "e3c9e316-0b5c-4db8-817d-f92df00215ae",
                "partuuid": "83be41a3-8469-4a0c-a087-bbf7f43deff8",
                "path": "/dev/nvme0n1p3",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "878cd1a6-d40c-40ac-b211-cf3c20c138a6",
                "rota": false,
                "size": "16 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": null
            },
            {
                "children": [],
                "fsavail": null,
                "fsroots": [],
                "fstype": "ntfs",
                "fsuse_percentage": null,
                "fsver": null,
                "log_sec": 512,
                "mountpoint": null,
                "mountpoints": [],
                "name": "nvme0n1p4",
                "partn": 4,
                "parttype": "ebd0a0a2-b9e5-4433-87c0-68b6b72699c7",
                "partuuid": "2f86331b-06cc-4e38-b2d0-3efa3ebe77c3",
                "path": "/dev/nvme0n1p4",
                "pkname": "nvme0n1",
                "pttype": "gpt",
                "ptuuid": "878cd1a6-d40c-40ac-b211-cf3c20c138a6",
                "rota": false,
                "size": "507166 MiB",
                "tran": "nvme",
                "type": "part",
                "uuid": "AC0EFB1B0EFADD70"
            }
        ],
        "fsavail": null,
        "fsroots": [],
        "fstype": null,
        "fsuse_percentage": null,
        "fsver": null,
        "log_sec": 512,
        "mountpoint": null,
        "mountpoints": [],
        "name": "nvme0n1",
        "partn": null,
        "parttype": null,
        "partuuid": null,
        "path": "/dev/nvme0n1",
        "pkname": null,
        "pttype": "gpt",
        "ptuuid": "878cd1a6-d40c-40ac-b211-cf3c20c138a6",
        "rota": false,
        "size": "1907729 MiB",
        "tran": "nvme",
        "type": "disk",
        "uuid": null
    }
]
Checking version...
Failed determine pacman version: ['/usr/bin/pacman', '-Qu', 'archinstall'] exited with abnormal exit code [1]: [?25l[?25h
Password strength: débil
Password strength: débil
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/custom.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktop.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/minimal.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/server.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/tailored.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/xorg.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/applications/pipewire.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/awesome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/bspwm.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/budgie.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cinnamon.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/cutefish.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/deepin.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/enlightenment.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/gnome.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/hyprland.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/i3.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/kde.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/lxqt.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/mate.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/qtile.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/sway.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/desktops/xfce4.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/__init__.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/cockpit.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/docker.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/httpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/lighttpd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/mariadb.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/nginx.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/postgresql.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/sshd.py
Importing profile: /usr/lib/python3.12/site-packages/archinstall/default_profiles/servers/tomcat.py
 -- Chosen configuration --
{
    "__separator__": null,
    "additional-repositories": [
        "multilib",
        "testing"
    ],
    "archinstall-language": "Spanish",
    "audio_config": {
        "audio": "pipewire"
    },
    "bootloader": "Systemd-boot",
    "config_version": "2.8.0",
    "debug": false,
    "disk_config": {
        "config_type": "default_layout",
        "device_modifications": [
            {
                "device": "/dev/nvme0n1",
                "partitions": [
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [
                            "Boot",
                            "ESP"
                        ],
                        "fs_type": "fat32",
                        "mount_options": [],
                        "mountpoint": "/boot",
                        "obj_id": "e658860b-f3eb-453d-8631-3fc1248636dc",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "GiB",
                            "value": 1
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "MiB",
                            "value": 1
                        },
                        "status": "create",
                        "type": "primary"
                    },
                    {
                        "btrfs": [],
                        "dev_path": null,
                        "flags": [],
                        "fs_type": "ext4",
                        "mount_options": [],
                        "mountpoint": "/",
                        "obj_id": "6d6bfac3-56a0-4275-80c9-cfa86dbdf5aa",
                        "size": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1999323095040
                        },
                        "start": {
                            "sector_size": {
                                "unit": "B",
                                "value": 512
                            },
                            "unit": "B",
                            "value": 1074790400
                        },
                        "status": "create",
                        "type": "primary"
                    }
                ],
                "wipe": true
            }
        ]
    },
    "disk_encryption": null,
    "hostname": "archlinux",
    "kernels": [
        "linux-zen"
    ],
    "locale_config": {
        "kb_layout": "es",
        "sys_enc": "UTF-8",
        "sys_lang": "es_ES"
    },
    "mirror_config": {
        "custom_mirrors": [],
        "mirror_regions": {
            "Worldwide": [
                "https://mirror.rackspace.com/archlinux/$repo/os/$arch",
                "https://geo.mirror.pkgbuild.com/$repo/os/$arch",
                "http://mirror.rackspace.com/archlinux/$repo/os/$arch"
            ]
        }
    },
    "network_config": {},
    "no_pkg_lookups": false,
    "ntp": true,
    "offline": false,
    "packages": [
        "firefox",
        "gparted",
        "ksystemlog",
        "openrgb",
        "goverlay",
        "steam",
        "kcalc",
        "spectacle",
        "kdiskmark",
        "corectrl",
        "kdeconnect",
        "bleachbit"
    ],
    "parallel downloads": 0,
    "profile_config": {
        "gfx_driver": "AMD / ATI (open-source)",
        "greeter": "sddm",
        "profile": {
            "custom_settings": {
                "Kde": {}
            },
            "details": [
                "Kde"
            ],
            "main": "Desktop"
        }
    },
    "save_config": null,
    "script": "guided",
    "silent": false,
    "skip_ntp": false,
    "skip_version_check": false,
    "swap": false,
    "timezone": "America/Montevideo",
    "uki": false,
    "version": "2.8.0"
}
Unmounting all existing partitions: /dev/nvme0n1
Unmounting: /dev/nvme0n1p1
Unmounting: /dev/nvme0n1p2
Unmounting: /dev/nvme0n1p3
Unmounting: /dev/nvme0n1p4
Wiping partitions and metadata: /dev/nvme0n1
Creating partitions: /dev/nvme0n1
	Type: primary
	Filesystem: fat32
	Geometry: 2048 start sector, 2097152 length
	Type: primary
	Filesystem: ext4
	Geometry: 2099200 start sector, 3904927920 length
Unmounting all existing partitions: /dev/nvme0n1
Unmounting: /dev/nvme0n1p1
Unmounting: /dev/nvme0n1p2
Unmounting: /dev/nvme0n1p3
Error calling lsblk: lsblk: /dev/nvme0n1p3: not a block device
{
   "blockdevices": [

   ]
}

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1113, in _fetch_lsblk_info
    result = SysCommand(cmd).decode()
             ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 365, in __init__
    self.create_session()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 414, in create_session
    with SysCommandWorker(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/general.py", line 197, in __exit__
    raise SysCallError(
archinstall.lib.exceptions.SysCallError: ['/usr/bin/lsblk', '--json', '--bytes', '--output', '+name,path,pkname,size,log-sec,pttype,ptuuid,rota,tran,partn,partuuid,parttype,uuid,fstype,fsver,fsavail,fsuse%,type,mountpoint,mountpoints,fsroots', '/dev/nvme0n1p3'] exited with abnormal exit code [32]: lsblk: /dev/nvme0n1p3: not a block device
{
   "blockdevices": [

   ]
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 332, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 327, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 245, in <module>
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 55, in perform_filesystem_operations
    device_handler.format(mod, enc_conf=self._enc_config)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 304, in format
    self._umount_all_existing(device_mod.device_path)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 483, in _umount_all_existing
    self.umount(partition.path, recursive=True)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 564, in umount
    lsblk_info = get_lsblk_info(mountpoint)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1136, in get_lsblk_info
    if infos := _fetch_lsblk_info(dev_path):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_model.py", line 1121, in _fetch_lsblk_info
    raise DiskError(f'Failed to read disk "{dev_path}" with lsblk')
archinstall.lib.exceptions.DiskError: Failed to read disk "/dev/nvme0n1p3" with lsblk

Archinstall experienced the above error. If you think this is a bug, please report it to
https://github.com/archlinux/archinstall and include the log file "/var/log/archinstall/install.log".

Hint: To extract the log from a live ISO 
curl -F'file=@/var/log/archinstall/install.log' https://0x0.st

**Comment by svartkanin** [comment]
This should be fixed in master and will be released shortly

**Comment by JCDentonCore** [comment]
> This should be fixed in master and will be released shortly

Thank you!
