### ISSUE TITLE
[suggestion]

### ISSUE THREAD

**Issue by 7r9s3t5u1v2w4x6y8z0a** [archlinux/archinstall#2554]
add a profile set by default ex: kde plasma and when a noobie glosses over the profile section they wont be stuck in a tty not knowing what to do

**Comment by Torxed** [comment]
The whole principle of arch is to not force things on users and the motto is KISS. So as much as possible in archinstall is optional.

I'll go ahead and close this. I understand the good intent behind this idea, but it's not something that rhymes with Arch's principles.
