### ISSUE TITLE
the auto partitioning size for /boot is too small

### ISSUE THREAD

**Issue by ali50m** [archlinux/archinstall#2556]
Hi, I'm new to Arch linux! I am trying to installing the latest arch linux with `archinstall` in my PC these days. After successfully logining into the desktop Arch, I think the size for /boot partition might be a little small.

I read some issues in this repo said that the boot partion should have been increased.

I tried the same installation steps in VMPlayer and took some screenshots, please let me know if it is by-design behavior or a bug? Thanks!

[installation screen shots](https://github.com/ali50m/archinstall_disk)

**Comment by Schanzation** [comment]
The new 2.8.1 version doesn't work at all for me. None of the partitioning settings will apply.

**Comment by svartkanin** [comment]
Adding issues as comments to other unrelated issues isn't helpful and difficult to follow. @Schanzation if you experienced anything unexpected please open a separate issue and provide a reproducible description as well as the log file

**Comment by svartkanin** [comment]
@ali50m can you please provide the install log from /var/log/archinstall/install.log

**Comment by svartkanin** [comment]
@ali50m the update to 1GiB /boot size was done recently for a system with GPT but for any other system the size of 203MiB is still applied 

https://github.com/archlinux/archinstall/blob/master/archinstall/lib/interactions/disk_conf.py#L210-L216

```
def _boot_partition(sector_size: disk.SectorSize, using_gpt: bool) -> disk.PartitionModification:
	flags = [disk.PartitionFlag.Boot]
	if using_gpt:
		start = disk.Size(1, disk.Unit.MiB, sector_size)
		size = disk.Size(1, disk.Unit.GiB, sector_size)
		flags.append(disk.PartitionFlag.ESP)
	else:
		start = disk.Size(3, disk.Unit.MiB, sector_size)
		size = disk.Size(203, disk.Unit.MiB, sector_size)
```

According the wiki https://wiki.archlinux.org/title/Partitioning#Example_layouts
> In other cases, it is recommended to set the partition type to [Extended Boot Loader (XBOOTLDR) Partition](https://uapi-group.org/specifications/specs/boot_loader_specification/#the-partitions) which is GPT partition type GUID BC13C2FF-59E6-4262-A352-B275FD6F7172 (ea00 type for [gdisk](https://wiki.archlinux.org/title/Gdisk)) or MBR partition type ID ea.

> In both cases the suggested size for the partition is 1 GiB, which should give enough space to house multiple kernels. If still in doubt, 4 GiB ought to be enough for anybody.

This may have been updated now and the implementation is out of date.

**Comment by svartkanin** [comment]
You can increase the size during the installation
1. Disk configuration
2. Manual partitioning
3. Select your drive
4. Suggest partition layout
5. Now select your layout
6. The table will now contain all paritions from the default layout
7. Create your own partitions with the desired sizes
