### ISSUE TITLE
Selecting a single partition (ext4) it still creates different partitions for root and home.

### ISSUE THREAD

**Issue by KevinAlavik** [archlinux/archinstall#2562]
### Which ISO version are you using?

"2024-06-01"

### The installation log

```json
... (Im reporting this after it happend, noob mistake
```

#### Description of the issue
So ive had this issue a bunch of times, when i pick to create a ext4 filesystem on my drive and select to not create multiple partitions (beacuse im lazy). And it installs fine but when i reboot i get 2 partitions.
![image](https://github.com/archlinux/archinstall/assets/95900603/6643b076-4f14-4c28-85b7-379ca01bd38a)

I dont know if this happens for other file system types. I can debug that tho.

As i said in install log, this was a bit back. So i dont have logs since i just now rememberd the issue. Reason to why i remembered it is beacuse my root partition is basicly full. 

And also a suggestion is to be able to set the size of the partitions, you probably can do this and im just blind but if you cant please add that.

Thanks.

**Comment by svartkanin** [comment]
It's difficult to see what happened without a log. If the configuration was wrong or the installation...

**Comment by Torxed** [comment]
I suspect "Use separate home" was selected during best effort partitioning.
I think we can close this and we'll reopen next time when the log gets attached. 

Apologies that we can't be of more help.

**Comment by KevinAlavik** [comment]
@Torxed No i pressed thedont seperate or whatever

**Comment by Torxed** [comment]
Ok, then we definitely need that log to figure out what happened sadly :/

**Comment by KevinAlavik** [comment]
i can try to replicate tomorrow
