### ISSUE TITLE
Israel is missing in mirror list

### ISSUE THREAD

**Issue by counter-code** [archlinux/archinstall#2567]
### describe the request

I launched _archinstall_ a few days ago and noticed that Israel got removed from the mirrors list for some reason. The latest release log doesn't say anything about this. This is **ridiculous** and quite **antisemitic**. Please fix it immediately~~

here some screenshots:
![Screenshot 2024-07-09 222346](https://github.com/archlinux/archinstall/assets/108093983/ff53d279-d943-4b06-9dd4-cc520dfc2c22)
![Screenshot 2024-07-09 222404](https://github.com/archlinux/archinstall/assets/108093983/3acd1716-9783-444c-8ea4-704dc159b8a7)

Thanks and have a good day/night~ _uwu~_

(I'm from Israel btw)

**Comment by Torxed** [comment]
This is most likely temporary.
As we do not "ship" any mirror lists, these are all fetched during `archinstall` execution:
* https://github.com/archlinux/archinstall/blob/50d269957a602d99aacdda047506eb555058f6a9/archinstall/lib/mirrors.py#L299-L318

Verifying by visting https://archlinux.org/mirrorlist/?protocol=https&protocol=http&ip_version=4&ip_version=6&use_mirror_status=on
I also note that there's no mirrors in Israel currently with `http(s)` with IPv4/IPv6 with status `on`.

But aside from that, this is not an archinstall bug so I'll go ahead and close this ticket.
I'll have to separately investigate why the three active mirrors are not listed via the Mirrors repo: https://gitlab.archlinux.org/archlinux/arch-mirrors/-/issues/
