### ISSUE TITLE
Reuse DHCP

### ISSUE THREAD

**Issue by Anuskuss** [archlinux/archinstall#2590]
### Which ISO version are you using?

2024.07.01

### The installation log

```json
-
```

### describe the problem

I extracted `initramfs-linux.img`, `vmlinuz-linux` and `airootfs.sfs` from `archlinux-2024.07.01-x86_64.iso` and put them on my server so they can be loaded via iPXE (network boot) in case I break my Arch install. But the problem is that `eth0` is not respecting my DHCP settings and even though archiso has the same MAC address, it gets a new IP address and doesn't use my DNS server.
I tried the `ip=dhcp`/`ip=192.168.0.254::192.168.0.1:255.255.255.0::eth0:none` kernel parameter but that seems to be ignored (it's needed for downloading `airootfs.sfs` though). Same with `hostname=`.
It becomes a problem once I reboot my machine because then I get a completely new IP address (e.g. PC is 192.168.10, reboot, archiso is 192.168.0.11, reboot, PC is 192.168.0.12) which in turn breaks my NFS mount forcing me to having to restart `nfs-server`.

The interesting thing is that `ip=dhcp` does work and gives me the correct addresses *while `airootfs.sfs` is being downloaded* but once archiso starts it's all wrong. How can I force archiso to reuse my DHCP settings **automatically** (i.e. without running an autostart script or patching the filesystem)?

**Comment by Torxed** [comment]
This feels like a setup issue, as I do not experience the same issue in my network. Or this is a archiso issue and should be reported under it's repository: 
https://gitlab.archlinux.org/archlinux/archiso

**Comment by Anuskuss** [comment]
How is this a setup issue when I'm literally grabbing the official ISO? Anyway I send an email to `accountsupport` so hopefully I'll have an account there soon.

**Comment by Torxed** [comment]
This repo is for the command line tool `archinstall`. The reason why I suspect the setup is that you mention you get multiple new IP's as if your DHCP server does not honor a lease file.

**Comment by Anuskuss** [comment]
> as if your DHCP server does not honor a lease file

Ah ok you mean the issue stems from my router then? It could be that the DHCP server hands out addresses based on the hostname rather than the MAC address (which seems unlikely) or is confused about the same MAC address + different hostname combo. Well in that case honoring the `hostname=` kernel parameter would solve it.
