### ISSUE TITLE
[BUG]  `mkinitcpio.conf `: The HOOKS line have encrypt before keymap wich cause none QWERTY layout issues

### ISSUE THREAD

**Issue by ScriptSathi** [archlinux/archinstall#2600]
### Which ISO version are you using?

archlinux-2024.07.30-x86_64

### The installation log

```json
Not needed
```

#### Description of the issue

When installing LVM on LUKS with another keyboard layout than QWERTY, the installation is done successfully, but when trying to launch Arch at the encrypt stage (to open LUKS containers), the layout is in QWERTY.
This is because `mkinitcpio.conf` HOOKS are set in wrong order.

How it looks like

```
# Wrong
HOOKS=(base udev autodetect microcode modconf kms keyboard encrypt keymap consolefont lvm2 block  filesystems fsck)
```

But it should be like this

```
# Correct
HOOKS=(base udev autodetect microcode modconf kms keyboard keymap consolefont encrypt lvm2 block filesystems fsck)
```

To fix the problem, it is needed to update the order in `mkinitcpio.conf` and rebuild the initramfs.

**Comment by Torxed** [comment]
Nice catch! And thank you for submitting a PR to fix it too!
I'll leave it to @svartkanin to merge this one as I haven't deep-dived into the LVM stuff yet.
