### ISSUE TITLE
ArchInstall start failed.

### ISSUE THREAD

**Issue by zinmaxs** [archlinux/archinstall#2611]
### Which ISO version are you using?

archlinux-2024.08.01-x86_64

### The installation log

```json
Mounting /dew/sda3: mount /dew/eda3 /ant/arch_btrfs Brror calling labik: labik: #deuvada1: not a block device*M ("plockdevices": (M
Mounting /dow/sda3: mount /dow/sda3 /mnt/arch_btrfs Mounting /dowsda3: mount /dowsda3 /ant/arch_btrfs
```

### describe the problem

It has been working for a long time, now it is not, I have updated and introduced what I could.
Idk: 1050 ti, core i3-9100f, 1 ssd, 1 hdd, i using windows and using NTFS on my ssd.
![IMG_20240811_012019](https://github.com/user-attachments/assets/530005c3-af5f-4b62-97a4-fa80ea6e8dec)
![IMG_20240811_012027](https://github.com/user-attachments/assets/ff1ae631-eced-4bf0-b538-de76e022f81a)

**Comment by svartkanin** [comment]
Can you please provide the full log

**Comment by zinmaxs** [comment]
![IMG_20240811_102305](https://github.com/user-attachments/assets/9a7a9fbe-93b8-4ae5-ad95-5d6966bb352e)

**Comment by zinmaxs** [comment]
i cd to /var/log/archinstall/install.log

**Comment by zinmaxs** [comment]
Ok, i clear my disks and update all
