### ISSUE TITLE
Archstrike "Could not strap in pachages: ==> ERROR: /mnt/archinstall is not a directory"

### ISSUE THREAD

**Issue by BlackeyeAnubinator** [archlinux/archinstall#2668]
### Which ISO version are you using?

2021.12.31

### The installation log

```json
See Photo
```

### describe the problem

Hi, you can see the error below. I would appreciate some solutions. (Maybe someone would also help me with the installation)
With kind regards
![Problem](https://github.com/user-attachments/assets/dff7a9a6-6c18-4a9b-8eb0-0a0a84add708)

**Comment by Torxed** [comment]
You're using a ~2 year old version, and archstrike have their own mirrors and packages so I'm not sure your issue is strictly related to us tbh.

I'll re-open if you can try with a newer version.

**Comment by BlackeyeAnubinator** [comment]
is there already a new version?
Kind regards and thank you for your reply
