### ISSUE TITLE
PKGBUILD missing depends for mkfs utils

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#2671]
The PKGBUILD is missing [dependencies](https://gitlab.archlinux.org/archlinux/packaging/packages/archinstall/-/blob/b1ac1db43c63090f9c86e431ea0c0d8f998d0324/PKGBUILD#L14-31) for packages that provide mkfs.\<type\> utils, which are used in `DeviceHandler.format()`. 

https://github.com/archlinux/archinstall/blob/6a2a204f18109a496712d67d47cacb1b16bb8506/archinstall/lib/disk/device_handler.py#L214-L251

The missing [file system packages](https://wiki.archlinux.org/title/File_systems#Types_of_file_systems) are: `f2fs-tools`, `ntfs-3g`, `reiserfsprogs`, and `xfsprogs`. See also #2439.

**Comment by codefiles** [comment]
Not a mkfs util but related and also missing from the PKGBUILD depends is `lvm2`.

Issues can arise when using archinstall to [install Arch Linux from an existing host running Arch Linux](https://wiki.archlinux.org/title/Install_Arch_Linux_from_existing_Linux#From_a_host_running_Arch_Linux) since these packages are missing from the depends.

**Comment by Torxed** [comment]
Nice catch, I added all of the above packages to the PKGBUILD.
