### ISSUE TITLE
New Archstrike Version

### ISSUE THREAD

**Issue by BlackeyeAnubinator** [archlinux/archinstall#2674]
### describe the request

Are there now newer versions of archstrike than 2021.12.31? 
with kind regards

**Comment by Torxed** [comment]
You'll have to ask on their GitHub page: https://github.com/ArchStrike

**Comment by BlackeyeAnubinator** [comment]
> You'll have to ask on their GitHub page: https://github.com/ArchStrike

And where exactly do I have to ask? I have already written an email to the Archstrike team, still no answer

**Comment by Torxed** [comment]
> > You'll have to ask on their GitHub page: https://github.com/ArchStrike
> 
> And where exactly do I have to ask? I have already written an email to the Archstrike team, still no answer

You're asking a complete stranger for advice on an totally unrelated GitHub project. I'm not sure how I can help you here other than say what you've already done, send them an e-mail and then give them plenty of time to respond.

Other than that, I don't know? It's not an Arch Linux project, it's a "fork" called ArchStrike with their own team and developers. Sorry I can't be of more help.
