### ISSUE TITLE
Error with Logical Volume Management

### ISSUE THREAD

**Issue by Alixxx-please** [archlinux/archinstall#2687]
I can't even access the log file, sorry for not using the error template.

So I'm trying to install Arch on my nvme and in the Disk configuration part I set "Use a best-effort default partition layout" with btrfs and CoW. But when I try to set LVM with btrfs still, it makes everything crash as you can see on the screenshot. I tried with ext4 to see what was the problem and still got errors with LVM, so I belive it is the problem.
Also, despite the commands shown I couldn't find any log file, so I can't give one unfortunately. 
This happened on the last official iso, 2024-09-01.
If there is another way to get some logs I would like to know to properly help with the issue. Thanks!

![cbfb7f55-9046-4f35-a079-e112bc3d9efc](https://github.com/user-attachments/assets/2271f63a-4bed-46d8-b8eb-568e082ecc2c)

**Comment by Torxed** [comment]
For some additional context, I recommended to post this issue based on this conversation: https://www.reddit.com/r/archlinux/comments/1fi228p/comment/lnfv1ay/?context=3 :)

**Comment by Alixxx-please** [comment]
This is the only thing preventing me from fully switching to Arch, is there a workaround or something I can do about it?

**Comment by svartkanin** [comment]
I haven't had time to look into this yet.
You could try to delete all existing partitions, then reboot and try the installation again.

**Comment by Alixxx-please** [comment]
Unfortunately it didn't solve the problem, still the same error. But thanks, and keep me updated if anything happens! 🫶🏻

**Comment by TheWiFiNerds** [comment]
I am also having this issue

**Comment by Alixxx-please** [comment]
Weird thing is that it used to work a few months ago, I used different settings but I remember setting btrfs with LVM 🤔

**Comment by Firebleu** [comment]
Hi !

I think LVM is experimental, maybe you need to wait a little bit.
Unfortunately I can't help you more, for my computer I use ext4 + Luks.
Maybe I can create a VM to see if I have the same problem.
Another thing, sometimes archinstall don't work very good maybe try to install arch with the wiki without the script.

I hope someone will come with an  answer for you.

**Comment by Alixxx-please** [comment]
Seem to just be a lvm problem, and not just specifically a lvm + btrfs problem. Tried ext4 + lvm and here is the result error : https://0x0.st/XIQQ.log

**Comment by svartkanin** [comment]
After it crashes could you run the below command manually 
```

**Comment by Alixxx-please** [comment]
I don't know how can I extract the text other than with this poor image. I believe it's at least readable, but I would appreciate a better way to send this if possible. Trying to upload the log file to 0x0.st doesn't include the command
![20241019_021059.jpg](https://github.com/user-attachments/assets/7e54975e-4286-4216-92f6-b57c554c80b6)

**Comment by svartkanin** [comment]
Thanks, to export anything you can store the output to a file and then simply run 
```
curl -F'file=@output.log' https://0x0.st
```

So it seems that the vol was created eventually, the current logic will attempt to fetch the info 3 times within 10s or so and then fail. We can definitely increase the timeout but I'm not sure what the actual time to create any VG or VOL is...
We can try to fetch it forever and then would just "hang" there if it can never get the info back. 

Would you mind exporting that output so it's better readable, I'm curious to what the `log` entry exactly says

**Comment by Alixxx-please** [comment]
Here is the output of the command : https://0x0.st/Xlpz.log

**Comment by codefiles** [comment]
I have a fix but I'm becoming disinterested because of how long it takes to get anything basic merged. It does not seem to be a problem with merging either as is evident by the renovate[bot] polluted commit log.

**Comment by Alixxx-please** [comment]
Fix underway?

**Comment by svartkanin** [comment]
@Alixxx-please I have not tested this but you can give this patch a try and see if it works https://github.com/archlinux/archinstall/pull/2748

**Comment by Alixxx-please** [comment]
Sorry but how would I test this on a live iso please?

**Comment by Alixxx-please** [comment]
I got a very similar error, but still one unfortunately. It also happened almost instantly after starting the installation
https://0x0.st/Xlwg.log

**Comment by svartkanin** [comment]
Could you try to reboot and then again

**Comment by Alixxx-please** [comment]
I believe I get the same error unfortunately 😕
https://0x0.st/Xlwh.log

**Comment by codefiles** [comment]
@svartkanin, why would you think it is acceptable to submit a pull request with my proposed solution? You did not discuss this with me or even add me as an author. That is very unprofessional of you and it is not the first time you have done this.

@Torxed, are you going to allow this to keep happening?

**Comment by svartkanin** [comment]
@codefiles this issue has been open for over a month now and there was no PR raised from your side thus far. You said "you're planning" to eventually fix all retries but didn't necessarily specify a time frame for it. 

In the spirit of trying to resolve the issue and to see if your proposed eventual fix is actually solving this I was thinking of raising it to get it tested if it works. Yes I did not mention you in the PR and that was my fault for not giving credit for your solution.

I've declined the PR now so feel free to raise your own with a fix.

**Comment by Alixxx-please** [comment]
So if the first fix doesn't work, there's not other option at the moment?

**Comment by Alixxx-please** [comment]
..?

**Comment by svartkanin** [comment]
@Alixxx-please could you please try if the patch https://github.com/archlinux/archinstall/pull/2778 works for you?

**Comment by Alixxx-please** [comment]
I put the iso of your fix in rufus, booted it, typed archinstall, did my usual configure but it led to I believe the same error as usual :/
https://0x0.st/XDMz.log
Am I doing something wrong, when I type `archinstall` even on a device iso is it still using the official latest version?

**Comment by svartkanin** [comment]
That's not the same error. Can you try running it on a clean system. Are you in a VM or real hardware?

**Comment by Alixxx-please** [comment]
I'm on real hardware, I'm trying to install it on a clean nvme, with nothing on it (except the partitions from the previous attempts to install Arch) and dedicated to install Arch. You want me to install it on a VM, on another drive?

**Comment by svartkanin** [comment]
Can you purge all partitions from the previous attempts so that you have a newly formatted disk

**Comment by Alixxx-please** [comment]
Purged all partitions but still get the error 😶
https://0x0.st/XDM7.log

**Comment by Alixxx-please** [comment]
I'm honestly thinking the script won't work anymore, except if some magic happen from my computer, the same that broke the script haha. I think I'm going to install it manually again. Does archinstall installs certain packages of anything that is necessary / useful that I might miss by installing everything by myself?

**Comment by svartkanin** [comment]
The error you received now is unrelated to the initial one so the patch fixed that one.
I didn't have a chance to look into the new one yet, I suspect something with lvm+btefs isn't quite right.
Unless you absolutely need that setup, you could try ext4 with lvm instead

**Comment by Alixxx-please** [comment]
I absolutely want, don't need. But I'm glad it solved the initial issue then. Take your time don't worry, after two months I can wait as long as needed haha

**Comment by Goosegit11** [comment]
```
Setting up LVM config...


^CTraceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 395, in _lvm_info_with_retry
    return self._lvm_info(cmd, info_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 367, in _lvm_info
    raise ValueError('Report does not contain any entry')
ValueError: Report does not contain any entry

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/archinstall", line 8, in <module>
    sys.exit(run_as_a_module())
             ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 337, in run_as_a_module
    main()
  File "/usr/lib/python3.12/site-packages/archinstall/__init__.py", line 330, in main
    importlib.import_module(mod_name)
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 186, in <module>
    guided()
  File "/usr/lib/python3.12/site-packages/archinstall/scripts/guided.py", line 182, in guided
    fs_handler.perform_filesystem_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 81, in perform_filesystem_operations
    self.perform_lvm_operations()
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 152, in perform_lvm_operations
    self._setup_lvm_encrypted(
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 164, in _setup_lvm_encrypted
    self._setup_lvm(lvm_config, enc_mods)
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/filesystem.py", line 228, in _setup_lvm
    lv_info = device_handler.lvm_vol_info(lv.name)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 406, in lvm_vol_info
    return self._lvm_info_with_retry(cmd, 'lv')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/archinstall/lib/disk/device_handler.py", line 397, in _lvm_info_with_retry
    time.sleep(3)
KeyboardInterrupt


```
