### ISSUE TITLE
Clearer language selection, full layout names

### ISSUE THREAD

**Issue by joewood9364** [archlinux/archinstall#2706]
### describe the request

I remember trying to find the British keyboard layout and I was looking for en-gb or gb but couldn't find it. I almost selected UK but i was worried i would end up in Ukrainian so I just stayed in american English. Would it be possible to just use full country names for clarity?

**Comment by rasputyashka** [comment]
archinstall just uses localects --no-pager list-keymaps to get all the locales (so it would be quite difficult to map each layout to a country, especially in cases where it does not depend on the country (check dvorak-programmer out for example)).

**Comment by svartkanin** [comment]
@rasputyashka is right on the way we assemble the list and it will be very challenging to actually create such a mapping
