### ISSUE TITLE
SD Card (MMC) as root not being able to boot

### ISSUE THREAD

**Issue by PD-Kerman** [archlinux/archinstall#2708]
### Which ISO version are you using?

2024.09.01 (archlinux-2024.09.01-x86_64)

### The installation log

```
installation was successful
will attach later if necessary
```

### Description of the issue

I was installing archlinux on a laptop into **SanDisk Extreme 256 mSD Card (SN256)**

Then **after** installing with archinstall and **rebooting** **(for multiple times)**

**Something like this showed up:**

`ERROR: device 'UUID=<uuid>' not found. Skiiping fsck.
mount: /new_root: can't find UUID=<uuid>.
You are now being dropped into an emergency shell.`

**# i was **using recommended disk partition solution** (and **regardless** of using **ext4** and **btrfs**) and basically just cleaned/**erased** the **whole disk** and performed the installation **

**for some reason i tried installing ubuntu and it works fine**

But on archlinux installing with archinstall on to some kind of sd card or emmc devices it just crashes when rebooting, seemss like its **not being able to find the root partition** on the MMC disk

*And i tried running **blkid** to get things checked and found that none of the mmcblk partition showed up with any infos, basically **no outputs**(neither the boot partition nor the root), but quite contrarily, when i plug in some **usb devices** after being dumped into the emergency shell, and execute blkid again, u could surprisingly found all kinds of uuid infos in the **output** of the usb device(flash drive)* 

and i found this post in the forums: 
https://bbs.archlinux.org/viewtopic.php?id=234313
which **very much the same**

but i modified the `/etc/mkinitcpio.conf` as it was being **mentioned in the post** and tried running `mkinitcpio -P` and `mkinitcpio linux` in the chroot enviroment(not sure i did it exactly right in some scenarios when chroot(ing) manually after rebooted, although the output seems fine) in order to get things updated, but no joy, the issue still remains

not sure whats causing it, regardly, FYI, i also checked out the **archwiki** and tried **switching the order** of the elements in the **HOOK section(block keyboard)** and the update using the very same command as well, didnt help though

Any sort help would be much appreciated
Thanks in advance, 
Best Regards

**Comment by svartkanin** [comment]
@PD-Kerman could you provide the install.log as it provides a better way to debug the issue

**Comment by PD-Kerman** [comment]
> @PD-Kerman could you provide the install.log as it provides a better way to debug the issue 

Thank you for your reply, 
Yeah about this issue,
i guess it should just be some kind of weird mmc blocks supports that mkinitcpio comes with, i tried all kinds of tricks by modifying the config file (MODULES, HOOKS) all kinds of stuff, didnt really helped

its related to the initramfs, i tried to re-generate the initramfs using dracut with using the default profile/configs from dracut (by not specifying) it booted right away

I guess it should be an archlinux(mkinitcpio) issue it self which archinstall doesnt have much to do about it(tried manual installation) so...

Thank you for replying once again 

And considering its not much related to archinstall, considering closing this issue soon (within days)

Best Regards,
PD-Kerman
