### ISSUE TITLE
On the Report Issues & Bugs page of the documentation the link points to a fork instead of the actual project.

### ISSUE THREAD

**Issue by IPlayZed** [archlinux/archinstall#2712]
### Which ISO version are you using?

Not relevant

### The installation log

```json
Not relevant
```

#### Description of the issue

On the [Report Issues & Bugs](https://archinstall.archlinux.page/help/report_bug.html) page of the project, the following link in this line:
> Issues and bugs should be reported over at [https://github.com/archlinux/archinstall/issues](https://github.com/Torxed/archinstall/issues)

takes the reader to [Torxed's fork's pull requests](https://github.com/Torxed/archinstall/pulls) instead of the official project. This is probably by accident assume and the link should be corrected.

**Comment by Torxed** [comment]
Correct. GitHub used to redirect users here automatically, after the project was transferred from my account to the distro's account. 

But once I forked it myself that redirect got broken. Easy fix, thanks for bringing it to our attention :)

**Comment by Torxed** [comment]
Thanks for fixing this @svartkanin!
Issue link should now point correctly!
