### ISSUE TITLE
ZFS as an option for partitioning layout

### ISSUE THREAD

**Issue by ipaqmaster** [archlinux/archinstall#2714]
### describe the request

Hi team,

I would love for archinstall to support a ZFS rootfs using this installer. `zfs-linux` and `zfs-dkms` currently live on the AUR. Are there be any obvious blockades to consider if I were to look into making that an option?

**Comment by svartkanin** [comment]
https://github.com/archlinux/archinstall/discussions/701

**Comment by ipaqmaster** [comment]
I see. I was worried that not being an official package may have been a blockage.
