### ISSUE TITLE
I couldn't install archlinux at the end

### ISSUE THREAD

**Issue by Huseynakhm** [archlinux/archinstall#2726]
### Which ISO version are you using?

2024-10-01

### The installation log

```json
Process 34 stopped
* thread #1: tid = 34, 0x00007f1b227fdb90, name = 'fhost'
    frame #0:
Process 34 stopped
* thread #8: tid = 34, 0x00007f1bee248940 fhost`get(path='/XE70.log') + 27 at fhost.c:139, name = 'fhost/responder', stop reason = invalid address (fault address: 0x30)
    frame #0: {3:#018x} fhost`get(path='/XE70.log') + 27 at fhost.c:139
   136   get(SrvContext *ctx, const char *path)
   137   {
   138       StoredObj *obj = ctx->store->query(shurl_debase(path));
-> 139       switch (obj->type) {
   140           case ObjTypeFile:
   141               ctx->serve_file_id(obj->id);
   142               break;
(lldb) q
```

### describe the problem

Description of the issue

I was installing on Amd ryzen 3 3250U, amd radeon vega 3 graphics and 8gb of RAM hardware. I was installing archlinux watching this video [https://youtu.be/tPYCd4w65-0?si=FJ7o4MjjNutthIhm] and at 6:32 I did the same thing but after like 3 minutes I got this problem
![20241009_130011](https://github.com/user-attachments/assets/f510faa8-6011-4837-91c7-5fbb6c2983da)

What could go wrong? I am new in Archlinux

**Comment by svartkanin** [comment]
Can you provide the log file as described

**Comment by svartkanin** [comment]
Without a log file this can't be debugged
