### ISSUE TITLE
Crash during keying sync on Framework 13 AMD

### ISSUE THREAD

**Issue by shawnyeager** [archlinux/archinstall#2744]
### Which ISO version are you using?

2024.10.01

### The installation log

```json
http://0x0.st/Xl4i.log
```

#### Description of the issue

I was installing on my Framework 13” AMD

Then `Waiting for Arch Linux keyring sync (archlinux-keyring-wkd-sync) to complete.` and archinstall crashed with the error `Device path was not set`.

**Comment by svartkanin** [comment]
Does this solve the problem https://github.com/archlinux/archinstall/issues/2320? 
For more information: https://archinstall.archlinux.page/help/known_issues.html#keyring-is-out-of-date-2213

**Comment by shawnyeager** [comment]
Thanks, @svartkanin. I won't be able to test, as I ran a second time after this bug report, and fortunately the installation succeeded.

**Comment by svartkanin** [comment]
In that case I'll close the issue for now and we can reopen it if it differs from the others
