### ISSUE TITLE
When setting manually the IP-adres, no netmask is added

### ISSUE THREAD

**Issue by zenlord** [archlinux/archinstall#2756]
### Which ISO version are you using?

2024-10-01

### The installation log

```json
Not relevant - installation succeeds
```

#### Description of the issue

I set the IP address with this block in my config.json:

```
  "network_config": {
    "type": "manual",
    "nics": [
      {
        "iface": "eno1",
        "ip": "192.168.2.16",
        "dhcp": false,
        "gateway": "192.168.2.1",
        "dns": [
          "192.168.2.1"
        ]
      }
    ]
  },
```

This configuration is then correctly transferred to a *.network file in /etc/systemd/network/ - but the service systemd-networkd complains that no netmask is specified and /32 is assumed. This results in dysfunctional network.

### Proposed solution

Just simply document that the "ip address" must be specified using CIDR notation:
* 192.168.2.16/24
* 192.168.2.16/255.255.255.0

OR you could also add a key 'netmask' to the schema and use the value to create the *.network file.

**Comment by svartkanin** [comment]
The input does show an example of the CIDR notation 
![image](https://github.com/user-attachments/assets/c092155a-7cc4-4d95-9591-9520c970156f)

or where would you suggest to document it better?

**Comment by zenlord** [comment]
The examples of a JSON configuration file should be updated to reflect this change. I sent a PR already to update the sample JSON file, but it did not include this change.
I'll create another one for this change specifically.
