### ISSUE TITLE
Archinstall failed no medium bus found

### ISSUE THREAD

**Issue by kensin998** [archlinux/archinstall#2769]
### Which ISO version are you using?

2024.11.01-x86_64.iso

### The installation log

```json
Process 45 stopped
* thread #1: tid = 45, 0x00007f6caa8bf910, name = 'fhost'
    frame #0:
Process 45 stopped
* thread #8: tid = 45, 0x00007f6d762bc8e0 fhost`get(path='/xgfc.log') + 27 at fhost.c:139, name = 'fhost/responder', stop reason = invalid address (fault address: 0x30)
    frame #0: {3:#018x} fhost`get(path='/xgfc.log') + 27 at fhost.c:139
   136   get(SrvContext *ctx, const char *path)
   137   {
   138       StoredObj *obj = ctx->store->query(shurl_debase(path));
-> 139       switch (obj->type) {
   140           case ObjTypeFile:
   141               ctx->serve_file_id(obj->id);
   142               break;
(lldb) q
```

#### Description of the issue

I was installing on windows 11 dualboot what I did was just followed this guys video

https://youtu.be/Pl-McGH_mvY?si=QUUP0l9wv-QeGwOM

...

Then a error happened and it says exited with abnormal code failed to connect to bus: no medium found and archinstall crashed ...

installed on real windows 11 and dualboot
![image](https://github.com/user-attachments/assets/43caa7ce-baa9-47e6-b87e-d9f9795a5edb)
![image](https://github.com/user-attachments/assets/6e4fcbb8-8500-4388-8820-85a9dfa0caf1)
![image](https://github.com/user-attachments/assets/987bc31a-7383-42b9-9341-6009f2f2ba9d)
![image](https://github.com/user-attachments/assets/2d31bce4-a6c0-4aa6-a9cb-59920b23d99c)

**Comment by kensin998** [comment]
Oh sorry I think I missing log file I will create issue again

**Comment by abrar-wadud** [comment]
Yep, same damn issue 😔. Now I can't even install arch Linux.

**Comment by svartkanin** [comment]
Can you please provide the log file

**Comment by kensin998** [comment]
well but I don’t know how to upload log file from arch Linux can you navigate

**Comment by kensin998** [comment]
Also I exit installation and rebooted so I think I’m need to do same steps

**Comment by abrar-wadud** [comment]
> Also I exit installation and rebooted so I think I’m need to do same steps

When installing don't select any audio server and it will work

**Comment by kensin998** [comment]
really?

**Comment by abrar-wadud** [comment]
> really?

Try it 😉. Mine worked

**Comment by kensin998** [comment]
alright

**Comment by abrar-wadud** [comment]
> alright

Although your audio may not work afterwards. But at least you can install arch you can always fix audio problem later

**Comment by kensin998** [comment]
ok

**Comment by kensin998** [comment]
sorry for taking time

**Comment by kensin998** [comment]
now I’m installing without audio server

**Comment by kensin998** [comment]
a another error

**Comment by kensin998** [comment]
I’m gonna post new issue

**Comment by kensin998** [comment]
but I don’t know how to put log file so please tell me in new issue

**Comment by losmust** [comment]
estou com o mesmo problema...

**Comment by abrar-wadud** [comment]
> but I don’t know how to put log file so please tell me in new issue

Sry I don't know it either.

**Comment by kensin998** [comment]
I posted another one

**Comment by kensin998** [comment]
let’s me close this issue

**Comment by marufimtiaz** [comment]
Why did you close this one though? Not selecting any audio server is just a workaround for not facing the issue. Not using archinstall is also a workaround for not facing the issue. 
But the issue itself is still there, right? You wouldn't close the issue if I told you just don't use archinstall.

**Comment by Torxed** [comment]
Sensible choice, seeing as it's a duplicate of #2764
