### ISSUE TITLE
Nvidia drivers not loaded after installing

### ISSUE THREAD

**Issue by qx-775** [archlinux/archinstall#277]
I have a laptop and docking station with 2 external monitors that I want to show output on so that I can use 3 monitors. Using the standard pop_os with nvidia drivers this is automatically possible. 

However when I used archinstall `2.1.3` to install Arch Linux and selected nvidia drivers it wont run at boot, instead falls back to integrated AMD CPU graphics (but I want Nvidia graphics!). 

I have tried everything, from google to using the arch wiki to install drivers and settings `nomodeset` in systemd-boot but that drivers won't launch. `nvidia` package and it's utils are installed, I also tried `nvidia-dkms`
For example `nvidia-smi` reports the following:

```sh
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```
There is only output on my laptop screen, the external monitors are not detected by nvidia. I believe the drivers are not loaded at all. 

Nvidia is a pain in the butt on linux, yes but I still want this to succeed to make nvidia drivers load. Perhaps I am at the wrong place to ask, but since you know what the installer does when nvidia package is installed I'm curious what goes wrong. I can't find what the hardware section does to install nvidia sadly. 

Also thank you for this amazing installer. Looking forward to ur hard work on 2.2!

**Comment by dylanmtaylor** [comment]
This might be an issue with optimus since you're on a laptop. This is probably a good reference for you: https://wiki.archlinux.org/index.php/NVIDIA_Optimus

**Comment by qx-775** [comment]
Thanks for the response, I overlooked some settings in there.
I followed everything in the Arch Wiki. I have setup optimus correctly. Nvidia now runs!
However monitors are not detected and switching to hybrid or nvidia just doesnt work. `nvidia-xconfig` hangs.

Please forgive me if this is a bit ouf of archinstall context. Just stuck.

**Comment by Torxed** [comment]
> Thanks for the response, I overlooked some settings in there.
> Nvidia-prime helped me fix my problems! Thanks for your help!. Closing.

It's good feedback never the less.
Perhaps we should use the current API feature to detect multiple graphics cards, and warn about multiple graphic vendors detected.. And that post-configuration is required.
