### ISSUE TITLE
Unreachable fsync call in SysCommandWorker.write

### ISSUE THREAD

**Issue by correctmost** [archlinux/archinstall#2773]
### Description

`pylint --enable=unreachable .` picks up the following unreachable `fsync` call:

https://github.com/archlinux/archinstall/blob/7437668f1e51eb3c88f7a0ddc7ad7ef30b7f64a5/archinstall/lib/general.py#L217-L219

### Warning
```
************* Module archinstall.lib.general
archinstall/lib/general.py:219:3: W0101: Unreachable code (unreachable)
```

**Comment by Torxed** [comment]
That's because `pty.fork()` secondary executor will be the thing that performs that call.
Maybe pylint can't handle forked code?

**Comment by Torxed** [comment]
Ah yeah that return never happens, sorry about that one hehe. 
We can either move that line up or remove it all together
