### ISSUE TITLE
Failed install kde plasma, failed to connect to bus

### ISSUE THREAD

**Issue by 0xToHelL** [archlinux/archinstall#2783]
### Which ISO version are you using?

2024.11.01-x86_x64

### The installation log

```json
http://0x0.st/XD_z.log
```

#### Description of the issue

I was installing on X hardware ...

Then X Y Z happened and archinstall crashed ...

#### Virtual machine config:

```xml
<domain type="kvm">
  <name>my-arch-machine</name>
  ...
  </devices>
</domain>
```

```console
/usr/bin/qemu-system-x86_64 -name [guest=my-arch-machine,debug-threads=on](url) -object ...
```

**Comment by svartkanin** [comment]
Duplicate https://github.com/archlinux/archinstall/issues/2764
