### ISSUE TITLE
Pipewire Install fails when enabling systemd service for all users.

### ISSUE THREAD

**Issue by brockm218** [archlinux/archinstall#2788]
### Which ISO version are you using?

2024-11-01

### The installation log

```json
https://0x0.st/XDvi.log
```

#### Description of the issue

I was installing on bare metal and ran into an issue when installing Pipewire as my audio service. Even after re-downloading the ISO and retrying several times, the archinstall script fails on enabling pipewire-pulse as a systemd user service for the user account created at time of install.

**Comment by taoki123** [comment]
Am also facing thi issue and it not letting it enter chroot

**Comment by taoki123** [comment]
![image](https://github.com/user-attachments/assets/09a3ddf7-7e2d-4d6b-8782-12d4cb01d6f4)

**Comment by brockm218** [comment]
Duplicate of #2764 

Solved in master with `pacman-Syu git && git clone https://github.com/archlinux/archinstall && cd archinstall && python -m archinstall`

**Comment by taoki123** [comment]
> Duplicate of #2764 
> 
> 
> 
> Solved in master with `pacman-Syu git && git clone https://github.com/archlinux/archinstall && cd archinstall && python -m archinstall`

You mean this will solve my issue ??

**Comment by brockm218** [comment]
> > Duplicate of #2764
> > Solved in master with `pacman-Syu git && git clone https://github.com/archlinux/archinstall && cd archinstall && python -m archinstall`
> 
> You mean this will solve my issue ??

Read the linked issue #2764, make an effort to understand the logic of the solution posted (the master branch is the latest update that hasn’t yet been merged into the version of archinstall in an ISO release, those commands download and run the latest version into your install environment), and try it out before commenting on a closed issue without adding anything new or of substance to the conversation.

If you have the same issue as someone but don’t have anything additional to add (i.e “I tried with PulseAudio too and it also broke!”) then just react with a thumbs-up rather than replying. Not to lecture, just some GitHub etiquette.

**Comment by taoki123** [comment]
![Uploading 384669764...]![Uploading 384669765...]
