### ISSUE TITLE
You can just hit enter for locale selections and it will continue

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#279]
An error should be thrown that no selection was made.

**Comment by Torxed** [comment]
The default will be to leave it as is (en_US).
But perhaps we should put a (warning is a strong word here), notification mentioning that en_US layout was chosen.

**Comment by dylanmtaylor** [comment]
> The default will be to leave it as is (en_US).
> But perhaps we should put a (warning is a strong word here), notification mentioning that en_US layout was chosen.

As an American who speaks English this isn't something that is a problem for me, but because this is a project used internationally, perhaps it is not a good idea to default to these without letting the user know that we are doing so.

**Comment by Torxed** [comment]
> > The default will be to leave it as is (en_US).
> > But perhaps we should put a (warning is a strong word here), notification mentioning that en_US layout was chosen.
> 
> As an American who speaks English this isn't something that is a problem for me, but because this is a project used internationally, perhaps it is not a good idea to default to these without letting the user know that we are doing so.

I'm torn on this, I don't believe users *have* to choose a locale *(sure it may break certain/most applications if you skip it so that's why I threw in en_US)*.
But throwing an error sounds harsh. Informative decisions should be fine enough, so notifying about*(rather than erroring out)* en_US being the default until otherwise changed in post-conf should IMHO be more than enough. We're missing that notification tho.

**Comment by dylanmtaylor** [comment]
> > > The default will be to leave it as is (en_US).
> > > But perhaps we should put a (warning is a strong word here), notification mentioning that en_US layout was chosen.
> > 
> > 
> > As an American who speaks English this isn't something that is a problem for me, but because this is a project used internationally, perhaps it is not a good idea to default to these without letting the user know that we are doing so.
> 
> I'm torn on this, I don't believe users _have_ to choose a locale _(sure it may break certain/most applications if you skip it so that's why I threw in en_US)_.
> But throwing an error sounds harsh. Informative decisions should be fine enough, so notifying about*(rather than erroring out)* en_US being the default until otherwise changed in post-conf should IMHO be more than enough. We're missing that notification tho.

I can see your perspective and I'm fine with that. We should inform them that the default is being set to en_US then.

**Comment by Col433** [comment]
I think it's very important to be able to choose a locale. It's possible to get geoblocked without the correct locale?

**Comment by Torxed** [comment]
> I think it's very important to be able to choose a locale. It's possible to get geoblocked without the correct locale?

I've seen you mention goeblocked in another issue, but unless I've missed something the last few years, locale has nothing to do with geoblocking? Unless some really weird web designers take the locale of the browser for granted - which would be insane. But yes locale is important :)

**Comment by Col433** [comment]
@Torxed thanks Anton. I always thought geoblocking used your IP address but with people using proxy servers to bypass I thought they might also now look at system install locale as well. Sorry I'm a novice at these things so thanks for taking the time to clear that issue up for me 😊.

**Comment by Torxed** [comment]
The keyboard locale now has a clear message stating that if you skip that step, the default will be `en_US`.
Setting an actual locale (language) for the operating system is still not implemented, but will be for v2.3.0.
But I'm closing this to avoid duplicate issues and since the original problem is fixed.
