### ISSUE TITLE
Add xss-set to list of packages with installing Desktop + i3wm

### ISSUE THREAD

**Issue by jackdesert** [archlinux/archinstall#2790]
### describe the request

I chose "desktop -> i3wm" and was impressed that archinstall made sensible choices regarding i3. 

The only thing I've noticed amiss is that the laptop did not lock the screen before sleeping. 
xss-set is referenced in the default ~/.config/i3/config so all I had to do to get it to lock before resume was to install:

    pacman -S xss-set

and then restart my X session.

So this request is to (simply?) add xss-set to the list of packages that get installed when someone chooses desktop -> i3wm

**Comment by Torxed** [comment]
Thank you for both reporting and fixing it.
This looks sensible to me seeing as the [i3lock](https://man.archlinux.org/man/extra/i3lock/i3lock.1.en#SYNOPSIS) man page specifically mentions `xss-set`.

**Comment by opsrcode** [comment]
Hello guys, the package is 'xss-lock'. The change was made with the package named 'xss-set' (which does not exist), causing a failure in the installation of the i3 desktop (https://0x0.st/XkrA.log). I made a pull request with this correction: (https://github.com/archlinux/archinstall/pull/2796)
