### ISSUE TITLE
No BIOS support

### ISSUE THREAD

**Issue by thetayloredman** [archlinux/archinstall#280]
The installer uses systemd-boot and GPT. BIOS cannot boot from GPT by default.

Solution:
Switch to GRUB and add a bios_boot partition, or use MBR.

**Comment by dylanmtaylor** [comment]
This is implemented in the future 2.2.0 release.

**Comment by Torxed** [comment]
It's a good idea, see #42 and merged in #113, this feature will come in the next minor version: `v2.2.0` :)
