### ISSUE TITLE
Installing issue

### ISSUE THREAD

**Issue by menerel** [archlinux/archinstall#2805]
### Which ISO version are you using?

2024 11 15 is today

### The installation log

```json
Failed to connect to bus: no medium found
```

#### Description of the issue

I was installing on my computerhardware ...

Then X Y Z happened and archinstall crashed ...

#### Virtual machine config:

```xml
![Uploading IMG_20241115_182553.jpg…]()

<domain type="kvm">
  <name>my-arch-machine</name>
  ...
  </devices>
</domain>
```

```console
/usr/bin/qemu-system-x86_64 -name guest=my-arch-machine,debug-threads=on -object ...
```

**Comment by menerel** [comment]
![Uploading IMG_20241115_182553.jpg…]()

**Comment by svartkanin** [comment]
Duplicate https://github.com/archlinux/archinstall/issues/2764
