### ISSUE TITLE
Archinstall does not complete installation: sound server failure

### ISSUE THREAD

**Issue by serial02** [archlinux/archinstall#2846]
### Which ISO version are you using?

archlinux-2024.11.01-x86_64.iso

### The installation log

```json
Partition code not supported: 2
Partition code not supported: 1
Partition code not supported: 1
Hardware model detected: Hewlett-Packard p6540br; UEFI mode: False
Processor model detected: Intel(R) Core(TM) i3 CPU         540  @ 3.07GHz
Memory statistics: 14767468 available out of 16108896 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none
```

### describe the problem

I burned 8 Arch ISOS on different pendrives and even the installation didn't complete.

There's always an error saying it couldn't find a sound server and won't install it.

Installing audio server: Pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse', 'wireplumber']
['/usr/bin/arch-chroot', '/mnt/archinstall', 'su', '-', 'edson', '-c', 'systemctl enable --user pipewire-pulse.service'] exited with abnormal exit code [1]: [0;1;31mFailed to connect to user scope bus via local transport: Mídia não encontrada[0m

**Comment by serial02** [comment]
[install.log](https://github.com/user-attachments/files/17788788/install.log)

**Comment by svartkanin** [comment]
Duplicate https://github.com/archlinux/archinstall/issues/2764
