### ISSUE TITLE
Manual partitioning: partition creation size input crashes

### ISSUE THREAD

**Issue by codefiles** [archlinux/archinstall#2850]
When using manual partitioning to create a new partition, input is collected for the size of the new partition. Here are some ways to crash the program at that stage:

| Action | Expected behavior |
| --- | --- |
| Press Esc | Use displayed default value |
| Press Enter when an input field is blank | Use displayed default value |
| Use same value for start and end | Display message that size is invalid |

**Comment by utuhiro78** [comment]
I tested archinstall-git on the installed Arch Linux.

Run xfce4-terminal and install archinstall-git.

```
yay -S --needed archinstall-git
```

Run archinstall.

```
sudo archinstall
```

"Manual Partitioning" fails.

[traceback.txt](https://github.com/user-attachments/files/17791790/traceback.txt)

**Comment by codefiles** [comment]
The traceback you provided matches #2849, which is a different bug.
