### ISSUE TITLE
Got lots of errors while trying to install it....

### ISSUE THREAD

**Issue by NicoDBear** [archlinux/archinstall#2865]
### Which ISO version are you using?

2024-11-01

### The installation log

```json
Log issue createad at /var/log/archinstall/install.log
Please, read the image attached.
```

### describe the problem

Hello, Im newbie into this OS. First time installing Arch or any other linux distro. Could someone tell me what should I do?

![Errors](https://github.com/user-attachments/assets/7b9d0778-5252-4609-953f-6ce56d2c3a5d)

**Comment by svartkanin** [comment]
Please search for issues first, this has been reported 10+ times by now. 
It's fixed in the latest release and master
