### ISSUE TITLE
Wouldnt install on my nvme slots

### ISSUE THREAD

**Issue by LazyBev** [archlinux/archinstall#2871]
### Which ISO version are you using?

Latest

### The installation log

```json
https://0x0.st/Xde4.log
```

#### Description of the issue

I was installing on nvme hardware ...

Then it wouldn't install on my nvme partitions happened and archinstall crashed ...

**Comment by svartkanin** [comment]
The error says that the selected disk is currently in use, you may want to double check that. Also please upgrade to the latest version
