### ISSUE TITLE
Installing arch linux w/Hyprland on VMware failed

### ISSUE THREAD

**Issue by KirTeanEesti** [archlinux/archinstall#2887]
### Which ISO version are you using?

2024-11-01

### The installation log

```json
https://0x0.st/XnBN.log
```

#### Description of the issue

I was installing on VMware

It was the end of installation, then this error occured

#### Virtual machine config:
4 GB ram
Number of processors 2
Numbers of core 1
20 GB NVMe
Network Adapter NAT

(I'm a new in Linux at all, so... yeah..)

**Comment by RapidTransit** [comment]
Is this related to: https://github.com/archlinux/archinstall/issues/2764 ? Try not installing an audio server in the Arch Install.

**Comment by KirTeanEesti** [comment]
> Is this related to: #2764 ? Try not installing an audio server in the Arch Install.

That worked, thanks!
