### ISSUE TITLE
cannot use archistall er at all

### ISSUE THREAD

**Issue by KCBest** [archlinux/archinstall#2889]
### Which ISO version are you using?

2024-11-01

### The installation log

```json
I dont even have that Thing...
```

#### Description of the issue

I was installing on X hardware ...

Then X Y Z happened and archinstall crashed ...

#### Virtual machine config:

```xml
<domain type="kvm">
  <name>my-arch-machine</name>
  ...
  </devices>
</domain>
```

```console
/usr/bin/qemu-system-x86_64 -name guest=my-arch-machine,debug-threads=on -object ...
```
![IMG_20241119_204933](https://github.com/user-attachments/assets/0637ecad-7034-43e0-855e-96e39d038d6c)

The error occurs right after the countdown... I completely wiped the ssd before using the script but it just instantly gave the error and there is no log...

**Comment by svartkanin** [comment]
Can you try rebooting and running it again

**Comment by Time2138** [comment]
What version of the package do you have?

**Comment by GardenData61371** [comment]
Same problem here. The last commit broke the whole installer

**Comment by siuhamlop** [comment]
I have exactly the same error.
[install.log](https://github.com/user-attachments/files/17863836/install.log)

**Comment by svartkanin** [comment]
Without any log this is difficult to debug

**Comment by siuhamlop** [comment]
I have the log, can I paste it here?

**Comment by Time2138** [comment]
I had the same problem but I fixed it by formatting the disk to ext4 before installing

**Comment by arcolinuxz** [comment]
I see the same error here - https://0x0.st/X5sP.log

![image](https://github.com/user-attachments/assets/0b95538f-0c73-40cd-82ec-5bf6cf002f0e)

**Comment by KCBest** [comment]
there is no log, it doesnt exist... it just removed itself... it is on a laptop(Real Hardware) I made shure to Update with pacman -Sy and pacman - Syy and pacman - S archistall... Also after that I manually installed it and now it works...

**Comment by arcolinuxz** [comment]
I just used the url and it worked.

**Comment by KCBest** [comment]
that did not work for me...

**Comment by arcolinuxz** [comment]
Now I git cloned your repo and ran the ./build_iso.sh script.

Mounted the /tmp/... iso in VB

![image](https://github.com/user-attachments/assets/bee4acc5-057c-4815-a4b3-d5bf8b0fce16)

Let try to install and report back
Happy tidings

![image](https://github.com/user-attachments/assets/05221960-667e-4559-a263-7683819083a4)


Time to create a new release - current code lets you install Arch - choose pipewire - no issue with sound now

**Comment by KCBest** [comment]
but I use pulseaudio... it didnt have Audio output with pipewire

**Comment by Kingmtu** [comment]
I have the same problem. How to fix this.
The previous installer version was working like a charm.

**Comment by arcolinuxz** [comment]
This is how I overcame it - https://youtu.be/sQE4dFmjmxk

build your own ISO

**Comment by Kingmtu** [comment]
@arcolinuxz this video link is not working

**Comment by svartkanin** [comment]
@arcolinuxz this is not the same issue as the author's, please use the latest master, if yhat also contains the problem raise a new issue 

Based on the comment https://github.com/archlinux/archinstall/issues/2889#issuecomment-2492976602 the original problem seems resolved.

If anyone has other errors please check existing open issues and if none matches raise a new one
