### ISSUE TITLE
TypeError: 'PartitionFlagDataMixing' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by light-mooner** [archlinux/archinstall#2896]
### Which ISO version are you using?

archlinux-2024.11.01-x86_64.iso

### The installation log

```json
https://imgur.com/a/BzClbfV
```

#### Description of the issue

I was installing on qemu hardware ...

i cloned the latest version of archlinux to avoid an issue with the provided archinstall from the iso, and i get that issue.
the problem wasn't there yesterday, i guess it's a regression from this commit : https://github.com/archlinux/archinstall/pull/2895

when using a commit before 83d222c when cloning, i don't get the issue. (issue was not there yesterday)

#### disk config:

- Use a best effort default partition layout
- btrfs
- subvolumes enabled
- compression on

Hopefully i gave enough information, sorry for the screenshot as log, i can't copy paste from my vm as i don't have vm-tools enabled.

#### reproduce the issue

- create a qemu vm (tried on macos / proxmox ) but i suspect it's not linked to the fact it's a vm
- git clone latest version of archlinux
- set a single disk (sda in my case) as specified in 'disk config' section
- make install

**Comment by GardenData61371** [comment]
Same issue here on bare metal. Is there any way we can clone without that specific commit?
