### ISSUE TITLE
Add option to select shell

### ISSUE THREAD

**Issue by JakobDev** [archlinux/archinstall#291]
When creating a new user, archinstall should ask, which shell (bash,zsh,ksh,fish) the user wants to use.

**Comment by dylanmtaylor** [comment]
It wouldn't be hard to do, but it might be a bad idea to overwhelm users with questions and you can always get an alternate shell anyways with adding it in additional packages and running chsh

**Comment by dylanmtaylor** [comment]
A good compromise would be making a change_shell method that takes in the desired shell and user as arguments and allow it to be called when using the library, not the guided installer. Thoughts, @Torxed ?

**Comment by Torxed** [comment]
> A good compromise would be making a change_shell method that takes in the desired shell and user as arguments and allow it to be called when using the library, not the guided installer. Thoughts, @Torxed ?

I agree that this is something that can be implemented in the API for .dotfiles to support.
But in general, this can most likely be considered [Post Installation *(General recommendations)*](https://wiki.archlinux.org/index.php/General_recommendations#Alternative_shells), as such it shouldn't be in guided unless strong arguments for it. But I'm merging API changes for this! :)
