### ISSUE TITLE
Stuck on systemd coredump constant loop previous installer works like a charm before 3.0.1 

### ISSUE THREAD

**Issue by Kingmtu** [archlinux/archinstall#2913]
Systemd[1] Failed to start journal service. 
Constant loop. This makes installation so annoying. Sometimes I have to shut the system off. Any ideas 💡

**Comment by Torxed** [comment]
Do you have a stack trace or log file?

**Comment by Kingmtu** [comment]
I've taken this pic, as this is my main pc I ve to install endeavour os. Unfortunately 
 ![2024-11-22 21-11_page_2.jpg](https://github.com/user-attachments/assets/878cd82f-0fa1-4b78-aeb7-836a550e23a0)

**Comment by Torxed** [comment]
This feels like either you're formatting the drive you're sitting on - or your machine ran out of RAM.

**Comment by Kingmtu** [comment]
The previous script works fine before the update. I've 12 gigs of ram. I tried 4 5 times but the same problem appears. Then the installation failed.

**Comment by Torxed** [comment]
In my mind this is outside of `archinstall`, as it's the ISO/liveboot that is crashing hard.
Essentially it looks like your machine is core dumping for an unknown reason.

It's suspicious that it happens exactly when we want to format your drive, that much is related to `archinstall`. But it's really hard to say why your system crashed hard.

Without revealing any passwords, it would be interesting to get the final command found in `/var/log/archinstall/cmd_history.txt` or see the reason in `dmesg -w` why your system core dumped.

**Comment by Kingmtu** [comment]
Ok I will try to get the logs next time I try.

**Comment by Kingmtu** [comment]
I reset my bios settings and re download iso file from global mirror then  run sudo Pacman -Sy the, sudo Pacman  -S archinstall it's works.
