### ISSUE TITLE
Duplicate formatting on master

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#292]
Looks like partitions are getting formatted twice. It's not breaking anything but might be worth fixing eventually.

**Comment by Torxed** [comment]
![2021-04-12-123257_1275x317_scrot](https://user-images.githubusercontent.com/861439/114404128-b72cae80-9ba5-11eb-8783-22ce2d9e01e9.png)

**Comment by Torxed** [comment]
Partially fixed by #434 for the boot partition *(`vfat`)*, and #436 fixes the main partition dupe formatting.

**Comment by Torxed** [comment]
#436 Fixed the last duplicate formatting.
