### ISSUE TITLE
Failed to connect to user scope bus via local transport: No medium found

### ISSUE THREAD

**Issue by kay5421** [archlinux/archinstall#2926]
### Which ISO version are you using?

2024-11-01

### The installation log

```json
[here](https://0x0.st/X52S.log)
comment too long uggghghh
```

#### Description of the issue

I was installing on VirtualBox hardware ...

Then setting up pipewire happened and archinstall crashed ...

#### Virtual machine config:
[VBox.log](https://github.com/user-attachments/files/17882351/VBox.log)
[VBoxHardening.log](https://github.com/user-attachments/files/17882352/VBoxHardening.log)
[weirdassinstall.log](https://github.com/user-attachments/files/17882353/weirdassinstall.log)
[VM config.txt](https://github.com/user-attachments/files/17882355/VM.config.txt)

**Comment by svartkanin** [comment]
Resolved already
