### ISSUE TITLE
Archinstall failing on lsblk (not a block device)

### ISSUE THREAD

**Issue by EyBmr** [archlinux/archinstall#2930]
### Which ISO version are you using?

archlinux-2024.11.01-x86_64.iso

### The installation log

```json
Mounting /dev/sda1: mount /dev/sda1 /mnt/arch_btrfs
Partition /dev/sda1 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Mounting /dev/sdb1: mount /dev/sdb1 /mnt/arch_btrfs
Partition /dev/sdb1 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Mounting /dev/sdc1: mount /dev/sdc1 /mnt/arch_btrfs
Partition /dev/sdc1 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Mounting /dev/sdd1: mount /dev/sdd1 /mnt/arch_btrfs
Partition /dev/sdd1 is currently mounted at: ['/mnt/arch_btrfs']
Unmounting mountpoint: /mnt/arch_btrfs
Could not determine the filesystem: None
Error calling lsblk: lsblk: /dev/nvme0n1p1: not a block device
{
   "blockdevices": [

   ]
}
```

#### Description of the issue

When running `archinstall` in the live Arch iso image, the following error happens:

![20241124_231818](https://github.com/user-attachments/assets/1ad0188b-d592-4431-93f3-c3367ea3b269)

It appears that archinstall has trouble running lsblk on `/dev/nvme0n1p1` which is the boot partition of my existing Arch installation.

However, running `lsblk` manually lists the affected block device just fine:

```
nvme0n1     259:2    0 931,5G  0 disk

├─nvme0n1p1 259:3    0     1G  0 part /boot

├─nvme0n1p2 259:4    0   865G  0 part /var/cache/pacman/pkg

│                                     /var/log

│                                     /home

│                                     /
```

CPU: AMD Ryzen 7 5700G with Radeon Graphics
Memory: 32GB
GPU: AMD Radeon RX 7800 XT
Mainboard: MSI B550-A-PRO
Drive: Samsung 980 PRO 1TB SSD

**Comment by EyBmr** [comment]
Fixed `lsblk` output linebreaks missing

**Comment by svartkanin** [comment]
There has been some new releases since the last ISO, would you mind updating archinstall to 3.0.1 and try again?

**Comment by EyBmr** [comment]
Yes, now it works. Thanks.
