### ISSUE TITLE
Failed to connect to user scope bus via local transport: No medium found

### ISSUE THREAD

**Issue by svyatoplamya** [archlinux/archinstall#2944]
### Which ISO version are you using?

"2024-11-01"

### The installation log

```json
https://0x0.st/XRiT.log
```

### describe the problem

My laptop model HONOR NMH-WDX9 as it is said in the logs

**Comment by svyatoplamya** [comment]
I chose pulseaudio as a sound server

**Comment by svartkanin** [comment]
This has been resolved in the latest release
