### ISSUE TITLE
Filled install with pre-mounted btrfs

### ISSUE THREAD

**Issue by Darkness-Monarch** [archlinux/archinstall#2952]
### Which ISO version are you using?

archlinux-2024.11.01-x86_64

### The installation log

```json
Hardware model detected: Dell Inc. Inspiron 5759; UEFI mode: True
Processor model detected: Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
Memory statistics: 14889656 available out of 16267968 total installed
Could not detect virtual system: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

System is not running in a VM: ['/usr/bin/systemd-detect-virt'] exited with abnormal exit code [1]: none

Virtualization detected: None; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation Skylake GT2 [HD Graphics 520] (rev 07)'])
```

### The installation log.
[archinstall log](https://0x0.st/XRM3.log)

### Describe the problem.
When I try to install arch linux with a pre-mounted btrfs partition configuration it fails.

### When was the last time it works.
archinstall-3.0.0 or below

### Testing that I have done.
Tried on multiple computers
Different subvolume layout
Tried the git repo master branch (git clone https://github.com/archlinux/archinstall.git)

### What I have not tested.
Different filesystem.
Different bootloaders.
Without Unified Kenal Image.
With swap disable.

### How reproduce the problem.
cfdisk /dev/sda
mkfs.vfat -F 32 /dev/sda5
mkfs.btrfs -L "Arch Linux" /dev/sda6
mount /dev/sda6 /mnt
btrfs subvolume create /mnt/@
btrfs subvolume create /mnt/@home
btrfs subvolume create /mnt/@log
btrfs subvolume create /mnt/@pkg
btrfs subvolume create /mnt/@.snapshots
umount /mnt
mount -o noatime,compress=zstd:5,ssd,discard=async,space_cache=v2,commit=120,subvol=@ /dev/sda6 /mnt
mkdir -p /mnt/home
mount-o noatime,compress=zstd:5,ssd,discard=async,space_cache=v2,commit=120,subvol=@home /dev/sda6 /mnt/home
mkdir -p /mnt/var/log
mount-o noatime,compress=zstd:5,ssd,discard=async,space_cache=v2,commit=120,subvol=@log /dev/sda6 /mnt/var/log
mkdir -p /mnt/var/cache/pacman/pkg
mount-o noatime,compress=zstd:5,ssd,discard=async,space_cache=v2,commit=120,subvol=@pkg /dev/sda6 /mnt/var/cache/pacman/pkg
mkdir -p /mnt/.snapshots
mount-o noatime,compress=zstd:5,ssd,discard=async,space_cache=v2,commit=120,subvol=@.snapshots /dev/sda6 /mnt/.snapshots
mkdir -p /mnt/boot
mount /dev/sda5 /mnt/boot
iwctl --passphrase [passphrase] station [name] connect [SSID]
pacman -Sy
pacman -Sy archinstall
archinstall

**Comment by svartkanin** [comment]
Could you please upload the full log

**Comment by svartkanin** [comment]
right, I missed that

Looking at the log it seems that the btrfs device is mounted 
```
                    "path": "/dev/sda6",
                    "pkname": "sda",
                    "log_sec": 512,
                    "size": "237568 MiB",
                    "pttype": "gpt",
                    "ptuuid": "bda33ac4-d7da-4429-aa10-232271bb167b",
                    "rota": false,
                    "tran": null,
                    "partn": 6,
                    "partuuid": "725f1901-023e-4e6a-9bc2-805114cdc6af",
                    "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
                    "uuid": "551d6276-b357-455f-96d6-88625e226267",
                    "fstype": "btrfs",
                    "fsver": null,
                    "fsavail": 246942793728,
                    "fsuse_percentage": "0%",
                    "type": "part",
                    "mountpoint": "/mnt/.snapshots",
                    "mountpoints": [
                        "/mnt/.snapshots",
                        "/mnt/var/cache/pacman/pkg",
                        "/mnt/var/log",
                        "/mnt/home",
                        "/mnt"
                    ],
                    ```
                    
I need to look into the code on what is happening exactly

**Comment by Darkness-Monarch** [comment]
> right, I missed that
> 
> Looking at the log it seems that the btrfs device is mounted
> 
> ```
>                     "path": "/dev/sda6",
>                     "pkname": "sda",
>                     "log_sec": 512,
>                     "size": "237568 MiB",
>                     "pttype": "gpt",
>                     "ptuuid": "bda33ac4-d7da-4429-aa10-232271bb167b",
>                     "rota": false,
>                     "tran": null,
>                     "partn": 6,
>                     "partuuid": "725f1901-023e-4e6a-9bc2-805114cdc6af",
>                     "parttype": "0fc63daf-8483-4772-8e79-3d69d8477de4",
>                     "uuid": "551d6276-b357-455f-96d6-88625e226267",
>                     "fstype": "btrfs",
>                     "fsver": null,
>                     "fsavail": 246942793728,
>                     "fsuse_percentage": "0%",
>                     "type": "part",
>                     "mountpoint": "/mnt/.snapshots",
>                     "mountpoints": [
>                         "/mnt/.snapshots",
>                         "/mnt/var/cache/pacman/pkg",
>                         "/mnt/var/log",
>                         "/mnt/home",
>                         "/mnt"
>                     ],
> ```
> 
> I need to look into the code on what is happening exactly

Ok

**Comment by HolyBlackCat** [comment]
This used to work before. A very unfortunate regression.

**Comment by codefiles** [comment]
I failed to consider one small detail in 8fc3dc43 that resulted in this bug. I can reproduce this bug and it is fixed with the patch I just submitted.
