### ISSUE TITLE
archinstall

### ISSUE THREAD

**Issue by gloriosotv** [archlinux/archinstall#2953]
Friend, the archinstall script has an error in the audio part. To install archlinux, you can only disable the audio if you install Pipewire or Pulseaudio, there is an error. Could you fix this?

Amigo, o script archinstall tem um erro na parte de áudio. Para instalar o archlinux, você só consegue desabilitar o áudio se instalar o Pipewire ou o Pulseaudio, há um erro. Você conseguiu consertar isso?

**Comment by svartkanin** [comment]
This has been resolved please use the latest version
