### ISSUE TITLE
unable to input ? (question mark) in any input field (including password fields)

### ISSUE THREAD

**Issue by treeshateorcs** [archlinux/archinstall#2959]
### Which ISO version are you using?

2024-11-01 (version 3.0.1-1)

### The installation log

```json
any hardware
```

### describe the problem

i guess it's self explanatory. when i type ? it shows the help screen. i understand that you can't have the question mark as part of a hostname, but what about password fields? it was possible before 3.0

**Comment by svartkanin** [comment]
Very good point thanks for bringing this up. We can switch the help trigger to something like ctrl+?

**Comment by zbikkk** [comment]
just encountered the same issue, i have a password with a question mark in it and inputting it brought up the help menu, i closed the menu and it seemed fine so i continued with the installation, but upon reboot sddm wouldn't accept the password so i was left with a useless system.

**Comment by svartkanin** [comment]
Fix is up
