### ISSUE TITLE
Have NTP enabled as an install-time option

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#297]
Having an accurate clock is a huge quality of life improvement. Maybe ask right after timezone and enable relevant systemd units if the user selects yes.

**Comment by Torxed** [comment]
if timezone is not empty, we could add "Would you like to enable automatic time synchronization?"
It's also a part of the [Installation guide](https://wiki.archlinux.org/index.php/Installation_guide#Update_the_system_clock).
