### ISSUE TITLE
Control characters are not filtered when typing in additional package names

### ISSUE THREAD

**Issue by correctmost** [archlinux/archinstall#2979]
### Description
I'm not sure if this issue affects other text input fields.

### Steps to reproduce
- Run `archinstall`
- Select "Additional packages"
- Type firefox, backspace, and then x again
- Press enter to receive an error that "firefox\x08x" was not found in the repository

### Screenshot
![additional_packages_screenshot](https://github.com/user-attachments/assets/2acbe641-b390-46fa-9e6c-426ea3ef2373)

### Version
- eacc28d577

**Comment by svartkanin** [comment]
I've tried to reproduce this on master but I'm receiving 
![image](https://github.com/user-attachments/assets/8c70d7e9-9a70-49bf-8ad4-7af23b4aab5d)

**Comment by rany2** [comment]
Please reopen this issue. It's not acceptable that a user could mistakenly set the keyboard layout to what appears to be a reasonable value (en) when it's actually only appropriate for the PinePhone.
