### ISSUE TITLE
Ctrl + h doesn't bring up help menu

### ISSUE THREAD

**Issue by correctmost** [archlinux/archinstall#2982]
### Description
Ctrl + h is listed as a shortcut in the help menu, but the shortcut doesn't seem to work.

### Steps to reproduce
- Run `archinstall`
- Press Ctrl + h and notice the help menu does not appear
- Press ? and notice Ctrl + h is listed as a shortcut

### Version
- eacc28d577

**Comment by svartkanin** [comment]
Fix is up
