### ISSUE TITLE
Auto font Select

### ISSUE THREAD

**Issue by LOL64654** [archlinux/archinstall#2993]
### describe the request

There is a problem when choosing some languages the text become square 
And I think the problem from the font so add auto font select to a compatible font
To the language and good bye :)
![image](https://github.com/user-attachments/assets/c2442e40-c944-4624-a0d4-d0d65ab1c6b7)

**Comment by svartkanin** [comment]
There's a description that some fonts rely on non latin characters need to be enabled manually.
We have tried automating this in the past but not all fonts are present on iso so there will always be gaps
