### ISSUE TITLE
add option for Virtualbox - virtualbox-guest-utils - and enable the vbox service

### ISSUE THREAD

**Issue by erikdubois** [archlinux/archinstall#2997]
### describe the request

![test](https://github.com/user-attachments/assets/807bfb51-b4d2-4dca-922f-dde2ed453d2c)

Would it be an idea to add the choice to add support for virtualbox-guest-utils and activate its service

all TWMs need to be helped to get a maximum resolution in virtualbox

Just an idea. 

I would not add it in the list like I have shown here but give user the choice 

I only needed to activate the vbox.service to have a full screen now.

Technically it can work

**Comment by svartkanin** [comment]
I think this is more of a after installation setup. If we go down that road of providing these things it will escalate quickly. `archinstall` is primarily to setup the base system and this probably goes beyond it.

**Comment by erikdubois** [comment]
I have been thinking exactly the same thing after writing this.

For future readers - in archinstall you can add extra packages 
add virtualbox-guest-utils (or -nox)
then later after rebooting

sudo systemctl enable--now vboxservice... TAB TAB and done

lets keep doing it manually
