### ISSUE TITLE
More desktop environment options

### ISSUE THREAD

**Issue by mackilanu** [archlinux/archinstall#303]
Right now, the desktop environments available are Gnome, KDE and Awesome. Is there any plans to add more? For example i3 and xfce.

If this is not in the making, I can probably make that happen. Please feel free to suggest more DE's/WM's (As long as they are not exclusively available in the AUR)

**Comment by Torxed** [comment]
All of the ones mentioned are [already implemented](https://github.com/archlinux/archinstall/tree/master/profiles), however, they will not be visible until the next release *(due in a week or two)*. We're still performing tests on those profiles and they are a bit experimental.

If you do want to jump in on the testing, there's instructions on the README how to update against `master` and even some documentation in GitHub wiki pages on how to build your own ISO with any branch you desire. I'll be closing this, but if you have any suggestions for more profiles that are preferably widely used - feel free to open a new issue or start a conversation under [discussions](https://github.com/archlinux/archinstall/discussions) or jump in to any of our chat services.

**Comment by dylanmtaylor** [comment]
> Right now, the desktop environments available are Gnome, KDE and Awesome. Is there any plans to add more? For example i3 and xfce.
> 
> If this is not in the making, I can probably make that happen. Please feel free to suggest more DE's/WM's (As long as they are not exclusively available in the AUR)

Adding on to this, the new list looks like this (I think you will be very happy with the selection):

![image](https://user-images.githubusercontent.com/277927/114713484-28cc4000-9cff-11eb-934a-871ffa1879b7.png)

**Comment by mackilanu** [comment]
@dylanmtaylor Wow! This project is moving fast, I love it :)

**Comment by dylanmtaylor** [comment]
Yeah, probably not going to add more though, as there is a minimal install where you can install something yourself if you need something that's not supported, somehow.
