### ISSUE TITLE
Specify partition sizes

### ISSUE THREAD

**Issue by IngCr3at1on** [archlinux/archinstall#305]
Trying to use this to install arch on a 1TB drive, I select the drive during the installation process and choose ext4 then when it gets to the efi setup it errors saying not enough space on `/boot`

I did a quick `lsblk` to see and `/boot` is a 512M partition. Is there a way to set this partition to be larger I've been combing through the code and haven't found it yet but my python is pretty bad?

**Comment by dylanmtaylor** [comment]
So this is sort of coming in 2.1.4 with manual partitioning, implemented as part of #124. You'd simply make all the partitions you need, mount them under /mnt and run the installer, and you can have any size/layout you want including a separate home, swap, etc.

**Comment by dylanmtaylor** [comment]
A more interesting question is why you don't have enough space on /boot. I'd love to see what files are on there and how big they are. There shouldn't be much there, if it is a newly created partition and none of the files for systemd-boot are particularly large.

**Comment by Torxed** [comment]
We've actually had one other user with this issue, and IIRC the issue then was that `/boot` previously contained a wrong file system type before running the installer, which caused the installer to be a bit confused on how to proceed safely.

If you don't mind, a full `lsblk -f -o+TYPE,SIZE` would be very helpful.

**Comment by insanemal** [comment]
@dylanmtaylor I've run into cases where 512MB is not enough. Usually its when I'm dual booting Lin/Win and using the same efi partition for both.

I've been using 1GB as my default for ages and even in small 128GB SSD installs I don't really miss the extra 512MB. 
Also Arch Install guide recommends >512MB so, perhaps a revisit to this size is in order?

**Comment by IngCr3at1on** [comment]
Turns out this was resolved by zeroing out the hard drive.

**Comment by Torxed** [comment]
> Turns out this was resolved by zeroing out the hard drive.

Sadly this is the current workaround for a few of the partitioning issues with `v2.1.3`, hopefully these should all be fixed for `v2.1.4` which is coming on the next ISO if everything goes well.
