### ISSUE TITLE
ModuleNotFoundError: No Module named 'archinstall' || NEED HELP!

### ISSUE THREAD

**Issue by neepan** [archlinux/archinstall#3052]
I tried installing and running the archinstall command by different ways, but at the end all the method failed what to do next... It is showing ModuleNotFoundError: No Module named 'archinstall'. how to solve this?? i am using latest iso 2024.12.01

**Comment by sebgra** [comment]
Same issue here, even trying to install from the latest iso, upgrading and with archlinux-keyring.
Any advice ?

**Comment by abhimangs** [comment]
I’m also experiencing the same issue. Hoping for a resolution soon!

**Comment by abhimangs** [comment]
I had the same issue, and this worked for me:

**`pacman -Sy archinstall archlinux-keyring python python-pyparted python-simple-term-menu python-annotated-types python-pydantic python-pydantic-core python-typing_extensions`**

Give it a try and see if it resolves your issue!  
If any other missing module is mentioned, let me know the details of that error. These are the missing packages that resolved the issue for me.

**Comment by 8f7b68f2d3** [comment]
Big thanks bro it's worked.

**Comment by notleks2411** [comment]
I can confirm the same issue. I ended up manually installing Arch. It came out better than the script! :smile:

**Comment by neepan** [comment]
It worked thanks bro

**Comment by abhimangs** [comment]
> It worked thanks bro

Haha, I’m just figuring things out myself too! 😊 Glad it helped, though

**Comment by sebgra** [comment]
Worked for me, thanks for the help!
