### ISSUE TITLE
Bootloader not found

### ISSUE THREAD

**Issue by marcuxyz** [archlinux/archinstall#313]
Hello,

I initialized the script to perform the arch linux installation and it was successfully executed. At the end, I get a message in green asking to restart the system using the command `reboot`.

But when restarting, the boot system is not found. I cannot access the system via `SSD`. I have already reinstalled about 5x and the same problem continues.

Can someone help me? Thanks

**Comment by Torxed** [comment]
Any error messages during boot? *(such as which UID it's waiting for)*
Running `lsblk -f -o+TYPE,SIZE` before running the installer and also after it's supposedly finished would help a lot.

Apologies for the inconvenience! We'll try our best to sort it out!

**Comment by dylanmtaylor** [comment]
Are you installing in UEFI or legacy mode? Until 2.2.0, only UEFI is supported.

**Comment by marcuxyz** [comment]
Hello, thanks guys for replies.

@Torxed  I took a screenshot :

![image](https://user-images.githubusercontent.com/9499562/115020342-da4eab00-9e90-11eb-8073-ce88e39f7d8f.png)

@dylanmtaylor Yes, installation follows the UEFI mode 😃

**Comment by Torxed** [comment]
> Hello, thanks guys for replies.
> 
> @Torxed I took a screenshot :
> 
> ![image](https://user-images.githubusercontent.com/9499562/115020342-da4eab00-9e90-11eb-8073-ce88e39f7d8f.png)
> 
> @dylanmtaylor Yes, installation follows the UEFI mode 😃

What does `cat /mnt/boot/loader/entries/*` say?
I just realized I forgot PARTUUID in the command previously as well: `lsblk -f -o+TYPE,SIZE,PARTUUID`

Is your motherboard configured to boot form `/dev/sda`? Otherwise it's going to try and boot `/dev/sdb` where ther's an ISO?

**Comment by marcuxyz** [comment]
Hi, @Torxed 

Thank you very much for responding,
I will try to execute the command again and post the result here.

My motherboard is configured correctly

`/dev/sda` is my ssd
`/dev/sdb` is my flash drive.

I had to put the pendrive to boot and be able to type the `lsblk command`

**Comment by dylanmtaylor** [comment]
Just curious, have you tried with the 2.1.4 RC (https://github.com/archlinux/archinstall/releases/tag/v2.1.4-RC1)? Lots of fixes landed in that one, so it might work better for you. What's the make and model of your system and/or motherboard?

Can you take pictures of the UEFI/legacy configuration options and/or secure boot settings so we can double-check those are right? I'm not sure why this is not working for you, but I'd love to figure it out. Have you had other Linux distros installed successfully?

**Comment by Torxed** [comment]
I'm 70% sure it's the `PARTUUID` that isn't matching up with the boot loader config in `/boot/loader/entries/*`, but I would need to have the content to verify. But testing with 2.1.4 would be very appreciated as well! : )

**Comment by marcuxyz** [comment]
Hey guys!

Yes, I already have experience with other Linux installations on my computer. In fact, the installation of Arch Linux without archinstall goes well.

Right below I will post the requested images, on `PARTUUID` I will have to take a look. I'll do it right now! 

My motherboad is B460M-DS3H.

![CMS](https://user-images.githubusercontent.com/9499562/115090226-b15b0400-9eea-11eb-8e77-587c67d17beb.jpg)
![Secure](https://user-images.githubusercontent.com/9499562/115090232-b3bd5e00-9eea-11eb-9272-d90dd7e4909f.jpg)

**Comment by dylanmtaylor** [comment]
> Hey guys!
> 
> Yes, I already have experience with other Linux installations on my computer. In fact, the installation of `Arch Linux` without `archinstall `goes well.
> 
> Right below I will post the requested images, on `PARTUUID` I will have to take a look. I'll do it right now!
> 
> My motherboad is B460M-DS3H.
> 

Your hardware definitely supports booting EFI images, and if you can install arch without the installer, it's almost certainly an installer bug.

**Comment by marcuxyz** [comment]
@dylanmtaylor @Torxed thanks for help me. I can using the image `v2.1.4-RC1` and solved the issue.

You can close the issue :) I'm be happy.

**Comment by Torxed** [comment]
> @dylanmtaylor @Torxed thanks for help me. I can using the image `v2.1.4-RC1` and solved the issue.
> 
> You can close the issue :) I'm happy.
> 
> Thanks!!!!!!!!!!!!!!!

Thanks for trying it out, we've tried to fix a lot of partitioning issues in that release without introducing to much complexity. So I'm glad that worked :D Do let us know if there's any other issues!
