### ISSUE TITLE
Formatting fails under certain conditions

### ISSUE THREAD

**Issue by SecondThundeR** [archlinux/archinstall#324]
### Description:
There is an issue where formatting may fail if user skips manual partitioning step.
**Example:**

![image](https://user-images.githubusercontent.com/36604233/115281797-11071880-a152-11eb-93b6-373ffc89513d.png)

### Steps to reproduce:
1. Use `archinstall` and fully install system with it.
2. Run `archinstall` again.
3. Select the drive and select "Keep existing partitions ...".
4. When you get a list of partitions, press Enter and continue with the installation.
5. After the formatting countdown, formatting will fail.

> Tested with latest `archinstall` master branch changes on VirtualBox 6.1

**Comment by Torxed** [comment]
Ah, ofc we need a verification that the user selected at least two partitions, `/` and `/boot`!

**Comment by SecondThundeR** [comment]
I wondering, what partition do it set by default. Because, it fails even when I select any partition and just hit Enter twice

**Comment by Torxed** [comment]
Nothing should be set by default, if "keep partitions" is selected, there has to be a user choice.
The installer will not try to make any informed decisions based on the disks themselves.

**Comment by SecondThundeR** [comment]
It might be worthwhile to check for `/mnt` and `/mnt/ boot` and replace them with `/` and `/ boot` * (or leave as is) *

**Comment by Torxed** [comment]
In guided we can probably do some magic and replace `/mnt` with `/` for instance, since I don't see any use case where they would ever need to actually write `/mnt` unless they chose "Use /mnt as is" which is the third new option. But I'd like to merge your other PR before starting on fixing this since it has to do with user-input :)
