### ISSUE TITLE
Don't use 0 unless it's the default.

### ISSUE THREAD

**Issue by jtagcat** [archlinux/archinstall#329]
![image](https://user-images.githubusercontent.com/38327267/115570820-f47ff300-a2ad-11eb-97ab-4a18e400060e.png)

For me, 0 implies, that it's the default (can be selected by just pressing enter).  
Don't show 0 at all, or move the 'if you don't want to install one' to `0: Don't use a preconfigured profile`.

Thoughts?

**Comment by Torxed** [comment]
Most if not all steps are optional and can be skipped with just hitting Enter.
The text `Leave blank and hit enter to skip this step` should also indicate this.

I'm moving this to a conversation topic as it's not an issue in of itself in my opinion.
Perhaps a healthy discussion can hash out a suggestion on how to better put emphasis on the skipping part.
