### ISSUE TITLE
Invalid user name `Konstantin`

### ISSUE THREAD

**Issue by KonstantinasK-1205** [archlinux/archinstall#332]
Just encountered that it is possible to crash installer by passing username with upper case letter, requiring to restart all install from beginning.
It would be nice to have check system, which would disallow entering username with upper case letters.

Log File:
[install.log](https://github.com/archlinux/archinstall/files/6353154/install.log)

And trace log:
![20210421_213629](https://user-images.githubusercontent.com/9715435/115604147-b6082980-a2e9-11eb-91c1-555ef00dd732.jpg)

**Comment by Torxed** [comment]
Fixed in #170 and will be released in a day roughly. Next official ISO will not have this issue :) thanks for reporting tho, it's appreciated :)
