### ISSUE TITLE
Add support for loading installer args from a config file

### ISSUE THREAD

**Issue by l4zy0n3** [archlinux/archinstall#333]
Support for running an unattended installation from a config file would be great as I saw that the installer is storing args as a dict, which is spitted out as JSON in logs. We could use the same JSON as a config file to run the installation.

**Comment by l4zy0n3** [comment]
I have already started working on this, will raise a PR if this seems a valid case

**Comment by Torxed** [comment]
Sounds awesome, but just to avoid double work, check out this discussion: https://github.com/archlinux/archinstall/discussions/150
