### ISSUE TITLE
[Enhancement] Add verification for UEFI/Boot method

### ISSUE THREAD

**Issue by manderio** [archlinux/archinstall#353]
### Problem
We managed to complete an installation without errors using the script, but booting into the system didn't work since we didn't boot using UEFI.

### Suggested solution
Make sure to verify that the installer is run in UEFI rather than Legacy at the start of the script so you don't discover it in end. Would be great to just verify that the boot method is correct at the start of the script. Something like "this system is only supporting [boot mode], exiting script". Rather than just having the process act like nothing happened. 

### Additional notes
I know this can be checked, might be something to make more clear in the readme since it was missed by several of my friends. Maybe add it to the command you want to use for the guided installation.
Have a nice day and a hug, thanks for creating this 🤗

**Comment by dylanmtaylor** [comment]
This is already fixed in 2.1.4, the next release and 2.2.0 should add legacy boot support so it should work regardless.

**Comment by manderio** [comment]
Thanks!

We used 2.1.3.1, so that explains why this was an issue. Thanks though! Also, awesome with the legacy addition! Thanks.
