### ISSUE TITLE
Typo in base package names

### ISSUE THREAD

**Issue by l4zy0n3** [archlinux/archinstall#363]
Facing the following issue when selecting kernels ( built from master)
A space is needed to be added after base package names

error: target not found: linux-firmwarelinux-lts
==> ERROR: Failed to install packages to new root

'/usr/bin/pacstrap /mnt base base-devel linux linux-firmwarelinux-lts efibootmgr btrfs-progs' did not exit gracefully (trace log above), exit code: 256

**Comment by advaithm** [comment]
@Torxed  we can close this issue, my pr reworked how we add the appropriate kernel which solved this issu
