### ISSUE TITLE
Can't run archinstall right after running it

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#372]
If the previous run of archinstall mounted /mnt and /mnt/boot, archinstall will fail to run the second time.

Workaround: umount /mnt/boot /mnt (or just reboot)

**Comment by Torxed** [comment]
Please attach the error so we can work on a potential work-around.
Since we shouldn't unmount `/mnt` on re-runs, since we should support *"Use `/mnt` as is"*.. But perhaps we can fix the issue that is the reason for this ticket.

**Comment by dylanmtaylor** [comment]
![VirtualBox_Arch_29_04_2021_08_43_21](https://user-images.githubusercontent.com/277927/116552481-0faebc00-a8c7-11eb-847e-f9bdcfd957fb.png)

**Comment by abhishekshree** [comment]
Yeah @dylanmtaylor, I am facing exactly the same issue while installing it on my machine. Did you find a workaround?
