### ISSUE TITLE
Can not write known profile-names in the profile step

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#382]
I can not write `awesome` in the profile step of the guided installer.
This is a regression in feature and I would very much like that back.

This probably got lost when we created the `top_level` profiles, which means you have to go through desktop first (which installs a bunch of stuff) just to get to awesome.

I'd very much like to be able to write *known* profiles directly in this step and bypass jumping through hoops.

**Comment by dylanmtaylor** [comment]
> I can not write `awesome` in the profile step of the guided installer.
> This is a regression in feature and I would very much like that back.
> 
> This probably got lost when we created the `top_level` profiles, which means you have to go through desktop first (which installs a bunch of stuff) just to get to awesome.
> 
> I'd very much like to be able to write _known_ profiles directly in this step and bypass jumping through hoops.

I don't know if there's an easy fix for this; awesome is in a sense a child profile of desktop. A lot of the common installation stuff for desktops is handled in the desktop top level profile to keep the individual desktop profiles clean, and just installing awesome without doing the desktop and awesome profile would lead to a bad experience, probably broken because of missing xdg-utils in awesome's case.

**Comment by dylanmtaylor** [comment]
It's odd that we can do profile: "gnome" in the config file yet this is an issue - I think this is because the generic select is validating it's in the list that is passed to it. Maybe we need a way to handle hidden values that are accepted but not displayed? It's going to be tricky.

**Comment by Torxed** [comment]
I think we could do @SecondThundeR's trick of printing our own list, giving `generic_select()` a different list (that matches index wise) but call `generic_select(options, options_output=False)`. That way, we can have generic select absolut inputs validated and returned, but hidden from the output.

**Comment by dylanmtaylor** [comment]
> I think we could do @SecondThundeR's trick of [printing our own list](https://github.com/archlinux/archinstall/blob/49e6cbdc545402e066bdc2daf6054abf6c1bf977/archinstall/lib/user_interaction.py#L403-L407), giving `generic_select()` a different list (that matches index wise) but call `generic_select(options, options_output=False)`. That way, we can have generic select absolut inputs validated and returned, but hidden from the output.

So use the filter logic to print the list, and then use the full list of profiles for validation in generic select
