### ISSUE TITLE
TODO: Add super users created during installation to docker group

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#395]
Right now you get a permission denied error with docker if that profile is installed unless the users are in the docker group.

Note that docker works just fine with sudo/running as root.

**Comment by AladW** [comment]
This is something users should decide, instead of being enabled implicitly in an installer. See the warning in https://wiki.archlinux.org/title/Docker#Installation

**Comment by Torxed** [comment]
We could steal some code from: https://github.com/archlinux/archinstall/blob/6a0e3d9e4b31ce443b6a9ff22cc513ef53ab0437/profiles/applications/pipewire.py#L11-L14

**Comment by svartkanin** [comment]
@Torxed we can close this as it should be resolved with the new profile manger and the updated docker profile
