### ISSUE TITLE
Support AppArmor installation

### ISSUE THREAD

**Issue by kvuj** [archlinux/archinstall#399]
AppArmor is much simpler to set up / use than SELinux and is fully supported in all official Arch kernels.

To set up, it requires:
- Setting the kernel parameters: lsm=lockdown,yama,apparmor,bpf
Arch notes:
```
Make sure that apparmor is the first "major" module in the list.[1] Examples of valid values and their order can be found in security/Kconfig.
capability should be omitted from lsm= as it will always get included automatically.
```
- Install apparmor for userspace tools and libraries to control AppArmor.
- To load all AppArmor profiles on startup, enable apparmor.service.

**Comment by dylanmtaylor** [comment]
> AppArmor is much simpler to set up / use than SELinux and is fully supported in all official Arch kernels.

This sounds very subjective but the fact that it's in extra not the AUR and is officially supported is a plus.
> 
> To set up, it requires:

> * Setting the kernel parameters: lsm=lockdown,yama,apparmor,bpf
>   Arch notes:
> 
> ```
> Make sure that apparmor is the first "major" module in the list.[1] Examples of valid values and their order can be found in security/Kconfig.
> capability should be omitted from lsm= as it will always get included automatically.
> ```

This would likely require a facility in the codebase to customize kernel parameters. I don't think we have this now.

> * Install apparmor for userspace tools and libraries to control AppArmor.
> * To load all AppArmor profiles on startup, enable apparmor.service.

These bits here are trivial, and we could easily do these things in an applications/apparmor.py profile.

I'm not sure if this is something we want to present to users as an option in guided.py, as dealing with apparmor or even selinux is something advanced that most users won't play with, and it sounds like this CAN be done post-installation without too much trouble. It might make sense to have a profile available if archinstall is used as a library to automate a custom installation; there are examples of this, but I think we'd have to implement the bits to set kernel params first.

Not opposed to this change but don't feel like it makes sense to have an apparmor/selinux choice in guided.py.

**Comment by Torxed** [comment]
We'll need a better way of handling kernel modules and parameters, I'm on it :)

**Comment by grazzolini** [comment]
This seems to be completely out of the scope of an installer

**Comment by dylanmtaylor** [comment]
> This seems to be completely out of the scope of an installer

I agree to a point, which is why I'm against it ever landing in guided.py (and I will personally not use it), but having an application profile for it to make it east for people who want to script a custom installation and have it out of the box isn't bad. One thing I really like about ArchInstall is that it's a great tool for helping people write their own installation code since it's a library, and having a mechanism to set kernel params is something that would benefit this use case regardless, so apparmor would serve as a good test for this functionality.

**Comment by grazzolini** [comment]
We're heading towards feature creep, that's my only concern. archinstall should deliver a simple installation to the user, as close as possible to the installation guide. All of this is optional to the users and should be done after the installation.

**Comment by Torxed** [comment]
> The only thing addressed in the comments is the kernel cmdline parsing (which is fine), but why support something non-standard like apparmor? It requires several profiles for applications and shouldn't be added willynilly without the user understanding the implications. You'll also struggle with apparmor profile coverage for most packages in Arch Linux.

Fair point, as much as I would love to attempt to increase security of the user base (through attempts like these), understanding security and educating is in some if not most cases more rewarding in the long run. I think we'll revert the introduction of the apparmor application profile - even tho it's hidden. It serves little to no meaning unless we started shipping application profiles like say Ubuntu does, which is unmaintainable by this project I would say. And users need a full understanding of what the profile does before using it anyway.

But I'll leave this issue open as it serves as a reminder of the kernel parameters, which is added in #401 once that's tested and merged.

I appreciate everyone's involvement, concerns and feedback! And I'd like to point out that most these features come from a place of good intention, and I love the opportunity to explore, evaluate and elaborate on them - whether they get implemented or scrapped - it's a healthy discussion and test of features!

**Comment by Torxed** [comment]
Kernel parameters have now been implemented. But closing this issue since AppArmor itself will not be supported at this current time. We can come back and re-visit this later if there's a sane way of supporting it :)

**Comment by Foxboron** [comment]
Lovely, thanks for the work :)

**Comment by dominiksr** [comment]
Has anything changed through this time in this regard? It would be nice to have some MAC configured by default after installing archlinux using archinstall. Especially since archinstall is so good and easy to use

**Comment by Torxed** [comment]
I'm not against it, as long as it's a profile (that detects all the software that will be installed) or under a "enhancements" menu.
If anyone has experience or are willing to deep dive the wiki, contributors in this area is welcome :)
