### ISSUE TITLE
Installation crashes if graphics card driver selection was skipped

### ISSUE THREAD

**Issue by SecondThundeR** [archlinux/archinstall#402]
In current master branch, there is an issue that causes the installation to crash when the user skips choosing a graphics card driver (Error example: `KeyError: None`)
**Solution:** Disable empty selection for graphics card driver selection

> Currently, pending PR #379 will close that issue once merged
> Fix commit: https://github.com/archlinux/archinstall/pull/379/commits/5f1156f80e4038a52719f4ba01c87eae4f0a8660

**Comment by dylanmtaylor** [comment]
> In current master branch, there is an issue that causes the installation to crash when the user skips choosing a graphics card driver (Error example: `KeyError: None`)
> **Solution:** Disable empty selection for graphics card driver selection
> 
> > Currently, pending PR #379 will close that issue once merged
> > Fix commit: [5f1156f](https://github.com/archlinux/archinstall/commit/5f1156f80e4038a52719f4ba01c87eae4f0a8660)

As mentioned in #414, maybe we can default to all the open-source drivers by default?

**Comment by dylanmtaylor** [comment]
If #418 gets merged, can we make it default to "All open-source (default)"?

**Comment by SecondThundeR** [comment]
If both PR’s will be merged at the same time, so I think I can add default option in my PR
