### ISSUE TITLE
Check internet connection before formatting disk

### ISSUE THREAD

**Issue by daniel-schuermann** [archlinux/archinstall#413]
At the moment, the installation errors out after the disk has been formatted in case there is no internet connection.

Would also be nice to be able to configure wifi properly, but that probably has to wait a bit longer.

**Comment by Torxed** [comment]
I'll add a check to make sure pacman can access it's configured mirrors before continuing.

---

The wifi-configuration part has been discussed quite thurrowly, and the consensus is that archinstall will most likely never include wifi configuration. There's other tools that does this way better, and the wifi configuration can get so complex that it's almost a full project of it's own. So `iwctl` will be recommended instead :)

**Comment by dylanmtaylor** [comment]
I agree - users should have internet configured before running archinstall. iwd isn't hard to use.

**Comment by daniel-schuermann** [comment]
> I agree - users should have internet configured before running archinstall. iwd isn't hard to use.

I'd then even suggest checking the internet connection on starting archinstall with a small error message to configure it first. Just pinging a mirror or something like that.

**Comment by Torxed** [comment]
> I agree - users should have internet configured before running archinstall. iwd isn't hard to use.

They should have a reachable mirror*
