### ISSUE TITLE
Gnome package group bloat 

### ISSUE THREAD

**Issue by jatin-cbs** [archlinux/archinstall#415]
In this installer package groups and meta packages have been used for different profiles which is great !
However 

https://archlinux.org/groups/x86_64/plasma/  or  https://archlinux.org/packages/extra/any/plasma-meta/ which is used in the installer

it doesn't include any video players / music players like dragonplayer/elisa, okular document viewer and other default KDE applications which are part of https://archlinux.org/packages/extra/any/kde-applications-meta . Which is great as it is giving users a choice of what they want to use and it respects the Arch Linux philosophy. Other package groups like xfce4 and other profiles too are very minimal.
Comparing it to the gnome package group

https://archlinux.org/groups/x86_64/gnome/

This has epiphany as the default browser
Orca Screen reader for individuals who are blind or visually impaired
gnome-music, and other gtk applications like gnome-books which are not even pre installed on other gnome distributions.

To solve this either we should have a different gnome-minimal group or meta package. Similar to plasma having a different meta package for DE and another meta package for applications.

manjaro as an example does this by https://gitlab.manjaro.org/profiles-and-settings/iso-profiles/-/blob/master/manjaro/gnome/Packages-Desktop   the packages which have `>` are extra packages and are packages not part of gnome-minimal.

**Comment by dylanmtaylor** [comment]
We try to make the installation very minimal by default, but as you stated, the gnome package group does have things that some users don't want in it. Unfortunately, there's not an easy solution for this because if gnome were to add a new dependency in the future that it needed to run and we didn't update the list (which would be very long if we weren't to use the meta package), it would break installations. Splitting 'gnome' up into things like 'gnome-shell, gnome-session, gnome-terminal', etc. is VERY hard to get right and have it work consistently as packagers make changes. I know it's not perfect, and we DO aim to install a basic system by default for everyone (and it's unfortunate that we install things like epiphany and orca), but again, it's hard to fix this without causing a potential problem, so it's kind of a necessary compromise. What you could do is open a ticket against the packagers of gnome for Arch linux to see if they would be willing to remove some of these unneeded optional packages from the base group. I'm kind of against trying to split them out ourselves as there is risk involved if new deps are added later, etc.

**Comment by jatin-cbs** [comment]
There is no dependency removal needed, but the Applications like orca, epiphany and few others, I can sort the packages out. 

We can add an option in the installer to trim the packages getting installed tho ! 
Bring this pacman thing in front
For example - 
Enter a selection (default=all): ^5-8 ^2
which will select all packages except 5 through 8 and 2 for installation.

as given in the pacman axample here https://wiki.archlinux.org/title/pacman

**Comment by dylanmtaylor** [comment]
> There is no dependency removal needed, but the Applications like orca, epiphany and few others, I can sort the packages out.
> 
> We can add an option in the installer to trim the packages getting installed tho !
> Bringing this pacman thing in front
> 
> Just as an example -
> Enter a selection (default=all): ^5-8 ^2
> which will select all packages except 5 through 8 and 2 for installation.
> 
> as given in the pacman axample here https://wiki.archlinux.org/title/pacman
> 
> Maybe asking the user "Do you want to review packages to be installed ?"
> I don't think it will be hard to implement @dylanmtaylor

Listing the packages for installation is something we've been wanting to do, but I think it'd ve hard to get the 'install everything except x,y,and z' if users want to install gnome piecemeal, minimal might be a better choice or they could remove what they want after installing it. I honestly think this should be raised as a packaging issue like 'epiphany should not be part of the base gnome group and should instead be in gnome-extras'. I think reliable installation is more important than offering too much customization and I think keeping the number of choices low to not overwhelm users is a good ideal to have. It's a shame there isn't a gnome-minimal group we can pull in for this, but it is what it is.

**Comment by jatin-cbs** [comment]
pacman has a feature when installing a group where it asks 

`Enter a selection (default=all): `

But yes, I will open a ticket regarding this as having a gnome-minimal group will be the ideal solution.

**Comment by Col433** [comment]
I think you opened a can of worms by adding more options for different DE's. I would prefer just xorg and one default DE. To me it would have been better to have added a help file listing DE's and display managers and which packages are need for each to be added when you get to additional packages to install. A note there too how to enable the display manager. Yes @dylanmtaylor the script needs to be kept minimal. You just make the install script too complex by trying to please everyone.

**Comment by Col433** [comment]
@dylanmtaylor Yes fair point Dylan and one opinionated default won't please everyone but honestly anyone who is installing Arch should have enough understanding to know how to just go for xorg and put their desired DE and display manager in under additional packages and know the command to enable it. Yes it's all in the Arch wiki but as long as their there just as an option it's fine by me 😊

**Comment by jatin-cbs** [comment]
Ya I too personally don't have any issue, but if we had a better meta package or group would have been better, if such arrives I will open another issue to use that as a default instead. Closing.
