### ISSUE TITLE
add_bootloader() won't install anything but 'systemd-bootctl'

### ISSUE THREAD

**Issue by emanuelep57** [archlinux/archinstall#419]
Before trying to implement the function I looked at the code and I saw installing grub was possible via passing as argument of the function add_bootloader( ) 'grub-install' or bootloader='grub-install' (in either way it doesn't work) then I tried by replacing grub-install with grub, obtaining the same result. On the other hand, using systemd-bootctl works perfectly, so I guess the problem is not the function itself being used. Here is the install.log I have. (I want to premise I am testing this of virtual machine (QEMU) with UEFI system) 
https://pastebin.com/wwwE1aGA

**Comment by dylanmtaylor** [comment]
This is on a master build? Or is this on 2.1.4? GRUB is not implemented in 2.1.4 (May ISO).

**Comment by emanuelep57** [comment]
> This is on a master build? Or is this on 2.1.4? GRUB is not implemented in 2.1.4 (May ISO).

Actually I thought It'd have been available already, my bad then.. when do you think will it be implemented?

**Comment by dylanmtaylor** [comment]
> > This is on a master build? Or is this on 2.1.4? GRUB is not implemented in 2.1.4 (May ISO).
> 
> Actually I thought It'd have been already available , my bad then.. when do you think will it be implemented?

Probably June unless it's somehow broken and we have to back it out
