### ISSUE TITLE
README.md minimal example is missing awesome

### ISSUE THREAD

**Issue by zebulon2** [archlinux/archinstall#421]
Hi,
In the "Scripting your own installation" example, it is said that the minimal example given "Installs a profile with a window manager called awesome (more on profile installations in the documentation)." Am I missing something, or does it actually install 'minimal' only? There should be "installation.install_profile('awesome')" in place of (or in addition to?) the "installation.install_profile('minimal')" line. Am I correct?

**Comment by Torxed** [comment]
Ouff, writing is hard apparently.. I missed that when I tweaked the minimal installation example in the README, good catch!
You are 100% correct in that it should also contain `installation.install_profile("awesome")`, or that we should swap the word "awesome" to "minimal" in the description below.

if you want some cred you're free to open a PR and add it back right around line 94 in the readme or change the description after :D If not I can do the required changes in while.
