### ISSUE TITLE
GRUB support for dual-boot

### ISSUE THREAD

**Issue by matteoturini** [archlinux/archinstall#424]
Adding grub support would be nice for dualbooting Arch & Windows.

**Comment by dylanmtaylor** [comment]
You should also be able to dual-boot Windows with systemd-boot.

**Comment by Torxed** [comment]
Thanks @jatin-cbs for linking that duplicate issue! Closing this one to keep the number of issues to a minimum.

Feel free to subscribe and track the other issue @matteoturini :)
