### ISSUE TITLE
Unknown blockdevice type for /dev/sr0: rom

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#429]
A minor issue with a debug error slipping through the cracks:

![2021-05-12-125331_894x119_scrot](https://user-images.githubusercontent.com/861439/117964029-697ca080-b321-11eb-88b7-3cf87fdb2c4c.png)

**Comment by dylanmtaylor** [comment]
We ought to filter out the installer and any loopback devices from this list.

**Comment by dylanmtaylor** [comment]
This message is coming from https://github.com/archlinux/archinstall/blob/master/archinstall/lib/disk.py#L95

Is debugging output supposed to be visible?

**Comment by Torxed** [comment]
No it's a regression from when I moved to `logging.<level>` instead of `LOG_LEVELS.<level>`.
It's the comparison operator that is flipped the wrong way. It's fixed in `torxed-fix-partitioning` branch :)

**Comment by Torxed** [comment]
Fixed in 49e6cb
