### ISSUE TITLE
Install frozen on "waiting for automatic mirror selection (reflector) to complete."

### ISSUE THREAD

**Issue by NotTheUsualYT** [archlinux/archinstall#431]
Hello everyone! I am running archinstall on my laptop and it freezes when it gets to "waiting for automatic mirror selection (reflector) to complete." I have left it running for ~8 hours now and it is still stuck.

**Comment by dylanmtaylor** [comment]
Do you have an internet connection established?

**Comment by NotTheUsualYT** [comment]
> Do you have an internet connection established?

Yes, I used iwctl to connect and confirmed it with ping.

**Comment by Torxed** [comment]
Which Arch Linux ISO did you use? And after you've configured the wifi, but before you run the installer, what does this say:
```
systemctl show --no-pager -p SubState --value reflector.service
```

**Comment by NotTheUsualYT** [comment]
> Which Arch Linux ISO did you use? And after you've configured the wifi, but before you run the installer, what does this say:
> 
> ```
> systemctl show --no-pager -p SubState --value reflector.service
> ```
> 
> If it's not `dead` or `failed`, you should check `journalctl -f -u reflector.service` for any errors. Probably a proxy error or something similar.

ISO: `archlinux-2021.05.01-x86_64.iso`
Output of `systemctl`: `auto-restart`
Output of `journalctl`: 
`archiso systemd[1]: reflector.service: Main process exited, code=exited, status=1/FAILURE
archiso systemd[1]: reflector.service: Failed with result: 'exit-code'.
archiso systemd[1]: Failed to start Refresh Pacman mirrorlist with Reflector..
archiso systemd[1]: reflector.service: Scheduled restart job, restart counter is at 6.
archiso systemd[1]: Stopped Refresh Pacman mirrorlist with Reflector..
archiso systemd[1]: Starting Refresh Pacman mirrorlist with Reflector....
archiso reflector[723]: error: failed to retrieve mirrorstatus data: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid. (_ssl.c:1123)>
archiso systemd[1]: reflector.service: Main process exited, code=exited, status=1/FAILURE
archiso systemd[1]: reflector.service: Failed with result: 'exit-code'.
archiso systemd[1]: Failed to start Refresh Pacman mirrorlist with Reflector..
archiso systemd[1]: reflector.service: Scheduled restart job, restart counter is at 7.
archiso systemd[1]: Stopped Refresh Pacman mirrorlist with Reflector..
archiso systemd[1]: Starting Refresh Pacman mirrorlist with Reflector....
archiso reflector[723]: error: failed to retrieve mirrorstatus data: URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid. (_ssl.c:1123)>
archiso systemd[1]: reflector.service: Main process exited, code=exited, status=1/FAILURE
archiso systemd[1]: reflector.service: Failed with result: 'exit-code'.
archiso systemd[1]: Failed to start Refresh Pacman mirrorlist with Reflector..`

**Comment by Torxed** [comment]
So, technically this isn't an Archinstall issue any longer. I would investigate why the reflector can not update the mirror-list as it's supposed to do on each ISO boot. The only way archinstall could continue would be to either:

 1. Kill the reflector service after X seconds (really shouldn't even consider this)
 2. Ignore/skip mirror selection in the installer - because it might get overwritten at any second by the reflector once it kicks in

You can try to manually run the reflector, in the ISO, by doing *(or any other examples under [Reflector (archwiki)](https://wiki.archlinux.org/title/Reflector), bare in mind that this replaces the mirrorlist, so reboot before you run again)*:
```
reflector --latest 200 --protocol http --protocol https --sort rate --save /etc/pacman.d/mirrorlist
```

**Comment by dylanmtaylor** [comment]
From the errors, it says "certificate is not yet valid". This indicates your BIOS clock is set in the far past. Please set your clock appropriately and try again.

**Comment by dylanmtaylor** [comment]
@Torxed I think you can probably close this since it's not an archinstall specific issue anyways.

**Comment by Torxed** [comment]
> @Torxed I think you can probably close this since it's not an archinstall specific issue anyways.

True. Had a thought of keeping this open since we could probably detect and at least warn about time sync issues, if we checked validity against archlinux.org certificate. But then I also thought, why doesn't the ISO have ntp?

Anyway, side thoughts, closing :)

**Comment by hiblari1** [comment]
i js had same error, thx @dylanmtaylor i fixed it 👍

**Comment by bidit06** [comment]
Hey, I am doing archlinux and it stuck in "Waiting for automatic mirror selection (reflector) to complete". How to fix?

**Comment by hiblari1** [comment]
> Hey, I am doing archlinux and it stuck in "Waiting for automatic mirror selection (reflector) to complete". How to fix?

might be your BIOS time not set correctly
