### ISSUE TITLE
Allow choosing multiple mirrors.

### ISSUE THREAD

**Issue by jtagcat** [archlinux/archinstall#457]
'Type your country', mine (EE) has only one mirror. Configuring only one mirror doesn't seem the best idea.

**Comment by kevr** [comment]
I'll look into producing a patch for this. Good idea. Hopefully they like it :)

**Comment by Torxed** [comment]
> I'll look into producing a patch for this. Good idea. Hopefully they like it :)

Would definitely like this! I would suggest using `archinstall.generic_multi_select()` and just make sure that `set_mirrors` both inside the `Installation()` class can handle it as well as `mirrors.py`'s function called the same can as well. (one sets outside the installation in the ISO and one inside the installation).

**Comment by kevr** [comment]
Apologies guys, this completely slipped away from my mind. Been super busy lately... I'll dedicate some days this next week to nailing this one.

**Comment by Torxed** [comment]
> Apologies guys, this completely slipped away from my mind. Been super busy lately... I'll dedicate some days this next week to nailing this one.

No worries at all, I have myself been occupied by other things which means I wouldn't have had time to merge it anyway. So don't stress it! : )

**Comment by svartkanin** [comment]
@Torxed @kevr  I'm happy to pick this up, unless someone is working on it already?

**Comment by Torxed** [comment]
Solved by @svartkanin, great work! :)
