### ISSUE TITLE
Install fails if ucode image is already on the filesystem

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#459]
This is from master (5/16 build).
![IMG_20210516_165114](https://user-images.githubusercontent.com/277927/118412262-082d3800-b667-11eb-9b1b-e333f9233425.jpg)

**Comment by kevr** [comment]
imo, this isn't really an issue with the installation script. if you have files that should be owned by packages in pacman, that's an issue in all situations -- what should the installer really decide to do in this case?

This is really just due to somebody having files already located on a system that are taken care of by the install.

**Comment by Torxed** [comment]
I'm guessing the [ucode](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/4c5f3fdcc7f5d2b6c1bcc11001ed58923db481ab) isn't something you would compile yourself. If that's the case, it should be safe to do `--overwrite {self.target}/boot/*-ucode.img` in the pacstrap. It's kind of a work-around, but should work?

**Comment by dylanmtaylor** [comment]
> I'm guessing the [ucode](https://github.com/intel/Intel-Linux-Processor-Microcode-Data-Files/commit/4c5f3fdcc7f5d2b6c1bcc11001ed58923db481ab) isn't something you would compile yourself. If that's the case, it should be safe to do `--overwrite {self.target}/boot/*-ucode.img` in the pacstrap. It's kind of a work-around, but should work?

Correct, it should probably remove and replace it.

**Comment by dylanmtaylor** [comment]
This issue occurred when trying to replace one install of Arch with another using format. Apparently /boot is not wiped.

**Comment by Torxed** [comment]
> This issue occurred when trying to replace one install of Arch with another using format. Apparently /boot is not wiped.

Also correct, users should be able to re-use `/boot` partitions, even with multiple Arch Linux installations. So this needs fixing :)

**Comment by dylanmtaylor** [comment]
My vote is +1 on your --overwrite suggestion, if you would like to commit that @Torxed ?

**Comment by Torxed** [comment]
> My vote is +1 on your --overwrite suggestion, if you would like to commit that @Torxed ?

Sure, gimme an hour :)

**Comment by Torxed** [comment]
Added `options=[]` to pacstrap function, however, it doesn't seam like `pacstrap` passes down the flags to `pacman`.
So there's no way to get `--overwrite` down to pacman sadly through pacstrap.

**Comment by Torxed** [comment]
#461 fixes this issue (untested tho, but should work).
Also swapped `subprocess.check_output()` for `SysCommand` in `archinstall.cpu_vendor()`.

So the `kvm` *(or whatever CPU arch was used)* output shouldn't pop out whenever that function is called.
