### ISSUE TITLE
cmd_output is undeclared in luks.py but is used when raising an exception

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#467]
```
		if cmd_handle.exit_code != 0:
			raise DiskError(f'Could not encrypt volume "{partition.path}": {cmd_output}')
```

This will need to be written get the output from the cmd_handle instance of the SysCommand class, or else if this is thrown the output won't be displayed, and we'll instead get an undeclared variable error.

**Comment by Torxed** [comment]
Also changed a `self.partition` to `partition` since the function takes a partition specifically.
