### ISSUE TITLE
OSError: out of pty devices

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#477]
In branch `torxed-fix-107`:
![screenshot](https://user-images.githubusercontent.com/861439/118774924-a64b1900-b886-11eb-83fd-24e4249d7826.jpg)

Either missing `devpts` mount in chroot or we're not closing the pty's as we should.

**Comment by Torxed** [comment]
Doesn't seam like we're forgetting to close the pty's. And the mounts are correct.

![screenshot2](https://user-images.githubusercontent.com/861439/118776480-566d5180-b888-11eb-9b29-88821550192c.jpg)
![screenshot3](https://user-images.githubusercontent.com/861439/118776482-5705e800-b888-11eb-9195-4070b8841113.jpg)
![screenshot](https://user-images.githubusercontent.com/861439/118776485-579e7e80-b888-11eb-84fb-dd651494960b.jpg)

**Comment by antechdesigns** [comment]
Was just about to report this, same branch, 'out of pty devices' 

thanks

**Comment by Torxed** [comment]
I'm pretty sure it's because of the excessive `ps -p <pid>` checks.
But I don't understand why yet, so I gotta dig deep why that happens.

**Comment by Torxed** [comment]
Not entirely sure what causes the issue.
I don't see any excessive PTY's anywhere, but it seams very restrictive as it is, so limiting it to one execution at a time seams to be the reliable way to go. Which means `SysCommand()` can not use `SysCommand()` to check if the first session is still running, using `subprocess.check_output()` instead for the `/usr/bin/ps` calls :)

**Comment by antechdesigns** [comment]
I just tested this branch again, while it did install.... now when it  boots, I am now getting:

ERROR; device 'UUID not found Skipping fsck'
mount; /new_root: can't find  UUID=*********
'you are now being dropped into emergency shell'
sh: can't access tty; job control turned off
[rootfs ]#

**Comment by Torxed** [comment]
> I just tested this branch again, while it did install.... now when it boots, I am now getting:
> 
> ERROR; device 'UUID not found Skipping fsck'
> mount; /new_root: can't find UUID=*********
> 'you are now being dropped into emergency shell'
> sh: can't access tty; job control turned off
> [rootfs ]#

This feels like a different issue all together.
I don't recognize it, so I'm wondering if it's GRUB related?

**Comment by antechdesigns** [comment]
Could well be, I did choose Grub when I installed...
I can open a new bug report if that's the case?

**Comment by Torxed** [comment]
> Could well be, I did choose Grub when I installed...
> I can open a new bug report if that's the case?

Absolutely! Will become easier to track the issue as well, and we can link PR's to the issue :)

**Comment by antechdesigns** [comment]
I just tested the 'master' branch, (could not find the torxed-fix-107) and was flawless :+1:
