### ISSUE TITLE
Failure at disk partition with already partitioned disk

### ISSUE THREAD

**Issue by eli-xciv** [archlinux/archinstall#478]
Branch: master
Type: MBR w/ Grub

Device: Toshiba Laptop

Issue: Archinstall fails trying to partition `/dev/sda` when a partition is already on disk.  Error thrown is https://github.com/archlinux/archinstall/blob/e3c8692bfa65d9b689bb50f9a4469989332adde4/archinstall/lib/disk.py#L541

This may be related to https://github.com/archlinux/archinstall/issues/460 since I only had 1 partition on the drive, but I selected a new scheme, the default during prompt, so...

Fix:
- run `parted /dev/sda rm <partition#>`
-  verify no paritions w/ `lsblk`
- `archinstall` completes

**Comment by Torxed** [comment]
As an update, this will be fixed in #426. We're trying to make partitioning more robust and separate business logic to avoid issues like these.

**Comment by eli-xciv** [comment]
@Torxed I don't know if this is changed in #426 but I just realized that a follow-on issue to this is that the partition created is not labeled as `bootable`. Should I create a new issue?

**Comment by Torxed** [comment]
> @Torxed I don't know if this is changed in #426 but I just realized that a follow-on issue to this is that the partition created is not labeled as `bootable`. Should I create a new issue?

It will be covered in the same PR :)

**Comment by eli-xciv** [comment]
Awesome thanks

> > @Torxed I don't know if this is changed in #426 but I just realized that a follow-on issue to this is that the partition created is not labeled as `bootable`. Should I create a new issue?
> 
> It will be covered in the same PR :)

Awesome thanks
