### ISSUE TITLE
Add ability to run commands in chroot automatically

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#479]
Just adding this to my wishlist, might implement eventually.
It would be nice if we added the ability to add a command list to the declarative installation instructions which would be run against the installation via `arch-chroot` or `systemd-nspawn` like so:
```json
    "custom-commands": [
        "cd /home/devel; git clone https://aur.archlinux.org/paru.git",
        "chown -R devel:devel /home/devel/paru",
        "usermod -aG docker devel"
    ]
```

**Comment by l4zy0n3** [comment]
We could add support for running a bash script directly from a URL

**Comment by Torxed** [comment]
I think I need more information to understand what this even means.
Isn't this what profiles are doing right now? Perhaps a small pseudo example would help here or a description of a scenario.

**Comment by dylanmtaylor** [comment]
> I think I need more information to understand what this even means.
> Isn't this what profiles are doing right now? Perhaps a small pseudo example would help here or a description of a scenario.

This is kind of given in my PR for post-install commands

**Comment by dylanmtaylor** [comment]
Basically, it would be in a 'custom-commands' declaration in a config file, but otherwise use existing profiles.

**Comment by Torxed** [comment]
Sounds good :)
