### ISSUE TITLE
Setting profile name in config file is currently broken

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#486]
Anything I tried except profile: null did not seem to work.

![VirtualBox_Arch_19_05_2021_20_00_51](https://user-images.githubusercontent.com/277927/118899998-f99c8600-b8dd-11eb-938b-b3774e6881f8.png)

**Comment by l4zy0n3** [comment]
![image](https://user-images.githubusercontent.com/21274221/118939937-d4efef00-b96d-11eb-817d-ffd9a2852caf.png)
Finally! @Torxed
