### ISSUE TITLE
Can't have users set to null in configuration profile

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#487]
![VirtualBox_Arch_19_05_2021_20_28_12](https://user-images.githubusercontent.com/277927/118901247-cb6c7580-b8e0-11eb-95ca-eae52c5ed200.png)

This should be permissible for a config file installation assuming superusers is set or root is set.

**Comment by dylanmtaylor** [comment]
Workaround: 

```
"users": {}

**Comment by dylanmtaylor** [comment]
> Ah, yea `users` should be set to `{}` instead of `None`.
> Not sure where that's being set to `None`, probably from the ask-for-users function?

It was me doing the configuration file manually, I thought setting it to null in the JSON would be valid.

**Comment by Torxed** [comment]
> > Ah, yea `users` should be set to `{}` instead of `None`.
> > Not sure where that's being set to `None`, probably from the ask-for-users function?
> 
> It was me doing the configuration file manually, I thought setting it to null in the JSON would be valid.

We should probaby handle `none` values if it's not to hard
