### ISSUE TITLE
from .systemd import Boot is the function set_keyboard_language instead of the file

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#489]
This means that Boot undeclared in set_x11_keyboard_language. We need to move this to the top of the file with other imports.

**Comment by Torxed** [comment]
Should we close this one as well?

**Comment by dylanmtaylor** [comment]
Maybe, I don't think we fixed it though

**Comment by Torxed** [comment]
Saw another missing import, so added that in 7daaf11
