### ISSUE TITLE
Installation does not print config path/url at the end

### ISSUE THREAD

**Issue by l4zy0n3** [archlinux/archinstall#510]
![image](https://user-images.githubusercontent.com/21274221/119256201-2ce05d00-bbdd-11eb-8865-5bd7d76e9520.png)

**Comment by Torxed** [comment]
What's the expected output in contrast?

**Comment by l4zy0n3** [comment]
> What's the expected output in contrast? The `--config <path>` is missing? I think this is a `zsh` issue?

Yes, it's just a minor issue, --config <path to URL> should show up, investigating this

**Comment by svartkanin** [comment]
@Torxed probably can close this?

**Comment by svartkanin** [comment]
@Torxed I think we can close this
