### ISSUE TITLE
Allow non-HTTPS mirrors

### ISSUE THREAD

**Issue by KhalilSantana** [archlinux/archinstall#517]
Hello there, as discussed on the matrix chat, I'm opening this issue to gather comments and feedback from the wider community, as well as any possible security implications this change might have.

**Description**
Archinstall currently only allows HTTPS mirrors see here[[1](https://github.com/archlinux/archinstall/blob/master/archinstall/lib/mirrors.py#L82)], which works for most users, but not all countries/regions have HTTPS mirrors, for example Brazil doesn't have any HTTPS mirror, but plenty of very fast HTTP ones.

**Reasons to consider allowing non-HTTPS:**

* HTTP is more widely available.
* HTTP allows for transparent caching at the ISP or LAN, allowing for even smaller network footprint. And while setting up a local mirror isn't hard, a dumb transparent cache is much more generic and useful in more situations.

**Reasons to NOT allow non-HTTPS mirrors**

* HTTPS can act as another layer of security, for example see this[[2](https://lists.debian.org/debian-security-announce/2019/msg00010.html)] Debian/apt bug.
* Using HTTP leaks which packages you are installing, which can be seen as a privacy problem.
* Bootstrapping an outdated pacman-keyring via HTTP is unsafe, although this should (AFAIK) only happen if your .ISO is severely outdated, and is not automatic.

**My opinion on this situation**

While I'm not an Archlinux dev or pacman expert, I believe all packages (`*.tar.zstd`) are signed (`*.sig`), and the public key of these signatures is stored in pacman's keyring (located at `/etc/pacman.d/gnupg`), so even if some Evil Attacker tampers with anything you download, it should be fine, because pacman should check the signature against the locally trusted keyring.

**Comment by dylanmtaylor** [comment]
I'm fine with this so long as HTTPS is preferred where available.

**Comment by 0ae** [comment]
> I'm fine with this so long as HTTPS is preferred where available.

I agree.

**Comment by Torxed** [comment]
If there's no objections to this within a few days, I'll merge https://github.com/archlinux/archinstall/pull/537 and it will introduce HTTP mirrors as well.

**Comment by Torxed** [comment]
Merged #537 which introduces HTTP mirrors. For those that rely on this should now see their region in the selection process if the region only caters via HTTP.
