### ISSUE TITLE
Cannot install on custom btrf partition

### ISSUE THREAD

**Issue by geowarin** [archlinux/archinstall#524]
Hello,

I love the idea of this installer but I haven't figure out a way to use it on a custom btrfs partition.
I'm trying to use the "leave blank option" for partitioning.

![image](https://user-images.githubusercontent.com/1045636/119901183-ddd05a00-bf45-11eb-88f9-eeb62de2be3e.png)

What I've done is fomatted and created btrfs suvolumes:

```
sgdisk -n 1:0:+300MiB -t 1:ef00 -c 1:efi /dev/sda
sgdisk -N 2 -t 2:8300 -c 2:root /dev/sda

mkfs.vfat /dev/sda1
mkfs.btrfs /dev/sda2

btrfs su cr /mnt/@

umount /mnt
mount -o noatime,compress=lzo,space_cache=v2,discard=async,subvol=@ /dev/sda2 /mnt
mount /dev/sda1 /mnt/boot
```

So I have /mnt and /mnt/boot volumes. 
If I don't run the `mount -o` part (no custom options for mount), and replace it with a simple `mount /dev/sda2 /mnt` the installer runs.

I'm not proficient in python enough to debug this, but in my opinion, the installer should not care how the disks are mounted as long as they are here... Should it?

Is there a way to achieve what I'm trying to do? Thank you.

**Comment by Torxed** [comment]
Thank you for reporting this, this feature is some what experimental in the things it support.
But we do want to be able to support these kinds of setups. I'm currently re-working/upgrading the partitioning logic and this will be one of the priorities. I'll also reference #93 and #112 as they are related.
