### ISSUE TITLE
Add feature to write out config to file in logs dir w/ credentials stripped

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#525]
I was thinking about adding this feature. Probably should go here:

https://github.com/archlinux/archinstall/blob/4bb644bf5b8ce70bc08c76deeeb6fe71a3c36c1a/examples/guided.py#L261

**Comment by Torxed** [comment]
Isn't this exactly what the referenced line of code does?
Or you want to log it separately? Because it is found in `/var/log/archinstall/install.log` currently :)
