### ISSUE TITLE
Default linux kernel is hardcoded in systemd-boot entry

### ISSUE THREAD

**Issue by japareaggae** [archlinux/archinstall#532]
## Summary

Pull request #315 added the ability to select a different kernel other than the default, but it seems to result in an unbootable system, since the code that generates the systemd-boot entry is hardcoded to load the default kernel:

https://github.com/archlinux/archinstall/blob/7b1096bfa6a5d042b38341b68f857dbe4f150bb3/archinstall/lib/installer.py#L471

## How to reproduce

I wrote a JSON config for archinstall with the following key in it:

    "kernels": ["linux-zen"],

After installing and rebooting, systemd-boot showed no entries available to boot. I dropped to an UEFI shell and found that the generated entry was trying to load the default linux kernel instead of linux-zen:

    # Created by: archinstall
    # Created on: 2021-05-30_21-00-01
    title Arch Linux
    linux /vmlinuz-linux
    initrd /initramfs-linux.img
    options root=PARTUUID=e6393745-d916-4176-a7c3-315b3457092c rw intel_pstate=no_hwp

The linux-zen files were present in the EFI system partition, and manually editing the entry to add the -zen suffix made the system bootable.

## Installation log

[install.log](https://github.com/archlinux/archinstall/files/6566917/install.log)

**Comment by Torxed** [comment]
Well spotted! We'll get that fixed! Thanks for reporting it and really great detail work on the issue!
