### ISSUE TITLE
Output looks broken with pacman 6

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#536]
Since `pacman` v6 was released, it introduced paralell downloads among other things (color enhancement and other good stuff).
Due to how we show "progressbars" in archinstall, the output looks broken and scrambled.

**The installs work fine!**

It's jut that the outlook looks garbage because: https://github.com/archlinux/archinstall/blob/615d0d38dd577a054151abcebf32b3a30b98e3fd/archinstall/lib/general.py#L212-L223

**Comment by jtagcat** [comment]
https://user-images.githubusercontent.com/38327267/121242195-ce2d0b80-c88b-11eb-87ed-86f36e5f78a1.mp4

Not exactly sure, whether this is what you meant..?

**Comment by Torxed** [comment]
Kind of, at some point it was even worse.
It used to spit out new-lines that made a kind of "ladder" filling the entire screen with "random text" that was supposed to be a progress bar.

And later, it started behaving like in your video except it also ate the previous output:
![output](https://user-images.githubusercontent.com/861439/121496073-6afdbf00-c9da-11eb-90e1-2f809a5ad66f.gif)
