### ISSUE TITLE
No such file or directory: '/mnt/boot/loader/loader.conf'

### ISSUE THREAD

**Issue by HackBug** [archlinux/archinstall#541]
Hey all, I'm trying out the arch installer for the first time today to reformat and refresh a system I've been using for a while. Process went smoothly until it began the installation, and then gave the error in the title immediately after installing efivar during the post-transaction hooks. I'm including my log file.

I'm capable of installing on my own so this isn't an urgent issue, but I'm not really sure what went wrong. It might have something to do with the fact I'm running the image off of ventoy, but I'm not 100% sure why that would be the case. I might be able to test without ventoy later.

[install.log](https://github.com/archlinux/archinstall/files/6587566/install.log)

**Comment by Torxed** [comment]
This is a *weird* issue that's been popping up today. Thank you for reporting! Any information would help here to be honest. And the install lo should help!

**Comment by HackBug** [comment]
So on a second try it worked again after two changes, not sure if either are relevant, but here's what I did (after a reboot as well)

1) Deleted all partitions and set the drive to gpt (didn't create any partitions myself)
2) Did not include any extra packages

Everything else was identical as far as I can tell.

**Comment by HackBug** [comment]
I take it back: I apparently (accidentally) booted without UEFI into the ventoy image. The installation itself seems pretty unwilling to boot, so I'm going to try installing one more time in UEFI mode.

**Comment by dylanmtaylor** [comment]
> I take it back: I apparently (accidentally) booted without UEFI into the ventoy image. The installation itself seems pretty unwilling to boot, so I'm going to try installing one more time in UEFI mode.

Does the Arch ISO work with Ventoy? Wow. I didn't realize that worked...

**Comment by HackBug** [comment]
I've already reset it, but it would end on a blank black screen with blinking cursor. I'm pretty confident this was an issue with my bios, though. This particularly computer has been finicky with UEFI in the past.

**Comment by HackBug** [comment]
So I've had a successful reinstall now, with a nearly identical setup. This time I used --debug, and here's the log. Hope it helps.
[install.log](https://github.com/archlinux/archinstall/files/6587818/install.log)

**Comment by dylanmtaylor** [comment]
Sadly, that install just shows that it worked correctly. The installation log from when it did not work would have been more helpful, but unfortunately, it's not possible to save that off after the fact.

**Comment by HackBug** [comment]
Sorry it wasn't broken again, I guess 🤣.

**Comment by Torxed** [comment]
```
[anton@bigrigv2 Downloads]$ diff packages.official.txt packages.archinstall.txt
72a73
> git 2.31.1-1
107c108
< js78 78.10.1-1
---
> js78 78.11.0-1
257a259,261
> perl-error 0.17029-3
> perl-mailtools 2.21-5
> perl-timedate 2.33-3
273a278
> python-cachecontrol 0.12.6-3
275a281
> python-colorama 0.4.4-3
276a283
> python-contextlib2 0.6.0.post1-3
277a285,286
> python-distlib 0.3.2-1
> python-distro 1.5.0-3
278a288
> python-html5lib 1.1-6
287a298
> python-msgpack 1.0.2-2
289c300
< python-oauthlib 3.1.0-6
---
> python-oauthlib 3.1.1-1
291a303,304
> python-pep517 0.10.0-2
> python-pip 20.3.1-1
292a306
> python-progress 1.5-5
293a308
> python-pyopenssl 20.0.1-1
296a312,313
> python-resolvelib 0.5.4-1
> python-retrying 1.3.3-9
298a316
> python-toml 0.10.2-3
299a318
> python-webencodings 0.5.1-6
```
...

**Comment by dylanmtaylor** [comment]
@Torxed users are still seeing this, check the logs from Discord #help with Steven after doing a systemd-boot install over a GRUB installation.

**Comment by Torxed** [comment]
> @Torxed users are still seeing this, check the logs from Discord #help with Steven after doing a systemd-boot install over a GRUB installation.

I'll catch up and read through the details! Thanks for pinging!

**Comment by teras** [comment]
I have the same issue on a brand new Dell 9710. I didn't want to destroy Windows (yet), so what I did was to shrink the Windows partition, and create manually two partitions one for the `ext4` (arch) filesystem, and one for swap.

Then I mounted the "linux" partition under `/mnt` as prompted. I didn't mount any EFI partitions (maybe this is the reason?).
Then I launched the installed and I didn't pick GRUB since the system is indeed EFI-based.

Then installer crashes with error:

`[Errno 2] No such file or directory: '/mnt/boot/loader/loader.conf'`

I checked the `/mnt/boot` folder and it's empty.
Should I have mounted the EFI partition under `/mnt/boot` as well?

**Comment by Torxed** [comment]
> I didn't mount any EFI partitions (maybe this is the reason?).

That would be the reason. I'm surprised the `bootctl install` didn't crash tho, which should be the one that sets up the loader file structure IIRC. Another reason might simply be that certain packages weren't installed properly (due to network hickups). This is something we need to fix as well as it should simply re-try to install those missing packages and not continue silently.

If you could provide me with a `/var/log/archinstall/install.log` file that would be helpful to double check :)

**Comment by teras** [comment]
Here it is.
I also have a question.
The correct location to mount EFI partition is '/mnt/boot' right?
Or should be one more level deep?

```
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'disk', 'size': '29.9G', 'children': [{'name': 'sda1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '748M'}, {'name': 'sda2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '3719-544C', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '84M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '953.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'ESP', 'uuid': 'D079-58C6', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '500M'}, {'name': 'nvme0n1p2', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '128M'}, {'name': 'nvme0n1p3', 'fstype': 'ntfs', 'fsver': None, 'label': 'Windows', 'uuid': '24867D85867D57EE', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '426.3G'}, {'name': 'nvme0n1p4', 'fstype': 'ntfs', 'fsver': None, 'label': 'WINRETOOLS', 'uuid': '96C4ACCAC4ACAE45', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.1G'}, {'name': 'nvme0n1p5', 'fstype': 'ntfs', 'fsver': None, 'label': 'Image', 'uuid': '48427F58427F4A28', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '9.2G'}, {'name': 'nvme0n1p6', 'fstype': 'ntfs', 'fsver': None, 'label': 'DELLSUPPORT', 'uuid': '344481944481598E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.1G'}, {'name': 'nvme0n1p7', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': 'b9417220-34aa-42a3-9d1b-7400c8756001', 'fsavail': '473.4G', 'fsuse%': '0%', 'mountpoints': ['/mnt'], 'type': 'part', 'size': '507.8G'}, {'name': 'nvme0n1p8', 'fstype': 'swap', 'fsver': '1', 'label': None, 'uuid': 'fdbd1c98-7777-4612-b41a-a02b6374451a', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '7.8G'}]}]}
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'disk', 'size': '29.9G', 'children': [{'name': 'sda1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '748M'}, {'name': 'sda2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '3719-544C', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '84M'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '953.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'ESP', 'uuid': 'D079-58C6', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '500M'}, {'name': 'nvme0n1p2', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '128M'}, {'name': 'nvme0n1p3', 'fstype': 'ntfs', 'fsver': None, 'label': 'Windows', 'uuid': '24867D85867D57EE', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '426.3G'}, {'name': 'nvme0n1p4', 'fstype': 'ntfs', 'fsver': None, 'label': 'WINRETOOLS', 'uuid': '96C4ACCAC4ACAE45', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.1G'}, {'name': 'nvme0n1p5', 'fstype': 'ntfs', 'fsver': None, 'label': 'Image', 'uuid': '48427F58427F4A28', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '9.2G'}, {'name': 'nvme0n1p6', 'fstype': 'ntfs', 'fsver': None, 'label': 'DELLSUPPORT', 'uuid': '344481944481598E', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '1.1G'}, {'name': 'nvme0n1p7', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': 'b9417220-34aa-42a3-9d1b-7400c8756001', 'fsavail': '473.4G', 'fsuse%': '0%', 'mountpoints': ['/mnt'], 'type': 'part', 'size': '507.8G'}, {'name': 'nvme0n1p8', 'fstype': 'swap', 'fsver': '1', 'label': None, 'uuid': 'fdbd1c98-7777-4612-b41a-a02b6374451a', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '7.8G'}]}]}
You can skip selecting a drive and partitioning and use whatever drive-setup is mounted at /mnt (experimental)
Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
-- Guided template chosen (with below config) --
{
    "!root-password": "******",
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "harddrive": null,
    "hostname": "erebos",
    "kernels": [
        "linux"
    ],
    "keyboard-language": "gr",
    "mirror-region": {
        "Greece": {
            "https://repo.greeklug.gr/data/pub/linux/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "NetworkManager": true,
        "nic": "Use NetworkManager to control and manage your internet connection"
    },
    "ntp": true,
    "packages": [],
    "profile": {
        "path": "/usr/lib/python3.9/site-packages/archinstall/profiles/desktop.py"
    },
    "script": "guided",
    "superusers": {
        "teras": {
            "!password": "******"
        }
    },
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "target-mount": "/mnt",
    "timezone": "Europe/Athens",
    "users": {}
}
Waiting for automatic mirror selection (reflector) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'intel-ucode']
Adding bootloader systemd-bootctl to Partition(path=/dev/nvme0n1p7, size=-1, fs=ext4, mounted=/mnt)
Installing packages: ('efibootmgr',)
[Errno 2] No such file or directory: '/mnt/boot/loader/loader.conf'
```

**Comment by teras** [comment]
As a feedback, when I mount the `EFI` partition under `/mnt/boot` the installation is performed.
May I propose to have a message somewhere, that the EFI partition should be mounted as well, to help people in the future of such mistakes?

**Comment by Torxed** [comment]
> The correct location to mount EFI partition is '/mnt/boot' right?

That is correct. All subsequent folders are created by the installation process.
`/` and `/boot` are the only folders to mount, prepended with whatever mount destination you'd like, usually that's `/mnt`.

The installer should have taken care of mounting the `/boot` part of the device correctly, if it didn't something's wrong.

**Comment by roope242** [comment]
> I've already reset it, but it would end on a blank black screen with blinking cursor. I'm pretty confident this was an issue with my bios, though. This particularly computer has been finicky with UEFI in the past.

Out of curiosity, which kernel were you trying to boot?
I had this issue when trying to boot LTS or ZEN kernels, when the normal worked fine. I fixed this by manually installing the needed nvidia packages for those kernels.

**Comment by marquedej** [comment]
I ran into this issue this morning.
I resolved it as follows:

1. run archinstall
2. upon failure ("No such file or directory ..."), manually create these two folders, as follows:
2.1. mkdir /mnt/boot/loader
2.2. mkdir /mnt/boot/loader/entries
3. re-run archinstall

At this point, the installation completes successfully.

**Comment by Torxed** [comment]
> I ran into this issue this morning. I resolved it as follows:
> 
> 1. run archinstall
> 2. upon failure ("No such file or directory ..."), manually create these two folders, as follows:
>    2.1. mkdir /mnt/boot/loader
>    2.2. mkdir /mnt/boot/loader/entries
> 3. re-run archinstall
> 
> At this point, the installation completes successfully.

This is usually due to a package not being installed correctly and the installation continued anyway. This is fixed in master.

**Comment by escape0707** [comment]
Two more my friends installation failure logs, if they help: https://fars.ee/-mM_ https://fars.ee/cEQk

I told them to manually partition, format and mount the disk and then install use the "with mounted `/mnt`" option. They are not having problems now.

I do have to mention that both of their first run of installation script was cancelled on half way due to slow / failed mirror selection. And the problem happened on the succeeding run.

**Comment by Torxed** [comment]
I hope that the recent changes in `master` will solve a lot of these "ghost" issues. Where it looks like the installer has run it course without issues but strange missing pieces pops up. The recent changes being that if a package is not installed correctly, the installer will halt. In the future we might be able to add re-tries and stuff, but at least we won't end up with half ok systems :)

**Comment by kallisti5** [comment]
same issue just now installing on a 2011 Apple iMac.  Three times in a row with varying partition configurations

**Comment by Torxed** [comment]
> same issue just now installing on a 2011 Apple iMac. Three times in a row with varying partition configurations

`master` dev branch or the official ISO? because this should be fixed in the repo now, the release is not out yet tho.

**Comment by uranderu** [comment]
I have the same issues as described above, however during install I saw something among the line of this "Error not enough space at /mnt/boot need 4000 blocks only have 46". If it is relevant, how do I create a log file of this?

**Comment by Torxed** [comment]
> need 4000 blocks only have 46". If it is relevant,

This is related to a previous installation not reserving enough on `/boot` and is a known issue, and should be fixed in `master` as well if you choose to wipe. There's no fix for dualboot yet, other than we'll implement some checks and instruct the user to manually correct the size.

**Comment by uranderu** [comment]
I cloned the master branch and used that instead of the one that comes provided with the liveiso and everything went great! I don't use dual boot though :) Thanks for the help though!
