### ISSUE TITLE
If choosing to format a whole drive, has_content should not be called

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#544]
We shouldn't care if it has content if we're about to delete it all.

**Comment by Torxed** [comment]
New partitioning will not do this.
But even the old code shouldn't either, because `self.keep_partitions = False` overrides this?

**Comment by dylanmtaylor** [comment]
In the 6/1 ISO, I installed it sanely once then ran mkswap on /dev/sda1. I reran after rebooting and chose format all. It failed in has_content.

**Comment by Torxed** [comment]
Then we have a logic issue some where.
I would say it's not worth fixing it - unless we plan on releasing a patch release.

Otherwise the new partitioning logic will handle this (and all other inconsistencies).
