### ISSUE TITLE
Guided install with config without harddrive set fails

### ISSUE THREAD

**Issue by Mattias-** [archlinux/archinstall#549]
A barebone config json file without harddrive set fails to install.
Is this a supported feature?
What I initially expected was to get prompted for the missing information before proceeding with the install.
A good solution for me would be to simply run a modified script, just wanted to see if I'm doing something wrong.

```json
{
    "bootloader": "systemd-bootctl",
    "filesystem": "btrfs",
    "hostname": "my-machine",
    "kernels": [
        "linux"
    ],
    "keyboard-language": "us",
    "nic": "Copy ISO network configuration to installation",
    "ntp": true,
    "packages": [],
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "Europe/Stockholm",
}
```

Error message as follows:

```
$ sudo archinstall --config ./config.json
Traceback (most recent call last):
  File "/usr/bin/archinstall", line 33, in <module>
    sys.exit(load_entry_point('archinstall==2.2.0', 'console_scripts', 'archinstall')())
  File "/usr/lib/python3.9/site-packages/archinstall/__init__.py", line 87, in run_as_a_module
    script.execute()
  File "/usr/lib/python3.9/site-packages/archinstall/lib/profiles.py", line 161, in execute
    self.spec.loader.exec_module(sys.modules[self.namespace])
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/archinstall/examples/guided.py", line 442, in <module>
    archinstall.arguments['harddrive'] = archinstall.BlockDevice(path=archinstall.arguments['harddrive']['path'])
KeyError: 'harddrive'
```

**Comment by Mattias-** [comment]
Now when I think of it, a potential fix would be to set `"silent": false` in the config and use

```py
if not archinstall.arguments.get('silent', None):
```
in

https://github.com/archlinux/archinstall/blob/a4033a7d3a94916f2b4972d212f9d0069fca39cd/examples/guided.py#L442-L444

What do you think?

**Comment by l4zy0n3** [comment]
We actually pass silent using `archinstall --silent` which sets `silent` to `true`, if we allow use `​if​ ​archinstall​.​arguments​.​get​(​'silent'​) ​is​ ​False​:` ask_user_questions() will be run even if the config is passed

**Comment by Mattias-** [comment]
> We actually pass silent using `archinstall --silent` which sets `silent` to `true`, if we allow use `​if​ ​archinstall​.​arguments​.​get​(​'silent'​) ​is​ ​False​:` ask_user_questions() will be run even if the config is passed

I see but `get` defaults to None if unset and
```
>>> None is False
False
```

**Comment by l4zy0n3** [comment]
> We actually pass silent using `archinstall --silent` which sets `silent` to `true`, if we allow use `​if​ ​archinstall​.​arguments​.​get​(​'silent'​) ​is​ ​False​:` ask_user_questions() will be run even if the config is passed

This seems good, we could support it, but it will require changes in ask_user_questions to not show the prompts if respective keys are loaded from config, I'm actually planning to keep only one function for loading config and asking user questions, and merge the workarounds we have right now

**Comment by Mattias-** [comment]
> it will require changes in ask_user_questions to not show the prompts if respective keys are loaded from config
Looks like that's already implemented? A bunch of checks like https://github.com/archlinux/archinstall/blob/a4033a7d3a94916f2b4972d212f9d0069fca39cd/examples/guided.py#L36
in `ask_user_questions`

**Comment by Mattias-** [comment]
True! Thanks for your input!

**Comment by Torxed** [comment]
> > We actually pass silent using `archinstall --silent` which sets `silent` to `true`, if we allow use `​if​ ​archinstall​.​arguments​.​get​(​'silent'​) ​is​ ​False​:` ask_user_questions() will be run even if the config is passed
> 
> This seems good, we could support it, but it will require changes in ask_user_questions to not show the prompts if respective keys are loaded from config, I'm actually planning to keep only one function for loading config and asking user questions, and merge the workarounds we have right now

This is what I tried explaining earlier that I wished `--config` did hehe.
Because `ask_user_questions()` is silent by default if all flags are met.
So if `--config` populated `arguments`, and only populated them.

`ask_user_questions` wouldn't ask a single question.
This is why I felt the removal of the "argparse" magic and dividing up `--config` in it's own logic and never call `ask_user_questions` felt a bit off.. I never had a good example but this issue demonstrates it pretty well.

I think we can tweak `--config` to populate `arguments` only, after which the normal work-flow can continue and the user should never have to answer any questions except those missing in config. I really love `--config` btw, it's a huge improvement, but I think we can tweak it further!

**Comment by l4zy0n3** [comment]
> > > We actually pass silent using `archinstall --silent` which sets `silent` to `true`, if we allow use `​if​ ​archinstall​.​arguments​.​get​(​'silent'​) ​is​ ​False​:` ask_user_questions() will be run even if the config is passed
> > 
> > 
> > This seems good, we could support it, but it will require changes in ask_user_questions to not show the prompts if respective keys are loaded from config, I'm actually planning to keep only one function for loading config and asking user questions, and merge the workarounds we have right now
> 
> This is what I tried explaining earlier that I wished `--config` did hehe.
> Because `ask_user_questions()` is silent by default if all flags are met.
> So if `--config` populated `arguments`, and only populated them.
> 
> `ask_user_questions` wouldn't ask a single question.
> This is why I felt the removal of the "argparse" magic and dividing up `--config` in it's own logic and never call `ask_user_questions` felt a bit off.. I never had a good example but this issue demonstrates it pretty well.
> 
> I think we can tweak `--config` to populate `arguments` only, after which the normal work-flow can continue and the user should never have to answer any questions except those missing in config. I really love `--config` btw, it's a huge improvement, but I think we can tweak it further!

Ideally it should only populate the arguments, We need to fix this. 👍🏽

**Comment by Torxed** [comment]
> Ideally it should only populate the arguments, We need to fix this. 👍🏽

I can get right on it after I've wrapped my head around the partitioner.
Will take a few more days tho.

**Comment by Torxed** [comment]
I think we've fixed most of these issues.
I'll run a few more tests today and tomorrow and if something doesn't pop up I will consider this issue closed :)
In time for the next release.

**Comment by Torxed** [comment]
Sorry for the delay in feedback, I believe this has been fixed for a while now in `master` and I've verified with the latest version.
I'll go ahead and close this issue as it's a blocker for the release of v2.4.0 : )

![screenshot_bug](https://user-images.githubusercontent.com/861439/142448751-2bbd3d57-f903-46c1-b710-8b07264354bd.jpg)

**Comment by Mattias-** [comment]
Wow that's great, thanks for all the hard work. I'll make sure to try it out
