### ISSUE TITLE
Add more info to Formatting in 5…

### ISSUE THREAD

**Issue by jtagcat** [archlinux/archinstall#560]
It currently shows just `BlockDevice(/dev/sda)`. Provide the same info as you do in disk selection (size).

**Comment by Torxed** [comment]
Will do! We currently have a limitation of window size on some machine, fitting all the information of the guided installer is currently very hard and we're already on the edge of things. So we'll have to do tradeoffs I think. Perhaps only show "damaging information" such as disk, network related information and profiles chosen.
There's really no need to see "we will set a root password of ***** for you" kind of stuff.

**Comment by Torxed** [comment]
This is now done, I forgot to mark this issue when creating the PR way way back.
But it now shows the total size of the drive, and some other information.

![screenshot](https://user-images.githubusercontent.com/861439/141087514-dd542a4d-1989-46ba-a456-2112fe691564.jpg)
