### ISSUE TITLE
The installation media should not even be offered as a choice to install Arch Linux to

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#563]
I saw someone hit this last night (Eastern time) in the help channel on Discord.

Scenario:
* Arch ISO burned to USB drive mounted on /dev/sda
* /dev/sda chosen as target, and user chose to format /dev/sda and install there thinking it was their hard drive (their real drive was an NVMe SSD, on nvme0n1 - they didn't notice the sizes)
* parted mklabel command failed due to mounted partitions
* Manual unmount of /dev/sda partitions failed due to it being the Arch ISO

I propose that, if we can somehow detect the installer is running off of a block device, not listing that device as an option in guided.

**Comment by Torxed** [comment]
We should be able to map `/dev/loop0` (when ISO is used) or `/dev/sda` (if USB is used) against the logical device and filter the real device out. I believe `archinstall.Partition('/run/archiso/airrootfs').real_device` will turn out to be `/dev/sda` in this case, in which case we can filter out `/dev/sda` as it maps against the airrootfs device.

Pesudo code but `.real_device` exists in the library and could potentially be utilized.
