### ISSUE TITLE
check_mirror_reachable is slow and adds delay to startup

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#567]
The function `archinstall.check_mirror_reachable` adds a unnecessary long delay to startup of running `archinstall`:
https://github.com/archlinux/archinstall/blob/d3dddcf425238a70cb4811c50aa8f0d845f8cc39/archinstall/lib/networking.py#L31-L37

If the mirrors aren't reachable, it will immediately timeout and the function is blistering fast.
However, if mirrors are reachable, it will proceed to download the package definitions. This is perhaps harder to solve but maybe we can spawn a thread with this and if we detect output and no exit code is given - we could assume that it's grabbing package definitions and return `True` a bit quicker.

This is really only an issue during testing, but running the command over and over to test new features and in my case partitioning.. it gets a bit tedious to wait ~5-10 seconds on a slow connection for this to finish.

**Comment by dylanmtaylor** [comment]
I disagree with changing this fundamentally as it's necessary to make sure mirrors are reachable before doing a network installation and a simple internet test won't suffice due to things like corporate or government firewalls that could block access to mirrors. The one thing we might want to do is print an info message "Testing connectivity to the Arch Linux mirrors..." so users do not think it is frozen.

**Comment by dylanmtaylor** [comment]
Also, detecting output is not sufficient. We want to rely on the error code to show us that there is nothing wrong with it. Output could be a pile of errors, and we might not detect that. Especially if it changes from say 5 -> 6.

**Comment by Torxed** [comment]
> I disagree with changing this fundamentally as it's necessary to make sure mirrors are reachable before doing a network installation and a simple internet test won't suffice due to things like corporate or government firewalls that could block access to mirrors. The one thing we might want to do is print an info message "Testing connectivity to the Arch Linux mirrors..." so users do not think it is frozen.

If we can even get 1KB from the mirrors, they are by definition reachable. I get what you're saying tho, if the last mirror is a custom one we have to verify all of them. Having a smarter way of detecting reach-ability is desirable either way.

The issue I'm having with this is that a database (`extra` for instance) is quite large, and it takes time to download the entirety of the file. We technically only need to verify that we can reach the database-file, and perform a `HEAD` on it, we don't need to (at this stage) get the entire database locally in order to verify connectivity against a mirror.

A warning message is fine, that helps users.
Speeding this process up helps developers.

**Comment by dylanmtaylor** [comment]
In my experience, this pacman -Sy fetch usually takes < 3 seconds when I run in a virtual machine, and it'd take quite a lot longer than that to rewrite this logic. Not sure how you feel about that time trade-off.

**Comment by Torxed** [comment]
I'll consider it to be annoying for now, but re-writing it might add too much complexity and the possibility to miss something causing packages to break/not to be found later on.. So I'll close it for now :)
