### ISSUE TITLE
Proposal: don't export credentials with config as they are unusable

### ISSUE THREAD

**Issue by l4zy0n3** [archlinux/archinstall#571]
```json
"superusers": {
  "devel": {
     "!password": "*****"  
  }
}
```
these credentials shouldn't be exported?

**Comment by Torxed** [comment]
Initially it existed to present the user with the information that "Yes, these accounts will be created."
These can perhaps be omitted or we could simply export them into `/var/log/credentials.json` and `chmod 600` on the file.

**Comment by svartkanin** [comment]
@Torxed this is supported and can be exported/imported so I think we can close this :)

**Comment by svartkanin** [comment]
@Torxed this can be closed
