### ISSUE TITLE
No system found

### ISSUE THREAD

**Issue by Roknauta** [archlinux/archinstall#581]
After install and no errors, i rebooted the system and nothing happens. The system not found. This is my only boot entry.
![WhatsApp Image 2021-06-15 at 6 03 27 PM](https://user-images.githubusercontent.com/7780234/122123371-49e70500-ce04-11eb-9979-077ce9233366.jpeg)

**Comment by Torxed** [comment]
I assume you're using the latest ISO?
The older ISO had a "fix" which was that it wouldn't write any EFI variables, which could cause this.

If that's not the case, then I'd like to see your `/boot` partition, and/or your log `/var/log/archinstall/install.log`

**Comment by Roknauta** [comment]
> I assume you're using the latest ISO?
> The older ISO had a "fix" which was that it wouldn't write any EFI variables, which could cause this.
> 
> If that's not the case, then I'd like to see your `/boot` partition, and/or your log `/var/log/archinstall/install.log`

Yes, latest ISO. 

How can i get these information without system ?

**Comment by Torxed** [comment]
> > I assume you're using the latest ISO?
> > The older ISO had a "fix" which was that it wouldn't write any EFI variables, which could cause this.
> > If that's not the case, then I'd like to see your `/boot` partition, and/or your log `/var/log/archinstall/install.log`
> 
> Yes, latest ISO.
> 
> How can i get these information without system ?

You would need to still be in the live ISO right after it claimed it finished.
Or if you use a live-cd to mount your installed system it would be in `/var/log/archinstall/install.log` both on the ISO during installation and copied to the installed system.

Easiest way I know is to ssh/scp the file out to another machine.

**Comment by Roknauta** [comment]
> > > I assume you're using the latest ISO?
> > > The older ISO had a "fix" which was that it wouldn't write any EFI variables, which could cause this.
> > > If that's not the case, then I'd like to see your `/boot` partition, and/or your log `/var/log/archinstall/install.log`
> > 
> > 
> > Yes, latest ISO.
> > How can i get these information without system ?
> 
> You would need to still be in the live ISO right after it claimed it finished.
> Or if you use a live-cd to mount your installed system it would be in `/var/log/archinstall/install.log` both on the ISO during installation and copied to the installed system.
> 
> Easiest way I know is to ssh/scp the file out to another machine.

Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoint': '/run/archiso/airootfs', 'type': 'loop', 'size': '638.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': 'Arquivos', 'uuid': '98A0AC18A0ABFB40', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '931.5G'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '14.4G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'ARCH_202106', 'uuid': '94F2-E1BD', 'fsavail': '13.7G', 'fsuse%': '5%', 'mountpoint': '/run/archiso/bootmnt', 'type': 'part', 'size': '14.4G'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '232.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '3CF7-BEFD', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '512M'}, {'name': 'nvme0n1p2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '1c52ecbe-8667-440a-88f2-ed13d926a2e8', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '232.4G'}]}]}
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoint': '/run/archiso/airootfs', 'type': 'loop', 'size': '638.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': 'Arquivos', 'uuid': '98A0AC18A0ABFB40', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '931.5G'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '14.4G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'ARCH_202106', 'uuid': '94F2-E1BD', 'fsavail': '13.7G', 'fsuse%': '5%', 'mountpoint': '/run/archiso/bootmnt', 'type': 'part', 'size': '14.4G'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '232.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '3CF7-BEFD', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '512M'}, {'name': 'nvme0n1p2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '1c52ecbe-8667-440a-88f2-ed13d926a2e8', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '232.4G'}]}]}
You can skip selecting a drive and partitioning and use whatever drive-setup is mounted at /mnt (experimental)
BlockDevice(/dev/nvme0n1) contains the following partitions:
 Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat)
 Partition(path=/dev/nvme0n1p2, size=232.4G, fs=ext4)
Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
-- Guided template chosen (with below config) --
{
    "!root-password": "******",
    "audio": "pulseaudio",
    "bootloader": "grub-install",
    "filesystem": "ext4",
    "harddrive": {
        "model": "Samsung SSD 970 EVO Plus 250GB",
        "path": "/dev/nvme0n1",
        "size": "232.9G"
    },
    "hostname": "doug-pc",
    "kernels": [
        "linux"
    ],
    "keyboard-language": "br-abnt2",
    "mirror-region": {},
    "nic": {
        "NetworkManager": true,
        "nic": "Use NetworkManager to control and manage your internet connection"
    },
    "ntp": true,
    "packages": [],
    "profile": {
        "path": "/usr/lib/python3.9/site-packages/archinstall/profiles/desktop.py"
    },
    "script": "guided",
    "superusers": {
        "douglas": {
            "!password": "******"
        }
    },
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "America/Sao_Paulo",
    "users": {}
}
Wiping BlockDevice(/dev/nvme0n1) by using partition format 1
Using and formatting the entire BlockDevice(/dev/nvme0n1).
Adding partition to BlockDevice(/dev/nvme0n1)
Adding partition to BlockDevice(/dev/nvme0n1)
Set the root partition Partition(path=/dev/nvme0n1p2, size=232.4G, fs=ext4) to use filesystem ext4.
Partition Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) is a boot partition and has content inside.
Did not format Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) because .safe_to_format() returned False or .allow_formatting was False.
Formatting /dev/nvme0n1p2 -> ext4
Mounting Partition(path=/dev/nvme0n1p2, size=232.4G, fs=ext4, rel_mountpoint=/) to /mnt
Mounting Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) to /mnt/boot
Waiting for automatic mirror selection (reflector) to complete.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'intel-ucode']
Installing packages: ('grub',)
Adding bootloader grub-install to Partition(path=/dev/nvme0n1p1, size=-1, fs=vfat, mounted=/mnt/boot)
Installing packages: ('grub',)
Installing packages: ('efibootmgr',)
Installing packages: ('networkmanager',)
Enabling service NetworkManager.service
This audio server will be used: pulseaudio
Installing packages: ('pulseaudio',)
Installing network profile Profile(desktop)
Installing packages: ['nano', 'vim', 'openssh', 'htop', 'wget', 'iwd', 'wireless_tools', 'wpa_supplicant', 'smartmontools', 'xdg-utils']
Installing network profile Profile(kde)
Installing network profile Profile(xorg)
Installing packages: ('xorg-server xorg-xinit nvidia',)
Installing packages: ['plasma-meta', 'konsole', 'kate', 'dolphin', 'sddm', 'plasma-wayland-session', 'egl-wayland']
Enabling service sddm
Creating user douglas
Setting password for douglas
Enabling sudo permissions for douglas.
Installing and activating NTP.
Installing packages: ('ntp',)
Enabling service ntpd
Keyboard language for this installation is now set to: br-abnt2
For post-installation tips, see https://wiki.archlinux.org/index.php/Installation_guide#Post-installation
Updating /mnt/etc/fstab
Installation completed without any errors. You may now reboot.
Disk states after installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoint': '/run/archiso/airootfs', 'type': 'loop', 'size': '638.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sda1', 'fstype': 'ntfs', 'fsver': None, 'label': 'Arquivos', 'uuid': '98A0AC18A0ABFB40', 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'part', 'size': '931.5G'}]}, {'name': 'sdb', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '14.4G', 'children': [{'name': 'sdb1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': 'ARCH_202106', 'uuid': '94F2-E1BD', 'fsavail': '13.7G', 'fsuse%': '5%', 'mountpoint': '/run/archiso/bootmnt', 'type': 'part', 'size': '14.4G'}]}, {'name': 'nvme0n1', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoint': None, 'type': 'disk', 'size': '232.9G', 'children': [{'name': 'nvme0n1p1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '3CF7-BEFD', 'fsavail': '446.6M', 'fsuse%': '13%', 'mountpoint': '/mnt/boot', 'type': 'part', 'size': '512M'}, {'name': 'nvme0n1p2', 'fstype': 'ext4', 'fsver': '1.0', 'label': None, 'uuid': '7e7012fe-5346-4921-b832-9c7e28843c9d', 'fsavail': '210.5G', 'fsuse%': '2%', 'mountpoint': '/mnt', 'type': 'part', 'size': '232.4G'}]}]}

**Comment by Roknauta** [comment]
Finally, i solved: 

Before start i delete all partitions using cfdisk.
