### ISSUE TITLE
If nvidia-dkms is installed, headers that match the selected kernels should also be installed

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#585]
It was reported on Discord that with Linux Zen the proper headers were not getting installed.

**Comment by matteoturini** [comment]
this happened to me, to workaround i added to the additional packages linux-zen-headers.

**Comment by Torxed** [comment]
> this happened to me, to workaround i added to the additional packages linux-zen-headers.

Just back from vacation, so we only need to add `linux-zen-headers` to additional packages if `nvidia-dkms` is installed?
If so this should be an easy fix.

**Comment by matteoturini** [comment]
> > this happened to me, to workaround i added to the additional packages linux-zen-headers.
> 
> Just back from vacation, so we only need to add `linux-zen-headers` to additional packages if `nvidia-dkms` is installed?
> If so this should be an easy fix.

No! Add the headers matching the kernel. If linux-zen is installed, install linux-zen-headers. If linux is installed, install linux-headers. Etc.

**Comment by Torxed** [comment]
This should now be fixed in ffc43bc. There's currently also a bug where the proper `linux-<insert version` isn't properly added to the boot config, which is up next on the fixing list. But this should be testable now. I'm closing this issue and I'd be happy to re-open it if this didn't solve it : ) *(Just cleaning up among the issues)*

**Comment by Galcian79** [comment]
Even broadcom-wl needs dkms if linux-zen is used. Best practice would be to give an option to install headers beside kernels. So:
1) linux-zen
2) linux-zen-headers
3) linux-lts
4) linux-lts-headers
5) linux
6) linux-hardened
