### ISSUE TITLE
Crash when password is or has a quotation mark.

### ISSUE THREAD

**Issue by ledufff** [archlinux/archinstall#587]
Hi,
Hopefully this bug is easy to reproduce.   You just have to set a quotation mark (") as password.

**Comment by ledufff** [comment]
[install.log](https://github.com/archlinux/archinstall/files/6689205/install.log)

**Comment by Torxed** [comment]
I'll have a look at it, probably an issue in the way we escape strings.

**Comment by jonas-w** [comment]
Yes exactly, i have had this error a couple of times when using an uneven amount of quotation marks.
Is this still looked at?

**Comment by Torxed** [comment]
Forgot to tag it for a release, Ill get on it!

**Comment by jonas-w** [comment]
Thanks!

    Just fyi:
    When using a password like: 1234!"asdf"
    the password comes out as 1234!
    and when using a password with uneven amount for example 1234!"asdf. The script crashes!

**Comment by Torxed** [comment]
The patch in X now produces:
```
/usr/bin/arch-chroot /mnt/archinstall sh -c 'echo '"'"'anton:iam"atest!password'"'"'"'"'"'"'"'"'hehe'"'"' | chpasswd'
```
from
```
user = "anton"
password = 'iam"atest!password\'hehe'
```
Relying more on `shlex.join()` instead of manually trying to build complicated nested quoted strings.
