### ISSUE TITLE
lsblk shows that the boot partition is 512M, and df shows only 93M.

### ISSUE THREAD

**Issue by harvies** [archlinux/archinstall#591]
![image](https://user-images.githubusercontent.com/16585330/124374987-15af8780-dcd2-11eb-91d9-a8bf283669f3.png)

**Comment by Torxed** [comment]
That makes little to no sense to me. Anyone else have an idea of why two tools show different values?

The 93M sounds like the ~100M that Windows sets up. But then I don't get why lsblk would show a different amount. Did you run partprobe? Reboot? You're clearly not running in an ISO, so I'm assuming this is after you installed your system and configured it?

**Comment by harvies** [comment]
> That makes little to no sense to me. Anyone else have an idea of why two tools show different values?
> 
> The 93M sounds like the ~100M that Windows sets up. But then I don't get why lsblk would show a different amount. Did you run partprobe? Reboot? You're clearly not running in an ISO, so I'm assuming this is after you installed your system and configured it?

The disk sdb is partitioned and mounted by archinstall.

**Comment by Torxed** [comment]
> The disk sdb is partitioned and mounted by archinstall.

But that terminal doesn't look like stock ISO `zsh` shell.
This is why I wondered a little bit more about the hardware and method of usage.

**Comment by harvies** [comment]
> > The disk sdb is partitioned and mounted by archinstall.
> 
> But that terminal doesn't look like stock ISO `zsh` shell.
> This is why I wondered a little bit more about the hardware and method of usage.

I used archinstall to install the system and the gnome desktop, and then went to the system to prompt that the boot partition was insufficient and found the problem. I used oh-my-zsh.

**Comment by stephen-trippett** [comment]
@Torxed I'm getting the same error while running archinstall from the archiso. During the install process these errors show up:

```
error: Partition /mnt/boot too full: 9574 blocks needed, 4647 blocks free
error: not enough free disk space
error: failed to commit transactions (not enough free disk space)
==> ERROR: Failed to install packages to new root
Could not strap in packages: 256
Adding bootloader systemd-bootctl to Partition(path=/dev/nvme0n1p1, size=-1, fs=vfat, mounted=/mnt/boot)
```

They appear right after the step where it installs other system packages like `pacman` and `sudo`. Despite the errors, the installer continues and completes "successfully". These errors are only visible for a few seconds before they scroll off the screen. After it finishes, I ran `efibootmgr`, and there was no systemd boot loader for the new arch install.

I've tried numerous different configs (btrfs vs ext4, encrypted vs no encryption, desktop vs minimal) but always get the same error with the boot partition. I also manually removed all partitions from the disk before running archinstall, but still no luck.

Similar to @harvies , when I run `df -h` the size of nvme0n1p1 is 96M (used 92M), but `lsblk` says 512M.

Were you ever able to find an explanation to why they would show different sizes?

Is there a workaround? I haven't tried manually creating the partitions before running the install script and selecting "use /mnt". I'll try that next, but something funky is going on.

**Comment by Torxed** [comment]
> @Torxed I'm getting the same error while running archinstall from the archiso. During the install process these errors show up:
> 
> ```
> error: Partition /mnt/boot too full: 9574 blocks needed, 4647 blocks free
> error: not enough free disk space
> error: failed to commit transactions (not enough free disk space)
> ==> ERROR: Failed to install packages to new root
> Could not strap in packages: 256
> Adding bootloader systemd-bootctl to Partition(path=/dev/nvme0n1p1, size=-1, fs=vfat, mounted=/mnt/boot)
> ```
> 
> They appear right after the step where it installs other system packages like `pacman` and `sudo`. Despite the errors, the installer continues and completes "successfully". These errors are only visible for a few seconds before they scroll off the screen. After it finishes, I ran `efibootmgr`, and there was no systemd boot loader for the new arch install.
> 
> I've tried numerous different configs (btrfs vs ext4, encrypted vs no encryption, desktop vs minimal) but always get the same error with the boot partition. I also manually removed all partitions from the disk before running archinstall, but still no luck.
> 
> Similar to @harvies , when I run `df -h` the size of nvme0n1p1 is 96M (used 92M), but `lsblk` says 512M.
> 
> Were you ever able to find an explanation to why they would show different sizes?
> 
> Is there a workaround? I haven't tried manually creating the partitions before running the install script and selecting "use /mnt". I'll try that next, but something funky is going on.

I've addressed the silent packstrap issue by raising an exception, so if there's a network error during downloading of packages or disk running out of space, it should abort and not continue. At least that way people won't get the false perception that everything went great.

Regarding the disk issue, I still don't know why there's a discrepancy between `df` and `lsblk` in the matter. I do know that Windows creates a way to small boot sector to support anything other than Windows Boot loader and systemd-boot's main binary, but not the fallback vmlinuz kernel.

The only workaround to this is to expand the boot partition first, or wipe the drive completely to allow for a larger boot sector.
Something the new partitioning guide in the upcoming archinstall will allow you to do (wipe that is, not re-size, as it's way to complicated and risky for a installer at this stage)

**Comment by george-angel** [comment]
Just want to add that I have the same issue, which is preventing me from doing a firmware update:

```
/boot does not have sufficient space, required 33.6 MB, got 8.6 MB
```

```
$ lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINTS
sda           8:0    1     0B  0 disk
zram0       253:0    0     8G  0 disk  [SWAP]
nvme0n1     259:0    0 476.9G  0 disk
├─nvme0n1p1 259:1    0   512M  0 part  /boot
└─nvme0n1p2 259:2    0 476.4G  0 part
  └─luksdev 254:0    0 476.4G  0 crypt /var/lib/docker/btrfs
                                       /
```

```
$ df -khT /boot/
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/nvme0n1p1 vfat   96M   88M  8.2M  92% /boot
```

Only relevant looking lines from install.log:

```
Partition Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) is a boot partition and has content inside.
Did not format Partition(path=/dev/nvme0n1p1, size=512M, fs=vfat, rel_mountpoint=/boot) because .safe_to_format() returned False or .allow_formatting was False.
```

**Comment by Torxed** [comment]
> As a workaround, would something like this work https://unix.stackexchange.com/a/622221 ?
> Boot via live USB - and then resize the filesystem?

That could work. But I think I'll do a size check on `/boot` and raise an exception instructing people to re-size it prior to running archinstall. It will put less stress on archinstall to not mess up `/boot` when trying to dual-boot. And the manual or instructions can be too use tools like that.

For now I'll focus on wiping the disk when people want to, and telling people to handle cases where other OS:es have done something that won't support more stuff. And I'll re-visit adding in magic to just deal with other OS:es hehe

**Comment by george-angel** [comment]
Ok, I have tried following: https://superuser.com/a/1289122

But that hasn't worked for me. Now I cannot boot, getting the following error:

```
Your device/PC needs to be repaired

File: \\Windows\system32\winload.efi
Error code: 0xc000000e
```

As far as I can tell I recreated the partition, I can see correct flags on it (efi, boot), fat32, I copied all the files back. The UUID didn't actually change(?) so I didn't update fstab. Start and end sectors values are the same as before.

**Comment by Torxed** [comment]
The `PARTUUID` might have changed, or whatever equivalent Windows uses on their partitions to find their boot loader.

**Comment by george-angel** [comment]
Thanks @Torxed, I have managed to get a bit further by turning off UEFI only boot, selecting the disk the the boot menu. And startup failed at "Timed out waiting for device /dev/disk/by-uuid/38EE-E49C" - which was my old /boot.

Are you on libera.chat (I'm "george-angel" on there) or anywhere else, would you be able to help? Sorry, I appreciate this is a big ask. Thank you very much.

**Comment by svartkanin** [comment]
@Torxed this should probably be fixed already or now with pyparted
