### ISSUE TITLE
No such file or directory: /mnt/boot/loader/loader.conf

### ISSUE THREAD

**Issue by zJairO** [archlinux/archinstall#592]
When trying to install arch I get this error, previously I had installed arch without problems.

It happens when installing package 'efibootmgr'

Also want to say that installing grub, installation seems to be perfect ask for reboot, after that can't see the grub installed.

**Comment by Torxed** [comment]
Could you attach the `/var/log/archinstall/install.log` file?

**Comment by BuonHobo** [comment]
I was having this issue yesterday.
I solved it by doing this before running archinstall:
Mount the partition where I want to install arch to /mnt;
Mount the EFI system partition to /mnt/boot.
This made it work with systemd-boot, haven't tried it with grub.

**Comment by danielxvu** [comment]
I ran into this problem when wiping over a previous Fedora 34 installation using GRUB. It went away after: 

1. I manually partitioned and formatted the targeted drive 
2. and installed Arch Linux without archinstall using systemd-boot as the bootloader.

Running archinstall after these steps resulted in a successful installation. I suspect that zero-ing out the drive with DD before using `archinstall` would solve the problem as well.

**Comment by Torxed** [comment]
I'll close the issue once I've verified that the new partition logic zeroes out the device (upon request to do so).
As I want to help people avoid having to zero the disk first. Seems like there's been a "security flag" somewhere that blocked archinstall from properly wiping the disk. Hopefully next release addresses this and I'll close this one :)

**Comment by 0xc0000007b** [comment]
> > I ran into this problem when wiping over a previous Fedora 34 installation using GRUB. It went away after: 
> > 
> > 1. I manually partitioned and formatted the targeted drive 
> > 2. and installed Arch Linux without archinstall using systemd-boot as the bootloader.
> > 
> > Running archinstall after these steps resulted in a successful installation. I suspect that zero-ing out the drive with [dd](https://wiki.archlinux.org/title/Dd) before using archinstall would solve the problem as well i.e. `sudo dd if=/dev/zero of=/dev/sdx bs=16M conv=fsync`.
> 
> I've confirmed that zeroing out the drive works after reproducing the error by installing to a drive previously used by Windows. Therefore, this issue can be closed since it's not an actual problem with archinstall.

Same coming from macOS attempting to install using `/mnt`. Partition was ExFAT created by Disk Util under Monterey 12.1 gold. Reformatted partition with `mkfs.ext4` and did the zero wipe and blew right past this error, which I first experienced using the `archinstall-mbp` profile from @Redecorating in https://github.com/Redecorating/archinstall-mbp/issues/9.

**Comment by Torxed** [comment]
This has been fixed, and `pacstrap` will no longer silently continue on `Could not strap in packages: 256` which is the main culprit here. So I'll go ahead and close this one. The formatting and cleaning partition is usually just a fluke fix because the original issue was a network issue - which usually works the second time around.
