### ISSUE TITLE
Option to save config file for future use

### ISSUE THREAD

**Issue by liuhaowen478** [archlinux/archinstall#597]
It would be nice if, at the end of a guided install, archinstall can offer to save the configuration for future use. It could just save to some common place, or let users decide.

Or it would also be great if we can

```
archinstall --generate-config archinstall.config
```

and then it will go through the questions and write the generated config file to the path provided.

If there isn't already a similar WIP, and if you think this might be a desirable feature, I'm happy to work on it and open a PR.

**Comment by l4zy0n3** [comment]
the --dry-run flag does the same thing, it just needs to be documented

**Comment by liuhaowen478** [comment]
> config file is saved by default to `/var/log/archinstall/user_configuration.json`, you could add a flag to provide a path

That's what I was looking for. Thank you!

I think this should be documented somewhere but I'll close this now.
