### ISSUE TITLE
Hi, is it possible to add cutefish desktop to the desktop installation options?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [archlinux/archinstall#599]

**Comment by JakobDev** [comment]
There is already a [cutefish profile](https://github.com/archlinux/archinstall/blob/master/profiles/cutefish.py), but it's not in a released version yet. It also does not appear in the list, so have to type cutefish when you select a profile.

**Comment by Yakumo-Yukari** [comment]
> ‎已经有一‎[‎个可爱的鱼配置文件‎](https://github.com/archlinux/archinstall/blob/master/profiles/cutefish.py)‎，但它还没有在一个发布的版本。它也不出现在列表中，所以在选择配置文件时必须键入可爱的鱼。‎

Thank you for your answer
