### ISSUE TITLE
Tried installing - got an error and everything halted

### ISSUE THREAD

**Issue by arcolinuxz** [archlinux/archinstall#602]
I recorded every step of the way

https://youtu.be/aTUaysnMQEY

It is hidden so no one but the visitors here will see it.
It is best I show you rather than typing it all out.

Hope you understand.

**Comment by l4zy0n3** [comment]
I faced the same issue, workaround for now is creating a fresh table on the target drive, afaik this is happening only on virtualbox + BIOS.

**Comment by arcolinuxz** [comment]
Agreed was on virtualbox and BIOS

**Comment by l4zy0n3** [comment]
#588

**Comment by l4zy0n3** [comment]
> Agreed was on virtualbox and BIOS

Fixed in the latest commit on attached PR, verified on VirtualBox + BIOS
