### ISSUE TITLE
No such file or directory  :'/mnt/etc/fstab'

### ISSUE THREAD

**Issue by devewok** [archlinux/archinstall#607]
i'm trying to install on virtual box but i have that error.
![image](https://user-images.githubusercontent.com/87552609/126845001-d66e4feb-71f7-40b6-aaec-2b986bdabf8b.png)

**Comment by mark2185** [comment]
Stumbled upon the same problem, here's the config to reproduce:
```
{
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "filesystem": "btrfs",
    "harddrive": {
        "path" : "/dev/sda"
    },
    "!encryption-password": "123",
    "kernels": [
        "linux"
    ],
    "keyboard-language": "us",
    "mirror-region": {
        "Worldwide": {
            "https://mirror.rackspace.com/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "NetworkManager": true
    },
    "packages": [],
    "profile": "desktop",
    "superusers": {
        "username": {
            "!password": "rootroot"
        }
    },
    "timezone": "Europe/Stockholm",
    "users": {}
}
```

**Comment by godalming123-ipad** [comment]
I think this is because yo are using btrfs try using the ext4 filesystem also in my experience it doesnt work when you specify drive encryption other then that your config looks ok

**Comment by svartkanin** [comment]
@Torxed considering the changes to the partition logic and btrfs since this issue was raised maybe this can be considered as solved?

**Comment by Torxed** [comment]
This should be solved now yes, if it pops up we can create a new one.
@svartkanin thanks for finding all these fixed issues!

**Comment by svartkanin** [comment]
@Torxed no worries, just digging through the backlog to see what's still relevant :)
