### ISSUE TITLE
Can't automate i3 install with json config file

### ISSUE THREAD

**Issue by geowarin** [archlinux/archinstall#611]
Hello,

When I run `archinstall --config i3.json` with the following file:

```
{
    "audio": "pipewire",
    "bootloader": "systemd-bootctl",
    "custom-commands": [],
    "filesystem": "ext4",
    "gfx_driver": "VMware / VirtualBox (open-source)",
    "harddrive": {
        "path": "/dev/sda"
    },
    "hostname": "i3",
    "kernels": [
        "linux"
    ],
    "keyboard-language": "fr",
    "mirror-region": "France",
    "nic": {
        "NetworkManager": true
    },
    "ntp": true,
    "packages": [],
    "profile": "i3",
    "services": [],
    "superusers": {
        "geo": {
            "!password": "pass"
        }
    },
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "Europe/Paris",
    "users": {}
}

```

The installation fails (i3.py line 72).

This seems to be because we cannot pass a parameter to choose between i3-wm and i3-gaps when prompted.
https://github.com/archlinux/archinstall/blob/8489137b87/profiles/i3.py#L29

I think the script should either accept a parameter to skip the prompt or worst case scenario, default to i3-wm.

**Comment by Torxed** [comment]
Good catch! I'll have a good think about the best solution for this.
Just to avoid quick fixes that bites us later.

**Comment by geowarin** [comment]
Don't worry about the response time, the workaround is to explicitly install the packages with the minimal profile, so it's not a huge deal. Keep up the good work :)

**Comment by vincowl** [comment]
Facing the same trouble, I can't manage to apply @geowarin workaround since it doesn't enable the lightdm service. @Torxed is this issue an easy one to solve ? Thus I could submit a PR to fix this

**Comment by svartkanin** [comment]
@Torxed we can close this as it should be resolved with the new profile manger
