### ISSUE TITLE
Unable to set Canadian locale

### ISSUE THREAD

**Issue by GMJin** [archlinux/archinstall#617]
Tried installing with versions 2021.06.01-x86_64.iso and 2021.08.01-x86_64.iso on VirtualBox version 6.1.26 both ending with perl errors

**Comment by Torxed** [comment]
The perl errors aren't actual errors. They're warnings.
And the warnings is to be expected, as there's no fallback language added. The `LANGUAGE` variable is a fallback if the default `LANG` can not be found. As it's `en_US.UTF-8` it shouldn't be a problem and the warning can be ignored.

However, setting a different `LANG` should be supported and not [hardcoded](https://github.com/archlinux/archinstall/blob/master/archinstall/lib/installer.py#L414) to `en_US.UTF-8`.
We do support [configuring this](https://github.com/archlinux/archinstall/blob/master/examples/guided.py#L100-L102) during the installation, but in a forgetful moment I forgot I hardcoded it, and will fix in a bit. Perhaps I'll set `en_US.UTF-8` as a `LANGUAGE` fallback at the same time.

**Comment by svartkanin** [comment]
@Torxed this seems to be set correctly https://github.com/svartkanin/archinstall/blob/f37c7df78810d97dc84b19675be6fe0306ca08f8/archinstall/lib/installer.py#L466-L466 now
