### ISSUE TITLE
Cannot create partition from free space of HDD.

### ISSUE THREAD

**Issue by Jerrody** [archlinux/archinstall#618]
This is not part of Window's FS. So, any installer can use this space, but not Archinstall.

**Comment by Torxed** [comment]
It's a bug, archinstall did not recognize free space as available space and there for it didn't show up.
A workaround is to manually run `parted` and create a dummy partition and running `mkfs.ext4` on it and then running the installer.

The latest changes to the partitioner in `master` should solve this issue and should be on the next release :)

**Comment by svartkanin** [comment]
@Torxed This may be fixed by now considering the changes in partition logic :)
