### ISSUE TITLE
systemd-bootctl configs are not using kernel name

### ISSUE THREAD

**Issue by MiguelNdeCarvalho** [archlinux/archinstall#619]
Hey,

When selecting `systemd-bootctl` without "linux" the system won't boot. Because the 2 files generated by the script are calling the `linux` instead of the `linux-zen` and `linux-lts`.

Thanks,
MiguelNdeCarvalho

`config.json`:
```json
bootloader": "systemd-bootctl",
"kernels": [
        "linux-zen",
        "linux-lts"
    ]
```

`2021-08-25_22-54-19.conf`:
```
# Created by: archinstall
# Created on: 2021-08-25_22-54-19
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options cryptdevice=PARTUUID=9159d8b3-02ab-4441-b182-afffd27829fa:luksdev root=/dev/mapper/luksdev rw intel_pstate=no_hwp
```

`2021-08-26_00-35-21.conf`:
```
# Created by: archinstall
# Created on: 2021-08-26_00-35-21
title Arch Linux
linux /vmlinuz-linux
initrd /initramfs-linux.img
options cryptdevice=PARTUUID=90a801f1-cc11-4329-aab7-babb63109ef2:luksdev root=/dev/mapper/luksdev rw intel_pstate=no_hwp 
```

`loader.conf`:
```
timeout 3
#console-mode keep
default 2021-08-26_00-35-21
```

**Comment by Torxed** [comment]
This should now be fixed in `master` by iterating kernels and creating a config per kernel: https://github.com/archlinux/archinstall/blob/b8808491937a6140c9b4df00b4f27ef0405344a4/archinstall/lib/installer.py#L508-L510

*As a side note, I do not know if GRUB handles these options. But I'm sure `grub-mkconfig` does this.*

**Comment by Torxed** [comment]
Fixed and will be included in the upcoming release!

**Comment by MiguelNdeCarvalho** [comment]
Nice and thanks @olekthunder
