### ISSUE TITLE
Installing to already partitioned disk gets stuck asking for next partition to handle

### ISSUE THREAD

**Issue by andreaippo** [archlinux/archinstall#621]
My disk layout
p1 EFI
p4 swap
p5 opensuse
p6 opensuse home

I create p2, p3 for arch via the bootable drive prompt, and mkfs btrfs for / and ext4 for separate /home.

Then I launch archinstall and choose the option to use current partition table.

0 EFI
1 / for arch
2 /home for arch
3 swap
4 / for opensuse
5 /home for opensuse

I choose 0 to be mounted on /boot/efi
I choose 1 to be mounted on /
I choose 2 to be mounted on /home
Then I leave blank to stop here (will setup swap manually later, and don't want to touch opensuse partitions).

Well here the script is not accepting a blank, regardless of what it literally says.

I tried providing a blank, a tab, a ., entering also 3, 4, 5 without specifying mount points for them hoping that the script would detect that all partitions had been reviewed, and finally tried entering an index out of bounds, which also (legitimately) failed.

The problem is that entering a blank is not actually accepted.

This is with archlinux-2021.09.01-x86_64.iso.

Thank you in advance.

**Comment by KristerV** [comment]
Same problem for me. I'm trying to dual boot windows. Everything seems to work fine until

```
Select a partition by number that you want to set a mount-point for (leave blank when done):
```

just doesn't continue regardless of the fact that I leave it blank.

**Comment by Torxed** [comment]
@andreaippo could you supply us with a 

> Well here the script is not accepting a blank, regardless of what it literally says.

I'll look in to this, the new partitioning logic that's coming in the upcoming version should eradicate all these steps as the partitioning logic is re-worked. I've felt for a few months that the partitioning weren't quite right. So I'm going towards what people are more familiar with with other tools that's out there.

**Comment by svartkanin** [comment]
@Torxed this may be fixed as well now :)
