### ISSUE TITLE
instructions create a 20G image, not a 5G one

### ISSUE THREAD

**Issue by cdwijs** [archlinux/archinstall#624]
On this page [1], at the section "Without a Live ISO Image", it says the instructions will crate a 5GB image. I think this should have been 20GB, as this command yields a 20GB file:

# truncate -s 20G testimage.img

[1] https://github.com/archlinux/archinstall

**Comment by Torxed** [comment]
Correct, the command updated but the docs never did.
I've corrected it in this commit: https://github.com/archlinux/archinstall/commit/e3b6a46b74a1d464419c0e224b6281caf1d903ee
