### ISSUE TITLE
Partitioning problem

### ISSUE THREAD

**Issue by alm494** [archlinux/archinstall#627]
Hi, this tool near perfectly works on official arch install media. But due to issues with some of WiFi cards I created my own media on USB (using this tool!) and installed a very basic archlinux there, also included 'archinstall' and 'arch-install-scripts', 'parted' and 'fdisk'.
Archinstall works until disk partition reached and suspends on the step "BlockDevice(/dev/nvme0n1) contains the following partitions:"
Using lsblk I can see all devices perfectly:
nvme0n1      259.:0   0  476.9G  0 disk
It seems that some packages are missing for partitioning and they are not installed as dependencies.

**Comment by Torxed** [comment]
I know we've had issues with USB devices as the carrier, but I haven't tested it yet myself.
Could you upload the `/var/log/archinstall/install.log` and perhaps I could see where it goes wrong?

**Comment by alm494** [comment]
Aha, thank you, now I see that support filesystems support were not presented om my media:
BlockDevice(/dev/nvme0n1) contains the following partitions:
/usr/bin/mkfs.vfat does not exist.
 Partition(path=/dev/nvme0n1p1, size=100M, fs=vfat)
 Partition(path=/dev/nvme0n1p2, size=16M, fs=None) (Filesystem not supported)
 Partition(path=/dev/nvme0n1p3, size=476.3G, fs=ntfs) (Filesystem not supported)
 Partition(path=/dev/nvme0n1p4, size=540M, fs=ntfs) (Filesystem not supported)

**Comment by Torxed** [comment]
There should be dependencies in the package that should install these things.
I'm curious why `mkfs.vfat` doesn't exist.

**Comment by svartkanin** [comment]
@Torxed I suspect this can be closed :)
