### ISSUE TITLE
Install to an existing partition

### ISSUE THREAD

**Issue by colinramsay** [archlinux/archinstall#629]
I think this might just be a documentation issue but it's not clear to me if it's possible to install to an existing partition when using a config file. I'd like archinstall to wipe everything on my current Arch partition and reinstall it from a config file, but I have Ubuntu and Windows partitions on the same disk which I want to leave untouched.

**Comment by Torxed** [comment]
Currently I would say this is mostly unsupported, at least from a pure config standpoint.
The upcoming version does support this, and more fine tuned partitioning in general.
We've just got a few more bugs to work out and polish the workflow a little bit.

**Comment by Torxed** [comment]
The latest commits have added this functionality.
It's **HIGHLY** experimental at this stage, so I can't say for sure that data won't be wiped.

Before releasing this we'll do thorough testing, but if you wanna give it a go the latest `master` supports re-use of partitions using config via `--disk_layouts=<json file>`.

The format should be something like:
```json
{
	"/dev/sda" : {
		"wipe" : true,
		"partitions" : [
			{
				# Boot
				"type" : "primary",
				"start" : "1MiB",
				"size" : "513MiB",
				"boot" : true,
				"encrypted" : false,
				"format" : true,
				"mountpoint" : "/boot",
				"filesystem" : {
					"format" : "fat32"
				}
			},
			{
				# Root
				"type" : "primary",
				"start" : "513MiB",
				"encrypted" : false,
				"format" : true,
				"size" : "100%",
				"mountpoint" : "/",
				"filesystem" : {
					"format" : "btrfs"
				}
			}
		]
	},
	"/dev/sdb" : {
		"wipe" : true,
		"partitions" : [
			{
				# Home
				"type" : "primary",
				"encrypted" : false,
				"format" : true,
				"start" : "4MiB",
				"size" : "100%",
				"mountpoint" : "/home",
				"filesystem" : {
					"format" : "btrfs"
				}
			}
		]
	}
}
```

**Comment by svartkanin** [comment]
@Torxed this should be supported now as well :)
