### ISSUE TITLE
Keyboard doesn't work at encryption password stage

### ISSUE THREAD

**Issue by KristerV** [archlinux/archinstall#630]
Installed using archinstall today, but on reboot I couldn't enter the LUKS password. USB keyboard helped, ultimately changed `mkinitcpio.conf` to this order: `keyboard autodetect` (was switched before) and that fixed it.

**Comment by KristerV** [comment]
I have an Asus Zenbook UM425UA laptop.

Intrestingly I still have this problem sometimes, even with the switched mkinitcpio. Now I'm trying random stuff like putting `keymap` before autodetect, even though I don't know what it does.

**Comment by svartkanin** [comment]
I'll close this for the time being as it's an old issue, if we encounter this again we can reopen it
