### ISSUE TITLE
KeyError: 'harddrive'

### ISSUE THREAD

**Issue by deadlycatpurr** [archlinux/archinstall#631]
Trying the latest installer from git when encountered this error, probably caused by a misspelling?

> Hardware model detected: Intel Corporation NUC6CAYH; UEFI mode: True
Processor model detected: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
Memory statistics: 3250340 available out of 3861768 total installed
Virtualization detected: none; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation HD Graphics 500 (rev 0b)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': 'D27D-9366', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '512M'}, {'name': 'sda2', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': '7b284a76-4be8-4df8-a3cb-3eb2aa29ffd2', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '19.5G'}, {'name': 'sda3', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': 'd8c60f71-3afc-41ae-b97c-de4240f85128', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '911.5G'}]}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '119.2G', 'children': [{'name': 'sdb1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'part', 'size': '748M'}, {'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '3719-544C', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '84M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Hardware model detected: Intel Corporation NUC6CAYH; UEFI mode: True
Processor model detected: Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
Memory statistics: 3238224 available out of 3861768 total installed
Virtualization detected: none; is VM: False
Graphics devices detected: dict_keys(['Intel Corporation HD Graphics 500 (rev 0b)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '662.7M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '931.5G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': 'D27D-9366', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '512M'}, {'name': 'sda2', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': '7b284a76-4be8-4df8-a3cb-3eb2aa29ffd2', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '19.5G'}, {'name': 'sda3', 'fstype': 'btrfs', 'fsver': None, 'label': None, 'uuid': 'd8c60f71-3afc-41ae-b97c-de4240f85128', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '911.5G'}]}, {'name': 'sdb', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '119.2G', 'children': [{'name': 'sdb1', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202109', 'uuid': '2021-09-01-11-25-35-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'part', 'size': '748M'}, {'name': 'sdb2', 'fstype': 'vfat', 'fsver': 'FAT16', 'label': 'ARCHISO_EFI', 'uuid': '3719-544C', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '84M'}]}]}
Testing connectivity to the Arch Linux mirrors ...
Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
-- Guided template chosen (with below config) --
{
    "!root-password": "******",
    "audio": null,
    "bootloader": "systemd-bootctl",
    "desktop-environment": "budgie",
    "dry-run": false,
    "gfx_driver": "Intel (open-source)",
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "nuc",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {
        "Worldwide": {
            "http://mirror.rackspace.com/archlinux/$repo/os/$arch": true,
            "https://mirror.rackspace.com/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "NetworkManager": true,
        "nic": "Use NetworkManager (necessary to configure internet graphically in GNOME and KDE)"
    },
    "ntp": true,
    "packages": [],
    "profile": {
        "path": "/root/archinstall/archinstall/profiles/desktop.py"
    },
    "script": "guided",
    "superusers": {
        "aaa": {
            "!password": "******"
        }
    },
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "UTC",
    "users": {}
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MiB",
                "start": "1MiB",
                "type": "primary"
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs"
                },
                "format": true,
                "mountpoint": "/",
                "size": "20480MiB",
                "start": "513MiB",
                "type": "primary"
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "btrfs"
                },
                "format": true,
                "mountpoint": "/home",
                "size": "100%",
                "start": "20480MiB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
Kept partition format 1 for BlockDevice(/dev/sda, size=931.5GB, free_space=1031kB+729kB, bus_type=sata)
Creating a new partition labling on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=931.5GB, free_space=1000GB, bus_type=sata), 1MiB->513MiB
Formatting /dev/sda1 -> fat32
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sda, size=931.5GB, free_space=1031kB+1000GB, bus_type=sata), 513MiB->20480MiB
Formatting /dev/sda2 -> btrfs
Adding partition to BlockDevice(/dev/sda, size=931.5GB, free_space=1031kB+979GB, bus_type=sata), 20480MiB->100%
Formatting /dev/sda3 -> btrfs
Mounting Partition(path=/dev/sda2, size=19.5G, PARTUUID=28417b28-17f5-48ec-8fbe-75b842e12eba, fs=btrfs) to /mnt/archinstall/
Mounting Partition(path=/dev/sda1, size=512M, PARTUUID=df179c2b-0ce7-4cad-95d7-79c11dfb520b, fs=fat32) to /mnt/archinstall/boot
Mounting Partition(path=/dev/sda3, size=911.5G, PARTUUID=d07def57-3159-4dba-82bb-64cffee041ca, fs=btrfs) to /mnt/archinstall/home
Waiting for automatic mirror selection (reflector) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'btrfs-progs', 'btrfs-progs', 'intel-ucode']
'harddrive'

**Comment by deadlycatpurr** [comment]
![Uploading 1804B3FE-5C73-45E2-89FD-1457EB4B41DD.jpeg…]()

**Comment by deadlycatpurr** [comment]
![3328A0F9-F1FB-41C5-94B0-2E24043684A3](https://user-images.githubusercontent.com/45061322/132691542-4b72ff95-a218-49aa-a699-c94f607e935f.jpeg)

**Comment by colinramsay** [comment]
Are you passing a JSON config file? If I'm reading it right I think that if you use a `harddrives` key with the guided installer it needs to be a comma separated string rather than an array:

https://github.com/archlinux/archinstall/blob/e39e49ecc73c327fbb2161a080a7f9b4eacafb21/examples/guided.py#L31

So in your case:

```
"harddrives": "/dev/sda"

OR

"harddrives": "/dev/sda,/dev/sdb"
```

If you use a `harddrive` key then you need to use an object with a `path` value, for example:

```
"harddrive": {
    "path": "/dev/sda"
} 
```

**Comment by colinramsay** [comment]
Actually if you look at the line which is failing, it references the `harddrive` key but line 31 references `harddrives`. I'm not sure what has happened here but the inconsistency could be a bug.

**Comment by l4zy0n3** [comment]
The key used to be called harddrive as it supported only a particular drive, but now with multiple drive support the key has been renamed, this is an inconsistency issue, btw master is very unstable for now because of many breaking changes

**Comment by deadlycatpurr** [comment]
I am using the guided installer in master branch for this installation. I try to fix my self by changing `harddrive’ to ‘harddrives’ at the line that is causing the error, at first the installation finished without failing, but no bootable derive was detected in BIOS. I think i’ll just go back to v2.2.0 for now. Thanks for helping

**Comment by l4zy0n3** [comment]
> I am using the guided installer in master branch for this installation. I try to fix myself by changing `harddrive’ to ‘harddrives’ at the line that is causing the error, at first the installation finished without failing, but no bootable derive was detected in BIOS. I think i’ll just go back to v2.2.0 for now. Thanks for helping

That could be a related or a totally different issue. I'll try and investigate this.

**Comment by Torxed** [comment]
This is fixed now.
But remember that the partitioning is being re-worked, so some steps (like the manual more detailed formatting) still contains untested paths and might be broken.
But the guided (use the entire disk) appears to be working pretty well.
![jiff](https://user-images.githubusercontent.com/861439/133792249-861621d5-7608-4c29-ad60-e0099d995970.gif)
