### ISSUE TITLE
Cannot continue after selecting mountpoints in "keep existing partition layout"

### ISSUE THREAD

**Issue by ninoCan** [archlinux/archinstall#641]
I had already partitioned my drive using fdisk, so I wanted to skip the formatting phase of the guided installation. 

I selected the option 2 "Keep existing partition layout and select which one to use where" and selected the mountpoints for the partitions, but leaving the prompt blank as instructed does not exits the loop.

Also,  the linux-swap is not recognized as a valid filesystem.

**Comment by Torxed** [comment]
I'm assuming this issue was created by mistake, so I'll go ahead and close it :)

**Comment by ninoCan** [comment]
Sorry,  I'm writing from a tablet and I mistakenly submitted the issue before writing it. Please, consider for reopen

**Comment by Torxed** [comment]
No worries :) Do you happen to have a screenshot of the partitioning selection step? Where you entered which mount point to mount too? :)

**Comment by ninoCan** [comment]
The loop problem might arise in the guided.py at line 106.

I had 4 partitions (efi, swap, root and home) so my mountpoints where /mnt/efi, / and /home.

**Comment by Torxed** [comment]
Ah, you need two specific mountpoints and they are relative to `/mnt` so you don't need to write that.
You'll need `/` and you need `/boot` at the very least, `/efi` is equal to `/boot` in this instance.
Swap is currently not supported - but might work anyway *(I'm actually not sure tho)*

**Comment by ninoCan** [comment]
Ok, I see... Thanks anyway! I eventually went forward with the installation following the Archwiki. Would setting a configuration file have helped for my specific partition schema?

**Comment by Torxed** [comment]
> Would setting a configuration file have helped for my specific partition schema?

It could have helped, but you would have to mount your partitions manually first.
1) Mount your partitions under `/mnt`
2) Run `archinstall --config=<your config file here>`

That would have worked too :)
I'm closing this issue as it's more related to the input, altough we could have been more clear on this in the old partitioner.
