### ISSUE TITLE
Loop of "Selecting mirror region require a least one region to be given as an option."

### ISSUE THREAD

**Issue by miku86** [archlinux/archinstall#656]
Hey folks,

I try to use Arch Linux 32 Bit on an old machine with the ISO `archlinux32-2021.07.31-i686` from the [official site](https://archlinux32.org/download/).

1. I connect to my local Wifi with `iwctl`; I can ping `8.8.8.8` successfully.
1. I run `sudo archinstall`.
1. I get asked for a keyboard layout.

Whatever I type here, I get a loop of "Selecting mirror region require a least one region to be given as an option."

Examples:
- I input `4` for the `de` locale
- I input `26` for the `us` locale
- I input `?` for the help section and search for `de-` and input the number `1` for `de-latin1-nodeadkeys`
- I input `?` for the help section and search for `de-` and input `de-latin1-nodeadkeys` directly
- I input nothing (it should use the default `us`)

Each of these inputs lead to the same message loop.

---

The logs display `Disk states before installing: [...]` with all my devices correctly recognized.
Then `Selecting mirror region require a least one region to be given as an option.` starts showing up.

[This](https://github.com/archlinux/archinstall/blob/master/archinstall/lib/user_interaction.py#L926) is the code I'm talking about.

**Comment by Practicalbutterfly5** [comment]
Bump. Having same issue on i686 pc. I have even tried `pacman -S archinstall` to be on latest version.

**Comment by dylanmtaylor** [comment]
I'm guessing this bug is specific to 32-bit? I wasn't aware this is an issue - not sure of there's anything we're doing that wouldn't be completely the same as 64 bit other than UEFI stuff which tends to not be compatible on older systems.

**Comment by Practicalbutterfly5** [comment]
> I'm guessing this bug is specific to 32-bit? I wasn't aware this is an issue - not sure of there's anything we're doing that wouldn't be completely the same as 64 bit other than UEFI stuff which tends to not be compatible on older systems.

It might be because of 32 bit. As of now Im using the `python -m archinstall guided` version, which doesn't have this issue.

**Comment by Torxed** [comment]
> Bump. Having same issue on i686 pc. I have even tried `pacman -S archinstall` to be on latest version.

We haven't released a new version in quite some time, so this issue still remains. I will perform a few 32bit tests once I'm happy with the state of the code for the upcoming release.

**Comment by miku86** [comment]
Using `archlinux32-2022.01.15-i686-pre1.iso` with `archinstall 2.3.0-1.0` the exact same problem still exists.

**Comment by joao-neves95** [comment]
I was having this issue.

What I did was:
1. Update date/time in BIOS (don't know if this has any effect).
2. Run `pacman -Syy` before `archinstall`, (without `pacman -S archinstall`, I.e: just update pacman's databases, don't reinstall it).

**Comment by fixsee** [comment]
Updating my date and time in bios worked perfectly

**Comment by Torxed** [comment]
I'm closing this as it's mainly to do with incorrect configuration prior to running the installer.
However, in an effort to highlight when we couldn't retrieve the mirror list as expected, a log message should now be displayed detailing why we had to "loop" the mirror selection step.

Also the new menu system all together should make life easier :)
