### ISSUE TITLE
in xfce, it need network-manager-applet for NetworkManager

### ISSUE THREAD

**Issue by mumin16** [archlinux/archinstall#659]
in xfce, it need network-manager-applet for NetworkManager

**Comment by dylanmtaylor** [comment]
> I suggest implementing this under
> 
> https://github.com/archlinux/archinstall/blob/72849083e611486d4a3d141b30c7ad7f2b986cec/profiles/desktop.py#L11-L22

We likely don't want this installed for every desktop environment, as I'm not sure it's compatible with each. We also shouldn't install it if the user doesn't select network manager for managing network on their system

**Comment by dylanmtaylor** [comment]
@Torxed looks like this is already resolved in the XFCE profile and can be closed.

**Comment by Torxed** [comment]
Correct, closing!
