### ISSUE TITLE
[GRUB] No entry after succesfull installation

### ISSUE THREAD

**Issue by unixquuw** [archlinux/archinstall#669]
After being done with archinstall script, i rebooted into the boot menu. Ive booted into the grub and.. i didn't had the arch linux entry. I only keep getting: reboot into firmware interface.

Im using the newest ISO of arch linux, my architecture is x86_64.

**Comment by 144** [comment]
did you use "disk encryption"?

**Comment by 144** [comment]
> 
> 
> > did you use "disk encryption"?
> 
> Yessir, with hardened kernel.

Installer does not work properly with disk encryption, if you really want to use it with encryption currently either use master branch version of archinstall or configure GRUB yourself. It kinda sucks, i wait for it to be fixed in included archinstall myself.

**Comment by unixquuw** [comment]
> > > did you use "disk encryption"?
> > 
> > 
> > Yessir, with hardened kernel.
> 
> Installer does not work properly with disk encryption, if you really want to use it with encryption currently either use master branch version of archinstall or configure GRUB yourself. It kinda sucks, i wait for it to be fixed in included archinstall myself.

figured it out on my own, thanks for help anyways.
