### ISSUE TITLE
Errors on boot, fstab corrupted due to missing genfstab

### ISSUE THREAD

**Issue by OJFord** [archlinux/archinstall#673]
I don't really understand how I was able to boot and login at all, but I got to the login prompt after hitting enter a few times when presented with errors from trying to read `/etc/fstab`, and some error about unable to drop into a console as I went with the default of no root user.

Once I was logged in, I found `/etc/fstab` just contained a python traceback - `genfstab` not found. I installed `extra/arch-install-scripts` and `genfstab`bed it myself, and now seems fine.

Culprit here:
https://github.com/archlinux/archinstall/blob/ba725517fd290a60cd4e1ea570dbbf94a47ede05/archinstall/lib/installer.py#L187

Exit code is ignored and stderr written to the file.

(And also of course it needs to be installed so that it doesn't error anyway!)

**Comment by Torxed** [comment]
I think I got a permanent fix in for this one now.
Mainly the `SysCommand` should in v2.4.0 always raise an exception if the exit code isn't `0`.

But just to be safe, I also added a check for the exit code in the genfstab before the result.
