### ISSUE TITLE
Time, Timezone and Synchronize System Clock problem!

### ISSUE THREAD

**Issue by mumin16** [archlinux/archinstall#682]
i guess , it need "timedatectl set-ntp true" for synchronize

**Comment by Torxed** [comment]
We're using `ntpd` instead of `systemd-tymesyncd`, is there a preference to use `systemd-timesyncd` instead?
Relevant code: https://github.com/archlinux/archinstall/blob/85c97b56301e2131ee0606bcce7dffb4456bb580/archinstall/lib/installer.py#L251-L252
