### ISSUE TITLE
systemd-boot  and linux-zen are problem

### ISSUE THREAD

**Issue by mumin16** [archlinux/archinstall#683]
boot section is not modify for linux-zen.

**Comment by Torxed** [comment]
Did you test latest master or the official version on the official ISO? I believe this is a duplicate of #541

**Comment by mumin16** [comment]
/boot/loader/entries/2021-11-01_06-18-16.conf
linux /vmlinuz-linux
initrd /initramfs-linux.img
-> convert
linux /vmlinuz-linux-zen
initrd /initramfs-linux-zen.img

**Comment by Torxed** [comment]
This is fixed in `master` (https://github.com/archlinux/archinstall/pull/534) and will be released in the upcoming version :)
