### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'format' on master

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#689]
It seams that `Getting mount information at location` is trying to lookup `/dev/sda1` instead of `/`, or something else is wrong.

![image](https://user-images.githubusercontent.com/861439/140590899-27445591-8c8b-4a69-886a-4fc6ba21e042.png)

Virtualbox 6.1

**Comment by dylanmtaylor** [comment]
Could be related to #698

**Comment by dylanmtaylor** [comment]
This also occurs as no attribute 'encrypt' depending on whether or not you try to run with encryption. I think it's a race condition as it occurs (and doesn't) using the exact same options, seemingly at random.

![image](https://user-images.githubusercontent.com/277927/140848596-fab8f472-2a67-4a8b-8b8a-4f4a6e9424aa.png)

**Comment by Torxed** [comment]
Yea this one bugs me the most right now. Hard to debug as it's intermittent. But I'll add additional debug output and see if I can catch it

**Comment by wllacer** [comment]
It's also my showstopper right now. I think it only worked for me once.
For i could glean the partitions dictionary at filesystem.py is reset/deleted during the execution of the loop at line 78

**Comment by Torxed** [comment]
It's worth mentioning that Archinstall is single threaded and no concurrent operations.
So there has to be a step or check that's gone bad without raising an exception - allowing the code to continue.
Which is why this one becomes "tricky" to identity.

**Comment by bebetoalves** [comment]
Same here... If I put an encryption password it's works.
![20211110_190838](https://user-images.githubusercontent.com/13764984/141201996-072e8255-38bb-4dc2-ad2c-f40a23f53ea9.jpg)

**Comment by Torxed** [comment]
Ah, yea that should have been a .get() call, or better yet add it to the dict structure if one was supplied. My bad!

**Comment by eyestoflywith** [comment]
i'm still having this issue on master, open this.

**Comment by Torxed** [comment]
> this issue is still occuring for me on master, please reopen this.

Same code place? (stack trace file and line)

**Comment by eyestoflywith** [comment]
![IMG_0080](https://user-images.githubusercontent.com/96999044/150952513-96718d30-84a0-43c8-8e8e-6041128b58bf.jpeg)
i have no idea if it's the same place, and whatnot, i'm not technical enough, i apologise. i had the partUUID issue on stable, so i git clone'd the repo, and now it's showing me this, which looks like the same error the OP had. i'd appreciate all the help in advance!

**Comment by Torxed** [comment]
Looking in to it : )

**Comment by Torxed** [comment]
Well, I think I've found part of the problem: https://github.com/archlinux/archinstall/blob/26f9b681a45842d9a1ffd90e8b1397048b3c3645/archinstall/lib/disk/filesystem.py#L170

`add_partition()` is defined to no longer return the added `Partition()` object to: https://github.com/archlinux/archinstall/blob/26f9b681a45842d9a1ffd90e8b1397048b3c3645/archinstall/lib/disk/filesystem.py#L81

Although we still have: https://github.com/archlinux/archinstall/blob/26f9b681a45842d9a1ffd90e8b1397048b3c3645/archinstall/lib/disk/filesystem.py#L193

Clearly that doesn't trigger.
I'm cleaning up this code now.

**Comment by eyestoflywith** [comment]
will you be pushing this soonish? not to be a bother, i'd just like to be notified when i can have an arch setup haha!

**Comment by Torxed** [comment]
> will you be pushing a fix soonish? not to be a bother, i'd just like to be notified when i can have an arch setup haha!

Yepp, think I found it. Added a bunch of debugging and it appears as if `partprobe` was failing causing `add_partition` to not return the `Partition()` object.

Attaching a trace log, and it should be fixed by #896 and this PR should address this: https://github.com/archlinux/archinstall/pull/902

[archinstall fail 2.3.1 torxed-fix-deviceinstance 2.txt](https://github.com/archlinux/archinstall/files/7934062/archinstall.fail.2.3.1.torxed-fix-deviceinstance.2.txt)

**Comment by eyestoflywith** [comment]
alright, sweet! so if i boot into an iso and attempt archinstall now it should work, aye?

**Comment by Torxed** [comment]
> alright, sweet! so if i boot into an iso and attempt archinstall now it should work, aye?

If you follow these steps: https://github.com/archlinux/archinstall#using-a-live-iso-image
And you checkout `torxed-fix-deviceinstance` instead of `v2.3.1-rc1` yes.

Otherwise you'll have to wait for the PR to land in `master` and try the latest master.
Should be merged within the hour if everything looks good in testing (a community member is currently testing)

**Comment by eyestoflywith** [comment]
you're a legend, everything seems to be working at the moment, i'll edit the comment if i encounter further issues related to this! -- hopefully i won't.

**Comment by Torxed** [comment]
This was another issue after we fixed the first.
It's also fixed now, `git pull` and re-run should pass this issue : )

I'm not entirely sure if there's more issues behind this one as well, as I can't reproduce it locally (unsure why).

**Comment by eyestoflywith** [comment]
it had some issues with parted not being able to partition stuff after i git pull'd, but a reboot fixed it; i will soon have an install of arch on my system, thank you for the help and fixes, you're amazing once again!

**Comment by Torxed** [comment]
> it had some issues with parted not being able to partition stuff after i git pull'd, but a reboot fixed it; i will soon have an install of arch on my system, thank you for the help and fixes, you're amazing once again!

Glad it worked! And the pleasure is all mine!

**Comment by Torxed** [comment]
For reference to anyone who ends up here: it's now fixed in both `master` and `v2.3.1` *(which I'll try to release tomorrow)*.
