### ISSUE TITLE
Unecessary splitting and rejoining of sys_command output

### ISSUE THREAD

**Issue by vamega** [archlinux/archinstall#69]
I'm seeing a lot of splitting the output of `sys_command` using it's iterable, only to immediately rejoin it via `b''.join(sys_command(...))`. Is there a reason you've used this pattern so widely, since it seems to serve no purpose.

**Comment by Torxed** [comment]
As I mentioned in the other issue, the functionality is mainly derivative of legacy code:

```python
for line in sys_command("..."):
    ...
```

If there's a particular example you're referring to, like this [lspci](https://github.com/Torxed/archinstall/blob/66e495e994a459188a567d1410ba29dc3b2282ac/profiles/xorg.py#L40-L41) call. It's most likely because it can cause uncomplete lines when doing the `for line in` execution, because the command is so slow. So we need to wait for a unbuffered result before we can split by line : )

**Comment by vamega** [comment]
Maybe I'm missing something, but it doesn't seem like slow commands will have any effect on the output.
It seems like you call `os.waitpid` on the child before the `run` function returns, which means that it's really a fully blocking call (except when `kwargs` has `emulate` set to `True`, but in that situation you don't even seem to run the command).

There are also many places where you utilise `exit_code`, which would only be meaningfully be defined on a command that has fully executed (thus having a complete `trace_log`).

**Comment by Torxed** [comment]
> Maybe I'm missing something, but it doesn't seem like slow commands will have any effect on the output.
> It seems like you call `os.waitpid` on the child before the `run` function returns, which means that it's really a fully blocking call (except when `kwargs` has `emulate` set to `True`, but in that situation you don't even seem to run the command).
> 
> There are also many places where you utilise `exit_code`, which would only be meaningfully be defined on a command that has fully executed (thus having a complete `trace_log`).

Correct, to be more specific, if you thread and poll this.
This issue will arise :)

**Comment by vamega** [comment]
What are your thoughts on moving this to be explicitly blocking. If we need another non-blocking based execution command, we can have a different function that explicitly requires the caller to control the waiting on the other process?

Right now, it seems like this function both the implementation and usage is blocking (constructing a `sys_command` calls `run` and `run` calls `wait_pid`).

**Comment by Torxed** [comment]
I'm all for it! My only constraints are:

 * We need to be able to query for the exit code
 * We need to be able to write simple and complex command strings *(so I prefer `shell=True` and not splitting it into a list, but it's not a requirement)*
 * We need to get the raw output and store it for debugging *(currently it's stored in `~/.cache/archinstall/workers/<generated id>`)*

But it sounds like a reasonable change!

**Comment by Torxed** [comment]
`localectl` is now being used and locale's are set both for vconsole and X11.
We're trusting that `localectl` can handle the mapping between the two and we'll have to see how we deal with wayland in the future.

Any locale/layout that `localectl` supports, we now support.
We're not mapping locale language files for the listing any longer, and we're not using `loadkeys` or manual configuration of `/etc/vconsole.conf`, which means more robustness and any issues mentioned in this thread is considered resolved in the latest master branch. (next release will contain these changes).

Thank you to everyone reporting on on these issues!
