### ISSUE TITLE
[2.3.0-RC1] On uninitialized disk (VirtualBox), the selected partition table format 2 does not match that of BlockDevice

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#705]
![VirtualBox_arch_09_11_2021_10_32_13](https://user-images.githubusercontent.com/277927/140954414-a5c159af-74b5-4645-9b14-06712b163c21.png)

**Comment by dylanmtaylor** [comment]
I got this error twice in a row.

**Comment by Torxed** [comment]
I'm looking in to this error now, after running 20+ installations with no breakage surrounding `.format()` or `PARTUUID <partuuid> never showed up` I'm confident enough that it's good enough to merge the other code. And now I can begin chasing down this one.

**Comment by Torxed** [comment]
It might seam silly, but I've checked through the code and simply removed this on entry check if `format == MBR` or `format == GPT`. We don't need that check any longer. Will run a few tests with the PR and make sure it doesn't introduce anything weird I didn't think about..
