### ISSUE TITLE
#689 AttributeError: 'NoneType' object has no attribute 'format' on master reoccurs

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#708]
Sad to say, the last merge did not solve the problem, at least to me (test case a loop device on a SATA III SSD).
The original issue 689 is closed, but the symptoms are exactly the same as before

**Comment by Torxed** [comment]
Thank you for the feedback, but please keep the discussions to one topic and not multiple issues.
#689 is fine or #692 : )

**Comment by wllacer** [comment]
I did follow up the problem, and found a second place where the system delays the required information (at blockdevice.get_partitions, a the iterator. I've done some code changes (to put in into controlled loops and to get more debug info if necessary and haven't reproduced the error in a while. 
I'll send the corresponding PR to your attention.
PS. I hate to write into closed issues ...

**Comment by Torxed** [comment]
Thank you! #689 is open again, it got closed through the PR and I have to manually open it again once we found the issue :) So it's on me that it got closed and never re-opened once we verified the issue. Apologies.
