### ISSUE TITLE
KeyError: '!users' btrfs + luks and root account

### ISSUE THREAD

**Issue by mirsella** [archlinux/archinstall#712]
![Screenshot_20211111_185054](https://user-images.githubusercontent.com/45905567/141345426-430e2851-93bc-4440-8a93-f109228a0cc5.png)

heres the logs /var/log/archinstall [archinstall.zip](https://github.com/archlinux/archinstall/files/7522324/archinstall.zip)
running from master

thanks !

**Comment by Torxed** [comment]
Thanks for reporting this, should now be fixed.

**Comment by mirsella** [comment]
waw that was fast. You're awesome dude thanks
