### ISSUE TITLE
[Feature Request] Btrfs compression option

### ISSUE THREAD

**Issue by hkaancaliskan** [archlinux/archinstall#717]
Fedora ships with zstd level 1 (their study shows level 1 is the [most efficient](https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression#Simple_Analysis_of_btrfs_zstd_compression_level)) compression enabled by default and this would be great for users with btrfs.
File system can be mounted with `compress=zstd:1` argument and later than add `compress=zstd:1` to fstab.

Of course this can be enabled by user after installation but as arch wiki says;

> Only files created or modified after the mount option is added will be compressed. 

So stuff loaded by archinstall will not be compressed until files modified which is bad (need to re-write all files).
https://wiki.archlinux.org/title/Btrfs#Compression
https://fedoraproject.org/wiki/Changes/BtrfsTransparentCompression
https://btrfs.wiki.kernel.org/index.php/Compression

My own test on fresh install (Arch, Gnome, zstd 1)
```
    [kaan@arch ~]$ sudo compsize -x /
    Processed 138323 files, 71908 regular extents (74483 refs), 85668 inline.
    Type       Perc     Disk Usage   Uncompressed Referenced  
    TOTAL       54%      2.2G         4.1G         4.4G       
    none       100%      1.2G         1.2G         1.2G       
    zstd        35%      1.0G         2.9G         3.1G  
```

**Comment by Torxed** [comment]
We've discussed this back and forth a couple of times, what to enable and what we should leave up to the users.
Most recently I had this discussion in #380 where we landed in a compromise for advanced users: https://github.com/archlinux/archinstall/issues/380#issuecomment-955578905

The option *should* have been placed under the `filesystem` key, but it will do for now.
I think compression might be a sane option unless we can find arguments against it *(I don't know how taxing it is for older CPU's or limited RAM)*.

**Comment by J1Man** [comment]
I fully support this request. :)   Btrfs Compression is a good option that can be provided to the user by Archinstall.  

Arch wiki mentions that Btrfs compression significantly extends the life of Flash based boot media by reducing write amplification.  I am sure Solid State Hard Drives (SSDs) will also get life extension benefits from compression based on the wikipedia article that I linked below. Based on wikipedia, it seems like compression also improves SSD speed.
https://en.wikipedia.org/wiki/Write_amplification  

Archinstall script asks the user about encryption and swap on zram.  Asking about compression (if Btrfs is selected) is a logical step.  "compress=zstd:1" and "compress-force=zstd:1" are good choices that can be provided to the user.  Without the "force" flag some files don't get compressed.

**Comment by Torxed** [comment]
What im juggling is keeping menu entries simple and minimizing user questions, vs giving users options about every customizable aspect of all the choices.

Discussions like these are tricky because isolated to this context alone, i agree that it makes sense and "whats the harm? its just one option!" comes to mind.

Maybe with a `--compression` flag to easily enable it, but avoid adding one more meny entry?

**Comment by hkaancaliskan** [comment]
Yep you're right. There so much mount options and we can't ask every single one of them but what if we ask single question after user selected disk format type "write down mount options you would like to add, leave blank to use default options", by this way users can write down all the mount options they would like to add like compress, noatime, ssd etc and users who don't know/care about mount options can directly press enter. This would combine a lot of things in a single question.

**Comment by evilhamsterman** [comment]
That seems like a good compromise. I would offer a set of default to standard options. 

Another way is you could do a select screen like you do with the kernel selection

**Comment by J1Man** [comment]
@Torxed, thanks for the quick reply.  You are the visionary and the driving force behind this project.  Do it the way you think is the best.  You can use -compression flag or do what hkaancaliskan recommended.  If possible, chose something that can be implemented before the new Arch Installation CD is ready.  We only have  8 days left before the March 1st deadline. :))


The comment you linked https://github.com/archlinux/archinstall/issues/380#issuecomment-955578905 , seems to talk about format options.  Am I right about this?  My understanding is that inserting "options": "compress-force=zstd:15" into user_disk_layout.json file will not work.

The pull request by wllacer https://github.com/archlinux/archinstall/pull/838 has a mount option in it.  I am using the February Arch install CD.  Should I insert  "mount_options": "compress-force=zstd:15" into the Json file?

**There might be one issue/bug regarding this pull request https://github.com/archlinux/archinstall/pull/838**.  When I run archinstall with --dry-run command, the generated user_disk_layout.json file does not have any format options or mount options fields.  Shouldn't the file contain empty fields "format_options": "" and  "mount_options": "" ? Or do we need a special dry-run command for those.  For example --dry-run-showallfields.  People use --dry-run to generate these files and they edit them.  They won't even know that new options were implemented if they are not in the json file.  Editing existing fields is also easier/less error prone than adding them from scratch.

More I think about this, more complicated it gets. :))

**Comment by Torxed** [comment]
@J1Man: I will experiment and investigate some logical moments of archinstall before I can give a concrete answer :) Just wanted to ping and say that I'm looking in to it and will get back to you :)

**Comment by dylanmtaylor** [comment]
> @J1Man: I will experiment and investigate some logical moments of archinstall before I can give a concrete answer :) Just wanted to ping and say that I'm looking in to it and will get back to you :)

How about a generic filesystem mount options menu/prompt but only if --advanced is used?

**Comment by Torxed** [comment]
> > @J1Man: I will experiment and investigate some logical moments of archinstall before I can give a concrete answer :) Just wanted to ping and say that I'm looking in to it and will get back to you :)
> 
> How about a generic filesystem mount options menu/prompt but only if --advanced is used?

Could work too! That would probably be what most users assume `--advanced` to be even :)

**Comment by Torxed** [comment]
A PR for this has been submitted, testing will commence!

**Comment by Torxed** [comment]
I'm merging in a default `compress=ztsd` instead of `compress-force`.
This is to allow for a grace period of testing on general hardware.

As my somewhat limited understanding of the btrfs compression is that:
* `compress-force` attempts to compress entire files with the highest possible compression
* `compress` attempts to compress with in this case ztsd but only the beginning of the file, and if a good compression can be achieved it compresses the entire file.

And that it only stores the resulted compressed file if the compression was successful in both cases.
Mount points look like the following:
```
UUID     /    btrfs   rw,realtime,compress=zstd:3,space_cache=v2,subvolid=256,subvol=/@
...
```

**Comment by panchoh** [comment]
Hi, @Torxed!
Thanks for fixing this in `12b5e2e4e9537fbae0ec21ced9d21482b29610d3`.
I was curious about why you chose to not specify compression level 1 (`zstd:1`) and went with simply `zstd`.
(Asking because I have not seen it discussed anywhere else).

Thanks again!

**Comment by Torxed** [comment]
Hi. I tend to favor defaults as far as possible. Where default is sensible but the majority wish to cystomize, we usually offer a menu option or parameter to change values. Often hidden behind `--advanced` to avoid causing too many support tickets. Perhaps a `--compression zstd:1` would be ideal here?
