### ISSUE TITLE
Install failed, key error "Encrypted"

### ISSUE THREAD

**Issue by bebetoalves** [archlinux/archinstall#721]
During manual disk partitioning, you can realize that the "encrypted" key is not created in the dictionary, resulting in the error as we see below:

```log
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "600MiB",
                "start": "1MiB",
                "type": "primary",
                "wipe": true
            },
            {
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/",
                "size": "100%",
                "start": "600MiB",
                "type": "primary",
                "wipe": true
            }
        ]
    }
}
Kept partition format 1 for BlockDevice(/dev/sda, size=223.6GB, free_space=240GB, bus_type=sata)
Adding partition to BlockDevice(/dev/sda, size=223.6GB, free_space=240GB, bus_type=sata), 1MiB->600MiB
Getting mount information for device path /dev/sda1
Formatting /dev/sda1 -> fat32
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sda, size=223.6GB, free_space=1031kB+239GB, bus_type=sata), 600MiB->100%
Getting mount information for device path /dev/sda2
Formatting /dev/sda2 -> ext4
'encrypted'
```

![error](https://i.postimg.cc/tT2T3mZY/error-min.jpg)

A temporary solution for this is to manually activate disk encryption, then disable it.

**Comment by Torxed** [comment]
Apologies for that one. Should be fixed now.

**Comment by Torxed** [comment]
There's still a creeping feature here that encryption can be "enabled" in the configuration. And if there's no encryption password there will be an exception. You could argue that we should ask for a password if that's the case, but I'll leave it to be an exception as it's a manual choice, `guided` still protects us from this.

I'm referring to: https://github.com/archlinux/archinstall/blob/8799973895a8bb198c72522535852b3a9bfe83d9/archinstall/lib/installer.py#L180-L181
