### ISSUE TITLE
Desktop Environment Profile, make packages more specific

### ISSUE THREAD

**Issue by evan0greenup** [archlinux/archinstall#728]
# Potential Problem,

When focusing on `archinstall/profiles/gnome.py`, 

```python

# Note: GDM should be part of the gnome group, but adding it here for clarity
__packages__ = [
	"gnome",
	"gnome-tweaks",
	"gdm",
]

```

But here `gnome` is a group, 

```bash
$ pacman -Sg gnome
gnome baobab
gnome cheese
gnome eog
gnome epiphany
gnome evince
gnome file-roller
gnome gdm
gnome gedit
gnome gnome-backgrounds
gnome gnome-books
gnome gnome-calculator
gnome gnome-calendar
gnome gnome-characters
gnome gnome-clocks
gnome gnome-color-manager
gnome gnome-contacts
gnome gnome-control-center
gnome gnome-disk-utility
gnome gnome-font-viewer
gnome gnome-keyring
gnome gnome-logs
gnome gnome-maps
gnome gnome-menus
gnome gnome-music
gnome gnome-photos
gnome gnome-remote-desktop
gnome gnome-screenshot
gnome gnome-session
gnome gnome-settings-daemon
gnome gnome-shell
gnome gnome-shell-extensions
gnome gnome-software
gnome gnome-system-monitor
gnome gnome-terminal
gnome gnome-themes-extra
gnome gnome-user-docs
gnome gnome-user-share
gnome gnome-video-effects
gnome gnome-weather
gnome grilo-plugins
gnome gvfs
gnome gvfs-afc
gnome gvfs-goa
gnome gvfs-google
gnome gvfs-gphoto2
gnome gvfs-mtp
gnome gvfs-nfs
gnome gvfs-smb
gnome mutter
gnome nautilus
gnome orca
gnome rygel
gnome sushi
gnome totem
gnome tracker
gnome tracker-miners
gnome tracker3-miners
gnome vino
gnome xdg-user-dirs-gtk
gnome yelp
gnome gnome-boxes
gnome simple-scan

```

First issue, `gdm` and `gnome-tweaks` in in `gnome` group.

Not all this packages is needed by user who which to have a gnome desktop environment.

# Solution

alternative 1: make the packages list more specific, remove less-likely used packages.

alternative 2: create a new profile named `gnome_lite.py`, only list the most essential gnome packages in the list.

# My Opinion

For solution, I think alternative 2 is more practical, which doesn't change the behaviors for existed user.

`archinstall` can significantly save user's time while installing the system.

But the user why they choose Arch Linux is because they don't want to install unnecessary packages. 

A lite version of gnome profile can provide a minimum installation for gnome desktop environment. when the user need more packages, since the desktop system has already been established, they just need to type `pacman -S ...`, then the new packages will be installed.

This issue is not limited to `gnome`, but also other desktop environment profile.

**Comment by evan0greenup** [comment]
@Torxed Please have a consideration.

**Comment by Torxed** [comment]
This has been discussed before, and we have streamlined profiles before. But ideally this should be a discussion upstream to slim the gnome group down to not be so huge.

We cannot reliably maintain too many profiles with specific package lists without issues arising.

I'm willing to for maybe two major profiles to maintain a curated list, but after that it will be hard to stay up to date with changes.

**Comment by dylanmtaylor** [comment]
> This has been discussed before, and we have streamlined profiles before. But ideally this should be a discussion upstream to slim the gnome group down to not be so huge.
> 
> We cannot reliably maintain too many profiles with specific package lists without issues arising.
> 
> I'm willing to for maybe two major profiles to maintain a curated list, but after that it will be hard to stay up to date with changes.

Agreed. This is an upstream issue. If you need more customization, install minimal and cherry-pick what you want.
