### ISSUE TITLE
[Feature Request] source code generation for custom profiles and scripts.

### ISSUE THREAD

**Issue by evan0greenup** [archlinux/archinstall#740]
For user who want to install massive amount of computer with similar configuration and environment,  It would be awesome to provide a interactive interface to let user input essential information, and then generate relevant source code for script and profile.

For each computer instance, user just need to insert USB drive and then boot and then run the generated script. All the process will be done automatically.

And auto, for archinstall command, it would be nice to enable user to add custom profile, those custom profile will add to the candidate list when the archinstall let user to choose profile.

**Comment by Torxed** [comment]
I'm not sure I understand this request. Archinstall supports the `--config`, `--disk-layouts` and `--creds` parameters which allow you to do a complete template install.

Archinstall also supports custom profile paths in the profile question. If added to `--config`:

```json
{
    "profile": "https://remote.lan/my_profile.py",
    ...
}
```
Archinstall will source that profile and you can do whatever you want in it :)

A separate project of mine archiffline even allows you to do all this offline from a USB stick :)

Is this what you needed?

**Comment by bebetoalves** [comment]
> I'm not sure I understand this request. Archinstall supports the `--config`, `--disk-layouts` and `--creds` parameters which allow you to do a complete template install.
> 
> Archinstall also supports custom profile paths in the profile question. If added to `--config`:
> 
> ```json
> {
>     "profile": "https://remote.lan/my_profile.py",
>     ...
> }
> ```
> 
> Archinstall will source that profile and you can do whatever you want in it :)
> 
> A separate project of mine archiffline even allows you to do all this offline from a USB stick :)
> 
> Is this what you needed?

Maybe he's talking about this? #566

**Comment by dylanmtaylor** [comment]
I am pretty sure we already have this. --config allows you to pass in pre-populated values to guided. ArchInstall is also a python library and you can write your own installer using its methods very easily (there are examples of this).

**Comment by evan0greenup** [comment]
@Torxed @bebetoalves , is it possible to pass multiple profiles to archinstall?

**Comment by Torxed** [comment]
> @Torxed @bebetoalves , is it possible to pass multiple profiles to archinstall?

Not in the sense you mean, `--profile=one.py,two.py` does not work *(yet at least)*. Because we don't iterate the profile parameter in any of our usages: https://github.com/archlinux/archinstall/blob/627b6b5207beffee2ed9507933cebe780c62a11d/examples/guided.py#L152-L156

However, a [profile](https://github.com/archlinux/archinstall/blob/master/profiles/desktop.py#L83) can install [another profile](https://github.com/archlinux/archinstall/blob/master/profiles/awesome.py), so nesting profiles are allowed and supported. But it's done through the profile code and not via the guided installers parameter.

**Comment by svartkanin** [comment]
Profiles can now be programmed and used in scripts
