### ISSUE TITLE
Archinstall v2.3.0 RC2

### ISSUE THREAD

**Issue by Col433** [archlinux/archinstall#744]
Not asking for a user name, password and superuser? during install

**Comment by dylanmtaylor** [comment]
> Not asking for a user name, password and superuser? during install



> Not asking for a user name, password and superuser? during install

I think these prompts are skipped if you select a root user password

**Comment by Col433** [comment]
You are correct thanks Dylan. The install script has changed since the last time I used it  v2.3.0 RC2 installed without any problems using my configuration on my system.
