### ISSUE TITLE
System with encryption doesn't boot

### ISSUE THREAD

**Issue by Giusep24** [archlinux/archinstall#745]
Hi, I tried to install arch linux with archinstall but after reboot the system didn't  start inspite the installer finished without error.
I choose lusk encryption and systemd-boot. fdisk -l show two partion the efi and the encrypted one. ls /etc/boot doesn't find anything.
![photo5819036879528506890](https://user-images.githubusercontent.com/81783712/142703585-299c9efb-38b7-4c16-b52c-a404fd4905b1.jpg)

**Comment by Torxed** [comment]
Was this using the official ISO or a dev version from GitHub?

**Comment by Giusep24** [comment]
I tried with official Iso and with 2.3Rc2 same error, I also dd zeroing my
nvme but no change.

Il sab 20 nov 2021, 09:39 Anton Hvornum ***@***.***> ha
scritto:

**Comment by Torxed** [comment]
Can you post your `/var/log/archinstall/install.log`? And the `user_disk_layout.json` if you're using RC2.

**Comment by Giusep24** [comment]
Yes, but I don't know how to find it, can you guide me please?

Il sab 20 nov 2021, 11:15 Anton Hvornum ***@***.***> ha
scritto:

**Comment by Giusep24** [comment]
Yes if you want, but after a few days I found the problem, maybe is not an archinstall bug.
Missing the vmd module in mkinitcpio.

**Comment by Torxed** [comment]
Ah, this is a known issue and tracked here: #671
Generally speaking RAID and different hardware setups is something we'll polish for the next release.
