### ISSUE TITLE
[2.3.0RC2] [VM] Can't create a filesystem on a new partition during the manual partitioning

### ISSUE THREAD

**Issue by DesertStars** [archlinux/archinstall#746]
During the manual partitioning, if you select to ''Create a new partition'' and later write a filesystem when archinstall asks for one, it'll crash after writing the name of filesystem.

![2021-11-21_00-14-40](https://user-images.githubusercontent.com/53870341/142741251-742a1fdb-c900-44cc-9227-a8f0a29ab4a4.png)

**Comment by Torxed** [comment]
Thank you for this feedback, the manual partitioning is the least tested - so this is extremely valuable! :D
I'll investigate during the weekend.

**Comment by Torxed** [comment]
![screenshot](https://user-images.githubusercontent.com/861439/142836906-db8c7653-c348-4e05-b716-093fcea5bc89.jpg)

This specific error is now solved.
There might be more issues with manual partitioning, I'll run a few tests and see if I can find any but feedback is welcome.
