### ISSUE TITLE
[Feature Request] Add an option for seperate /home partition in the default partitioning

### ISSUE THREAD

**Issue by DesertStars** [archlinux/archinstall#747]
Currently if you choose `Wipe all selected drives and use a best-effort default partition layout` during the partitioning, it'll default to creating two partitions, `/boot` and `/`. It'd be really useful instead of just creating a `/` partition for everything, there'd be an option to choose between having everything on `/` and having a separate `/home` partition, ie. `/boot`, `/` and `/home`. I understand not wanting to clutter the guided partitioning too much but I believe this is a fairly common partition scheme that it makes sense to include alongside the current option.

**Comment by Torxed** [comment]
I'm guessing you used the official arch ISO? Because this feature already exists in `master` and will be released in a few days

**Comment by DesertStars** [comment]
I used 2.3.0RC2 iso, I'm guessing this option not available in there yet and will be in the next iso? If yes that's great to hear, because a seperate /home partition is pretty much the only thing missing from archinstall for me. This is what I see after the installation currently with the default partition layout:

![2021-11-21_11-26-41](https://user-images.githubusercontent.com/53870341/142755122-6d55d929-697a-402f-a4bb-90241a758ae7.png)

Not sure why it doesn't show the mountpoint for /boot, but only sda1 (/boot) and sda2 (/) are available in the system.

**Comment by Torxed** [comment]
Humm, it should have created a `/home`, it's in RC2.
Do you mind posting your `/var/log/archinstall/user_disk_layouts.json`? Would be very helpful.

**Comment by DesertStars** [comment]
I couldn't find archinstall directory in /var/log, is it removed after the installation?

**Comment by Torxed** [comment]
> I couldn't find archinstall directory in /var/log, is it removed a

It should be copied over to the installation, might require root privileges to grab it though.

**Comment by DesertStars** [comment]
Unfortunately it doesn't even exist, but it should be same as the layout I posted above in the edit, you might have missed it since it was almost edited as the same time as your post and AFAIK edits don't send a notification.

![2021-11-21_15-21-29](https://user-images.githubusercontent.com/53870341/142761540-dc954819-bf49-4c06-be33-0ecf2793b511.png)

**Comment by Torxed** [comment]
I'll close this as we've added it.
And the minimum size for a `/home` to be created in v2.3.1 will be 60GB of disk space. Users will have to do `--dry-run` to generate configurations in `/var/log/archinstall/` and modify `user_disk_layouts.json` in order to add a home if they still want it below 60GB.
