### ISSUE TITLE
iwctl not working

### ISSUE THREAD

**Issue by cabl9** [archlinux/archinstall#757]
I was trying to connect to wifi, and the keyword iwctl gives the error `command not found`. I'm not sure why it doesn't work because I am new to arch linux. I assumed that iwctl did not install for some reason and tried installing with the command `pacman -S iwd`. It gave me the error `iwd-1.20-1-x86_64.pkg.tar.zst failed to download` . It looked like it attempted to download from several websites unsuccessfully. What should I go about fixing this problem?

I've added a picture link in case that is any help: [https://linksharing.samsungcloud.com/8YB89xZ6mM8O](url)

**Comment by dylanmtaylor** [comment]
If you're not on a network connection, you won't be able to install iwd from the internet. This is from an installed system, not from ArchInstall? I think if you did the install with either NetworkManager selected or the copy my config option, you'd have iwd or some equivalent. You could copy iwd's package from https://archlinux.org/packages/ and install it that way with pacman -U, but I'd just recommend a reinstall unless you're really invested in the system, making sure you add all network packages needed during the installation. This isn't an installer issue so much as general troubleshooting of an installed system, so it should be closed.

**Comment by cabl9** [comment]
Ok, thanks for the advice.
