### ISSUE TITLE
Detect if espeakup.service is active in live medium and copy over

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#758]
When `espeakup.service` is used on the ISO, assume that the user would want that copied over and do so.
I don't think we necessarily need to ask the question in the guided installer, as it would probably be enough to do the detection and act on it.

See discussion on the `argh-general` mailing list: https://lists.archlinux.org/pipermail/arch-general/2021-November/049405.html

**Comment by dylanmtaylor** [comment]
This should be fairly easy to do actually,  in addition to making sure that the service is enabled by default, we also need to figure out all the packages necessary and have them installed as part of the base installation, not necessarily the desktop only.  It's kind of a shame that this isn't going to make it in for 2.3.0,  as I don't like that it's not very accessible to blind individuals right now.  The workaround would be to add the additional packages needed during installation and then enable them using the chroot before booting.

**Comment by Torxed** [comment]
I think for speech synthesis it's primarilly [espeak](https://archlinux.org/packages/community/x86_64/espeak/) that needs to be strapped.

**Comment by dylanmtaylor** [comment]
> I think for speech synthesis it's primarilly [espeak](https://archlinux.org/packages/community/x86_64/espeak/) that needs to be strapped. If the fix is small, I see no issues incorporating it in v2.3.0. I blindly assumed that it would require more re-work : )

I imagine that it's be something like this pseudo code:

if espeak.service is running:
    base_packages.append('espeak')
    enable_service('espeak.service')

**Comment by Torxed** [comment]
True, I will have to work out the multi-disk-layout dead code path (or simply add an exception to specify that this is in Beta) and then check on the btrfs subvolume issue that's open. So if anyone wants to contribute this for v2.3.0 I'm all for it : ) Otherwise I'll have to do it after those two issues.

**Comment by dylanmtaylor** [comment]
Working on this in #760
