### ISSUE TITLE
Installer does not append 'btrfs-progs' into mkiniticpio

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#764]
When installing over a btrfs filesystem btrfs-progs has to be included in binaries@mkinitcpio. Due to a mistype at Installer.py lnr 450, this is not done.
There is written
```
				if '/usr/bin/btrfs-progs' not in self.BINARIES:
					self.BINARIES.append('/usr/bin/btrfs')
```
Should be  *--Edited: the original solution was backwards*
```
				if '/usr/bin/btrfs' not in self.BINARIES:
					self.BINARIES.append('/usr/bin/btrfs')
```
I'll attach a PR

**Comment by wllacer** [comment]
I have to resyncroniz my branch. Solution will wait a litte

**Comment by dylanmtaylor** [comment]
> I have to resyncroniz my branch. Solution will wait a litte

This may ended up making it into the next release, Torxed is about to tag 2.3.0

**Comment by Torxed** [comment]
> > I have to resyncroniz my branch. Solution will wait a litte
> 
> This may ended up making it into the next release, Torxed is about to tag 2.3.0

There's still time, I'm about 50% done with the writeup of the changelog.
So there's time : )
