### ISSUE TITLE
JSON configuration files

### ISSUE THREAD

**Issue by mgml87** [archlinux/archinstall#772]
Hi. I use archinstall to provide automated installation on some servers, but with the new version, JSON has completely changed. Is there an expected date when https://github.com/archlinux/archinstall/blob/master/examples/config-sample.json and https://github.com/archlinux/archinstall/blob/master/examples/custom-command-sample.json will be updated?

**Comment by dylanmtaylor** [comment]
> Hi. I use archinstall to provide automated installation on some servers, but with the new version, JSON has completely changed. Is there an expected date when https://github.com/archlinux/archinstall/blob/master/examples/config-sample.json and https://github.com/archlinux/archinstall/blob/master/examples/custom-command-sample.json will be updated?

We really ought to update those ASAP, thank you for bringing this to our attention.

**Comment by Torxed** [comment]
The urgent fix is to run `archinstall --dry-run` and it should abort any operation before continuing. That way you can always get the latest examples generated. I'll do that later today and push to the examples catalog.

**Comment by Torxed** [comment]
I fixed the three most important updates, `--creds`, `--disk_layouts` and `--config` examples.
The custom-commands sample still remains, I'd like to bring those changes in as it serves as a good example but I'll have to go through it line by line to see what changed. The others were auto-generated with `--dry-run`.

**Comment by mgml87** [comment]
I tested it today and everything worked perfectly. Thank you.
