### ISSUE TITLE
Small UI annoyance when using a prepartitioned layout

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#776]
Using the guide script, when trying to execute over a preexisting disk layout (i.e. the target disk is parititoned and mounted BEFORE executing archinstall, we get following flow:
```
0: BlockDevice(/home/werner/vms/testimage.img, size=8.0GB, free_space=4177kB+1032kB, bus_type=None)
1: BlockDevice(/dev/sda, size=465.8GB, free_space=4177kB+7680B, bus_type=sata)
2: BlockDevice(None, size=1.0GB, free_space=, bus_type=sata)
Select one or more harddrives to use and configure (leave blank to skip this step):

0: Wipe all selected drives and use a best-effort default partition layout
1: Select what to do with each individual drive (followed by partition usage)
Select what you wish to do with the selected block devices:

Would you like to use GRUB as a bootloader instead of systemd-boot? [y/N]
```
As you will notice the question if i want to manipulate the disks still appears when it should not (The first time is one of this What the Heck moments)

**Comment by Torxed** [comment]
Heh, yea that should be fixed.
We're re-working the menu system altogether in #660 and making it more polished. We'll make sure that these questions does not come up, unnecessary scare : )

**Comment by wllacer** [comment]
The culprit is ln 111 at guided.py

https://github.com/archlinux/archinstall/blob/22ee2d90a1d2fb6af2ab5e80235e31f9da7a0550/examples/guided.py#L104-L113

Simply there is a check for **not None** when archinstall.arguments['harddrives'] holds an empty list.

I have a till now private change which besides solving this (and making the following code somehow more readable), has a bit of information for the user, and some "ass covering" (although i doubt a lawyer would agree). 
See the example 
```
0: BlockDevice(/home/werner/vms/testimage.img, size=8.0GB, free_space=4177kB+1032kB, bus_type=None)
1: BlockDevice(/dev/sda, size=465.8GB, free_space=4177kB+7680B, bus_type=sata)
2: BlockDevice(None, size=1.0GB, free_space=, bus_type=sata)
Select one or more harddrives to use and configure (leave blank to skip this step):

You decided to skip harddrive selection
and will use whatever drive-setup is mounted at /mnt/archinstall (experimental)
WARNING: Archinstall won't check the suitability of this setup
Do you wish to continue ? [Y/n]

Would you like to use GRUB as a bootloader instead of systemd-boot? [y/N]
```
When the user says no, i end the execution gracefully with an exit(1)
If you feel it useful, i'll send a PR with my solution

**Comment by svartkanin** [comment]
@Torxed I think this is no longer an issue with the new menu style?

**Comment by Torxed** [comment]
i think so yea :)
