### ISSUE TITLE
Choose partition size in Guided mode

### ISSUE THREAD

**Issue by MightyPork** [archlinux/archinstall#786]
Hi, I wanted to try this tool today and it almost saved me a lot of work, except: 20GB is too small for root. My existing system now uses 25GB on `/usr` alone. Actually, I would prefer to not split `/home` to its own partition at all. I don't have experience with resizing an encrypted partition, but something tells me it will be a pain.

Can this be changed other than by editing the library sources or writing a custom install script?

Here's the JSONs it printed:

```
{
    "audio": null,
    "bootloader": "grub-install",
    "desktop-environment": "kde",
    "dry-run": false,
    "gfx_driver": "Nvidia (proprietary)",
    "harddrives": [
        "/dev/nvme0n1"
    ],
    "hostname": "N202",
    "kernels": [
        "linux",
        "linux-lts"
    ],
    "keyboard-layout": "us",
    "mirror-region": {},
    "nic": {
        "NetworkManager": true,
        "nic": "Use NetworkManager (necessary to configure internet graphically in GNOME and KDE)"
    },
    "ntp": true,
    "packages": [
        "firefox"
    ],
    "profile": {
        "path": "/usr/lib/python3.9/site-packages/archinstall/profiles/desktop.py"
    },
    "script": "guided",
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "Europe/Prague"
}
{
    "/dev/nvme0n1": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MB",
                "start": "5MB",
                "type": "primary"
            },
            {
                "encrypted": true,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/",
                "size": "20GB",
                "start": "518MB",
                "type": "primary"
            },
            {
                "encrypted": true,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "generate-encryption-key-file": true,
                "mountpoint": "/home",
                "size": "100%",
                "start": "20.5GB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
```

**Comment by Torxed** [comment]
You can use `--dry-run` to generate the above config. And modify `/var/log/archinstall/user_disl_layouts.json` and pass it to archinstall via `--disk_layouts=/var/log/archinstall/user_disl_layouts.json`.

While we adjust the minimum size for root :)

**Comment by Torxed** [comment]
This should now have been tweaked in 3ef8387.
For future reference, I'm considering where and how to put a question *"Do you wish to create a separate home partition?"*.

**Comment by k12ish** [comment]
I'm a little confused because the codebase doesn't seem to have this change, instead I see this:

https://github.com/archlinux/archinstall/blob/21735c57ca4ace638b3c8faecc503720008fa82b/archinstall/lib/interactions/disk_conf.py#L324

Like @MightyPork, I've run into issues with the 20GiB limit, but I do see this reasonable amount for average users.
