### ISSUE TITLE
[Feature Request] enable Multiboot in /etc/default/grub

### ISSUE THREAD

**Issue by JohnML1** [archlinux/archinstall#791]
add this line so other Linuxe|Windows 10 keep bootable

GRUB_DISABLE_OS_PROBER=false

**Comment by Torxed** [comment]
This would require the package `os-prober` as well. And I have a vague memory of it being disabled for security reasons?
I can't find any information on this now, but if that still remains I can't set `GRUB_DISABLE_OS_PROBER` without ramifications.

**Comment by Torxed** [comment]
I'll reference the source mailing list too: https://lists.ubuntu.com/archives/ubuntu-devel/2021-December/041769.html

**Comment by Torxed** [comment]
I'm closing this as it's a duplicate of #266. Discussions are still ongoing but by closing this we streamline the conversation to one thread so we don't miss anything :)
