### ISSUE TITLE
Missing step to add user

### ISSUE THREAD

**Issue by SoongVilda** [archlinux/archinstall#799]
I went 2 times through archinstall, but I only saw question for hostname.
Where is question (step) for adding user?

Version ISO
archlinux-2021.12.01-x86_64

**Comment by SoongVilda** [comment]
That sounds weird, you be able use sudo, because you have superuser (root password), but user is also need it.
So I must miss root password and then I will be prompt to set user?

**Comment by dylanmtaylor** [comment]
> That sounds weird, you be able use sudo, because you have superuser (root password), but user is also need it. So I must miss root password and then I will be prompt to set user?

That appears to be how the current behavior works. @Torxed -  is this something we want to change?  So you can set the password and the password of the supervisor through the guided installer?

**Comment by SoongVilda** [comment]
Version 2.2.0 was pretty intuitive and follows simple way.

- Encryption
- hostname
- root password 
- user (name & password) 
- question for more user
done

I believe these are the most used options and perhaps you always have to configure them manually anyway, automation through archinstall would shorten the installation.

But latest version 2.3.0 without user? It's confusing

**Comment by Torxed** [comment]
The workflow here should be:

 1. Do you want root? No -> Force at least one superuser -> Do you want to add additional users? -> Sudo?
 2. Do you want root? Yes -> Do you want to add a user? -> Should that user be a super-user (sudo)?

Somewhere along the way during the last version that workflow changed and apparently lost some flexability.
Recommendation for now is to set a root password and then create your other users manually.
It's a bit of an inconvenience but at least is not a breaking issue. But I'll fix it in v2.3.1 this week.

**Comment by Torxed** [comment]
I'll have to apologize because I fixed this before seeing this PR.
So I'll close this but wanted to note that this was a welcome PR and there was nothing wrong with it, so I'm not closing it because it was bad or anything. Apologies!

*(See 2419c6b and aa21cd4)*
