### ISSUE TITLE
Regenerate initramfs at the end

### ISSUE THREAD

**Issue by rednaz1337** [archlinux/archinstall#805]
It would be great if this script regenerated the initramfs at the end. When you use an encrypted rootfs and set the keyboard layout to a non-english one, the keyboard layout is still set to english in the initramfs where you need to enter your password. This makes it difficult to enter the password correctly. It can be fixed by manually running `mkinitcpio -P` in the chroot environment at the end, but it would be great if archinstall did this automatically. It's not a huge problem, but it would be nice to have.

**Comment by Torxed** [comment]
Humm, we set the keyboard locale before generating initramfs, or so I thought.
But if we don't then we should absolutely implement this : )

**Comment by Torxed** [comment]
Fixed in c4f80b9 and should be released soon in v2.3.1.
