### ISSUE TITLE
Make this installer translatable, please

### ISSUE THREAD

**Issue by roxfr** [archlinux/archinstall#807]
Hello,
Could you make this installer translatable, please?
Thank you.
Regards,
Roxfr

**Comment by Torxed** [comment]
I don't mind this and I'll try to get on it for v2.4.0. Will be a fun one to solve neatly.

**Comment by svartkanin** [comment]
@Torxed I'd be happy to pick this one up. Maybe we can have a discussion around it how to best do it, I have some ideas but just to double check since it will be quiet a significant change

**Comment by Torxed** [comment]
> @Torxed I'd be happy to pick this one up. Maybe we can have a discussion around it how to best do it, I have some ideas but just to double check since it will be quiet a significant change

Go for it, we could use this issue, a discussion topic or a PM on Discord.
I'll be occupied for a bit tho : )

**Comment by svartkanin** [comment]
My idea was to use the `gettext` module and create a new `locals` folder with all the translations in it. 
Then we can use them in the code with `text = _('Select harddrive')`

**Comment by Torxed** [comment]
> gettext

That seems to be the best practice way, and it's a builtin. I very much like the idea! :)
If you've used that one before, feel free to start on it. I can help with replacing more strings once the skeleton is there.

**Comment by svartkanin** [comment]
@Torxed I reckon we can close this?

**Comment by Torxed** [comment]
Correct, translation has been added. Currently we have English, German and Spanish is on the way in a PR.
