### ISSUE TITLE
mkinitcpio.conf generated incorrectly for AMDGPU.

### ISSUE THREAD

**Issue by Galcian79** [archlinux/archinstall#808]
As the archwiki installation guide states [https://wiki.archlinux.org/title/AMDGPU#Specify_the_correct_module_order](https://wiki.archlinux.org/title/AMDGPU#Specify_the_correct_module_order), you must ensure that the amdgpu module is loaded before the radeon one: `MODULES=(amdgpu radeon)`
Otherwise the DM will fail to start at boot.

**Comment by Torxed** [comment]
We'll have to implement a package log in: https://github.com/archlinux/archinstall/blob/638a05243c7bab7db7449c24a2ab770e581244d0/archinstall/lib/installer.py#L264

And then in the xorg profile create a similar conditional update on https://github.com/archlinux/archinstall/blob/d2a4572e98044d4af504aabd0203b6c89e9991bf/profiles/xorg.py#L40

**Comment by Torxed** [comment]
Fixed, realized we could detect it based on the graphics driver selected in the prep function. This fix will be out in v2.3.1 :) Thank you for reporting this!
