### ISSUE TITLE
APFS partition not recognised

### ISSUE THREAD

**Issue by benglim** [archlinux/archinstall#811]
I have this error:

Re-using partition instance: (Partition(path=/dev/nvme0n1p6, size=xx, PARTUUID=XX, fs-apfs)
not supported between instances of 'str' and 'NoneType'

Any way around this? Is the old method of mounting '/' and '/boot' still working?

**Comment by Torxed** [comment]
> Any way around this? Is the old method of mounting '/' and '/boot' still working?

It is :) You can mount it manually and skip the partitioning step.
However, `fs-apfs` is not supported *(yet?)* and someone would have to contribute a PR for that if they want it: https://github.com/archlinux/archinstall/blob/638a05243c7bab7db7449c24a2ab770e581244d0/archinstall/lib/disk/partition.py#L260-L286

So I'm not sure that even mounting it manually would work? Unless there's no need for kernel parameters and stuff.

**Comment by benglim** [comment]
OK now with the latest build.
Just remember the manual mountpoints before starting archinstall:

/mnt/archinstall              for root partition
/mnt/archinstall/boot.    for boot/EFI partition
