### ISSUE TITLE
ValueError on setting a mountpoint 

### ISSUE THREAD

**Issue by bebetoalves** [archlinux/archinstall#812]
When I am creating the partitions manually and trying to set one of them to the /boot mount point, I get this error:

![20211227_092939](https://user-images.githubusercontent.com/13764984/147472240-9c05cdbb-6e3e-43de-9a77-dbb07805426f.jpg)

**Comment by bebetoalves** [comment]
Even setting the partition as bootable, the mount point is not automatically applied.

![20211227_093731](https://user-images.githubusercontent.com/13764984/147472594-6f070e69-d805-4f74-85a7-eeb295915495.jpg)

**Comment by Torxed** [comment]
Interesting error, I'll have a look at it :)

**Comment by svartkanin** [comment]
@Torxed this should be resolved with all the changes in the partition logic
