### ISSUE TITLE
correct driver for nvidia gpu

### ISSUE THREAD

**Issue by jithinjames916** [archlinux/archinstall#815]
I have an old nvidia gpu on my pc...
The arch install only install latest nvidia drivers...
There is correct drivers in aur and yay...
If there was an option to auto install the correct nvidia driver for pc/ an option to manually do so during install could be great

**Comment by Torxed** [comment]
Sadly this won't be possible I'm afraid.
Officially we can only support what's in the main package repositories. AUR packages are there for out of the question for support reasons. The easiest way for now is to install them manually.
