### ISSUE TITLE
Loading the correct key map

### ISSUE THREAD

**Issue by DrDonner** [archlinux/archinstall#816]
When choosing the german keymap it loads "de". But "de" does not contain the german Umlaute äöü.
This can lead to problems when entering information. Especially on passwords, since you cant see the digits you actually type
"de-latin1" or "de-latin1-nodeadkeys" would be every germans choice for keymap

**Comment by Torxed** [comment]
I would deem this not an archinstall issue, but a systemd issue.
We only use the list given to us by `localectl --no-pager list-keymaps`, which contains both `de` and `de-latin1`.

There are probably legitimate use cases for `de`, I don't know about them.
But I'll go ahead and close this issue as there's not much we can do about the list of locales *(other than curating our own list, which will be a nightmare to maintain, so we use the upstream lists)*.
