### ISSUE TITLE
issue with screen reader

### ISSUE THREAD

**Issue by ksb749** [archlinux/archinstall#825]
Im sorry if this is all wrong, im doing my best as legally blind and not a familiar user, but i was pointed over here from a reddit topic i made: https://www.reddit.com/r/archlinux/comments/rtna4n/archinstall_issue_with_speech/

With the screen reader enabled in Arch 2022.01.01 i run the archinstall and during this fantastic script i can choose my language and country, but there seem to be a problem because it reads it up like 1 lang 53 lang lang 54 lang

When it does it like that its confusing when to act because it will sound like it says a language and then its number followed by a pause.

Same goes with country and other situations like this.. Its my first time trying Arch with speech like this and maby i need to learn it, but it would be nice if the interface used arrow up, arrow down, enter, space etc. because its not easy when its not possible to get earlier text read up (i suppose i can, but i just dont know how)..

**Comment by Torxed** [comment]
> but it would be nice if the interface used arrow up, arrow down, enter, space etc.

Not the next, but probably the one after that will have these features.
The menu system has been re-written to use a menu library that supports arrows as well as reading out the entries.

**Comment by Torxed** [comment]
I'll close this since it's solved in master, not because it's a bad suggestion. Just wanted to make that clear before I closed it. Thank you for reporting this suggestion and I hope that you'll find the new menu system to suit your needs. If not, please open a new issue on the topic :)

**Comment by mhussaincov93** [comment]
yeah master does rock! perfectly navigable with espeakup,
Majid
