### ISSUE TITLE
Installer.arch_chroot() got an unexpected keyword argument 'runas'

### ISSUE THREAD

**Issue by hexarch** [archlinux/archinstall#826]
Arch ISO from 2022.01.01 with BIOS boot because UEFI does not boot.
Choose server edition, and pick httpd, postgresql and ssh. 
Filesystem was ext4 and I did select "no audio" but the install log says pipewire.

**Comment by hexarch** [comment]
root@archiso ~log/archinstall # cat install.log 
Hardware model detected: QEMU Standard PC (i440FX + PIIX, 1996); UEFI mode: False
Processor model detected: Common KVM processor
Memory statistics: 1755044 available out of 2023972 total installed
Virtualization detected: kvm; is VM: True
Graphics devices detected: dict_keys(['Device 1234:1111 (rev 02)'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '715.4M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '32G', 'children': [{'name': 'sda1', 'fstype': 'vfat', 'fsver': 'FAT32', 'label': None, 'uuid': '12B5-F32D', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '484M'}, {'name': 'sda2', 'fstype': 'crypto_LUKS', 'fsver': '2', 'label': None, 'uuid': 'bf48b182-7689-4be2-81c0-1e2a77dbd1db', 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'part', 'size': '31.5G'}]}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202201', 'uuid': '2022-01-01-10-11-06-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '864.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Unknown blockdevice type for /dev/sr0: rom
Unknown blockdevice type for /dev/sr0: rom
Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
-- Guided template chosen (with below config) --
{
    "audio": "pipewire",
    "bootloader": "grub-install",
    "dry-run": false,
    "harddrives": [
        "/dev/sda"
    ],
    "hostname": "arch2022",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {
        "Portugal": {
            "http://ftp.rnl.tecnico.ulisboa.pt/pub/archlinux/$repo/os/$arch": true,
            "http://glua.ua.pt/pub/archlinux/$repo/os/$arch": true,
            "https://ftp.rnl.tecnico.ulisboa.pt/pub/archlinux/$repo/os/$arch": true,
            "https://glua.ua.pt/pub/archlinux/$repo/os/$arch": true
        }
    },
    "nic": {
        "nic": "ens18"
    },
    "ntp": true,
    "packages": [],
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/server.py"
    },
    "script": "guided",
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "Europe/Lisbon"
}
{
    "/dev/sda": {
        "partitions": [
            {
                "boot": true,
                "encrypted": false,
                "filesystem": {
                    "format": "fat32"
                },
                "format": true,
                "mountpoint": "/boot",
                "size": "513MB",
                "start": "5MB",
                "type": "primary"
            },
            {
                "encrypted": false,
                "filesystem": {
                    "format": "ext4"
                },
                "format": true,
                "mountpoint": "/",
                "size": "100%",
                "start": "518MB",
                "type": "primary"
            }
        ],
        "wipe": true
    }
}
Creating a new partition label on /dev/sda
Adding partition to BlockDevice(/dev/sda, size=32.0GB, free_space=34.4GB, bus_type=None), 5MB->513MB
Getting mount information for device path /dev/sda1
Formatting /dev/sda1 -> fat32
Marking partition Partition(path=/dev/sda1, size=0.5, PARTUUID=e06dcd02-01, fs=fat32) as bootable.
Setting boot on on (parted) partition index 1
Adding partition to BlockDevice(/dev/sda, size=32.0GB, free_space=5242kB+33.8GB, bus_type=None), 518MB->100%
Getting mount information for device path /dev/sda2
Formatting /dev/sda2 -> ext4
Mounting / to /mnt/archinstall/ using Partition(path=/dev/sda2, size=31.5, PARTUUID=e06dcd02-02, fs=ext4)
Mounting Partition(path=/dev/sda2, size=31.5, PARTUUID=e06dcd02-02, fs=ext4) to /mnt/archinstall/
Getting mount information for device path /mnt/archinstall/
Mounting /boot to /mnt/archinstall/boot using Partition(path=/dev/sda1, size=0.5, PARTUUID=e06dcd02-01, fs=fat32)
Mounting Partition(path=/dev/sda1, size=0.5, PARTUUID=e06dcd02-01, fs=fat32) to /mnt/archinstall/boot
Getting mount information for device path /mnt/archinstall/boot
Getting mount information for device path /dev/sda2
Getting mount information for device path /dev/sda1
Waiting for automatic mirror selection (reflector) to complete.
A new package mirror-list has been created: /etc/pacman.d/mirrorlist
Getting mount information for device path /dev/sda2
Getting mount information for device path /dev/sda1
Getting mount information for device path /dev/sda
Getting mount information for device path /dev/sda
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'grub']
Getting mount information for device path /dev/sda2
Getting mount information for device path /dev/sda1
Adding bootloader grub-install to Partition(path=/dev/sda1, size=0.5, PARTUUID=e06dcd02-01, fs=vfat, mounted=/mnt/archinstall/boot)
Installing packages: ('grub',)
Getting mount information for device path /dev/sda
GRUB uses /dev/sda1 as the boot partition.
Setting up swap on zram
Installing packages: ('zram-generator',)
Enabling service systemd-zram-setup@zram0.service
Enabling service systemd-networkd
Enabling service systemd-resolved
This audio server will be used: pipewire
Installing packages: ['pipewire', 'pipewire-alsa', 'pipewire-jack', 'pipewire-media-session', 'pipewire-pulse', 'gst-plugin-pipewire', 'libpulse']
Installing network profile Profile(server)
Now installing the selected servers.
['httpd', 'postgresql', 'sshd']
Installing httpd ...
Installing packages: ['apache']
Enabling service httpd
Installing postgresql ...
Installing packages: ['postgresql']
Installer.arch_chroot() got an unexpected keyword argument 'runas'
root@archiso ~log/archinstall #

**Comment by Torxed** [comment]
This has been fixed in commit cad9118 for `master` and a470605 for `v2.3.1` and will be out in the new release in the next couple of days, v2.3.1 : )

**Comment by Torxed** [comment]
I'd just like to also mention that the `pipewire` installation now also correctly enables the `pipewire-pulse` service for backwards compatibility. So if some things didn't work with pipewire, #821 should fix that.
