### ISSUE TITLE
httpS problems if date is wrong in the installer

### ISSUE THREAD

**Issue by ilario** [archlinux/archinstall#830]
Using archinstall on a system with a wrong date/clock fails at the mirror selection step.
This happens because the https certificate used for downloading the mirrors list gets recognized as invalid when comparing its validity date and with the (wrong) system date.

The resulting error message in my case was this:

`Could not fetch an active mirror-list: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate is not yet valid (_ssl.c:1129)>`

Maybe this was related to #682 and #297

**Comment by Torxed** [comment]
This is expected. It's a security measurement in the HTTPS protocol. And any tool you run will have the same issue (wget, curl, archinstall, python.. etc).

Anytime you want to go out on the internet, even on your desktop client (windows, mac or linux) you will have to first ensure that the time of your BIOS and or OS (including Arch Linux live ISO) is correct.

There's not much archinstall can do here, so I'll close this unless suggestions to improve the UI to notify some how, but I'm not sure how we'd detect this prior to going out on the internet to check the time.

**Comment by ilario** [comment]
Yep, I know it is normal to happen. Check out #831 for a proposed solution (as it's the first time I use archinstall, this could well be a very bad way to fix, I don't know).

**Comment by Torxed** [comment]
Apologies, until I read your PR I thought this was more of a support ticket on how HTTPS works.
I now understand your intentions more clear and I merged your PR. It was a solid 10/10 fix I would say! : ) Good job!
