### ISSUE TITLE
Not pulling profiles when installing via pip? 

### ISSUE THREAD

**Issue by MattBlack85** [archlinux/archinstall#832]
Hi,

not sure if it's my config or something but it seems that when using pip (for the pypi package and the raw repo) profiles are not packaged and when running archinstall I am not prompted with the choices (Desktop etc.)

Is this expected?

**Comment by Torxed** [comment]
That is unexpected :) It used to be packaged. Most likely it's our switch to `pyproject.toml` and/or [flit](https://flit.readthedocs.io/en/latest/) that dropped the assets. We'll investigate why this happened.

For reference, this is the lines that are important: https://github.com/archlinux/archinstall/blob/240f688ccefa7bddb56efe5bc41a457c96792e42/pyproject.toml#L26-L27

**Comment by Torxed** [comment]
Found the issue, and it seems that `flit` doesn't follow symlinks *(any longer?)*.
Workaround:
```
cd ~/archinstall
rm archinstall/examples
rm archinstall/profiles
mv profiles/ archinstall/
mv examples/ archinstall/
pip install .
```
```console
[anton archinstall]$ ls -l archinstall/
total 16
drwxr-xr-x 1 anton anton  298 Jan 14 08:46 examples
-rw-r--r-- 1 anton anton 8578 Jan 14 08:46 __init__.py
drwxr-xr-x 1 anton anton  428 Jan 14 08:46 lib
-rw-r--r-- 1 anton anton   78 May 28  2021 __main__.py
drwxr-xr-x 1 anton anton  408 Jan 14 08:46 profiles
drwxr-xr-x 1 root  root    92 Oct 22 20:31 __pycache__
```
```console
pip install .
```
```python
>>> import archinstall
>>> archinstall.list_profiles()
{'awesome': {'path': '/home/anton/.local/lib/python3.10/site-packages/archinstall/profiles/awesome.py', ...}}
```

**Comment by Torxed** [comment]
I'm still waiting for upstream to fix `flit`.
I'm removing our milestone of fixing this in time for v2.3.1 so that I can release it tomorrow.

**Comment by Torxed** [comment]
In recent light, a discussion on the [flit project issues (522)](https://github.com/pypa/flit/issues/522) page the future of flit is being currently discussed, whether to remove or keep the existing build+publish pipeline. Or if flit should become a highly effective but simple builder. In which case we'll need to convert to `twine` for publishing and `pip` to install.

I think it's only fair to say that we should be using as much built-in stuff as possible, so perhaps we should beat the gun and swap straight away? I don't see our issue upstream being fixed any time soon.

**Comment by dylanmtaylor** [comment]
> In recent light, a discussion on the [flit project issues (522)](https://github.com/pypa/flit/issues/522) page the future of flit is being currently discussed, whether to remove or keep the existing build+publish pipeline. Or if flit should become a highly effective but simple builder. In which case we might need to convert our flit pipeline to `twine` for publishing and `pip` to install.
> 
> I think it's only fair to say that we should be using as much built-in stuff as possible, so perhaps we should beat the gun and swap straight away? I don't see our issue upstream being fixed any time soon.

I think we ought to look into switching build tools sooner rather than later
