### ISSUE TITLE
Plugins module not imported

### ISSUE THREAD

**Issue by ilario** [archlinux/archinstall#833]
Testing the master code I just got an error message due to `plugins` not being available here (I suppose it needs to be imported inside the very function?) as implemented in #821:
https://github.com/archlinux/archinstall/blob/240f688ccefa7bddb56efe5bc41a457c96792e42/archinstall/__init__.py#L178

**Comment by Torxed** [comment]
Yepp, some changes have been made to `__init__.py` over the last day or so.
This line should be moved outside of the locale scope function: https://github.com/archlinux/archinstall/blob/240f688ccefa7bddb56efe5bc41a457c96792e42/archinstall/__init__.py#L160

**Comment by Torxed** [comment]
Moved the import, and fixed in b533bd0 :) Thank you for reporting this! Apologies that it took some time. Work has been hectic.

**Comment by ilario** [comment]
Thank you for your great work!!!
