### ISSUE TITLE
archinstall formats as vfat but then doesn't understand it

### ISSUE THREAD

**Issue by jfabernathy** [archlinux/archinstall#834]
I know that vfat and fat32 are interchangeable because I can manually install Arch doing either mkfs.vfat /dev/sda1 or mkfs.fat -F32 /dev/sda1.

archinstall does not recognize vfat as a valid file system if you choose option 8 to select the file system for the partition.  In that case you have to use fat32.  Once you do that, and install your system, all is good.

The next time you boot the USB key and run archinstall it shows that same partition as vfat and if you leave it alone, the install will fail.
This is discussed on the forum at https://bbs.archlinux.org/viewtopic.php?id=272794

**Comment by Torxed** [comment]
We can probably use this helper function to map it for us: https://github.com/archlinux/archinstall/blob/7f9b7991e902489efb3501a98a7d6998ca15a0a5/archinstall/lib/disk/partition.py#L423-L428

or the safest bet for the `v2.3.1` release is to just double down on the if case here: https://github.com/archlinux/archinstall/blob/7f9b7991e902489efb3501a98a7d6998ca15a0a5/archinstall/lib/disk/partition.py#L286

**Comment by Torxed** [comment]
![screenshot2](https://user-images.githubusercontent.com/861439/149499361-16988e82-c451-4c9b-837d-e28f9be52f7a.jpg)

It now properly recognizes `vfat` as a format, but also `fat32` *(which will get converted to `vfat` internally)*.
