### ISSUE TITLE
(Query)  mount options in disk_layout ?

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#835]
Although all the infraestructure for executing mount command with options is in place (i'm using them now) i haven't found a formal way to specify them with the partition dictionary (the disk layout json). 
The usual way of mounting (via Installer.mount_ordered_layout) didn't used any (they do now, i put them), and I haven't yet found any other use of them, so existing code is of no help.
Anyone is using them it any other related project? and how? or did it have a planned, but never implemented place ?
As I need/wish them for **btrfs**, I've defined two new entries for the partition dictionary, **format_options** and **mount_options**. Before merging the code, any suggestions ?

I found an *options* keys , but it used is for filesystem creation (*mkfs*) , so they correspond to the first new key (compatibility code in place)
https://github.com/archlinux/archinstall/blob/3474176e641eed9ced37c918b157fd35c07dc388/archinstall/lib/disk/filesystem.py#L124

**Comment by Torxed** [comment]
They are used by people when modifying user disk layouts like so *(And I'm spitballing from the top of my head now)*:
```json
[
    {
        "/dev/sda": {
            "partitions": [
                {
                    "type": "primary",
                    "format": true,
                    "mountpoint": "/",
                    "options": ["casefold", "something-else"],
                    "filesystem": {
                        "format": "ext4"
                    }
                }
            ]
        }
    }
]
```

The placement of the options is a bit out of order if you ask me. I don't know why I placed it there to begin with. But the above example will make ext4 case insensitive for instance. And I would have liked the options to live under the `"filesystem": { ... }` block instead.

The full history can be found here: https://github.com/archlinux/archinstall/issues/380

**Comment by wllacer** [comment]
@torxed. 
1) Makes a lot of sense: There seems to be absolutely no problem to put the "format_options" were you want: under *filesystem* Just one line of code to touch, and already "backward compatible". The change is already done on my branch (btrfs-encrypt)
I just assume this is an advanced option, and for the time being implies editing the json file.
2) Any place where you would like to see the *mount_options*? I have the very specific problem with btrfs that i have to handle two sets of options, one for the whole partition (although specified at OS level by mount point) and one for each subvolume (sometimes it will be a mount option, sometimes not). This i why i choosed *mount_options* below partition (and general for all FS), and the *options* key in the new subvolume dictionary . The first is straightforward to change if desired, the second, not serious but not trivial.
BTW. This mount_options could answer thing like #717. We don't by default ... but you can mount the way you want with our tool

**Comment by wllacer** [comment]
A thing I forgot. We need both sets because format and mount can have two very different sets of options. F.i. the usual options with btrfs (*noatime* and *compress=...*) can not be specified at format time (it's how i discovered the line), and IIRC *casefold* can't be specified at mount time. 
We have one allocated ...
On a side note, if we allow mount options like *compress* or *nodatacow*, the usual complain that they only act for new files, and adding them later after an installation is not a good idea, falls from the discussion table; because we can do them from the start

**Comment by Torxed** [comment]
I agree with most of everything you suggested.
Perhaps something like this:
```json
{
    "/dev/sda": {
        "partitions": [
            {
                "type": "primary",
                "format": true,
                "mountpoint": "/",
                "options": ["casefold", "something-else"], # Keep this for backwards compatibility for a bit
                "filesystem": {
                    "format": "ext4",
                    "format_options": [
                        "casefold",
                        "something-else"
                    ]
                },
                "mount_options": [
                    "compress",
                    "noatime"
                ]
            }
        ]
    }
}
```

**Comment by wllacer** [comment]
This structure is more or less what i also prefer.
If noone has a better idea, it's what Will be implemented. Code is almost
done, but it is a busy week, so i can promise not a date.
Luckly, as there is no UI and only a line of Code involved, backward
compatibility is basically for free

**Comment by wllacer** [comment]
What would you think on both under filesystem ?
Filesystem:
     Format:
     Format_options:
     Mount_options:
Sorry about lack of formating. Writing from the phone

**Comment by Torxed** [comment]
No worries, formatting looks fine :)
The following looks good if I understood you correctly:
```json
{
    "/dev/sda": {
        "partitions": [
            {
                "type": "primary",
                "format": true,
                "mountpoint": "/",
                "options": ["casefold", "something-else"], # Keep this for backwards compatibility for a bit
                "filesystem": {
                    "format": "ext4",
                    "format_options": [
                        "casefold",
                        "something-else"
                    ],
                    "mount_options": [
                        "compress",
                        "noatime"
                    ]
                }
            }
        ]
    }
}
```
