### ISSUE TITLE
whats going on with partitions

### ISSUE THREAD

**Issue by Wolf10001000** [archlinux/archinstall#836]
when i opened gnome disks I have 6 partitions and when i opened disk usage analyzer it said i have 11.1 GB of space I don't fully understand how partitions work

**Comment by Wolf10001000** [comment]
![Screenshot from 2022-01-03 17-18-29](https://user-images.githubusercontent.com/97065979/147986727-6955e7a9-ccc3-40c9-91cc-8bed3b197471.png)

**Comment by Torxed** [comment]
This has been fixed in `v2.3.1` *(which is out on release candidate testing)* and in `master`.
It was a mistake on my end when doing math trying to compensate for offsets on partitions as they were created.
