### ISSUE TITLE
Feature request : save the current config at the end

### ISSUE THREAD

**Issue by arcolinuxz** [archlinux/archinstall#839]
What if we could save the current guided installation at the end and get a config file so that next time around we use that config to install Arch Linux? /var/log ...

Or even post it like on https://termbin.com.

It is not quite clear how to start an unattended installation.

**Comment by l4zy0n3** [comment]
It's already present, but sure, we need to document this https://github.com/archlinux/archinstall/blob/a68a23d10a08052091df9550d119810db94a2fdf/examples/guided.py#L195

**Comment by Torxed** [comment]
I agree that the documentation can be improved quite a in this regard.
We currently save:
 * `/var/log/archinstall/user_configuration.json`
 * `/var/log/archinstall/user_credentials.json`
 * `/var/log/archinstall/user_disk_layouts.json`
 * `/var/log/archinstall/install.log`
 * `/var/log/archinstall/cmd_history.txt`
 * `/var/log/archinstall/cmd_output.txt`

The first three is the guided installation, which you can re-use by doing:
```
archinstall --config user_config.json --disk_layouts=user_disk_layouts.json --creds user_credentials.json
```
And if you really want to ignore any steps you skipped, just add `--silent` and it will be a completely unattended installation.
You can also do, although I haven't tested this in ages:
```
archinstall unattended --profile https://domain.lan/your_custom_installation.py
```
And that will source the python file as the installation steps and run it unattended.
Those are the two options for doing unattended installs : ) Both of which should be described better in the docs, so I'll leave this issue open until I've gotten around to re-learning reST and it's syntax again. It's becoming a bigger priority to do so.

**Comment by Torxed** [comment]
I've updated the documentation to be more detailed oriented around this *(will be visible on the next build of the docs)*.
The section on log files now mention them all: https://archinstall.readthedocs.io/help/issues.html#log-files
The section on configurations also goes into detail about the different choices: https://archinstall.readthedocs.io/installing/guided.html#installing-directly-from-a-configuration-file

**Comment by Torxed** [comment]
Mia was quick to respond and approves of our intentions of asking users to post their logs to 0x0 :)
I'll create a new commit adding the suggestion to the log section of the documentation!
