### ISSUE TITLE
RFC: load_config into __init__.py

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#841]
When i updated the parameter handling, i moved the treatment of the disk_layouts file from *guided.load_config()* to *__init__,py*. It was simply a matter of putting all the config files handling in the same place, and the most logical one, because it will be always be executed whenever you use Archinstall.

Since then, i'm toying with the idea of moving everything from load_config() there also.

 On the positive side:
*  we can ensure that the **global** objects *archinstall.storage*, and *archinstall.arguments* are fully initialized when we access to them, 
* no user written script (or 3rd party application) misses some, which could be needed.
*  cost in memory and processing, seems basically trivial

On the negative side
* __init__.py grows too big and with more need of care, for such a critical piece of code
*  might be, we open the way to imprudent handling and unpredictable side-effects

What I don't know
*  What would be the consequences for 3rd party applications which use Archinstall ?
* Will it have an impact on the workflow in other scripts ?
 
What do you think of it ?

**Comment by Torxed** [comment]
As long as the processing of the arguments are optional and allow us to continue to use archinstall without `disk_layouts`, `config` and `creds` for instance. Some times I just want to do:
```
import archinstall
archinstall.list_profiles()
```
Without any parsing or loading of arguments. And just use it as a library.
So as long as that is possible, I'm more than fine with this change in a PR to tinker with :)
