### ISSUE TITLE
Only_hd.py not working (and may be other user written scripts)

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#851]
Some of the changes in the UI have  been NOT backwards compatible, and hit this script fully. 
I have to cook another version.
Once the new interface is stabilized, will be time to find a general solution for partial installs (only disk management, only config management, only package management,...) using the same script

**Comment by wllacer** [comment]
@svartkanin I'm having a bit of trouble with the new global menu. As I reduced the output to the needs of my script i got following scree
![Screenshot_20220107_131949](https://user-images.githubusercontent.com/10762720/148543369-b98be812-c4d7-439d-bab4-25ff3746c0b6.png)
Outside the obvious fact that I have no 5 configs missing, clicking install does not triggers any action. (from my early test it was clear that some configs -unidentified- are blockers).
Do you have any advice how can i manage it? Your code is too new for me

**Comment by Torxed** [comment]
I'll ping @svartkanin for this one, he's the menu-guru now hehe

**Comment by svartkanin** [comment]
> Outside the obvious fact that I have no 5 configs missing, clicking install does not triggers any action. (from my early test it was clear that some configs -unidentified- are blockers).
Do you have any advice how can i manage it? Your code is too new for me

@wllacer Yes I had this scenario on my mind when creating the global menu, but decided (maybe wrongly) to ignore it for now and wait until it happens, well didn't take that long :) 
So the `Install (X configs missing)` will refer to any of the configurations missing that have not been specified by either manual input or by the pre-loaded configuration. If you enabled configurations to be shown with the `selector.enable('XYZ') `  then that only means they will be displayed in the menu and filled with any pre-set configuration from the `archinstall.arguments[...]`. 
However, if the `archinstall.arguments` has nothing specified for a configuration value AND it was not enabled to be configured manually in the selection menu than it is simply a missing configuration that is required for the installation. I suspect in your example there are configurations that are not specified. 
I see a possible workaround to avoid confusion when using the menu, we can display all missing configurations automatically regardless if they have been enabled explicitly with `selector.enable('XYZ')` or not. This way they will be shown as mandatory. 
@Torxed @wllacer any thoughts on this?

**Comment by svartkanin** [comment]
> Some of the changes in the UI have been NOT backwards compatible, and hit this script fully.
I have to cook another version.
Once the new interface is stabilized, will be time to find a general solution for partial installs (only disk management, only config management, only package management,...) using the same script

@wllacer would you mind sharing how that script was executed so I can reproduce it?

**Comment by wllacer** [comment]
To reproduce the initial CV crash simply run
Sudo Python -m archinstall --script only_hd
The script is available in master since a week ago or so. But i don't think
there is very much interest on It, unless we would like to have a
compatibility layer, which is another story
The version i tested with the global menú is still local. Once i arrive
home i'll post a copy here.

**Comment by wllacer** [comment]
Here you have a copy of the only_hh.py i used to test the new menu. As you will see, is a striped down version of guided.py with minimal changes. -i've given up some stylistic decisions from the previous version, as it was starting to become a maintenance burden.
[only_hd.py.txt](https://github.com/archlinux/archinstall/files/7830733/only_hd.py.txt)

**Comment by wllacer** [comment]
@svartkanin Might be I have had a crucial misunderstanding. Having a look at selection_menu.py it seems that the code is a generic framework but specially tailored for guided.py. 
For a first version it is a good approach (we can test what is perfectible with the best posible good testbench ), but ... let's not create backward compatibility problems

**Comment by wllacer** [comment]
@svartkanin , @Torxed 
Is there a backward compatible way  calling *menu* ? 
If not, almost all the ask* functions at *user_interactions.py* have been converted to the menu interface, making any use of them  (?) unavailable to existing scripts without moving to the menu interface ... we've built a mess

**Comment by svartkanin** [comment]
@wllacer it is true that the selection menu class is currently tailored and tested for the guided script. However, most of the code is generic. I think the main part of interest is the function that verifies the missing fields, this is currently verifying the missing fields for the guided script. It should be fairly easy to make those dynamic so they can be set by the calling script, e.g. move them into the constructor. That way guided abd only_hd can set their own mandatory fields.


The selection menu is a layer on top of the new menu selection. It is not required for any script to use it to work. If pne doesn't wanna use it they can still set all the config values manually in the arguments after a user selected something.

> Is there a backward compatible way calling menu ?

I'm not sure what exactly you mean by a backwards compatible way of calling menu. The idea was to replace tge existing selection and multi selections, when I replaced them I did search in all the code for references to it and migrated those bur apparently I missed the ones from the only_hd script :( 
It should be relatively simple to migrate those as well though, by simply calling `Menu(...)` there's no need to use the selection menu if not wanted :)

**Comment by Torxed** [comment]
I think all the `ask_*` questions can be re-created for backwards compatibility by running `Menu(...).run()`. We can do that before v2.4.0 is released :)

**Comment by wllacer** [comment]
@svartkanin Forgetting about only_hd is pretty usual. It happens to me also ;-) The biggest problem is, that while there does not exist a public contract (an open and explicit API), Archinstall, and specially the script mechanism, is touted as a programmable tool. I can imagine other people doing what i did, using the ask* functions as building blocks of our own scripts; as there are not that many things that need user input for a tool like ours.  And here begins the trouble ... you rewrote the function instead making a new functional equivalent. Excellent, if the GlobalMenu were a "neutral" factory ... everyone would have been upgraded at no cost. But GlobalMenu is tied to the workflow of guided.py ; and  every script out there, which has reused the existing UI, finds itself  with is interface broken, and -as was my case- not a clue how to start. 
@Torxed  Not that easy, as the new versions share the name ... Unless there is a pythonic way to play  with two "function namespaces";  I think the best way would be to revert user_interactions.py to the previous version, add the newly written functions with a different name (f.i.. prefix them with m_) and make (at least) guided.py use the new ones.  More work, and creates a double set of functions, but they can be converged on the future. Why not, probably even before 2.4

**Comment by wllacer** [comment]
I have already gotten the last version of user_interaction.py. As I am the one that is complaining, i will take care of this backward compatibilty. Only alert me if you change anything at guided.py and user_interaction.py.

**Comment by svartkanin** [comment]
@wllacer I see the problem now, thanks for the clarification. If we're reverting back the old state completely and creating duplicate functionality we should potentially consider marking the old ones with a deprecated warning and giving a timeframe when they will be removed?

Also I'm not sure if it's necessary to revert all ask_* functions actually since they're implementing the new menu layout which shouldn't cause xny issues per se, or am I wrong there @wllacer ? It's more about the functions that got removed completely from the user_interactions.py i believe.

**Comment by Torxed** [comment]
I would say that as long as the `ask_*` functionality is the same *(more or less)* and they're called the same, we're not breaking backwards compatibility in the sense that people will still be able to call these functions from their own dotfile-installations.
That's the most important part. The guided installer we have some flexibility with, as it's not included in other projects or dotfiles *(i think)*. But functionality of those functions should stay intact as much as possible : )

**Comment by wllacer** [comment]
I did a tentative merge of both version this afternoon, so i have a fuller
picture.
The worst change has been, as @swartkanin says, the removal of the two
generic selection routines; as they don't have selfevident and ready made
alternatives
The degree of compatibility of the ask and select routines is one think i
want to check. Maybe there is a third way ... But i'll need a few days to
explore

**Comment by Torxed** [comment]
True, that would break backwards compatibility as well if `generic_select` is removed without an equal counterpart.
Some people might use those for asking their own questions.

**Comment by wllacer** [comment]
After discovering that mantaing a double interface *user_interactions.py*, is not that difficult, but a maintenance nightmare waiting to happen. I spent the rest of the morning, trying to assess the real impact of the changes. **I'm a lot more optimistic now**.

I've checked with older version of the distributed scripts, as, most probably, everyone starts from here. There might remain other issues; but the serious damage seems to be limited to the inability to use neither *generic_select* nor *generic_multi_select".  Looking at some equivalent functions, at least the first one seems pretty straightforward to recreate.

The rest of user inputs are either hardcoded inputs, or appear to do the UI upgrade by themselves (those functions which now instance Menu, i.e. the *ask_* and *select_* functions). 

IMHO, there is another catch, using the name *GlobalMenu* for the one tailored to *guided.py*, creates some confusion. Perhaps, just a rename will avoid some problems. And a general solution is worth exploring.

If you don't mind, i will try to tackle this issues.
BTW and totally off-topic. I definitively realized my current IDE (kdevelop) is  totally borked with Python 3.10 . Any recomendations?

**Comment by wllacer** [comment]
I created pr #857 with the generic_select and generic_multi_select functions recreated. It is the most important thing of this issue

**Comment by svartkanin** [comment]
@wllacer I had s look at the PR and left some comments, thanks a lot for addressing this so quickly!

Regarding the name of the GlobalMenu, I agree that it currently is only working for the guided script. However, i believe there's only a small update required - making the mandatory fields dynamic - so that it is actually generic. I have to double check that though since I'm not on a computer atm. But I'm also happy to rename it if it causes less confusion :)

Regarding 3.10 I'm using Pycharm and sublime so far no issues there

**Comment by Torxed** [comment]
> BTW and totally off-topic. I definitively realized my current IDE (kdevelop) is totally borked with Python 3.10 . Any recomendations?

Sadly I use sublime and nano, they work independent of what Python version you run so I wouldn't know : /

> I created pr #857

I'll have a look at the PR later today :)

**Comment by Torxed** [comment]
It seems that this has been mostly solved.
The menu system now works with `only_hd.py`, but it crashes during operation of adding partitions:
![screenshot](https://user-images.githubusercontent.com/861439/149513488-2d57389e-ad6e-40f6-a511-ec9e73478a55.jpg)

Not sure why `device_instance` appears to be `None`, as the log message right above shows the instance class initated.

**Comment by wllacer** [comment]
I added a PR #866 with a proposal for a less rigid GlobalMenu. Hope @Torxed  and @svartkanin will enjoy to rip it apart.
Will have a look on your problem. Any special steps or just simply a btrfs standard definition ?

**Comment by wllacer** [comment]
Just tested. It works on my machine (with a loop device) with master just have an hour new.
The first error (the raise args[1]) comes from an error in the number of parameters !?  
A wild guess :
https://github.com/archlinux/archinstall/blob/b533bd0553b094a201e11d47df8206cdd85c8f1c/examples/only_hd.py#L151-L154
Try avoiding the walrus assignment. Otherwise it makes no sense.
 Have you had a look at /var/log/archinstall/user_disk_layout.json ? ;-)

**Comment by Torxed** [comment]
Awesome, I'll merge it :)
