### ISSUE TITLE
Credentials don't get written out to file, if installation is interrupted before perform_installation() is called

### ISSUE THREAD

**Issue by l4zy0n3** [archlinux/archinstall#855]
![image](https://user-images.githubusercontent.com/21274221/148668609-9ec52bdb-5d59-4c2b-8dbe-d7615f96ea12.png)

**Comment by Torxed** [comment]
I've created a PR for this. I just want to run through it once before i commit it.
If it works I'll merge it into `v2.3.1` as well so that it's on the 2021-02-01 ISO.

**Comment by Torxed** [comment]
Code worked, tested in `master`.
Will test it against `v2.3.1-dev` as well in a bit :) Thank you for submitting this issue!
