### ISSUE TITLE
Support for systemd-boot reading common filesystems and EFI drivers

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#862]
systemd-boot is able to read common filesystems (ext4, btrfs etc.) (since 250).
* https://github.com/systemd/systemd/blob/main/NEWS
* https://github.com/systemd/systemd/issues/15617
* https://efi.akeo.ie/
* https://github.com/systemd/systemd/pull/20789

Support for preloading EFI drivers that are in /EFI/systemd/drivers/ *(such as filesystem EFI drivers https://efi.akeo.ie/)* (https://archlinux.org/packages/community/any/efifs/)

**Comment by hellosway** [comment]
I am trying to do this, but I cant find very much documentation on how to do it. Where is the folder for the drivers, and do you just format the XBOOTLDR partition to a supported filesystem with a driver or is ther something else you need to do.

**Comment by Torxed** [comment]
I haven't tried this myself, so I would have to tinker with it quite a bit.
I think I want HSM support in the disk encryption first, as that would give more usability :)

**Comment by dathide** [comment]
After install efifs, I ran
`# cp -r /usr/lib/efifs-x64/* /efi/EFI/systemd/drivers`
However, `bootctl install` doesn't generate the proper EFI boot entries, even though I have the proper files in /efi/loader/entries that indicate the label of my BTRFS disk and the proper subvolume.

**Comment by Torxed** [comment]
Possibly related: #1334

**Comment by dvzrv** [comment]
The specification can be found here: https://systemd.io/DISCOVERABLE_PARTITIONS/

I believe it should be implemented no matter what. All bootloaders will eventually support this or only support legacy boot.

**Comment by codefiles** [comment]
This may only  be intended to work with unified kernel images. That is the only way I have had success with this. I will look into this after addressing #1217.
