### ISSUE TITLE
Installation at master fails during pacstrap processing

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#868]
Log message is obvious 

```python
Getting mount information for device path /dev/loop0
Getting mount information for device path /dev/loop0
Installing packages: ['base', 'base-devel', 'linux-firmware', 'l', 'i', 'n', 'u', 'x', 'btrfs-progs', 'intel-ucode']
==> Creating install root at /mnt/archinstall
==> Installing packages to /mnt/archinstall

```
No need to show the actual crash

Somewhere along the line we are treating a string as a list :-()

**Comment by Torxed** [comment]
Yepp, `'l', 'i', 'n', 'u', 'x'` would be `linux`, I'm not sure if we're doing a `.split()` or `list(x)` on a string.

**Comment by wllacer** [comment]
It only happens if we don't enter the selection (as a matter of fact, there is no 'kernels' entry in the configuration file in this case).
Both situations didn't  occur with the old interface (I've kept a copy of the pre-GlobalMenu guided.py). I suspect we have two separated issues:
* the transference from the menu to archinstall.arguments with default values and no active selection, and
* And odd process at pacstrap when there is no value at archinstall.arguments
Good hunting ground ... But, let me worry about that, and enjoy your vacations i've read you are taking.

**Comment by Torxed** [comment]
I think it's because `default` value gets split because it's a string, and results are `list()`:ed :)

**Comment by Torxed** [comment]
Culprit: https://github.com/archlinux/archinstall/blob/b533bd0553b094a201e11d47df8206cdd85c8f1c/archinstall/lib/menu/menu.py#L74

I think at least.

**Comment by wllacer** [comment]
Not only. The culprit was at installer
https://github.com/archlinux/archinstall/blob/b533bd0553b094a201e11d47df8206cdd85c8f1c/archinstall/lib/installer.py#L105-L106
Instead of ```for kernels```it should have been ```for self.kernels```. Te funny thing the code is ancient (some 9 month according to blame)
I've overdone a bit and converted the parameter to list before in the PR 869. Now it works flawless (let's hope)

**Comment by Torxed** [comment]
Great work on identifying the other places as well. A lot of this code have followed along since the day the dinosaurs first developed this project hehe. I'm on vacation for a week, but I'll be around to hopefully merge PR's and fix urgent issues using my phone.

**Comment by wllacer** [comment]
## A bit of postmortem analysis
There is more to it. It's how the new *guided.py* treats some default values.
The root of the failure comes from this line
https://github.com/archlinux/archinstall/blob/31f55e8d6b0b6e7a7fe28433d7d305d58d5667a1/examples/guided.py#L195
We are passing a string where a list is expected. The bug sat, as i said, long time in the code . Why has it never been triggered?
* In the old version, the argument *kernels* always came with a value, and -the result of a multiple selection- as a list.
* In the new, if not selected in the menu, and despite its default value, it is not even specified. So we pass a string ('linux') where a list is expected.  Install.__init__() then triggers the bug.

I've built in this patch a mitigation to the error, and thus merits the merge, so people can work with master; but I haven't solved the cause (neither the line, nor the new behaviour). I hope to have a more comprehensive solution when you come back

**Comment by wllacer** [comment]
PR #871 is, I believe,  the general solution i talked about.
