### ISSUE TITLE
chile repo by default ?

### ISSUE THREAD

**Issue by RedCommand** [archlinux/archinstall#870]
i don't know if it is only me but archinstall use Chile repo by default. i leave in France so it is very slow to download (previous version download at 950mb/s but now i am a 100kb/s)

i tried to manually change repo but archinstall "auto detect best repo" and change back to Chile

PS: i am not on a real machine, i use proxmox (personnal server) with a vlan managed by pfsense

**Comment by Torxed** [comment]
This has to do with https://wiki.archlinux.org/title/reflector which is in charge (unless that's changed) for re-ranking mirrors. I can never remember if it's the reflector or https://wiki.archlinux.org/title/mirrors#Ranking_an_existing_mirror_list that is in charge during boot. But one of them ranks your mirrors according to the latest and greatest depending on speed. But it might be latency and not throughput.

So archinstall has the option to use the same mechanism, or select a mirror manually.
You can change it via command-line parameters too, `archinstall --mirror-region=France` and it should select something more suitable.

But in general, this is an upstream issue so I'll go ahead and close this unless there's a suggestion to deal with this better than relying on upstream optimizations :)

**Comment by RedCommand** [comment]
Thanks a lot !
