### ISSUE TITLE
Use an automated code formatter

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#872]
The code currently contains different formats which is understandable in an OSS project :) 
I personally use YAPF (https://github.com/google/yapf) in my projects which allows one to customize the code formatting. 
I think it would be very beneficial to use this to auto format the code when commiting, possibly with a commit hook

**Comment by Torxed** [comment]
I'm not against it, but I'm against intrusive tools.
`mypy` is even bordering untolerable forced changes, despite how well you configure it.

But I'll have a look at YAPF. For clarity, black is a no-go for me. It's way to strict :)

**Comment by svartkanin** [comment]
I totally share the view on black with you, i tried it once and never again :)
Yapf allows you to configure pretty much any formatting rule which gives you the mighty power of creating your own python ;)

**Comment by svartkanin** [comment]
Also since you mentioned mypy being a PITA, having a automatic custom but valid python formatter would probably eliminate some of the mypy issues as well then

**Comment by Torxed** [comment]
> I totally share the view on black with you, i tried it once and never again :) Yapf allows you to configure pretty much any formatting rule which gives you the mighty power of creating your own python ;)

This sounds like something I could agree on :) I like mypy for the fact that it catches a few data types. And I kind of like that it forces me to do less magical functions that "does everything".. I should think more about separation of duties and stuff, which is why I kinda like mypy.
