### ISSUE TITLE
Unless run with --advanced (on master), KeyError sys-language

### ISSUE THREAD

**Issue by panchoh** [archlinux/archinstall#873]
Hi!

Trying `3d30a4eb28bd84713571c52622cb88b6458076a5 @ master`, on real hardware.

If I simply run `archinstall`, it eventually dies with a `KeyError`, regarding a missing `sys-language`.
After examining the code, I realized that the registration of default values for both `sys-language` and `sys-locale` is dependent on `archinstall` being called with the `--advanced` parameter.

(So, as a workaround, invoke `archinstall --advanced`).

I reckon that the registration of the default values should happen even if `--advanced` is not supplied.

Wonderful project, thanks!!!

![photo_2022-01-16_11-13-12](https://user-images.githubusercontent.com/471059/149655772-4d71f4fa-fd5c-4fc4-8dd6-d796d0cda2f6.jpg)

**Comment by wllacer** [comment]
Running master branch?
I have the bug pinned down, but still not solved in full. I hope to have it today and a corresponding PR uploaded. I'll explain later

**Comment by wllacer** [comment]
@panchoh  Gracias por notificar el problema. 
The problem is that the new menu infraestructure, sometimes, if an item was not selected didn't transfer its default value. I tried to solve it in the patch you were testing, but my conditions were too restrictive, trying to keep the config area as leanest as possible. Thanks to your report, we have been able to get, i hope, this problem from the table

**Comment by Torxed** [comment]
Merged the code, it got me thinking where we store the arguments. Especially when we dump the config at the end as you mention, we don't want duplicate information and we don't want to mix creds, disk layout and config :)

**Comment by wllacer** [comment]
It was a good idea to centralize all config information at  *arguments* and let *storage* only for "environment variables".
The problem of "printing" the config info as three separate files, is that the solution is either:
* have an internal structure *arguments['config']* for config data, *arguments['disk_layout']* ... for disk_layout and *arguments['creds']* for credentials. I hate the idea  to migrate it, and clashes with the new menu implementation (it expects a flat structure)
* Not to "print" directly from *arguments* but do it from intermediate areas. A bit of not-so-elegant code at the script(s), and probably some rearranging, but a lot less impact, on the short term.

**Comment by wllacer** [comment]
More elegant than what i have now in the kitchen, but basically the  same. 
My solution loops only once thru the arguments dict, the former has to loop once per area.
The code comes from  a rather barroque version of guided.py i'm using to test and enhance my take on the new menu, and some other things (for which a selection menu is a godsend). I hope to have it ready in a couple of days (not much free time this week), and then port the results wherever they need to be.
But if you think it can not wait i could port it to guided and only_hd, on a fast lane
```python
def save_user_configurations():
	user_credentials = {}
	disk_layout = {}
	user_config = {}
	for key in archinstall.arguments:
		if key in ['!users','!superusers','!encryption-password']:
			user_credentials[key] = archinstall.arguments[key]
		elif key == 'disk_layouts':
			disk_layout = archinstall.arguments[key]
		elif key in ['abort','install','config','creds','dry_run']:
			pass
		else:
			user_config[key] = archinstall.arguments[key]

	user_configuration = json.dumps({
		'config_version': archinstall.__version__, # Tells us what version was used to generate the config
		**user_config, # __version__ will be overwritten by old version definition found in config
		'version': archinstall.__version__
	} , indent=4, sort_keys=True, cls=archinstall.JSON)

	with open("/var/log/archinstall/user_credentials.json", "w") as config_file:
		config_file.write(json.dumps(user_credentials, indent=4, sort_keys=True, cls=archinstall.UNSAFE_JSON))

	with open("/var/log/archinstall/user_configuration.json", "w") as config_file:
		config_file.write(user_configuration)

	if archinstall.arguments.get('disk_layouts'):
		user_disk_layout = json.dumps(disk_layout, indent=4, sort_keys=True, cls=archinstall.JSON)
		with open("/var/log/archinstall/user_disk_layout.json", "w") as disk_layout_file:
			disk_layout_file.write(user_disk_layout)

	print()
	print('This is your chosen configuration:')
	archinstall.log("-- Guided template chosen (with below config) --", level=logging.DEBUG)
	archinstall.log(user_configuration, level=logging.INFO)

	if archinstall.arguments.get('disk_layouts'):
		archinstall.log(user_disk_layout, level=logging.INFO)

``

**Comment by Torxed** [comment]
No rush, I'm back on Sunday earliest :)

**Comment by panchoh** [comment]
The issue is fixed now, so I'll close this.
Feel free to reopen if it makes sense (@wllacer, you seem to be thinking of a refactor).
At any rate, cheers!
