### ISSUE TITLE
Target /mnt/archinstall/mnt never got mounted properly....

### ISSUE THREAD

**Issue by saikatm** [archlinux/archinstall#904]
I have used archinstall script in the past it worked fine but now trying to install after many months facing this issue... tried 7/8 times today.

![Screenshot 2022-01-25 at 8 19 37 PM](https://user-images.githubusercontent.com/9909763/150999768-80382134-b027-4554-a77e-97bd334e0fdb.png)
![Screenshot 2022-01-25 at 8 19 21 PM](https://user-images.githubusercontent.com/9909763/150999791-9dfcbfde-1487-4a8d-b17f-05faca520ce9.png)

**Comment by Torxed** [comment]
Ah, your `partitions` definitions is a bit wrong.
It looks like you're using an older style of configuration.

Either tweak it, I think changing `"mountpoint": "/mnt/boot"` to `"mountpoint": "/boot"` and as well `"/mnt"` to `"/"` should fix it. If not, do `archinstall --dry-run` and re-generate a configuration to your liking and you should be good to go : )

We've had a few breaking changes to the configuration layout to support `btrfs` over the last couple of months.

**Comment by Torxed** [comment]
> @Torxed thanks for the tip I will try it but currently after running `archinstall` after selecting the keyboard layout the installer freezes and gives a timeout error as attached in the below screenshot. please help.. ![Screenshot from 2022-01-25 22-18-33](https://user-images.githubusercontent.com/9909763/151022924-02e3e62e-d662-4a25-9643-d26d088de2b8.png)

That's a strange issue, can you run `localectl set-keymap us` manually?

**Comment by saikatm** [comment]
Never faced this , just tried on kvm and vmware same issue on both platform 
![Screenshot 2022-01-26 at 12 15 35 PM](https://user-images.githubusercontent.com/9909763/151115858-3f8b34d2-7f27-45ff-8f4b-4dab18991799.png)

**Comment by Torxed** [comment]
Which ISO are you using? And have you done `pacman -Syu` by any chance?

**Comment by saikatm** [comment]
`archlinux-2022.01.01-x86_64.iso` no have not done any pacman -Syu, :/

**Comment by Torxed** [comment]
It's definitely an archiso issue, since we didn't implement this. I still want to help you, but I'm not sure what could have caused this.

Works fine here on the same iso. 64bit, KVM. Probably did about 100 installs yesterday.

Check dmesg and journalctl for clues?

**Comment by saikatm** [comment]
I think I found what is causing this.
1. rebooted the vm 
2. ran `localectl set-keymap us` worked fine 
3. **mounted the volumes `/ , /boot` then `localectl set-keymap us` did not work neither the `archinstall` , still giving same time out error.** 
here is a screen recording I did please watch, https://youtu.be/lVJHD9CssBQ
meanwhile I am downloading another iso.

**Comment by Torxed** [comment]
Ah, you essentially replaced your entire live operating system, with whatever was on `/dev/sda3` : )
There's no way for linux to recover or use applications in `/usr/bin` since you replaced `/` with emptyness.

I'm surprised it even allowed you to do so. Anyway, that's the issue. Do `mount /dev/sda3 /mnt/archinstall` instead if you want to re-use partitions as that's where we'll look for partitions :)

**Comment by saikatm** [comment]
thanks alot for giving your time and helping me out. :) I mounted `/dev/sda3 `to  `/mnt/archinstall` but having this error now please look at the configuration file. sorry for being such a noob. I have used the `archinstall` in the past it was really helpful and time saving that's why I do not want to manually install just want to use `archinstall`. 
![Screenshot 2022-01-26 at 1 06 10 PM](https://user-images.githubusercontent.com/9909763/151122516-be4bdb28-83d7-45ad-a96e-c19e65842ff5.png)
![Screenshot 2022-01-26 at 1 07 40 PM](https://user-images.githubusercontent.com/9909763/151122526-4f53097b-b0ff-4f88-a144-5b0e988ed045.png)
![Screenshot 2022-01-26 at 1 08 05 PM](https://user-images.githubusercontent.com/9909763/151122527-f79f2654-da17-4e98-9d93-c86f878d37cc.png)

**Comment by saikatm** [comment]
mounted `/dev/sda1` to `/mnt/boot `& `/dev/sda3` to `/mnt `as the arch installation guide, 
![Screenshot 2022-01-26 at 1 22 57 PM](https://user-images.githubusercontent.com/9909763/151124163-03e5488c-5464-4750-8517-73470f9378aa.png)
![Screenshot 2022-01-26 at 1 23 22 PM](https://user-images.githubusercontent.com/9909763/151124152-495a224f-f10d-4a7e-97f5-ba1fef3056fb.png)

**Comment by saikatm** [comment]
selecting the `archinstall` to create best suited partitions works fine and installer works but when I want to create the partition as my choice but does not work. I must be not mounting the partitions properly?

**Comment by Torxed** [comment]
My bad, should have been more clear hehe.
If you want to manually mount partitions to `/mnt/archinstall`, you can skip `"harddrives"` in `--conf` configuration.
And you don't need to supply `--disk_layouts` either, as archinstall *should*  auto-detect your partitions and the layout by looking in `/mnt/archinstall`.

**Comment by saikatm** [comment]
okay I think now I understood the mounting and fixed myself the issue reading the `archinstall` error and the configuration file. here is a video if someone faces the same issue and also for my self for future reference. @Torxed thanks alot for helping and creating the script.

**Comment by Torxed** [comment]
You're welcome and thank you! Glad it helped in the end hehe.

**Comment by saikatm** [comment]
I will be installing arch using `archinstall` on virtualbox every weekend to stay updated with the script. 😆

**Comment by saikatm** [comment]
can you identify what error is this? is the a error in the script? @Torxed 

![Screenshot 2022-01-26 at 3 07 56 PM](https://user-images.githubusercontent.com/9909763/151139208-81dbeba1-3082-4c43-9c26-81ce0e45ab21.png)
![Screenshot 2022-01-26 at 3 07 16 PM](https://user-images.githubusercontent.com/9909763/151139192-2fea598a-a74e-4ae8-ace1-ee7965276355.png)

**Comment by Torxed** [comment]
The first error is fixed in `v2.3.1` *(and in `master`)*.
It was related to an issue where we tried to sort partitions based on `mountpoint`, and some partitions didn't have one. *(for instance, partitions you don't want to use but are there, like the Windows partitions)*.

The second issue is *most* likely due to the "bug" in the ISO itself, I would have to see the log, but if you run `pacman -Sy archlinux-keyring` before running archinstall on the 2022-01-01 ISO everything should work just fine :)

**Comment by saikatm** [comment]
1. does running `pacman -S archinstall `pulls the latest v2.3.1 ?
2. thanks I will try `pacman -Sy archlinux-keyring`.

**Comment by Torxed** [comment]
> * does running `pacman -S archinstall `pulls the latest v2.3.1 ?
Not yet, I'm planning on releasing it tonight. For now, you'd have to follow https://github.com/archlinux/archinstall#using-a-live-iso-image but instead of `2.3.1-rc1` you'd have to use `2.3.1-dev` for the latest changes.

> * is there any way to get the log file from the VM ?

Yes, we have some instructions on the official docs: https://archinstall.readthedocs.io/help/issues.html
See the "tip" section, and other relevant information.

- :warning: **Be careful when posting things to pastebins, especially the `user_creds.json` file!**!

**Comment by saikatm** [comment]
here is the log sir @Torxed https://0x0.st/oo78.log

**Comment by Torxed** [comment]
That log appears to be from your issue:

![issue](https://user-images.githubusercontent.com/9909763/151122527-f79f2654-da17-4e98-9d93-c86f878d37cc.png)

Which you managed to get past I believe?

**Comment by saikatm** [comment]
@Torxed tried the `2.3.1-dev` branch the installation and everything worked perfectly like before. also in the current `archinstall` does not prompt to add a new user except the root user but `2.3.1-dev` does prompts. please merge it. 


https://github.com/archlinux/archinstall#:~:text=Using%20a%20Live%20ISO%20Image

**Comment by Torxed** [comment]
Prompting for new users will be in the next release as well :)
If it works in `v2.3.1-dev` then it will make it to `v2.31` and `v2.4.0 (master)` as well.
