### ISSUE TITLE
Could not strap in package:256

### ISSUE THREAD

**Issue by EzPecks** [archlinux/archinstall#907]
Hi everyone! I am rookie and i want to install Archlinux on my secondary PC. (AMD Ryzen 5 1600, PowerColor 6600XT, 16gb ram 2666mhz, 1TB WB green) Im used the "command" archinstall and followed all steps correctly. It start install, but in certain moment, it's stop, a lot of words in red and the last things its says is "Could not strap in package 256". I searched in a all web and nothing. Please if anyone knows how to solve this, can explain like im a fool.

Thanks you!

**Comment by dylanmtaylor** [comment]
Can you take a picture of the error and describe the configuration you chose?

**Comment by Torxed** [comment]
Usually `Could not strap in packages: 256` means there was a network related issue.
Probably a mirror that timed out or something similar, re-running the installer should work.

**Comment by timmypidashev** [comment]
@EzPecks run this command before you run archinstall: ```bash
pacman -Sy archlinux-keyring
```
I just had this issue as well, the keyring just needs to be synced because of some picky packages :) Also if a dev is reading this it would be nice if this is automatically included in the script. I can open a pr or something maybe.

**Comment by timmypidashev** [comment]
> Usually `Could not strap in packages: 256` means there was a network related issue. Probably a mirror that timed out or something similar, re-running the installer should work.

@Torxed usually but the op did not specify the full issue. The pacstrap did not happen as a result of package integrity failure

**Comment by Torxed** [comment]
> > Usually `Could not strap in packages: 256` means there was a network related issue. Probably a mirror that timed out or something similar, re-running the installer should work.
> 
> @Torxed usually but the op did not specify the full issue. The pacstrap did not happen as a result of package integrity failure

I don't know if pacstrapping in the keyring blindly is considered ok? If it is, we should definitely do it to avoid this issue. PR would be welcome :)

**Comment by timmypidashev** [comment]
Ok so I've spent a fair bit of of time researching this topic, and while it isnt that hard to just hard-code `pacman -Sy archlinux-keyring` in __init__ or elsewhere, this script aims to be more than that, offering customizable installations and acts as a library. I am not experienced enough to do this yet, although I do marvel at how efficiently designed this python package is(TY to the devs). Anyways I will back off this pr, although I do think it would be nice to have archinstall update the keyring for inexperienced users trying to get into arch(me as well).

**Comment by Torxed** [comment]
> Ok so I've spent a fair bit of of time researching this topic, and while it isnt that hard to just hard-code `pacman -Sy archlinux-keyring` in **init** or elsewhere, this script aims to be more than that, offering customizable installations and acts as a library. I am not experienced enough to do this yet, although I do marvel at how efficiently designed this python package is(TY to the devs). Anyways I will back off this pr, although I do think it would be nice to have archinstall update the keyring for inexperienced users trying to get into arch(me as well).

Thank you for the kind words, and you are correct in how archinstall is intended to work. The best placement would probably be in `examples/guided.py` right before `archinstall.Installer()` is invoked. I can fix a PR this week :)

**Comment by timmypidashev** [comment]
Awesome!

**Comment by EzPecks** [comment]
Hi! I followed your tips and solved the problem. I used `pacman -Sy archlinux-keyring` before `archinstall` and its work! Thanks you so much for all who took your time to help me

**Comment by dattmavis** [comment]
I had this issue on the latest ISO a few moments ago, for what it's worth. 

`pacman -Sy archlinux-keyring` fixed it. 

Just wanted to bring it to attention. Build: archlinux-2022.07.01-x86_64

**Comment by funky-tree** [comment]
So i tried `pacman -Sy archlinux-keyrinh` but i still get the same error

**Comment by Torxed** [comment]
> So i tried `pacman -Sy archlinux-keyring` but i still get the same error

Screenshot or error log would be appreciated :)

**Comment by SkySpnc** [comment]
getting this as well on a thinkpad x270. it simply says that /mnt/archinstall is not a directory

**Comment by Torxed** [comment]
> getting this as well on a thinkpad x270. it simply says that /mnt/archinstall is not a directory

Probably not relevant to this issue, but please post a traceback and `install.log` and I'll take a look at it :)

**Comment by Assault-OPS** [comment]
> @EzPecks run this command before you run archinstall:
> 
> ```shell
> pacman -Sy archlinux-keyring
> ```
> 
> I just had this issue as well, the keyring just needs to be synced because of some picky packages :) Also if a dev is reading this it would be nice if this is automatically included in the script. I can open a pr or something maybe.

This worked thank you so much
