### ISSUE TITLE
feature request for future release? the ability for the end user to configure if archinstall checks for a internet connection

### ISSUE THREAD

**Issue by mhussaincov93** [archlinux/archinstall#909]
hi,
here is my reasoning.
I want to add a custom repo to the image, and don't require the net check.
in other words I want to do a offline install with packages that would be required added via a custom repo.
archinstall currently performs a net check I believe?
could a question be added before the installer starts asking if it should perform the check?
or a flag be added maybe --no-net or something?
I realize that the new version will be out very very soon, so for a future release?
sorry for errors, i'm blind and use a screen reader.
thank you for considdering my request.
Majid

**Comment by dylanmtaylor** [comment]
The network check actually isn't a network check if that makes any sense. As long as pacman -Sy has an exit code of 0 which would be the case if all the repos defined are local/reachable, this would work offline. That said, it wouldn't be too hard to add a flag to skip this check.

**Comment by Torxed** [comment]
Fixed in master :) I do the same with archoffline, so that's one thing less to work around :)

**Comment by mhussaincov93** [comment]
hi,

thank you so much!

sorry for my delayed responce,

just literally awoke and had to check.

you all are the best :)

Majid
