### ISSUE TITLE
desktop profiles, replace pipewire-media-session with wireplumber, wireplumber seembs to be the newest replacement media-session replaceing pipewire-media-session

### ISSUE THREAD

**Issue by mhussaincov93** [archlinux/archinstall#912]
hi,
would it be possible to replace pipewire-media-session with wireplumber?
or, to make things flexable,
add a question in asking,
"would you like to use wireplumber or pipewire-media-session?
p.s
i'm using wireplumber currently.
wireplumber will remove pipewire-media-session and the systemd units.
a total replacement.
thank you for considdering my request!
Majid Hussain

**Comment by mhussaincov93** [comment]
hi,
found this about wireplumber
Two session managers are now available. The one pulled in by default pipewire-media-session is primitive, and is best when using PipeWire just for its basic functionality like screensharing. When using PipeWire as your system’s sound server, the maintainer recommends installing the more advanced WirePlumber instead.

**Comment by dylanmtaylor** [comment]
We probably should switch pipewire-media-session with wireplumber. It looks like the wireplumber package is the new official solution. https://archlinux.org/packages/extra/x86_64/wireplumber/

**Comment by dylanmtaylor** [comment]
> Fixed in `master` now, it won't make it to `v2.3.1` which is already in `[testing]` repo, but I think people can live with pipewire-media-session for that release.

Or just install wireplumber manually after install if they want it ;)

**Comment by mhussaincov93** [comment]
hi,

many thanks!

I was expecting this for next release :)

everyone working at archinstall towers are ausom!

Majid
