### ISSUE TITLE
Pacman errors when using archinstall

### ISSUE THREAD

**Issue by BigFonz** [archlinux/archinstall#925]
![error1](https://user-images.githubusercontent.com/60957399/151756401-f4bcd522-fbba-4c38-9a4f-7c9a1ad35828.jpg)
![error2](https://user-images.githubusercontent.com/60957399/151756405-ae6ac00f-8d98-4e1a-a056-dad83aea805c.jpg)
I'm trying to install arch with GNOME. It looks like an issue with a specific package so maybe I can make it install only the minimal packages?

**Comment by Torxed** [comment]
Did you run `pacman -S archlinux-keyring` before starting an installation?

**Comment by timmypidashev** [comment]
PR #917 has taken care of this issue. Would be nice to close this issue as it is stale.
