### ISSUE TITLE
DiskError: Could not get PARTUUID for /dev/sda1

### ISSUE THREAD

**Issue by wiloon** [archlinux/archinstall#926]
Error message:
`archinstall.lib.exceptions.DiskError: Could not get PARTUUID for /dev/sda1 using 'lsblk -J -o+PARTUUID /dev/sda1'`

And my `lsblk -J -o+PARTUUID /dev/sda1` output is 

        {
           "blockdevices": [
              {
                 "name": "sda1",
                 "maj:min": "8:1",
                 "rm": false,
                 "size": "484M",
                 "ro": false,
                 "type": "part",
                 "mountpoints": [
                     null
                 ],
                 "partuuid": "23ad838f-01"
              }
           ]
        }

Looks the lowercase "partuuid", not reconized.

**Comment by wiloon** [comment]
git clone and build latest version, fixed.

**Comment by Torxed** [comment]
Perfect :) the issue was actually caused by `partprobe` scheduling kernel updates on partition cache and `lsblk` not detecting and waiting for the cache to update which returns empty PARTUUID information. Fixed in new version as you noticed :)
