### ISSUE TITLE
Parallel downloads 

### ISSUE THREAD

**Issue by RedCommand** [archlinux/archinstall#930]
Why not activate parallel download by default or maby an option durring the setup ?

**Comment by Torxed** [comment]
We rely on the defaults used on the ISO. We could add an option for it and present it, sure.
But we are already getting one too many questions during install I think, so this would have to be up for discussion before we commit to this change.

Do people want one more menu entry? Or should a petition be started upstream to `archiso` and namely the `releng` configuration?

**Comment by l4zy0n3** [comment]
I think the petition way would be better, but this is just my humble opinion, as there would be no end to adding optional features as menu entries. Instead, for now, we could leverage plugins, custom commands to add these optional features to try to keep the installer modular and minimal. Installer stability and repeatable builds could be prioritised over adding non defaults. Again, just my 2 cents 🙂

**Comment by Torxed** [comment]
> I think the petition way would be better, but this is just my humble opinion, as there would be no end to adding optional features as menu entries. Instead, for now, we could leverage plugins, custom commands to add these optional features to try to keep the installer modular and minimal. Installer stability and repeatable builds could be prioritised over adding non defaults. Again, just my 2 cents slightly_smiling_face

I fully agree. I could perhaps wrap up a plugin example, consider it the same value `AUR` has to the normal packaging.
It's optional things people can hook into their systems. And a plugin in this case wouldn't be a bad idea :)

For the uninitiated, as a concept example: `archinstall --plugin https://github.com/Torxed/archinstall-paralell-downloads.py`

**Comment by edl2** [comment]
whichever of the three options it is i would say this is really important to the user experience and should not be ignored

**Comment by Torxed** [comment]
I'll ask around and see why it's not enabled by default in upstream archiso releng configuration.
I suspect there might be a reason. I too like the faster downloads using parallel downloads :)

**Comment by matteoturini** [comment]
forgot to enable parallel downloads, speeds suffering

**Comment by Torxed** [comment]
I've gotten some info on the topic. And one of the main reasons is for the mirrors to not suffer as much.
If everyone had X amount of parallel downloads enabled by default that would hog a lot of connection resources for mirrors.

One could probably argue that they would survive, but at some cost.
But that's the reason and we'll honor it. It's relatively easy to modify `/etc/pacman.conf` before running any installation, so users who know what they're doing can easily do so without additional menu entries.

I'm not ruling it out for the future, but I'll close this one for now as the recommendation is to not enable it for a wider audience :)

**Comment by godalming123** [comment]
What about adding an advanced section since it would make it so much easier for power users and clean up confusing options for regular users you could also add options for extra grub entry's or zram/zswap/no ram compression their

**Comment by loxoron218** [comment]
Any news about this?
I think it would be very cool if it was possible to configure _pacman.conf_ more easily and streamline things. I always use these command on post-installation:
```
sudo sed -i 's/#Color/Color/' /etc/pacman.conf
sudo sed -i 's/#VerbosePkgLists/VerbosePkgLists/' /etc/pacman.conf
sudo sed -i 's/#ParallelDownloads/ParallelDownloads/' /etc/pacman.conf
```
