### ISSUE TITLE
Keep memory of the current main menu

### ISSUE THREAD

**Issue by svartkanin** [archlinux/archinstall#946]
I open this issue as a tracker for this https://github.com/archlinux/archinstall/pull/874#issuecomment-1027940309
It will include a memory for the current selection of the main menu when entering a sub-menu and jump to the same selection again after exiting the sub-menu

**Comment by wllacer** [comment]
Seems we are working on the same subject. My problem was to keep the values from a config file from being destroyed when entering a selection. 
It seems possible to do now using the preset values at the menus (after PR #962). This is what i was about to do
At the GeneralMenu.exec_option, if you move from

https://github.com/archlinux/archinstall/blob/5990491292fb1a9b7dbd80af6109d9e71630a75c/archinstall/lib/menu/selection_menu.py#L302-L307
to 
```
		if selector.func:
			# TODO insert code to allow selector functions with preset value
			preval =self.options('selector_name').get_selection()
			result = selector.func(preval)

```
You can show the preset value. I think nothing more is needed on the GenealMenu.  But sadly the interface of all the selection functions have to be changed to accept a preset value, and all the ones which call Menu() or -i hope- TextInput.
Do you have another plan ?

**Comment by Torxed** [comment]
Great job on both of you tbh. You've been rocking out a solid menu system in less time than anyone could have hoped for! Keep it up!
