### ISSUE TITLE
Consider switching to doas instead of sudo

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#947]
I'm creating this issue so we can track the rising popularity of doas.
I'm not favouring one or the other, they probably both has their benefits.

[sudo](https://wiki.archlinux.org/title/sudo) has stood the test of time and is most likely still the most popular impersonator there is.
[doas](https://wiki.archlinux.org/title/Doas) main appeal appears to be that it's less bloated *(smaller)* and potentially more secure.

I still say we keep `sudo` for the foreseeable future, but if popular opinion is to switch.
We'll open a PR and close this one - or if it's down right just a BSD thing and we shouldn't muck about we'll close it with information why.

**Comment by dylanmtaylor** [comment]
Not really a fan of this one, `sudo` has been a standard for a very long time and works well. This would just be confusing to users.

**Comment by edl2** [comment]
The problem with this is that they are not comparable, doas if primarily used just for simple privilege escalation (which is why it is 'lightweight') but sudo has a wide variety of special use cases other than simple privilege escalation (why its 'bloated'), primarily used by servers and advanced users. Even if most people won't notice the differences, it is not a drop in replacement, which is why I would suggest making it an option in the installer, (sudo as default).

**Comment by dylanmtaylor** [comment]
> The problem with this is that they are not comparable, doas if primarily used just for simple privilege escalation (which is why it is 'lightweight') but sudo has a wide variety of special use cases other than simple privilege escalation (why its 'bloated'), primarily used by servers and advanced users. Even if most people won't notice the differences, it is not a drop in replacement, which is why I would suggest making it an option in the installer, (sudo as default).

I'm not 100% convinced this should be an option, it'll just add more complication and confusion. If we do add it, it should be using --advanced

**Comment by Torxed** [comment]
> > The problem with this is that they are not comparable, doas if primarily used just for simple privilege escalation (which is why it is 'lightweight') but sudo has a wide variety of special use cases other than simple privilege escalation (why its 'bloated'), primarily used by servers and advanced users. Even if most people won't notice the differences, it is not a drop in replacement, which is why I would suggest making it an option in the installer, (sudo as default).
> 
> I'm not 100% convinced this should be an option, it'll just add more complication and confusion. If we do add it, it should be using --advanced

Ironically `doas` is the lesser of the two in terms of being advance heh.
I get the reasoning tho and it will be a bit of a PITA to support both use cases code wise.

I only opened this ticket to spark a conversation, and so far I like the arguments :)

**Comment by dylanmtaylor** [comment]
Also worth considering -- the sheer number of programs and scripts that would break if sudo isn't there. Does doas provide a compatibility binary for sudo? What about less advanced users trying to follow a guide that has them running a sudo command?

**Comment by Torxed** [comment]
> Does doas provide a compatibility binary for sudo?

As far as I understand they are a `1:1` for basic usage. I've seen some people do `alias sudo='doas'` and for simple stuff it works. But as pointed out by edl2 they're not comparable and I can probably guarantee that doing such a thing will end up badly.

**Comment by AladW** [comment]
I have no idea why archinstall is trying to impose a particular privilege installation tool. Even adding add a default `sudoers` installation is questionable, but at least something that most desktop users already do. (`sudo` is installed on 97.3% of systems with `pkgstats`, `doas` on less than 0.30%)

https://pkgstats.archlinux.de/packages/sudo
https://pkgstats.archlinux.de/packages/doas

**Comment by edl2** [comment]
They aren't imposing anything...

> > The problem with this is that they are not comparable, doas if primarily used just for simple privilege escalation (which is why it is 'lightweight') but sudo has a wide variety of special use cases other than simple privilege escalation (why its 'bloated'), primarily used by servers and advanced users. Even if most people won't notice the differences, it is not a drop in replacement, which is why I would suggest making it an option in the installer, (sudo as default).
> 
> I'm not 100% convinced this should be an option, it'll just add more complication and confusion. If we do add it, it should be using --advanced

I think we should just leave it to the user

**Comment by Torxed** [comment]
I think imposing is the wrong word. But the stats is very compelling.
I like exploring new ideas - and this was one such occation.

But the overall feedback so far is pretty clear, so I'll go ahead and close this :)
I'd like to thank you all for the discussion before I do tho!

**Comment by JotaRandom** [comment]
> I have no idea why archinstall is trying to impose a particular privilege escalation tool. Even adding add a default `sudoers` installation is questionable, but at least something that most desktop users already do. `sudo` is installed on 97.3% of systems with `pkgstats`, `doas` on less than 0.30%.
> 
> https://pkgstats.archlinux.de/packages/sudo
> https://pkgstats.archlinux.de/packages/doas

Coming from the other issue about improving the user, this pkgstat and defaults archinstall has proven something: if something is installed by default it is more likely to become the predominant option and so does happen at the end... Like Windows and pre-installed OS or now sudo and sudo installed by default.

Also run0 is installed in 100% of machines (is part of systemd), should we switch to it and ship no sudo-doas-sudors? No, is obviously not the solution.

Also since this issue opened we now have a sudo-rs which seems like a drop in replacement for sudo and IF we want options and we are limit to u2f then sudo-rs may be worth looking if fill the needed.

Also I have moved to old pacstrap and we still have pacstrap as an option...

**Comment by h8d13** [comment]
@JotaRandom i think the main thing would be scratching u2f (temporarily), last time I tried I couldn't get to register them during install and sudoless password didn't work post install (this was a bit of time ago).

Aside from that it should be totally possible within changing 50-100 lines of code to make this configurable, but would require a bit of work you can clone it locally and search in `archinstall/archinstall/` term `sudo` to get a good overview of what you'd need.

It's actually not a bad idea. Would just need to cover the same ideas : enable sudo for `Users` section, `sudoers.d` equivalent, add to `wheel`. 

That's about it ! Then yeah comment u2f related code for testing
