### ISSUE TITLE
lets' get with the times! london is not part of the EU any more, could we move london away from Europe?

### ISSUE THREAD

**Issue by mhussaincov93** [archlinux/archinstall#952]
currently, when picking timezone I think it is it says Europe/london
but we are no longer in europe.
could all references to Europe/london be changed to London/uk instead?

**Comment by dylanmtaylor** [comment]
It's still in the continent of Europe, just not in the European Union. It should not be changed.

**Comment by mhussaincov93** [comment]
fare play.
