### ISSUE TITLE
A couple of issues around all_blockdevices()

### ISSUE THREAD

**Issue by wllacer** [archlinux/archinstall#954]
This are thing that should have had ready yesterday. But hadn't the time to test before you merged it
*Edited* The last question has solved itself (reading the doc  at the PR #949)
* I had a curious problem looking for subvolumes, as they didn't listed the ones i had mounted in my hard disk. It turned out i'm not using the "quasi-standard" @ notation. And it is what is assumed in the code at 
https://github.com/archlinux/archinstall/blob/d3b6832345c9b5cad54951d4f976ebdbfe59a086/archinstall/lib/disk/btrfs.py#L27-L29
If I changed the at sign b'@' at line 28 with an open bracket **[** it works like charm. The brackets are what define, for the OS, bind mounts (subvolume mount) and not the @
* btw, keeping the / at the name attribute in BtrfsSubvolume is confortable, but not mandatory
* Coming a bit up the stack i found
https://github.com/archlinux/archinstall/blob/d3b6832345c9b5cad54951d4f976ebdbfe59a086/archinstall/lib/disk/partition.py#L46-L49
Would that not be better an `@property` ? It could change during the lifetime of the object
* This is a double doubt i haven't been able to solve. At 
https://github.com/archlinux/archinstall/blob/d3b6832345c9b5cad54951d4f976ebdbfe59a086/archinstall/lib/disk/helpers.py#L289-L294
You use the recursive flag -R which returns a lot of entries (an a  bit complex). In my setups it runs *without recursion* without problem for nonencrypted devices, and outputs only the mountpoints at the partition exclusively., Testing the command with `/dev/mapper/ainstloop0p2` (an AI standard btrfs volume) worked perfectly without recursion. Why do you need the recursion flag ?
* the last one is a related and dumb question. I can not get the subvolumes in an encrypted partition, b.c. i don't know how to search for it, *Updated* Use DBMCryptDev.MapperDev.subvolumes
My code
```python
result = archinstall.all_blockdevices(partitions=True)
for res in sorted(result):
	print(res,type(result[res]),result[res])
        #print(get_info(res)
	if isinstance(result[res],archinstall.DMCryptDev):
            print(result[res].name,
                    result[res].path,
                    result[res].blockdev,
                    result[res].mountpoint,
                    result[res].filesystem,
                    result[res].MapperDev.partition)
            for mp in result[res]MapperDev.subvolumes:    #<== This did the trick
			print(res,'>',mp)
	#... some code to select what should be result and res in the following line
		for mp in archinstall.find_mountpoint(res):
			print(res,'>',mp)
		#for mp in result[res].subvolumes:
			#print(res,'>',mp)
``` 
~I know the list comes up if I do `find_mountpoint('/dev/mapper/ainstloop0p2')` but I can't find which attribute to use~
See output from the print stmt.
```
/dev/dm-0 <class 'archinstall.lib.disk.dmcryptdev.DMCryptDev'> DMCryptDev(dev_path='/dev/dm-0')
ainstloop0p2 /dev/mapper//dev/dm-0 None /mnt/archinstall btrfs Partition(path=/dev/loop0p2, size=7.5, PARTUUID=58fcab49-a7eb-40ca-8d27-663619f8e7f0, parent=/dev/loop0, fs=crypto_LUKS)

```
~Yes, i could append `/dev/mapper` to the name, but it is always the same string? OTOH using DMCryptDev.partition goes to the base device, and neither find_mountpoints, nor `.subvolumes` work. A good solution would be the DMCryptDev object to have a `subvolumes` parameter also and a `mount_path` parameter (or redefine the actual path one)
(Besides)~ The mountpoint is wrong. /mnt/archinstall is mounted to /dev/mapper/ainstloop0p2[/@] not to the device

**Comment by wllacer** [comment]
A couple more:
When I run the installation script in my system (I have qemu-nbd enabled and an encrypted partition somewhere) I get following list
```
Select one or more hard drives to use and configure                                                                                                                    
                                                                                                                                                                       
Use ESC to skip                                                                                                                                                        
                                                                                                                                                                       
                                                                                                                                                                       
> [ ] BlockDevice(/dev/loop0, size=8.0GB, free_space=1031kB+1049kB+1032kB, bus_type=None)                                                                              
  [ ] BlockDevice(/dev/nbd0, size=20.0GB, free_space=, bus_type=None)                                                                                                  
  [ ] BlockDevice(/dev/nbd1, size=0.0GB, free_space=, bus_type=None)                                                                                                   
... a number of nbd device
  [ ] BlockDevice(/dev/sda, size=465.8GB, free_space=4177kB+7680B, bus_type=sata)                                                                                      
  [ ] BlockDevice(/dev/sr0, size=1.0GB, free_space=, bus_type=sata)                                                                                                    
  [ ] DMCryptDev(dev_path='/dev/dm-0')                                                                                                                                 
(Press "/" to search)                        
```
* If I select the encrypted device, and later I select that i want to hand manage it (at disk_layouts) I get the error
```
 File "/home/werner/projects/archinstall/archinstall/lib/user_interaction.py", line 787, in select_disk_layout
    return select_individual_blockdevice_usage(block_devices)
  File "/home/werner/projects/archinstall/archinstall/lib/user_interaction.py", line 763, in select_individual_blockdevice_usage
    layout = manage_new_and_existing_partitions(device)
  File "/home/werner/projects/archinstall/archinstall/lib/user_interaction.py", line 590, in manage_new_and_existing_partitions
    "partitions": [partition.__dump__() for partition in block_device.partitions.values()]
AttributeError: 'DMCryptDev' object has no attribute 'partitions'

```
* If I select to do a  default partitioning it works until I have to print the layout, when I get
```
  ...
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DMCryptDev is not JSON serializable
```
I could suppress it from the selection screen, but I don't know what plans you have with them. Anyhow, probably the DMCryptDev object should  have an interface more in line with a standard (disk/partition ¿?). Else we'll be handling a lot ot error codes like this

and BTW anyone knows how to supress all this non-allocated qemu-nbd devices ? in another place i've gotten rid of all devices with size == 0, but this info is not available until I instanciate the BlockDevice

**Comment by svartkanin** [comment]
@Torxed that should be resolved as well now :)
