### ISSUE TITLE
For 2.4.0, if it's a BIOS system and only GRUB is available, default the selection to grub-install

### ISSUE THREAD

**Issue by dylanmtaylor** [archlinux/archinstall#970]

**Comment by Torxed** [comment]
I agree, and overall we should populate the empty selections with default values so that there is no “x missing” on the install button. Let’s default to systemd-boot when possible and default to host name “archinstall” for instance.

**Comment by dylanmtaylor** [comment]
> I agree, and overall we should populate the empty selections with default values so that there is no “x missing” on the install button. Let’s default to systemd-boot when possible and default to host name “archinstall” for instance.

Maybe 'archlinux' as the hostname? :) It's the target system we're talking about here, not the installer
