### ISSUE TITLE
Look in to enabling SMART for drives that support it

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#98]
Something like `smartctl --smart=on --offlineauto=on --saveauto=on /dev/sda` where `archinstall.hardware.detectSmart()` finds drives that support it (to extend drive lifetime if possible).

**Comment by grazzolini** [comment]
These are the steps we use on Arch servers: https://gitlab.archlinux.org/archlinux/infrastructure/-/blob/master/roles/common/tasks/main.yml#L25
