### ISSUE TITLE
'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Half-Shot** [archlinux/archinstall#982]
Was setting this up on a VM, setting `/` to be the full size of the disk minus the boot partition, and it exploded after starting the process.

![image](https://user-images.githubusercontent.com/2072976/153748001-c651c6f5-533e-46a8-b99b-b331339f6aa4.png)

**Comment by Torxed** [comment]
Thanks for reporting this, will see where and why we’re trying to use the uuid incorrectly.

**Comment by Half-Shot** [comment]
I tried the process again, this time leaving the partition table with defaults (seperate parts for / and /home) and it was absolutely fine.

**Comment by Torxed** [comment]
This has been fixed in v2.3.2.
The issue was a bit hidden, it mainly came when drives were blanked and parted couldn't create partitions - causing UUID to be empty. But it also happened when manual formatting was done due to a logical error.

Thank you for reporting it :)
