### ISSUE TITLE
Add sudoers.d file instead of appending to sudoers

### ISSUE THREAD

**Issue by KenJyn76** [archlinux/archinstall#985]
A cleaner way to add a user as a superuser would be to create a file in /etc/sudoers.d, and add the %user ALL=(ALL) ALL syntax in that file. I'd make a PR, but I'm terrible with git :)

**Comment by Torxed** [comment]
i like this idea a lot. it would also mean that plugins and stuff can place for instance temporary build users there while building packages in plugins :D

**Comment by eugeniopacceli** [comment]
An attempt was made :p

**Comment by Torxed** [comment]
Functionality was added in #1025
