### ISSUE TITLE
Add support for ZFS

### ISSUE THREAD

**Issue by Torxed** [archlinux/archinstall#99]
This goes towards #46. But not only should we support more custom partitioning schemes.
We'll also add ZFS support among other file systems and/or volume managers.

**Comment by nas-faq** [comment]
Is it supposed to add root on ZFS as well?

**Comment by Torxed** [comment]
> Is it supposed to add root on ZFS as well?

That's the plan and It's coming. At least in a basic capacity as well as #124 which should give more degrees of freedom with subvolumes and stuff. ZFS and BTRFS users tend to want pretty advance setups, curenttly I we can only cater to those who are ok with using simpler setups.

**Comment by Foxboron** [comment]
Wait, how do you plan on supporting this? The zfs packages won't be added to the repositories because of the well known license restrictions. The other options is intentionally supporting the archzfs repositories (which archinstall should *not* be doing) or AUR packages, which is again unsupported.

**Comment by Torxed** [comment]
> Wait, how do you plan on supporting this? The zfs packages won't be added to the repositories because of the well known license restrictions. The other options is intentionally supporting the archzfs repositories (which archinstall should _not_ be doing) or AUR packages, which is again unsupported.

This occurred to me the other day as well when we were discussing OpenZFS vs ZFS.
It poses a big road block and I currently have no solution/answer to this. As you mentioned, AUR and custom mirrors are unsupported.

**Comment by Foxboron** [comment]
That lines up with what I was expecting. It would be weird if we where to suddenly allow custom repositories and modifications to the `archlinux-keyring` intermixed with supported filesystems.

Regardless, improving the partitioning stuff and having this as an external thing seems like a completely decent solution.

**Comment by Torxed** [comment]
I'm closing this as there's no way we can support this in the main repository (due to AUR being a external dependency).
However, #393 and #369 - both trying to solve #368 - will allow for external plugins that are allowed to do these kinds of AUR supported features.

It's worth mentioning, that plugin support is offered as an API for people who know and are willing to spend the time to write their own .dotfile installation scripts - and need these types of external dependencies. It's currently being debated which plugin support we should go for and it's not really a priority to develop at the moment (because of partitioning issues and other more urgent stuff). But feel free to chime in :)
