### ISSUE TITLE
vmware pacman fail

### ISSUE THREAD

**Issue by imanbarati** [archlinux/archinstall#990]
![image](https://user-images.githubusercontent.com/40170427/154622293-eb630bcb-b897-4c64-9f8d-0c33c3639634.png)
tried 10 times

**Comment by imanbarati** [comment]
https://0x0.st/o8tr.log
Hardware model detected: VMware, Inc. VMware Virtual Platform; UEFI mode: False
Processor model detected: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
Memory statistics: 129524 available out of 699688 total installed
Virtualization detected: vmware; is VM: True
Graphics devices detected: dict_keys(['VMware SVGA II Adapter'])
Disk states before installing: {'blockdevices': [{'name': 'loop0', 'fstype': 'squashfs', 'fsver': '4.0', 'label': None, 'uuid': None, 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/airootfs'], 'type': 'loop', 'size': '657.4M'}, {'name': 'sda', 'fstype': None, 'fsver': None, 'label': None, 'uuid': None, 'fsavail': None, 'fsuse%': None, 'mountpoints': [None], 'type': 'disk', 'size': '8G'}, {'name': 'sr0', 'fstype': 'iso9660', 'fsver': 'Joliet Extension', 'label': 'ARCH_202202', 'uuid': '2022-02-01-17-06-09-00', 'fsavail': '0', 'fsuse%': '100%', 'mountpoints': ['/run/archiso/bootmnt'], 'type': 'rom', 'size': '812.3M'}]}
Testing connectivity to the Arch Linux mirrors ...
Unknown blockdevice type for /dev/sr0: rom
Hardware time and other post-configuration steps might be required in order for NTP to work. For more information, please check the Arch wiki.
-- Guided template chosen (with below config) --
{
    "audio": null,
    "bootloader": "grub-install",
    "dry-run": false,
    "harddrives": [],
    "hostname": "1",
    "kernels": [
        "linux"
    ],
    "keyboard-layout": "us",
    "mirror-region": {},
    "nic": "Copy ISO network configuration to installation",
    "ntp": true,
    "packages": [],
    "profile": {
        "path": "/usr/lib/python3.10/site-packages/archinstall/profiles/minimal.py"
    },
    "script": "guided",
    "swap": true,
    "sys-encoding": "utf-8",
    "sys-language": "en_US",
    "timezone": "UTC",
    "version": "2.3.1"
}
Waiting for automatic mirror selection (reflector) to complete.
Installing packages: ['base', 'base-devel', 'linux-firmware', 'linux', 'grub']
Could not strap in packages: ==> ERROR: /mnt/archinstall is not a directory

Could not strap in packages: 256
Pacstrap failed. See /var/log/archinstall/install.log or above message for error details.

**Comment by dylanmtaylor** [comment]
> i've never seen this pacman error before:
> 
> ```
> /usr/bin/pacstrap: line 374:  2059 Killed                  unshare --fork --pid pacman -r "$newroot" $pacmode "${pacman_args[@]}"
> ```

Potentially killed by the kernel due to an OOM condition?

**Comment by Torxed** [comment]
You are probably correct!
@imanbarati what's the specs on the machine?

**Comment by imanbarati** [comment]
hp 4540s
typical 768mb ram vmware 16

**Comment by dylanmtaylor** [comment]
> hp 4540s typical 768mb ram vmware 16

Is it possible to try allocating say 2 GB of RAM just to see if it helps? You can revert the ram change after installation, I just want to see if it corrects this issue for you.

**Comment by imanbarati** [comment]
gave it 3 gb ram issue is no more

**Comment by imanbarati** [comment]
there is another problem wayland session doesn't list root and a bigger problem there is no internet

**Comment by Torxed** [comment]
> there is another problem wayland session doesn't list root and a bigger problem there is no internet

Did you chose btrfs?
Did you select one of the nerwork config options during install? :)
