### ISSUE TITLE
server installation: leaving blank for a minimal selection loops

### ISSUE THREAD

**Issue by j-james** [archlinux/archinstall#999]
At one point in archinstall after selecting the "server" profile, you're prompted to pick which servers to install with the message: `Choose which servers to install and enable (leave blank for a minimal installation)`.

Leaving this blank and pressing enter quickly flashes an error and loops you back to the same question again.

**Comment by j-james** [comment]
Also, `ctrl+c` no longer works - I'm not sure if this is because something with archinstall crashed, or if archinstall just doesn't respect it at this point in the install.

**Comment by Torxed** [comment]
I'll have a look :)

**Comment by svartkanin** [comment]
@Torxed we can close this as it should be resolved with the new profile manger
